## setup OS_LIBS
set (OS_LIBS)

# if (APPLE)
   # FIND_LIBRARY(CARBON_LIBRARY Carbon )
   # FIND_LIBRARY(COCOA_LIBRARY Cocoa )
   # FIND_LIBRARY(COREMIDI_LIBRARY CoreMidi )
   # FIND_LIBRARY(IOKIT_LIBRARY IOKit )
   # FIND_LIBRARY(AGL_LIBRARY AGL )
   # FIND_LIBRARY(OPENGL_LIBRARY OpenGL )
   # FIND_LIBRARY(APP_SERVICES_LIBRARY ApplicationServices )
   # FIND_LIBRARY(COREAUDIO_LIBRARY CoreAudio )
   # FIND_LIBRARY(COREFOUNDATION_LIBRARY CoreFoundation )
   # FIND_LIBRARY(APP_KIT_LIBRARY AppKit )
   # FIND_LIBRARY(WEB_KIT_LIBRARY WebKit )
   # FIND_LIBRARY(QTKIT_LIBRARY QTKit )
   # FIND_LIBRARY(AUDIOTOOLBOX_LIBRARY AudioToolbox )
   # FIND_LIBRARY(QUARTZCORE_LIBRARY QuartzCore )
   # FIND_LIBRARY(ACCELERATE_LIBRARY Accelerate )
   # FIND_LIBRARY(AUDIOUNIT_LIBRARY AudioUnit)
   # MARK_AS_ADVANCED (
	# COREAUDIO_LIBRARY
	# COREFOUNDATION_LIBRARY
	# CARBON_LIBRARY
	# COCOA_LIBRARY
	# COREMIDI_LIBRARY
	# IOKIT_LIBRARY
	# QTKIT_LIBRARY
	# AGL_LIBRARY
	# OPENGL_LIBRARY
	# APP_KIT_LIBRARY
	# WEB_KIT_LIBRARY
	# APP_SERVICES_LIBRARY
	# AUDIOTOOLBOX_LIBRARY
	# QUARTZCORE_LIBRARY
	# ACCELERATE_LIBRARY
	# AUDIOUNIT_LIBRARY
# )

   # list (APPEND OS_LIBS ${COREAUDIO_LIBRARY} ${COREFOUNDATION_LIBRARY} ${APP_SERVICES_LIBRARY} ${APP_KIT_LIBRARY} ${WEB_KIT_LIBRARY} ${CARBON_LIBRARY} ${COCOA_LIBRARY} ${COREMIDI_LIBRARY} ${IOKIT_LIBRARY} ${QTKIT_LIBRARY} ${AGL_LIBRARY} ${OPENGL_LIBRARY} ${AUDIOTOOLBOX_LIBRARY} ${QUARTZCORE_LIBRARY} ${ACCELERATE_LIBRARY} ${AUDIOUNIT_LIBRARY})

# endif (APPLE)

# option(WITH_PTHREADS "use pthreads library in 3rdPartyLibs/pthreads-Win32" OFF)
# if (WITH_PTHREADS)
    # FIND_PACKAGE ( pthreads REQUIRED )
    # list (APPEND OS_LIBS ${PTHREAD_LIBRARY})
# endif (WITH_PTHREADS)
