ACA: ComputeBeatHisto.cpp File Reference
ComputeBeatHisto.cpp File Reference
#include "AcaAll.h"
#include <iostream>
#include <fstream>
#include <ctime>
#include "BeatHisto.h"
Functions
void showClInfo ()
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
< file paths
< block length in samples
< hop length in samples
< BeatHisto result
Definition at line 17 of file ComputeBeatHisto.cpp.
{
    std::string             sInputFilePath,                 //!< file paths
        sOutputFilePath;
    int iBlockLength = 0, //!< block length in samples
        iHopLength = 0; //!< hop length in samples
    int iBeatHistoDimension = 0;
    clock_t time = 0;
    CBeatHistoIf* pCInstance = 0;
    CBeatHistoIf::BeatHisto_t eBeatHistoIdx = CBeatHistoIf::kBeatHistoFft;
    float* pfBeatHisto = 0; //!< BeatHisto result
    std::fstream hOutputFile;
    showClInfo();
    //////////////////////////////////////////////////////////////////////////////
    // parse command line arguments
    if (argc < 2)
    {
        cout << "Missing audio input path!" << endl;
        cout << "Expected Synopsis: inputfile [outputtxtfile] [blocksize] [hopsize]" << endl;
        return -1;
    }
    else
    {
        sInputFilePath = argv[1];
        sOutputFilePath = (argc < 3) ? sInputFilePath + ".txt" : argv[2];
        iBlockLength = (argc < 4) ? 1024 : std::stoi(argv[3]);
        iHopLength = (argc < 5) ? 8 : std::stoi(argv[4]);
    }
    //////////////////////////////////////////////////////////////////////////////
    // initialize BeatHisto instance
    CBeatHistoIf::create(pCInstance, sInputFilePath, iBlockLength, iHopLength);
    iBeatHistoDimension = pCInstance->getNumBins(eBeatHistoIdx);
    //////////////////////////////////////////////////////////////////////////////
    // open the output text file
    hOutputFile.open(sOutputFilePath.c_str(), std::ios::out);
    if (!hOutputFile.is_open())
    {
        cout << "Text file open error!";
        CBeatHistoIf::destroy(pCInstance);
        return -1;
    }
    //////////////////////////////////////////////////////////////////////////////
    // allocate memory
    pfBeatHisto = new float[iBeatHistoDimension];
    if (!pfBeatHisto)
    {
        CBeatHistoIf::destroy(pCInstance);
        hOutputFile.close();
        return -1;
    }
    time = clock();
    //////////////////////////////////////////////////////////////////////////////
    // compute spectrogram
    cout << "\n1. computing BeatHisto..." << endl;
    pCInstance->compBeatHisto(pfBeatHisto);
    cout << "\n BeatHisto computation done in: \t" << (clock() - time) * 1.F / CLOCKS_PER_SEC << " seconds." << endl;
    time = clock();
    //////////////////////////////////////////////////////////////////////////////
    // file writing
    cout << "\n2. writing output file..." << endl;
    for (auto k = 0; k < iBeatHistoDimension; k++)
    {
        hOutputFile << pfBeatHisto[k] << endl;
    }
    cout << "\n writing done in: \t" << (clock() - time) * 1.F / CLOCKS_PER_SEC << " seconds." << endl;
    //////////////////////////////////////////////////////////////////////////////
    // clean-up (close files, delete instances, and free memory)
    CBeatHistoIf::destroy(pCInstance);
    hOutputFile.close();
    delete[] pfBeatHisto;
    pfBeatHisto = 0;
    // all done
    return 0;
}
References CBeatHistoIf::compBeatHisto(), Catch::cout(), CBeatHistoIf::create(), CBeatHistoIf::destroy(), CBeatHistoIf::getNumBins(), CBeatHistoIf::kBeatHistoFft, and showClInfo().
showClInfo()
void showClInfo ()
Definition at line 117 of file ComputeBeatHisto.cpp.
{
    cout << "ACA v" << getAcaVersion() << ": Demo Executable for Beat Histogram Extraction" << endl;
    cout << "Build date: " << getAcaBuildDate() << endl;
    cout << "(c) 2022 by Alexander Lerch" << endl;
    cout << "Synopsis: ComputeBeatHistoFunction inputwavfile [outputtxtfile] [blocksize] [hopsize]" << endl;
    cout << endl;
    return;
}
References Catch::cout(), getAcaBuildDate(), and getAcaVersion().
Referenced by main().