ACA: CFeatureSpectralPitchChroma Class Reference
CFeatureSpectralPitchChroma Class Reference
Public Member Functions
CFeatureSpectralPitchChroma (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureSpectralPitchChroma ()
Error_t compFeature (float *pfFeature, const float *pfInput) override
int getFeatureDimensions () const override
bool hasAdditionalParam () const override
Error_t setAdditionalParam (float fParamValue) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfInput)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Member Functions
CFeatureSpectralPitchChroma ()
CFeatureSpectralPitchChroma (const CFeatureSpectralPitchChroma &that)
disallow copy construction
CFeatureSpectralPitchChroma & operator= (const CFeatureSpectralPitchChroma &c)
void genPcFilters_ ()
Private Attributes
const int m_iNumPitchClasses = 12
const float m_fA4 = 440.F
int m_iNumOctaves = 4
float ** m_ppfH = 0
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume it's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
Definition at line 507 of file FeatureFromBlock.cpp.
Constructor & Destructor Documentation
CFeatureSpectralPitchChroma() [1/3]
CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 510 of file FeatureFromBlock.cpp.
                                                                                                     : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        // alloc transfer function memory
        CMatrix::alloc(m_ppfH, m_iNumPitchClasses, iDataLength);
        genPcFilters_();
    };
References CMatrix::alloc(), genPcFilters_(), m_iNumPitchClasses, and m_ppfH.
~CFeatureSpectralPitchChroma()
virtual CFeatureSpectralPitchChroma::~CFeatureSpectralPitchChroma () inline virtual
Definition at line 518 of file FeatureFromBlock.cpp.
    {
        CMatrix::free(m_ppfH, m_iNumPitchClasses);
    };
References CMatrix::free(), m_iNumPitchClasses, and m_ppfH.
CFeatureSpectralPitchChroma() [2/3]
CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma () inline private
Definition at line 571 of file FeatureFromBlock.cpp.
{};
CFeatureSpectralPitchChroma() [3/3]
CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma (const CFeatureSpectralPitchChroma & that) private
disallow copy construction
Member Function Documentation
compFeature()
Error_t CFeatureSpectralPitchChroma::compFeature (float * pfFeature, const float * pfInput) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfInput input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 523 of file FeatureFromBlock.cpp.
    {
        assert(pfFeature);
        assert(pfInput);
        CVectorFloat::setZero(pfFeature, m_iNumPitchClasses);
        for (auto p = 0; p < m_iNumPitchClasses; p++)
        {
            // we could do this nicer with CVectorFloat::mulScalar if we allocated memory
            for (auto k = 0; k < m_iDataLength; k++)
            {
                pfFeature[p] += m_ppfH[p][k] * (pfInput[k] * pfInput[k]);
            }
        }
        float fSum = CVectorFloat::getSum(pfFeature, m_iNumPitchClasses);
        if (fSum > 0)
            CVectorFloat::mulC_I(pfFeature, 1.F/fSum, m_iNumPitchClasses);
        return Error_t::kNoError;
    };
References CVectorFloat::getSum(), kNoError, CFeatureFromBlockIf::m_iDataLength, m_iNumPitchClasses, m_ppfH, CVectorFloat::mulC_I(), and CVectorFloat::setZero().
genPcFilters_()
void CFeatureSpectralPitchChroma::genPcFilters_ () inline private
< C4
Definition at line 575 of file FeatureFromBlock.cpp.
    {
        const float fStartPitch = 60; //!< C4
        float fMid = CConversion::convertMidi2Freq(fStartPitch, m_fA4);
        //sanity check: reduce number of octaves if highest freq is higher than half fs
        while (fMid * std::exp2(m_iNumOctaves) > m_fSampleRate / 2)
            m_iNumOctaves--;
        if (m_iNumOctaves <= 0)
            return;
        for (auto p = 0; p < m_iNumPitchClasses; p++)
        {
            const float fQuarterToneRatio = 1.02930223664349F;
            float afBoundFreqs[2] = { fMid / fQuarterToneRatio,
                fMid * fQuarterToneRatio };
            for (auto o = 0; o < m_iNumOctaves; o++)
            {
                // get indices from freqs
                const int aiBoundIdx[2] = { static_cast<int>(CConversion::convertFreq2Bin(afBoundFreqs[0], (m_iDataLength - 1) * 2, m_fSampleRate)) + 1,
                    static_cast<int>(CConversion::convertFreq2Bin(afBoundFreqs[1], (m_iDataLength - 1) * 2, m_fSampleRate)) };
                // set transfer function
                CVectorFloat::setValue(&m_ppfH[p][aiBoundIdx[0]], 1.F / (aiBoundIdx[1] - aiBoundIdx[0] + 1), static_cast<long long>(aiBoundIdx[1]) - aiBoundIdx[0] + 1);
                // proceed to next octave
                for (auto i = 0; i < 2; i++)
                    afBoundFreqs[i] *= 2.F;
            }
            // proceed to next pitch class
            fMid *= fQuarterToneRatio * fQuarterToneRatio;
        }
    }
References CConversion::convertFreq2Bin(), CConversion::convertMidi2Freq(), m_fA4, CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, m_iNumOctaves, m_iNumPitchClasses, m_ppfH, and CVectorFloat::setValue().
Referenced by CFeatureSpectralPitchChroma(), and setAdditionalParam().
getFeatureDimensions()
int CFeatureSpectralPitchChroma::getFeatureDimensions () const inline override virtual
returns size of output feature (1 in most cases)
Returns
int
Reimplemented from CFeatureFromBlockIf.
Definition at line 548 of file FeatureFromBlock.cpp.
    {
        return m_iNumPitchClasses;
    }
References m_iNumPitchClasses.
hasAdditionalParam()
bool CFeatureSpectralPitchChroma::hasAdditionalParam () const inline override virtual
returns true if there is an additional parameter
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 553 of file FeatureFromBlock.cpp.
    {
        return true;
    }
operator=()
CFeatureSpectralPitchChroma & CFeatureSpectralPitchChroma::operator= (const CFeatureSpectralPitchChroma & c) private
setAdditionalParam()
Error_t CFeatureSpectralPitchChroma::setAdditionalParam (float fParamValue) inline override virtual
returns true if there is an additional parameter
Parameters
fParamValue new parameter value
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 558 of file FeatureFromBlock.cpp.
    {
        if (fParamValue <= 0)
            return Error_t::kFunctionInvalidArgsError;
        m_iNumOctaves = CUtil::float2int<int>(fParamValue);
        // recompute transformation matrix
        genPcFilters_();
        return Error_t::kNoError;
    }
References genPcFilters_(), kFunctionInvalidArgsError, kNoError, and m_iNumOctaves.
Member Data Documentation
m_fA4
const float CFeatureSpectralPitchChroma::m_fA4 = 440.F private
Definition at line 613 of file FeatureFromBlock.cpp.
Referenced by genPcFilters_().
m_iNumOctaves
int CFeatureSpectralPitchChroma::m_iNumOctaves = 4 private
Definition at line 614 of file FeatureFromBlock.cpp.
Referenced by genPcFilters_(), and setAdditionalParam().
m_iNumPitchClasses
const int CFeatureSpectralPitchChroma::m_iNumPitchClasses = 12 private
Definition at line 611 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralPitchChroma(), compFeature(), genPcFilters_(), getFeatureDimensions(), and ~CFeatureSpectralPitchChroma().
m_ppfH
float** CFeatureSpectralPitchChroma::m_ppfH = 0 private
Definition at line 616 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralPitchChroma(), compFeature(), genPcFilters_(), and ~CFeatureSpectralPitchChroma().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp