ACA: LaszloFft Namespace Reference
LaszloFft Namespace Reference
Functions
long bitreverse (long i, long size)
long bruun_reverse (long i, long sizze)
void dif_butterfly (float *data, long size)
void inverse_dit_butterfly (float *data, long size)
void unshuffle (float *data, long size)
void realize (float *data, long size)
void unrealize (float *data, long size)
void fft (float *data, long size)
void ifft (float *data, long size)
void realfft_packed (float *data, long size)
void irealfft_packed (float *data, long size)
void realfft_bruun (float *data, long size)
void realfft_split (float *data, long n)
void irealfft_split (float *data, long n)
void realfft_radix2 (float *data, long n)
Function Documentation
bitreverse()
long LaszloFft::bitreverse (long i, long size)
Definition at line 30 of file rvfft.cpp.
{
    long result,mask;
    result=0;
    for(;size>1;size>>=1){
        mask=i&1;
        i>>=1;
        result<<=1;
        result|=mask;
    }
/*     __asm{       the same in assebly
     mov eax,i
     mov ecx,sizze
     mov ebx,0
   l:shr eax,1
     rcl ebx,1
     shr ecx,1
     cmp ecx,1
     jnz l
     mov result,ebx
     }*/
     return result;
}
bruun_reverse()
long LaszloFft::bruun_reverse (long i, long sizze)
Definition at line 60 of file rvfft.cpp.
{
    long result, add;
    result=0;
    add=sizze;
    while(1){
    if(i!=0) {
        while((i&1)==0) { i>>=1; add>>=1;}
        i>>=1; add>>=1;
        result+=add;
    }
    else {result<<=1;result+=add; return result;}
    if(i!=0) {
        while((i&1)==0) { i>>=1; add>>=1;}
        i>>=1; add>>=1;
        result-=add;
    }
    else {result<<=1;result-=add; return result;}
    }
}
Referenced by realfft_bruun().
dif_butterfly()
void LaszloFft::dif_butterfly (float * data, long size)
Definition at line 134 of file rvfft.cpp.
{
    long angle,astep,dl;
    float xr,yr,xi,yi,wr,wi,dr,di,ang;
    float *l1, *l2, *end, *ol2;
     astep=1;
     end=data+size+size;
     for(dl=size;dl>1;dl>>=1,astep+=astep){
                      l1=data;
                      l2=data+dl;
                      for(;l2<end;l1=l2,l2=l2+dl){
                            ol2=l2;
                            for(angle=0;l1<ol2;l1+=2,l2+=2){
                               ang=static_cast<float>(2*M_PI*angle/size);
                               wr=cosf(ang);
                               wi=-sinf(ang);
                               xr=*l1+*l2;
                               xi=*(l1+1)+*(l2+1);
                               dr=*l1-*l2;
                               di=*(l1+1)-*(l2+1);
                               yr=dr*wr-di*wi;
                               yi=dr*wi+di*wr;
                               *(l1)=xr;*(l1+1)=xi;
                               *(l2)=yr;*(l2+1)=yi;
                               angle+=astep;
                               }
                      }
     }
}
References M_PI.
Referenced by fft(), and realfft_packed().
fft()
void LaszloFft::fft (float * data, long size)
Definition at line 332 of file rvfft.cpp.
{
    float *l, *end;
    dif_butterfly(data,size);
    unshuffle(data,size);
    end=data+size+size;
    for(l=data;l<end;l++){*l=*l/size;};
}
References dif_butterfly(), and unshuffle().
ifft()
void LaszloFft::ifft (float * data, long size)
Definition at line 355 of file rvfft.cpp.
{
    unshuffle(data,size);
    inverse_dit_butterfly(data,size);
}
References inverse_dit_butterfly(), and unshuffle().
inverse_dit_butterfly()
void LaszloFft::inverse_dit_butterfly (float * data, long size)
Definition at line 178 of file rvfft.cpp.
{
    long angle,astep,dl;
    float xr,yr,xi,yi,wr,wi,dr,di,ang;
    float *l1, *l2, *end, *ol2;
     astep=size>>1;
     end=data+size+size;
     for(dl=2;astep>0;dl+=dl,astep>>=1){
                      l1=data;
                      l2=data+dl;
                      for(;l2<end;l1=l2,l2=l2+dl){
                            ol2=l2;
                            for(angle=0;l1<ol2;l1+=2,l2+=2){
                               ang=static_cast<float>(2*M_PI*angle/size);
                               wr=cosf(ang);
                               wi=sinf(ang);
                               xr=*l1;
                               xi=*(l1+1);
                               yr=*l2;
                               yi=*(l2+1);
                               dr=yr*wr-yi*wi;
                               di=yr*wi+yi*wr;
                               *(l1)=xr+dr;*(l1+1)=xi+di;
                               *(l2)=xr-dr;*(l2+1)=xi-di;
                               angle+=astep;
                               }
                      }
     }
}
References M_PI.
Referenced by ifft(), and irealfft_packed().
irealfft_packed()
void LaszloFft::irealfft_packed (float * data, long size)
Definition at line 401 of file rvfft.cpp.
{
    float *l, *end;
    size>>=1;
    unrealize(data,size);
    unshuffle(data,size);
    inverse_dit_butterfly(data,size);
    end=data+size+size;
    for(l=data;l<end;l++){*l=(*l)*2;};
}
References inverse_dit_butterfly(), unrealize(), and unshuffle().
irealfft_split()
void LaszloFft::irealfft_split (float * data, long n)
Definition at line 838 of file rvfft.cpp.
{
  long i,j,k,i5,i6,i7,i8,i0,id,i1,i2,i3,i4,n2,n4,n8,n1;
  float t1,t2,t3,t4,t5,a3,ss1,ss3,cc1,cc3,a,e,sqrt2;
  sqrt2=sqrtf(2.F);
n1=n-1;
n2=n<<1;
for(k=n;k>2;k>>=1){
    id=n2;
    n2>>=1;
    n4=n2>>2;
    n8=n2>>3;
    e = static_cast<float>(2*M_PI/(n2));
    i1=0;
    do{
        for (; i1<n; i1+=id){
            i2=i1+n4;
            i3=i2+n4;
            i4=i3+n4;
            t1=data[i1]-data[i3];
            data[i1]+=data[i3];
            data[i2]*=2;
            data[i3]=t1-2*data[i4];
            data[i4]=t1+2*data[i4];
            if (n4!=1){
                i0=i1+n8;
                i2+=n8;
                i3+=n8;
                i4+=n8;
                t1=(data[i2]-data[i0])/sqrt2;
                t2=(data[i4]+data[i3])/sqrt2;
                data[i0]+=data[i2];
                data[i2]=data[i4]-data[i3];
                data[i3]=2*(-t2-t1);
                data[i4]=2*(-t2+t1);
            }
         }
         id<<=1;
         i1=id-n2;
         id<<=1;
      } while ( i1<n1 );
    a=e;
    for (j=2; j<=n8; j++){
          a3=3*a;
          cc1=cosf(a);
          ss1=sinf(a);
          cc3=cosf(a3);
          ss3=sinf(a3);
          a=j*e;
          i=0;
          id=n2<<1;
          do{
           for (; i<n; i+=id){
              i1=i+j-1;
              i2=i1+n4;
              i3=i2+n4;
              i4=i3+n4;
              i5=i+n4-j+1;
              i6=i5+n4;
              i7=i6+n4;
              i8=i7+n4;
              t1=data[i1]-data[i6];
              data[i1]+=data[i6];
              t2=data[i5]-data[i2];
              data[i5]+=data[i2];
              t3=data[i8]+data[i3];
              data[i6]=data[i8]-data[i3];
              t4=data[i4]+data[i7];
              data[i2]=data[i4]-data[i7];
              t5=t1-t4;
              t1+=t4;
              t4=t2-t3;
              t2+=t3;
              data[i3]=t5*cc1+t4*ss1;
              data[i7]=-t4*cc1+t5*ss1;
              data[i4]=t1*cc3-t2*ss3;
              data[i8]=t2*cc3+t1*ss3;
              }
           id<<=1;
           i=id-n2;
           id<<=1;
         } while(i<n1);
       }
    }
   /*----------------------*/
    i0=0;
    id=4;
   do{
       for (; i0<n1; i0+=id){
            i1=i0+1;
            t1=data[i0];
            data[i0]=t1+data[i1];
            data[i1]=t1-data[i1];
        }
       id<<=1;
       i0=id-2;
       id<<=1;
    } while ( i0<n1 );
/*----------------------*/
//data shuffling
      for (i=0,j=0,n2=n/2; i<n1 ; i++){
      if (i<j){
                t1=data[j];
                data[j]=data[i];
                data[i]=t1;
                }
      k=n2;
      while (k<=j){
                j-=k;
                k>>=1;
                }
      j+=k;
      }
}
References M_PI.
Referenced by CFft::compInvFft().
realfft_bruun()
void LaszloFft::realfft_bruun (float * data, long size)
Definition at line 434 of file rvfft.cpp.
{
    float *end, *l0, *l1, *l2=0, *l3=0;
    long dl, dl2, dl_o, dl2_o, i, j, k, kk;
    float d0,d1,d2,d3,c,c2,p4;
    end=data+size;
    //first filterings, when there're only two taps
    size>>=1;
    dl=size;
    dl2=dl/2;
    for(;dl>1;dl>>=1,dl2>>=1){
        l0=data;
        l3=data+dl;
        for(i=0;i<dl;i++){
            d0=*l0;
            d2=*l3;
            *l0=d0+d2;
            *l3=d0-d2;
            l0++;
            l3++;
        }
    }
    l0=data;l1=data+1;
    d0=*l0;d1=*l1;
    *l0=d0+d1;*l1=d0-d1;
    l1+=2;
    *l1=-(*l1);
    //the remaining filterings
    p4=static_cast<float>(M_PI/(2*size));
    j=1;
    kk=1;
    dl_o=size/2;
    dl2_o=size/4;
    while(dl_o>1){
    for(k=0;k<kk;k++){
    c2=p4*bruun_reverse(j,size);
    c=2*cosf(c2);
    c2=2*sinf(c2);
    dl=dl_o;
    dl2=dl2_o;
    for(;dl>1;dl>>=1,dl2>>=1){
            l0=data+((dl*j)<<1);
            l1=l0+dl2;l2=l0+dl;l3=l1+dl;
            for(i=0;i<dl2;i++){
                d1=(*l1)*c;
                d2=(*l2)*c;
                d3=*l3+(*l1);
                d0=*l0+(*l2);
                *l0=d0+d1;
                *l1=d3+d2;
                *l2=d0-d1;
                *l3=d3-d2;
                l0++;
                l1++;
                l2++;
                l3++;
            }
        }
        //real conversion
        l3-=4;
        *l3=*l3-c*(*l0)/2;
        *l0=-c2*(*l0)/2;
        *l1=*l1+c*(*l2)/2;
        *l2=-c2*(*l2)/2;
    j++;
    }
    dl_o>>=1;
    dl2_o>>=1;
    kk<<=1;
    }
    //division with array length
    size<<=1;
    for(i=0;i<size;i++) data[i]=data[i]/size;
}
References bruun_reverse(), and M_PI.
realfft_packed()
void LaszloFft::realfft_packed (float * data, long size)
Definition at line 373 of file rvfft.cpp.
{
    float *l, *end;
    float div;
    size>>=1;
    dif_butterfly(data,size);
    unshuffle(data,size);
    realize(data,size);
    end=data+size+size;
    div=1.F*size+size;
    for(l=data;l<end;l++){*l=*l/div;};
}
References dif_butterfly(), realize(), and unshuffle().
realfft_radix2()
void LaszloFft::realfft_radix2 (float * data, long n)
Definition at line 972 of file rvfft.cpp.
{
    float  xt,a,e, t1, t2, cc, ss;
    long  i, j, k, n1, n2, n3, n4, i1, i2, i3, i4;
    n4=n-1;
  //data shuffling
      for (i=0,j=0,n2=n/2; i<n4 ; i++){
      if (i<j){
                xt=data[j];
                data[j]=data[i];
                data[i]=xt;
                }
      k=n2;
      while (k<=j){
                j-=k;
                k>>=1;
                }
      j+=k;
      }
/* -------------------- */
    for (i=0; i<n; i += 2)
      {
     xt = data[i];
     data[i] = xt + data[i+1];
     data[i+1] = xt - data[i+1];
      }
/* ------------------------ */
    n2 = 1;
    for (k=n;k>2;k>>=1){
        n4 = n2;
        n2 = n4 << 1;
        n1 = n2 << 1;
        e = static_cast<float>(2*M_PI/(n1));
        for (i=0; i<n; i+=n1){
            xt = data[i];
            data[i] = xt + data[i+n2];
            data[i+n2] = xt-data[i+n2];
            data[i+n4+n2] = -data[i+n4+n2];
            a = e;
            n3=n4-1;
            for (j = 1; j <=n3; j++){
                i1 = i+j;
                i2 = i - j + n2;
                i3 = i1 + n2;
                i4 = i - j + n1;
                cc = cosf(a);
                ss = sinf(a);
                a += e;
                t1 = data[i3] * cc + data[i4] * ss;
                t2 = data[i3] * ss - data[i4] * cc;
                data[i4] = data[i2] - t2;
                data[i3] = -data[i2] - t2;
                data[i2] = data[i1] - t1;
                data[i1] += t1;
          }
      }
  }
    //division with array length
   for(i=0;i<n;i++) data[i]/=n;
}
References M_PI.
realfft_split()
void LaszloFft::realfft_split (float * data, long n)
Definition at line 668 of file rvfft.cpp.
{
  long i,j,k,i5,i6,i7,i8,i0,id,i1,i2,i3,i4,n2,n4,n8;
  float t1,t2,t3,t4,t5,t6,a3,ss1,ss3,cc1,cc3,a,e,sqrt2;
  sqrt2=sqrtf(2.F);
  n4=n-1;
  //data shuffling
      for (i=0,j=0,n2=n/2; i<n4 ; i++){
      if (i<j){
                t1=data[j];
                data[j]=data[i];
                data[i]=t1;
                }
      k=n2;
      while (k<=j){
                j-=k;
                k>>=1;
                }
      j+=k;
      }
/*----------------------*/
    //length two butterflies
    i0=0;
    id=4;
   do{
       for (; i0<n4; i0+=id){
            i1=i0+1;
            t1=data[i0];
            data[i0]=t1+data[i1];
            data[i1]=t1-data[i1];
        }
       id<<=1;
       i0=id-2;
       id<<=1;
    } while ( i0<n4 );
   /*----------------------*/
   //L shaped butterflies
n2=2;
for(k=n;k>2;k>>=1){
    n2<<=1;
    n4=n2>>2;
    n8=n2>>3;
    e = static_cast<float>(2*M_PI/(n2));
    i1=0;
    id=n2<<1;
    do{
        for (; i1<n; i1+=id){
            i2=i1+n4;
            i3=i2+n4;
            i4=i3+n4;
            t1=data[i4]+data[i3];
            data[i4]-=data[i3];
            data[i3]=data[i1]-t1;
            data[i1]+=t1;
            if (n4!=1){
                i0=i1+n8;
                i2+=n8;
                i3+=n8;
                i4+=n8;
                t1=(data[i3]+data[i4])/sqrt2;
                t2=(data[i3]-data[i4])/sqrt2;
                data[i4]=data[i2]-t1;
                data[i3]=-data[i2]-t1;
                data[i2]=data[i0]-t2;
                data[i0]+=t2;
            }
         }
         id<<=1;
         i1=id-n2;
         id<<=1;
      } while ( i1<n );
    a=e;
    for (j=2; j<=n8; j++){
          a3=3*a;
          cc1=cosf(a);
          ss1=sinf(a);
          cc3=cosf(a3);
          ss3=sinf(a3);
          a=j*e;
          i=0;
          id=n2<<1;
          do{
           for (; i<n; i+=id){
              i1=i+j-1;
              i2=i1+n4;
              i3=i2+n4;
              i4=i3+n4;
              i5=i+n4-j+1;
              i6=i5+n4;
              i7=i6+n4;
              i8=i7+n4;
              t1=data[i3]*cc1+data[i7]*ss1;
              t2=data[i7]*cc1-data[i3]*ss1;
              t3=data[i4]*cc3+data[i8]*ss3;
              t4=data[i8]*cc3-data[i4]*ss3;
              t5=t1+t3;
              t6=t2+t4;
              t3=t1-t3;
              t4=t2-t4;
              t2=data[i6]+t6;
              data[i3]=t6-data[i6];
              data[i8]=t2;
              t2=data[i2]-t3;
              data[i7]=-data[i2]-t3;
              data[i4]=t2;
              t1=data[i1]+t5;
              data[i6]=data[i1]-t5;
              data[i1]=t1;
              t1=data[i5]+t4;
              data[i5]-=t4;
              data[i2]=t1;
             }
           id<<=1;
           i=id-n2;
           id<<=1;
         } while(i<n);
       }
      }
    //division with array length
   for(i=0;i<n;i++) data[i]/=n;
}
References M_PI.
Referenced by CFft::compFft().
realize()
void LaszloFft::realize (float * data, long size)
Definition at line 257 of file rvfft.cpp.
{
    float xr,yr,xi,yi,wr,wi,dr,di,ang,astep;
    float *l1, *l2;
    l1=data;
    l2=data+size+size-2;
    xr=*l1;
    xi=*(l1+1);
    *l1=xr+xi;
    *(l1+1)=xr-xi;
    l1+=2;
    astep=static_cast<float>(M_PI/size);
    for(ang=astep;l1<=l2;l1+=2,l2-=2,ang+=astep){
                               xr=(*l1+*l2)/2;
                               yi=(-(*l1)+(*l2))/2;
                               yr=(*(l1+1)+*(l2+1))/2;
                               xi=(*(l1+1)-*(l2+1))/2;
                               wr=cosf(ang);
                               wi=-sinf(ang);
                               dr=yr*wr-yi*wi;
                               di=yr*wi+yi*wr;
                               *l1=xr+dr;
                               *(l1+1)=xi+di;
                               *l2=xr-dr;
                               *(l2+1)=-xi+di;
    }
}
References M_PI.
Referenced by realfft_packed().
unrealize()
void LaszloFft::unrealize (float * data, long size)
Definition at line 293 of file rvfft.cpp.
{
    float xr,yr,xi,yi,wr,wi,dr,di,ang,astep;
    float *l1, *l2;
    l1=data;
    l2=data+size+size-2;
    xr=(*l1)/2;
    xi=(*(l1+1))/2;
    *l1=xr+xi;
    *(l1+1)=xr-xi;
    l1+=2;
    astep=static_cast<float>(M_PI/size);
    for(ang=astep;l1<=l2;l1+=2,l2-=2,ang+=astep){
                               xr=(*l1+*l2)/2;
                               yi=-(-(*l1)+(*l2))/2;
                               yr=(*(l1+1)+*(l2+1))/2;
                               xi=(*(l1+1)-*(l2+1))/2;
                               wr=cosf(ang);
                               wi=-sinf(ang);
                               dr=yr*wr-yi*wi;
                               di=yr*wi+yi*wr;
                               *l2=xr+dr;
                               *(l1+1)=xi+di;
                               *l1=xr-dr;
                               *(l2+1)=-xi+di;
    }
}
References M_PI.
Referenced by irealfft_packed().
unshuffle()
void LaszloFft::unshuffle (float * data, long size)
Definition at line 218 of file rvfft.cpp.
{
    long i,j,k,l,m;
    float re,im;
    //old version - turned out to be a bit slower
    /*for(i=0;i<size-1;i++){
             j=bitreverse(i,size);
             if (j>i){   //swap
                    re=data[i+i];im=data[i+i+1];
                    data[i+i]=data[j+j];data[i+i+1]=data[j+j+1];
                    data[j+j]=re;data[j+j+1]=im;
             }
    }*/
l=size-1;
m=size>>1;
for (i=0,j=0; i<l ; i++){
      if (i<j){
                re=data[j+j]; im=data[j+j+1];
                data[j+j]=data[i+i]; data[j+j+1]=data[i+i+1];
                data[i+i]=re; data[i+i+1]=im;
                }
      k=m;
      while (k<=j){
                j-=k;
                k>>=1;
                }
      j+=k;
      }
}
Referenced by fft(), ifft(), irealfft_packed(), and realfft_packed().