ACA: CPitchTimeAuditory Class Reference
CPitchTimeAuditory Class Reference
Public Member Functions
CPitchTimeAuditory (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchTimeAuditory ()
float compF0 (const float *pfInput) override
Public Member Functions inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t getPitchExtractorIdx () const
virtual float compF0 (const float *pfInput)=0
Private Member Functions
CPitchTimeAuditory ()
CPitchTimeAuditory (const CPitchTimeAuditory &that)
disallow copy construction
CPitchTimeAuditory & operator= (const CPitchTimeAuditory &c)
int getAcfMax_ (const float *pfInput)
Private Attributes
CCcf * m_pCCcf = 0
float * m_pfAcf = 0
float * m_pfSumAcf = 0
float ** m_ppfProcBuff = 0
CFilter< float > * m_apCFilter [m_iNumBands] = { 0 }
CGammaToneFbIf * m_pCFilterBank = 0
float m_fMax = 2000.F
const float m_fSmoothLpCutoff = 0.02F
const float m_fMinThresh = 0.35F
Static Private Attributes
static const int m_iNumBands = 20
Additional Inherited Members
Static Public Member Functions inherited from CPitchFromBlockIf
static Error_t create (CPitchFromBlockIf *&pCInstance, CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CPitchFromBlockIf *&pCInstance)
Protected Member Functions inherited from CPitchFromBlockIf
CPitchFromBlockIf ()
CPitchFromBlockIf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchFromBlockIf ()
CPitchFromBlockIf (const CPitchFromBlockIf &that)
CPitchFromBlockIf & operator= (const CPitchFromBlockIf &c)
Protected Attributes inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t m_ePitchIdx = CPitchIf::kNumPitchExtractors
index of Pitch to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
Detailed Description
Definition at line 213 of file PitchFromBlock.cpp.
Constructor & Destructor Documentation
CPitchTimeAuditory() [1/3]
CPitchTimeAuditory::CPitchTimeAuditory (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate) inline
Definition at line 216 of file PitchFromBlock.cpp.
                                                                                                : CPitchFromBlockIf(ePitchIdx, iDataLength, fSampleRate)
    {
        float afA[3] = { 0 };
        float afB[3] = { 0 };
        CButterLp::calcCoeffs(afB, afA, 2, m_fSmoothLpCutoff);
        m_pCCcf = new CCcf();
        m_pCCcf->init(iDataLength);
        CVector::alloc(m_pfAcf, m_pCCcf->getCcfLength(true));
        CVector::alloc(m_pfSumAcf, m_pCCcf->getCcfLength(true));
        CMatrix::alloc(m_ppfProcBuff, m_iNumBands, iDataLength);
        for (auto c = 0; c < m_iNumBands; c++)
        {
            m_apCFilter[c] = new CFilter<float>();
            m_apCFilter[c]->init(afB, afA, 3);
        }
        CGammaToneFbIf::create(m_pCFilterBank, fSampleRate, m_iNumBands);
    };
References CVector::alloc(), CMatrix::alloc(), CButterLp::calcCoeffs(), CGammaToneFbIf::create(), CCcf::getCcfLength(), CFilter< T >::init(), CCcf::init(), m_apCFilter, m_fSmoothLpCutoff, m_iNumBands, m_pCCcf, m_pCFilterBank, m_pfAcf, m_pfSumAcf, and m_ppfProcBuff.
~CPitchTimeAuditory()
virtual CPitchTimeAuditory::~CPitchTimeAuditory () inline virtual
Definition at line 239 of file PitchFromBlock.cpp.
    {
        CVector::free(m_pfAcf);
        CVector::free(m_pfSumAcf);
        CMatrix::free(m_ppfProcBuff, m_iNumBands);
        for (auto c = 0; c < m_iNumBands; c++)
            delete m_apCFilter[c];
        delete m_pCCcf;
        m_pCCcf = 0;
        CGammaToneFbIf::destroy(m_pCFilterBank);
    };
References CGammaToneFbIf::destroy(), CVector::free(), CMatrix::free(), m_apCFilter, m_iNumBands, m_pCCcf, m_pCFilterBank, m_pfAcf, m_pfSumAcf, and m_ppfProcBuff.
CPitchTimeAuditory() [2/3]
CPitchTimeAuditory::CPitchTimeAuditory () inline private
Definition at line 281 of file PitchFromBlock.cpp.
{};
CPitchTimeAuditory() [3/3]
CPitchTimeAuditory::CPitchTimeAuditory (const CPitchTimeAuditory & that) private
disallow copy construction
Member Function Documentation
compF0()
float CPitchTimeAuditory::compF0 (const float * pfInput) inline override virtual
performs the PitchFromBlock computation
Parameters
pfInput input data of length iDataLength
Returns
float fF0InHz
Implements CPitchFromBlockIf.
Definition at line 254 of file PitchFromBlock.cpp.
    {
        assert(pfInput);
        CVectorFloat::setZero(m_pfSumAcf, m_iDataLength);
        m_pCFilterBank->process(m_ppfProcBuff, pfInput, m_iDataLength);
        for (auto c = 0; c < m_iNumBands; c++)
        {
            // smooth
            m_apCFilter[c]->process(m_ppfProcBuff[c], m_ppfProcBuff[c], m_iDataLength);
            // compute acf
            m_pCCcf->compCcf(m_ppfProcBuff[c], m_ppfProcBuff[c], true);
            m_pCCcf->getCcf(m_pfAcf, true);
            // compute sum of acfs
            CVectorFloat::add_I(m_pfSumAcf, m_pfAcf, m_iDataLength);
        }
        int iEta = getAcfMax_(m_pfSumAcf);
        return m_fSampleRate / iEta;
    }
References CVectorFloat::add_I(), CCcf::compCcf(), getAcfMax_(), CCcf::getCcf(), m_apCFilter, CPitchFromBlockIf::m_fSampleRate, CPitchFromBlockIf::m_iDataLength, m_iNumBands, m_pCCcf, m_pCFilterBank, m_pfAcf, m_pfSumAcf, m_ppfProcBuff, CGammaToneFbIf::process(), CFilter< T >::process(), and CVectorFloat::setZero().
getAcfMax_()
int CPitchTimeAuditory::getAcfMax_ (const float * pfInput) inline private
Definition at line 285 of file PitchFromBlock.cpp.
    {
        int iEta = 0,
            iEtaMin = static_cast<int>(m_fSampleRate / m_fMax);
        // avoid main lobe
        while (pfInput[iEta] > m_fMinThresh)
            iEta++;
        if (iEtaMin < iEta)
            iEtaMin = iEta;
        // only look after first minimum
        iEta = 0;
        while (pfInput[iEta] > pfInput[iEta + 1])
        {
            iEta++;
            if (iEta >= m_iDataLength)
                break;
        }
        if (iEta >= m_iDataLength)
            iEtaMin = 0;
        else if (iEtaMin < iEta)
            iEtaMin = iEta;
        // get the maximum given the constraints above
        float fMax = 0;
        long long iMax = -1;
        CVectorFloat::findMax(&pfInput[iEtaMin], fMax, iMax, static_cast<long long>(m_iDataLength) - iEtaMin);
        if (fMax <= 0)
            return 0;
        return static_cast<int>(iMax + iEtaMin);
    };
References CVectorFloat::findMax(), m_fMax, m_fMinThresh, CPitchFromBlockIf::m_fSampleRate, and CPitchFromBlockIf::m_iDataLength.
Referenced by compF0().
operator=()
CPitchTimeAuditory & CPitchTimeAuditory::operator= (const CPitchTimeAuditory & c) private
Member Data Documentation
m_apCFilter
CFilter<float>* CPitchTimeAuditory::m_apCFilter[m_iNumBands] = { 0 } private
Definition at line 327 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_fMax
float CPitchTimeAuditory::m_fMax = 2000.F private
Definition at line 331 of file PitchFromBlock.cpp.
Referenced by getAcfMax_().
m_fMinThresh
const float CPitchTimeAuditory::m_fMinThresh = 0.35F private
Definition at line 333 of file PitchFromBlock.cpp.
Referenced by getAcfMax_().
m_fSmoothLpCutoff
const float CPitchTimeAuditory::m_fSmoothLpCutoff = 0.02F private
Definition at line 332 of file PitchFromBlock.cpp.
Referenced by CPitchTimeAuditory().
m_iNumBands
const int CPitchTimeAuditory::m_iNumBands = 20 static private
Definition at line 326 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pCCcf
CCcf* CPitchTimeAuditory::m_pCCcf = 0 private
Definition at line 321 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pCFilterBank
CGammaToneFbIf* CPitchTimeAuditory::m_pCFilterBank = 0 private
Definition at line 328 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pfAcf
float* CPitchTimeAuditory::m_pfAcf = 0 private
Definition at line 322 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pfSumAcf
float* CPitchTimeAuditory::m_pfSumAcf = 0 private
Definition at line 323 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_ppfProcBuff
float** CPitchTimeAuditory::m_ppfProcBuff = 0 private
Definition at line 324 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
The documentation for this class was generated from the following file:
PitchFromBlock.cpp