ACA: CFeatureIf Class Reference
CFeatureIf Class Reference
class for computation of a magnitude Feature from either a file or a vector
#include <Feature.h>
Public Types
enum Feature_t {
kFeatureSpectralCentroid , kFeatureSpectralCrestFactor , kFeatureSpectralDecrease , kFeatureSpectralFlatness ,
kFeatureSpectralFlux , kFeatureSpectralKurtosis , kFeatureSpectralMfccs , kFeatureSpectralPitchChroma ,
kFeatureSpectralRolloff , kFeatureSpectralSkewness , kFeatureSpectralSlope , kFeatureSpectralSpread ,
kFeatureSpectralTonalPowerRatio , kFeatureTimeAcfCoeff , kFeatureTimeMaxAcf , kFeatureTimePeakEnvelope ,
kFeatureTimeRms , kFeatureTimeStd , kFeatureTimeZeroCrossingRate , kNumFeatures
}
enum to index all features note: update CFeatureIf::isFeatureSpectral_() when modifying
Public Member Functions
Error_t getFeatureDimensions (int &iNumRows, int &iNumCols) const
Error_t getFeatureTimeStamps (float *pfAxisTicks) const
Error_t compFeature1Dim (float *pfFeature)
Error_t compFeatureNDim (float **ppfFeature)
Static Public Member Functions
static Error_t create (CFeatureIf *&pCInstance, Feature_t eFeatureIdx, const std::string &strAudioFilePath, int iBlockLength=2048, int iHopLength=1024)
static Error_t create (CFeatureIf *&pCInstance, Feature_t eFeatureIdx, const float *pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength=2048, int iHopLength=1024)
static Error_t destroy (CFeatureIf *&pCInstance)
static std::string getFeatureString (Feature_t eFeatureIdx)
static Feature_t getFeatureIdxFromString (std::string sFeatureString)
Protected Member Functions
CFeatureIf ()
virtual ~CFeatureIf ()
CFeatureIf (const CFeatureIf &that)
CFeatureIf & operator= (const CFeatureIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (Feature_t eFeatureIdx)
init configuration
bool isFeatureSpectral_ (Feature_t eFeatureIdx)
void computeMagSpectrum_ ()
Protected Attributes
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CFeatureFromBlockIf * m_pCFeature = 0
CFft * m_pCFft = 0
fft instance
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcessBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcessBuff1 = 0
temporary buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a magnitude Feature from either a file or a vector
Definition at line 17 of file Feature.h.
Member Enumeration Documentation
Feature_t
enum CFeatureIf::Feature_t
enum to index all features note: update CFeatureIf::isFeatureSpectral_() when modifying
Enumerator
kFeatureSpectralCentroid
kFeatureSpectralCrestFactor
kFeatureSpectralDecrease
kFeatureSpectralFlatness
kFeatureSpectralFlux
kFeatureSpectralKurtosis
kFeatureSpectralMfccs
kFeatureSpectralPitchChroma
kFeatureSpectralRolloff
kFeatureSpectralSkewness
kFeatureSpectralSlope
kFeatureSpectralSpread
kFeatureSpectralTonalPowerRatio
kFeatureTimeAcfCoeff
kFeatureTimeMaxAcf
kFeatureTimePeakEnvelope
kFeatureTimeRms
kFeatureTimeStd
kFeatureTimeZeroCrossingRate
kNumFeatures
Definition at line 23 of file Feature.h.
    {
        kFeatureSpectralCentroid,
        kFeatureSpectralCrestFactor,
        kFeatureSpectralDecrease,
        kFeatureSpectralFlatness,
        kFeatureSpectralFlux,
        kFeatureSpectralKurtosis,
        kFeatureSpectralMfccs,
        kFeatureSpectralPitchChroma,
        kFeatureSpectralRolloff,
        kFeatureSpectralSkewness,
        kFeatureSpectralSlope,
        kFeatureSpectralSpread,
        kFeatureSpectralTonalPowerRatio,
        kFeatureTimeAcfCoeff,
        kFeatureTimeMaxAcf,
        kFeatureTimePeakEnvelope,
        kFeatureTimeRms,
        kFeatureTimeStd,
        kFeatureTimeZeroCrossingRate,
        kNumFeatures
    };
Constructor & Destructor Documentation
CFeatureIf() [1/2]
CFeatureIf::CFeatureIf () protected
Definition at line 86 of file Feature.cpp.
{
    reset_();
}
References reset_().
~CFeatureIf()
CFeatureIf::~CFeatureIf () inline protected virtual
Definition at line 91 of file Feature.cpp.
{
    reset_();
}
References reset_().
CFeatureIf() [2/2]
CFeatureIf::CFeatureIf (const CFeatureIf & that) protected
Member Function Documentation
compFeature1Dim()
Error_t CFeatureIf::compFeature1Dim (float * pfFeature)
performs the Feature computation for 1 dimensional features and writes the result
Parameters
pfFeature (user-allocated, to be written, dimensions from CFeatureIf::getFeatureDimensions)
Returns
Error_t
Definition at line 173 of file Feature.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!pfFeature)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcessBuff1);
    assert(m_pfProcessBuff2);
    assert(m_pCFft);
    assert(m_pCBlockAudio);
    assert(m_pCNormalize);
    assert(m_pCFeature);
    auto iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        // retrieve the next audio block
        m_pCBlockAudio->getNextBlock(m_pfProcessBuff1);
        // normalize if specified
        if (m_pCNormalize)
            m_pCNormalize->normalizeBlock(m_pfProcessBuff1, m_iBlockLength);
        if (isFeatureSpectral_(m_pCFeature->getFeatureIdx()))
            computeMagSpectrum_();
        m_pCFeature->compFeature(&pfFeature[n], m_pfProcessBuff1);
    }
    return Error_t::kNoError;
}
References CFeatureFromBlockIf::compFeature(), computeMagSpectrum_(), CFeatureFromBlockIf::getFeatureIdx(), CBlockAudioIf::getNextBlock(), CBlockAudioIf::getNumBlocks(), isFeatureSpectral_(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iBlockLength, m_pCBlockAudio, m_pCFeature, m_pCFft, m_pCNormalize, m_pfProcessBuff1, m_pfProcessBuff2, and CNormalizeAudio::normalizeBlock().
Referenced by main().
compFeatureNDim()
Error_t CFeatureIf::compFeatureNDim (float ** ppfFeature)
performs the Feature computation for N dimensional features and writes the result
Parameters
ppfFeature (user-allocated, to be written, dimensions from CFeatureIf::getFeatureDimensions)
Returns
Error_t
Definition at line 207 of file Feature.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!ppfFeature)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfFeature[0])
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcessBuff1);
    assert(m_pfProcessBuff2);
    assert(m_pCBlockAudio);
    assert(m_pCNormalize);
    assert(m_pCFeature);
    auto iNumBlocks = m_pCBlockAudio->getNumBlocks();
    auto iNumFeatures = m_pCFeature->getFeatureDimensions();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        // retrieve the next audio block
        m_pCBlockAudio->getNextBlock(m_pfProcessBuff1);
        // normalize if specified
        if (m_pCNormalize)
            m_pCNormalize->normalizeBlock(m_pfProcessBuff1, m_iBlockLength);
        if (isFeatureSpectral_(m_pCFeature->getFeatureIdx()))
            computeMagSpectrum_();
        m_pCFeature->compFeature(m_pfProcessBuff2, m_pfProcessBuff1);
        // copy to output buffer
        for (auto k = 0; k < iNumFeatures; k++)
            ppfFeature[k][n] = m_pfProcessBuff2[k];
    }
    return Error_t::kNoError;
}
References CFeatureFromBlockIf::compFeature(), computeMagSpectrum_(), CFeatureFromBlockIf::getFeatureDimensions(), CFeatureFromBlockIf::getFeatureIdx(), CBlockAudioIf::getNextBlock(), CBlockAudioIf::getNumBlocks(), isFeatureSpectral_(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iBlockLength, m_pCBlockAudio, m_pCFeature, m_pCNormalize, m_pfProcessBuff1, m_pfProcessBuff2, and CNormalizeAudio::normalizeBlock().
Referenced by main().
computeMagSpectrum_()
void CFeatureIf::computeMagSpectrum_ () protected
Definition at line 308 of file Feature.cpp.
{
    assert(m_pCFft);
    // compute magnitude spectrum (hack
    m_pCFft->compFft(m_pfProcessBuff2, m_pfProcessBuff1);
    m_pCFft->getMagnitude(m_pfProcessBuff1, m_pfProcessBuff2);
    CVectorFloat::mulC_I(m_pfProcessBuff2, 2.F, m_pCFft->getLength(CFft::kLengthMagnitude));
}
References CFft::compFft(), CFft::getLength(), CFft::getMagnitude(), CFft::kLengthMagnitude, m_pCFft, m_pfProcessBuff1, m_pfProcessBuff2, and CVectorFloat::mulC_I().
Referenced by compFeature1Dim(), and compFeatureNDim().
create() [1/2]
Error_t CFeatureIf::create (CFeatureIf *& pCInstance, Feature_t eFeatureIdx, const float * pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength = 2048, int iHopLength = 1024) static
initializes a Feature instance from audio data
Parameters
pCInstance pointer to instance to be written
eFeatureIdx as defined in Feature_t
pfAudio complete audio data
iNumFrames length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in Frames
iHopLength hop length in Frames
Returns
Error_t
Definition at line 111 of file Feature.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumFrames <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CFeatureFromVector(eFeatureIdx, pfAudio, iNumFrames, fSampleRate, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, and kNoError.
create() [2/2]
Error_t CFeatureIf::create (CFeatureIf *& pCInstance, Feature_t eFeatureIdx, const std::string & strAudioFilePath, int iBlockLength = 2048, int iHopLength = 1024) static
initializes a Feature instance with file reading
Parameters
pCInstance pointer to instance to be written
eFeatureIdx as defined in Feature_t
strAudioFilePath complete path to audio file
iBlockLength FFT block length in Frames
iHopLength hop length in Frames
Returns
Error_t
Definition at line 96 of file Feature.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CFeatureFromFile(eFeatureIdx, strAudioFilePath, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References CUtil::isPowOf2(), kFunctionInvalidArgsError, and kNoError.
Referenced by main().
destroy()
Error_t CFeatureIf::destroy (CFeatureIf *& pCInstance) static
destroys a Feature instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 129 of file Feature.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by main().
getFeatureDimensions()
Error_t CFeatureIf::getFeatureDimensions (int & iNumRows, int & iNumCols) const
returns size of matrix to be allocated by user
Parameters
iNumRows (number of rows, to be written) equals number of feature values per time stamp
iNumCols (number of columns, to be written) equals number of blocks
Returns
Error_t
Definition at line 137 of file Feature.cpp.
{
    if (!m_bIsInitialized)
    {
        iNumRows = 0;
        iNumCols = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumRows = m_pCFeature->getFeatureDimensions();
    iNumCols = static_cast<int>(m_pCBlockAudio->getNumBlocks());
    return Error_t::kNoError;
}
References CFeatureFromBlockIf::getFeatureDimensions(), CBlockAudioIf::getNumBlocks(), kFunctionIllegalCallError, kNoError, m_bIsInitialized, m_pCBlockAudio, and m_pCFeature.
Referenced by main().
getFeatureIdxFromString()
CFeatureIf::Feature_t CFeatureIf::getFeatureIdxFromString (std::string sFeatureString) static
returns feature index from string
Parameters
sFeatureString string describing the feature
Returns
Feature_t
Definition at line 276 of file Feature.cpp.
{
    const std::map<std::string, CFeatureIf::Feature_t> FeatureMap
    {
            {"SpectralCentroid", kFeatureSpectralCentroid},
            {"SpectralCrestFactor", kFeatureSpectralCrestFactor},
            {"SpectralDecrease", kFeatureSpectralDecrease},
            {"SpectralFlatness", kFeatureSpectralFlatness},
            {"SpectralFlux", kFeatureSpectralFlux},
            {"SpectralKurtosis", kFeatureSpectralKurtosis},
            {"SpectralMfccs", kFeatureSpectralMfccs},
            {"SpectralPitchChroma", kFeatureSpectralPitchChroma},
            {"SpectralRolloff", kFeatureSpectralRolloff},
            {"SpectralSkewness", kFeatureSpectralSkewness},
            {"SpectralSlope", kFeatureSpectralSlope},
            {"SpectralSpread", kFeatureSpectralSpread},
            {"SpectralTonalPowerRatio", kFeatureSpectralTonalPowerRatio},
            {"TimeAcfCoeff", kFeatureTimeAcfCoeff},
            {"TimeMaxAcf", kFeatureTimeMaxAcf},
            {"TimePeakEnvelope", kFeatureTimePeakEnvelope},
            {"TimeRms", kFeatureTimeRms},
            {"TimeStd", kFeatureTimeStd},
            {"TimeZeroCrossingRate", kFeatureTimeZeroCrossingRate}
    };
    auto search = FeatureMap.find(sFeatureString);
    if (search != FeatureMap.end())
        return FeatureMap.at(sFeatureString);
    else
        return kNumFeatures;
}
References kFeatureSpectralCentroid, kFeatureSpectralCrestFactor, kFeatureSpectralDecrease, kFeatureSpectralFlatness, kFeatureSpectralFlux, kFeatureSpectralKurtosis, kFeatureSpectralMfccs, kFeatureSpectralPitchChroma, kFeatureSpectralRolloff, kFeatureSpectralSkewness, kFeatureSpectralSlope, kFeatureSpectralSpread, kFeatureSpectralTonalPowerRatio, kFeatureTimeAcfCoeff, kFeatureTimeMaxAcf, kFeatureTimePeakEnvelope, kFeatureTimeRms, kFeatureTimeStd, kFeatureTimeZeroCrossingRate, and kNumFeatures.
Referenced by main().
getFeatureString()
std::string CFeatureIf::getFeatureString (Feature_t eFeatureIdx) static
returns feature name as string
Parameters
eFeatureIdx feature index
Returns
std::string
Definition at line 247 of file Feature.cpp.
{
    const std::map<CFeatureIf::Feature_t, std::string> FeatureMap
    {
            {kFeatureSpectralCentroid, "SpectralCentroid"},
            {kFeatureSpectralCrestFactor, "SpectralCrestFactor"},
            {kFeatureSpectralDecrease, "SpectralDecrease"},
            {kFeatureSpectralFlatness, "SpectralFlatness"},
            {kFeatureSpectralFlux, "SpectralFlux"},
            {kFeatureSpectralKurtosis, "SpectralKurtosis"},
            {kFeatureSpectralMfccs, "SpectralMfccs"},
            {kFeatureSpectralPitchChroma, "SpectralPitchChroma"},
            {kFeatureSpectralRolloff, "SpectralRolloff"},
            {kFeatureSpectralSkewness, "SpectralSkewness"},
            {kFeatureSpectralSlope, "SpectralSlope"},
            {kFeatureSpectralSpread, "SpectralSpread"},
            {kFeatureSpectralTonalPowerRatio, "SpectralTonalPowerRatio"},
            {kFeatureTimeAcfCoeff, "TimeAcfCoeff"},
            {kFeatureTimeMaxAcf, "TimeMaxAcf"},
            {kFeatureTimePeakEnvelope, "TimePeakEnvelope"},
            {kFeatureTimeRms, "TimeRms"},
            {kFeatureTimeStd, "TimeStd"},
            {kFeatureTimeZeroCrossingRate, "TimeZeroCrossingRate"}
    };
    return FeatureMap.at(eFeatureIdx);
}
References kFeatureSpectralCentroid, kFeatureSpectralCrestFactor, kFeatureSpectralDecrease, kFeatureSpectralFlatness, kFeatureSpectralFlux, kFeatureSpectralKurtosis, kFeatureSpectralMfccs, kFeatureSpectralPitchChroma, kFeatureSpectralRolloff, kFeatureSpectralSkewness, kFeatureSpectralSlope, kFeatureSpectralSpread, kFeatureSpectralTonalPowerRatio, kFeatureTimeAcfCoeff, kFeatureTimeMaxAcf, kFeatureTimePeakEnvelope, kFeatureTimeRms, kFeatureTimeStd, and kFeatureTimeZeroCrossingRate.
getFeatureTimeStamps()
Error_t CFeatureIf::getFeatureTimeStamps (float * pfAxisTicks) const
returns axis ticks
Parameters
pfAxisTicks (to be written) equals iNumRows if eAxisLabel == kFrequencyInHz, otherwise iNumCols
Returns
Error_t
Definition at line 152 of file Feature.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
        pfAxisTicks[n] = m_pCBlockAudio->getTimeStamp(n);
    return Error_t::kNoError;
}
References CBlockAudioIf::getNumBlocks(), CBlockAudioIf::getTimeStamp(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, and m_pCBlockAudio.
init_()
Error_t CFeatureIf::init_ (Feature_t eFeatureIdx) protected
init configuration
Definition at line 345 of file Feature.cpp.
{
    if (isFeatureSpectral_(eFeatureIdx))
    {
        // initialize FFT and fft  buffer
        m_pCFft = new CFft();
        m_pCFft->init(m_iBlockLength);
        // allocate processing memory
        m_pfProcessBuff1 = new float[m_pCFft->getLength(CFft::kLengthFft)];
        m_pfProcessBuff2 = new float[m_pCFft->getLength(CFft::kLengthFft)];
        CFeatureFromBlockIf::create(m_pCFeature, eFeatureIdx, m_pCFft->getLength(CFft::kLengthMagnitude), m_fSampleRate);
    }
    else
    {
        // allocate processing memory
        m_pfProcessBuff1 = new float[m_iBlockLength];
        CFeatureFromBlockIf::create(m_pCFeature, eFeatureIdx, m_iBlockLength, m_fSampleRate);
    }
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CFeatureFromBlockIf::create(), CFft::getLength(), CFft::init(), isFeatureSpectral_(), CFft::kLengthFft, CFft::kLengthMagnitude, kNoError, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_pCFeature, m_pCFft, m_pfProcessBuff1, and m_pfProcessBuff2.
Referenced by CFeatureFromFile::CFeatureFromFile(), and CFeatureFromVector::CFeatureFromVector().
isFeatureSpectral_()
bool CFeatureIf::isFeatureSpectral_ (Feature_t eFeatureIdx) protected
Definition at line 368 of file Feature.cpp.
{
    return (eFeatureIdx <= kFeatureSpectralTonalPowerRatio) ? true : false;
}
References kFeatureSpectralTonalPowerRatio, and true.
Referenced by compFeature1Dim(), compFeatureNDim(), and init_().
operator=()
CFeatureIf & CFeatureIf::operator= (const CFeatureIf & c) protected
reset_()
Error_t CFeatureIf::reset_ () protected
reset configuration
Definition at line 320 of file Feature.cpp.
{
    delete[] m_pfProcessBuff1;
    m_pfProcessBuff1 = 0;
    delete[] m_pfProcessBuff2;
    m_pfProcessBuff2 = 0;
    delete m_pCFft;
    m_pCFft = 0;
    delete m_pCNormalize;
    m_pCNormalize = 0;
    CBlockAudioIf::destroy(m_pCBlockAudio);
    CFeatureFromBlockIf::destroy(m_pCFeature);
    m_iBlockLength = 0;
    m_iHopLength = 0;
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CBlockAudioIf::destroy(), CFeatureFromBlockIf::destroy(), kNoError, m_bIsInitialized, m_iBlockLength, m_iHopLength, m_pCBlockAudio, m_pCFeature, m_pCFft, m_pCNormalize, m_pfProcessBuff1, and m_pfProcessBuff2.
Referenced by CFeatureFromFile::CFeatureFromFile(), CFeatureIf(), and ~CFeatureIf().
Member Data Documentation
m_bIsInitialized
bool CFeatureIf::m_bIsInitialized = false protected
true if initialized
Definition at line 141 of file Feature.h.
Referenced by compFeature1Dim(), compFeatureNDim(), getFeatureDimensions(), getFeatureTimeStamps(), init_(), and reset_().
m_fSampleRate
float CFeatureIf::m_fSampleRate = 0 protected
sample rate
Definition at line 136 of file Feature.h.
Referenced by CFeatureFromFile::CFeatureFromFile(), CFeatureFromVector::CFeatureFromVector(), getFeatureTimeStamps(), and init_().
m_iBlockLength
int CFeatureIf::m_iBlockLength = 0 protected
fft length
Definition at line 133 of file Feature.h.
Referenced by CFeatureFromFile::CFeatureFromFile(), CFeatureFromVector::CFeatureFromVector(), compFeature1Dim(), compFeatureNDim(), getFeatureTimeStamps(), init_(), and reset_().
m_iHopLength
int CFeatureIf::m_iHopLength = 0 protected
hop length
Definition at line 134 of file Feature.h.
Referenced by CFeatureFromFile::CFeatureFromFile(), CFeatureFromVector::CFeatureFromVector(), getFeatureTimeStamps(), and reset_().
m_pCBlockAudio
CBlockAudioIf* CFeatureIf::m_pCBlockAudio = 0 protected
instantiate for blocking time domain signal
Definition at line 127 of file Feature.h.
Referenced by CFeatureFromFile::CFeatureFromFile(), CFeatureFromVector::CFeatureFromVector(), compFeature1Dim(), compFeatureNDim(), getFeatureDimensions(), getFeatureTimeStamps(), and reset_().
m_pCFeature
CFeatureFromBlockIf* CFeatureIf::m_pCFeature = 0 protected
Definition at line 129 of file Feature.h.
Referenced by compFeature1Dim(), compFeatureNDim(), getFeatureDimensions(), init_(), and reset_().
m_pCFft
CFft* CFeatureIf::m_pCFft = 0 protected
fft instance
Definition at line 131 of file Feature.h.
Referenced by compFeature1Dim(), computeMagSpectrum_(), init_(), and reset_().
m_pCNormalize
CNormalizeAudio* CFeatureIf::m_pCNormalize = 0 protected
instantiate if audio file normalization is wanted
Definition at line 125 of file Feature.h.
Referenced by CFeatureFromFile::CFeatureFromFile(), CFeatureFromVector::CFeatureFromVector(), compFeature1Dim(), compFeatureNDim(), reset_(), and CFeatureFromFile::~CFeatureFromFile().
m_pfProcessBuff1
float* CFeatureIf::m_pfProcessBuff1 = 0 protected
temporary buffer
Definition at line 139 of file Feature.h.
Referenced by compFeature1Dim(), compFeatureNDim(), computeMagSpectrum_(), init_(), reset_(), and CFeatureFromFile::~CFeatureFromFile().
m_pfProcessBuff2
float* CFeatureIf::m_pfProcessBuff2 = 0 protected
temporary buffer for current spectrum
Definition at line 138 of file Feature.h.
Referenced by compFeature1Dim(), compFeatureNDim(), computeMagSpectrum_(), init_(), and reset_().
The documentation for this class was generated from the following files:
Feature.h
Feature.cpp