ACA: CAudioFileRaw Class Reference
CAudioFileRaw Class Reference
open, read, and write raw audio files in 16 bit integer little endian format.
#include <AudioFile.h>
Public Member Functions
CAudioFileRaw ()
virtual ~CAudioFileRaw ()
Error_t openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const *psFileSpec=0) override
Error_t closeFile () override
bool isEof () override
bool isOpen () override
Public Member Functions inherited from CAudioFileIf
virtual Error_t reset (bool bFreeMemory=false)
virtual Error_t openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const *psFileSpec=0)=0
virtual Error_t closeFile ()=0
virtual Error_t readData (float **ppfAudioData, long long int &iNumFrames)
virtual Error_t writeData (float **ppfAudioData, long long int iNumFrames)
Error_t getFileSpec (FileSpec_t &sFileSpec)
virtual Error_t setPosition (long long iFrame=0)
Error_t setPosition (double dTimeInS=.0)
Error_t setClippingEnabled (bool bIsEnabled=true)
bool isClippingEnabled ()
Error_t getPosition (long long &iFrame)
Error_t getPosition (double &dTimeInS)
Error_t getLength (long long &iLengthInFrames)
Error_t getLength (double &dLengthInSeconds)
virtual bool isEof ()=0
virtual bool isOpen ()=0
virtual bool isInitialized ()
Private Member Functions
CAudioFileRaw (const CAudioFileRaw &that)
Error_t freeMemory_ () override
Error_t allocMemory_ () override
long long int readDataIntern_ (float **ppfAudioData, long long int iNumFrames) override
long long int writeDataIntern_ (float **ppfAudioData, long long int iLength) override
long long getLengthIntern_ () override
long long getPositionIntern_ () override
Error_t setPositionIntern_ (long long iFrame) override
float scaleUp (float fSample2Clip)
float scaleDown (float fSample2Scale)
Private Attributes
std::fstream m_File
raw pcm file handle
short * m_piTmpBuff
temporary buffer for 16 bit integer values
Additional Inherited Members
Public Types inherited from CAudioFileIf
enum FileIoType_t { kFileRead = 0x1L , kFileWrite = 0x2L , kNumFileOpenTypes = 2 }
enum FileFormat_t {
kFileFormatRaw , kFileFormatWav , kFileFormatAiff , kFileFormatUnknown ,
kNumFileFormats
}
enum BitStream_t { kFileBitStreamInt16 , kFileBitStreamFloat32 , kFileBitStreamUnknown , kNumWordLengths }
Static Public Member Functions inherited from CAudioFileIf
static Error_t create (CAudioFileIf *&pCInstance)
static Error_t destroy (CAudioFileIf *&pCInstance)
Protected Member Functions inherited from CAudioFileIf
CAudioFileIf ()
virtual ~CAudioFileIf ()
virtual Error_t freeMemory_ ()
virtual Error_t allocMemory_ ()
Error_t setInitialized_ (bool bInitialized=true)
Error_t setIoType_ (FileIoType_t eIoType)
FileIoType_t getIoType_ () const
Error_t setFileSpec_ (const FileSpec_t *pFileSpec)
int getNumChannels_ () const
long long convFrames2Bytes_ (long long iNumFrames)
long long convBytes2Frames_ (long long iNumFrames)
Error_t setNumBytesPerSample_ (int iNumBytes)
int getNumBytesPerSample_ () const
int getNumBitsPerSample_ () const
float clip2Range_ (float fSample2Clip, float fMin, float fMax)
Static Protected Attributes inherited from CAudioFileIf
static const long long int m_kiDefBlockLength = 1024
buffer length for read and write operations
Detailed Description
open, read, and write raw audio files in 16 bit integer little endian format.
Definition at line 10 of file AudioFile.h.
Constructor & Destructor Documentation
CAudioFileRaw() [1/2]
CAudioFileRaw::CAudioFileRaw ()
Definition at line 20 of file AudioFile.cpp.
                            : CAudioFileIf() ,
    m_piTmpBuff(0)
{
    reset (true);
}
References CAudioFileIf::reset().
~CAudioFileRaw()
CAudioFileRaw::~CAudioFileRaw () virtual
Definition at line 26 of file AudioFile.cpp.
{
    reset (true);
}
References CAudioFileIf::reset().
CAudioFileRaw() [2/2]
CAudioFileRaw::CAudioFileRaw (const CAudioFileRaw & that) private
Member Function Documentation
allocMemory_()
Error_t CAudioFileRaw::allocMemory_ () override private virtual
Reimplemented from CAudioFileIf.
Definition at line 43 of file AudioFile.cpp.
{
    freeMemory_ ();
    m_piTmpBuff = new short [static_cast<unsigned int>(m_kiDefBlockLength)];
    if (!m_piTmpBuff)
        return Error_t::kMemError;
    else
        return Error_t::kNoError;
}
References freeMemory_(), kMemError, kNoError, CAudioFileIf::m_kiDefBlockLength, and m_piTmpBuff.
Referenced by openFile().
closeFile()
Error_t CAudioFileRaw::closeFile () override virtual
close the current file
Returns
Error_t
Implements CAudioFileIf.
Definition at line 82 of file AudioFile.cpp.
{
    if (!isOpen())
    {
        return Error_t::kNoError;
    }
    m_File.close ();
    // free internal memory
    return freeMemory_ ();
}
References freeMemory_(), isOpen(), kNoError, and m_File.
freeMemory_()
Error_t CAudioFileRaw::freeMemory_ () override private virtual
Reimplemented from CAudioFileIf.
Definition at line 31 of file AudioFile.cpp.
{
    CAudioFileIf::freeMemory_ ();
    if (!m_piTmpBuff)
        return Error_t::kNoError;
    delete [] m_piTmpBuff;
    m_piTmpBuff  = 0;
    return Error_t::kNoError;
}
References CAudioFileIf::freeMemory_(), kNoError, and m_piTmpBuff.
Referenced by allocMemory_(), and closeFile().
getLengthIntern_()
long long CAudioFileRaw::getLengthIntern_ () override private virtual
Implements CAudioFileIf.
Definition at line 207 of file AudioFile.cpp.
{
    assert(m_File);
    //static const int    iNumOfBytesPerSample = 2;
    long long iCurrPos  = getPositionIntern_();
    long long iLength   = 0;
    m_File.seekg (0, m_File.end);
    iLength = convBytes2Frames_(static_cast<long long>(m_File.tellg()));
    setPositionIntern_(iCurrPos);
    return iLength;
}
References CAudioFileIf::convBytes2Frames_(), getPositionIntern_(), m_File, and setPositionIntern_().
getPositionIntern_()
long long CAudioFileRaw::getPositionIntern_ () override private virtual
Implements CAudioFileIf.
Definition at line 224 of file AudioFile.cpp.
{
    assert(m_File);
    return convBytes2Frames_(static_cast<long long>(m_File.tellg()));
}
References CAudioFileIf::convBytes2Frames_(), and m_File.
Referenced by getLengthIntern_().
isEof()
bool CAudioFileRaw::isEof () override virtual
check if EOF is true
Returns
bool
Implements CAudioFileIf.
Definition at line 95 of file AudioFile.cpp.
{
    return m_File.eof();
}
References m_File.
isOpen()
bool CAudioFileRaw::isOpen () override virtual
check if a file is opened
Returns
bool
Implements CAudioFileIf.
Definition at line 100 of file AudioFile.cpp.
{
    return m_File.is_open ();
}
References m_File.
Referenced by closeFile(), and openFile().
openFile()
Error_t CAudioFileRaw::openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const * psFileSpec = 0) override virtual
open a file for reading or writing
Parameters
cAudioFileName
eIoType
psFileSpec
Returns
Error_t
Implements CAudioFileIf.
Definition at line 55 of file AudioFile.cpp.
{
    if (cAudioFileName.empty())
        return Error_t::kFileOpenError;
    reset (true);
    setIoType_(eIoType);
    // set file spec (required for raw streams)
    if (psFileSpec)
    {
        setFileSpec_(psFileSpec);
        setInitialized_(true);
    }
    // open file
    m_File.open (cAudioFileName.c_str(), ios::binary | ((eIoType & kFileRead)? ios::in : ios::out));
    if (!isOpen())
    {
        reset (true);
        return Error_t::kFileOpenError;
    }
    // allocate internal memory
    return allocMemory_ ();
}
References allocMemory_(), isOpen(), kFileOpenError, CAudioFileIf::kFileRead, m_File, CAudioFileIf::reset(), CAudioFileIf::setFileSpec_(), CAudioFileIf::setInitialized_(), and CAudioFileIf::setIoType_().
readDataIntern_()
long long int CAudioFileRaw::readDataIntern_ (float ** ppfAudioData, long long int iNumFrames) override private virtual
Implements CAudioFileIf.
Definition at line 122 of file AudioFile.cpp.
{
    int iNumChannels                = getNumChannels_();
    long long int iNumFrames2Read   = min (iLength, m_kiDefBlockLength/iNumChannels);
    long long int iNumFrames        = 0;
    // sanity check
    assert(ppfAudioData);
    assert (ppfAudioData[0]);
    // ugly hack
    // a) only for 16 bit input
    // b) only for little endian
    while (iNumFrames2Read > 0)
    {
        long long int iCurrFrames = iNumFrames2Read;
        m_File.read (reinterpret_cast<char*>(m_piTmpBuff), convFrames2Bytes_(iNumFrames2Read));
        iNumFrames2Read = min (iLength-iCurrFrames, m_kiDefBlockLength/iNumChannels);
        if (!m_File)
        {
            iCurrFrames     = static_cast<int>(convBytes2Frames_(m_File.gcount ()));
            iNumFrames2Read = 0;
        }
        // copy the data
        for (int iCh = 0; iCh < iNumChannels; iCh++)
        {
            for (int i = 0; i < iCurrFrames; i++)
            {
                ppfAudioData[iCh][iNumFrames+i] = scaleDown(static_cast<float> (m_piTmpBuff[i*iNumChannels+iCh]));
            }
        }
        // update frame counters
        iLength        -= iCurrFrames;
        iNumFrames     += iCurrFrames;
        assert (iLength >= 0);
    }
    // update iLength to the number of frames actually read
    return iNumFrames;
}
References CAudioFileIf::convBytes2Frames_(), CAudioFileIf::convFrames2Bytes_(), CAudioFileIf::getNumChannels_(), m_File, CAudioFileIf::m_kiDefBlockLength, m_piTmpBuff, and scaleDown().
scaleDown()
float CAudioFileRaw::scaleDown (float fSample2Scale) private
Definition at line 116 of file AudioFile.cpp.
{
    float fScale        = static_cast<float>(1<<(getNumBitsPerSample_()-1));
    return fSample2Scale/fScale;
}
References CAudioFileIf::getNumBitsPerSample_().
Referenced by readDataIntern_().
scaleUp()
float CAudioFileRaw::scaleUp (float fSample2Clip) private
Definition at line 105 of file AudioFile.cpp.
{
    float fScale        = static_cast<float>(1<<(getNumBitsPerSample_()-1));
    fSample2Clip *= fScale;
    if (isClippingEnabled())
    {
        fSample2Clip = clip2Range_(fSample2Clip, -fScale, fScale-1);
    }
    return fSample2Clip;
}
References CAudioFileIf::clip2Range_(), CAudioFileIf::getNumBitsPerSample_(), and CAudioFileIf::isClippingEnabled().
Referenced by writeDataIntern_().
setPositionIntern_()
Error_t CAudioFileRaw::setPositionIntern_ (long long iFrame) override private virtual
Implements CAudioFileIf.
Definition at line 230 of file AudioFile.cpp.
{
    assert(m_File);
    assert(iFrame >= 0);
    m_File.seekg (convFrames2Bytes_(iFrame), m_File.beg);
    return Error_t::kNoError;
}
References CAudioFileIf::convFrames2Bytes_(), kNoError, and m_File.
Referenced by getLengthIntern_().
writeDataIntern_()
long long int CAudioFileRaw::writeDataIntern_ (float ** ppfAudioData, long long int iLength) override private virtual
Implements CAudioFileIf.
Definition at line 169 of file AudioFile.cpp.
{
    long long int iIdx  = 0;
    int iNumChannels    = getNumChannels_();
    // sanity check
    assert(ppfAudioData);
    assert(ppfAudioData[0]);
    // very ugly hack
    // a) only for 16 bit output
    // b) disregarded endianess
    while (iIdx < iLength)
    {
        long long int iNumFrames2Write = min (iLength-iIdx, m_kiDefBlockLength/iNumChannels);
        // copy the data
        for (int iCh = 0; iCh < iNumChannels; iCh++)
        {
            for (int i = 0; i < iNumFrames2Write; i++)
            {
                m_piTmpBuff[i*iNumChannels+iCh] = CUtil::float2int<short>(scaleUp(ppfAudioData[iCh][iIdx+i]));
            }
        }
        m_File.write (reinterpret_cast<char*>(m_piTmpBuff), convFrames2Bytes_(iNumFrames2Write));
        if (!m_File)
        {
            break;
        }
        // update frame counter
        iIdx   += iNumFrames2Write;
    }
    return iIdx;
}
References CAudioFileIf::convFrames2Bytes_(), CAudioFileIf::getNumChannels_(), m_File, CAudioFileIf::m_kiDefBlockLength, m_piTmpBuff, and scaleUp().
Member Data Documentation
m_File
std::fstream CAudioFileRaw::m_File private
raw pcm file handle
Definition at line 34 of file AudioFile.h.
Referenced by closeFile(), getLengthIntern_(), getPositionIntern_(), isEof(), isOpen(), openFile(), readDataIntern_(), setPositionIntern_(), and writeDataIntern_().
m_piTmpBuff
short* CAudioFileRaw::m_piTmpBuff private
temporary buffer for 16 bit integer values
Definition at line 35 of file AudioFile.h.
Referenced by allocMemory_(), freeMemory_(), readDataIntern_(), and writeDataIntern_().
The documentation for this class was generated from the following files:
AudioFile.h
AudioFile.cpp