ACA: CMatrix Class Reference
CMatrix Class Reference
class with static functions for matrix operations with type float (functionality only added when needed)
#include <Matrix.h>
Static Public Member Functions
template<typename T >
static void alloc (T **&ppfMat, int iNumRows, int iNumCols)
template<typename T >
static void free (T **&ppfMat, int iNumRows)
static void mulMatColVec (float *pfDestColVec, float **ppfMatrix, const float *pfSrcColVec, int iNumMatRows, int iNumMatCols)
static void mulRowVecMat (float *pfDestRowVec, const float *pfSrcRowVec, float **ppfMatrix, int iNumMatRows, int iNumMatCols)
static void mulMatMat (float **ppfDest, float **ppfSrc1, float **ppfSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols)
static void setEye (float **ppfDest, int iNumRows, int iNumCols)
static float getMax (float **ppfMat, int iNumRows, int iNumCols)
static void addC_I (float **ppfMat, float fAdd, int iNumRows, int iNumCols)
static void mulC_I (float **ppfMat, float fScale, int iNumRows, int iNumCols)
static void swapRowCol (float **ppfSrcDest, int iRowIdx, int iColIdx, int iNumCols)
template<typename T >
static void copy (T **ppfDestMat, T **ppfSrcMat, int iNumRows, int iNumCols)
template<typename T >
static void setRow (T **ppfDestMat, T *pfSrcVec, int iRowIdx, int iNumCols)
template<typename T >
static void setCol (T **ppfDestMat, T *pfSrcVec, int iColIdx, int iNumRows)
static void inv_I (float **ppfSrcDest, int iNumRows, int iNumCols)
Detailed Description
class with static functions for matrix operations with type float (functionality only added when needed)
Definition at line 10 of file Matrix.h.
Member Function Documentation
addC_I()
static void CMatrix::addC_I (float ** ppfMat, float fAdd, int iNumRows, int iNumCols) inline static
adds a single value to all matrix elements
Parameters
ppfMat matrix to analyze
fAdd scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 183 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVectorFloat::addC_I(ppfMat[m], fAdd, iNumCols);
    }
References CVectorFloat::addC_I().
Referenced by CChordIf::initViterbi_().
alloc()
template<typename T > static void CMatrix::alloc (T **& ppfMat, int iNumRows, int iNumCols) inline static
allocates a float matrix and inits it with zeros
Parameters
ppfMat (empty double pointer, to be allocated)
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 21 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        CVector::alloc(ppfMat, iNumRows);
        assert(ppfMat);
        for (auto m = 0; m < iNumRows; m++)
            CVector::alloc(ppfMat[m], iNumCols);
    }
References CVector::alloc().
Referenced by CFeatureSpectralMfccs::allocDctMat_(), CBlockAudioFile::CBlockAudioFile(), CChordFromBlockIf::CChordFromBlockIf(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma(), CPitchTimeAuditory::CPitchTimeAuditory(), CSpectrogramIf::generateMelFb_(), CViterbi::init(), CDtw::init(), CChordIf::init_(), CChordIf::initViterbi_(), inv_I(), and CFilter< T >::setInitState_().
copy()
template<typename T > static void CMatrix::copy (T ** ppfDestMat, T ** ppfSrcMat, int iNumRows, int iNumCols) inline static
copies matrix content to another matrix
Parameters
ppfDestMat (destination matrix, user allocated)
ppfSrcMat (source matrix)
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 244 of file Matrix.h.
    {
        assert(ppfDestMat);
        assert(ppfSrcMat);
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::copy(ppfDestMat[m], ppfSrcMat[m], iNumCols);
    }
References CVector::copy().
Referenced by CViterbi::init(), and inv_I().
free()
template<typename T > static void CMatrix::free (T **& ppfMat, int iNumRows) inline static
frees a float matrix
Parameters
ppfMat (empty double pointer, to be set to zero)
iNumRows number of rows
Returns
Definition at line 39 of file Matrix.h.
    {
        if (!ppfMat) return;
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::free(ppfMat[m]);
        CVector::free(ppfMat);
        ppfMat = 0;
    }
References CVector::free().
Referenced by CFeatureSpectralMfccs::deleteDctMat_(), CSpectrogramIf::destroyMelFb_(), CChordIf::initViterbi_(), inv_I(), CDtw::reset(), CViterbi::reset(), CChordIf::reset_(), CFilter< T >::setInitState_(), CBlockAudioFile::~CBlockAudioFile(), CChordFromBlockIf::~CChordFromBlockIf(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::~CFeatureSpectralPitchChroma(), and CPitchTimeAuditory::~CPitchTimeAuditory().
getMax()
static float CMatrix::getMax (float ** ppfMat, int iNumRows, int iNumCols) inline static
return maximum value in a matrix
Parameters
ppfMat matrix to analyze
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 159 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        float fGlobalMax = CVectorFloat::getMax(ppfMat[0], iNumCols);
        for (auto m = 1; m < iNumRows; m++)
        {
            float fMax = CVectorFloat::getMax(ppfMat[m], iNumCols);
            if (fMax > fGlobalMax)
                fGlobalMax = fMax;
        }
        return fGlobalMax;
    }
References CVectorFloat::getMax().
Referenced by CChordIf::initViterbi_().
inv_I()
static void CMatrix::inv_I (float ** ppfSrcDest, int iNumRows, int iNumCols) inline static
computes inverse of square matrix
Parameters
ppfSrcDest input and output matrix (to be modified, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 298 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        const float kSingularityThresh = 1e-15F;
        float** ppfTmp = 0;
        float** ppfEye = 0;
        int    i, j;
        double dDet = 1;
        alloc(ppfTmp, iNumRows, iNumCols);
        copy(ppfTmp, ppfSrcDest, iNumRows, iNumCols);
        alloc(ppfEye, iNumRows, iNumCols);
        setEye(ppfEye, iNumRows, iNumCols);
        if (ppfSrcDest[0][0] == 0)
        {
            i = 1;
            while (i < iNumRows)
            {
                if (ppfSrcDest[i][0] != 0)
                {
                    swapRowCol(ppfSrcDest, 0, i, iNumCols);
                    swapRowCol(ppfEye, 0, i, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        dDet *= ppfSrcDest[0][0];
        CVectorFloat::mulC_I(ppfEye[0], 1.F / ppfSrcDest[0][0], iNumCols);
        CVectorFloat::mulC_I(ppfSrcDest[0], 1.F / ppfSrcDest[0][0], iNumCols);
        for (i = 1; i < iNumRows; i++)
        {
            j = 0;
            if (dDet < kSingularityThresh *1.* kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVectorFloat::subW_I(ppfEye[i], ppfEye[j], ppfSrcDest[i][j], iNumCols);
                CVectorFloat::subW_I(ppfSrcDest[i], ppfSrcDest[j], ppfSrcDest[i][j], iNumCols);
                j++;
            }
            if (ppfSrcDest[i][i] != 0)
            {
                dDet *= ppfSrcDest[i][i];
                CVectorFloat::mulC_I(ppfEye[i], 1.F / ppfSrcDest[i][i], iNumCols);
                CVectorFloat::mulC_I(ppfSrcDest[i], 1.F / ppfSrcDest[i][i], iNumCols);
            }
            if (ppfSrcDest[i][i] == 0)
            {
                for (int j1 = i + 1; j1 < iNumCols; j1++)
                {
                    if (ppfSrcDest[i][j1] != 0)         // Column pivotting not supported
                    {
                        for (int i1 = 0; i1 < iNumRows; i1++)
{
                            for (j = 0; j < iNumCols; j++)
                                ppfSrcDest[i1][j] = ppfTmp[i1][j];
                        }
                        inv_I(ppfTmp, iNumRows, iNumCols);
                        copy(ppfSrcDest, ppfTmp, iNumRows, iNumCols);
                        CMatrix::free(ppfTmp, iNumRows);
                        CMatrix::free(ppfEye, iNumRows);
                        return;
                    }
                }
            }
        }
        for (i = iNumRows - 1; i > 0; i--)
        {
            for (j = i - 1; j >= 0; j--)
            {
                CVectorFloat::subW_I(ppfEye[j], ppfEye[i], ppfSrcDest[j][i], iNumCols);
                CVectorFloat::subW_I(ppfSrcDest[j], ppfSrcDest[i], ppfSrcDest[j][i], iNumCols);
            }
        }
        copy(ppfSrcDest, ppfEye, iNumRows, iNumCols);
        CMatrix::free(ppfTmp, iNumRows);
        CMatrix::free(ppfEye, iNumRows);
    }
References alloc(), copy(), free(), inv_I(), CVectorFloat::mulC_I(), setEye(), CVectorFloat::subW_I(), and swapRowCol().
Referenced by inv_I(), and CFilter< T >::setInitState_().
mulC_I()
static void CMatrix::mulC_I (float ** ppfMat, float fScale, int iNumRows, int iNumCols) inline static
multiplies the whole matrix with a single factor
Parameters
ppfMat matrix to analyze
fScale scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 201 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVectorFloat::mulC_I(ppfMat[m], fScale, iNumCols);
    }
References CVectorFloat::mulC_I().
Referenced by CChordIf::initViterbi_().
mulMatColVec()
static void CMatrix::mulMatColVec (float * pfDestColVec, float ** ppfMatrix, const float * pfSrcColVec, int iNumMatRows, int iNumMatCols) inline static
multiplies a matrix with a column vector (MAT * VEC)
Parameters
pfDestColVec resulting (column) vector of length iNumMatRows (to be written, user allocated)
ppfMatrix matrix to be multiplied
pfSrcColVec (column) vector to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 59 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(pfDestColVec);
        assert(pfSrcColVec);
        assert(ppfMatrix);
        assert(ppfMatrix[0]);
        for (auto m = 0; m < iNumMatRows; m++)
            pfDestColVec[m] = CVectorFloat::mulScalar(ppfMatrix[m], pfSrcColVec, iNumMatCols);
    }
References CVectorFloat::mulScalar().
Referenced by CChordFromBlockIf::compChordProb(), and CFilter< T >::setInitState_().
mulMatMat()
static void CMatrix::mulMatMat (float ** ppfDest, float ** ppfSrc1, float ** ppfSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols) inline static
multiplies a matrix with a matrix (MAT1 * MAT2)
Parameters
ppfDest resulting matrix of dimension iNum1Rows x iNum2Cols (to be written, user allocated)
ppfSrc1 first matrix to be multiplied
ppfSrc2 second matrix to be multiplied
iNum1Rows number of rows in matrix 1
iNum1Cols number of columns in matrix 1 (has to equal iNum2Rows)
iNum2Rows number of rows in matrix 2 (has to equal iNum1Col)
iNum2Cols number of columns in matrix 2
Returns
Definition at line 105 of file Matrix.h.
    {
        assert(iNum1Rows > 0);
        assert(iNum1Cols > 0);
        assert(iNum2Rows > 0);
        assert(iNum2Cols > 0);
        assert(iNum1Cols == iNum2Rows);
        assert(ppfDest);
        assert(ppfDest[0]);
        assert(ppfSrc1);
        assert(ppfSrc1[0]);
        assert(ppfSrc2);
        assert(ppfSrc2[0]);
        iNum2Rows = iNum1Cols; // avoid compiler warning
        for (auto m = 0; m < iNum1Rows; m++)
        {
            for (auto n = 0; n < iNum2Cols; n++)
            {
                ppfDest[m][n] = 0.F;
                for (auto k = 0; k < iNum1Cols; k++)
                    ppfDest[m][n] += ppfSrc1[m][k] * ppfSrc2[k][n];
            }
        }
    }
mulRowVecMat()
static void CMatrix::mulRowVecMat (float * pfDestRowVec, const float * pfSrcRowVec, float ** ppfMatrix, int iNumMatRows, int iNumMatCols) inline static
multiplies a row vector with a matrix (VEC * MAT)
Parameters
pfDestRowVec resulting (row) vector of length iNumMatCols (to be written, user allocated)
pfSrcRowVec (column) vector to be multiplied
ppfMatrix matrix to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 80 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(pfDestRowVec);
        assert(pfSrcRowVec);
        assert(ppfMatrix);
        assert(ppfMatrix[0]);
        CVectorFloat::setZero(pfDestRowVec, iNumMatCols);
        for (auto n = 0; n < iNumMatCols; n++)
            for (auto m = 0; m < iNumMatRows; m++)
                pfDestRowVec[n] += pfSrcRowVec[m] * ppfMatrix[m][n];
    }
References CVectorFloat::setZero().
setCol()
template<typename T > static void CMatrix::setCol (T ** ppfDestMat, T * pfSrcVec, int iColIdx, int iNumRows) inline static
copies vector content to a column
Parameters
ppfDestMat (destination matrix, user allocated)
pfSrcVec (source vector)
iColIdx index of row to copy to
iNumRows number of columns
Returns
Definition at line 281 of file Matrix.h.
    {
        assert(ppfDestMat);
        assert(pfSrcVec);
        assert(iColIdx >= 0);
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            ppfDestMat[m][iColIdx] = pfSrcVec[m];
    }
Referenced by CChordIf::compChords(), and CChordIf::initViterbi_().
setEye()
static void CMatrix::setEye (float ** ppfDest, int iNumRows, int iNumCols) inline static
fills matrix with ones on the diagonal, zeros elsewhere
Parameters
ppfDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 138 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(ppfDest);
        assert(ppfDest[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            CVectorFloat::setZero(ppfDest[m], iNumCols);
            ppfDest[m][m] = 1.F;
        }
    }
References CVectorFloat::setZero().
Referenced by inv_I().
setRow()
template<typename T > static void CMatrix::setRow (T ** ppfDestMat, T * pfSrcVec, int iRowIdx, int iNumCols) inline static
copies vector content to a row
Parameters
ppfDestMat (destination matrix, user allocated)
pfSrcVec (source vector)
iRowIdx index of row to copy to
iNumCols number of columns
Returns
Definition at line 263 of file Matrix.h.
    {
        assert(ppfDestMat);
        assert(pfSrcVec);
        assert(iRowIdx >= 0);
        assert(iNumCols > 0);
        CVector::copy(ppfDestMat[iRowIdx], pfSrcVec, iNumCols);
    }
References CVector::copy().
swapRowCol()
static void CMatrix::swapRowCol (float ** ppfSrcDest, int iRowIdx, int iColIdx, int iNumCols) inline static
swaps a matrix row with a column in a square matrix
Parameters
ppfSrcDest resulting matrix (to be modified)
iRowIdx index of row
iColIdx index of columns
iNumCols number of columns in the matrix
Returns
Definition at line 220 of file Matrix.h.
    {
        assert(iRowIdx > 0);
        assert(iColIdx > 0);
        assert(iNumCols > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            float fTmp = ppfSrcDest[iRowIdx][n];
            ppfSrcDest[iRowIdx][n] = ppfSrcDest[iColIdx][n];
            ppfSrcDest[iColIdx][n] = fTmp;
        }
    }
Referenced by inv_I().
The documentation for this class was generated from the following file:
Matrix.h