ACA: CChordIf Class Reference
CChordIf Class Reference
class for computation of a magnitude Chord from either a file or a vector
#include <Chord.h>
Public Types
enum Chords_t {
kCMajor , kCsMajor , kDMajor , kDsMajor ,
kEMajor , kFMajor , kFsMajor , kGMajor ,
kGsMajor , kAMajor , kAsMajor , kBMajor ,
kCMinor , kCsMinor , kDMinor , kDsMinor ,
kEMinor , kFMinor , kFsMinor , kGMinor ,
kGsMinor , kAMinor , kAsMinor , kBMinor ,
kNoChord , kNumChords
}
Public Member Functions
Error_t getNumBlocks (int &iNumBlocks) const
int getNumBlocks () const
float getTimeStamp (int iBlockIdx) const
Error_t getTimeStamps (float *pfAxisTicks) const
Error_t compChords (Chords_t *peChord, bool bWithViterbi=true)
Static Public Member Functions
static Error_t create (CChordIf *&pCInstance, const std::string &strAudioFilePath, int iBlockLength=8192, int iHopLength=2048)
static Error_t create (CChordIf *&pCInstance, const float *pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength=8192, int iHopLength=2048)
static Error_t destroy (CChordIf *&pCInstance)
static std::string getChordString (Chords_t eChordIdx)
static Chords_t getChordIdxFromString (std::string sChordString)
Protected Member Functions
CChordIf ()
virtual ~CChordIf ()
CChordIf (const CChordIf &that)
CChordIf & operator= (const CChordIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ ()
init configuration
void initViterbi_ ()
void computeMagSpectrum_ ()
Protected Attributes
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CChordFromBlockIf * m_pCChord = 0
CFft * m_pCFft = 0
fft instance
CViterbi * m_pCViterbi = 0
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcessBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcessBuff1 = 0
temporary buffer
float ** m_ppfChordProbs = 0
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a magnitude Chord from either a file or a vector
Definition at line 18 of file Chord.h.
Member Enumeration Documentation
Chords_t
enum CChordIf::Chords_t
detectable chords
Enumerator
kCMajor
kCsMajor
kDMajor
kDsMajor
kEMajor
kFMajor
kFsMajor
kGMajor
kGsMajor
kAMajor
kAsMajor
kBMajor
kCMinor
kCsMinor
kDMinor
kDsMinor
kEMinor
kFMinor
kFsMinor
kGMinor
kGsMinor
kAMinor
kAsMinor
kBMinor
kNoChord
kNumChords
Definition at line 23 of file Chord.h.
    {
        kCMajor,
        kCsMajor,
        kDMajor,
        kDsMajor,
        kEMajor,
        kFMajor,
        kFsMajor,
        kGMajor,
        kGsMajor,
        kAMajor,
        kAsMajor,
        kBMajor,
        kCMinor,
        kCsMinor,
        kDMinor,
        kDsMinor,
        kEMinor,
        kFMinor,
        kFsMinor,
        kGMinor,
        kGsMinor,
        kAMinor,
        kAsMinor,
        kBMinor,
        kNoChord,
        kNumChords
    };
Constructor & Destructor Documentation
CChordIf() [1/2]
CChordIf::CChordIf () protected
Definition at line 94 of file Chord.cpp.
{
    reset_();
}
References reset_().
~CChordIf()
CChordIf::~CChordIf () inline protected virtual
Definition at line 99 of file Chord.cpp.
{
    reset_();
}
References reset_().
CChordIf() [2/2]
CChordIf::CChordIf (const CChordIf & that) protected
Member Function Documentation
compChords()
Error_t CChordIf::compChords (Chords_t * peChord, bool bWithViterbi = true)
performs the Chord computation for 1 dimensional Chords and writes the result
Parameters
peChord resulting chord indices (user-allocated, to be written, dimensions from CChordIf::getNumBlocks)
bWithViterbi use HMM post-processing
Returns
Error_t
Definition at line 197 of file Chord.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!peChord)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcessBuff1);
    assert(m_pCBlockAudio);
    assert(m_pCNormalize);
    assert(m_pCChord);
    auto iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        float fTmp = 0;
        long long iMaxIdx = -1;
        float afChordProb[kNumChords] = { 0 };
        // retrieve the next audio block
        m_pCBlockAudio->getNextBlock(m_pfProcessBuff1);
        // normalize if specified
        if (m_pCNormalize)
            m_pCNormalize->normalizeBlock(m_pfProcessBuff1, m_iBlockLength);
        assert(m_pfProcessBuff2);
        assert(m_pCFft);
        computeMagSpectrum_();
        // compute instantaneous chord probs
        m_pCChord->compChordProb(afChordProb, m_pfProcessBuff1);
        // store result
        if (bWithViterbi)
            CMatrix::setCol(m_ppfChordProbs, afChordProb, n, kNumChords);
        else
        {
            CVectorFloat::findMax(afChordProb, fTmp, iMaxIdx, kNumChords);
            peChord[n] = static_cast<Chords_t>(iMaxIdx);
        }
    }
    // compute viterbi
    if (bWithViterbi)
    {
        int* piTmp = 0;
        CVector::alloc(piTmp, iNumBlocks);
        m_pCViterbi->compViterbi(m_ppfChordProbs);
        m_pCViterbi->getStateSequence(piTmp);
        for (auto n = 0; n < iNumBlocks; n++)
            peChord[n] = static_cast<Chords_t>(piTmp[n]);
        CVector::free(piTmp);
    }
    return Error_t::kNoError;
}
References CVector::alloc(), CChordFromBlockIf::compChordProb(), computeMagSpectrum_(), CViterbi::compViterbi(), CVectorFloat::findMax(), CVector::free(), CBlockAudioIf::getNextBlock(), CBlockAudioIf::getNumBlocks(), CViterbi::getStateSequence(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, kNumChords, m_bIsInitialized, m_iBlockLength, m_pCBlockAudio, m_pCChord, m_pCFft, m_pCNormalize, m_pCViterbi, m_pfProcessBuff1, m_pfProcessBuff2, m_ppfChordProbs, CNormalizeAudio::normalizeBlock(), and CMatrix::setCol().
Referenced by main().
computeMagSpectrum_()
void CChordIf::computeMagSpectrum_ () protected
Definition at line 355 of file Chord.cpp.
{
    assert(m_pCFft);
    // compute magnitude spectrum (hack
    m_pCFft->compFft(m_pfProcessBuff2, m_pfProcessBuff1);
    m_pCFft->getMagnitude(m_pfProcessBuff1, m_pfProcessBuff2);
    CVectorFloat::mulC_I(m_pfProcessBuff2, 2.F, m_pCFft->getLength(CFft::kLengthMagnitude));
}
References CFft::compFft(), CFft::getLength(), CFft::getMagnitude(), CFft::kLengthMagnitude, m_pCFft, m_pfProcessBuff1, m_pfProcessBuff2, and CVectorFloat::mulC_I().
Referenced by compChords().
create() [1/2]
Error_t CChordIf::create (CChordIf *& pCInstance, const float * pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength = 8192, int iHopLength = 2048) static
initializes a Chord instance from audio data
Parameters
pCInstance pointer to instance to be written
pfAudio complete audio data
iNumFrames length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in Frames
iHopLength hop length in Frames
Returns
Error_t
Definition at line 119 of file Chord.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumFrames <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CChordFromVector(pfAudio, iNumFrames, fSampleRate, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, and kNoError.
create() [2/2]
Error_t CChordIf::create (CChordIf *& pCInstance, const std::string & strAudioFilePath, int iBlockLength = 8192, int iHopLength = 2048) static
initializes a Chord instance with file reading
Parameters
pCInstance pointer to instance to be written
strAudioFilePath complete path to audio file
iBlockLength FFT block length in Frames
iHopLength hop length in Frames
Returns
Error_t
Definition at line 104 of file Chord.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CChordFromFile(strAudioFilePath, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References CUtil::isPowOf2(), kFunctionInvalidArgsError, and kNoError.
Referenced by main().
destroy()
Error_t CChordIf::destroy (CChordIf *& pCInstance) static
destroys a Chord instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 137 of file Chord.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by main().
getChordIdxFromString()
CChordIf::Chords_t CChordIf::getChordIdxFromString (std::string sChordString) static
returns Chord index from string
Parameters
sChordString string describing the Chord
Returns
Chords_t
Definition at line 295 of file Chord.cpp.
{
    const std::map<std::string, CChordIf::Chords_t> ChordMap
    {
        {"C Major", kCMajor},
        {"C# Major", kCsMajor},
        {"Db Major", kCsMajor},
        {"C# Major/Db Major", kCsMajor},
        {"D Major", kDMajor},
        {"D# Major", kDsMajor},
        {"Eb Major", kDsMajor},
        {"D# Major/Eb Major", kDsMajor},
        {"E Major", kEMajor},
        {"F Major", kFMajor},
        {"F# Majo", kFsMajor},
        {"Gb Major", kFsMajor},
        {"F# Major/Gb Major", kFsMajor},
        {"G Major", kGMajor},
        {"G# Major", kGsMajor},
        {"Ab Major", kGsMajor},
        {"G# Major/Ab Major", kGsMajor},
        {"A Major", kAMajor},
        {"A# Major", kAsMajor},
        {"Bb Major", kAsMajor},
        {"A# Major/Bb Major", kAsMajor},
        {"B Major", kBMajor},
        {"C Minor", kCMinor},
        {"C# Minor", kCsMinor},
        {"Db Minor", kCsMinor},
        {"C# Minor/Db Minor", kCsMinor},
        {"D Minor", kDMinor},
        {"D# Minor", kDsMinor},
        {"Eb Minor", kDsMinor},
        {"D# Minor/Eb Minor", kDsMinor},
        {"E Minor", kEMinor},
        {"F Minor", kFMinor},
        {"F# Minor", kFsMinor},
        {"Gb Minor", kFsMinor},
        {"F# Minor/Gb Minor", kFsMinor},
        {"G Minor", kGMinor},
        {"G# Minor", kGsMinor},
        {"Ab Minor", kGsMinor},
        {"G# Minor/Ab Minor", kGsMinor},
        {"A Minor", kAMinor},
        {"A# Minor", kAsMinor},
        {"Bb Minor", kAsMinor},
        {"A# Minor/Bb Minor", kAsMinor},
        {"B Minor", kBMinor},
        {"No Chord", kNoChord}
    };
    auto search = ChordMap.find(sChordString);
    if (search != ChordMap.end())
        return ChordMap.at(sChordString);
    else
        return kNumChords;
}
References kAMajor, kAMinor, kAsMajor, kAsMinor, kBMajor, kBMinor, kCMajor, kCMinor, kCsMajor, kCsMinor, kDMajor, kDMinor, kDsMajor, kDsMinor, kEMajor, kEMinor, kFMajor, kFMinor, kFsMajor, kFsMinor, kGMajor, kGMinor, kGsMajor, kGsMinor, kNoChord, and kNumChords.
getChordString()
std::string CChordIf::getChordString (Chords_t eChordIdx) static
returns Chord name as string
Parameters
eChordIdx Chord index
Returns
std::string
Definition at line 259 of file Chord.cpp.
{
    const std::map<CChordIf::Chords_t, std::string> ChordMap
    {
        {kCMajor, "C Major"},
        {kCsMajor, "C# Major/Db Major"},
        {kDMajor, "D Major"},
        {kDsMajor, "D# Major/Eb Major"},
        {kEMajor, "E Major"},
        {kFMajor, "F Major"},
        {kFsMajor, "F# Major/Gb Major"},
        {kGMajor, "G Major"},
        {kGsMajor, "G# Major/Ab Major"},
        {kAMajor, "A Major"},
        {kAsMajor, "A# Major/Bb Major"},
        {kBMajor, "B Major"},
        {kCMinor, "C Minor"},
        {kCsMinor, "C# Minor/Db Minor"},
        {kDMinor, "D Minor"},
        {kDsMinor, "D# Minor/Eb Minor"},
        {kEMinor, "E Minor"},
        {kFMinor, "F Minor"},
        {kFsMinor, "F# Minor/Gb Minor"},
        {kGMinor, "G Minor"},
        {kGsMinor, "G# Minor/Ab Minor"},
        {kAMinor, "A Minor"},
        {kAsMinor, "A# Minor/Bb Minor"},
        {kBMinor, "B Minor"},
        {kNoChord, "No Chord"}
    };
    return ChordMap.at(eChordIdx);
}
References kAMajor, kAMinor, kAsMajor, kAsMinor, kBMajor, kBMinor, kCMajor, kCMinor, kCsMajor, kCsMinor, kDMajor, kDMinor, kDsMajor, kDsMinor, kEMajor, kEMinor, kFMajor, kFMinor, kFsMajor, kFsMinor, kGMajor, kGMinor, kGsMajor, kGsMinor, and kNoChord.
Referenced by main().
getNumBlocks() [1/2]
int CChordIf::getNumBlocks () const
returns size of vector to be allocated by user
Returns
int
Definition at line 163 of file Chord.cpp.
{
    assert(m_bIsInitialized);
    assert(m_pCBlockAudio);
    return static_cast<int>(m_pCBlockAudio->getNumBlocks());
}
References CBlockAudioIf::getNumBlocks(), m_bIsInitialized, and m_pCBlockAudio.
Referenced by getNumBlocks().
getNumBlocks() [2/2]
Error_t CChordIf::getNumBlocks (int & iNumBlocks) const
returns size of vector to be allocated by user
Parameters
iNumBlocks (number of blocks, to be written)
Returns
Error_t
Definition at line 145 of file Chord.cpp.
{
    if (!m_bIsInitialized)
    {
        iNumBlocks = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumBlocks = this->getNumBlocks();
    return Error_t::kNoError;
}
References getNumBlocks(), kFunctionIllegalCallError, kNoError, and m_bIsInitialized.
Referenced by main().
getTimeStamp()
float CChordIf::getTimeStamp (int iBlockIdx) const
returns time stamps
Parameters
iBlockIdx index of block
Returns
float time stamp
Definition at line 171 of file Chord.cpp.
{
    return m_pCBlockAudio->getTimeStamp(iBlockIdx);
}
References CBlockAudioIf::getTimeStamp(), and m_pCBlockAudio.
Referenced by main().
getTimeStamps()
Error_t CChordIf::getTimeStamps (float * pfAxisTicks) const
returns time stamps
Parameters
pfAxisTicks (user- allocated, to be written) length iNumBlocks
Returns
Error_t
Definition at line 176 of file Chord.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
        pfAxisTicks[n] = m_pCBlockAudio->getTimeStamp(n);
    return Error_t::kNoError;
}
References CBlockAudioIf::getNumBlocks(), CBlockAudioIf::getTimeStamp(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, and m_pCBlockAudio.
init_()
Error_t CChordIf::init_ () protected
init configuration
Definition at line 395 of file Chord.cpp.
{
    // initialize FFT and fft  buffer
    m_pCFft = new CFft();
    m_pCFft->init(m_iBlockLength);
    initViterbi_();
    // allocate processing memory
    CVector::alloc(m_pfProcessBuff1, m_pCFft->getLength(CFft::kLengthFft));
    CVector::alloc(m_pfProcessBuff2, m_pCFft->getLength(CFft::kLengthFft));
    CChordFromBlockIf::create(m_pCChord, m_pCFft->getLength(CFft::kLengthMagnitude), m_fSampleRate);
    CMatrix::alloc(m_ppfChordProbs, kNumChords, static_cast<int>(m_pCBlockAudio->getNumBlocks()));
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), CChordFromBlockIf::create(), CFft::getLength(), CBlockAudioIf::getNumBlocks(), CFft::init(), initViterbi_(), CFft::kLengthFft, CFft::kLengthMagnitude, kNoError, kNumChords, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_pCBlockAudio, m_pCChord, m_pCFft, m_pfProcessBuff1, m_pfProcessBuff2, and m_ppfChordProbs.
Referenced by CChordFromFile::CChordFromFile(), and CChordFromVector::CChordFromVector().
initViterbi_()
void CChordIf::initViterbi_ () protected
Definition at line 414 of file Chord.cpp.
{
    int iNumBlocks = static_cast<int>(m_pCBlockAudio->getNumBlocks());
    /////////////////////////////
    // start probabilities
    float afStartProb[kNumChords] = { 0 };
    CVectorFloat::setValue(afStartProb, 1.F / (kNumChords + 1), kNumChords);
    afStartProb[kNoChord] *= 2.F;
    /////////////////////////////
    // transition probabilities
    float** ppfTransProb = 0;
    CMatrix::alloc(ppfTransProb, kNumChords, kNumChords);
    const int aiCircleOfFifths[24] = { 0, -5, 2, -3, 4, -1, 6, 1, -4, 3, -2, 5, -3, 4, -1, 6, 1, -4, 3, -2, 5, 0, -5, 2 };
    float fRadius = 1.F;
    float fDistance = .5F;
    for (auto m = 0; m < kNumChords-1; m++)
    {
        float fX1 = static_cast<float>(fRadius * std::cos(2. * M_PI * aiCircleOfFifths[m] / 12.));
        float fY1 = static_cast<float>(fRadius * std::sin(2. * M_PI * aiCircleOfFifths[m] / 12.));
        float fZ1 = fDistance - ((m < 12) ? 0 : fDistance);
        for (auto n = 0; n < kNumChords - 1; n++)
        {
            float fXDist = static_cast<float>(fX1 - fRadius * std::cos(2. * M_PI * aiCircleOfFifths[n] / 12.));
            float fYDist = static_cast<float>(fY1 - fRadius * std::sin(2. * M_PI * aiCircleOfFifths[n] / 12.));
            float fZDist = fZ1 - (fDistance - ((n < 12) ? 0 : fDistance));
            ppfTransProb[m][n] = .1F + std::sqrt(fXDist * fXDist + fYDist * fYDist + fZDist * fZDist);
        }
    }
    // convert to probabilities
    CMatrix::mulC_I(ppfTransProb, -1.F / (.1F + CMatrix::getMax(ppfTransProb, kNumChords, kNumChords)), kNumChords, kNumChords);
    CMatrix::addC_I(ppfTransProb, 1.F, kNumChords, kNumChords);
    // no chord probs
    CVectorFloat::setValue(ppfTransProb[kNoChord], 1.F / kNumChords, kNumChords);
    CMatrix::setCol(ppfTransProb, ppfTransProb[kNoChord], kNoChord, kNumChords);
    // normalization
    for (auto m = 0; m < kNumChords; m++)
        CVectorFloat::mulC_I(ppfTransProb[m], 1.F / CVectorFloat::getSum(ppfTransProb[m], kNumChords), kNumChords);
    /////////////////////////////
    // instance creation and initialization
    m_pCViterbi = new CViterbi();
    m_pCViterbi->init(ppfTransProb, afStartProb, kNumChords, iNumBlocks);
    // free temp memory
    CMatrix::free(ppfTransProb, kNumChords);
}
References CMatrix::addC_I(), CMatrix::alloc(), CMatrix::free(), CMatrix::getMax(), CBlockAudioIf::getNumBlocks(), CVectorFloat::getSum(), CViterbi::init(), kNoChord, kNumChords, m_pCBlockAudio, m_pCViterbi, M_PI, CMatrix::mulC_I(), CVectorFloat::mulC_I(), CMatrix::setCol(), and CVectorFloat::setValue().
Referenced by init_().
operator=()
CChordIf & CChordIf::operator= (const CChordIf & c) protected
reset_()
Error_t CChordIf::reset_ () protected
reset configuration
Definition at line 367 of file Chord.cpp.
{
    CVector::free(m_pfProcessBuff1);
    CVector::free(m_pfProcessBuff2);
    CMatrix::free(m_ppfChordProbs, kNumChords);
    delete m_pCFft;
    m_pCFft = 0;
    delete m_pCNormalize;
    m_pCNormalize = 0;
    delete m_pCViterbi;
    m_pCViterbi = 0;
    CBlockAudioIf::destroy(m_pCBlockAudio);
    CChordFromBlockIf::destroy(m_pCChord);
    m_iBlockLength = 0;
    m_iHopLength = 0;
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CBlockAudioIf::destroy(), CChordFromBlockIf::destroy(), CVector::free(), CMatrix::free(), kNoError, kNumChords, m_bIsInitialized, m_iBlockLength, m_iHopLength, m_pCBlockAudio, m_pCChord, m_pCFft, m_pCNormalize, m_pCViterbi, m_pfProcessBuff1, m_pfProcessBuff2, and m_ppfChordProbs.
Referenced by CChordFromFile::CChordFromFile(), CChordIf(), and ~CChordIf().
Member Data Documentation
m_bIsInitialized
bool CChordIf::m_bIsInitialized = false protected
true if initialized
Definition at line 153 of file Chord.h.
Referenced by compChords(), getNumBlocks(), getTimeStamps(), init_(), and reset_().
m_fSampleRate
float CChordIf::m_fSampleRate = 0 protected
sample rate
Definition at line 146 of file Chord.h.
Referenced by CChordFromFile::CChordFromFile(), CChordFromVector::CChordFromVector(), getTimeStamps(), and init_().
m_iBlockLength
int CChordIf::m_iBlockLength = 0 protected
fft length
Definition at line 143 of file Chord.h.
Referenced by CChordFromFile::CChordFromFile(), CChordFromVector::CChordFromVector(), compChords(), getTimeStamps(), init_(), and reset_().
m_iHopLength
int CChordIf::m_iHopLength = 0 protected
hop length
Definition at line 144 of file Chord.h.
Referenced by CChordFromFile::CChordFromFile(), CChordFromVector::CChordFromVector(), getTimeStamps(), and reset_().
m_pCBlockAudio
CBlockAudioIf* CChordIf::m_pCBlockAudio = 0 protected
instantiate for blocking time domain signal
Definition at line 137 of file Chord.h.
Referenced by CChordFromFile::CChordFromFile(), CChordFromVector::CChordFromVector(), compChords(), getNumBlocks(), getTimeStamp(), getTimeStamps(), init_(), initViterbi_(), and reset_().
m_pCChord
CChordFromBlockIf* CChordIf::m_pCChord = 0 protected
Definition at line 139 of file Chord.h.
Referenced by compChords(), init_(), and reset_().
m_pCFft
CFft* CChordIf::m_pCFft = 0 protected
fft instance
Definition at line 140 of file Chord.h.
Referenced by compChords(), computeMagSpectrum_(), init_(), and reset_().
m_pCNormalize
CNormalizeAudio* CChordIf::m_pCNormalize = 0 protected
instantiate if audio file normalization is wanted
Definition at line 135 of file Chord.h.
Referenced by CChordFromFile::CChordFromFile(), CChordFromVector::CChordFromVector(), compChords(), reset_(), and CChordFromFile::~CChordFromFile().
m_pCViterbi
CViterbi* CChordIf::m_pCViterbi = 0 protected
Definition at line 141 of file Chord.h.
Referenced by compChords(), initViterbi_(), and reset_().
m_pfProcessBuff1
float* CChordIf::m_pfProcessBuff1 = 0 protected
temporary buffer
Definition at line 149 of file Chord.h.
Referenced by compChords(), computeMagSpectrum_(), init_(), reset_(), and CChordFromFile::~CChordFromFile().
m_pfProcessBuff2
float* CChordIf::m_pfProcessBuff2 = 0 protected
temporary buffer for current spectrum
Definition at line 148 of file Chord.h.
Referenced by compChords(), computeMagSpectrum_(), init_(), and reset_().
m_ppfChordProbs
float** CChordIf::m_ppfChordProbs = 0 protected
Definition at line 151 of file Chord.h.
Referenced by compChords(), init_(), and reset_().
The documentation for this class was generated from the following files:
Chord.h
Chord.cpp