ACA: CMatrix Class Reference
CMatrix Class Reference
class with static functions for matrix operations with type float (functionality only added when needed)
#include <Matrix.h>
Static Public Member Functions
template<typename T >
static void alloc (T **&ppfMat, int iNumRows, int iNumCols)
template<typename T >
static void free (T **&ppfMat, int iNumRows)
template<typename T >
static void setZero (T **ppfMat, int iNumRows, int iNumCols)
template<typename T >
static void setValue (T **ppfMat, T tValue, int iNumRows, int iNumCols)
template<typename T >
static void setRand (T **ppfMat, int iNumRows, int iNumCols)
template<typename T >
static void setCol (T **ppfDestMat, T *pfSrcVec, int iColIdx, int iNumRows)
template<typename T >
static void setZeroBelowThresh (T **ppfMat, int iNumRows, int iNumCols, T tThresh)
static void setEye (float **ppfDest, int iNumRows, int iNumCols)
static float getSum (float **ppfMat, int iNumRows, int iNumCols, bool bAbs=false)
static float getNorm (float **ppfMat, int iNumRows, int iNumCols)
static void vecnorm_I (float **ppfSrcDest, int iNumRows, int iNumCols)
static float calcKlDivergence (float **ppfSrc1, float **ppfSrc2, int iNumRows, int iNumCols)
static void transpose (float **ppfDest, float **ppfSrc, int iNumSrcRows, int iNumSrcCols)
static void rearrangeRows (float **ppfSrcDest, int *piRowIndices, int iNumRows)
static void diag (float *pfDest, float **ppfSrc, int iNumSrcRows, int iNumSrcCols)
static void mulMatColVec (float *pfDestColVec, float **ppfMat, const float *pfSrcColVec, int iNumMatRows, int iNumMatCols)
static void mulRowVecMat (float *pfDestRowVec, const float *pfSrcRowVec, float **ppfMat, int iNumMatRows, int iNumMatCols)
static void mulMatMat (float **ppfDest, float **ppfSrc1, float **ppfSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols)
static void mul_I (float **ppfSrcDest, float **ppfSrc, int iNumRows, int iNumCols)
static void add_I (float **ppfSrcDest, float **ppfSrc, int iNumRows, int iNumCols)
static void sub_I (float **ppfSrcDest, float **ppfSrc, int iNumRows, int iNumCols)
static void div_I (float **ppfSrcDest, float **ppfSrc, int iNumRows, int iNumCols, bool bAddSmallConst=false)
static float getMax (float **ppfMat, int iNumRows, int iNumCols)
static void addC_I (float **ppfMat, float fAdd, int iNumRows, int iNumCols)
static void mulC_I (float **ppfMat, float fScale, int iNumRows, int iNumCols)
static void swapRowCol (float **ppfSrcDest, int iRowIdx, int iColIdx, int iNumCols)
template<typename T >
static void copy (T **ppfDestMat, T **ppfSrcMat, int iNumRows, int iNumCols)
template<typename T >
static void setRow (T **ppfDestMat, T *pfSrcVec, int iRowIdx, int iNumCols)
static void inv_I (float **ppfSrcDest, int iNumRows, int iNumCols)
Detailed Description
class with static functions for matrix operations with type float (functionality only added when needed)
Definition at line 11 of file Matrix.h.
Member Function Documentation
add_I()
static void CMatrix::add_I (float ** ppfSrcDest, float ** ppfSrc, int iNumRows, int iNumCols) inline static
elementwise addition of two matrices inplace
Parameters
ppfSrcDest resulting matrix
ppfSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 449 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                ppfSrcDest[m][n] += ppfSrc[m][n];
        }
    }
addC_I()
static void CMatrix::addC_I (float ** ppfMat, float fAdd, int iNumRows, int iNumCols) inline static
adds a single value to all matrix elements
Parameters
ppfMat matrix to analyze
fAdd scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 544 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVectorFloat::addC_I(ppfMat[m], fAdd, iNumCols);
    }
References CVectorFloat::addC_I().
Referenced by CChordIf::initViterbi_(), and CNmf::runNmfIter().
alloc()
template<typename T > static void CMatrix::alloc (T **& ppfMat, int iNumRows, int iNumCols) inline static
allocates a float matrix and inits it with zeros
Parameters
ppfMat (empty double pointer, to be allocated)
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 22 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        CVector::alloc(ppfMat, iNumRows);
        assert(ppfMat);
        for (auto m = 0; m < iNumRows; m++)
            CVector::alloc(ppfMat[m], iNumCols);
    }
References CVector::alloc().
Referenced by CFeatureSpectralMfccs::allocDctMat_(), CBlockAudioFile::CBlockAudioFile(), CChordFromBlockIf::CChordFromBlockIf(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma(), CPitchTimeAuditory::CPitchTimeAuditory(), CSpectrogramIf::generateMelFb_(), CNmf::init(), CViterbi::init(), CPca::init(), CDtw::init(), CNmfResult::init(), CChordIf::init_(), CChordIf::initViterbi_(), inv_I(), and CFilter< T >::setInitState_().
calcKlDivergence()
static float CMatrix::calcKlDivergence (float ** ppfSrc1, float ** ppfSrc2, int iNumRows, int iNumCols) inline static
comnputes kl divergence between two matrices
Parameters
ppfSrc1 matrix of dimension iNumRows x iNumCols
ppfSrc2 matrix of dimension iNumRows x iNumCols
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 246 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfSrc1);
        assert(ppfSrc1[0]);
        assert(ppfSrc2);
        assert(ppfSrc2[0]);
        float fResult = 0;
        for (int i = 0; i < iNumRows; i++)
        {
            for (int j = 0; j < iNumCols; j++)
                fResult += ppfSrc1[i][j] * (std::log((ppfSrc1[i][j] + 1e-24F) / (ppfSrc2[i][j] + 1e-24F)) - 1.F) + ppfSrc2[i][j];
        }
        return fResult;
    }
Referenced by CNmf::runNmfIter().
copy()
template<typename T > static void CMatrix::copy (T ** ppfDestMat, T ** ppfSrcMat, int iNumRows, int iNumCols) inline static
copies matrix content to another matrix
Parameters
ppfDestMat (destination matrix, user allocated)
ppfSrcMat (source matrix)
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 605 of file Matrix.h.
    {
        assert(ppfDestMat);
        assert(ppfSrcMat);
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::copy(ppfDestMat[m], ppfSrcMat[m], iNumCols);
    }
References CVector::copy().
Referenced by CPca::calcSVD(), CNmfResult::getMat(), CViterbi::init(), inv_I(), and CNmf::runNmfIter().
diag()
static void CMatrix::diag (float * pfDest, float ** ppfSrc, int iNumSrcRows, int iNumSrcCols) inline static
returns matrix diagonal as vector
Parameters
pfDest resulting vector of dimension min(iNumSrcRows, iNumCols) (to be written, user allocated)
ppfSrc input matrix of dimension iNumSrcRows x iNumCols
iNumSrcRows number of rows in the matrix
iNumSrcCols number of columns in the matrix
Returns
Definition at line 324 of file Matrix.h.
    {
        assert(iNumSrcRows > 0);
        assert(iNumSrcCols > 0);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        assert(pfDest);
        int iLen = std::min(iNumSrcRows, iNumSrcCols);
        for (auto m = 0; m < iLen; m++)
            pfDest[m] = ppfSrc[m][m];
    }
Referenced by CPca::compPca().
div_I()
static void CMatrix::div_I (float ** ppfSrcDest, float ** ppfSrc, int iNumRows, int iNumCols, bool bAddSmallConst = false) inline static
elementwise division of two matrices inplace
Parameters
ppfSrcDest resulting matrix
ppfSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
bAddSmallConst a small floating point number is added before division if true
Returns
Definition at line 496 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        float fEpsilon = bAddSmallConst? 1e-30F : .0F;
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                ppfSrcDest[m][n] /= (ppfSrc[m][n] + fEpsilon);
        }
    }
Referenced by CNmf::runNmfIter().
free()
template<typename T > static void CMatrix::free (T **& ppfMat, int iNumRows) inline static
frees a float matrix
Parameters
ppfMat (empty double pointer, to be set to zero)
iNumRows number of rows
Returns
Definition at line 40 of file Matrix.h.
    {
        if (!ppfMat) return;
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::free(ppfMat[m]);
        CVector::free(ppfMat);
        ppfMat = 0;
    }
References CVector::free().
Referenced by CFeatureSpectralMfccs::deleteDctMat_(), CSpectrogramIf::destroyMelFb_(), CChordIf::initViterbi_(), inv_I(), CNmfResult::reset(), CNmf::reset(), CPca::reset(), CDtw::reset(), CViterbi::reset(), CChordIf::reset_(), CFilter< T >::setInitState_(), CBlockAudioFile::~CBlockAudioFile(), CChordFromBlockIf::~CChordFromBlockIf(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::~CFeatureSpectralPitchChroma(), and CPitchTimeAuditory::~CPitchTimeAuditory().
getMax()
static float CMatrix::getMax (float ** ppfMat, int iNumRows, int iNumCols) inline static
return maximum value in a matrix
Parameters
ppfMat matrix to analyze
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 520 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        float fGlobalMax = CVectorFloat::getMax(ppfMat[0], iNumCols);
        for (auto m = 1; m < iNumRows; m++)
        {
            float fMax = CVectorFloat::getMax(ppfMat[m], iNumCols);
            if (fMax > fGlobalMax)
                fGlobalMax = fMax;
        }
        return fGlobalMax;
    }
References CVectorFloat::getMax().
Referenced by CChordIf::initViterbi_().
getNorm()
static float CMatrix::getNorm (float ** ppfMat, int iNumRows, int iNumCols) inline static
return the matrix norm (p=1)
Parameters
ppfMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 193 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        float fResult = 0;
        for (auto n = 0; n < iNumCols; n++)
        {
            float fTmp = 0;
            for (auto m = 0; m < iNumRows; m++)
                fTmp += std::abs(ppfMat[m][n]);
            if (fTmp > fResult)
                fResult = fTmp;
        }
        return fResult;
    }
Referenced by CNmf::runNmfIter().
getSum()
static float CMatrix::getSum (float ** ppfMat, int iNumRows, int iNumCols, bool bAbs = false) inline static
adds all matrix elements
Parameters
ppfMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
bAbs flag to indicate whether to sum the absolute values
Returns
Definition at line 172 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        float fResult = 0;
        for (auto m = 0; m < iNumRows; m++)
            fResult += CVectorFloat::getSum(ppfMat[m], iNumCols, bAbs);
        return fResult;
    }
References CVectorFloat::getSum().
inv_I()
static void CMatrix::inv_I (float ** ppfSrcDest, int iNumRows, int iNumCols) inline static
computes inverse of square matrix
Parameters
ppfSrcDest input and output matrix (to be modified, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 640 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        const float kSingularityThresh = 1e-15F;
        float** ppfTmp = 0;
        float** ppfEye = 0;
        int    i, j;
        double dDet = 1;
        alloc(ppfTmp, iNumRows, iNumCols);
        copy(ppfTmp, ppfSrcDest, iNumRows, iNumCols);
        alloc(ppfEye, iNumRows, iNumCols);
        setEye(ppfEye, iNumRows, iNumCols);
        if (ppfSrcDest[0][0] == 0)
        {
            i = 1;
            while (i < iNumRows)
            {
                if (ppfSrcDest[i][0] != 0)
                {
                    swapRowCol(ppfSrcDest, 0, i, iNumCols);
                    swapRowCol(ppfEye, 0, i, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        dDet *= ppfSrcDest[0][0];
        CVectorFloat::mulC_I(ppfEye[0], 1.F / ppfSrcDest[0][0], iNumCols);
        CVectorFloat::mulC_I(ppfSrcDest[0], 1.F / ppfSrcDest[0][0], iNumCols);
        for (i = 1; i < iNumRows; i++)
        {
            j = 0;
            if (dDet < kSingularityThresh *1.* kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVectorFloat::subW_I(ppfEye[i], ppfEye[j], ppfSrcDest[i][j], iNumCols);
                CVectorFloat::subW_I(ppfSrcDest[i], ppfSrcDest[j], ppfSrcDest[i][j], iNumCols);
                j++;
            }
            if (ppfSrcDest[i][i] != 0)
            {
                dDet *= ppfSrcDest[i][i];
                CVectorFloat::mulC_I(ppfEye[i], 1.F / ppfSrcDest[i][i], iNumCols);
                CVectorFloat::mulC_I(ppfSrcDest[i], 1.F / ppfSrcDest[i][i], iNumCols);
            }
            if (ppfSrcDest[i][i] == 0)
            {
                for (int j1 = i + 1; j1 < iNumCols; j1++)
                {
                    if (ppfSrcDest[i][j1] != 0)         // Column pivotting not supported
                    {
                        for (int i1 = 0; i1 < iNumRows; i1++)
{
                            for (j = 0; j < iNumCols; j++)
                                ppfSrcDest[i1][j] = ppfTmp[i1][j];
                        }
                        inv_I(ppfTmp, iNumRows, iNumCols);
                        copy(ppfSrcDest, ppfTmp, iNumRows, iNumCols);
                        CMatrix::free(ppfTmp, iNumRows);
                        CMatrix::free(ppfEye, iNumRows);
                        return;
                    }
                }
            }
        }
        for (i = iNumRows - 1; i > 0; i--)
        {
            for (j = i - 1; j >= 0; j--)
            {
                CVectorFloat::subW_I(ppfEye[j], ppfEye[i], ppfSrcDest[j][i], iNumCols);
                CVectorFloat::subW_I(ppfSrcDest[j], ppfSrcDest[i], ppfSrcDest[j][i], iNumCols);
            }
        }
        copy(ppfSrcDest, ppfEye, iNumRows, iNumCols);
        CMatrix::free(ppfTmp, iNumRows);
        CMatrix::free(ppfEye, iNumRows);
    }
References alloc(), copy(), free(), inv_I(), CVectorFloat::mulC_I(), setEye(), CVectorFloat::subW_I(), and swapRowCol().
Referenced by inv_I(), and CFilter< T >::setInitState_().
mul_I()
static void CMatrix::mul_I (float ** ppfSrcDest, float ** ppfSrc, int iNumRows, int iNumCols) inline static
elementwise multiplication of two matrices inplace
Parameters
ppfSrcDest resulting matrix
ppfSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 426 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                ppfSrcDest[m][n] *= ppfSrc[m][n];
        }
    }
Referenced by CNmf::runNmfIter().
mulC_I()
static void CMatrix::mulC_I (float ** ppfMat, float fScale, int iNumRows, int iNumCols) inline static
multiplies the whole matrix with a single factor
Parameters
ppfMat matrix to analyze
fScale scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 562 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVectorFloat::mulC_I(ppfMat[m], fScale, iNumCols);
    }
References CVectorFloat::mulC_I().
Referenced by CPca::compCov(), and CChordIf::initViterbi_().
mulMatColVec()
static void CMatrix::mulMatColVec (float * pfDestColVec, float ** ppfMat, const float * pfSrcColVec, int iNumMatRows, int iNumMatCols) inline static
multiplies a matrix with a column vector (MAT * VEC)
Parameters
pfDestColVec resulting (column) vector of length iNumMatRows (to be written, user allocated)
ppfMat matrix to be multiplied
pfSrcColVec (column) vector to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 346 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(pfDestColVec);
        assert(pfSrcColVec);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumMatRows; m++)
            pfDestColVec[m] = CVectorFloat::mulScalar(ppfMat[m], pfSrcColVec, iNumMatCols);
    }
References CVectorFloat::mulScalar().
Referenced by CChordFromBlockIf::compChordProb(), and CFilter< T >::setInitState_().
mulMatMat()
static void CMatrix::mulMatMat (float ** ppfDest, float ** ppfSrc1, float ** ppfSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols) inline static
multiplies a matrix with a matrix (MAT1 * MAT2)
Parameters
ppfDest resulting matrix of dimension iNum1Rows x iNum2Cols (to be written, user allocated)
ppfSrc1 first matrix to be multiplied
ppfSrc2 second matrix to be multiplied
iNum1Rows number of rows in matrix 1
iNum1Cols number of columns in matrix 1 (has to equal iNum2Rows)
iNum2Rows number of rows in matrix 2 (has to equal iNum1Col)
iNum2Cols number of columns in matrix 2
Returns
Definition at line 392 of file Matrix.h.
    {
        assert(iNum1Rows > 0);
        assert(iNum1Cols > 0);
        assert(iNum2Rows > 0);
        assert(iNum2Cols > 0);
        assert(iNum1Cols == iNum2Rows);
        assert(ppfDest);
        assert(ppfDest[0]);
        assert(ppfSrc1);
        assert(ppfSrc1[0]);
        assert(ppfSrc2);
        assert(ppfSrc2[0]);
        iNum2Rows = iNum1Cols; // avoid compiler warning
        for (auto m = 0; m < iNum1Rows; m++)
        {
            for (auto n = 0; n < iNum2Cols; n++)
            {
                ppfDest[m][n] = 0.F;
                for (auto k = 0; k < iNum1Cols; k++)
                    ppfDest[m][n] += ppfSrc1[m][k] * ppfSrc2[k][n];
            }
        }
    }
Referenced by CPca::compPca(), and CNmf::runNmfIter().
mulRowVecMat()
static void CMatrix::mulRowVecMat (float * pfDestRowVec, const float * pfSrcRowVec, float ** ppfMat, int iNumMatRows, int iNumMatCols) inline static
multiplies a row vector with a matrix (VEC * MAT)
Parameters
pfDestRowVec resulting (row) vector of length iNumMatCols (to be written, user allocated)
pfSrcRowVec (column) vector to be multiplied
ppfMat matrix to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 367 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(pfDestRowVec);
        assert(pfSrcRowVec);
        assert(ppfMat);
        assert(ppfMat[0]);
        CVectorFloat::setZero(pfDestRowVec, iNumMatCols);
        for (auto n = 0; n < iNumMatCols; n++)
            for (auto m = 0; m < iNumMatRows; m++)
                pfDestRowVec[n] += pfSrcRowVec[m] * ppfMat[m][n];
    }
References CVectorFloat::setZero().
rearrangeRows()
static void CMatrix::rearrangeRows (float ** ppfSrcDest, int * piRowIndices, int iNumRows) inline static
rearrange the rows of a matrix according to a row index vector
Parameters
ppfSrcDest resorted matrix of dimension iNumRows x ?
piRowIndices new indices iNumRows
iNumRows number of rows in the matrix
Returns
Definition at line 295 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(piRowIndices);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        float** ppfTmp = 0;
        CVector::alloc(ppfTmp, iNumRows);
        for (auto m = 0; m < iNumRows; m++)
        {
            assert(piRowIndices[m] < iNumRows);
            assert(piRowIndices[m] >= 0);
            ppfTmp[m] = ppfSrcDest[piRowIndices[m]];
        }
        CVector::copy(ppfSrcDest, ppfTmp, iNumRows);
        CVector::free(ppfTmp);
    }
References CVector::alloc(), CVector::copy(), and CVector::free().
Referenced by CPca::compPca().
setCol()
template<typename T > static void CMatrix::setCol (T ** ppfDestMat, T * pfSrcVec, int iColIdx, int iNumRows) inline static
copies vector content to a column
Parameters
ppfDestMat (destination matrix, user allocated)
pfSrcVec (source vector)
iColIdx index of row to copy to
iNumRows number of columns
Returns
Definition at line 115 of file Matrix.h.
    {
        assert(ppfDestMat);
        assert(pfSrcVec);
        assert(iColIdx >= 0);
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            ppfDestMat[m][iColIdx] = pfSrcVec[m];
    }
Referenced by CChordIf::compChords(), and CChordIf::initViterbi_().
setEye()
static void CMatrix::setEye (float ** ppfDest, int iNumRows, int iNumCols) inline static
fills matrix with ones on the diagonal, zeros elsewhere
Parameters
ppfDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 151 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(ppfDest);
        assert(ppfDest[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            CVectorFloat::setZero(ppfDest[m], iNumCols);
            ppfDest[m][m] = 1.F;
        }
    }
References CVectorFloat::setZero().
Referenced by inv_I().
setRand()
template<typename T > static void CMatrix::setRand (T ** ppfMat, int iNumRows, int iNumCols) inline static
sets a float matrix to random
Parameters
ppfMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 96 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setRand(ppfMat[m], iNumCols);
    }
References CVector::setRand().
Referenced by CNmfResult::init().
setRow()
template<typename T > static void CMatrix::setRow (T ** ppfDestMat, T * pfSrcVec, int iRowIdx, int iNumCols) inline static
copies vector content to a row
Parameters
ppfDestMat (destination matrix, user allocated)
pfSrcVec (source vector)
iRowIdx index of row to copy to
iNumCols number of columns
Returns
Definition at line 624 of file Matrix.h.
    {
        assert(ppfDestMat);
        assert(pfSrcVec);
        assert(iRowIdx >= 0);
        assert(iNumCols > 0);
        CVector::copy(ppfDestMat[iRowIdx], pfSrcVec, iNumCols);
    }
References CVector::copy().
setValue()
template<typename T > static void CMatrix::setValue (T ** ppfMat, T tValue, int iNumRows, int iNumCols) inline static
sets a float matrix to zero
Parameters
ppfMat pointer to memory to be set
tValue value to use
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 78 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setValue(ppfMat[m], tValue, iNumCols);
    }
References CVector::setValue().
Referenced by CNmf::init().
setZero()
template<typename T > static void CMatrix::setZero (T ** ppfMat, int iNumRows, int iNumCols) inline static
sets a float matrix to zero
Parameters
ppfMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 59 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setZero(ppfMat[m], iNumCols);
    }
References CVector::setZero().
Referenced by CPca::calcSVD(), and CPca::compCov().
setZeroBelowThresh()
template<typename T > static void CMatrix::setZeroBelowThresh (T ** ppfMat, int iNumRows, int iNumCols, T tThresh) inline static
sets all elements in a matrix below a threshold to zero
Parameters
ppfMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
tThresh threshold
Returns
Definition at line 134 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfMat);
        assert(ppfMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setZeroBelowThresh(ppfMat[m], iNumCols, tThresh);
    }
References CVector::setZeroBelowThresh().
Referenced by CNmf::runNmfIter().
sub_I()
static void CMatrix::sub_I (float ** ppfSrcDest, float ** ppfSrc, int iNumRows, int iNumCols) inline static
elementwise subtraction of two matrices inplace
Parameters
ppfSrcDest resulting matrix
ppfSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 472 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                ppfSrcDest[m][n] -= ppfSrc[m][n];
        }
    }
swapRowCol()
static void CMatrix::swapRowCol (float ** ppfSrcDest, int iRowIdx, int iColIdx, int iNumCols) inline static
swaps a matrix row with a column in a square matrix
Parameters
ppfSrcDest resulting matrix (to be modified)
iRowIdx index of row
iColIdx index of columns
iNumCols number of columns in the matrix
Returns
Definition at line 581 of file Matrix.h.
    {
        assert(iRowIdx > 0);
        assert(iColIdx > 0);
        assert(iNumCols > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            float fTmp = ppfSrcDest[iRowIdx][n];
            ppfSrcDest[iRowIdx][n] = ppfSrcDest[iColIdx][n];
            ppfSrcDest[iColIdx][n] = fTmp;
        }
    }
Referenced by inv_I().
transpose()
static void CMatrix::transpose (float ** ppfDest, float ** ppfSrc, int iNumSrcRows, int iNumSrcCols) inline static
transposes matrix ppfSrc and write the result to ppfDest
Parameters
ppfDest resulting matrix of dimension iNumSrcCols x iNumSrcRows (to be written, user allocated)
ppfSrc input matrix of dimension iNumSrcRows x iNumCols
iNumSrcRows number of rows in the matrix
iNumSrcCols number of columns in the matrix
Returns
Definition at line 273 of file Matrix.h.
    {
        assert(iNumSrcRows > 0);
        assert(iNumSrcCols > 0);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        assert(ppfDest);
        assert(ppfDest[0]);
        for (auto m = 0; m < iNumSrcRows; m++)
        {
            for (auto n = 0; n < iNumSrcCols; n++)
                ppfDest[n][m] = ppfSrc[m][n];
        }
    }
Referenced by CPca::compPca(), and CNmf::runNmfIter().
vecnorm_I()
static void CMatrix::vecnorm_I (float ** ppfSrcDest, int iNumRows, int iNumCols) inline static
normalizes each column of the matrix (p=1)
Parameters
ppfSrcDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 221 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            float fNorm = 0;
            for (auto m = 0; m < iNumRows; m++)
                fNorm += std::abs(ppfSrcDest[m][n]);
            if (fNorm > 0)
                for (auto m = 0; m < iNumRows; m++)
                    ppfSrcDest[m][n] /= fNorm;
        }
    }
Referenced by CNmfResult::init(), and CNmf::runNmfIter().
The documentation for this class was generated from the following file:
Matrix.h