ACA: CNoveltyFromBlockIf Class Reference
CNoveltyFromBlockIf Class Reference
class for computation of a Novelty from a block of data (e.g., time or magnitude spectrum)
#include <NoveltyFromBlock.h>
Public Member Functions
virtual int getNoveltyDimension () const
CNoveltyIf::Novelty_t getNoveltyIdx () const
virtual Error_t compNovelty (float *pfNovelty, const float *pfInput)
Static Public Member Functions
static Error_t create (CNoveltyFromBlockIf *&pCInstance, CNoveltyIf::Novelty_t eNoveltyIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CNoveltyFromBlockIf *&pCInstance)
static float compNoveltyFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compNoveltyHainsworth (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compNoveltyLaroche (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
Protected Member Functions
CNoveltyFromBlockIf ()
CNoveltyFromBlockIf (CNoveltyIf::Novelty_t eNoveltyIdx, int iDataLength, float fSampleRate)
virtual ~CNoveltyFromBlockIf ()
CNoveltyFromBlockIf (const CNoveltyFromBlockIf &that)
CNoveltyFromBlockIf & operator= (const CNoveltyFromBlockIf &c)
Protected Attributes
CNoveltyIf::Novelty_t m_eNoveltyIdx = CNoveltyIf::kNumNoveltyFunctions
index of Novelty to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
float * m_pfPrevSpec = 0
const std::map< CNoveltyIf::Novelty_t, std::function< float(const float *, const float *, int, float)> > m_DispatchMap
Detailed Description
class for computation of a Novelty from a block of data (e.g., time or magnitude spectrum)
Definition at line 13 of file NoveltyFromBlock.h.
Constructor & Destructor Documentation
CNoveltyFromBlockIf() [1/3]
CNoveltyFromBlockIf::CNoveltyFromBlockIf () inline protected
Definition at line 60 of file NoveltyFromBlock.h.
{};
Referenced by create().
CNoveltyFromBlockIf() [2/3]
CNoveltyFromBlockIf::CNoveltyFromBlockIf (CNoveltyIf::Novelty_t eNoveltyIdx, int iDataLength, float fSampleRate) protected
Definition at line 70 of file NoveltyFromBlock.cpp.
                                                                                                            :
    m_eNoveltyIdx(eNoveltyIdx),
    m_iDataLength(iDataLength),
    m_fSampleRate(fSampleRate)
{
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    CVector::alloc(m_pfPrevSpec, m_iDataLength);
}
References CVector::alloc(), m_iDataLength, and m_pfPrevSpec.
~CNoveltyFromBlockIf()
CNoveltyFromBlockIf::~CNoveltyFromBlockIf () protected virtual
Definition at line 81 of file NoveltyFromBlock.cpp.
{
    CVector::free(m_pfPrevSpec);
}
References CVector::free(), and m_pfPrevSpec.
CNoveltyFromBlockIf() [3/3]
CNoveltyFromBlockIf::CNoveltyFromBlockIf (const CNoveltyFromBlockIf & that) protected
Member Function Documentation
compNovelty()
Error_t CNoveltyFromBlockIf::compNovelty (float * pfNovelty, const float * pfInput) virtual
performs the NoveltyFromBlock computation
Parameters
pfNovelty Novelty result (user-allocated, to be written, length from CNoveltyFromBlockIf::getNoveltyDimension)
pfInput input data of length iDataLength
Returns
Error_t
Definition at line 111 of file NoveltyFromBlock.cpp.
{
    *pfNovelty = m_DispatchMap.at(m_eNoveltyIdx)(pfInput, m_pfPrevSpec, m_iDataLength, m_fSampleRate);
    CVectorFloat::copy(m_pfPrevSpec, pfInput, m_iDataLength);
    return Error_t::kNoError;
}
References CVectorFloat::copy(), kNoError, m_DispatchMap, m_eNoveltyIdx, m_fSampleRate, m_iDataLength, and m_pfPrevSpec.
Referenced by CNoveltyIf::compNovelty().
compNoveltyFlux()
float CNoveltyFromBlockIf::compNoveltyFlux (const float * pfMagSpec, const float * pfPrevSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 12 of file NoveltyFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(pfPrevSpec);
    assert(iDataLength > 0);
    float fSum = 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fDiff = pfMagSpec[k] - pfPrevSpec[k];
        fSum += (fDiff > 0) ? fDiff * fDiff : 0.F;
    }
    return std::sqrt(fSum) / iDataLength;
}
compNoveltyHainsworth()
float CNoveltyFromBlockIf::compNoveltyHainsworth (const float * pfMagSpec, const float * pfPrevSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 29 of file NoveltyFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(pfPrevSpec);
    assert(iDataLength > 0);
    const float fEpsilon = 1e-5F;
    float fSum = 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fMag = (pfMagSpec[k] > 0) ? pfMagSpec[k] : fEpsilon;
        float fPrev = (pfPrevSpec[k] > 0) ? pfPrevSpec[k] : fEpsilon;
        fSum += std::log2(fMag / fPrev);
    }
    return fSum / iDataLength;
}
compNoveltyLaroche()
float CNoveltyFromBlockIf::compNoveltyLaroche (const float * pfMagSpec, const float * pfPrevSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 48 of file NoveltyFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(pfPrevSpec);
    assert(iDataLength > 0);
    float fSum = 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fDiff = std::sqrt(pfMagSpec[k]) - std::sqrt(pfPrevSpec[k]);
        fSum += (fDiff > 0) ? fDiff : 0.F;
    }
    return fSum / iDataLength;
}
create()
Error_t CNoveltyFromBlockIf::create (CNoveltyFromBlockIf *& pCInstance, CNoveltyIf::Novelty_t eNoveltyIdx, int iDataLength, float fSampleRate = 1.F) static
initializes a NoveltyFromBlock instance
Parameters
pCInstance pointer to instance to be written
eNoveltyIdx index of Novelty to extract
iDataLength block length
fSampleRate sample rate (only used when needed)
Returns
Error_t
Definition at line 86 of file NoveltyFromBlock.cpp.
{
    if (iDataLength <= 0 || fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CNoveltyFromBlockIf(eNoveltyIdx, iDataLength, fSampleRate);
    return Error_t::kNoError;
}
References CNoveltyFromBlockIf(), kFunctionInvalidArgsError, and kNoError.
Referenced by CNoveltyIf::init_().
destroy()
Error_t CNoveltyFromBlockIf::destroy (CNoveltyFromBlockIf *& pCInstance) static
destroys a NoveltyFromBlock instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 96 of file NoveltyFromBlock.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by CNoveltyIf::reset_().
getNoveltyDimension()
int CNoveltyFromBlockIf::getNoveltyDimension () const virtual
returns size of output Novelty (1 in all currently implemented cases)
Returns
int
Definition at line 105 of file NoveltyFromBlock.cpp.
{
    // default: 1 value per block
    return 1;
}
getNoveltyIdx()
CNoveltyIf::Novelty_t CNoveltyFromBlockIf::getNoveltyIdx () const inline
returns index of the Novelty to extract
Returns
Novelty_t
Definition at line 40 of file NoveltyFromBlock.h.
    {
        return m_eNoveltyIdx;
    }
References m_eNoveltyIdx.
operator=()
CNoveltyFromBlockIf & CNoveltyFromBlockIf::operator= (const CNoveltyFromBlockIf & c) protected
Member Data Documentation
m_DispatchMap
const std::map<CNoveltyIf::Novelty_t, std::function<float(const float*, const float*, int, float)> > CNoveltyFromBlockIf::m_DispatchMap protected
Initial value:
{
            {CNoveltyIf::kNoveltyFlux, &compNoveltyFlux},
            {CNoveltyIf::kNoveltyHainsworth, &compNoveltyHainsworth},
            {CNoveltyIf::kNoveltyLaroche, &compNoveltyLaroche}
    }
Definition at line 76 of file NoveltyFromBlock.h.
Referenced by compNovelty().
m_eNoveltyIdx
CNoveltyIf::Novelty_t CNoveltyFromBlockIf::m_eNoveltyIdx = CNoveltyIf::kNumNoveltyFunctions protected
index of Novelty to extract
Definition at line 67 of file NoveltyFromBlock.h.
Referenced by compNovelty(), and getNoveltyIdx().
m_fSampleRate
float CNoveltyFromBlockIf::m_fSampleRate = 0 protected
sample rate
Definition at line 71 of file NoveltyFromBlock.h.
Referenced by compNovelty().
m_iDataLength
int CNoveltyFromBlockIf::m_iDataLength = 0 protected
block length
Definition at line 69 of file NoveltyFromBlock.h.
Referenced by CNoveltyFromBlockIf(), and compNovelty().
m_pfPrevSpec
float* CNoveltyFromBlockIf::m_pfPrevSpec = 0 protected
Definition at line 73 of file NoveltyFromBlock.h.
Referenced by CNoveltyFromBlockIf(), compNovelty(), and ~CNoveltyFromBlockIf().
The documentation for this class was generated from the following files:
NoveltyFromBlock.h
NoveltyFromBlock.cpp