ACA: CVector Class Reference
CVector Class Reference
class with static functions for buffer operations with type T
#include <Vector.h>
Static Public Member Functions
template<typename T >
static void alloc (T *&ptVec, long long iLength)
template<typename T >
static void free (T *&ptVec)
template<typename T >
static void setZero (T *ptSrcDest, long long iLength)
template<typename T >
static void setValue (T *ptDest, T tValue, long long iLength)
template<typename T >
static void setRand (T *pfDest, long long iLength)
template<typename T >
static void setZeroBelowThresh (T *ptSrcDest, long long int iLength, T tThresh)
template<typename T >
static void copy (T *ptDest, const T *ptSrc, long long int iLength)
template<typename T >
static void flip_I (T *ptSrcDest, long long int iLength)
template<typename T >
static void moveInMem (T *ptSrcDest, int iDestIdx, int iSrcIdx, long long int iLength)
Detailed Description
class with static functions for buffer operations with type T
Definition at line 14 of file Vector.h.
Member Function Documentation
alloc()
template<typename T > static void CVector::alloc (T *& ptVec, long long iLength) inline static
allocates a float buffer and inits it with zeros
Parameters
ptVec (empty pointer, to be allocated)
iLength number of floats
Returns
Definition at line 24 of file Vector.h.
    {
        assert(iLength > 0);
        ptVec = new T[iLength];
        assert(ptVec);
        setZero(ptVec, iLength);
    }
References setZero().
Referenced by CMatrix::alloc(), CFft::allocMemory_(), CButterLp::calcCoeffs(), CPca::calcSVD(), CBlockAudioBuffer::CBlockAudioBuffer(), CChordFromBlockIf::CChordFromBlockIf(), CFeatureSpectralFlux::CFeatureSpectralFlux(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureTimeMaxAcf::CFeatureTimeMaxAcf(), CInstFreq::CInstFreq(), CNormalizeAudio::CNormalizeAudio(), CNoveltyFromBlockIf::CNoveltyFromBlockIf(), CChordIf::compChords(), CNoveltyIf::compNovelty(), CPitchSpectralAcf::CPitchSpectralAcf(), CPitchSpectralHps::CPitchSpectralHps(), CPitchTimeAcf::CPitchTimeAcf(), CPitchTimeAuditory::CPitchTimeAuditory(), CMovingAverage::filtfilt(), CFilter< T >::filtfilt(), CSpectrogramIf::generateMelFb_(), CFilter< T >::init(), CViterbi::init(), CKnn::init(), CCcf::init(), CPca::init(), CDtw::init(), CChordIf::init_(), CGammaToneFbIf::init_(), CBeatHistoIf::init_(), CFeatureIf::init_(), CSpectrogramIf::init_(), CNoveltyIf::init_(), CPitchIf::init_(), CResample::process(), CMatrix::rearrangeRows(), CFilter< T >::setInitState_(), and CKnn::setParam().
copy()
template<typename T > static void CVector::copy (T * ptDest, const T * ptSrc, long long int iLength) inline static
copies buffer of type T
Parameters
ptDest pointer to destination memory
ptSrc pointer to source memory
iLength length of buffer
Returns
void
Definition at line 113 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptDest);
            assert(ptSrc);
            memcpy(ptDest, ptSrc, sizeof(T)*iLength);
        }
    }
Referenced by CKnn::classify(), CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), CVectorFloat::copy(), CMatrix::copy(), CFilter< T >::init(), CViterbi::init(), CKnn::init(), CAudioFileSndLib::openFile(), CMatrix::rearrangeRows(), and CMatrix::setRow().
flip_I()
template<typename T > static void CVector::flip_I (T * ptSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
ptSrcDest pointer to memory to be flipped
iLength number of elements
Returns
void
Definition at line 130 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptSrcDest);
            auto iLoopLength = iLength / 2; // integer division!
            for (auto i = 0; i < iLoopLength; i++)
            {
                T Tmp = ptSrcDest[i];
                ptSrcDest[i] = ptSrcDest[iLength - 1 - i];
                ptSrcDest[iLength - 1 - i] = Tmp;
            }
        }
    }
Referenced by CBeatHistoIf::compBeatHisto(), and CVectorFloat::flip_I().
free()
template<typename T > static void CVector::free (T *& ptVec) inline static
frees a float buffer and sets it to zero
Parameters
ptVec (empty pointer, to be allocated)
Returns
Definition at line 39 of file Vector.h.
    {
        delete[] ptVec;
        ptVec = 0;
    }
Referenced by CButterLp::calcCoeffs(), CPca::calcSVD(), CNormalizeAudio::CNormalizeAudio(), CChordIf::compChords(), CNoveltyIf::compNovelty(), CMovingAverage::filtfilt(), CFilter< T >::filtfilt(), CMatrix::free(), CFft::freeMemory_(), CResample::process(), CMatrix::rearrangeRows(), CCcf::reset(), CPca::reset(), CDtw::reset(), CViterbi::reset(), CKnn::reset(), CFilter< T >::reset(), CBeatHistoIf::reset_(), CChordIf::reset_(), CFeatureIf::reset_(), CNoveltyIf::reset_(), CPitchIf::reset_(), CSpectrogramIf::reset_(), CGammaToneFbIf::reset_(), CFilter< T >::setInitState_(), CKnn::setParam(), CBlockAudioBuffer::~CBlockAudioBuffer(), CBlockAudioFile::~CBlockAudioFile(), CChordFromBlockIf::~CChordFromBlockIf(), CChordFromFile::~CChordFromFile(), CFeatureFromFile::~CFeatureFromFile(), CFeatureSpectralFlux::~CFeatureSpectralFlux(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureTimeMaxAcf::~CFeatureTimeMaxAcf(), CInstFreq::~CInstFreq(), CNoveltyFromBlockIf::~CNoveltyFromBlockIf(), CNoveltyFromFile::~CNoveltyFromFile(), CPitchFromFile::~CPitchFromFile(), CPitchSpectralAcf::~CPitchSpectralAcf(), CPitchSpectralHps::~CPitchSpectralHps(), CPitchTimeAcf::~CPitchTimeAcf(), CPitchTimeAuditory::~CPitchTimeAuditory(), and CSpectrogramFromFile::~CSpectrogramFromFile().
moveInMem()
template<typename T > static void CVector::moveInMem (T * ptSrcDest, int iDestIdx, int iSrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
ptSrcDest source and destination
iDestIdx destination index
iSrcIdx source index
iLength number of elements to be moved
Returns
void
Definition at line 155 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        if (iLength > 0)
            memmove (&ptSrcDest[iDestIdx], &ptSrcDest[iSrcIdx], sizeof(T)*iLength);
    }
Referenced by CVectorFloat::moveInMem().
setRand()
template<typename T > static void CVector::setRand (T * pfDest, long long iLength) inline static
initializes the buffer with random noise
Parameters
pfDest pointer to memory to be initialized
iLength number of elements to be set
Returns
void
Definition at line 82 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfDest);
        CSynthesis::genNoise(pfDest, iLength);
    }
References CSynthesis::genNoise().
Referenced by CVectorFloat::setRand(), and CMatrix::setRand().
setValue()
template<typename T > static void CVector::setValue (T * ptDest, T tValue, long long iLength) inline static
initializes the buffer to a specific value
Parameters
ptDest pointer to memory to be set
tValue value to use
iLength number of elements to be set
Returns
void
Definition at line 67 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptDest);
        for (auto i = 0; i < iLength; i++)
            ptDest[i] = tValue;
    }
Referenced by CKnn::buildHistogram_(), CNoveltyIf::compNovelty(), CVectorFloat::findPeaks(), CKnn::init(), and CMatrix::setValue().
setZero()
template<typename T > static void CVector::setZero (T * ptSrcDest, long long iLength) inline static
sets a buffer to zero
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
Returns
void
Definition at line 51 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        if (iLength > 0)
            memset (ptSrcDest, 0, sizeof(T)*iLength);
    }
Referenced by alloc(), CDtw::CDtw(), CFilter< T >::init(), CKnn::init(), CNmfResult::reset(), CFilter< T >::reset(), CVectorFloat::setZero(), and CMatrix::setZero().
setZeroBelowThresh()
template<typename T > static void CVector::setZeroBelowThresh (T * ptSrcDest, long long int iLength, T tThresh) inline static
sets all values smaller than a threshold to 0
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
tThresh threshold value
Returns
void
Definition at line 97 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        for (auto i = 0; i < iLength; i++)
            if (ptSrcDest[i] < tThresh)
                ptSrcDest[i] = 0;
    }
Referenced by CVectorFloat::setZeroBelowThresh(), and CMatrix::setZeroBelowThresh().
The documentation for this class was generated from the following file:
Vector.h