ACA: CVectorFloat Class Reference
CVectorFloat Class Reference
class with static functions for buffer operations with type float
#include <Vector.h>
Static Public Member Functions
static void setZero (float *pfSrcDest, long long int iLength)
static void setZeroBelowThresh (float *pfSrcDest, long long int iLength, float fThresh=0.F)
static void copy (float *pfDest, const float *pfSrc, long long int iLength)
static void flip_I (float *pfSrcDest, long long int iLength)
static void moveInMem (float *pfSrcDest, int iDestIdx, int iSrcIdx, long long int iLength)
static void setValue (float *pfDest, float fValue, long long int iLength)
static void setRand (float *pfDest, long long int iLength)
static void mulC_I (float *pfSrcDest, float fScale, long long int iLength)
static void mul_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static float mulScalar (const float *pfSrc1, const float *pfSrc2, long long int iLength)
static void div_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static void add_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static void addC_I (float *pfSrcDest, float fConst, long long int iLength)
static void sort_I (float *pfSrcDest, int *piIndices, int iLength, bool bAscending=true)
static void sub_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static float distManhattan (const float *pfSrc1, const float *pfSrc2, long long iLength)
static float distEuclidean (const float *pfSrc1, const float *pfSrc2, long long iLength)
static float distCosine (const float *pfSrc1, const float *pfSrc2, long long iLength)
static void subW_I (float *pfSrcDest, const float *pfSrc, float fWeight, long long int iLength)
static float getSum (const float *pfSrc, long long int iLength, bool bAbs=false)
static bool isEqual (const float *pfSrc1, const float *pfSrc2, long long int iLength)
static float getMean (const float *pfSrc, long long int iLength)
static float getStd (const float *pfSrc, long long int iLength, float fMean=std::numeric_limits< float >::max())
static float getRms (const float *pfSrc, long long int iLength)
static float getMax (const float *pfSrc, long long int iLength, bool bAbs=false)
static int findPeaks (bool *pbIsLocalMax, const float *pfSrc, long long int iLength, float fThresh=-std::numeric_limits< float >::max())
static float getMin (const float *pfSrc, long long int iLength, bool bAbs=false)
static void findMax (const float *pfSrc, float &fMax, long long &iMax, long long int iLength, bool bAbs=false)
static void findMin (const float *pfSrc, float &fMin, long long &iMin, long long int iLength, bool bAbs=false)
Detailed Description
class with static functions for buffer operations with type float
Definition at line 167 of file Vector.h.
Member Function Documentation
add_I()
static void CVectorFloat::add_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector addition
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be added
Returns
void
Definition at line 325 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        assert (pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] += pfSrc[i];
    }
Referenced by CBeatHistoIf::compBeatHisto(), CPitchTimeAuditory::compF0(), CPreProc::downmix(), and CInstFreq::process().
addC_I()
static void CVectorFloat::addC_I (float * pfSrcDest, float fConst, long long int iLength) inline static
adds a buffer to a scalar
Parameters
pfSrcDest buffer to be added
fConst scalar
iLength number of element to be added
Returns
void
Definition at line 341 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] += fConst;
    }
Referenced by CMatrix::addC_I(), CNoveltyIf::compNovelty(), and CChordFromBlockIf::genTemplateMatrix_().
copy()
static void CVectorFloat::copy (float * pfDest, const float * pfSrc, long long int iLength) inline static
copies buffer of type float
Parameters
pfDest pointer to destination memory
pfSrc pointer to source memory
iLength length of buffer
Returns
void
Definition at line 198 of file Vector.h.
    {
        CVector::copy(pfDest, pfSrc, iLength);
    }
References CVector::copy().
Referenced by CButterLp::calcCoeffs(), CBlockAudioBuffer::CBlockAudioBuffer(), CBeatHistoIf::compBeatHisto(), CCcf::compCcf(), CFeatureSpectralFlux::compFeature(), CFft::compFft(), CFft::compInvFft(), CNoveltyFromBlockIf::compNovelty(), CPreProc::downmix(), CCcf::getCcf(), CSpectrogramIf::getMelSpectrogramAxisVectors(), CBlockAudioBuffer::getNextBlock(), CFft::getWindow(), CFft::mergeRealImag(), CFft::overrideWindow(), CInstFreq::process(), CGammatone::process(), and CFft::splitRealImag().
distCosine()
static float CVectorFloat::distCosine (const float * pfSrc1, const float * pfSrc2, long long iLength) inline static
Cosine distance
Parameters
pfSrc1 first input vector
pfSrc2 second input vector
iLength length of vectors
Returns
float
Definition at line 474 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrc1);
        assert(pfSrc2);
        float fDist = 0;
        for (auto i = 0; i < iLength; i++)
            fDist += pfSrc1[i] * pfSrc2[i];
        return 1.F - fDist / std::sqrt(mulScalar(pfSrc1, pfSrc1, iLength) * mulScalar(pfSrc2, pfSrc2, iLength));
    }
References mulScalar().
distEuclidean()
static float CVectorFloat::distEuclidean (const float * pfSrc1, const float * pfSrc2, long long iLength) inline static
Euclidean distance
Parameters
pfSrc1 first input vector
pfSrc2 second input vector
iLength length of vectors
Returns
float
Definition at line 453 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrc1);
        assert(pfSrc2);
        float fDist = -2.F * mulScalar(pfSrc1, pfSrc2, iLength);
        fDist += mulScalar(pfSrc1, pfSrc1, iLength);
        fDist += mulScalar(pfSrc2, pfSrc2, iLength);
        //for (auto i = 0; i < iLength; i++)
        //    fDist += (pfSrc1[i] - pfSrc2[i]) * (pfSrc1[i] - pfSrc2[i]);
        return std::sqrt(fDist);
    }
References mulScalar().
Referenced by CKnn::classify().
distManhattan()
static float CVectorFloat::distManhattan (const float * pfSrc1, const float * pfSrc2, long long iLength) inline static
manhattan distance
Parameters
pfSrc1 first input vector
pfSrc2 second input vector
iLength length of vectors
Returns
float
Definition at line 434 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrc1);
        assert(pfSrc2);
        float fDist = std::abs(pfSrc1[0] - pfSrc2[0]);
        for (auto i = 1; i < iLength; i++)
            fDist += std::abs(pfSrc1[i] - pfSrc2[i]);
        return fDist;
    }
div_I()
static void CVectorFloat::div_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector division
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be divided
Returns
void
Definition at line 306 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        assert (pfSrc);
        for (auto i = 0; i < iLength; i++)
        {
            assert(pfSrc[i] != 0);
            pfSrcDest[i] /= pfSrc[i];
        }
    }
findMax()
static void CVectorFloat::findMax (const float * pfSrc, float & fMax, long long & iMax, long long int iLength, bool bAbs = false) inline static
finds the maximum (absolute) value in the buffer
Parameters
pfSrc input buffer
fMax resulting output value
iMax index of the resulting output value
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 695 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc);
        fMax    = -std::numeric_limits<float>::max();
        iMax    = -1;
        for (auto i = 0; i < iLength; i++)
        {
            float fCurr   = (bAbs)? std::abs(pfSrc[i]) : pfSrc[i];
            if (fCurr > fMax)
            {
                fMax = fCurr;
                iMax = i;
            }
        }
    }
Referenced by CChordIf::compChords(), CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), CPitchTimeAcf::compF0(), CKnn::countMaxima_(), CPitchTimeAuditory::getAcfMax_(), CCcf::getCcfMaxIdx(), and getMax().
findMin()
static void CVectorFloat::findMin (const float * pfSrc, float & fMin, long long & iMin, long long int iLength, bool bAbs = false) inline static
finds the minimum (absolute) value in the buffer
Parameters
pfSrc input buffer
fMin resulting output value
iMin index of the resulting output value
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 723 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc);
        fMin    = std::numeric_limits<float>::max();
        iMin    = -1;
        for (auto i = 0; i < iLength; i++)
        {
            float fCurr   = (bAbs)? std::abs(pfSrc[i]) : pfSrc[i];
            if (fCurr < fMin)
            {
                fMin    = fCurr;
                iMin    = i;
            }
        }
    }
Referenced by getMin().
findPeaks()
static int CVectorFloat::findPeaks (bool * pbIsLocalMax, const float * pfSrc, long long int iLength, float fThresh = -std::numeric_limits<float>::max()) inline static
finds the local maxima in the buffer
Parameters
pbIsLocalMax result buffer
pfSrc input buffer
iLength number of elements in buffer
fThresh only detect maxima above this threshold
Returns
int number of local maxima
Definition at line 643 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrc);
        assert(pbIsLocalMax);
        int iNumPeaks = 0;
        CVector::setValue(pbIsLocalMax, false, iLength);
        for (auto k = 1; k < iLength - 1; k++)
        {
            // search for local maxima
            if (pfSrc[k] <= pfSrc[k - 1] || pfSrc[k] <= pfSrc[k + 1] || pfSrc[k] <= fThresh)
                continue;
            else
            {
                pbIsLocalMax[k] = true;
                iNumPeaks++;
                // increment because the next bin cannot be a local max
                k++;
            }
        }
        return iNumPeaks;
    }
References CVector::setValue().
Referenced by CNoveltyIf::compNovelty().
flip_I()
static void CVectorFloat::flip_I (float * pfSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
pfSrcDest pointer to memory to be flipped
iLength number of elements
Returns
void
Definition at line 208 of file Vector.h.
    {
        CVector::flip_I(pfSrcDest, iLength);
    }
References CVector::flip_I().
Referenced by CPitchSpectralAcf::compF0().
getMax()
static float CVectorFloat::getMax (const float * pfSrc, long long int iLength, bool bAbs = false) inline static
finds the maximum (absolute) value in the buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 626 of file Vector.h.
    {
        float fMax;
        long long iMax;
        findMax(pfSrc, fMax, iMax, iLength, bAbs);
        return fMax;
    }
References findMax().
Referenced by CNormalizeAudio::CNormalizeAudio(), CPitchSpectralAcf::compF0(), CFeatureTimeMaxAcf::compFeature(), CFeatureFromBlockIf::compFeatureSpectralCrestFactor(), CFeatureFromBlockIf::compFeatureTimePeakEnvelope(), CNoveltyIf::compNovelty(), CCcf::getCcfMax(), CMatrix::getMax(), CKnn::init(), and CNormalizeAudio::normalizeSignal().
getMean()
static float CVectorFloat::getMean (const float * pfSrc, long long int iLength) inline static
extracts the mean value
Parameters
pfSrc input buffer
iLength number of elements in buffer
Returns
float
Definition at line 550 of file Vector.h.
    {
        assert (iLength >= 0);
        float fMean = getSum(pfSrc, iLength);
        if (iLength > 0)
        {
            fMean  /= iLength;
        }
        return fMean;
    }
References getSum().
Referenced by CPca::compCov(), CFeatureFromBlockIf::compFeatureSpectralFlatness(), CNoveltyIf::compNovelty(), getStd(), and CKnn::init().
getMin()
static float CVectorFloat::getMin (const float * pfSrc, long long int iLength, bool bAbs = false) inline static
finds the minimum (absolute) value in the buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 677 of file Vector.h.
    {
        float fMin;
        long long iMin;
        findMin(pfSrc, fMin, iMin, iLength, bAbs);
        return fMin;
    }
References findMin().
Referenced by CFeatureFromBlockIf::compFeatureSpectralFlatness(), and CKnn::init().
getRms()
static float CVectorFloat::getRms (const float * pfSrc, long long int iLength) inline static
extracts the root mean square from a buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
Returns
float
Definition at line 600 of file Vector.h.
    {
        assert (iLength >= 0);
        float fRms = 0;
        for (auto i=0; i < iLength; i++)
        {
            fRms   += pfSrc[i] * pfSrc[i];
        }
        if (iLength > 0)
        {
            fRms   /= iLength;
        }
        return std::sqrt(fRms);
    }
getStd()
static float CVectorFloat::getStd (const float * pfSrc, long long int iLength, float fMean = std::numeric_limits<float>::max()) inline static
extracts the standard deviation (biased) from a buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
fMean mean value if it has already been computed, otherwise it will be extracted in function
Returns
float
Definition at line 570 of file Vector.h.
    {
        assert (iLength >= 0);
        float  fStd = 0;
        if (fMean == std::numeric_limits<float>::max())
        {
            fMean   = getMean(pfSrc, iLength);
        }
        for (auto i=0; i < iLength; i++)
        {
            fStd   += (pfSrc[i] - fMean) * (pfSrc[i] - fMean);
        }
        if (iLength > 1)
        {
            //dStd   /= (iLength - 1);
            fStd   /= iLength;
        }
        return std::sqrt(fStd);
    }
References getMean().
Referenced by CFeatureFromBlockIf::compFeatureTimeRms(), CFeatureFromBlockIf::compFeatureTimeStd(), and CKnn::init().
getSum()
static float CVectorFloat::getSum (const float * pfSrc, long long int iLength, bool bAbs = false) inline static
computes the sum of a vector
Parameters
pfSrc vector
iLength length of vector
bAbs specifies whether it is the sum of absolute values or not
Returns
float
Definition at line 511 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc);
        float fResult = 0;
        if (bAbs)
        {
            for (auto i = 0; i < iLength; i++)
                fResult += std::abs(pfSrc[i]);
        }
        else
        {
            for (auto i = 0; i < iLength; i++)
                fResult += pfSrc[i];
        }
        return fResult;
    }
Referenced by CChordFromBlockIf::compChordProb(), CPitchTimeAmdf::compF0(), CFeatureSpectralPitchChroma::compFeature(), CFeatureFromBlockIf::compFeatureSpectralCrestFactor(), CFeatureFromBlockIf::compFeatureSpectralRolloff(), getMean(), CMatrix::getSum(), and CChordIf::initViterbi_().
isEqual()
static bool CVectorFloat::isEqual (const float * pfSrc1, const float * pfSrc2, long long int iLength) inline static
checks to buffer for equality (no floating point tolerance)
Parameters
pfSrc1 buffer 1
pfSrc2 buffer 2
iLength number of dimensions
Returns
bool
Definition at line 536 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc1);
        assert (pfSrc2);
        return (memcmp (pfSrc1, pfSrc2, iLength * sizeof(float)) == 0);
    }
moveInMem()
static void CVectorFloat::moveInMem (float * pfSrcDest, int iDestIdx, int iSrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
pfSrcDest source and destination
iDestIdx destination index
iSrcIdx source index
iLength number of elements to be moved
Returns
void
Definition at line 220 of file Vector.h.
    {
        CVector::moveInMem(pfSrcDest, iDestIdx, iSrcIdx, iLength);
    }
References CVector::moveInMem().
mul_I()
static void CVectorFloat::mul_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector multiplication
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be multiplied
Returns
void
Definition at line 271 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        assert (pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] *= pfSrc[i];
    }
Referenced by CKnn::classify(), CFft::compFft(), CFft::compInvFft(), and CKnn::init().
mulC_I()
static void CVectorFloat::mulC_I (float * pfSrcDest, float fScale, long long int iLength) inline static
multiplies a buffer with a scalar
Parameters
pfSrcDest buffer to be multiplied
fScale scalar
iLength number of element to be multiplied
Returns
void
Definition at line 256 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] *= fScale;
    }
Referenced by CGammatone::calcFilterCoeffs_(), CCcf::compCcf(), CChordFromBlockIf::compChordProb(), CFeatureSpectralPitchChroma::compFeature(), CNoveltyIf::compNovelty(), CChordIf::computeMagSpectrum_(), CFeatureIf::computeMagSpectrum_(), CNoveltyIf::computeMagSpectrum_(), CPitchIf::computeMagSpectrum_(), CSpectrogramIf::computeMagSpectrum_(), CFft::conjugate_I(), CPreProc::downmix(), CFeatureSpectralMfccs::genDctMat_(), CChordIf::initViterbi_(), CMatrix::inv_I(), CMatrix::mulC_I(), CNormalizeAudio::normalizeBlock(), CNormalizeAudio::normalizeSignal(), and CInstFreq::process().
mulScalar()
static float CVectorFloat::mulScalar (const float * pfSrc1, const float * pfSrc2, long long int iLength) inline static
computes the scalar product between two vectors
Parameters
pfSrc1 vector one
pfSrc2 vector two
iLength number of dimenions
Returns
float
Definition at line 287 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc1);
        assert (pfSrc2);
        float  fResult = 0;
        for (auto i = 0; i < iLength; i++)
            fResult += pfSrc1[i] * pfSrc2[i];
        return fResult;
    }
Referenced by CCcf::compCcf(), CFeatureSpectralMfccs::compFeature(), CFeatureFromBlockIf::compFeatureTimeAcfCoeff(), CSpectrogramIf::compMelSpectrogram(), distCosine(), distEuclidean(), and CMatrix::mulMatColVec().
setRand()
static void CVectorFloat::setRand (float * pfDest, long long int iLength) inline static
initializes the buffer with random noise
Parameters
pfDest pointer to memory to be initialized
iLength number of elements to be set
Returns
void
Definition at line 245 of file Vector.h.
    {
        CVector::setRand(pfDest, iLength);
    }
References CVector::setRand().
setValue()
static void CVectorFloat::setValue (float * pfDest, float fValue, long long int iLength) inline static
initializes the buffer to a specific value
Parameters
pfDest pointer to memory to be initialized
fValue value to use
iLength number of elements to be set
Returns
void
Definition at line 231 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfDest);
        for (auto i = 0; i < iLength; i++)
            pfDest[i] = fValue;
    }
Referenced by CViterbi::compProbability_(), CFeatureSpectralPitchChroma::genPcFilters_(), and CChordIf::initViterbi_().
setZero()
static void CVectorFloat::setZero (float * pfSrcDest, long long int iLength) inline static
sets a buffer to zero
Parameters
pfSrcDest pointer to memory to be modified
iLength buffer length
Returns
void
Definition at line 176 of file Vector.h.
    {
        CVector::setZero(pfSrcDest, iLength);
    }
References CVector::setZero().
Referenced by CButterLp::calcCoeffs(), CFeatureSpectralFlux::CFeatureSpectralFlux(), CBeatHistoIf::compBeatHisto(), CChordFromBlockIf::compChordProb(), CDtw::compDtw(), CPitchSpectralHps::compF0(), CPitchTimeAuditory::compF0(), CFeatureSpectralMfccs::compFeature(), CFeatureSpectralPitchChroma::compFeature(), CFft::compFft(), CBlockAudioFile::getNextBlock(), CBlockAudioBuffer::getNextBlock(), CMatrix::mulRowVecMat(), CBlockAudioFile::readFile2RingBuff(), and CMatrix::setEye().
setZeroBelowThresh()
static void CVectorFloat::setZeroBelowThresh (float * pfSrcDest, long long int iLength, float fThresh = 0.F) inline static
sets all values smaller than a threshold to 0
Parameters
pfSrcDest pointer to memory to be modified
iLength buffer length
fThresh threshold value
Returns
void
Definition at line 187 of file Vector.h.
    {
        CVector::setZeroBelowThresh(pfSrcDest, iLength, fThresh);
    }
References CVector::setZeroBelowThresh().
Referenced by CNoveltyIf::compNovelty().
sort_I()
static void CVectorFloat::sort_I (float * pfSrcDest, int * piIndices, int iLength, bool bAscending = true) inline static
sorts values in a buffer
Parameters
pfSrcDest buffer to be sorted
piIndices new indices (optional, can be left 0)
iLength number of elements to be sorted
bAscending sort order (descending -> false)
Returns
void
Definition at line 358 of file Vector.h.
    {
        // go bubble sort! ( should be replaced some time with something faster)
        bool bDone = false; // this flag will be used to check whether we have to continue the algorithm
        // initialize
        if (piIndices)
            for (auto i = 0; i < iLength; i++)
                piIndices[i] = i;
        if (bAscending)
        {
            while (!bDone)
            {
                bDone = true;
                for (auto i = 0; i < iLength-1; i++)
                {
                    if (pfSrcDest[i] > pfSrcDest[i + 1]) // compare the current element with the following one
                    {
                        //swap them
                        CUtil::swap(pfSrcDest[i], pfSrcDest[i + 1]);
                        if (piIndices)
                            CUtil::swap(piIndices[i], piIndices[i + 1]);
                        bDone = false; // let's recheck the array
                    }
                }
            }
        }
        else // descending
        {
            while (!bDone)
            {
                bDone = true;
                for (auto i = 0; i < iLength-1; i++)
                {
                    if (pfSrcDest[i] < pfSrcDest[i + 1]) // compare the current element with the following one
                    {
                        //swap them
                        CUtil::swap(pfSrcDest[i], pfSrcDest[i + 1]);
                        if (piIndices)
                            CUtil::swap(piIndices[i], piIndices[i + 1]);
                        bDone = false; // let's recheck the array
                    }
                }
            }
        }
    }
References CUtil::swap().
Referenced by CKnn::classify(), and CPca::compPca().
sub_I()
static void CVectorFloat::sub_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector subtraction
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be subtracted
Returns
void
Definition at line 418 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrcDest);
        assert(pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] -= pfSrc[i];
    }
Referenced by CKnn::classify(), CNoveltyIf::compNovelty(), CKnn::init(), and CInstFreq::process().
subW_I()
static void CVectorFloat::subW_I (float * pfSrcDest, const float * pfSrc, float fWeight, long long int iLength) inline static
weighted element-wise vector subtraction
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
fWeight weight to be applied to pfSrc entries
iLength number of element to be subtracted
Returns
void
Definition at line 495 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrcDest);
        assert(pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] -= fWeight*pfSrc[i];
    }
Referenced by CMatrix::inv_I().
The documentation for this class was generated from the following file:
Vector.h