ACA: CVector Class Reference
CVector Class Reference
class with static functions for buffer operations with type T
#include <Vector.h>
Static Public Member Functions
template<typename T >
static void alloc (T *&pfVec, long long iLength)
template<typename T >
static void free (T *&pfVec)
template<typename T >
static void setZero (T *ptSrcDest, long long iLength)
template<typename T >
static void setValue (T *ptDest, T tValue, long long iLength)
template<typename T >
static void setZeroBelowThresh (T *ptSrcDest, long long int iLength, T Thresh)
template<typename T >
static void copy (T *ptDest, const T *pSource, long long int iLength)
template<typename T >
static void flip_I (T *ptSrcDest, long long int iLength)
template<typename T >
static void moveInMem (T *ptSrcDest, int iDestIdx, int iSrcIdx, long long int iLength)
Detailed Description
class with static functions for buffer operations with type T
Definition at line 12 of file Vector.h.
Member Function Documentation
alloc()
template<typename T > static void CVector::alloc (T *& pfVec, long long iLength) inline static
allocates a float buffer and inits it with zeros
Parameters
pfVec (empty pointer, to be allocated)
iLength number of floats
Returns
Definition at line 22 of file Vector.h.
    {
        assert(iLength > 0);
        pfVec = new T[iLength];
        assert(pfVec);
        setZero(pfVec, iLength);
    }
References setZero().
Referenced by CMatrix::alloc(), CFft::allocMemory_(), CButterLp::calcCoeffs(), CBlockAudioBuffer::CBlockAudioBuffer(), CFeatureSpectralFlux::CFeatureSpectralFlux(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureTimeMaxAcf::CFeatureTimeMaxAcf(), CInstFreq::CInstFreq(), CNormalizeAudio::CNormalizeAudio(), CNoveltyFromBlockIf::CNoveltyFromBlockIf(), CNoveltyIf::compNovelty(), CPitchSpectralAcf::CPitchSpectralAcf(), CPitchSpectralHps::CPitchSpectralHps(), CPitchTimeAcf::CPitchTimeAcf(), CPitchTimeAuditory::CPitchTimeAuditory(), CMovingAverage::filtfilt(), CFilter< T >::filtfilt(), CSpectrogramIf::generateMelFb_(), CFilter< T >::init(), CCcf::init(), CDtw::init(), CGammaToneFbIf::init_(), CBeatHistoIf::init_(), CFeatureIf::init_(), CSpectrogramIf::init_(), CNoveltyIf::init_(), CPitchIf::init_(), CResample::process(), and CFilter< T >::setInitState_().
copy()
template<typename T > static void CVector::copy (T * ptDest, const T * pSource, long long int iLength) inline static
copies buffer of type T
Parameters
ptDest pointer to destination memory
pSource pointer to source memory
iLength length of buffer
Returns
void
Definition at line 97 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptDest);
            assert(pSource);
            memcpy(ptDest, pSource, sizeof(T)*iLength);
        }
    }
Referenced by CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), CVectorFloat::copy(), CFilter< T >::init(), and CAudioFileSndLib::openFile().
flip_I()
template<typename T > static void CVector::flip_I (T * ptSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
ptSrcDest pointer to memory to be flipped
iLength number of elements
Returns
void
Definition at line 114 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptSrcDest);
            auto iLoopLength = iLength / 2; // integer division!
            for (auto i = 0; i < iLoopLength; i++)
            {
                T Tmp = ptSrcDest[i];
                ptSrcDest[i] = ptSrcDest[iLength - 1 - i];
                ptSrcDest[iLength - 1 - i] = Tmp;
            }
        }
    }
Referenced by CBeatHistoIf::compBeatHisto(), and CVectorFloat::flip_I().
free()
template<typename T > static void CVector::free (T *& pfVec) inline static
frees a float buffer and sets it to zero
Parameters
pfVec (empty pointer, to be allocated)
Returns
Definition at line 37 of file Vector.h.
    {
        delete[] pfVec;
        pfVec = 0;
    }
Referenced by CButterLp::calcCoeffs(), CNormalizeAudio::CNormalizeAudio(), CNoveltyIf::compNovelty(), CMovingAverage::filtfilt(), CFilter< T >::filtfilt(), CMatrix::free(), CFft::freeMemory_(), CResample::process(), CCcf::reset(), CDtw::reset(), CFilter< T >::reset(), CBeatHistoIf::reset_(), CFeatureIf::reset_(), CNoveltyIf::reset_(), CPitchIf::reset_(), CSpectrogramIf::reset_(), CGammaToneFbIf::reset_(), CFilter< T >::setInitState_(), CBlockAudioBuffer::~CBlockAudioBuffer(), CBlockAudioFile::~CBlockAudioFile(), CFeatureFromFile::~CFeatureFromFile(), CFeatureSpectralFlux::~CFeatureSpectralFlux(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureTimeMaxAcf::~CFeatureTimeMaxAcf(), CInstFreq::~CInstFreq(), CNoveltyFromBlockIf::~CNoveltyFromBlockIf(), CNoveltyFromFile::~CNoveltyFromFile(), CPitchFromFile::~CPitchFromFile(), CPitchSpectralAcf::~CPitchSpectralAcf(), CPitchSpectralHps::~CPitchSpectralHps(), CPitchTimeAcf::~CPitchTimeAcf(), CPitchTimeAuditory::~CPitchTimeAuditory(), and CSpectrogramFromFile::~CSpectrogramFromFile().
moveInMem()
template<typename T > static void CVector::moveInMem (T * ptSrcDest, int iDestIdx, int iSrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
ptSrcDest source and destination
iDestIdx destination index
iSrcIdx source index
iLength number of elements to be moved
Returns
void
Definition at line 139 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        if (iLength > 0)
            memmove (&ptSrcDest[iDestIdx], &ptSrcDest[iSrcIdx], sizeof(T)*iLength);
    }
Referenced by CVectorFloat::moveInMem().
setValue()
template<typename T > static void CVector::setValue (T * ptDest, T tValue, long long iLength) inline static
initializes the buffer to a specific value
Parameters
ptDest pointer to memory to be initialized
tValue value to use
iLength number of elements to be set
Returns
void
Definition at line 65 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptDest);
        for (auto i = 0; i < iLength; i++)
            ptDest[i] = tValue;
    }
Referenced by CNoveltyIf::compNovelty(), and CVectorFloat::findPeaks().
setZero()
template<typename T > static void CVector::setZero (T * ptSrcDest, long long iLength) inline static
sets a buffer to zero
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
Returns
void
Definition at line 49 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        if (iLength > 0)
            memset (ptSrcDest, 0, sizeof(T)*iLength);
    }
Referenced by alloc(), CDtw::CDtw(), CFilter< T >::init(), CFilter< T >::reset(), and CVectorFloat::setZero().
setZeroBelowThresh()
template<typename T > static void CVector::setZeroBelowThresh (T * ptSrcDest, long long int iLength, T Thresh) inline static
sets all values smaller than a threshold to 0
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
Thresh threshold value
Returns
void
Definition at line 81 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        for (auto i = 0; i < iLength; i++)
            if (ptSrcDest[i] < Thresh)
                ptSrcDest[i] = 0;
    }
Referenced by CVectorFloat::setZeroBelowThresh().
The documentation for this class was generated from the following file:
Vector.h