ACA: CNmf Class Reference
CNmf Class Reference
computation of non-negative matrix factorization
#include <ToolNmf.h>
Public Member Functions
CNmf (void)
virtual ~CNmf (void)
Error_t init (CNmfResult *pCNmfResult, int iRank, int iNumRows, int iNumCols, int iMaxIter=300, float fSparsity=0)
Error_t reset ()
Error_t compNmf (CNmfResult *pCNmfResult, float **ppfInput)
Private Member Functions
CNmf (const CNmf &that)
disallow copy construction
CNmf & operator= (const CNmf &c)
float runNmfIter (CNmfResult *pNmfResult, float **ppfInput)
Private Attributes
float ** m_ppfX = 0
float ** m_ppfOnes = 0
float ** m_ppfTransp = 0
float ** m_ppfNum = 0
float ** m_ppfDenom = 0
float m_fSparsity = 0
int m_iMaxIter = 0
int m_iAllocSize = 0
int m_iNumRows = 0
bool m_bIsInitialized = false
true if init has been called
Static Private Attributes
static const float m_kMinOffset = 1e-30F
Detailed Description
computation of non-negative matrix factorization
Definition at line 47 of file ToolNmf.h.
Constructor & Destructor Documentation
CNmf() [1/2]
CNmf::CNmf (void)
Definition at line 9 of file ToolNmf.cpp.
{
   reset();
}
References reset().
~CNmf()
CNmf::~CNmf (void) virtual
Definition at line 14 of file ToolNmf.cpp.
{
    reset();
}
References reset().
CNmf() [2/2]
CNmf::CNmf (const CNmf & that) private
disallow copy construction
Member Function Documentation
compNmf()
Error_t CNmf::compNmf (CNmfResult * pCNmfResult, float ** ppfInput)
Definition at line 59 of file ToolNmf.cpp.
{
    if (!pCNmfResult || !ppfInput)
        return Error_t::kFunctionInvalidArgsError;
    if (!m_bIsInitialized || !pCNmfResult->isInitialized())
        return Error_t::kFunctionIllegalCallError;
    enum Cost_t
    {
        kStartCost,
        kPrevCost,
        kCurrCost,
        kNumCosts
    };
    float afCost[kNumCosts] = { 0 };
    for (int k = 0; k < m_iMaxIter; k++)
    {
        afCost[kCurrCost] = runNmfIter(pCNmfResult, ppfInput);
        assert(!std::isnan(afCost[kCurrCost]));
        if (k > 0)
        {
            if (std::abs((afCost[kCurrCost] - afCost[kPrevCost]) / (afCost[kStartCost] - afCost[kCurrCost] + m_kMinOffset)) < .001F)
                break;
        }
        else
            afCost[kStartCost] = afCost[kCurrCost];
        afCost[kPrevCost] = afCost[kCurrCost];
    }
    return Error_t::kNoError;
}
References CNmfResult::isInitialized(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iMaxIter, m_kMinOffset, and runNmfIter().
init()
Error_t CNmf::init (CNmfResult * pCNmfResult, int iRank, int iNumRows, int iNumCols, int iMaxIter = 300, float fSparsity = 0)
initializes the class with the size of the distance matrix
Parameters
pCNmfResult class holding the result to be initialized (user allocated)
iRank NMF rank
iNumRows number of rows of matrix to be factorized
iNumCols number of columns of matrix to be factorized
iMaxIter maximum number of iterations
fSparsity sparsity weight
Returns
Error_t
Definition at line 19 of file ToolNmf.cpp.
{
    if (!pCNmfResult || iRank <= 0 || iNumRows <= 0 || iNumCols <= 0 || iMaxIter <= 0)
        return Error_t::kFunctionInvalidArgsError;
    pCNmfResult->init(iRank, iNumRows, iNumCols);
    m_iNumRows = iNumRows;
    m_iMaxIter = iMaxIter;
    m_fSparsity = fSparsity;
    CMatrix::alloc(m_ppfX, iNumRows, iNumCols);
    CMatrix::alloc(m_ppfOnes, iNumRows, iNumCols);
    CMatrix::setValue(m_ppfOnes, 1.F, iNumRows, iNumCols);
    m_iAllocSize = std::max(std::max(iRank, iNumRows), iNumCols);
    CMatrix::alloc(m_ppfTransp, m_iAllocSize, m_iAllocSize);
    CMatrix::alloc(m_ppfNum, m_iAllocSize, m_iAllocSize);
    CMatrix::alloc(m_ppfDenom, m_iAllocSize, m_iAllocSize);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CMatrix::alloc(), CNmfResult::init(), kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSparsity, m_iAllocSize, m_iMaxIter, m_iNumRows, m_ppfDenom, m_ppfNum, m_ppfOnes, m_ppfTransp, m_ppfX, and CMatrix::setValue().
operator=()
CNmf & CNmf::operator= (const CNmf & c) private
reset()
Error_t CNmf::reset (void)
resets all internal class members
Returns
Error_t
Definition at line 44 of file ToolNmf.cpp.
{
    m_bIsInitialized = false;
    CMatrix::free(m_ppfX, m_iNumRows);
    CMatrix::free(m_ppfOnes, m_iNumRows);
    CMatrix::free(m_ppfTransp, m_iAllocSize);
    CMatrix::free(m_ppfNum, m_iAllocSize);
    CMatrix::free(m_ppfDenom, m_iAllocSize);
    m_iMaxIter = 0;
    m_fSparsity = 0;
    return Error_t::kNoError;
}
References CMatrix::free(), kNoError, m_bIsInitialized, m_fSparsity, m_iAllocSize, m_iMaxIter, m_iNumRows, m_ppfDenom, m_ppfNum, m_ppfOnes, m_ppfTransp, and m_ppfX.
Referenced by CNmf(), and ~CNmf().
runNmfIter()
float CNmf::runNmfIter (CNmfResult * pNmfResult, float ** ppfInput) private
Definition at line 97 of file ToolNmf.cpp.
{
    float** ppfW = pCNmfResult->getMatPointer(CNmfResult::kW);
    float** ppfH = pCNmfResult->getMatPointer(CNmfResult::kH);
    float** ppfXHat = pCNmfResult->getMatPointer(CNmfResult::kXHat);
    int iRank = pCNmfResult->getMatCols(CNmfResult::kW);
    int iNumObs = pCNmfResult->getMatCols(CNmfResult::kH);
    int iNumBins = pCNmfResult->getMatRows(CNmfResult::kW);
    const bool bUpdateH = true,
        bUpdateW = true;
    // compute current estimate
    CMatrix::mulMatMat(ppfXHat, ppfW, ppfH, iNumBins, iRank, iRank, iNumObs);
    CMatrix::addC_I(ppfXHat, m_kMinOffset, iNumBins, iNumObs);
    //m_ppfX
    CMatrix::copy(m_ppfX, ppfInput, iNumBins, iNumObs);
    CMatrix::div_I(m_ppfX, ppfXHat, iNumBins, iNumObs);
    // update H
    if (bUpdateH)
    {
        CMatrix::transpose(m_ppfTransp, ppfW, iNumBins, iRank);
        // denominator
        CMatrix::mulMatMat(m_ppfDenom, m_ppfTransp, m_ppfOnes, iRank, iNumBins, iNumBins, iNumObs);
        CMatrix::addC_I(m_ppfDenom, m_fSparsity + m_kMinOffset, iRank, iNumObs);
        // numerator
        CMatrix::mulMatMat(m_ppfNum, m_ppfTransp, m_ppfX, iRank, iNumBins, iNumBins, iNumObs);
        CMatrix::div_I(m_ppfNum, m_ppfDenom, iRank, iNumObs);
        CMatrix::mul_I(ppfH, m_ppfNum, iRank, iNumObs);
        // clean small values
        CMatrix::setZeroBelowThresh(ppfH, iRank, iNumObs, m_kMinOffset);
    }
    // update W
    if (bUpdateW)
    {
        CMatrix::transpose(m_ppfTransp, ppfH, iRank, iNumObs);
        // denominator
        CMatrix::mulMatMat(m_ppfDenom, m_ppfOnes, m_ppfTransp, iNumBins, iNumObs, iNumObs, iRank);
        CMatrix::addC_I(m_ppfDenom, m_kMinOffset, iNumBins, iRank);
        // numerator
        CMatrix::mulMatMat(m_ppfNum, m_ppfX, m_ppfTransp, iNumBins, iNumObs, iNumObs, iRank);
        CMatrix::div_I(m_ppfNum, m_ppfDenom, iNumBins, iRank);
        CMatrix::mul_I(ppfW, m_ppfNum, iNumBins, iRank);
        // normalize
        CMatrix::vecnorm_I(ppfW, iNumBins, iRank);
        // clean small values
        CMatrix::setZeroBelowThresh(ppfW, iNumBins, iRank, m_kMinOffset);
    }
    // compute error
    CMatrix::mulMatMat(ppfXHat, ppfW, ppfH, iNumBins, iRank, iRank, iNumObs);
    CMatrix::addC_I(ppfXHat, m_kMinOffset, iNumBins, iNumObs);
    // deal with sparsity
    CMatrix::addC_I(ppfXHat, m_fSparsity * CMatrix::getNorm(ppfXHat, iNumBins, iNumObs), iNumBins, iNumObs);
    return CMatrix::calcKlDivergence(ppfInput, ppfXHat, iNumBins, iNumObs);
}
References CMatrix::addC_I(), CMatrix::calcKlDivergence(), CMatrix::copy(), CMatrix::div_I(), CNmfResult::getMatCols(), CNmfResult::getMatPointer(), CNmfResult::getMatRows(), CMatrix::getNorm(), CNmfResult::kH, CNmfResult::kW, CNmfResult::kXHat, m_fSparsity, m_kMinOffset, m_ppfDenom, m_ppfNum, m_ppfOnes, m_ppfTransp, m_ppfX, CMatrix::mul_I(), CMatrix::mulMatMat(), CMatrix::setZeroBelowThresh(), CMatrix::transpose(), and CMatrix::vecnorm_I().
Referenced by compNmf().
Member Data Documentation
m_bIsInitialized
bool CNmf::m_bIsInitialized = false private
true if init has been called
Definition at line 89 of file ToolNmf.h.
Referenced by compNmf(), init(), and reset().
m_fSparsity
float CNmf::m_fSparsity = 0 private
Definition at line 84 of file ToolNmf.h.
Referenced by init(), reset(), and runNmfIter().
m_iAllocSize
int CNmf::m_iAllocSize = 0 private
Definition at line 86 of file ToolNmf.h.
Referenced by init(), and reset().
m_iMaxIter
int CNmf::m_iMaxIter = 0 private
Definition at line 85 of file ToolNmf.h.
Referenced by compNmf(), init(), and reset().
m_iNumRows
int CNmf::m_iNumRows = 0 private
Definition at line 87 of file ToolNmf.h.
Referenced by init(), and reset().
m_kMinOffset
const float CNmf::m_kMinOffset = 1e-30F static private
Definition at line 91 of file ToolNmf.h.
Referenced by compNmf(), and runNmfIter().
m_ppfDenom
float ** CNmf::m_ppfDenom = 0 private
Definition at line 83 of file ToolNmf.h.
Referenced by init(), reset(), and runNmfIter().
m_ppfNum
float ** CNmf::m_ppfNum = 0 private
Definition at line 82 of file ToolNmf.h.
Referenced by init(), reset(), and runNmfIter().
m_ppfOnes
float ** CNmf::m_ppfOnes = 0 private
Definition at line 80 of file ToolNmf.h.
Referenced by init(), reset(), and runNmfIter().
m_ppfTransp
float ** CNmf::m_ppfTransp = 0 private
Definition at line 81 of file ToolNmf.h.
Referenced by init(), reset(), and runNmfIter().
m_ppfX
float** CNmf::m_ppfX = 0 private
Definition at line 79 of file ToolNmf.h.
Referenced by init(), reset(), and runNmfIter().
The documentation for this class was generated from the following files:
ToolNmf.h
ToolNmf.cpp