ACA: CKmeans Class Reference
CKmeans Class Reference
implements kmeans clustering
#include <ToolSimpleKmeans.h>
Public Member Functions
CKmeans (void)
virtual ~CKmeans (void)
Error_t init (int iK, int iNumFeatures, int iNumObservations, int iMaxIter=300)
Error_t reset ()
Error_t compKmeans (int *piResult, float **ppfFeatures)
Private Types
enum States_t { kPrev , kCurr , kNumStates }
Private Member Functions
CKmeans (const CKmeans &that)
disallow copy construction
CKmeans & operator= (const CKmeans &c)
void reinitClusterMeans_ (float **ppfFeatures)
void initClusterMeans_ (float **ppfFeatures)
void computeClusterMeans_ (float **ppfFeatures, const int *piResult)
bool checkConverged_ ()
void assignClusterLabels_ (int *piResult, float **ppfFeatures)
Private Attributes
float ** m_appfClusterMeans [kNumStates] = { 0 }
contains the current and previous cluster means
float * m_pfProc = 0
temporary pre-allocated memory buffer
float * m_pfDist = 0
buffer for distance calculation
int * m_piClusterSize = 0
number of observations per cluster
int m_iNumFeatures = 0
number of feature dimension (matrix rows)
int m_iNumObs = 0
number of observations (matrix cols)
int m_iK = 0
number of clusters
int m_iMaxIter = 0
maximum number of iterations
bool m_bIsInitialized = false
Detailed Description
implements kmeans clustering
Definition at line 15 of file ToolSimpleKmeans.h.
Member Enumeration Documentation
States_t
enum CKmeans::States_t private
Enumerator
kPrev
kCurr
kNumStates
Definition at line 46 of file ToolSimpleKmeans.h.
    {
        kPrev,
        kCurr,
        kNumStates
    };
Constructor & Destructor Documentation
CKmeans() [1/2]
CKmeans::CKmeans (void) inline
Definition at line 19 of file ToolSimpleKmeans.h.
{};
~CKmeans()
CKmeans::~CKmeans (void) virtual
Definition at line 9 of file ToolSimpleKmeans.cpp.
{
    this->reset();
}
References reset().
CKmeans() [2/2]
CKmeans::CKmeans (const CKmeans & that) private
disallow copy construction
Member Function Documentation
assignClusterLabels_()
void CKmeans::assignClusterLabels_ (int * piResult, float ** ppfFeatures) private
assigns cluster labels given the means
Parameters
piResult new cluster assignments
ppfFeatures input matrix of dimesions iNumFeatures X iNumObservations
Returns
Definition at line 161 of file ToolSimpleKmeans.cpp.
{
    CVector::setZero(m_piClusterSize, m_iK);
    for (auto n = 0; n < m_iNumObs; n++)
    {
        float fMin = 0;
        long long iMin = -1;
        CMatrix::getCol(m_pfProc, ppfFeatures, n, m_iNumFeatures, m_iNumObs);
        // compute distance to all training observations
        for (auto k = 0; k < m_iK; k++)
            m_pfDist[k] = CVector::distEuclidean(m_appfClusterMeans[kCurr][k], m_pfProc, m_iNumFeatures);
        CVector::findMin(m_pfDist, fMin, iMin, m_iK);
        piResult[n] = static_cast<int>(iMin);
        m_piClusterSize[iMin]++;
    }
}
References CVector::distEuclidean(), CVector::findMin(), CMatrix::getCol(), kCurr, m_appfClusterMeans, m_iK, m_iNumFeatures, m_iNumObs, m_pfDist, m_pfProc, m_piClusterSize, and CVector::setZero().
Referenced by compKmeans().
checkConverged_()
bool CKmeans::checkConverged_ () private
check if the means have changed during the last iteration
Returns
bool true if unchanged
Definition at line 143 of file ToolSimpleKmeans.cpp.
{
    float fSum = 0;
    int k = 0;
    CVector::copy(m_pfProc, m_appfClusterMeans[kCurr][k], m_iNumFeatures);
    CVector::sub_I(m_pfProc, m_appfClusterMeans[kPrev][k], m_iNumFeatures);
    while ((fSum += CVector::getSum(m_pfProc, m_iNumFeatures, true)) <= 0 && k < m_iK - 1)
    {
        k++;
        CVector::copy(m_pfProc, m_appfClusterMeans[kCurr][k], m_iNumFeatures);
        CVector::sub_I(m_pfProc, m_appfClusterMeans[kPrev][k], m_iNumFeatures);
    }
    if (fSum <= 0)
        return true;
    return false;
}
References CVector::copy(), CVector::getSum(), kCurr, kPrev, m_appfClusterMeans, m_iK, m_iNumFeatures, m_pfProc, and CVector::sub_I().
Referenced by compKmeans().
compKmeans()
Error_t CKmeans::compKmeans (int * piResult, float ** ppfFeatures)
clusters the data
Parameters
piResult resulting cluster indices, starting with 0 (length iNumObservations, user-allocated, to be written)
ppfFeatures input matrix of dimesions iNumFeatures X iNumObservations
Returns
Error_t
Definition at line 54 of file ToolSimpleKmeans.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!piResult || !ppfFeatures)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfFeatures[0])
        return Error_t::kFunctionInvalidArgsError;
    // init: randomly selected data points as cluster means
    initClusterMeans_(ppfFeatures);
    // assign observations to clusters
    assignClusterLabels_(piResult, ppfFeatures);
    // iterate
    for (auto i = 0; i < m_iMaxIter; i++)
    {
        // copy state to prev state
        CMatrix::copy(m_appfClusterMeans[kPrev], m_appfClusterMeans[kCurr], m_iK, m_iNumFeatures);
        // update cluster means
        computeClusterMeans_(ppfFeatures, piResult);
        // re-init empty clusters
        reinitClusterMeans_(ppfFeatures);
        // assign observations to clusters
        assignClusterLabels_(piResult, ppfFeatures);
        // check for change
        if (checkConverged_())
            break;
    }
    return Error_t::kNoError;
}
References assignClusterLabels_(), checkConverged_(), computeClusterMeans_(), CMatrix::copy(), initClusterMeans_(), kCurr, kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, kPrev, m_appfClusterMeans, m_bIsInitialized, m_iK, m_iMaxIter, m_iNumFeatures, and reinitClusterMeans_().
computeClusterMeans_()
void CKmeans::computeClusterMeans_ (float ** ppfFeatures, const int * piResult) private
computes the current cluster means
Parameters
ppfFeatures input matrix of dimesions iNumFeatures X iNumObservations
piResult current cluster assignments
Returns
Definition at line 126 of file ToolSimpleKmeans.cpp.
{
    CMatrix::setZero(m_appfClusterMeans[kCurr], m_iK, m_iNumFeatures);
    //CVector::setZero(m_piClusterSize, m_iK);
    for (auto n = 0; n < m_iNumObs; n++)
    {
        for (auto v = 0; v < m_iNumFeatures; v++)
            m_appfClusterMeans[kCurr][piResult[n]][v] += ppfFeatures[v][n];
    }
    for (auto k = 0; k < m_iK; k++)
    {
        if (!m_piClusterSize[k])
            continue;
        CVector::mulC_I(m_appfClusterMeans[kCurr][k], 1.F / m_piClusterSize[k], m_iNumFeatures);
    }
}
References kCurr, m_appfClusterMeans, m_iK, m_iNumFeatures, m_iNumObs, m_piClusterSize, CVector::mulC_I(), and CMatrix::setZero().
Referenced by compKmeans().
init()
Error_t CKmeans::init (int iK, int iNumFeatures, int iNumObservations, int iMaxIter = 300)
initializes the class
Parameters
iK target number of clusters
iNumFeatures number of rows of matrix to be clustered
iNumObservations number of columns of matrix to be clustered
iMaxIter maximum number of iterations
Returns
Error_t
Definition at line 14 of file ToolSimpleKmeans.cpp.
{
    if (iK <= 0 || iNumFeatures <= 0 || iNumObservations <= iK || iMaxIter < 1)
        return Error_t::kFunctionInvalidArgsError;
    m_iK = iK;
    m_iNumFeatures = iNumFeatures;
    m_iNumObs = iNumObservations;
    m_iMaxIter = iMaxIter;
    CMatrix::alloc(m_appfClusterMeans[kPrev], m_iK, m_iNumFeatures);
    CMatrix::alloc(m_appfClusterMeans[kCurr], m_iK, m_iNumFeatures);
    CVector::alloc(m_pfProc, std::max(m_iK, m_iNumFeatures));
    CVector::alloc(m_pfDist, m_iK);
    CVector::alloc(m_piClusterSize, m_iK);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), kCurr, kFunctionInvalidArgsError, kNoError, kPrev, m_appfClusterMeans, m_bIsInitialized, m_iK, m_iMaxIter, m_iNumFeatures, m_iNumObs, m_pfDist, m_pfProc, and m_piClusterSize.
initClusterMeans_()
void CKmeans::initClusterMeans_ (float ** ppfFeatures) private
randomly initializes the initial cluster means
Parameters
ppfFeatures input matrix of dimesions iNumFeatures X iNumObservations
Returns
Definition at line 111 of file ToolSimpleKmeans.cpp.
{
    CSynthesis::genNoise(m_pfProc, m_iK);
    CVector::addC_I(m_pfProc, 1.F, m_iK);
    CVector::mulC_I(m_pfProc, (m_iNumObs - 1) / 2.F, m_iK);
    for (auto k = 0; k < m_iK; k++)
    {
        int iIdx = CUtil::float2int<int>(m_pfProc[k]);
        assert(iIdx > 0 && iIdx < m_iNumObs);
        for (auto v = 0; v < m_iNumFeatures; v++)
            m_appfClusterMeans[kCurr][k][v] = ppfFeatures[v][iIdx];
    }
}
References CVector::addC_I(), CSynthesis::genNoise(), kCurr, m_appfClusterMeans, m_iK, m_iNumFeatures, m_iNumObs, m_pfProc, and CVector::mulC_I().
Referenced by compKmeans().
operator=()
CKmeans & CKmeans::operator= (const CKmeans & c) private
reinitClusterMeans_()
void CKmeans::reinitClusterMeans_ (float ** ppfFeatures) private
deals with empty clusters through new random initialization
Parameters
ppfFeatures input matrix of dimesions iNumFeatures X iNumObservations
Returns
Definition at line 92 of file ToolSimpleKmeans.cpp.
{
    if (CVector::getMin(m_piClusterSize, m_iK) > 0)
        return;
    CSynthesis::genNoise(m_pfProc, m_iK);
    CVector::addC_I(m_pfProc, 1.F, m_iK);
    CVector::mulC_I(m_pfProc, (m_iNumObs - 1) / 2.F, m_iK);
    for (auto k = 0; k < m_iK; k++)
    {
        if (m_piClusterSize[k] > 0)
            continue;
        int iIdx = CUtil::float2int<int>(m_pfProc[k]);
        assert(iIdx > 0 && iIdx < m_iNumObs);
        for (auto v = 0; v < m_iNumFeatures; v++)
            m_appfClusterMeans[kCurr][k][v] = ppfFeatures[v][iIdx];
    }
}
References CVector::addC_I(), CSynthesis::genNoise(), CVector::getMin(), kCurr, m_appfClusterMeans, m_iK, m_iNumFeatures, m_iNumObs, m_pfProc, m_piClusterSize, and CVector::mulC_I().
Referenced by compKmeans().
reset()
Error_t CKmeans::reset (void)
resets all internal class members
Returns
Error_t
Definition at line 36 of file ToolSimpleKmeans.cpp.
{
    m_bIsInitialized = false;
    CMatrix::free(m_appfClusterMeans[kPrev], m_iK);
    CMatrix::free(m_appfClusterMeans[kCurr], m_iK);
    CVector::free(m_pfProc);
    CVector::free(m_pfDist);
    CVector::free(m_piClusterSize);
    m_iK = 0;
    m_iNumFeatures = 0;
    m_iNumObs = 0;
    m_iMaxIter = 0;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kCurr, kNoError, kPrev, m_appfClusterMeans, m_bIsInitialized, m_iK, m_iMaxIter, m_iNumFeatures, m_iNumObs, m_pfDist, m_pfProc, and m_piClusterSize.
Referenced by ~CKmeans().
Member Data Documentation
m_appfClusterMeans
float** CKmeans::m_appfClusterMeans[kNumStates] = { 0 } private
contains the current and previous cluster means
Definition at line 91 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), checkConverged_(), compKmeans(), computeClusterMeans_(), init(), initClusterMeans_(), reinitClusterMeans_(), and reset().
m_bIsInitialized
bool CKmeans::m_bIsInitialized = false private
Definition at line 103 of file ToolSimpleKmeans.h.
Referenced by compKmeans(), init(), and reset().
m_iK
int CKmeans::m_iK = 0 private
number of clusters
Definition at line 100 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), checkConverged_(), compKmeans(), computeClusterMeans_(), init(), initClusterMeans_(), reinitClusterMeans_(), and reset().
m_iMaxIter
int CKmeans::m_iMaxIter = 0 private
maximum number of iterations
Definition at line 101 of file ToolSimpleKmeans.h.
Referenced by compKmeans(), init(), and reset().
m_iNumFeatures
int CKmeans::m_iNumFeatures = 0 private
number of feature dimension (matrix rows)
Definition at line 98 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), checkConverged_(), compKmeans(), computeClusterMeans_(), init(), initClusterMeans_(), reinitClusterMeans_(), and reset().
m_iNumObs
int CKmeans::m_iNumObs = 0 private
number of observations (matrix cols)
Definition at line 99 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), computeClusterMeans_(), init(), initClusterMeans_(), reinitClusterMeans_(), and reset().
m_pfDist
float * CKmeans::m_pfDist = 0 private
buffer for distance calculation
Definition at line 94 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), init(), and reset().
m_pfProc
float* CKmeans::m_pfProc = 0 private
temporary pre-allocated memory buffer
Definition at line 93 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), checkConverged_(), init(), initClusterMeans_(), reinitClusterMeans_(), and reset().
m_piClusterSize
int* CKmeans::m_piClusterSize = 0 private
number of observations per cluster
Definition at line 96 of file ToolSimpleKmeans.h.
Referenced by assignClusterLabels_(), computeClusterMeans_(), init(), reinitClusterMeans_(), and reset().
The documentation for this class was generated from the following files:
ToolSimpleKmeans.h
ToolSimpleKmeans.cpp