ACA: Catch::ReusableStringStream Class Reference
Catch::ReusableStringStream Class Reference
#include <catch.hpp>
Public Member Functions
ReusableStringStream ()
~ReusableStringStream ()
auto str () const -> std::string
template<typename T >
auto operator<< (T const &value) -> ReusableStringStream &
auto get () -> std::ostream &
Private Attributes
std::size_t m_index
std::ostream * m_oss
Additional Inherited Members
Private Member Functions inherited from Catch::NonCopyable
NonCopyable ()
virtual ~NonCopyable ()
Detailed Description
Definition at line 1440 of file catch.hpp.
Constructor & Destructor Documentation
ReusableStringStream()
Catch::ReusableStringStream::ReusableStringStream ()
~ReusableStringStream()
Catch::ReusableStringStream::~ReusableStringStream ()
Member Function Documentation
get()
auto Catch::ReusableStringStream::get () -> std::ostream& inline
Definition at line 1454 of file catch.hpp.
{ return *m_oss; }
References m_oss.
operator<<()
template<typename T > auto Catch::ReusableStringStream::operator<< (T const & value) -> ReusableStringStream& inline
Definition at line 1450 of file catch.hpp.
{
            *m_oss << value;
            return *this;
        }
References m_oss, and Catch::Generators::value().
str()
auto Catch::ReusableStringStream::str () const -> std::string
Referenced by Catch::StringMaker< T, typename >::convert(), Catch::Detail::rangeToString(), and Catch::rangeToString().
Member Data Documentation
m_index
std::size_t Catch::ReusableStringStream::m_index private
Definition at line 1441 of file catch.hpp.
m_oss
std::ostream* Catch::ReusableStringStream::m_oss private
Definition at line 1442 of file catch.hpp.
Referenced by get(), and operator<<().
The documentation for this class was generated from the following file:
catch.hpp