ACA: CInstFreq Class Reference
CInstFreq Class Reference
class for extracting the instantaneous frequency
#include <ToolInstFreq.h>
Public Member Functions
CInstFreq (int iFftLength, int iHopLength, float fSampleRate)
virtual ~CInstFreq ()
Error_t process (float *pfInstFreq, const CFft::complex_t *pfSpectrum)
Private Types
enum Phase_t { kPhasePrev , kPhaseCurr , kNumPhases }
Private Member Functions
CInstFreq (const CInstFreq &that)
CInstFreq & operator= (const CInstFreq &c)
void princArg_ (float *pfSrcDestPhase)
Private Attributes
int m_iPhaseLength = 0
length of phase spectrum
int m_iHopLength = 0
hop length in samples
float m_fSampleRate = 0.F
sample rate in hz
float * m_apfPhase [kNumPhases] = { 0 }
pointers to buffer for storing the phase
float * m_pfSwapBuff = 0
temporary process buffer and storage of previous phase spectrum
float * m_pfOmega = 0
constant offset
CFft * m_pCFft = 0
fft instance for handling compex spectra
Detailed Description
class for extracting the instantaneous frequency
Definition at line 17 of file ToolInstFreq.h.
Member Enumeration Documentation
Phase_t
enum CInstFreq::Phase_t private
Enumerator
kPhasePrev
kPhaseCurr
kNumPhases
Definition at line 82 of file ToolInstFreq.h.
    {
        kPhasePrev,
        kPhaseCurr,
        kNumPhases
    };
Constructor & Destructor Documentation
CInstFreq() [1/2]
CInstFreq::CInstFreq (int iFftLength, int iHopLength, float fSampleRate) inline explicit
Definition at line 21 of file ToolInstFreq.h.
                                                                          :
        m_iHopLength(iHopLength),
        m_fSampleRate(fSampleRate)
    {
        // init Fft instance for handling phase and stuff
        m_pCFft = new CFft();
        m_pCFft->init(iFftLength);
        m_iPhaseLength = m_pCFft->getLength(CFft::kLengthPhase);
        CVector::alloc(m_pfOmega, m_iPhaseLength);
        // use one buffer with two pointers
        CVector::alloc(m_pfSwapBuff, 2 * static_cast<long long>(m_iPhaseLength));
        m_apfPhase[0] = &m_pfSwapBuff[0];
        m_apfPhase[1] = &m_pfSwapBuff[m_iPhaseLength];
        //init omega
        for (auto k = 0; k < m_iPhaseLength; k++)
            m_pfOmega[k] = static_cast<float>(m_iHopLength * 2.* k * M_PI/ iFftLength);
    }
References CVector::alloc(), CFft::getLength(), CFft::init(), CFft::kLengthPhase, m_apfPhase, m_iHopLength, m_iPhaseLength, m_pCFft, m_pfOmega, m_pfSwapBuff, and M_PI.
~CInstFreq()
virtual CInstFreq::~CInstFreq () inline virtual
Definition at line 42 of file ToolInstFreq.h.
    {
       CVector::free(m_pfOmega);
       CVector::free(m_pfSwapBuff);
        delete m_pCFft;
    }
References CVector::free(), m_pCFft, m_pfOmega, and m_pfSwapBuff.
CInstFreq() [2/2]
CInstFreq::CInstFreq (const CInstFreq & that) private
Member Function Documentation
operator=()
CInstFreq & CInstFreq::operator= (const CInstFreq & c) private
princArg_()
void CInstFreq::princArg_ (float * pfSrcDestPhase) inline private
Definition at line 92 of file ToolInstFreq.h.
    {
        assert(pfSrcDestPhase);
        for (auto k = 0; k < m_iPhaseLength; k++)
            pfSrcDestPhase[k] = static_cast<float>(std::fmod(pfSrcDestPhase[k] + M_PI, -2 * M_PI) + M_PI);
        return;
    }
References m_iPhaseLength, and M_PI.
Referenced by process().
process()
Error_t CInstFreq::process (float * pfInstFreq, const CFft::complex_t * pfSpectrum) inline
performs the InstFreq computation on subsequent spectra
Parameters
pfInstFreq output vector containing the estimated frequencies (to be written), length iFftLength/2+1
pfSpectrum current (complex) spectrum return Error_t
Definition at line 56 of file ToolInstFreq.h.
    {
        if (!pfInstFreq || !pfSpectrum)
            return Error_t::kFunctionInvalidArgsError;
        // get current phase
        m_pCFft->getPhase(m_apfPhase[kPhaseCurr], pfSpectrum);
        // calc instantaneous frequency
        CVector::sub_I(m_apfPhase[kPhasePrev], m_apfPhase[kPhaseCurr], m_iPhaseLength);
        CVector::add_I(m_apfPhase[kPhasePrev], m_pfOmega, m_iPhaseLength);
        CVector::mulC_I(m_apfPhase[kPhasePrev], -1.0F, m_iPhaseLength);
        princArg_(m_apfPhase[kPhasePrev]);
        CVector::add_I(m_apfPhase[kPhasePrev], m_pfOmega, m_iPhaseLength);
        CVector::copy(pfInstFreq, m_apfPhase[kPhasePrev], m_iPhaseLength);
        CVector::mulC_I(pfInstFreq, static_cast<float>(m_fSampleRate / (m_iHopLength * 2. * M_PI)), m_iPhaseLength);
        // remember phase for next call but avoid copying
        CUtil::swap(m_apfPhase[kPhasePrev], m_apfPhase[kPhaseCurr]);
        return Error_t::kNoError;
    }
References CVector::add_I(), CVector::copy(), CFft::getPhase(), kFunctionInvalidArgsError, kNoError, kPhaseCurr, kPhasePrev, m_apfPhase, m_fSampleRate, m_iHopLength, m_iPhaseLength, m_pCFft, m_pfOmega, M_PI, CVector::mulC_I(), princArg_(), CVector::sub_I(), and CUtil::swap().
Member Data Documentation
m_apfPhase
float* CInstFreq::m_apfPhase[kNumPhases] = { 0 } private
pointers to buffer for storing the phase
Definition at line 106 of file ToolInstFreq.h.
Referenced by CInstFreq(), and process().
m_fSampleRate
float CInstFreq::m_fSampleRate = 0.F private
sample rate in hz
Definition at line 104 of file ToolInstFreq.h.
Referenced by process().
m_iHopLength
int CInstFreq::m_iHopLength = 0 private
hop length in samples
Definition at line 103 of file ToolInstFreq.h.
Referenced by CInstFreq(), and process().
m_iPhaseLength
int CInstFreq::m_iPhaseLength = 0 private
length of phase spectrum
Definition at line 102 of file ToolInstFreq.h.
Referenced by CInstFreq(), princArg_(), and process().
m_pCFft
CFft* CInstFreq::m_pCFft = 0 private
fft instance for handling compex spectra
Definition at line 110 of file ToolInstFreq.h.
Referenced by CInstFreq(), process(), and ~CInstFreq().
m_pfOmega
float* CInstFreq::m_pfOmega = 0 private
constant offset
Definition at line 108 of file ToolInstFreq.h.
Referenced by CInstFreq(), process(), and ~CInstFreq().
m_pfSwapBuff
float* CInstFreq::m_pfSwapBuff = 0 private
temporary process buffer and storage of previous phase spectrum
Definition at line 107 of file ToolInstFreq.h.
Referenced by CInstFreq(), and ~CInstFreq().
The documentation for this class was generated from the following file:
ToolInstFreq.h