ACA: CDtw Class Reference
CDtw Class Reference
simple dynamic time warping
#include <ToolSimpleDtw.h>
Public Types
enum MatrixDimension_t { kRow , kCol , kNumMatrixDimensions }
Public Member Functions
CDtw (void)
virtual ~CDtw (void)
Error_t init (int iNumRows, int iNumCols)
Error_t reset ()
Error_t compDtw (float **ppfDistanceMatrix)
int getPathLength ()
float getPathCost () const
Error_t getPath (int **ppiPathResult) const
Private Types
enum Directions_t { kHoriz , kVert , kDiag , kNumDirections }
enum InternalMemory_t { kRowCurr , kRowNext , kNumVectors }
Private Member Functions
CDtw (const CDtw &that)
CDtw & operator= (const CDtw &c)
Static Private Member Functions
static Directions_t findMin_ (float fHorizCost, float fVertCost, float fDiagCost, float &fResultCost)
Private Attributes
bool m_bIsInitialized = false
true if init has been called
bool m_bWasProcessed = false
true if compDtw has been called
float * m_apfCost [kNumVectors] = {0,0}
only allocate two rows instead of a whole matrix for the cost
float m_fOverallCost = 0
overall cost
unsigned char ** m_ppePathIdx = 0
matrix with directions for traceback
int m_iLengthOfPath = 0
overall length of path
int m_aiMatrixDimensions [kNumMatrixDimensions] = {0,0}
size of distance matrix
Static Private Attributes
static const int aiDecrement [kNumDirections][kNumMatrixDimensions]
index changes for directions
Detailed Description
simple dynamic time warping
Definition at line 10 of file ToolSimpleDtw.h.
Member Enumeration Documentation
Directions_t
enum CDtw::Directions_t private
Enumerator
kHoriz
move horizontally
kVert
move vertically
kDiag
move diagonally
kNumDirections
Definition at line 62 of file ToolSimpleDtw.h.
    {
        kHoriz, //!< move horizontally
        kVert, //!< move vertically
        kDiag, //!< move diagonally
        kNumDirections
    };
InternalMemory_t
enum CDtw::InternalMemory_t private
Enumerator
kRowCurr
current row index (cost calculation)
kRowNext
next row index (cost calculation)
kNumVectors
Definition at line 70 of file ToolSimpleDtw.h.
    {
        kRowCurr, //!< current row index (cost calculation)
        kRowNext, //!< next row index (cost calculation)
        kNumVectors
    };
MatrixDimension_t
enum CDtw::MatrixDimension_t
Enumerator
kRow
kCol
kNumMatrixDimensions
Definition at line 13 of file ToolSimpleDtw.h.
    {
        kRow,
        kCol,
        kNumMatrixDimensions
    };
Constructor & Destructor Documentation
CDtw() [1/2]
CDtw::CDtw (void)
Definition at line 15 of file ToolSimpleDtw.cpp.
                 :
    m_bIsInitialized(false),
    m_bWasProcessed(false),
    m_fOverallCost(0),
    m_ppePathIdx(0),
    m_iLengthOfPath(0)
{
    CVector::setZero(m_apfCost, kNumVectors);
    CVector::setZero(m_aiMatrixDimensions, kNumMatrixDimensions);
    reset();
}
References kNumMatrixDimensions, kNumVectors, m_aiMatrixDimensions, m_apfCost, reset(), and CVector::setZero().
~CDtw()
CDtw::~CDtw (void) virtual
Definition at line 28 of file ToolSimpleDtw.cpp.
{
    reset();
}
References reset().
CDtw() [2/2]
CDtw::CDtw (const CDtw & that) private
Member Function Documentation
compDtw()
Error_t CDtw::compDtw (float ** ppfDistanceMatrix)
computes cost and path w/o back-tracking
Parameters
ppfDistanceMatrix (dimensions [rows][columns])
Returns
Error_t
< variable that will only contain the cost of the first column (for the current row to be processed)
Definition at line 73 of file ToolSimpleDtw.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!ppfDistanceMatrix)
        return Error_t::kFunctionInvalidArgsError;
    float fFirstColCost     = 0;        //!< variable that will only contain the cost of the first column (for the current row to be processed)
    // initialize
    CVectorFloat::setZero(m_apfCost[kRowNext], m_aiMatrixDimensions[kCol]);
    m_apfCost[kRowCurr][0]  = ppfDistanceMatrix[0][0];
    fFirstColCost           = ppfDistanceMatrix[0][0];
    m_ppePathIdx[0][0]      = kDiag;
    for (int j = 1; j < m_aiMatrixDimensions[kCol]; j++)
    {
        m_apfCost[kRowCurr][j]  = m_apfCost[kRowCurr][j-1] + ppfDistanceMatrix[0][j];
        m_ppePathIdx[0][j] = kHoriz;
    }
    for (int i = 1; i < m_aiMatrixDimensions[kRow]; i++)
    {
        m_ppePathIdx[i][0] = kVert;
    }
    // compute cost 'matrix' (we only use two rows here) and store backtracking path
    for (int i = 1; i < m_aiMatrixDimensions[kRow]; i++)
    {
        // init the variables we need for the current row (remember the cost in the first column, and then increment it)
        m_apfCost[kRowCurr][0]  = fFirstColCost;
        fFirstColCost          += ppfDistanceMatrix[i][0];
        m_apfCost[kRowNext][0]  = fFirstColCost;
        for (int j = 1; j < m_aiMatrixDimensions[kCol]; j++)
        {
            m_ppePathIdx[i][j] = static_cast<unsigned char>(findMin_(    m_apfCost[kRowNext][j-1],   // horiz
                                                                            m_apfCost[kRowCurr][j],     // vert
                                                                            m_apfCost[kRowCurr][j-1],   // diag
                                                                            m_apfCost[kRowNext][j]));   // minimum cost output
            m_apfCost[kRowNext][j] += ppfDistanceMatrix[i][j];
        }
        // swap the pointers of our two buffers as we proceed to the next row
        CUtil::swap(m_apfCost[kRowCurr], m_apfCost[kRowNext]);
    }
    // all done
    m_bWasProcessed = true;
    return Error_t::kNoError;
}
References findMin_(), kCol, kDiag, kFunctionInvalidArgsError, kHoriz, kNoError, kNotInitializedError, kRow, kRowCurr, kRowNext, kVert, m_aiMatrixDimensions, m_apfCost, m_bIsInitialized, m_bWasProcessed, m_ppePathIdx, CVectorFloat::setZero(), and CUtil::swap().
findMin_()
static Directions_t CDtw::findMin_ (float fHorizCost, float fVertCost, float fDiagCost, float & fResultCost) inline static private
Definition at line 78 of file ToolSimpleDtw.h.
    {
        Directions_t eDirection = kDiag;
        fResultCost = fDiagCost;
        if (fHorizCost < fDiagCost)
        {
            eDirection  = kHoriz;
            fResultCost = fHorizCost;
        }
        if (fVertCost < fHorizCost && fVertCost < fDiagCost)
        {
            eDirection  = kVert;
            fResultCost = fVertCost;
        }
        return eDirection;
    }
References kDiag, kHoriz, and kVert.
Referenced by compDtw().
getPath()
Error_t CDtw::getPath (int ** ppiPathResult) const
returns the path
See also
getPathLength
Parameters
ppiPathResult pointer to memory the result is written to (dimensions [2][length_of_path])
Returns
Error_t
Definition at line 151 of file ToolSimpleDtw.cpp.
{
    if (!ppiPathResult)
        return Error_t::kFunctionInvalidArgsError;
    if (m_iLengthOfPath <= 0)
        return Error_t::kFunctionIllegalCallError;
    int iIdx = m_iLengthOfPath - 1;
    // init
    ppiPathResult[kRow][0] = 0;
    ppiPathResult[kCol][0] = 0;
    ppiPathResult[kRow][iIdx] = m_aiMatrixDimensions[kRow] - 1;
    ppiPathResult[kCol][iIdx] = m_aiMatrixDimensions[kCol] - 1;
    while (iIdx > 0)
    {
        ppiPathResult[kRow][iIdx-1] = ppiPathResult[kRow][iIdx] + aiDecrement[m_ppePathIdx[ppiPathResult[kRow][iIdx]][ppiPathResult[kCol][iIdx]]][kRow];
        ppiPathResult[kCol][iIdx-1] = ppiPathResult[kCol][iIdx] + aiDecrement[m_ppePathIdx[ppiPathResult[kRow][iIdx]][ppiPathResult[kCol][iIdx]]][kCol];
        iIdx--;
    }
    return Error_t::kNoError;
}
References aiDecrement, kCol, kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, kRow, m_aiMatrixDimensions, m_iLengthOfPath, and m_ppePathIdx.
getPathCost()
float CDtw::getPathCost () const
returns the overall cost
Returns
float
Definition at line 146 of file ToolSimpleDtw.cpp.
{
    return m_apfCost[kRowCurr][m_aiMatrixDimensions[kCol]-1];
}
References kCol, kRowCurr, m_aiMatrixDimensions, and m_apfCost.
getPathLength()
int CDtw::getPathLength ()
returns the length of the path
Returns
int
Definition at line 125 of file ToolSimpleDtw.cpp.
{
    int i = m_aiMatrixDimensions[kRow]-1;
    int j = m_aiMatrixDimensions[kCol]-1;
    if (!m_bWasProcessed)
        return 0;
    m_iLengthOfPath = 1;
    while (i > 0 || j > 0)
    {
        int iNewI   = i + aiDecrement[m_ppePathIdx[i][j]][kRow];
        j          += aiDecrement[m_ppePathIdx[i][j]][kCol];
        i           = iNewI;
        m_iLengthOfPath++;
    }
    return m_iLengthOfPath;
}
References aiDecrement, kCol, kRow, m_aiMatrixDimensions, m_bWasProcessed, m_iLengthOfPath, and m_ppePathIdx.
init()
Error_t CDtw::init (int iNumRows, int iNumCols)
initializes the class with the size of the distance matrix
Parameters
iNumRows
iNumCols
Returns
Error_t
Definition at line 33 of file ToolSimpleDtw.cpp.
{
    if (iNumRows <= 0 || iNumCols <= 0)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    m_aiMatrixDimensions[kRow]  = iNumRows;
    m_aiMatrixDimensions[kCol]  = iNumCols;
    // allocate memory
    for (int i = 0; i < kNumVectors; i++)
        CVector::alloc(m_apfCost[i], m_aiMatrixDimensions[kCol]);
    CMatrix::alloc(m_ppePathIdx, m_aiMatrixDimensions[kRow], m_aiMatrixDimensions[kCol]);
    // all done here
    m_bIsInitialized    = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), kCol, kFunctionInvalidArgsError, kNoError, kNumVectors, kRow, m_aiMatrixDimensions, m_apfCost, m_bIsInitialized, m_ppePathIdx, and reset().
operator=()
CDtw & CDtw::operator= (const CDtw & c) private
reset()
Error_t CDtw::reset ()
resets all internal class members
Returns
Error_t
Definition at line 55 of file ToolSimpleDtw.cpp.
{
    m_bIsInitialized    = false;
    m_bWasProcessed     = false;
    CMatrix::free(m_ppePathIdx, m_aiMatrixDimensions[kRow]);
    for (int i = 0; i < kNumVectors; i++)
        CVector::free(m_apfCost[i]);
    m_aiMatrixDimensions[kRow]  = 0;
    m_aiMatrixDimensions[kCol]  = 0;
    m_fOverallCost              = 0;
    m_iLengthOfPath             = 0;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kCol, kNoError, kNumVectors, kRow, m_aiMatrixDimensions, m_apfCost, m_bIsInitialized, m_bWasProcessed, m_fOverallCost, m_iLengthOfPath, and m_ppePathIdx.
Referenced by CDtw(), init(), and ~CDtw().
Member Data Documentation
aiDecrement
const int CDtw::aiDecrement static private
Initial value:
=
{
    { 0, -1 },
    { -1, 0 },
    { -1, -1 }
}
index changes for directions
Definition at line 109 of file ToolSimpleDtw.h.
Referenced by getPath(), and getPathLength().
m_aiMatrixDimensions
int CDtw::m_aiMatrixDimensions[kNumMatrixDimensions] = {0,0} private
size of distance matrix
Definition at line 107 of file ToolSimpleDtw.h.
Referenced by CDtw(), compDtw(), getPath(), getPathCost(), getPathLength(), init(), and reset().
m_apfCost
float* CDtw::m_apfCost[kNumVectors] = {0,0} private
only allocate two rows instead of a whole matrix for the cost
Definition at line 101 of file ToolSimpleDtw.h.
Referenced by CDtw(), compDtw(), getPathCost(), init(), and reset().
m_bIsInitialized
bool CDtw::m_bIsInitialized = false private
true if init has been called
Definition at line 98 of file ToolSimpleDtw.h.
Referenced by compDtw(), init(), and reset().
m_bWasProcessed
bool CDtw::m_bWasProcessed = false private
true if compDtw has been called
Definition at line 99 of file ToolSimpleDtw.h.
Referenced by compDtw(), getPathLength(), and reset().
m_fOverallCost
float CDtw::m_fOverallCost = 0 private
overall cost
Definition at line 102 of file ToolSimpleDtw.h.
Referenced by reset().
m_iLengthOfPath
int CDtw::m_iLengthOfPath = 0 private
overall length of path
Definition at line 105 of file ToolSimpleDtw.h.
Referenced by getPath(), getPathLength(), and reset().
m_ppePathIdx
unsigned char** CDtw::m_ppePathIdx = 0 private
matrix with directions for traceback
Definition at line 104 of file ToolSimpleDtw.h.
Referenced by compDtw(), getPath(), getPathLength(), init(), and reset().
The documentation for this class was generated from the following files:
ToolSimpleDtw.h
ToolSimpleDtw.cpp