ACA: Catch::Capturer Class Reference
Catch::Capturer Class Reference
#include <catch.hpp>
Public Member Functions
Capturer (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType resultType, StringRef names)
~Capturer ()
void captureValue (size_t index, std::string const &value)
template<typename T >
void captureValues (size_t index, T const &value)
template<typename T , typename... Ts>
void captureValues (size_t index, T const &value, Ts const &... values)
Private Attributes
std::vector< MessageInfo > m_messages
IResultCapture & m_resultCapture = getResultCapture()
size_t m_captured = 0
Detailed Description
Definition at line 2652 of file catch.hpp.
Constructor & Destructor Documentation
Capturer()
Catch::Capturer::Capturer (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType resultType, StringRef names)
~Capturer()
Catch::Capturer::~Capturer ()
Member Function Documentation
captureValue()
void Catch::Capturer::captureValue (size_t index, std::string const & value)
captureValues() [1/2]
template<typename T > void Catch::Capturer::captureValues (size_t index, T const & value) inline
Definition at line 2663 of file catch.hpp.
{
            captureValue( index, Catch::Detail::stringify( value ) );
        }
References Catch::Detail::stringify(), and Catch::Generators::value().
captureValues() [2/2]
template<typename T , typename... Ts> void Catch::Capturer::captureValues (size_t index, T const & value, Ts const &... values) inline
Definition at line 2668 of file catch.hpp.
{
            captureValue( index, Catch::Detail::stringify(value) );
            captureValues( index+1, values... );
        }
References Catch::Detail::stringify(), Catch::Generators::value(), and Catch::Generators::values().
Member Data Documentation
m_captured
size_t Catch::Capturer::m_captured = 0 private
Definition at line 2655 of file catch.hpp.
m_messages
std::vector<MessageInfo> Catch::Capturer::m_messages private
Definition at line 2653 of file catch.hpp.
m_resultCapture
IResultCapture& Catch::Capturer::m_resultCapture = getResultCapture() private
Definition at line 2654 of file catch.hpp.
The documentation for this class was generated from the following file:
catch.hpp