ACA: Catch::AssertionHandler Class Reference
Catch::AssertionHandler Class Reference
#include <catch.hpp>
Public Member Functions
AssertionHandler (StringRef const &macroName, SourceLineInfo const &lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler ()
template<typename T >
void handleExpr (ExprLhs< T > const &expr)
void handleExpr (ITransientExpression const &expr)
void handleMessage (ResultWas::OfType resultType, StringRef const &message)
void handleExceptionThrownAsExpected ()
void handleUnexpectedExceptionNotThrown ()
void handleExceptionNotThrownAsExpected ()
void handleThrowingCallSkipped ()
void handleUnexpectedInflightException ()
void complete ()
void setCompleted ()
auto allowThrows () const -> bool
Private Attributes
AssertionInfo m_assertionInfo
AssertionReaction m_reaction
bool m_completed = false
IResultCapture & m_resultCapture
Detailed Description
Definition at line 2548 of file catch.hpp.
Constructor & Destructor Documentation
AssertionHandler()
Catch::AssertionHandler::AssertionHandler (StringRef const & macroName, SourceLineInfo const & lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler()
Catch::AssertionHandler::~AssertionHandler () inline
Definition at line 2560 of file catch.hpp.
{
            if ( !m_completed ) {
                m_resultCapture.handleIncomplete( m_assertionInfo );
            }
        }
References Catch::IResultCapture::handleIncomplete(), m_assertionInfo, m_completed, and m_resultCapture.
Member Function Documentation
allowThrows()
auto Catch::AssertionHandler::allowThrows () const -> bool
complete()
void Catch::AssertionHandler::complete ()
handleExceptionNotThrownAsExpected()
void Catch::AssertionHandler::handleExceptionNotThrownAsExpected ()
handleExceptionThrownAsExpected()
void Catch::AssertionHandler::handleExceptionThrownAsExpected ()
handleExpr() [1/2]
template<typename T > void Catch::AssertionHandler::handleExpr (ExprLhs< T > const & expr) inline
Definition at line 2567 of file catch.hpp.
{
            handleExpr( expr.makeUnaryExpr() );
        }
References handleExpr(), and Catch::ExprLhs< LhsT >::makeUnaryExpr().
Referenced by handleExpr().
handleExpr() [2/2]
void Catch::AssertionHandler::handleExpr (ITransientExpression const & expr)
handleMessage()
void Catch::AssertionHandler::handleMessage (ResultWas::OfType resultType, StringRef const & message)
handleThrowingCallSkipped()
void Catch::AssertionHandler::handleThrowingCallSkipped ()
handleUnexpectedExceptionNotThrown()
void Catch::AssertionHandler::handleUnexpectedExceptionNotThrown ()
handleUnexpectedInflightException()
void Catch::AssertionHandler::handleUnexpectedInflightException ()
setCompleted()
void Catch::AssertionHandler::setCompleted ()
Member Data Documentation
m_assertionInfo
AssertionInfo Catch::AssertionHandler::m_assertionInfo private
Definition at line 2549 of file catch.hpp.
Referenced by ~AssertionHandler().
m_completed
bool Catch::AssertionHandler::m_completed = false private
Definition at line 2551 of file catch.hpp.
Referenced by ~AssertionHandler().
m_reaction
AssertionReaction Catch::AssertionHandler::m_reaction private
Definition at line 2550 of file catch.hpp.
m_resultCapture
IResultCapture& Catch::AssertionHandler::m_resultCapture private
Definition at line 2552 of file catch.hpp.
Referenced by ~AssertionHandler().
The documentation for this class was generated from the following file:
catch.hpp