ACA: Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch > Struct Template Reference
Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch > Struct Template Reference
#include <catch.hpp>
Public Member Functions
ApproxMatcher (std::vector< T, AllocComp > const &comparator)
bool match (std::vector< T, AllocMatch > const &v) const override
std::string describe () const override
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & epsilon (T const &newEpsilon)
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & margin (T const &newMargin)
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & scale (T const &newScale)
Public Member Functions inherited from Catch::Matchers::Impl::MatcherBase< T >
MatchAllOf< T > operator&& (MatcherBase const &other) const
MatchAnyOf< T > operator|| (MatcherBase const &other) const
MatchNotOf< T > operator! () const
Public Member Functions inherited from Catch::Matchers::Impl::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
std::string toString () const
Public Member Functions inherited from Catch::Matchers::Impl::MatcherMethod< T >
virtual bool match (T const &arg) const=0
Public Attributes
std::vector< T, AllocComp > const & m_comparator
Catch::Detail::Approx approx = Catch::Detail::Approx::custom()
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::Impl::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual std::string describe () const =0
Protected Attributes inherited from Catch::Matchers::Impl::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename T, typename AllocComp, typename AllocMatch>
struct Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >
Definition at line 3681 of file catch.hpp.
Constructor & Destructor Documentation
ApproxMatcher()
template<typename T , typename AllocComp , typename AllocMatch > Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::ApproxMatcher (std::vector< T, AllocComp > const & comparator) inline
Definition at line 3683 of file catch.hpp.
: m_comparator(comparator) {}
Member Function Documentation
describe()
template<typename T , typename AllocComp , typename AllocMatch > std::string Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::describe () const inline override virtual
Implements Catch::Matchers::Impl::MatcherUntypedBase.
Definition at line 3693 of file catch.hpp.
{
                return "is approx: " + ::Catch::Detail::stringify( m_comparator );
            }
References Catch::Detail::stringify().
epsilon()
template<typename T , typename AllocComp , typename AllocMatch > template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> ApproxMatcher & Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::epsilon (T const & newEpsilon) inline
Definition at line 3697 of file catch.hpp.
{
                approx.epsilon(newEpsilon);
                return *this;
            }
References Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::epsilon().
Referenced by Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::epsilon().
margin()
template<typename T , typename AllocComp , typename AllocMatch > template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> ApproxMatcher & Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::margin (T const & newMargin) inline
Definition at line 3702 of file catch.hpp.
{
                approx.margin(newMargin);
                return *this;
            }
References Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::margin().
Referenced by Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::margin().
match()
template<typename T , typename AllocComp , typename AllocMatch > bool Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::match (std::vector< T, AllocMatch > const & v) const inline override
Definition at line 3685 of file catch.hpp.
{
                if (m_comparator.size() != v.size())
                    return false;
                for (std::size_t i = 0; i < v.size(); ++i)
                    if (m_comparator[i] != approx(v[i]))
                        return false;
                return true;
            }
scale()
template<typename T , typename AllocComp , typename AllocMatch > template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> ApproxMatcher & Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::scale (T const & newScale) inline
Definition at line 3707 of file catch.hpp.
{
                approx.scale(newScale);
                return *this;
            }
References Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::scale().
Referenced by Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::scale().
Member Data Documentation
approx
template<typename T , typename AllocComp , typename AllocMatch > Catch::Detail::Approx Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::approx = Catch::Detail::Approx::custom() mutable
Definition at line 3713 of file catch.hpp.
m_comparator
template<typename T , typename AllocComp , typename AllocMatch > std::vector<T, AllocComp> const& Catch::Matchers::Vector::ApproxMatcher< T, AllocComp, AllocMatch >::m_comparator
Definition at line 3712 of file catch.hpp.
The documentation for this struct was generated from the following file:
catch.hpp