ACA: Catch::Generators::ChunkGenerator< T > Class Template Reference
Catch::Generators::ChunkGenerator< T > Class Template Reference final
#include <catch.hpp>
Public Member Functions
ChunkGenerator (size_t size, GeneratorWrapper< T > generator)
std::vector< T > const & get () const override
bool next () override
Public Member Functions inherited from Catch::Generators::IGenerator< std::vector< T > >
virtual ~IGenerator ()=default
virtual std::vector< T > const & get () const=0
Public Member Functions inherited from Catch::Generators::GeneratorUntypedBase
GeneratorUntypedBase ()=default
virtual ~GeneratorUntypedBase ()
virtual bool next ()=0
Private Attributes
std::vector< T > m_chunk
size_t m_chunk_size
GeneratorWrapper< T > m_generator
bool m_used_up = false
Additional Inherited Members
Public Types inherited from Catch::Generators::IGenerator< std::vector< T > >
using type = std::vector< T >
Detailed Description
template<typename T>
class Catch::Generators::ChunkGenerator< T >
Definition at line 4297 of file catch.hpp.
Constructor & Destructor Documentation
ChunkGenerator()
template<typename T > Catch::Generators::ChunkGenerator< T >::ChunkGenerator (size_t size, GeneratorWrapper< T > generator) inline
Definition at line 4303 of file catch.hpp.
                                                                   :
            m_chunk_size(size), m_generator(std::move(generator))
        {
            m_chunk.reserve(m_chunk_size);
            if (m_chunk_size != 0) {
                m_chunk.push_back(m_generator.get());
                for (size_t i = 1; i < m_chunk_size; ++i) {
                    if (!m_generator.next()) {
                        Catch::throw_exception(GeneratorException("Not enough values to initialize the first chunk"));
                    }
                    m_chunk.push_back(m_generator.get());
                }
            }
        }
References Catch::Generators::GeneratorWrapper< T >::get(), Catch::Generators::GeneratorWrapper< T >::next(), and Catch::throw_exception().
Member Function Documentation
get()
template<typename T > std::vector< T > const & Catch::Generators::ChunkGenerator< T >::get () const inline override virtual
Implements Catch::Generators::IGenerator< std::vector< T > >.
Definition at line 4317 of file catch.hpp.
{
            return m_chunk;
        }
next()
template<typename T > bool Catch::Generators::ChunkGenerator< T >::next () inline override virtual
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 4320 of file catch.hpp.
{
            m_chunk.clear();
            for (size_t idx = 0; idx < m_chunk_size; ++idx) {
                if (!m_generator.next()) {
                    return false;
                }
                m_chunk.push_back(m_generator.get());
            }
            return true;
        }
References Catch::Generators::GeneratorWrapper< T >::get(), and Catch::Generators::GeneratorWrapper< T >::next().
Member Data Documentation
m_chunk
template<typename T > std::vector<T> Catch::Generators::ChunkGenerator< T >::m_chunk private
Definition at line 4298 of file catch.hpp.
m_chunk_size
template<typename T > size_t Catch::Generators::ChunkGenerator< T >::m_chunk_size private
Definition at line 4299 of file catch.hpp.
m_generator
template<typename T > GeneratorWrapper<T> Catch::Generators::ChunkGenerator< T >::m_generator private
Definition at line 4300 of file catch.hpp.
m_used_up
template<typename T > bool Catch::Generators::ChunkGenerator< T >::m_used_up = false private
Definition at line 4301 of file catch.hpp.
The documentation for this class was generated from the following file:
catch.hpp