ACA: Catch::Generators::FilterGenerator< T, Predicate > Class Template Reference
Catch::Generators::FilterGenerator< T, Predicate > Class Template Reference
#include <catch.hpp>
Public Member Functions
template<typename P = Predicate>
FilterGenerator (P &&pred, GeneratorWrapper< T > &&generator)
T const & get () const override
bool next () override
Public Member Functions inherited from Catch::Generators::IGenerator< T >
virtual ~IGenerator ()=default
virtual T const & get () const =0
Public Member Functions inherited from Catch::Generators::GeneratorUntypedBase
GeneratorUntypedBase ()=default
virtual ~GeneratorUntypedBase ()
virtual bool next ()=0
Private Member Functions
bool nextImpl ()
Private Attributes
GeneratorWrapper< T > m_generator
Predicate m_predicate
Additional Inherited Members
Public Types inherited from Catch::Generators::IGenerator< T >
using type = T
Detailed Description
template<typename T, typename Predicate>
class Catch::Generators::FilterGenerator< T, Predicate >
Definition at line 4156 of file catch.hpp.
Constructor & Destructor Documentation
FilterGenerator()
template<typename T , typename Predicate > template<typename P = Predicate> Catch::Generators::FilterGenerator< T, Predicate >::FilterGenerator (P && pred, GeneratorWrapper< T > && generator) inline
Definition at line 4161 of file catch.hpp.
                                                                  :
            m_generator(std::move(generator)),
            m_predicate(std::forward<P>(pred))
        {
            if (!m_predicate(m_generator.get())) {
                // It might happen that there are no values that pass the
                // filter. In that case we throw an exception.
                auto has_initial_value = nextImpl();
                if (!has_initial_value) {
                    Catch::throw_exception(GeneratorException("No valid value found in filtered generator"));
                }
            }
        }
References Catch::Generators::GeneratorWrapper< T >::get(), and Catch::throw_exception().
Member Function Documentation
get()
template<typename T , typename Predicate > T const & Catch::Generators::FilterGenerator< T, Predicate >::get () const inline override virtual
Implements Catch::Generators::IGenerator< T >.
Definition at line 4175 of file catch.hpp.
{
            return m_generator.get();
        }
References Catch::Generators::GeneratorWrapper< T >::get().
next()
template<typename T , typename Predicate > bool Catch::Generators::FilterGenerator< T, Predicate >::next () inline override virtual
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 4179 of file catch.hpp.
{
            return nextImpl();
        }
nextImpl()
template<typename T , typename Predicate > bool Catch::Generators::FilterGenerator< T, Predicate >::nextImpl () inline private
Definition at line 4184 of file catch.hpp.
{
            bool success = m_generator.next();
            if (!success) {
                return false;
            }
            while (!m_predicate(m_generator.get()) && (success = m_generator.next()) == true);
            return success;
        }
References Catch::Generators::GeneratorWrapper< T >::get(), and Catch::Generators::GeneratorWrapper< T >::next().
Member Data Documentation
m_generator
template<typename T , typename Predicate > GeneratorWrapper<T> Catch::Generators::FilterGenerator< T, Predicate >::m_generator private
Definition at line 4157 of file catch.hpp.
m_predicate
template<typename T , typename Predicate > Predicate Catch::Generators::FilterGenerator< T, Predicate >::m_predicate private
Definition at line 4158 of file catch.hpp.
The documentation for this class was generated from the following file:
catch.hpp