ACA: CFeatureSpectralMfccs Class Reference
CFeatureSpectralMfccs Class Reference
Public Member Functions
CFeatureSpectralMfccs (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureSpectralMfccs ()
Error_t compFeature (float *pfFeature, const float *pfInput) override
int getFeatureDimensions () const override
bool hasAdditionalParam () const override
Error_t setAdditionalParam (float fParamValue) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfInput)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Member Functions
CFeatureSpectralMfccs ()
CFeatureSpectralMfccs (const CFeatureSpectralMfccs &that)
disallow copy construction
CFeatureSpectralMfccs & operator= (const CFeatureSpectralMfccs &c)
void genMfccFilters_ ()
void genDctMat_ (int iNumCoeffs)
void allocDctMat_ (int iNumCoeffs)
void deleteDctMat_ ()
Private Attributes
const int m_iNumBands = 40
int m_iNumMfcCoeffs = 13
float ** m_ppfH = 0
float ** m_ppfDct = 0
float * m_pfMelSpec = 0
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume it's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
Definition at line 357 of file FeatureFromBlock.cpp.
Constructor & Destructor Documentation
CFeatureSpectralMfccs() [1/3]
CFeatureSpectralMfccs::CFeatureSpectralMfccs (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 360 of file FeatureFromBlock.cpp.
                                                                                               : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        // alloc transfer function memory
        m_ppfH = new float* [m_iNumBands];
        for (auto p = 0; p < m_iNumBands; p++)
        {
            m_ppfH[p] = new float[iDataLength];
            CVectorFloat::setZero(m_ppfH[p], iDataLength);
        }
        genMfccFilters_();
        genDctMat_(m_iNumMfcCoeffs);
        m_pfMelSpec = new float [m_iNumBands];
    }
References genDctMat_(), genMfccFilters_(), m_iNumBands, m_iNumMfcCoeffs, m_pfMelSpec, m_ppfH, and CVectorFloat::setZero().
~CFeatureSpectralMfccs()
virtual CFeatureSpectralMfccs::~CFeatureSpectralMfccs () inline virtual
Definition at line 375 of file FeatureFromBlock.cpp.
    {
        for (auto p = 0; p < m_iNumBands; p++)
            delete[] m_ppfH[p];
        delete[] m_ppfH;
        m_ppfH = 0;
        deleteDctMat_();
        delete [] m_pfMelSpec;
        m_pfMelSpec = 0;
    }
References deleteDctMat_(), m_iNumBands, m_pfMelSpec, and m_ppfH.
CFeatureSpectralMfccs() [2/3]
CFeatureSpectralMfccs::CFeatureSpectralMfccs () inline private
Definition at line 427 of file FeatureFromBlock.cpp.
{};
CFeatureSpectralMfccs() [3/3]
CFeatureSpectralMfccs::CFeatureSpectralMfccs (const CFeatureSpectralMfccs & that) private
disallow copy construction
Member Function Documentation
allocDctMat_()
void CFeatureSpectralMfccs::allocDctMat_ (int iNumCoeffs) inline private
Definition at line 495 of file FeatureFromBlock.cpp.
    {
        if (m_ppfDct)
            deleteDctMat_();
        m_ppfDct = new float* [iNumCoeffs];
        for (auto c = 0; c < iNumCoeffs; c++)
        {
            m_ppfDct[c] = new float[m_iNumBands];
            CVectorFloat::setZero(m_ppfDct[c], m_iNumBands);
        }
    }
References deleteDctMat_(), m_iNumBands, m_ppfDct, and CVectorFloat::setZero().
Referenced by genDctMat_().
compFeature()
Error_t CFeatureSpectralMfccs::compFeature (float * pfFeature, const float * pfInput) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfInput input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 388 of file FeatureFromBlock.cpp.
    {
        assert(pfFeature);
        assert(pfInput);
        CVectorFloat::setZero(pfFeature, m_iNumMfcCoeffs);
        // compute mel spectrum
        for (auto c = 0; c < m_iNumBands; c++)
            m_pfMelSpec[c] = std::log10(CVectorFloat::mulScalar(m_ppfH[c], pfInput, m_iDataLength) + 1e-20F);
        // compute dct
        for (auto j = 0; j < m_iNumMfcCoeffs; j++)
            pfFeature[j] = CVectorFloat::mulScalar(m_ppfDct[j], m_pfMelSpec, m_iNumBands);
         return Error_t::kNoError;
    };
References kNoError, CFeatureFromBlockIf::m_iDataLength, m_iNumBands, m_iNumMfcCoeffs, m_pfMelSpec, m_ppfDct, m_ppfH, CVectorFloat::mulScalar(), and CVectorFloat::setZero().
deleteDctMat_()
void CFeatureSpectralMfccs::deleteDctMat_ () inline private
Definition at line 507 of file FeatureFromBlock.cpp.
    {
        for (auto c = 0; c < m_iNumMfcCoeffs; c++)
            delete[] m_ppfDct[c];
        delete[] m_ppfDct;
        m_ppfDct = 0;
    }
References m_iNumMfcCoeffs, and m_ppfDct.
Referenced by allocDctMat_(), and ~CFeatureSpectralMfccs().
genDctMat_()
void CFeatureSpectralMfccs::genDctMat_ (int iNumCoeffs) inline private
Definition at line 480 of file FeatureFromBlock.cpp.
    {
        allocDctMat_(iNumCoeffs);
        for (auto c = 0; c < iNumCoeffs; c++)
        {
            for (auto b = 0; b < m_iNumBands; b++)
                m_ppfDct[c][b] = static_cast<float>(std::cos(c * (2 * b + 1) * M_PI / 2. / m_iNumBands));
            CVectorFloat::mulC_I(m_ppfDct[c], 1/std::sqrt(m_iNumBands / 2.F), m_iNumBands);
        }
        CVectorFloat::mulC_I(m_ppfDct[0], 1.F / std::sqrt(2.f), m_iNumBands);
        m_iNumMfcCoeffs = iNumCoeffs;
    }
References allocDctMat_(), m_iNumBands, m_iNumMfcCoeffs, m_ppfDct, and CVectorFloat::mulC_I().
Referenced by CFeatureSpectralMfccs(), and setAdditionalParam().
genMfccFilters_()
void CFeatureSpectralMfccs::genMfccFilters_ () inline private
< Check me
Definition at line 431 of file FeatureFromBlock.cpp.
    {
        const double dFreq = 400. / 3.;
        const int iNumLinFilters = 13;
        const double dLinSpacing = 200. / 3.,
            dLogSpacing = 1.0711703; // note sure where this mel resolution comes from exactly
        assert(m_iNumBands > iNumLinFilters);
        double adBoundFreqs[3] = { dFreq,
            dFreq + dLinSpacing,
            dFreq + 2. * dLinSpacing};
        int aiBoundIdx[3] = { static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[0]), (m_iDataLength - 1) * 2, m_fSampleRate)),
            static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[1]), (m_iDataLength - 1) * 2, m_fSampleRate)),
            static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[2]), (m_iDataLength - 1) * 2, m_fSampleRate))};
        for (auto c = 0; c < m_iNumBands; c++)
        {
            double dFilterAmp = 2. / (adBoundFreqs[2] - adBoundFreqs[0]);
            // upward slope
            for (auto k = aiBoundIdx[0]; k <= aiBoundIdx[1]; k++)
            {
                float fFreqk = CConversion::convertBin2Freq(1.F * k, (m_iDataLength - 1) * 2, m_fSampleRate);
                if ((fFreqk - adBoundFreqs[0]) <= 0.F)
                    continue;
                m_ppfH[c][k] = static_cast<float>(dFilterAmp * (fFreqk - adBoundFreqs[0]) / (adBoundFreqs[1] - adBoundFreqs[0]));
                assert(m_ppfH[c][k] >= 0);
            }
            // downward slope
            for (auto k = aiBoundIdx[1]+1; k <= aiBoundIdx[2]; k++)
            {
                float fFreqk = CConversion::convertBin2Freq(1.F * k, (m_iDataLength - 1) * 2, m_fSampleRate);
                //if ((afBoundFreqs[2] - fFreqk) < 0.F)
                //    continue;
                m_ppfH[c][k] = static_cast<float>(dFilterAmp * (adBoundFreqs[2] - fFreqk) / (adBoundFreqs[2] - adBoundFreqs[1]));
                assert(m_ppfH[c][k] >= 0);
            }
            // proceed to next band
            adBoundFreqs[0] = adBoundFreqs[1];
            adBoundFreqs[1] = adBoundFreqs[2];
            adBoundFreqs[2] = (c < iNumLinFilters-3) ? adBoundFreqs[1] + dLinSpacing : adBoundFreqs[2] * dLogSpacing; //!< Check me
            aiBoundIdx[0] = aiBoundIdx[1];
            aiBoundIdx[1] = aiBoundIdx[2];
            aiBoundIdx[2] = static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[2]), (m_iDataLength - 1) * 2, m_fSampleRate));
        }
    }
References CConversion::convertBin2Freq(), CConversion::convertFreq2Bin(), CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, m_iNumBands, and m_ppfH.
Referenced by CFeatureSpectralMfccs().
getFeatureDimensions()
int CFeatureSpectralMfccs::getFeatureDimensions () const inline override virtual
returns size of output feature (1 in most cases)
Returns
int
Reimplemented from CFeatureFromBlockIf.
Definition at line 407 of file FeatureFromBlock.cpp.
    {
        return m_iNumMfcCoeffs;
    }
References m_iNumMfcCoeffs.
hasAdditionalParam()
bool CFeatureSpectralMfccs::hasAdditionalParam () const inline override virtual
returns true if there is an additional parameter
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 412 of file FeatureFromBlock.cpp.
    {
        return true;
    }
operator=()
CFeatureSpectralMfccs & CFeatureSpectralMfccs::operator= (const CFeatureSpectralMfccs & c) private
setAdditionalParam()
Error_t CFeatureSpectralMfccs::setAdditionalParam (float fParamValue) inline override virtual
returns true if there is an additional parameter
Parameters
fParamValue new parameter value
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 417 of file FeatureFromBlock.cpp.
    {
        if (fParamValue <= 0)
            return Error_t::kFunctionInvalidArgsError;
        genDctMat_(CUtil::float2int<int>(fParamValue));
        return Error_t::kNoError;
    }
References genDctMat_(), kFunctionInvalidArgsError, and kNoError.
Member Data Documentation
m_iNumBands
const int CFeatureSpectralMfccs::m_iNumBands = 40 private
Definition at line 515 of file FeatureFromBlock.cpp.
Referenced by allocDctMat_(), CFeatureSpectralMfccs(), compFeature(), genDctMat_(), genMfccFilters_(), and ~CFeatureSpectralMfccs().
m_iNumMfcCoeffs
int CFeatureSpectralMfccs::m_iNumMfcCoeffs = 13 private
Definition at line 516 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralMfccs(), compFeature(), deleteDctMat_(), genDctMat_(), and getFeatureDimensions().
m_pfMelSpec
float* CFeatureSpectralMfccs::m_pfMelSpec = 0 private
Definition at line 521 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralMfccs(), compFeature(), and ~CFeatureSpectralMfccs().
m_ppfDct
float ** CFeatureSpectralMfccs::m_ppfDct = 0 private
Definition at line 519 of file FeatureFromBlock.cpp.
Referenced by allocDctMat_(), compFeature(), deleteDctMat_(), and genDctMat_().
m_ppfH
float** CFeatureSpectralMfccs::m_ppfH = 0 private
Definition at line 518 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralMfccs(), compFeature(), genMfccFilters_(), and ~CFeatureSpectralMfccs().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp