ACA: CFeatureFromFile Class Reference
CFeatureFromFile Class Reference
Public Member Functions
CFeatureFromFile (Feature_t eFeatureIdx, std::string strAudioFilePath, int iBlockLength, int iHopLength)
virtual ~CFeatureFromFile ()
Public Member Functions inherited from CFeatureIf
Error_t getFeatureDimensions (int &iNumRows, int &iNumCols) const
Error_t getFeatureTimeStamps (float *pfAxisTicks) const
Error_t compFeature1Dim (float *pfFeature)
Error_t compFeatureNDim (float **ppfFeature)
Private Attributes
CAudioFileIf * m_pCAudioFile
Additional Inherited Members
Public Types inherited from CFeatureIf
enum Feature_t {
kFeatureSpectralCentroid , kFeatureSpectralCrestFactor , kFeatureSpectralDecrease , kFeatureSpectralFlatness ,
kFeatureSpectralFlux , kFeatureSpectralKurtosis , kFeatureSpectralMfccs , kFeatureSpectralPitchChroma ,
kFeatureSpectralRolloff , kFeatureSpectralSkewness , kFeatureSpectralSlope , kFeatureSpectralSpread ,
kFeatureSpectralTonalPowerRatio , kFeatureTimeAcfCoeff , kFeatureTimeMaxAcf , kFeatureTimePeakEnvelope ,
kFeatureTimeRms , kFeatureTimeStd , kFeatureTimeZeroCrossingRate , kNumFeatures
}
enum to index all features note: update CFeatureIf::isFeatureSpectral_() when modifying
Static Public Member Functions inherited from CFeatureIf
static Error_t create (CFeatureIf *&pCInstance, Feature_t eFeatureIdx, const std::string &strAudioFilePath, int iBlockLength=2048, int iHopLength=1024)
static Error_t create (CFeatureIf *&pCInstance, Feature_t eFeatureIdx, const float *pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength=2048, int iHopLength=1024)
static Error_t destroy (CFeatureIf *&pCInstance)
static std::string getFeatureString (Feature_t eFeatureIdx)
static Feature_t getFeatureIdxFromString (std::string sFeatureString)
Protected Member Functions inherited from CFeatureIf
CFeatureIf ()
virtual ~CFeatureIf ()
CFeatureIf (const CFeatureIf &that)
CFeatureIf & operator= (const CFeatureIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (Feature_t eFeatureIdx)
init configuration
bool isFeatureSpectral_ (Feature_t eFeatureIdx)
void computeMagSpectrum_ ()
Protected Attributes inherited from CFeatureIf
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CFeatureFromBlockIf * m_pCFeature = 0
CFft * m_pCFft = 0
fft instance
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcessBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcessBuff1 = 0
temporary buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
Definition at line 14 of file Feature.cpp.
Constructor & Destructor Documentation
CFeatureFromFile()
CFeatureFromFile::CFeatureFromFile (Feature_t eFeatureIdx, std::string strAudioFilePath, int iBlockLength, int iHopLength)
Definition at line 35 of file Feature.cpp.
                                                                                                                      :
    m_pCAudioFile(0)
{
    this->reset_();
    CAudioFileIf::FileSpec_t stFileSpec;
    CAudioFileIf::create(m_pCAudioFile);
    m_pCAudioFile->openFile(strAudioFilePath, CAudioFileIf::kFileRead);
    m_pCAudioFile->getFileSpec(stFileSpec);
    m_fSampleRate = stFileSpec.fSampleRateInHz;
    CBlockAudioIf::create(m_pCBlockAudio, m_pCAudioFile, iBlockLength, iHopLength);
    m_pCNormalize = new CNormalizeAudio(m_pCAudioFile);
    // set length variables
    m_iBlockLength = iBlockLength;
    m_iHopLength = iHopLength;
    init_(eFeatureIdx);
}
References CAudioFileIf::create(), CBlockAudioIf::create(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CAudioFileIf::getFileSpec(), CFeatureIf::init_(), CAudioFileIf::kFileRead, CFeatureIf::m_fSampleRate, CFeatureIf::m_iBlockLength, CFeatureIf::m_iHopLength, m_pCAudioFile, CFeatureIf::m_pCBlockAudio, CFeatureIf::m_pCNormalize, CAudioFileIf::openFile(), and CFeatureIf::reset_().
~CFeatureFromFile()
virtual CFeatureFromFile::~CFeatureFromFile () inline virtual
Definition at line 19 of file Feature.cpp.
    {
        delete m_pCNormalize;
        m_pCNormalize = 0;
        delete[] m_pfProcessBuff1;
        m_pfProcessBuff1 = 0;
        m_pCAudioFile->closeFile();
        CAudioFileIf::destroy(m_pCAudioFile);
    };
References CAudioFileIf::closeFile(), CAudioFileIf::destroy(), m_pCAudioFile, CFeatureIf::m_pCNormalize, and CFeatureIf::m_pfProcessBuff1.
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CFeatureFromFile::m_pCAudioFile private
Definition at line 32 of file Feature.cpp.
Referenced by CFeatureFromFile(), and ~CFeatureFromFile().
The documentation for this class was generated from the following file:
Feature.cpp