ACA: CFeatureSpectralFlux Class Reference
CFeatureSpectralFlux Class Reference
Public Member Functions
CFeatureSpectralFlux (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureSpectralFlux ()
Error_t compFeature (float *pfFeature, const float *pfInput) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfInput)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Member Functions
CFeatureSpectralFlux ()
CFeatureSpectralFlux (const CFeatureSpectralFlux &that)
disallow copy construction
CFeatureSpectralFlux & operator= (const CFeatureSpectralFlux &c)
Private Attributes
float * m_pfPrevSpec = 0
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume it's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
Definition at line 325 of file FeatureFromBlock.cpp.
Constructor & Destructor Documentation
CFeatureSpectralFlux() [1/3]
CFeatureSpectralFlux::CFeatureSpectralFlux (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 328 of file FeatureFromBlock.cpp.
                                                                                              : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        m_pfPrevSpec = new float[m_iDataLength];
        CVectorFloat::setZero(m_pfPrevSpec, m_iDataLength);
    };
References CFeatureFromBlockIf::m_iDataLength, m_pfPrevSpec, and CVectorFloat::setZero().
~CFeatureSpectralFlux()
virtual CFeatureSpectralFlux::~CFeatureSpectralFlux () inline virtual
Definition at line 334 of file FeatureFromBlock.cpp.
    {
        delete[] m_pfPrevSpec;
        m_pfPrevSpec = 0;
    };
References m_pfPrevSpec.
CFeatureSpectralFlux() [2/3]
CFeatureSpectralFlux::CFeatureSpectralFlux () inline private
Definition at line 350 of file FeatureFromBlock.cpp.
{};
CFeatureSpectralFlux() [3/3]
CFeatureSpectralFlux::CFeatureSpectralFlux (const CFeatureSpectralFlux & that) private
disallow copy construction
Member Function Documentation
compFeature()
Error_t CFeatureSpectralFlux::compFeature (float * pfFeature, const float * pfInput) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfInput input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 340 of file FeatureFromBlock.cpp.
    {
        *pfFeature = compFeatureSpectralFlux(pfInput, m_pfPrevSpec, m_iDataLength, m_fSampleRate);
        CVectorFloat::copy(m_pfPrevSpec, pfInput, m_iDataLength);
        return Error_t::kNoError;
    };
References CFeatureFromBlockIf::compFeatureSpectralFlux(), CVectorFloat::copy(), kNoError, CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, and m_pfPrevSpec.
operator=()
CFeatureSpectralFlux & CFeatureSpectralFlux::operator= (const CFeatureSpectralFlux & c) private
Member Data Documentation
m_pfPrevSpec
float* CFeatureSpectralFlux::m_pfPrevSpec = 0 private
Definition at line 354 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralFlux(), compFeature(), and ~CFeatureSpectralFlux().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp