ACA: CVector Class Reference
CVector Class Reference
class with static functions for buffer operations with type T
#include <Vector.h>
Static Public Member Functions
template<typename T >
static void setZero (T *ptSrcDest, long long iLength)
template<typename T >
static void setValue (T *ptDest, T tValue, long long iLength)
template<typename T >
static void setZeroBelowThresh (T *ptSrcDest, long long int iLength, T Thresh)
template<typename T >
static void copy (T *ptDest, const T *pSource, long long int iLength)
template<typename T >
static void flip_I (T *ptSrcDest, long long int iLength)
template<typename T >
static void moveInMem (T *ptSrcDest, int iDestIdx, int iSrcIdx, long long int iLength)
Detailed Description
class with static functions for buffer operations with type T
Definition at line 12 of file Vector.h.
Member Function Documentation
copy()
template<typename T > static void CVector::copy (T * ptDest, const T * pSource, long long int iLength) inline static
copies buffer of type T
Parameters
ptDest pointer to destination memory
pSource pointer to source memory
iLength length of buffer
Returns
void
Definition at line 69 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptDest);
            assert(pSource);
            memcpy(ptDest, pSource, sizeof(T)*iLength);
        }
    }
Referenced by CVectorFloat::copy(), CFilter< T >::init(), and CAudioFileSndLib::openFile().
flip_I()
template<typename T > static void CVector::flip_I (T * ptSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
ptSrcDest pointer to memory to be flipped
iLength number of elements
Returns
void
Definition at line 86 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptSrcDest);
            auto iLoopLength = iLength / 2; // integer division!
            for (auto i = 0; i < iLoopLength; i++)
            {
                T Tmp = ptSrcDest[i];
                ptSrcDest[i] = ptSrcDest[iLength - 1 - i];
                ptSrcDest[iLength - 1 - i] = Tmp;
            }
        }
    }
Referenced by CBeatHistoIf::compBeatHisto(), and CVectorFloat::flip_I().
moveInMem()
template<typename T > static void CVector::moveInMem (T * ptSrcDest, int iDestIdx, int iSrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
ptSrcDest source and destination
iDestIdx destination index
iSrcIdx source index
iLength number of elements to be moved
Returns
void
Definition at line 111 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        if (iLength > 0)
            memmove (&ptSrcDest[iDestIdx], &ptSrcDest[iSrcIdx], sizeof(T)*iLength);
    }
Referenced by CVectorFloat::moveInMem().
setValue()
template<typename T > static void CVector::setValue (T * ptDest, T tValue, long long iLength) inline static
initializes the buffer to a specific value
Parameters
ptDest pointer to memory to be initialized
tValue value to use
iLength number of elements to be set
Returns
void
Definition at line 37 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptDest);
        for (auto i = 0; i < iLength; i++)
            ptDest[i] = tValue;
    }
Referenced by CNoveltyIf::compNovelty(), and CVectorFloat::findPeaks().
setZero()
template<typename T > static void CVector::setZero (T * ptSrcDest, long long iLength) inline static
sets a buffer to zero
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
Returns
void
Definition at line 21 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        if (iLength > 0)
            memset (ptSrcDest, 0, sizeof(T)*iLength);
    }
Referenced by CDtw::CDtw(), CFilter< T >::init(), and CVectorFloat::setZero().
setZeroBelowThresh()
template<typename T > static void CVector::setZeroBelowThresh (T * ptSrcDest, long long int iLength, T Thresh) inline static
sets all values smaller than a threshold to 0
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
Thresh threshold value
Returns
void
Definition at line 53 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (ptSrcDest);
        for (auto i = 0; i < iLength; i++)
            if (ptSrcDest[i] < Thresh)
                ptSrcDest[i] = 0;
    }
Referenced by CVectorFloat::setZeroBelowThresh().
The documentation for this class was generated from the following file:
Vector.h