ACA: CMatrix Class Reference
CMatrix Class Reference
class with static functions for matrix operations with type float (functionality only added when needed)
#include <Matrix.h>
Static Public Member Functions
static void alloc (float **&ppfMat, int iNumRows, int iNumCols)
static void free (float **&ppfMat, int iNumRows)
static void mulMatColVec (float *pfDestColVec, float **ppfMatrix, const float *pfSrcColVec, int iNumMatRows, int iNumMatCols)
static void mulRowVecMat (float *pfDestColVec, const float *pfSrcRowVec, float **ppfMatrix, int iNumMatRows, int iNumMatCols)
static void setEye (float **ppfDest, int iNumRows, int iNumCols)
static void swapRowCol (float **ppfSrcDest, int iRowIdx, int iColIdx, int iNumRows, int iNumCols)
static void copy (float **ppfDest, float **ppfSrc, int iNumRows, int iNumCols)
static void inv_I (float **ppfSrcDest, int iNumRows, int iNumCols)
Detailed Description
class with static functions for matrix operations with type float (functionality only added when needed)
Definition at line 10 of file Matrix.h.
Member Function Documentation
alloc()
static void CMatrix::alloc (float **& ppfMat, int iNumRows, int iNumCols) inline static
Definition at line 14 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        ppfMat = new float* [iNumRows];
        assert(ppfMat);
        for (auto m = 0; m < iNumRows; m++)
        {
            ppfMat[m] = new float[iNumCols];
            assert(ppfMat[m]);
            CVectorFloat::setZero(ppfMat[m], iNumCols);
        }
    }
References CVectorFloat::setZero().
Referenced by inv_I().
copy()
static void CMatrix::copy (float ** ppfDest, float ** ppfSrc, int iNumRows, int iNumCols) inline static
Definition at line 104 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfSrc);
        assert(ppfSrc[0]);
        assert(ppfDest);
        assert(ppfDest[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVectorFloat::copy(ppfDest[m], ppfSrc[m], iNumCols);
    }
References CVectorFloat::copy().
Referenced by inv_I().
free()
static void CMatrix::free (float **& ppfMat, int iNumRows) inline static
Definition at line 31 of file Matrix.h.
    {
        assert(iNumRows > 0);
        if (!ppfMat) return;
        for (auto m = 0; m < iNumRows; m++)
            delete[] ppfMat[m];
        delete[] ppfMat;
        ppfMat = 0;
    }
inv_I()
static void CMatrix::inv_I (float ** ppfSrcDest, int iNumRows, int iNumCols) inline static
Definition at line 117 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        const float kSingularityThresh = 1e-15F;
        float** ppfTmp = 0;
        float** ppfEye = 0;
        int    i, j;
        double dDet = 1;
        alloc(ppfTmp, iNumRows, iNumCols);
        copy(ppfTmp, ppfSrcDest, iNumRows, iNumCols);
        alloc(ppfEye, iNumRows, iNumCols);
        setEye(ppfEye, iNumRows, iNumCols);
        if (ppfSrcDest[0][0] == 0)
        {
            i = 1;
            while (i < iNumRows)
            {
                if (ppfSrcDest[i][0] != 0)
                {
                    swapRowCol(ppfSrcDest, 0, i, iNumRows, iNumCols);
                    swapRowCol(ppfEye, 0, i, iNumRows, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        dDet *= ppfSrcDest[0][0];
        CVectorFloat::mulC_I(ppfEye[0], 1.F / ppfSrcDest[0][0], iNumCols);
        CVectorFloat::mulC_I(ppfSrcDest[0], 1.F / ppfSrcDest[0][0], iNumCols);
        for (i = 1; i < iNumRows; i++)
        {
            j = 0;
            if (dDet < kSingularityThresh * kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVectorFloat::subW_I(ppfEye[i], ppfEye[j], ppfSrcDest[i][j], iNumCols);
                CVectorFloat::subW_I(ppfSrcDest[i], ppfSrcDest[j], ppfSrcDest[i][j], iNumCols);
                j++;
            }
            if (ppfSrcDest[i][i] != 0)
            {
                dDet *= ppfSrcDest[i][i];
                CVectorFloat::mulC_I(ppfEye[i], 1.F / ppfSrcDest[i][i], iNumCols);
                CVectorFloat::mulC_I(ppfSrcDest[i], 1.F / ppfSrcDest[i][i], iNumCols);
            }
            if (ppfSrcDest[i][i] == 0)
            {
                for (int j1 = i + 1; j1 < iNumCols; j1++)
                {
                    if (ppfSrcDest[i][j1] != 0)         // Column pivotting not supported
                    {
                        for (int i1 = 0; i1 < iNumRows; i1++)
{
                            for (j = 0; j < iNumCols; j++)
                                ppfSrcDest[i1][j] = ppfTmp[i1][j];
                        }
                        inv_I(ppfTmp, iNumRows, iNumCols);
                        copy(ppfSrcDest, ppfTmp, iNumRows, iNumCols);
                        return;
                    }
                }
            }
        }
        for (i = iNumRows - 1; i > 0; i--)
        {
            for (j = i - 1; j >= 0; j--)
            {
                CVectorFloat::subW_I(ppfEye[j], ppfEye[i], ppfSrcDest[j][i], iNumCols);
                CVectorFloat::subW_I(ppfSrcDest[j], ppfSrcDest[i], ppfSrcDest[j][i], iNumCols);
            }
        }
        copy(ppfSrcDest, ppfEye, iNumRows, iNumCols);
    }
References alloc(), copy(), inv_I(), CVectorFloat::mulC_I(), setEye(), CVectorFloat::subW_I(), and swapRowCol().
Referenced by inv_I().
mulMatColVec()
static void CMatrix::mulMatColVec (float * pfDestColVec, float ** ppfMatrix, const float * pfSrcColVec, int iNumMatRows, int iNumMatCols) inline static
Definition at line 43 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(pfDestColVec);
        assert(pfSrcColVec);
        assert(ppfMatrix);
        assert(ppfMatrix[0]);
        for (auto m = 0; m < iNumMatRows; m++)
            pfDestColVec[m] = CVectorFloat::mulScalar(ppfMatrix[m], pfSrcColVec, iNumMatCols);
    }
References CVectorFloat::mulScalar().
mulRowVecMat()
static void CMatrix::mulRowVecMat (float * pfDestColVec, const float * pfSrcRowVec, float ** ppfMatrix, int iNumMatRows, int iNumMatCols) inline static
Definition at line 56 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(pfDestColVec);
        assert(pfSrcRowVec);
        assert(ppfMatrix);
        assert(ppfMatrix[0]);
        CVectorFloat::setZero(pfDestColVec, iNumMatCols);
        for (auto n = 0; n < iNumMatCols; n++)
            for (auto m = 0; m < iNumMatRows; m++)
                pfDestColVec[n] += pfSrcRowVec[m] * ppfMatrix[m][n];
    }
References CVectorFloat::setZero().
setEye()
static void CMatrix::setEye (float ** ppfDest, int iNumRows, int iNumCols) inline static
Definition at line 71 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(ppfDest);
        assert(ppfDest[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            CVectorFloat::setZero(ppfDest[m], iNumCols);
            ppfDest[m][m] = 1.F;
        }
    }
References CVectorFloat::setZero().
Referenced by inv_I().
swapRowCol()
static void CMatrix::swapRowCol (float ** ppfSrcDest, int iRowIdx, int iColIdx, int iNumRows, int iNumCols) inline static
Definition at line 86 of file Matrix.h.
    {
        assert(iRowIdx > 0);
        assert(iColIdx > 0);
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(ppfSrcDest);
        assert(ppfSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            float fTmp = ppfSrcDest[iRowIdx][n];
            //ppfSrcDest[iRowIdx][n] = ppfSrcDest[n][iColIdx];
            ppfSrcDest[iRowIdx][n] = ppfSrcDest[iColIdx][n];
            ppfSrcDest[iColIdx][n] = fTmp;
        }
    }
Referenced by inv_I().
The documentation for this class was generated from the following file:
Matrix.h