ACA: CVectorFloat Class Reference
CVectorFloat Class Reference
class with static functions for buffer operations with type float
#include <Vector.h>
Static Public Member Functions
static void alloc (float *&pfVec, long long iLength)
static void free (float *&pfVec)
static void setZero (float *pfSrcDest, long long int iLength)
static void setZeroBelowThresh (float *pfSrcDest, long long int iLength, float fThresh=0.F)
static void copy (float *pfDest, const float *pfSource, long long int iLength)
static void flip_I (float *pfSrcDest, long long int iLength)
static void moveInMem (float *pfSrcDest, int iDestIdx, int iSrcIdx, long long int iLength)
static void setValue (float *pfDest, float fValue, long long int iLength)
static void mulC_I (float *pfSrcDest, float fScale, long long int iLength)
static void mul_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static float mulScalar (const float *pfSrc1, const float *pfSrc2, long long int iLength)
static void div_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static void add_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static void addC_I (float *pfSrcDest, float fConst, long long int iLength)
static void sub_I (float *pfSrcDest, const float *pfSrc, long long int iLength)
static void subW_I (float *pfSrcDest, const float *pfSrc, float fWeight, long long int iLength)
static float getSum (const float *pfSrc, long long int iLength, bool bAbs=false)
static bool isEqual (const float *pfSrc1, const float *pfSrc2, long long int iLength)
static float getMean (const float *pfSrc, long long int iLength)
static float getStd (const float *pfSrc, long long int iLength, float fMean=std::numeric_limits< float >::max())
static float getRms (const float *pfSrc, long long int iLength)
static float getMax (const float *pfSrc, long long int iLength, bool bAbs=false)
static int findPeaks (bool *pbIsLocalMax, const float *pfSrc, long long int iLength, float fThresh=-std::numeric_limits< float >::max())
static float getMin (const float *pfSrc, long long int iLength, bool bAbs=false)
static void findMax (const float *pfSrc, float &fMax, long long &iMax, long long int iLength, bool bAbs=false)
static void findMin (const float *pfSrc, float &fMin, long long &iMin, long long int iLength, bool bAbs=false)
Detailed Description
class with static functions for buffer operations with type float
Definition at line 151 of file Vector.h.
Member Function Documentation
add_I()
static void CVectorFloat::add_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector addition
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be added
Returns
void
Definition at line 324 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        assert (pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] += pfSrc[i];
    }
Referenced by CBeatHistoIf::compBeatHisto(), CPreProc::downmix(), and CInstFreq::process().
addC_I()
static void CVectorFloat::addC_I (float * pfSrcDest, float fConst, long long int iLength) inline static
adds a buffer to a scalar
Parameters
pfSrcDest buffer to be added
fConst scalar
iLength number of element to be added
Returns
void
Definition at line 340 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] += fConst;
    }
Referenced by CNoveltyIf::compNovelty().
alloc()
static void CVectorFloat::alloc (float *& pfVec, long long iLength) inline static
allocates a float buffer and inits it with zeros
Parameters
pfVec (empty pointer, to be allocated)
iLength number of floats
Returns
Definition at line 160 of file Vector.h.
    {
        assert(iLength > 0);
        pfVec = new float[iLength];
        assert(pfVec);
        setZero(pfVec, iLength);
    }
References setZero().
Referenced by CButterLp::calcCoeffs(), CFilter< T >::filtfilt(), CResample::process(), and CFilter< T >::setInitState_().
copy()
static void CVectorFloat::copy (float * pfDest, const float * pfSource, long long int iLength) inline static
copies buffer of type float
Parameters
pfDest pointer to destination memory
pfSource pointer to source memory
iLength length of buffer
Returns
void
Definition at line 207 of file Vector.h.
    {
        CVector::copy(pfDest, pfSource, iLength);
    }
References CVector::copy().
Referenced by CButterLp::calcCoeffs(), CBlockAudioBuffer::CBlockAudioBuffer(), CBeatHistoIf::compBeatHisto(), CCcf::compCcf(), CFeatureSpectralFlux::compFeature(), CFft::compFft(), CFft::compInvFft(), CNoveltyFromBlockIf::compNovelty(), CMatrix::copy(), CPreProc::downmix(), CCcf::getCcf(), CSpectrogramIf::getMelSpectrogramAxisVectors(), CBlockAudioBuffer::getNextBlock(), CFft::getWindow(), CFft::mergeRealImag(), CFft::overrideWindow(), CInstFreq::process(), CGammatone::process(), and CFft::splitRealImag().
div_I()
static void CVectorFloat::div_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector division
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be divided
Returns
void
Definition at line 305 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        assert (pfSrc);
        for (auto i = 0; i < iLength; i++)
        {
            assert(pfSrc[i] != 0);
            pfSrcDest[i] /= pfSrc[i];
        }
    }
findMax()
static void CVectorFloat::findMax (const float * pfSrc, float & fMax, long long & iMax, long long int iLength, bool bAbs = false) inline static
finds the maximum (absolute) value in the buffer
Parameters
pfSrc input buffer
fMax resulting output value
iMax index of the resulting output value
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 565 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc);
        fMax    = -std::numeric_limits<float>::max();
        iMax    = -1;
        for (auto i = 0; i < iLength; i++)
        {
            float fCurr   = (bAbs)? std::abs(pfSrc[i]) : pfSrc[i];
            if (fCurr > fMax)
            {
                fMax = fCurr;
                iMax = i;
            }
        }
    }
Referenced by CCcf::getCcfMaxIdx(), and getMax().
findMin()
static void CVectorFloat::findMin (const float * pfSrc, float & fMin, long long & iMin, long long int iLength, bool bAbs = false) inline static
finds the minimum (absolute) value in the buffer
Parameters
pfSrc input buffer
fMin resulting output value
iMin index of the resulting output value
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 593 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc);
        fMin    = std::numeric_limits<float>::max();
        iMin    = -1;
        for (auto i = 0; i < iLength; i++)
        {
            float fCurr   = (bAbs)? std::abs(pfSrc[i]) : pfSrc[i];
            if (fCurr < fMin)
            {
                fMin    = fCurr;
                iMin    = i;
            }
        }
    }
Referenced by getMin().
findPeaks()
static int CVectorFloat::findPeaks (bool * pbIsLocalMax, const float * pfSrc, long long int iLength, float fThresh = -std::numeric_limits<float>::max()) inline static
finds the local maxima in the buffer
Parameters
pbIsLocalMax result buffer
pfSrc input buffer
iLength number of elements in buffer
fThresh only detect maxima above this threshold
Returns
int number of local maxima
Definition at line 513 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrc);
        assert(pbIsLocalMax);
        int iNumPeaks = 0;
        CVector::setValue(pbIsLocalMax, false, iLength);
        for (auto k = 1; k < iLength - 1; k++)
        {
            // search for local maxima
            if (pfSrc[k] <= pfSrc[k - 1] || pfSrc[k] <= pfSrc[k + 1] || pfSrc[k] <= fThresh)
                continue;
            else
            {
                pbIsLocalMax[k] = true;
                iNumPeaks++;
                // increment because the next bin cannot be a local max
                k++;
            }
        }
        return iNumPeaks;
    }
References CVector::setValue().
Referenced by CNoveltyIf::compNovelty().
flip_I()
static void CVectorFloat::flip_I (float * pfSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
pfSrcDest pointer to memory to be flipped
iLength number of elements
Returns
void
Definition at line 217 of file Vector.h.
    {
        CVector::flip_I(pfSrcDest, iLength);
    }
References CVector::flip_I().
free()
static void CVectorFloat::free (float *& pfVec) inline static
frees a float buffer and sets it to zero
Parameters
pfVec (empty pointer, to be allocated)
Returns
Definition at line 174 of file Vector.h.
    {
        delete[] pfVec;
        pfVec = 0;
    }
Referenced by CButterLp::calcCoeffs(), CFilter< T >::filtfilt(), CResample::process(), and CFilter< T >::setInitState_().
getMax()
static float CVectorFloat::getMax (const float * pfSrc, long long int iLength, bool bAbs = false) inline static
finds the maximum (absolute) value in the buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 496 of file Vector.h.
    {
        float fMax;
        long long iMax;
        findMax(pfSrc, fMax, iMax, iLength, bAbs);
        return fMax;
    }
References findMax().
Referenced by CNormalizeAudio::CNormalizeAudio(), CFeatureTimeMaxAcf::compFeature(), CFeatureFromBlockIf::compFeatureSpectralCrestFactor(), CFeatureFromBlockIf::compFeatureTimePeakEnvelope(), CNoveltyIf::compNovelty(), CCcf::getCcfMax(), and CNormalizeAudio::normalizeSignal().
getMean()
static float CVectorFloat::getMean (const float * pfSrc, long long int iLength) inline static
extracts the mean value
Parameters
pfSrc input buffer
iLength number of elements in buffer
Returns
float
Definition at line 420 of file Vector.h.
    {
        assert (iLength >= 0);
        float fMean = getSum(pfSrc, iLength);
        if (iLength > 0)
        {
            fMean  /= iLength;
        }
        return fMean;
    }
References getSum().
Referenced by CFeatureFromBlockIf::compFeatureSpectralFlatness(), CNoveltyIf::compNovelty(), and getStd().
getMin()
static float CVectorFloat::getMin (const float * pfSrc, long long int iLength, bool bAbs = false) inline static
finds the minimum (absolute) value in the buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
float
Definition at line 547 of file Vector.h.
    {
        float fMin;
        long long iMin;
        findMin(pfSrc, fMin, iMin, iLength, bAbs);
        return fMin;
    }
References findMin().
Referenced by CFeatureFromBlockIf::compFeatureSpectralFlatness().
getRms()
static float CVectorFloat::getRms (const float * pfSrc, long long int iLength) inline static
extracts the root mean square from a buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
Returns
float
Definition at line 470 of file Vector.h.
    {
        assert (iLength >= 0);
        float fRms = 0;
        for (auto i=0; i < iLength; i++)
        {
            fRms   += pfSrc[i] * pfSrc[i];
        }
        if (iLength > 0)
        {
            fRms   /= iLength;
        }
        return std::sqrt(fRms);
    }
getStd()
static float CVectorFloat::getStd (const float * pfSrc, long long int iLength, float fMean = std::numeric_limits<float>::max()) inline static
extracts the standard deviation (biased) from a buffer
Parameters
pfSrc input buffer
iLength number of elements in buffer
fMean mean value if it has already been computed, otherwise it will be extracted in function
Returns
float
Definition at line 440 of file Vector.h.
    {
        assert (iLength >= 0);
        float  fStd = 0;
        if (fMean == std::numeric_limits<float>::max())
        {
            fMean   = getMean(pfSrc, iLength);
        }
        for (auto i=0; i < iLength; i++)
        {
            fStd   += (pfSrc[i] - fMean) * (pfSrc[i] - fMean);
        }
        if (iLength > 1)
        {
            //dStd   /= (iLength - 1);
            fStd   /= iLength;
        }
        return std::sqrt(fStd);
    }
References getMean().
Referenced by CFeatureFromBlockIf::compFeatureTimeRms(), and CFeatureFromBlockIf::compFeatureTimeStd().
getSum()
static float CVectorFloat::getSum (const float * pfSrc, long long int iLength, bool bAbs = false) inline static
computes the sum of a vector
Parameters
pfSrc vector
iLength length of vector
bAbs specifies whether it is the sum of absolute values or not
Returns
float
Definition at line 381 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc);
        float fResult = 0;
        if (bAbs)
        {
            for (auto i = 0; i < iLength; i++)
                fResult += std::abs(pfSrc[i]);
        }
        else
        {
            for (auto i = 0; i < iLength; i++)
                fResult += pfSrc[i];
        }
        return fResult;
    }
Referenced by CFeatureSpectralPitchChroma::compFeature(), CFeatureFromBlockIf::compFeatureSpectralCrestFactor(), CFeatureFromBlockIf::compFeatureSpectralRolloff(), and getMean().
isEqual()
static bool CVectorFloat::isEqual (const float * pfSrc1, const float * pfSrc2, long long int iLength) inline static
checks to buffer for equality (no floating point tolerance)
Parameters
pfSrc1 buffer 1
pfSrc2 buffer 2
iLength number of dimensions
Returns
bool
Definition at line 406 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc1);
        assert (pfSrc2);
        return (memcmp (pfSrc1, pfSrc2, iLength * sizeof(float)) == 0);
    }
moveInMem()
static void CVectorFloat::moveInMem (float * pfSrcDest, int iDestIdx, int iSrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
pfSrcDest source and destination
iDestIdx destination index
iSrcIdx source index
iLength number of elements to be moved
Returns
void
Definition at line 229 of file Vector.h.
    {
        CVector::moveInMem(pfSrcDest, iDestIdx, iSrcIdx, iLength);
    }
References CVector::moveInMem().
mul_I()
static void CVectorFloat::mul_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector multiplication
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be multiplied
Returns
void
Definition at line 270 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        assert (pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] *= pfSrc[i];
    }
Referenced by CFft::compFft(), and CFft::compInvFft().
mulC_I()
static void CVectorFloat::mulC_I (float * pfSrcDest, float fScale, long long int iLength) inline static
multiplies a buffer with a scalar
Parameters
pfSrcDest buffer to be multiplied
fScale scalar
iLength number of element to be multiplied
Returns
void
Definition at line 255 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] *= fScale;
    }
Referenced by CGammatone::calcFilterCoeffs_(), CCcf::compCcf(), CFeatureSpectralPitchChroma::compFeature(), CNoveltyIf::compNovelty(), CFeatureIf::computeMagSpectrum_(), CNoveltyIf::computeMagSpectrum_(), CSpectrogramIf::computeMagSpectrum_(), CFft::conjugate_I(), CPreProc::downmix(), CFeatureSpectralMfccs::genDctMat_(), CMatrix::inv_I(), CNormalizeAudio::normalizeBlock(), CNormalizeAudio::normalizeSignal(), and CInstFreq::process().
mulScalar()
static float CVectorFloat::mulScalar (const float * pfSrc1, const float * pfSrc2, long long int iLength) inline static
computes the scalar product between two vectors
Parameters
pfSrc1 vector one
pfSrc2 vector two
iLength number of dimenions
Returns
float
Definition at line 286 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrc1);
        assert (pfSrc2);
        float  fResult = 0;
        for (auto i = 0; i < iLength; i++)
            fResult += pfSrc1[i] * pfSrc2[i];
        return fResult;
    }
Referenced by CCcf::compCcf(), CFeatureSpectralMfccs::compFeature(), CFeatureFromBlockIf::compFeatureTimeAcfCoeff(), CSpectrogramIf::compMelSpectrogram(), and CMatrix::mulMatColVec().
setValue()
static void CVectorFloat::setValue (float * pfDest, float fValue, long long int iLength) inline static
initializes the buffer to a specific value
Parameters
pfDest pointer to memory to be initialized
fValue value to use
iLength number of elements to be set
Returns
void
Definition at line 240 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfDest);
        for (auto i = 0; i < iLength; i++)
            pfDest[i] = fValue;
    }
Referenced by CFeatureSpectralPitchChroma::genPcFilters_().
setZero()
static void CVectorFloat::setZero (float * pfSrcDest, long long int iLength) inline static
sets a buffer to zero
Parameters
pfSrcDest pointer to memory to be modified
iLength buffer length
Returns
void
Definition at line 185 of file Vector.h.
    {
        CVector::setZero(pfSrcDest, iLength);
    }
References CVector::setZero().
Referenced by alloc(), CMatrix::alloc(), CFeatureSpectralMfccs::allocDctMat_(), CButterLp::calcCoeffs(), CFeatureSpectralFlux::CFeatureSpectralFlux(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma(), CInstFreq::CInstFreq(), CNoveltyFromBlockIf::CNoveltyFromBlockIf(), CBeatHistoIf::compBeatHisto(), CDtw::compDtw(), CFeatureSpectralMfccs::compFeature(), CFeatureSpectralPitchChroma::compFeature(), CFft::compFft(), CSpectrogramIf::generateMelFb_(), CBlockAudioFile::getNextBlock(), CBlockAudioBuffer::getNextBlock(), CCcf::init(), CMatrix::mulRowVecMat(), CBlockAudioFile::readFile2RingBuff(), and CMatrix::setEye().
setZeroBelowThresh()
static void CVectorFloat::setZeroBelowThresh (float * pfSrcDest, long long int iLength, float fThresh = 0.F) inline static
sets all values smaller than a threshold to 0
Parameters
pfSrcDest pointer to memory to be modified
iLength buffer length
fThresh threshold value
Returns
void
Definition at line 196 of file Vector.h.
    {
        CVector::setZeroBelowThresh(pfSrcDest, iLength, fThresh);
    }
References CVector::setZeroBelowThresh().
Referenced by CNoveltyIf::compNovelty().
sub_I()
static void CVectorFloat::sub_I (float * pfSrcDest, const float * pfSrc, long long int iLength) inline static
element-wise vector subtraction
Parameters
pfSrcDest one input and output buffer
pfSrc second input buffer
iLength number of element to be subtracted
Returns
void
Definition at line 355 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrcDest);
        assert(pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] -= pfSrc[i];
    }
Referenced by CNoveltyIf::compNovelty(), and CInstFreq::process().
subW_I()
static void CVectorFloat::subW_I (float * pfSrcDest, const float * pfSrc, float fWeight, long long int iLength) inline static
Definition at line 365 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(pfSrcDest);
        assert(pfSrc);
        for (auto i = 0; i < iLength; i++)
            pfSrcDest[i] -= fWeight*pfSrc[i];
    }
Referenced by CMatrix::inv_I().
The documentation for this class was generated from the following file:
Vector.h