ACA: sndlib.h File Reference
sndlib.h File Reference
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include "xen.h"
#include "vct.h"
Macros
#define SNDLIB_VERSION 23
#define SNDLIB_REVISION 0
#define SNDLIB_DATE "2-Sep-13"
#define bool int
#define true 1
#define false 0
#define MUS_EXPORT __declspec(dllexport)
#define MUS_LITTLE_ENDIAN 1
#define MUS_AUDIO_COMPATIBLE_FORMAT MUS_LSHORT
#define MUS_OUT_FORMAT MUS_LDOUBLE
#define MUS_NIST_SHORTPACK 2
#define MUS_AIFF_IMA_ADPCM 99
#define MUS_AUDIO_PACK_SYSTEM(n) ((n) << 16)
#define MUS_AUDIO_SYSTEM(n) (((n) >> 16) & 0xffff)
#define MUS_AUDIO_DEVICE(n) ((n) & 0xffff)
#define MUS_AUDIO_DEFAULT 0
#define MUS_ERROR -1
#define MUS_LOOP_INFO_SIZE 8
#define mus_sound_seek_frame(Ifd, Frm) mus_file_seek_frame(Ifd, Frm)
#define mus_sound_read(Fd, Beg, End, Chans, Bufs) mus_file_read(Fd, Beg, End, Chans, Bufs)
#define mus_sound_write(Fd, Beg, End, Chans, Bufs) mus_file_write(Fd, Beg, End, Chans, Bufs)
Typedefs
typedef double mus_float_t
typedef long long int mus_long_t
typedef void mus_error_handler_t(int type, char *msg)
typedef void mus_print_handler_t(char *msg)
typedef mus_float_t mus_clip_handler_t(mus_float_t val)
typedef void mus_header_write_hook_t(const char *filename)
Enumerations
enum {
MUS_UNSUPPORTED , MUS_NEXT , MUS_AIFC , MUS_RIFF ,
MUS_RF64 , MUS_BICSF , MUS_NIST , MUS_INRS ,
MUS_ESPS , MUS_SVX , MUS_VOC , MUS_SNDT ,
MUS_RAW , MUS_SMP , MUS_AVR , MUS_IRCAM ,
MUS_SD1 , MUS_SPPACK , MUS_MUS10 , MUS_HCOM ,
MUS_PSION , MUS_MAUD , MUS_IEEE , MUS_MATLAB ,
MUS_ADC , MUS_MIDI , MUS_SOUNDFONT , MUS_GRAVIS ,
MUS_COMDISCO , MUS_GOLDWAVE , MUS_SRFS , MUS_MIDI_SAMPLE_DUMP ,
MUS_DIAMONDWARE , MUS_ADF , MUS_SBSTUDIOII , MUS_DELUSION ,
MUS_FARANDOLE , MUS_SAMPLE_DUMP , MUS_ULTRATRACKER , MUS_YAMAHA_SY85 ,
MUS_YAMAHA_TX16W , MUS_DIGIPLAYER , MUS_COVOX , MUS_AVI ,
MUS_OMF , MUS_QUICKTIME , MUS_ASF , MUS_YAMAHA_SY99 ,
MUS_KURZWEIL_2000 , MUS_AIFF , MUS_PAF , MUS_CSL ,
MUS_FILE_SAMP , MUS_PVF , MUS_SOUNDFORGE , MUS_TWINVQ ,
MUS_AKAI4 , MUS_IMPULSETRACKER , MUS_KORG , MUS_NVF ,
MUS_CAFF , MUS_MAUI , MUS_SDIF , MUS_OGG ,
MUS_FLAC , MUS_SPEEX , MUS_MPEG , MUS_SHORTEN ,
MUS_TTA , MUS_WAVPACK , MUS_SOX , MUS_NUM_HEADER_TYPES
}
enum {
MUS_UNKNOWN , MUS_BSHORT , MUS_MULAW , MUS_BYTE ,
MUS_BFLOAT , MUS_BINT , MUS_ALAW , MUS_UBYTE ,
MUS_B24INT , MUS_BDOUBLE , MUS_LSHORT , MUS_LINT ,
MUS_LFLOAT , MUS_LDOUBLE , MUS_UBSHORT , MUS_ULSHORT ,
MUS_L24INT , MUS_BINTN , MUS_LINTN , MUS_BFLOAT_UNSCALED ,
MUS_LFLOAT_UNSCALED , MUS_BDOUBLE_UNSCALED , MUS_LDOUBLE_UNSCALED , MUS_NUM_DATA_FORMATS
}
enum {
MUS_NO_ERROR , MUS_NO_FREQUENCY , MUS_NO_PHASE , MUS_NO_GEN ,
MUS_NO_LENGTH , MUS_NO_FREE , MUS_NO_DESCRIBE , MUS_NO_DATA ,
MUS_NO_SCALER , MUS_MEMORY_ALLOCATION_FAILED , MUS_CANT_OPEN_FILE , MUS_NO_SAMPLE_INPUT ,
MUS_NO_SAMPLE_OUTPUT , MUS_NO_SUCH_CHANNEL , MUS_NO_FILE_NAME_PROVIDED , MUS_NO_LOCATION ,
MUS_NO_CHANNEL , MUS_NO_SUCH_FFT_WINDOW , MUS_UNSUPPORTED_DATA_FORMAT , MUS_HEADER_READ_FAILED ,
MUS_UNSUPPORTED_HEADER_TYPE , MUS_FILE_DESCRIPTORS_NOT_INITIALIZED , MUS_NOT_A_SOUND_FILE , MUS_FILE_CLOSED ,
MUS_WRITE_ERROR , MUS_HEADER_WRITE_FAILED , MUS_CANT_OPEN_TEMP_FILE , MUS_INTERRUPTED ,
MUS_BAD_ENVELOPE , MUS_AUDIO_CHANNELS_NOT_AVAILABLE , MUS_AUDIO_SRATE_NOT_AVAILABLE , MUS_AUDIO_FORMAT_NOT_AVAILABLE ,
MUS_AUDIO_NO_INPUT_AVAILABLE , MUS_AUDIO_CONFIGURATION_NOT_AVAILABLE , MUS_AUDIO_WRITE_ERROR , MUS_AUDIO_SIZE_NOT_AVAILABLE ,
MUS_AUDIO_DEVICE_NOT_AVAILABLE , MUS_AUDIO_CANT_CLOSE , MUS_AUDIO_CANT_OPEN , MUS_AUDIO_READ_ERROR ,
MUS_AUDIO_CANT_WRITE , MUS_AUDIO_CANT_READ , MUS_AUDIO_NO_READ_PERMISSION , MUS_CANT_CLOSE_FILE ,
MUS_ARG_OUT_OF_RANGE , MUS_NO_CHANNELS , MUS_NO_HOP , MUS_NO_WIDTH ,
MUS_NO_FILE_NAME , MUS_NO_RAMP , MUS_NO_RUN , MUS_NO_INCREMENT ,
MUS_NO_OFFSET , MUS_NO_XCOEFF , MUS_NO_YCOEFF , MUS_NO_XCOEFFS ,
MUS_NO_YCOEFFS , MUS_NO_RESET , MUS_BAD_SIZE , MUS_CANT_CONVERT ,
MUS_READ_ERROR , MUS_NO_FEEDFORWARD , MUS_NO_FEEDBACK , MUS_NO_INTERP_TYPE ,
MUS_NO_POSITION , MUS_NO_ORDER , MUS_INITIAL_ERROR_TAG
}
Functions
MUS_EXPORT int mus_error (int error, const char *format,...)
MUS_EXPORT void mus_print (const char *format,...)
MUS_EXPORT char * mus_format (const char *format,...)
MUS_EXPORT mus_error_handler_t * mus_error_set_handler (mus_error_handler_t *new_error_handler)
MUS_EXPORT int mus_make_error (const char *error_name)
MUS_EXPORT const char * mus_error_type_to_string (int err)
MUS_EXPORT mus_print_handler_t * mus_print_set_handler (mus_print_handler_t *new_print_handler)
MUS_EXPORT mus_clip_handler_t * mus_clip_set_handler (mus_clip_handler_t *new_clip_handler)
MUS_EXPORT mus_clip_handler_t * mus_clip_set_handler_and_checker (mus_clip_handler_t *new_clip_handler, bool(*checker)(void))
MUS_EXPORT mus_long_t mus_sound_samples (const char *arg)
MUS_EXPORT mus_long_t mus_sound_frames (const char *arg)
MUS_EXPORT int mus_sound_datum_size (const char *arg)
MUS_EXPORT mus_long_t mus_sound_data_location (const char *arg)
MUS_EXPORT int mus_sound_chans (const char *arg)
MUS_EXPORT int mus_sound_srate (const char *arg)
MUS_EXPORT int mus_sound_header_type (const char *arg)
MUS_EXPORT int mus_sound_data_format (const char *arg)
MUS_EXPORT int mus_sound_original_format (const char *arg)
MUS_EXPORT mus_long_t mus_sound_comment_start (const char *arg)
MUS_EXPORT mus_long_t mus_sound_comment_end (const char *arg)
MUS_EXPORT mus_long_t mus_sound_length (const char *arg)
MUS_EXPORT int mus_sound_fact_samples (const char *arg)
MUS_EXPORT time_t mus_sound_write_date (const char *arg)
MUS_EXPORT int mus_sound_type_specifier (const char *arg)
MUS_EXPORT int mus_sound_block_align (const char *arg)
MUS_EXPORT int mus_sound_bits_per_sample (const char *arg)
MUS_EXPORT int mus_sound_set_chans (const char *arg, int val)
MUS_EXPORT int mus_sound_set_srate (const char *arg, int val)
MUS_EXPORT int mus_sound_set_header_type (const char *arg, int val)
MUS_EXPORT int mus_sound_set_data_format (const char *arg, int val)
MUS_EXPORT int mus_sound_set_data_location (const char *arg, mus_long_t val)
MUS_EXPORT int mus_sound_set_samples (const char *arg, mus_long_t val)
MUS_EXPORT const char * mus_header_type_name (int type)
MUS_EXPORT const char * mus_data_format_name (int format)
MUS_EXPORT const char * mus_header_type_to_string (int type)
MUS_EXPORT const char * mus_data_format_to_string (int format)
MUS_EXPORT const char * mus_data_format_short_name (int format)
MUS_EXPORT char * mus_sound_comment (const char *name)
MUS_EXPORT int mus_bytes_per_sample (int format)
MUS_EXPORT float mus_sound_duration (const char *arg)
MUS_EXPORT int mus_sound_initialize (void)
MUS_EXPORT int mus_sound_override_header (const char *arg, int srate, int chans, int format, int type, mus_long_t location, mus_long_t size)
MUS_EXPORT int mus_sound_forget (const char *name)
MUS_EXPORT int mus_sound_prune (void)
MUS_EXPORT void mus_sound_report_cache (FILE *fp)
MUS_EXPORT int * mus_sound_loop_info (const char *arg)
MUS_EXPORT void mus_sound_set_loop_info (const char *arg, int *loop)
MUS_EXPORT int mus_sound_mark_info (const char *arg, int **mark_ids, int **mark_positions)
MUS_EXPORT int mus_sound_open_input (const char *arg)
MUS_EXPORT int mus_sound_open_output (const char *arg, int srate, int chans, int data_format, int header_type, const char *comment)
MUS_EXPORT int mus_sound_reopen_output (const char *arg, int chans, int format, int type, mus_long_t data_loc)
MUS_EXPORT int mus_sound_close_input (int fd)
MUS_EXPORT int mus_sound_close_output (int fd, mus_long_t bytes_of_data)
MUS_EXPORT mus_long_t mus_sound_maxamps (const char *ifile, int chans, mus_float_t *vals, mus_long_t *times)
MUS_EXPORT int mus_sound_set_maxamps (const char *ifile, int chans, mus_float_t *vals, mus_long_t *times)
MUS_EXPORT bool mus_sound_maxamp_exists (const char *ifile)
MUS_EXPORT bool mus_sound_channel_maxamp_exists (const char *file, int chan)
MUS_EXPORT mus_float_t mus_sound_channel_maxamp (const char *file, int chan, mus_long_t *pos)
MUS_EXPORT void mus_sound_channel_set_maxamp (const char *file, int chan, mus_float_t mx, mus_long_t pos)
MUS_EXPORT mus_long_t mus_file_to_array (const char *filename, int chan, mus_long_t start, mus_long_t samples, mus_float_t *array)
MUS_EXPORT int mus_array_to_file (const char *filename, mus_float_t *ddata, mus_long_t len, int srate, int channels)
MUS_EXPORT const char * mus_array_to_file_with_error (const char *filename, mus_float_t *ddata, mus_long_t len, int srate, int channels)
MUS_EXPORT mus_long_t mus_file_to_float_array (const char *filename, int chan, mus_long_t start, mus_long_t samples, mus_float_t *array)
MUS_EXPORT int mus_float_array_to_file (const char *filename, mus_float_t *ddata, mus_long_t len, int srate, int channels)
MUS_EXPORT int mus_audio_open_output (int dev, int srate, int chans, int format, int size)
MUS_EXPORT int mus_audio_open_input (int dev, int srate, int chans, int format, int size)
MUS_EXPORT int mus_audio_write (int line, char *buf, int bytes)
MUS_EXPORT int mus_audio_close (int line)
MUS_EXPORT int mus_audio_read (int line, char *buf, int bytes)
MUS_EXPORT int mus_audio_initialize (void)
MUS_EXPORT int mus_audio_reinitialize (void)
MUS_EXPORT char * mus_audio_moniker (void)
MUS_EXPORT int mus_audio_api (void)
MUS_EXPORT int mus_audio_compatible_format (int dev)
MUS_EXPORT int mus_audio_device_channels (int dev)
MUS_EXPORT int mus_audio_device_format (int dev)
MUS_EXPORT int mus_file_open_descriptors (int tfd, const char *arg, int df, int ds, mus_long_t dl, int dc, int dt)
MUS_EXPORT int mus_file_open_read (const char *arg)
MUS_EXPORT bool mus_file_probe (const char *arg)
MUS_EXPORT int mus_file_open_write (const char *arg)
MUS_EXPORT int mus_file_create (const char *arg)
MUS_EXPORT int mus_file_reopen_write (const char *arg)
MUS_EXPORT int mus_file_close (int fd)
MUS_EXPORT mus_long_t mus_file_seek_frame (int tfd, mus_long_t frame)
MUS_EXPORT mus_long_t mus_file_read (int fd, mus_long_t beg, mus_long_t end, int chans, mus_float_t **bufs)
MUS_EXPORT mus_long_t mus_file_read_chans (int fd, mus_long_t beg, mus_long_t end, int chans, mus_float_t **bufs, mus_float_t **cm)
MUS_EXPORT int mus_file_write (int tfd, mus_long_t beg, mus_long_t end, int chans, mus_float_t **bufs)
MUS_EXPORT mus_long_t mus_file_read_any (int tfd, mus_long_t beg, int chans, mus_long_t nints, mus_float_t **bufs, mus_float_t **cm)
MUS_EXPORT mus_long_t mus_file_read_file (int tfd, mus_long_t beg, int chans, mus_long_t nints, mus_float_t **bufs)
MUS_EXPORT mus_long_t mus_file_read_buffer (int charbuf_data_format, mus_long_t beg, int chans, mus_long_t nints, mus_float_t **bufs, char *charbuf)
MUS_EXPORT int mus_file_write_file (int tfd, mus_long_t beg, mus_long_t end, int chans, mus_float_t **bufs)
MUS_EXPORT int mus_file_write_buffer (int charbuf_data_format, mus_long_t beg, mus_long_t end, int chans, mus_float_t **bufs, char *charbuf, bool clipped)
MUS_EXPORT char * mus_expand_filename (const char *name)
MUS_EXPORT char * mus_getcwd (void)
MUS_EXPORT bool mus_clipping (void)
MUS_EXPORT bool mus_set_clipping (bool new_value)
MUS_EXPORT bool mus_file_clipping (int tfd)
MUS_EXPORT int mus_file_set_clipping (int tfd, bool clipped)
MUS_EXPORT int mus_file_set_header_type (int tfd, int type)
MUS_EXPORT int mus_file_header_type (int tfd)
MUS_EXPORT char * mus_file_fd_name (int tfd)
MUS_EXPORT int mus_file_set_chans (int tfd, int chans)
MUS_EXPORT int mus_iclamp (int lo, int val, int hi)
MUS_EXPORT mus_long_t mus_oclamp (mus_long_t lo, mus_long_t val, mus_long_t hi)
MUS_EXPORT mus_float_t mus_fclamp (mus_float_t lo, mus_float_t val, mus_float_t hi)
MUS_EXPORT void mus_reset_io_c (void)
MUS_EXPORT void mus_reset_headers_c (void)
MUS_EXPORT void mus_reset_audio_c (void)
MUS_EXPORT int mus_samples_bounds (unsigned char *data, int bytes, int chan, int chans, int format, mus_float_t *min_samp, mus_float_t *max_samp)
MUS_EXPORT mus_long_t mus_max_malloc (void)
MUS_EXPORT mus_long_t mus_set_max_malloc (mus_long_t new_max)
MUS_EXPORT mus_long_t mus_max_table_size (void)
MUS_EXPORT mus_long_t mus_set_max_table_size (mus_long_t new_max)
MUS_EXPORT char * mus_strdup (const char *str)
MUS_EXPORT int mus_strlen (const char *str)
MUS_EXPORT bool mus_strcmp (const char *str1, const char *str2)
MUS_EXPORT char * mus_strcat (char *errmsg, const char *str, int *err_size)
MUS_EXPORT bool mus_data_format_p (int n)
MUS_EXPORT bool mus_header_type_p (int n)
MUS_EXPORT mus_long_t mus_header_samples (void)
MUS_EXPORT mus_long_t mus_header_data_location (void)
MUS_EXPORT int mus_header_chans (void)
MUS_EXPORT int mus_header_srate (void)
MUS_EXPORT int mus_header_type (void)
MUS_EXPORT int mus_header_format (void)
MUS_EXPORT mus_long_t mus_header_comment_start (void)
MUS_EXPORT mus_long_t mus_header_comment_end (void)
MUS_EXPORT int mus_header_type_specifier (void)
MUS_EXPORT int mus_header_bits_per_sample (void)
MUS_EXPORT int mus_header_fact_samples (void)
MUS_EXPORT int mus_header_block_align (void)
MUS_EXPORT int mus_header_loop_mode (int which)
MUS_EXPORT int mus_header_loop_start (int which)
MUS_EXPORT int mus_header_loop_end (int which)
MUS_EXPORT int mus_header_mark_position (int id)
MUS_EXPORT int mus_header_mark_info (int **marker_ids, int **marker_positions)
MUS_EXPORT int mus_header_base_note (void)
MUS_EXPORT int mus_header_base_detune (void)
MUS_EXPORT void mus_header_set_raw_defaults (int sr, int chn, int frm)
MUS_EXPORT void mus_header_raw_defaults (int *sr, int *chn, int *frm)
MUS_EXPORT mus_long_t mus_header_true_length (void)
MUS_EXPORT int mus_header_original_format (void)
MUS_EXPORT mus_long_t mus_samples_to_bytes (int format, mus_long_t size)
MUS_EXPORT mus_long_t mus_bytes_to_samples (int format, mus_long_t size)
MUS_EXPORT int mus_header_read (const char *name)
MUS_EXPORT int mus_header_write (const char *name, int type, int srate, int chans, mus_long_t loc, mus_long_t size_in_samples, int format, const char *comment, int len)
MUS_EXPORT int mus_write_header (const char *name, int type, int in_srate, int in_chans, mus_long_t size_in_samples, int format, const char *comment)
MUS_EXPORT mus_long_t mus_header_aux_comment_start (int n)
MUS_EXPORT mus_long_t mus_header_aux_comment_end (int n)
MUS_EXPORT int mus_header_initialize (void)
MUS_EXPORT bool mus_header_writable (int type, int format)
MUS_EXPORT void mus_header_set_aiff_loop_info (int *data)
MUS_EXPORT int mus_header_sf2_entries (void)
MUS_EXPORT char * mus_header_sf2_name (int n)
MUS_EXPORT int mus_header_sf2_start (int n)
MUS_EXPORT int mus_header_sf2_end (int n)
MUS_EXPORT int mus_header_sf2_loop_start (int n)
MUS_EXPORT int mus_header_sf2_loop_end (int n)
MUS_EXPORT const char * mus_header_original_format_name (int format, int type)
MUS_EXPORT bool mus_header_no_header (const char *name)
MUS_EXPORT char * mus_header_riff_aux_comment (const char *name, mus_long_t *starts, mus_long_t *ends)
MUS_EXPORT char * mus_header_aiff_aux_comment (const char *name, mus_long_t *starts, mus_long_t *ends)
MUS_EXPORT int mus_header_change_chans (const char *filename, int type, int new_chans)
MUS_EXPORT int mus_header_change_srate (const char *filename, int type, int new_srate)
MUS_EXPORT int mus_header_change_type (const char *filename, int new_type, int new_format)
MUS_EXPORT int mus_header_change_format (const char *filename, int type, int new_format)
MUS_EXPORT int mus_header_change_location (const char *filename, int type, mus_long_t new_location)
MUS_EXPORT int mus_header_change_comment (const char *filename, int type, const char *new_comment)
MUS_EXPORT int mus_header_change_data_size (const char *filename, int type, mus_long_t bytes)
MUS_EXPORT mus_header_write_hook_t * mus_header_write_set_hook (mus_header_write_hook_t *new_hook)
Macro Definition Documentation
bool
#define bool int
Definition at line 22 of file sndlib.h.
false
#define false 0
Definition at line 24 of file sndlib.h.
MUS_AIFF_IMA_ADPCM
#define MUS_AIFF_IMA_ADPCM 99
Definition at line 108 of file sndlib.h.
MUS_AUDIO_COMPATIBLE_FORMAT
#define MUS_AUDIO_COMPATIBLE_FORMAT MUS_LSHORT
Definition at line 72 of file sndlib.h.
MUS_AUDIO_DEFAULT
#define MUS_AUDIO_DEFAULT 0
Definition at line 115 of file sndlib.h.
MUS_AUDIO_DEVICE
#define MUS_AUDIO_DEVICE (n) ((n) & 0xffff)
Definition at line 112 of file sndlib.h.
MUS_AUDIO_PACK_SYSTEM
#define MUS_AUDIO_PACK_SYSTEM (n) ((n) << 16)
Definition at line 110 of file sndlib.h.
MUS_AUDIO_SYSTEM
#define MUS_AUDIO_SYSTEM (n) (((n) >> 16) & 0xffff)
Definition at line 111 of file sndlib.h.
MUS_ERROR
#define MUS_ERROR -1
Definition at line 116 of file sndlib.h.
MUS_EXPORT
#define MUS_EXPORT __declspec(dllexport)
Definition at line 41 of file sndlib.h.
MUS_LITTLE_ENDIAN
#define MUS_LITTLE_ENDIAN 1
Definition at line 57 of file sndlib.h.
MUS_LOOP_INFO_SIZE
#define MUS_LOOP_INFO_SIZE 8
Definition at line 144 of file sndlib.h.
MUS_NIST_SHORTPACK
#define MUS_NIST_SHORTPACK 2
Definition at line 107 of file sndlib.h.
MUS_OUT_FORMAT
#define MUS_OUT_FORMAT MUS_LDOUBLE
Definition at line 81 of file sndlib.h.
mus_sound_read
#define mus_sound_read (Fd, Beg, End, Chans, Bufs) mus_file_read(Fd, Beg, End, Chans, Bufs)
Definition at line 222 of file sndlib.h.
mus_sound_seek_frame
#define mus_sound_seek_frame (Ifd, Frm) mus_file_seek_frame(Ifd, Frm)
Definition at line 221 of file sndlib.h.
mus_sound_write
#define mus_sound_write (Fd, Beg, End, Chans, Bufs) mus_file_write(Fd, Beg, End, Chans, Bufs)
Definition at line 223 of file sndlib.h.
SNDLIB_DATE
#define SNDLIB_DATE "2-Sep-13"
Definition at line 6 of file sndlib.h.
SNDLIB_REVISION
#define SNDLIB_REVISION 0
Definition at line 5 of file sndlib.h.
SNDLIB_VERSION
#define SNDLIB_VERSION 23
Definition at line 4 of file sndlib.h.
true
#define true 1
Definition at line 23 of file sndlib.h.
Typedef Documentation
mus_clip_handler_t
typedef mus_float_t mus_clip_handler_t(mus_float_t val)
Definition at line 170 of file sndlib.h.
mus_error_handler_t
typedef void mus_error_handler_t(int type, char *msg)
Definition at line 162 of file sndlib.h.
mus_float_t
typedef double mus_float_t
Definition at line 29 of file sndlib.h.
mus_header_write_hook_t
typedef void mus_header_write_hook_t(const char *filename)
Definition at line 391 of file sndlib.h.
mus_long_t
typedef long long int mus_long_t
Definition at line 30 of file sndlib.h.
mus_print_handler_t
typedef void mus_print_handler_t(char *msg)
Definition at line 167 of file sndlib.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MUS_UNSUPPORTED
MUS_NEXT
MUS_AIFC
MUS_RIFF
MUS_RF64
MUS_BICSF
MUS_NIST
MUS_INRS
MUS_ESPS
MUS_SVX
MUS_VOC
MUS_SNDT
MUS_RAW
MUS_SMP
MUS_AVR
MUS_IRCAM
MUS_SD1
MUS_SPPACK
MUS_MUS10
MUS_HCOM
MUS_PSION
MUS_MAUD
MUS_IEEE
MUS_MATLAB
MUS_ADC
MUS_MIDI
MUS_SOUNDFONT
MUS_GRAVIS
MUS_COMDISCO
MUS_GOLDWAVE
MUS_SRFS
MUS_MIDI_SAMPLE_DUMP
MUS_DIAMONDWARE
MUS_ADF
MUS_SBSTUDIOII
MUS_DELUSION
MUS_FARANDOLE
MUS_SAMPLE_DUMP
MUS_ULTRATRACKER
MUS_YAMAHA_SY85
MUS_YAMAHA_TX16W
MUS_DIGIPLAYER
MUS_COVOX
MUS_AVI
MUS_OMF
MUS_QUICKTIME
MUS_ASF
MUS_YAMAHA_SY99
MUS_KURZWEIL_2000
MUS_AIFF
MUS_PAF
MUS_CSL
MUS_FILE_SAMP
MUS_PVF
MUS_SOUNDFORGE
MUS_TWINVQ
MUS_AKAI4
MUS_IMPULSETRACKER
MUS_KORG
MUS_NVF
MUS_CAFF
MUS_MAUI
MUS_SDIF
MUS_OGG
MUS_FLAC
MUS_SPEEX
MUS_MPEG
MUS_SHORTEN
MUS_TTA
MUS_WAVPACK
MUS_SOX
MUS_NUM_HEADER_TYPES
Definition at line 86 of file sndlib.h.
     {MUS_UNSUPPORTED, MUS_NEXT, MUS_AIFC, MUS_RIFF, MUS_RF64, MUS_BICSF, MUS_NIST, MUS_INRS, MUS_ESPS, MUS_SVX, MUS_VOC,
      MUS_SNDT, MUS_RAW, MUS_SMP, MUS_AVR, MUS_IRCAM, MUS_SD1, MUS_SPPACK, MUS_MUS10, MUS_HCOM, MUS_PSION, MUS_MAUD,
      MUS_IEEE, MUS_MATLAB, MUS_ADC, MUS_MIDI, MUS_SOUNDFONT, MUS_GRAVIS, MUS_COMDISCO, MUS_GOLDWAVE, MUS_SRFS,
      MUS_MIDI_SAMPLE_DUMP, MUS_DIAMONDWARE, MUS_ADF, MUS_SBSTUDIOII, MUS_DELUSION,
      MUS_FARANDOLE, MUS_SAMPLE_DUMP, MUS_ULTRATRACKER, MUS_YAMAHA_SY85, MUS_YAMAHA_TX16W, MUS_DIGIPLAYER,
      MUS_COVOX, MUS_AVI, MUS_OMF, MUS_QUICKTIME, MUS_ASF, MUS_YAMAHA_SY99, MUS_KURZWEIL_2000,
      MUS_AIFF, MUS_PAF, MUS_CSL, MUS_FILE_SAMP, MUS_PVF, MUS_SOUNDFORGE, MUS_TWINVQ, MUS_AKAI4,
      MUS_IMPULSETRACKER, MUS_KORG, MUS_NVF, MUS_CAFF, MUS_MAUI, MUS_SDIF, MUS_OGG, MUS_FLAC, MUS_SPEEX, MUS_MPEG,
      MUS_SHORTEN, MUS_TTA, MUS_WAVPACK, MUS_SOX,
      MUS_NUM_HEADER_TYPES};
anonymous enum
anonymous enum
Enumerator
MUS_UNKNOWN
MUS_BSHORT
MUS_MULAW
MUS_BYTE
MUS_BFLOAT
MUS_BINT
MUS_ALAW
MUS_UBYTE
MUS_B24INT
MUS_BDOUBLE
MUS_LSHORT
MUS_LINT
MUS_LFLOAT
MUS_LDOUBLE
MUS_UBSHORT
MUS_ULSHORT
MUS_L24INT
MUS_BINTN
MUS_LINTN
MUS_BFLOAT_UNSCALED
MUS_LFLOAT_UNSCALED
MUS_BDOUBLE_UNSCALED
MUS_LDOUBLE_UNSCALED
MUS_NUM_DATA_FORMATS
Definition at line 98 of file sndlib.h.
     {MUS_UNKNOWN, MUS_BSHORT, MUS_MULAW, MUS_BYTE, MUS_BFLOAT, MUS_BINT, MUS_ALAW, MUS_UBYTE, MUS_B24INT,
      MUS_BDOUBLE, MUS_LSHORT, MUS_LINT, MUS_LFLOAT, MUS_LDOUBLE, MUS_UBSHORT, MUS_ULSHORT, MUS_L24INT,
      MUS_BINTN, MUS_LINTN, MUS_BFLOAT_UNSCALED, MUS_LFLOAT_UNSCALED, MUS_BDOUBLE_UNSCALED, MUS_LDOUBLE_UNSCALED,
      MUS_NUM_DATA_FORMATS};
anonymous enum
anonymous enum
Enumerator
MUS_NO_ERROR
MUS_NO_FREQUENCY
MUS_NO_PHASE
MUS_NO_GEN
MUS_NO_LENGTH
MUS_NO_FREE
MUS_NO_DESCRIBE
MUS_NO_DATA
MUS_NO_SCALER
MUS_MEMORY_ALLOCATION_FAILED
MUS_CANT_OPEN_FILE
MUS_NO_SAMPLE_INPUT
MUS_NO_SAMPLE_OUTPUT
MUS_NO_SUCH_CHANNEL
MUS_NO_FILE_NAME_PROVIDED
MUS_NO_LOCATION
MUS_NO_CHANNEL
MUS_NO_SUCH_FFT_WINDOW
MUS_UNSUPPORTED_DATA_FORMAT
MUS_HEADER_READ_FAILED
MUS_UNSUPPORTED_HEADER_TYPE
MUS_FILE_DESCRIPTORS_NOT_INITIALIZED
MUS_NOT_A_SOUND_FILE
MUS_FILE_CLOSED
MUS_WRITE_ERROR
MUS_HEADER_WRITE_FAILED
MUS_CANT_OPEN_TEMP_FILE
MUS_INTERRUPTED
MUS_BAD_ENVELOPE
MUS_AUDIO_CHANNELS_NOT_AVAILABLE
MUS_AUDIO_SRATE_NOT_AVAILABLE
MUS_AUDIO_FORMAT_NOT_AVAILABLE
MUS_AUDIO_NO_INPUT_AVAILABLE
MUS_AUDIO_CONFIGURATION_NOT_AVAILABLE
MUS_AUDIO_WRITE_ERROR
MUS_AUDIO_SIZE_NOT_AVAILABLE
MUS_AUDIO_DEVICE_NOT_AVAILABLE
MUS_AUDIO_CANT_CLOSE
MUS_AUDIO_CANT_OPEN
MUS_AUDIO_READ_ERROR
MUS_AUDIO_CANT_WRITE
MUS_AUDIO_CANT_READ
MUS_AUDIO_NO_READ_PERMISSION
MUS_CANT_CLOSE_FILE
MUS_ARG_OUT_OF_RANGE
MUS_NO_CHANNELS
MUS_NO_HOP
MUS_NO_WIDTH
MUS_NO_FILE_NAME
MUS_NO_RAMP
MUS_NO_RUN
MUS_NO_INCREMENT
MUS_NO_OFFSET
MUS_NO_XCOEFF
MUS_NO_YCOEFF
MUS_NO_XCOEFFS
MUS_NO_YCOEFFS
MUS_NO_RESET
MUS_BAD_SIZE
MUS_CANT_CONVERT
MUS_READ_ERROR
MUS_NO_FEEDFORWARD
MUS_NO_FEEDBACK
MUS_NO_INTERP_TYPE
MUS_NO_POSITION
MUS_NO_ORDER
MUS_INITIAL_ERROR_TAG
Definition at line 118 of file sndlib.h.
     {MUS_NO_ERROR, MUS_NO_FREQUENCY, MUS_NO_PHASE, MUS_NO_GEN, MUS_NO_LENGTH,
      MUS_NO_FREE, MUS_NO_DESCRIBE, MUS_NO_DATA, MUS_NO_SCALER,
      MUS_MEMORY_ALLOCATION_FAILED,
      MUS_CANT_OPEN_FILE, MUS_NO_SAMPLE_INPUT, MUS_NO_SAMPLE_OUTPUT,
      MUS_NO_SUCH_CHANNEL, MUS_NO_FILE_NAME_PROVIDED, MUS_NO_LOCATION, MUS_NO_CHANNEL,
      MUS_NO_SUCH_FFT_WINDOW, MUS_UNSUPPORTED_DATA_FORMAT, MUS_HEADER_READ_FAILED,
      MUS_UNSUPPORTED_HEADER_TYPE,
      MUS_FILE_DESCRIPTORS_NOT_INITIALIZED, MUS_NOT_A_SOUND_FILE, MUS_FILE_CLOSED, MUS_WRITE_ERROR,
      MUS_HEADER_WRITE_FAILED, MUS_CANT_OPEN_TEMP_FILE, MUS_INTERRUPTED, MUS_BAD_ENVELOPE,
      MUS_AUDIO_CHANNELS_NOT_AVAILABLE, MUS_AUDIO_SRATE_NOT_AVAILABLE, MUS_AUDIO_FORMAT_NOT_AVAILABLE,
      MUS_AUDIO_NO_INPUT_AVAILABLE, MUS_AUDIO_CONFIGURATION_NOT_AVAILABLE,
      MUS_AUDIO_WRITE_ERROR, MUS_AUDIO_SIZE_NOT_AVAILABLE, MUS_AUDIO_DEVICE_NOT_AVAILABLE,
      MUS_AUDIO_CANT_CLOSE, MUS_AUDIO_CANT_OPEN, MUS_AUDIO_READ_ERROR,
      MUS_AUDIO_CANT_WRITE, MUS_AUDIO_CANT_READ, MUS_AUDIO_NO_READ_PERMISSION,
      MUS_CANT_CLOSE_FILE, MUS_ARG_OUT_OF_RANGE,
      MUS_NO_CHANNELS, MUS_NO_HOP, MUS_NO_WIDTH, MUS_NO_FILE_NAME, MUS_NO_RAMP, MUS_NO_RUN,
      MUS_NO_INCREMENT, MUS_NO_OFFSET,
      MUS_NO_XCOEFF, MUS_NO_YCOEFF, MUS_NO_XCOEFFS, MUS_NO_YCOEFFS, MUS_NO_RESET, MUS_BAD_SIZE, MUS_CANT_CONVERT,
      MUS_READ_ERROR,
      MUS_NO_FEEDFORWARD, MUS_NO_FEEDBACK, MUS_NO_INTERP_TYPE, MUS_NO_POSITION, MUS_NO_ORDER,
      MUS_INITIAL_ERROR_TAG};
Function Documentation
mus_array_to_file()
MUS_EXPORT int mus_array_to_file (const char * filename, mus_float_t * ddata, mus_long_t len, int srate, int channels)
mus_array_to_file_with_error()
MUS_EXPORT const char * mus_array_to_file_with_error (const char * filename, mus_float_t * ddata, mus_long_t len, int srate, int channels)
mus_audio_api()
MUS_EXPORT int mus_audio_api (void)
mus_audio_close()
MUS_EXPORT int mus_audio_close (int line)
mus_audio_compatible_format()
MUS_EXPORT int mus_audio_compatible_format (int dev)
mus_audio_device_channels()
MUS_EXPORT int mus_audio_device_channels (int dev)
mus_audio_device_format()
MUS_EXPORT int mus_audio_device_format (int dev)
mus_audio_initialize()
MUS_EXPORT int mus_audio_initialize (void)
mus_audio_moniker()
MUS_EXPORT char * mus_audio_moniker (void)
mus_audio_open_input()
MUS_EXPORT int mus_audio_open_input (int dev, int srate, int chans, int format, int size)
mus_audio_open_output()
MUS_EXPORT int mus_audio_open_output (int dev, int srate, int chans, int format, int size)
mus_audio_read()
MUS_EXPORT int mus_audio_read (int line, char * buf, int bytes)
mus_audio_reinitialize()
MUS_EXPORT int mus_audio_reinitialize (void)
mus_audio_write()
MUS_EXPORT int mus_audio_write (int line, char * buf, int bytes)
mus_bytes_per_sample()
MUS_EXPORT int mus_bytes_per_sample (int format)
mus_bytes_to_samples()
MUS_EXPORT mus_long_t mus_bytes_to_samples (int format, mus_long_t size)
mus_clip_set_handler()
MUS_EXPORT mus_clip_handler_t * mus_clip_set_handler (mus_clip_handler_t * new_clip_handler)
mus_clip_set_handler_and_checker()
MUS_EXPORT mus_clip_handler_t * mus_clip_set_handler_and_checker (mus_clip_handler_t * new_clip_handler, bool(*)(void) checker)
mus_clipping()
MUS_EXPORT bool mus_clipping (void)
mus_data_format_name()
MUS_EXPORT const char * mus_data_format_name (int format)
mus_data_format_p()
MUS_EXPORT bool mus_data_format_p (int n)
mus_data_format_short_name()
MUS_EXPORT const char * mus_data_format_short_name (int format)
mus_data_format_to_string()
MUS_EXPORT const char * mus_data_format_to_string (int format)
mus_error()
MUS_EXPORT int mus_error (int error, const char * format, ...)
mus_error_set_handler()
MUS_EXPORT mus_error_handler_t * mus_error_set_handler (mus_error_handler_t * new_error_handler)
mus_error_type_to_string()
MUS_EXPORT const char * mus_error_type_to_string (int err)
mus_expand_filename()
MUS_EXPORT char * mus_expand_filename (const char * name)
mus_fclamp()
MUS_EXPORT mus_float_t mus_fclamp (mus_float_t lo, mus_float_t val, mus_float_t hi)
mus_file_clipping()
MUS_EXPORT bool mus_file_clipping (int tfd)
mus_file_close()
MUS_EXPORT int mus_file_close (int fd)
mus_file_create()
MUS_EXPORT int mus_file_create (const char * arg)
mus_file_fd_name()
MUS_EXPORT char * mus_file_fd_name (int tfd)
mus_file_header_type()
MUS_EXPORT int mus_file_header_type (int tfd)
mus_file_open_descriptors()
MUS_EXPORT int mus_file_open_descriptors (int tfd, const char * arg, int df, int ds, mus_long_t dl, int dc, int dt)
mus_file_open_read()
MUS_EXPORT int mus_file_open_read (const char * arg)
mus_file_open_write()
MUS_EXPORT int mus_file_open_write (const char * arg)
mus_file_probe()
MUS_EXPORT bool mus_file_probe (const char * arg)
mus_file_read()
MUS_EXPORT mus_long_t mus_file_read (int fd, mus_long_t beg, mus_long_t end, int chans, mus_float_t ** bufs)
mus_file_read_any()
MUS_EXPORT mus_long_t mus_file_read_any (int tfd, mus_long_t beg, int chans, mus_long_t nints, mus_float_t ** bufs, mus_float_t ** cm)
mus_file_read_buffer()
MUS_EXPORT mus_long_t mus_file_read_buffer (int charbuf_data_format, mus_long_t beg, int chans, mus_long_t nints, mus_float_t ** bufs, char * charbuf)
mus_file_read_chans()
MUS_EXPORT mus_long_t mus_file_read_chans (int fd, mus_long_t beg, mus_long_t end, int chans, mus_float_t ** bufs, mus_float_t ** cm)
mus_file_read_file()
MUS_EXPORT mus_long_t mus_file_read_file (int tfd, mus_long_t beg, int chans, mus_long_t nints, mus_float_t ** bufs)
mus_file_reopen_write()
MUS_EXPORT int mus_file_reopen_write (const char * arg)
mus_file_seek_frame()
MUS_EXPORT mus_long_t mus_file_seek_frame (int tfd, mus_long_t frame)
mus_file_set_chans()
MUS_EXPORT int mus_file_set_chans (int tfd, int chans)
mus_file_set_clipping()
MUS_EXPORT int mus_file_set_clipping (int tfd, bool clipped)
mus_file_set_header_type()
MUS_EXPORT int mus_file_set_header_type (int tfd, int type)
mus_file_to_array()
MUS_EXPORT mus_long_t mus_file_to_array (const char * filename, int chan, mus_long_t start, mus_long_t samples, mus_float_t * array)
mus_file_to_float_array()
MUS_EXPORT mus_long_t mus_file_to_float_array (const char * filename, int chan, mus_long_t start, mus_long_t samples, mus_float_t * array)
mus_file_write()
MUS_EXPORT int mus_file_write (int tfd, mus_long_t beg, mus_long_t end, int chans, mus_float_t ** bufs)
mus_file_write_buffer()
MUS_EXPORT int mus_file_write_buffer (int charbuf_data_format, mus_long_t beg, mus_long_t end, int chans, mus_float_t ** bufs, char * charbuf, bool clipped)
mus_file_write_file()
MUS_EXPORT int mus_file_write_file (int tfd, mus_long_t beg, mus_long_t end, int chans, mus_float_t ** bufs)
mus_float_array_to_file()
MUS_EXPORT int mus_float_array_to_file (const char * filename, mus_float_t * ddata, mus_long_t len, int srate, int channels)
mus_format()
MUS_EXPORT char * mus_format (const char * format, ...)
mus_getcwd()
MUS_EXPORT char * mus_getcwd (void)
mus_header_aiff_aux_comment()
MUS_EXPORT char * mus_header_aiff_aux_comment (const char * name, mus_long_t * starts, mus_long_t * ends)
mus_header_aux_comment_end()
MUS_EXPORT mus_long_t mus_header_aux_comment_end (int n)
mus_header_aux_comment_start()
MUS_EXPORT mus_long_t mus_header_aux_comment_start (int n)
mus_header_base_detune()
MUS_EXPORT int mus_header_base_detune (void)
mus_header_base_note()
MUS_EXPORT int mus_header_base_note (void)
mus_header_bits_per_sample()
MUS_EXPORT int mus_header_bits_per_sample (void)
mus_header_block_align()
MUS_EXPORT int mus_header_block_align (void)
mus_header_change_chans()
MUS_EXPORT int mus_header_change_chans (const char * filename, int type, int new_chans)
mus_header_change_comment()
MUS_EXPORT int mus_header_change_comment (const char * filename, int type, const char * new_comment)
mus_header_change_data_size()
MUS_EXPORT int mus_header_change_data_size (const char * filename, int type, mus_long_t bytes)
mus_header_change_format()
MUS_EXPORT int mus_header_change_format (const char * filename, int type, int new_format)
mus_header_change_location()
MUS_EXPORT int mus_header_change_location (const char * filename, int type, mus_long_t new_location)
mus_header_change_srate()
MUS_EXPORT int mus_header_change_srate (const char * filename, int type, int new_srate)
mus_header_change_type()
MUS_EXPORT int mus_header_change_type (const char * filename, int new_type, int new_format)
mus_header_chans()
MUS_EXPORT int mus_header_chans (void)
mus_header_comment_end()
MUS_EXPORT mus_long_t mus_header_comment_end (void)
mus_header_comment_start()
MUS_EXPORT mus_long_t mus_header_comment_start (void)
mus_header_data_location()
MUS_EXPORT mus_long_t mus_header_data_location (void)
mus_header_fact_samples()
MUS_EXPORT int mus_header_fact_samples (void)
mus_header_format()
MUS_EXPORT int mus_header_format (void)
mus_header_initialize()
MUS_EXPORT int mus_header_initialize (void)
mus_header_loop_end()
MUS_EXPORT int mus_header_loop_end (int which)
mus_header_loop_mode()
MUS_EXPORT int mus_header_loop_mode (int which)
mus_header_loop_start()
MUS_EXPORT int mus_header_loop_start (int which)
mus_header_mark_info()
MUS_EXPORT int mus_header_mark_info (int ** marker_ids, int ** marker_positions)
mus_header_mark_position()
MUS_EXPORT int mus_header_mark_position (int id)
mus_header_no_header()
MUS_EXPORT bool mus_header_no_header (const char * name)
mus_header_original_format()
MUS_EXPORT int mus_header_original_format (void)
mus_header_original_format_name()
MUS_EXPORT const char * mus_header_original_format_name (int format, int type)
mus_header_raw_defaults()
MUS_EXPORT void mus_header_raw_defaults (int * sr, int * chn, int * frm)
mus_header_read()
MUS_EXPORT int mus_header_read (const char * name)
mus_header_riff_aux_comment()
MUS_EXPORT char * mus_header_riff_aux_comment (const char * name, mus_long_t * starts, mus_long_t * ends)
mus_header_samples()
MUS_EXPORT mus_long_t mus_header_samples (void)
mus_header_set_aiff_loop_info()
MUS_EXPORT void mus_header_set_aiff_loop_info (int * data)
mus_header_set_raw_defaults()
MUS_EXPORT void mus_header_set_raw_defaults (int sr, int chn, int frm)
mus_header_sf2_end()
MUS_EXPORT int mus_header_sf2_end (int n)
mus_header_sf2_entries()
MUS_EXPORT int mus_header_sf2_entries (void)
mus_header_sf2_loop_end()
MUS_EXPORT int mus_header_sf2_loop_end (int n)
mus_header_sf2_loop_start()
MUS_EXPORT int mus_header_sf2_loop_start (int n)
mus_header_sf2_name()
MUS_EXPORT char * mus_header_sf2_name (int n)
mus_header_sf2_start()
MUS_EXPORT int mus_header_sf2_start (int n)
mus_header_srate()
MUS_EXPORT int mus_header_srate (void)
mus_header_true_length()
MUS_EXPORT mus_long_t mus_header_true_length (void)
mus_header_type()
MUS_EXPORT int mus_header_type (void)
mus_header_type_name()
MUS_EXPORT const char * mus_header_type_name (int type)
mus_header_type_p()
MUS_EXPORT bool mus_header_type_p (int n)
mus_header_type_specifier()
MUS_EXPORT int mus_header_type_specifier (void)
mus_header_type_to_string()
MUS_EXPORT const char * mus_header_type_to_string (int type)
mus_header_writable()
MUS_EXPORT bool mus_header_writable (int type, int format)
mus_header_write()
MUS_EXPORT int mus_header_write (const char * name, int type, int srate, int chans, mus_long_t loc, mus_long_t size_in_samples, int format, const char * comment, int len)
mus_header_write_set_hook()
MUS_EXPORT mus_header_write_hook_t * mus_header_write_set_hook (mus_header_write_hook_t * new_hook)
mus_iclamp()
MUS_EXPORT int mus_iclamp (int lo, int val, int hi)
mus_make_error()
MUS_EXPORT int mus_make_error (const char * error_name)
mus_max_malloc()
MUS_EXPORT mus_long_t mus_max_malloc (void)
mus_max_table_size()
MUS_EXPORT mus_long_t mus_max_table_size (void)
mus_oclamp()
MUS_EXPORT mus_long_t mus_oclamp (mus_long_t lo, mus_long_t val, mus_long_t hi)
mus_print()
MUS_EXPORT void mus_print (const char * format, ...)
mus_print_set_handler()
MUS_EXPORT mus_print_handler_t * mus_print_set_handler (mus_print_handler_t * new_print_handler)
mus_reset_audio_c()
MUS_EXPORT void mus_reset_audio_c (void)
mus_reset_headers_c()
MUS_EXPORT void mus_reset_headers_c (void)
mus_reset_io_c()
MUS_EXPORT void mus_reset_io_c (void)
mus_samples_bounds()
MUS_EXPORT int mus_samples_bounds (unsigned char * data, int bytes, int chan, int chans, int format, mus_float_t * min_samp, mus_float_t * max_samp)
mus_samples_to_bytes()
MUS_EXPORT mus_long_t mus_samples_to_bytes (int format, mus_long_t size)
mus_set_clipping()
MUS_EXPORT bool mus_set_clipping (bool new_value)
mus_set_max_malloc()
MUS_EXPORT mus_long_t mus_set_max_malloc (mus_long_t new_max)
mus_set_max_table_size()
MUS_EXPORT mus_long_t mus_set_max_table_size (mus_long_t new_max)
mus_sound_bits_per_sample()
MUS_EXPORT int mus_sound_bits_per_sample (const char * arg)
mus_sound_block_align()
MUS_EXPORT int mus_sound_block_align (const char * arg)
mus_sound_channel_maxamp()
MUS_EXPORT mus_float_t mus_sound_channel_maxamp (const char * file, int chan, mus_long_t * pos)
mus_sound_channel_maxamp_exists()
MUS_EXPORT bool mus_sound_channel_maxamp_exists (const char * file, int chan)
mus_sound_channel_set_maxamp()
MUS_EXPORT void mus_sound_channel_set_maxamp (const char * file, int chan, mus_float_t mx, mus_long_t pos)
mus_sound_chans()
MUS_EXPORT int mus_sound_chans (const char * arg)
Referenced by CAudioFileSndLib::openFile().
mus_sound_close_input()
MUS_EXPORT int mus_sound_close_input (int fd)
Referenced by CAudioFileSndLib::closeFile().
mus_sound_close_output()
MUS_EXPORT int mus_sound_close_output (int fd, mus_long_t bytes_of_data)
Referenced by CAudioFileSndLib::closeFile().
mus_sound_comment()
MUS_EXPORT char * mus_sound_comment (const char * name)
mus_sound_comment_end()
MUS_EXPORT mus_long_t mus_sound_comment_end (const char * arg)
mus_sound_comment_start()
MUS_EXPORT mus_long_t mus_sound_comment_start (const char * arg)
mus_sound_data_format()
MUS_EXPORT int mus_sound_data_format (const char * arg)
Referenced by CAudioFileSndLib::openFile().
mus_sound_data_location()
MUS_EXPORT mus_long_t mus_sound_data_location (const char * arg)
mus_sound_datum_size()
MUS_EXPORT int mus_sound_datum_size (const char * arg)
mus_sound_duration()
MUS_EXPORT float mus_sound_duration (const char * arg)
mus_sound_fact_samples()
MUS_EXPORT int mus_sound_fact_samples (const char * arg)
mus_sound_forget()
MUS_EXPORT int mus_sound_forget (const char * name)
mus_sound_frames()
MUS_EXPORT mus_long_t mus_sound_frames (const char * arg)
Referenced by CAudioFileSndLib::openFile().
mus_sound_header_type()
MUS_EXPORT int mus_sound_header_type (const char * arg)
Referenced by CAudioFileSndLib::openFile().
mus_sound_initialize()
MUS_EXPORT int mus_sound_initialize (void)
mus_sound_length()
MUS_EXPORT mus_long_t mus_sound_length (const char * arg)
mus_sound_loop_info()
MUS_EXPORT int * mus_sound_loop_info (const char * arg)
mus_sound_mark_info()
MUS_EXPORT int mus_sound_mark_info (const char * arg, int ** mark_ids, int ** mark_positions)
mus_sound_maxamp_exists()
MUS_EXPORT bool mus_sound_maxamp_exists (const char * ifile)
mus_sound_maxamps()
MUS_EXPORT mus_long_t mus_sound_maxamps (const char * ifile, int chans, mus_float_t * vals, mus_long_t * times)
mus_sound_open_input()
MUS_EXPORT int mus_sound_open_input (const char * arg)
Referenced by CAudioFileSndLib::openFile().
mus_sound_open_output()
MUS_EXPORT int mus_sound_open_output (const char * arg, int srate, int chans, int data_format, int header_type, const char * comment)
Referenced by CAudioFileSndLib::openFile().
mus_sound_original_format()
MUS_EXPORT int mus_sound_original_format (const char * arg)
mus_sound_override_header()
MUS_EXPORT int mus_sound_override_header (const char * arg, int srate, int chans, int format, int type, mus_long_t location, mus_long_t size)
mus_sound_prune()
MUS_EXPORT int mus_sound_prune (void)
mus_sound_reopen_output()
MUS_EXPORT int mus_sound_reopen_output (const char * arg, int chans, int format, int type, mus_long_t data_loc)
mus_sound_report_cache()
MUS_EXPORT void mus_sound_report_cache (FILE * fp)
mus_sound_samples()
MUS_EXPORT mus_long_t mus_sound_samples (const char * arg)
mus_sound_set_chans()
MUS_EXPORT int mus_sound_set_chans (const char * arg, int val)
Referenced by CAudioFileSndLib::openFile().
mus_sound_set_data_format()
MUS_EXPORT int mus_sound_set_data_format (const char * arg, int val)
Referenced by CAudioFileSndLib::openFile().
mus_sound_set_data_location()
MUS_EXPORT int mus_sound_set_data_location (const char * arg, mus_long_t val)
mus_sound_set_header_type()
MUS_EXPORT int mus_sound_set_header_type (const char * arg, int val)
Referenced by CAudioFileSndLib::openFile().
mus_sound_set_loop_info()
MUS_EXPORT void mus_sound_set_loop_info (const char * arg, int * loop)
mus_sound_set_maxamps()
MUS_EXPORT int mus_sound_set_maxamps (const char * ifile, int chans, mus_float_t * vals, mus_long_t * times)
mus_sound_set_samples()
MUS_EXPORT int mus_sound_set_samples (const char * arg, mus_long_t val)
mus_sound_set_srate()
MUS_EXPORT int mus_sound_set_srate (const char * arg, int val)
Referenced by CAudioFileSndLib::openFile().
mus_sound_srate()
MUS_EXPORT int mus_sound_srate (const char * arg)
Referenced by CAudioFileSndLib::openFile().
mus_sound_type_specifier()
MUS_EXPORT int mus_sound_type_specifier (const char * arg)
mus_sound_write_date()
MUS_EXPORT time_t mus_sound_write_date (const char * arg)
mus_strcat()
MUS_EXPORT char * mus_strcat (char * errmsg, const char * str, int * err_size)
mus_strcmp()
MUS_EXPORT bool mus_strcmp (const char * str1, const char * str2)
mus_strdup()
MUS_EXPORT char * mus_strdup (const char * str)
mus_strlen()
MUS_EXPORT int mus_strlen (const char * str)
mus_write_header()
MUS_EXPORT int mus_write_header (const char * name, int type, int in_srate, int in_chans, mus_long_t size_in_samples, int format, const char * comment)