ACA: CBlockAudioFile Class Reference
CBlockAudioFile Class Reference
Public Member Functions
CBlockAudioFile (CAudioFileIf *pCAudioFile, int iBlockLength, int iHopLength)
virtual ~CBlockAudioFile ()
bool IsEndOfData () const override
int getNextBlock (float *pfBlock, float *pfTimeStamp) override
Public Member Functions inherited from CBlockAudioIf
long long getNumBlocks () const
long long getLengthInSamples () const
float getTimeStamp (long long iBlockIdx)
virtual bool IsEndOfData () const =0
virtual int getNextBlock (float *pfBlock, float *pfTimeStampInS=0)=0
Private Member Functions
CBlockAudioFile (const CBlockAudioFile &that)
disallow copy construction
CBlockAudioFile & operator= (const CBlockAudioFile &c)
void readFile2RingBuff ()
Private Attributes
CAudioFileIf * m_pCAudioFile
CRingBuffer< float > * m_pCRingBuffer
float ** m_ppfAudioData
Additional Inherited Members
Static Public Member Functions inherited from CBlockAudioIf
static Error_t create (CBlockAudioIf *&pCInstance, CAudioFileIf *pCAudioFile, int iBlockLength, int iHopLength)
static Error_t create (CBlockAudioIf *&pCInstance, const float *pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate)
static Error_t destroy (CBlockAudioIf *&pCInstance)
Protected Member Functions inherited from CBlockAudioIf
CBlockAudioIf ()
virtual ~CBlockAudioIf ()
CBlockAudioIf (const CBlockAudioIf &that)
CBlockAudioIf & operator= (const CBlockAudioIf &c)
Protected Attributes inherited from CBlockAudioIf
long long m_iNumBlocks = 0
number of blocks
long long m_iCurrBlock = 0
current block index
long long m_iAudioLength = 0
length of audio buffer
int m_iBlockLength = 0
block length
int m_iNumChannels = 0
number of channels
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
Detailed Description
Definition at line 9 of file ToolBlockAudio.cpp.
Constructor & Destructor Documentation
CBlockAudioFile() [1/2]
CBlockAudioFile::CBlockAudioFile (CAudioFileIf * pCAudioFile, int iBlockLength, int iHopLength) inline
Definition at line 12 of file ToolBlockAudio.cpp.
                                                                                 :
        m_pCAudioFile(pCAudioFile),
        m_pCRingBuffer(0),
        m_ppfAudioData(0)
    {
        m_iBlockLength = iBlockLength;
        m_iHopLength = iHopLength;
        CAudioFileIf::FileSpec_t stFileSpec;
        // get length of audio file
        m_pCAudioFile->getLength(m_iAudioLength);
        m_pCAudioFile->getFileSpec(stFileSpec);
        m_iNumChannels = stFileSpec.iNumChannels;
        m_fSampleRate = stFileSpec.fSampleRateInHz;
        // compute number of blocks
        m_iNumBlocks = m_iAudioLength / m_iHopLength + 1;
        // initialize read buffers
        m_pCRingBuffer = new CRingBuffer<float>(iBlockLength+1);
        m_ppfAudioData = new float* [m_iNumChannels];
        for (auto c = 0; c < m_iNumChannels; c++)
            m_ppfAudioData[c] = new float[iHopLength];
        // prefill from file to read buffer
        while(m_pCRingBuffer->getNumValuesInBuffer() < m_pCRingBuffer->getLength() - m_iHopLength - 1)
            readFile2RingBuff();
    }
References CAudioFileIf::FileSpec_t::fSampleRateInHz, CAudioFileIf::getFileSpec(), CRingBuffer< T >::getLength(), CAudioFileIf::getLength(), CRingBuffer< T >::getNumValuesInBuffer(), CAudioFileIf::FileSpec_t::iNumChannels, CBlockAudioIf::m_fSampleRate, CBlockAudioIf::m_iAudioLength, CBlockAudioIf::m_iBlockLength, CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumBlocks, CBlockAudioIf::m_iNumChannels, m_pCAudioFile, m_pCRingBuffer, m_ppfAudioData, and readFile2RingBuff().
~CBlockAudioFile()
virtual CBlockAudioFile::~CBlockAudioFile () inline virtual
Definition at line 42 of file ToolBlockAudio.cpp.
    {
        delete m_pCRingBuffer;
        m_pCRingBuffer = 0;
        for (auto c = 0; c < m_iNumChannels; c++)
            delete[] m_ppfAudioData[c];
        delete[] m_ppfAudioData;
        m_ppfAudioData = 0;
    }
References CBlockAudioIf::m_iNumChannels, m_pCRingBuffer, and m_ppfAudioData.
CBlockAudioFile() [2/2]
CBlockAudioFile::CBlockAudioFile (const CBlockAudioFile & that) private
disallow copy construction
Member Function Documentation
getNextBlock()
int CBlockAudioFile::getNextBlock (float * pfBlock, float * pfTimeStampInS) inline override virtual
retrieves audio data for next block
Parameters
pfBlock (to be written) of length blocklength
pfTimeStampInS (to be written, optional) for current time stamp
Returns
int iNumFramesRead
Implements CBlockAudioIf.
Definition at line 58 of file ToolBlockAudio.cpp.
    {
        if (!m_pCAudioFile || !pfBlock)
            return -1;
        // read from file to read buffer
        readFile2RingBuff();
        int iNumFrames = m_iBlockLength;
        if (m_pCAudioFile->isEof())
            iNumFrames = m_pCRingBuffer->getNumValuesInBuffer();
        // get data from ringbuffer and increment read index
        m_pCRingBuffer->get(pfBlock, iNumFrames);
        if (iNumFrames < m_iBlockLength)
        {
            for (int c = 0; c < m_iNumChannels; c++)
                CVectorFloat::setZero(&pfBlock[iNumFrames], m_iBlockLength - iNumFrames);
            iNumFrames = m_iHopLength;
        }
        m_pCRingBuffer->setReadIdx(m_pCRingBuffer->getReadIdx() + m_iHopLength);
        if (pfTimeStamp)
            *pfTimeStamp = getTimeStamp(m_iCurrBlock);
        m_iCurrBlock++;
        return iNumFrames;
    }
References CRingBuffer< T >::get(), CRingBuffer< T >::getNumValuesInBuffer(), CRingBuffer< T >::getReadIdx(), CBlockAudioIf::getTimeStamp(), CAudioFileIf::isEof(), CBlockAudioIf::m_iBlockLength, CBlockAudioIf::m_iCurrBlock, CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumChannels, m_pCAudioFile, m_pCRingBuffer, readFile2RingBuff(), CRingBuffer< T >::setReadIdx(), and CVectorFloat::setZero().
IsEndOfData()
bool CBlockAudioFile::IsEndOfData () const inline override virtual
checks for end of data
Returns
bool true if end of audio data is reached
Implements CBlockAudioIf.
Definition at line 52 of file ToolBlockAudio.cpp.
    {
        assert(m_pCAudioFile);
        return m_pCAudioFile->isEof();
    }
References CAudioFileIf::isEof(), and m_pCAudioFile.
operator=()
CBlockAudioFile & CBlockAudioFile::operator= (const CBlockAudioFile & c) private
readFile2RingBuff()
void CBlockAudioFile::readFile2RingBuff () inline private
Definition at line 93 of file ToolBlockAudio.cpp.
    {
        // set file read length variable
        //long long iNumFrames = std::min(m_iHopLength, m_pCRingBuffer->getLength() - m_pCRingBuffer->getNumValuesInBuffer() + 1);
        long long iNumFrames = m_iHopLength;
        // read data (iNumOfFrames might be updated!)
        m_pCAudioFile->readData(m_ppfAudioData, iNumFrames);
        // set buffer to zero if not written (EOF)
        if (iNumFrames < m_iHopLength)
        {
            for (int c = 0; c < m_iNumChannels; c++)
                CVectorFloat::setZero(&m_ppfAudioData[c][iNumFrames], m_iHopLength - iNumFrames);
            iNumFrames = m_iHopLength;
        }
        // downmix in case of multichannel
        CPreProc::downmix(m_ppfAudioData[0], m_ppfAudioData, m_iNumChannels, iNumFrames);
        // write data into inputbuffer
        m_pCRingBuffer->putPostInc(m_ppfAudioData[0], m_iHopLength);
    }
References CPreProc::downmix(), CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumChannels, m_pCAudioFile, m_pCRingBuffer, m_ppfAudioData, CRingBuffer< T >::putPostInc(), CAudioFileIf::readData(), and CVectorFloat::setZero().
Referenced by CBlockAudioFile(), and getNextBlock().
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CBlockAudioFile::m_pCAudioFile private
Definition at line 117 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioFile(), getNextBlock(), IsEndOfData(), and readFile2RingBuff().
m_pCRingBuffer
CRingBuffer<float>* CBlockAudioFile::m_pCRingBuffer private
Definition at line 118 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioFile(), getNextBlock(), readFile2RingBuff(), and ~CBlockAudioFile().
m_ppfAudioData
float** CBlockAudioFile::m_ppfAudioData private
Definition at line 119 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioFile(), readFile2RingBuff(), and ~CBlockAudioFile().
The documentation for this class was generated from the following file:
ToolBlockAudio.cpp