ACA: CFilter< T > Class Template Reference
CFilter< T > Class Template Reference
class providing a generic filter implementation
#include <Filter.h>
Public Member Functions
CFilter ()
virtual ~CFilter ()
Error_t init (const T *pfB, const T *pfA, int iNumCoeffs)
Error_t reset (bool bFreeMem=true)
Error_t process (T *pfOut, const T *pfIn, long long iNumSamples)
Error_t processDFII (T *pfOut, const T *pfIn, long long iNumSamples)
Error_t filtfilt (T *pfOut, const T *pfIn, long long iNumSamples)
Private Types
enum FilterCoeffs_t { kFir , kIir , kNumFilterDims }
Private Member Functions
CFilter (const CFilter &that)
CFilter & operator= (const CFilter &c)
void setInitState_ (float fWeight)
Private Attributes
CRingBuffer< T > * m_pCFilterBuff = 0
internal ring buffer for filter (only used for direct form II implementation CFilter::processDFII)
T * m_aptCoeff [kNumFilterDims] = { 0,0 }
filter coefficients
T * m_ptProcBuff = 0
temp buffer for processing
int m_iNumFilterCoeffs = 0
number of filter coefficients
bool m_bIsInitialized = false
true if initialized
Detailed Description
template<class T>
class CFilter< T >
class providing a generic filter implementation
Definition at line 13 of file Filter.h.
Member Enumeration Documentation
FilterCoeffs_t
template<class T > enum CFilter::FilterCoeffs_t private
Enumerator
kFir
kIir
kNumFilterDims
Definition at line 231 of file Filter.h.
    {
        kFir,
        kIir,
        kNumFilterDims
    };
Constructor & Destructor Documentation
CFilter() [1/2]
template<class T > CFilter< T >::CFilter () inline
Definition at line 17 of file Filter.h.
{};
~CFilter()
template<class T > virtual CFilter< T >::~CFilter () inline virtual
Definition at line 18 of file Filter.h.
    {
        reset();
    };
References CFilter< T >::reset().
CFilter() [2/2]
template<class T > CFilter< T >::CFilter (const CFilter< T > & that) private
Member Function Documentation
filtfilt()
template<class T > Error_t CFilter< T >::filtfilt (T * pfOut, const T * pfIn, long long iNumSamples) inline
zero phase filtering (can only be called with a complete signal, not block by block)
Parameters
pfOut output signal (to be written, allocated by user)
pfIn input signal
iNumSamples length of both pfOut and pfIn
Returns
Error_t
Definition at line 168 of file Filter.h.
    {
        if (!m_bIsInitialized)
            return Error_t::kFunctionIllegalCallError;
        if (!pfOut || !pfIn || iNumSamples <= 0)
            return Error_t::kFunctionInvalidArgsError;
        // reset filter but don't delete memory
        this->reset(false);
        float* pfTmpBuff = 0;
        float* pfPadding = 0;
        int iPadLength = 3 * (m_iNumFilterCoeffs - 1);
        if (iPadLength > iNumSamples)
            return Error_t::kFunctionIllegalCallError;
        // alloc necessary memory
        CVectorFloat::alloc(pfTmpBuff, iNumSamples + iPadLength);
        CVectorFloat::alloc(pfPadding, iPadLength);
        for (auto i = 0; i < iPadLength; i++)
            pfPadding[iPadLength - 1 - i] = 2 * pfIn[0] - pfIn[i + 1];
        // set initial state
        this->setInitState_(pfPadding[0]);
        // front padding (discard results)
        this->process(pfTmpBuff, pfPadding, iPadLength);
        // forward path
        this->process(pfTmpBuff, pfIn, iNumSamples);
        // back padding in forward path
        for (auto i = 0; i < iPadLength; i++)
            pfPadding[i] = 2 * pfIn[iNumSamples - 1] - pfIn[iNumSamples - 2 - i];
        this->process(&pfTmpBuff[iNumSamples], pfPadding, iPadLength);
        // set initial state
        this->setInitState_(pfTmpBuff[iNumSamples+iPadLength-1]);
        // padded backward path (discard results)
        for (auto i = iNumSamples + iPadLength - 1; i >= iNumSamples; i--)
            this->process(pfOut, &pfTmpBuff[i], 1);
        // backward path
        for (auto i = iNumSamples - 1; i >= 0; i--)
            this->process(&pfOut[i], &pfTmpBuff[i], 1);
        // reset filter but don't delete memory
        this->reset(false);
        // free memory
        CVectorFloat::free(pfTmpBuff);
        CVectorFloat::free(pfPadding);
        return Error_t::kNoError;
    }
References CVectorFloat::alloc(), CVectorFloat::free(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, CFilter< T >::m_bIsInitialized, CFilter< T >::m_iNumFilterCoeffs, CFilter< T >::process(), CFilter< T >::reset(), and CFilter< T >::setInitState_().
Referenced by CResample::process().
init()
template<class T > Error_t CFilter< T >::init (const T * pfB, const T * pfA, int iNumCoeffs) inline
initializes the filter
Parameters
pfB numerator coefficients
pfA denominator coefficients (normalized: pfA[0] = 1)
length of both pfB, and pfA
Returns
Error_t
Definition at line 30 of file Filter.h.
    {
        if (!pfA || !pfB || iNumCoeffs <= 0)
            return Error_t::kFunctionInvalidArgsError;
        reset();
        // alloc internal coefficients
        for (auto i = 0; i < kNumFilterDims; i++)
        {
            m_aptCoeff[i] = new T[iNumCoeffs];
            CVector::setZero(m_aptCoeff[i], iNumCoeffs);
        }
        // set coefficients
        CVector::copy(m_aptCoeff[kFir], pfB, iNumCoeffs);
        CVector::copy(m_aptCoeff[kIir], pfA, iNumCoeffs);
        m_iNumFilterCoeffs = iNumCoeffs;
        // initialize other internal memory
        m_pCFilterBuff = new CRingBuffer<T>(iNumCoeffs);
        m_pCFilterBuff->setWriteIdx(static_cast<long long>(iNumCoeffs - 1));
        m_ptProcBuff = new T[static_cast<long long>(iNumCoeffs-1)];
        CVector::setZero(m_ptProcBuff, static_cast<long long>(iNumCoeffs - 1));
        m_bIsInitialized = true;
        return Error_t::kNoError;
    }
References CVector::copy(), CFilter< T >::kFir, kFunctionInvalidArgsError, CFilter< T >::kIir, kNoError, CFilter< T >::kNumFilterDims, CFilter< T >::m_aptCoeff, CFilter< T >::m_bIsInitialized, CFilter< T >::m_iNumFilterCoeffs, CFilter< T >::m_pCFilterBuff, CFilter< T >::m_ptProcBuff, CFilter< T >::reset(), and CVector::setZero().
Referenced by CResample::process().
operator=()
template<class T > CFilter & CFilter< T >::operator= (const CFilter< T > & c) private
process()
template<class T > Error_t CFilter< T >::process (T * pfOut, const T * pfIn, long long iNumSamples) inline
filters the signal (transposed direct form II implementation), can be called block by block
Parameters
pfOut output signal (to be written, allocated by user)
pfIn input signal
iNumSamples length of both pfOut and pfIn
Returns
Error_t
Definition at line 103 of file Filter.h.
    {
        if (!m_bIsInitialized)
            return Error_t::kFunctionIllegalCallError;
        if (!pfOut || !pfIn || iNumSamples <= 0)
            return Error_t::kFunctionInvalidArgsError;
        for (auto i = 0; i < iNumSamples; i++)
        {
            T fTmp = m_ptProcBuff[0] + m_aptCoeff[kFir][0] * pfIn[i];
            for (auto j = 1; j < m_iNumFilterCoeffs - 1; j++)
                m_ptProcBuff[j - 1] = m_ptProcBuff[j] - m_aptCoeff[kIir][j] * fTmp + m_aptCoeff[kFir][j] * pfIn[i];
            m_ptProcBuff[m_iNumFilterCoeffs-2] = -m_aptCoeff[kIir][m_iNumFilterCoeffs - 1] * fTmp + m_aptCoeff[kFir][m_iNumFilterCoeffs-1] * pfIn[i];
            pfOut[i] = fTmp;
        }
        return Error_t::kNoError;
    }
References CFilter< T >::kFir, kFunctionIllegalCallError, kFunctionInvalidArgsError, CFilter< T >::kIir, kNoError, CFilter< T >::m_aptCoeff, CFilter< T >::m_bIsInitialized, CFilter< T >::m_iNumFilterCoeffs, and CFilter< T >::m_ptProcBuff.
Referenced by CFilter< T >::filtfilt().
processDFII()
template<class T > Error_t CFilter< T >::processDFII (T * pfOut, const T * pfIn, long long iNumSamples) inline
filters the signal (direct form II implementation, here as "informative" implementation)
Parameters
pfOut output signal (to be written, allocated by user)
pfIn input signal
iNumSamples length of both pfOut and pfIn
Returns
Error_t
Definition at line 130 of file Filter.h.
    {
        if (!m_bIsInitialized)
            return Error_t::kFunctionIllegalCallError;
        if (!pfOut || !pfIn || iNumSamples <= 0)
            return Error_t::kFunctionInvalidArgsError;
        for (auto i = 0; i < iNumSamples; i++)
        {
            T fTmp = pfIn[i];
            // get buffer values
            m_pCFilterBuff->get(m_ptProcBuff, m_iNumFilterCoeffs - 1);
            // IIR part
            for (auto j = 1; j < m_iNumFilterCoeffs; j++)
                fTmp -= m_aptCoeff[kIir][j] * m_ptProcBuff[m_iNumFilterCoeffs - 1 - j];
            //put new value into buffer
            m_pCFilterBuff->putPostInc(fTmp);
            // FIR part
            pfOut[i] = m_aptCoeff[kFir][0] * fTmp;
            for (auto j = 1; j < m_iNumFilterCoeffs; j++)
                pfOut[i] += m_aptCoeff[kFir][j] * m_ptProcBuff[m_iNumFilterCoeffs - 1 - j];
            // increment read index
            m_pCFilterBuff->getPostInc();
        }
        return Error_t::kNoError;
    }
References CFilter< T >::kFir, kFunctionIllegalCallError, kFunctionInvalidArgsError, CFilter< T >::kIir, kNoError, CFilter< T >::m_aptCoeff, CFilter< T >::m_bIsInitialized, CFilter< T >::m_iNumFilterCoeffs, CFilter< T >::m_pCFilterBuff, and CFilter< T >::m_ptProcBuff.
reset()
template<class T > Error_t CFilter< T >::reset (bool bFreeMem = true) inline
resets a Filter instance
Returns
Error_t
Definition at line 64 of file Filter.h.
    {
        if (!m_bIsInitialized)
            return Error_t::kNoError;
        if (bFreeMem)
        {
            for (auto i = 0; i < kNumFilterDims; i++)
            {
                delete m_aptCoeff[i];
                m_aptCoeff[i] = 0;
            }
            m_iNumFilterCoeffs = 0;
            delete m_pCFilterBuff;
            m_pCFilterBuff = 0;
            delete[] m_ptProcBuff;
            m_ptProcBuff = 0;
            m_bIsInitialized = false;
        }
        else
        {
            m_pCFilterBuff->reset();
            m_pCFilterBuff->setWriteIdx(m_iNumFilterCoeffs - 1);
            CVector::setZero(m_ptProcBuff, m_iNumFilterCoeffs - 1);
        }
        return Error_t::kNoError;
    }
References kNoError, CFilter< T >::kNumFilterDims, CFilter< T >::m_aptCoeff, CFilter< T >::m_bIsInitialized, CFilter< T >::m_iNumFilterCoeffs, CFilter< T >::m_pCFilterBuff, CFilter< T >::m_ptProcBuff, and CVector::setZero().
Referenced by CFilter< T >::filtfilt(), CFilter< T >::init(), CGammatone::reset(), and CFilter< T >::~CFilter().
setInitState_()
template<class T > void CFilter< T >::setInitState_ (float fWeight) inline private
Definition at line 240 of file Filter.h.
    {
        float** ppfA = 0;
        float* pfB = 0;
        float* pfZi = 0;
        int iLengthOfCoeffBuffers = m_iNumFilterCoeffs - 1;
        CVectorFloat::alloc(pfB, iLengthOfCoeffBuffers);
        CVectorFloat::alloc(pfZi, iLengthOfCoeffBuffers);
        CMatrix::alloc(ppfA, iLengthOfCoeffBuffers, iLengthOfCoeffBuffers);
        for (auto i = 1; i < m_iNumFilterCoeffs; i++)
            pfB[i - 1] = m_aptCoeff[kFir][i] - m_aptCoeff[kFir][0] * m_aptCoeff[kIir][i];
        for (auto m = 0; m < iLengthOfCoeffBuffers; m++)
        {
            ppfA[m][m] = 1;
            ppfA[m][0] += m_aptCoeff[kIir][m + 1];
            if (m < iLengthOfCoeffBuffers-1)
                ppfA[m][m + 1] = -1;
        }
        // solve linear equation
        CMatrix::inv_I(ppfA, iLengthOfCoeffBuffers, iLengthOfCoeffBuffers);
        CMatrix::mulMatColVec(pfZi, ppfA, pfB, iLengthOfCoeffBuffers, iLengthOfCoeffBuffers);
        // set internal state
        for (auto i = 0; i < iLengthOfCoeffBuffers; i++)
            m_ptProcBuff[i] = fWeight * pfZi[i];
        // clean up
        CMatrix::free(ppfA, iLengthOfCoeffBuffers);
        CVectorFloat::free(pfB);
        CVectorFloat::free(pfZi);
    }
References CVectorFloat::alloc(), CMatrix::alloc(), CVectorFloat::free(), CMatrix::free(), CMatrix::inv_I(), CFilter< T >::kFir, CFilter< T >::kIir, CFilter< T >::m_aptCoeff, CFilter< T >::m_iNumFilterCoeffs, CFilter< T >::m_ptProcBuff, and CMatrix::mulMatColVec().
Referenced by CFilter< T >::filtfilt().
Member Data Documentation
m_aptCoeff
template<class T > T* CFilter< T >::m_aptCoeff[kNumFilterDims] = { 0,0 } private
filter coefficients
Definition at line 279 of file Filter.h.
Referenced by CFilter< T >::init(), CFilter< T >::process(), CFilter< T >::processDFII(), CFilter< T >::reset(), and CFilter< T >::setInitState_().
m_bIsInitialized
template<class T > bool CFilter< T >::m_bIsInitialized = false private
true if initialized
Definition at line 285 of file Filter.h.
Referenced by CFilter< T >::filtfilt(), CFilter< T >::init(), CFilter< T >::process(), CFilter< T >::processDFII(), and CFilter< T >::reset().
m_iNumFilterCoeffs
template<class T > int CFilter< T >::m_iNumFilterCoeffs = 0 private
number of filter coefficients
Definition at line 283 of file Filter.h.
Referenced by CFilter< T >::filtfilt(), CFilter< T >::init(), CFilter< T >::process(), CFilter< T >::processDFII(), CFilter< T >::reset(), and CFilter< T >::setInitState_().
m_pCFilterBuff
template<class T > CRingBuffer<T>* CFilter< T >::m_pCFilterBuff = 0 private
internal ring buffer for filter (only used for direct form II implementation CFilter::processDFII)
Definition at line 277 of file Filter.h.
Referenced by CFilter< T >::init(), CFilter< T >::processDFII(), and CFilter< T >::reset().
m_ptProcBuff
template<class T > T* CFilter< T >::m_ptProcBuff = 0 private
temp buffer for processing
Definition at line 281 of file Filter.h.
Referenced by CFilter< T >::init(), CFilter< T >::process(), CFilter< T >::processDFII(), CFilter< T >::reset(), and CFilter< T >::setInitState_().
The documentation for this class was generated from the following file:
Filter.h