ACA: CPitchSpectralAcf Class Reference
CPitchSpectralAcf Class Reference
class for computation of the pitch via the acf of the magnitude spectrum
Public Member Functions
CPitchSpectralAcf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchSpectralAcf ()
float compF0 (const float *pfIn) override
Public Member Functions inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t getPitchExtractorIdx () const
Private Member Functions
CPitchSpectralAcf ()
CPitchSpectralAcf (const CPitchSpectralAcf &that)
disallow copy construction
CPitchSpectralAcf & operator= (const CPitchSpectralAcf &c)
Private Attributes
CCcf * m_pCCcf = 0
instance for correlation function computation
float * m_pfAcf = 0
acf result
float * m_pfProcBuff = 0
temporary buffer for processing
float m_fMin = 300.F
minimum frequency
Additional Inherited Members
Static Public Member Functions inherited from CPitchFromBlockIf
static Error_t create (CPitchFromBlockIf *&pCInstance, CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CPitchFromBlockIf *&pCInstance)
Protected Member Functions inherited from CPitchFromBlockIf
CPitchFromBlockIf ()
CPitchFromBlockIf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchFromBlockIf ()
CPitchFromBlockIf (const CPitchFromBlockIf &that)
CPitchFromBlockIf & operator= (const CPitchFromBlockIf &c)
Protected Attributes inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t m_ePitchIdx = CPitchIf::kNumPitchExtractors
index of Pitch to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
Detailed Description
class for computation of the pitch via the acf of the magnitude spectrum
Definition at line 18 of file PitchFromBlock.cpp.
Constructor & Destructor Documentation
CPitchSpectralAcf() [1/3]
CPitchSpectralAcf::CPitchSpectralAcf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate) inline
Definition at line 21 of file PitchFromBlock.cpp.
                                                                                               : CPitchFromBlockIf(ePitchIdx, iDataLength, fSampleRate)
    {
        m_pCCcf = new CCcf();
        m_pCCcf->init((m_iDataLength - 1) * 2);
        CVector::alloc(m_pfProcBuff, (static_cast<long long>(m_iDataLength) - 1) * 2);
        CVector::alloc(m_pfAcf, m_pCCcf->getCcfLength(true));
    };
References CVector::alloc(), CPitchFromBlockIf::CPitchFromBlockIf(), CPitchFromBlockIf::m_iDataLength, m_pCCcf, m_pfAcf, and m_pfProcBuff.
Referenced by CPitchSpectralAcf(), and operator=().
~CPitchSpectralAcf()
virtual CPitchSpectralAcf::~CPitchSpectralAcf () inline virtual
Definition at line 30 of file PitchFromBlock.cpp.
    {
        CVector::free(m_pfAcf);
        CVector::free(m_pfProcBuff);
        delete m_pCCcf;
        m_pCCcf = 0;
    };
References CVector::free(), m_pCCcf, m_pfAcf, and m_pfProcBuff.
CPitchSpectralAcf() [2/3]
CPitchSpectralAcf::CPitchSpectralAcf () inline private
Definition at line 80 of file PitchFromBlock.cpp.
{};
CPitchSpectralAcf() [3/3]
CPitchSpectralAcf::CPitchSpectralAcf (const CPitchSpectralAcf & that) private
disallow copy construction
References CPitchSpectralAcf().
Member Function Documentation
compF0()
float CPitchSpectralAcf::compF0 (const float * pfIn) inline override virtual
performs the PitchFromBlock computation
Parameters
pfIn input data of length iDataLength
Returns
float fF0InHz
Implements CPitchFromBlockIf.
Definition at line 39 of file PitchFromBlock.cpp.
    {
        assert(pfIn);
        // get minimum bin
        int iMin = CUtil::float2int<int>(CConversion::convertFreq2Bin(m_fMin, (m_iDataLength - 1) * 2, m_fSampleRate));
        float fTmp = 0;
        long long iMaxIdx = -1;
        // flip data so it's more robust and set bin 0 to max
        CVector::copy(m_pfProcBuff, pfIn, m_iDataLength);
        CVector::flip_I(m_pfProcBuff, m_iDataLength);
        CVector::copy(&m_pfProcBuff[m_iDataLength - 1], pfIn, m_iDataLength - static_cast<long long>(1));
        m_pfProcBuff[m_iDataLength - 1] = CVector::getMax(pfIn, m_iDataLength);
        // compute acf
        m_pCCcf->compCcf(m_pfProcBuff, m_pfProcBuff, true);
        m_pCCcf->getCcf(m_pfAcf, true);
        // adjust lower search boundary for local maxima
        for (auto k = iMin - 1; k < m_iDataLength; k++)
        {
            if (m_pfAcf[k + 1] < m_pfAcf[k])
            {
                iMin--;
                break;
            }
            iMin++;
        }
        // sanity check
        if (iMin >= m_iDataLength - 2)
            return 0.F;
        // now find the maximum
        CVector::findMax(&m_pfAcf[iMin], fTmp, iMaxIdx, m_iDataLength - static_cast<long long>(1) - iMin);
        return CConversion::convertBin2Freq((iMin + iMaxIdx) * 1.F, (m_iDataLength - 1) * 2, m_fSampleRate);
    };
References CConversion::convertBin2Freq(), CConversion::convertFreq2Bin(), CVector::copy(), CVector::findMax(), CVector::flip_I(), CUtil::float2int(), CVector::getMax(), m_fMin, CPitchFromBlockIf::m_fSampleRate, CPitchFromBlockIf::m_iDataLength, m_pCCcf, m_pfAcf, and m_pfProcBuff.
operator=()
CPitchSpectralAcf & CPitchSpectralAcf::operator= (const CPitchSpectralAcf & c) private
References CPitchSpectralAcf().
Member Data Documentation
m_fMin
float CPitchSpectralAcf::m_fMin = 300.F private
minimum frequency
Definition at line 88 of file PitchFromBlock.cpp.
Referenced by compF0().
m_pCCcf
CCcf* CPitchSpectralAcf::m_pCCcf = 0 private
instance for correlation function computation
Definition at line 84 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchSpectralAcf(), and ~CPitchSpectralAcf().
m_pfAcf
float* CPitchSpectralAcf::m_pfAcf = 0 private
acf result
Definition at line 85 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchSpectralAcf(), and ~CPitchSpectralAcf().
m_pfProcBuff
float* CPitchSpectralAcf::m_pfProcBuff = 0 private
temporary buffer for processing
Definition at line 86 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchSpectralAcf(), and ~CPitchSpectralAcf().
The documentation for this class was generated from the following file:
PitchFromBlock.cpp