ACA: CPitchFromFile Class Reference
CPitchFromFile Class Reference
class for computation of the pitch from a file
Public Member Functions
CPitchFromFile (PitchExtractors_t ePitchIdx, std::string strAudioFilePath, int iBlockLength, int iHopLength)
virtual ~CPitchFromFile ()
Public Member Functions inherited from CPitchIf
Error_t getNumBlocks (int &iNumBlocks) const
int getNumBlocks () const
float getTimeStamp (int iBlockIdx) const
Error_t getTimeStamps (float *pfAxisTicks) const
Error_t compF0 (float *pfPitch)
Private Attributes
CAudioFileIf * m_pCAudioFile
Additional Inherited Members
Public Types inherited from CPitchIf
enum PitchExtractors_t {
kPitchSpectralAcf , kPitchSpectralHps , kPitchTimeAcf , kPitchTimeAmdf ,
kPitchTimeAuditory , kPitchTimeZeroCrossings , kNumPitchExtractors
}
enum to index all Pitch extractorss
Static Public Member Functions inherited from CPitchIf
static Error_t create (CPitchIf *&pCInstance, PitchExtractors_t ePitchIdx, const std::string &strAudioFilePath, int iBlockLength=2048, int iHopLength=1024)
static Error_t create (CPitchIf *&pCInstance, PitchExtractors_t ePitchIdx, const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=2048, int iHopLength=1024)
static Error_t destroy (CPitchIf *&pCInstance)
static std::string getPitchString (PitchExtractors_t ePitchIdx)
static PitchExtractors_t getPitchIdxFromString (std::string sPitchString)
Protected Member Functions inherited from CPitchIf
CPitchIf ()
virtual ~CPitchIf ()
CPitchIf (const CPitchIf &that)
CPitchIf & operator= (const CPitchIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (PitchExtractors_t ePitchIdx)
init configuration
bool isPitchExtractorSpectral_ (PitchExtractors_t ePitchIdx)
void computeMagSpectrum_ ()
Protected Attributes inherited from CPitchIf
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CPitchFromBlockIf * m_pCPitch = 0
class for extracting f0 from block of data
CPitchAuditory * m_pCAuditory = 0
instace for auditory pitch tracking (the other pitch trackers don't need a time dependent implementation)
CFft * m_pCFft = 0
fft instance
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcBuff1 = 0
temporary buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of the pitch from a file
Definition at line 18 of file Pitch.cpp.
Constructor & Destructor Documentation
CPitchFromFile()
CPitchFromFile::CPitchFromFile (PitchExtractors_t ePitchIdx, std::string strAudioFilePath, int iBlockLength, int iHopLength)
Definition at line 38 of file Pitch.cpp.
                                                                                                                        :
    m_pCAudioFile(0)
{
    this->reset_();
    CAudioFileIf::FileSpec_t stFileSpec;
    CAudioFileIf::create(m_pCAudioFile);
    m_pCAudioFile->openFile(strAudioFilePath, CAudioFileIf::kFileRead);
    m_pCAudioFile->getFileSpec(stFileSpec);
    m_fSampleRate = stFileSpec.fSampleRateInHz;
    CBlockAudioIf::create(m_pCBlockAudio, m_pCAudioFile, iBlockLength, iHopLength);
    m_pCNormalize = new CNormalizeAudio(m_pCAudioFile);
    // set length variables
    m_iBlockLength = iBlockLength;
    m_iHopLength = iHopLength;
    init_(ePitchIdx);
}
References CAudioFileIf::create(), CBlockAudioIf::create(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CPitchIf::init_(), CAudioFileIf::kFileRead, CPitchIf::m_fSampleRate, CPitchIf::m_iBlockLength, CPitchIf::m_iHopLength, m_pCAudioFile, CPitchIf::m_pCBlockAudio, CPitchIf::m_pCNormalize, and CPitchIf::reset_().
~CPitchFromFile()
virtual CPitchFromFile::~CPitchFromFile () inline virtual
Definition at line 23 of file Pitch.cpp.
    {
        delete m_pCNormalize;
        m_pCNormalize = 0;
        CVector::free(m_pfProcBuff1);
        m_pCAudioFile->closeFile();
        CAudioFileIf::destroy(m_pCAudioFile);
    };
References CAudioFileIf::destroy(), CVector::free(), m_pCAudioFile, CPitchIf::m_pCNormalize, and CPitchIf::m_pfProcBuff1.
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CPitchFromFile::m_pCAudioFile private
Definition at line 35 of file Pitch.cpp.
Referenced by CPitchFromFile(), and ~CPitchFromFile().
The documentation for this class was generated from the following file:
Pitch.cpp