ACA: CPreProc Class Reference
CPreProc Class Reference
class with static utility functions for pre-processing
#include <ToolPreProc.h>
Static Public Member Functions
static void downmix (float *pfOutput, float **ppfInput, int iNumChannels, long long iNumSamples)
Detailed Description
class with static utility functions for pre-processing
Definition at line 12 of file ToolPreProc.h.
Member Function Documentation
downmix()
static void CPreProc::downmix (float * pfOutput, float ** ppfInput, int iNumChannels, long long iNumSamples) inline static
downmixes multichannel audio (can be inplace
Returns
void (no error returns b/c not user-facing)
Definition at line 18 of file ToolPreProc.h.
    {
        // sanity checks
        assert(pfOutput);
        assert(ppfInput);
        assert(ppfInput[0]);
        assert(iNumChannels > 0);
        assert(iNumSamples > 0);
        // copy in case of not inplace processing
        if (pfOutput != ppfInput[0])
            CVectorFloat::copy(pfOutput, ppfInput[0], iNumSamples);
        // downmix
        for (auto c = 1; c < iNumChannels; c++)
            CVectorFloat::add_I(pfOutput, ppfInput[c], iNumSamples);
        CVectorFloat::mulC_I(pfOutput, 1.F / iNumChannels, iNumSamples);
        return;
    }
References CVectorFloat::add_I(), CVectorFloat::copy(), and CVectorFloat::mulC_I().
Referenced by CNormalizeAudio::CNormalizeAudio(), and CBlockAudioFile::readFile2RingBuff().
The documentation for this class was generated from the following file:
ToolPreProc.h