ACA: CFeatureTimeMaxAcf Class Reference
CFeatureTimeMaxAcf Class Reference
Public Member Functions
CFeatureTimeMaxAcf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureTimeMaxAcf ()
Error_t compFeature (float *pfFeature, const float *pfInput) override
bool hasAdditionalParam () const override
Error_t setAdditionalParam (float fParamValue) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfInput)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Member Functions
CFeatureTimeMaxAcf ()
CFeatureTimeMaxAcf (const CFeatureTimeMaxAcf &that)
disallow copy construction
CFeatureTimeMaxAcf & operator= (const CFeatureTimeMaxAcf &c)
Private Attributes
CCcf * m_pCCcf = 0
float * m_pfAcf = 0
float m_fMax = 2000.F
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume it's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
Definition at line 726 of file FeatureFromBlock.cpp.
Constructor & Destructor Documentation
CFeatureTimeMaxAcf() [1/3]
CFeatureTimeMaxAcf::CFeatureTimeMaxAcf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 729 of file FeatureFromBlock.cpp.
                                                                                            : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        m_pCCcf = new CCcf();
        m_pCCcf->init(iDataLength);
        CVector::alloc(m_pfAcf , m_pCCcf->getCcfLength(true));
    };
References CVector::alloc(), CCcf::getCcfLength(), CCcf::init(), m_pCCcf, and m_pfAcf.
~CFeatureTimeMaxAcf()
virtual CFeatureTimeMaxAcf::~CFeatureTimeMaxAcf () inline virtual
Definition at line 737 of file FeatureFromBlock.cpp.
    {
        CVector::free(m_pfAcf);
        delete m_pCCcf;
        m_pCCcf = 0;
    };
References CVector::free(), m_pCCcf, and m_pfAcf.
CFeatureTimeMaxAcf() [2/3]
CFeatureTimeMaxAcf::CFeatureTimeMaxAcf () inline private
Definition at line 798 of file FeatureFromBlock.cpp.
{};
CFeatureTimeMaxAcf() [3/3]
CFeatureTimeMaxAcf::CFeatureTimeMaxAcf (const CFeatureTimeMaxAcf & that) private
disallow copy construction
Member Function Documentation
compFeature()
Error_t CFeatureTimeMaxAcf::compFeature (float * pfFeature, const float * pfInput) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfInput input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 745 of file FeatureFromBlock.cpp.
    {
        float fMinThresh = 0.35F;
        int iEta = 0,
            iEtaMin = static_cast<int>(m_fSampleRate / m_fMax);
        m_pCCcf->compCcf(pfInput, pfInput, true);
        m_pCCcf->getCcf(m_pfAcf, true);
        // avoid main lobe
        while (m_pfAcf[iEta] > fMinThresh)
            iEta++;
        if (iEtaMin < iEta)
            iEtaMin = iEta;
        // only look after first minimum
        iEta = 0;
        while (m_pfAcf[iEta] > m_pfAcf[iEta + 1])
        {
            iEta++;
            if (iEta >= m_iDataLength)
                break;
        }
        if (iEta >= m_iDataLength)
            iEtaMin = 0;
        else if (iEtaMin < iEta)
            iEtaMin = iEta;
        // get the maximum given the constraints above
        *pfFeature = CVector::getMax(&m_pfAcf[iEtaMin], static_cast<long long>(m_iDataLength) - iEtaMin);
        return Error_t::kNoError;
    };
References CCcf::compCcf(), CCcf::getCcf(), CVector::getMax(), kNoError, m_fMax, CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, m_pCCcf, and m_pfAcf.
hasAdditionalParam()
bool CFeatureTimeMaxAcf::hasAdditionalParam () const inline override virtual
returns true if there is an additional parameter
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 782 of file FeatureFromBlock.cpp.
    {
        return true;
    }
operator=()
CFeatureTimeMaxAcf & CFeatureTimeMaxAcf::operator= (const CFeatureTimeMaxAcf & c) private
setAdditionalParam()
Error_t CFeatureTimeMaxAcf::setAdditionalParam (float fParamValue) inline override virtual
returns true if there is an additional parameter
Parameters
fParamValue new parameter value
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 787 of file FeatureFromBlock.cpp.
    {
        if (fParamValue <= 0 || fParamValue > m_fSampleRate/2)
            return Error_t::kNoError;
        m_fMax = fParamValue;
        return Error_t::kNoError;
    }
References kNoError, m_fMax, and CFeatureFromBlockIf::m_fSampleRate.
Member Data Documentation
m_fMax
float CFeatureTimeMaxAcf::m_fMax = 2000.F private
Definition at line 805 of file FeatureFromBlock.cpp.
Referenced by compFeature(), and setAdditionalParam().
m_pCCcf
CCcf* CFeatureTimeMaxAcf::m_pCCcf = 0 private
Definition at line 802 of file FeatureFromBlock.cpp.
Referenced by CFeatureTimeMaxAcf(), compFeature(), and ~CFeatureTimeMaxAcf().
m_pfAcf
float* CFeatureTimeMaxAcf::m_pfAcf = 0 private
Definition at line 803 of file FeatureFromBlock.cpp.
Referenced by CFeatureTimeMaxAcf(), compFeature(), and ~CFeatureTimeMaxAcf().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp