ACA: CInstFreq Class Reference
CInstFreq Class Reference
class for single-pole low pass filtering
#include <ToolInstFreq.h>
Public Member Functions
CInstFreq (int iFftLength, int iHopLength, float fSampleRate)
virtual ~CInstFreq ()
Error_t process (float *pfInstFreq, const CFft::complex_t *pfSpectrum)
Private Types
enum Phase_t { kPhasePrev , kPhaseCurr , kNumPhases }
Private Member Functions
CInstFreq (const CInstFreq &that)
CInstFreq & operator= (const CInstFreq &c)
void princArg_ (float *pfSrcDestPhase)
Private Attributes
int m_iPhaseLength = 0
int m_iHopLength = 0
float m_fSampleRate = 0.F
float * m_apfPhase [kNumPhases] = { 0 }
float * m_pfSwapBuff = 0
float * m_pfOmega = 0
CFft * m_pCFft = 0
Detailed Description
class for single-pole low pass filtering
Definition at line 15 of file ToolInstFreq.h.
Member Enumeration Documentation
Phase_t
enum CInstFreq::Phase_t private
Enumerator
kPhasePrev
kPhaseCurr
kNumPhases
Definition at line 81 of file ToolInstFreq.h.
    {
        kPhasePrev,
        kPhaseCurr,
        kNumPhases
    };
Constructor & Destructor Documentation
CInstFreq() [1/2]
CInstFreq::CInstFreq (int iFftLength, int iHopLength, float fSampleRate) inline explicit
Definition at line 19 of file ToolInstFreq.h.
                                                                          :
        m_iHopLength(iHopLength),
        m_fSampleRate(fSampleRate)
    {
        // init Fft instance for handling phase and stuff
        m_pCFft = new CFft();
        m_pCFft->init(iFftLength);
        m_iPhaseLength = m_pCFft->getLength(CFft::kLengthPhase);
        m_pfOmega = new float[m_iPhaseLength];
        // use one buffer with two pointers
        m_pfSwapBuff = new float[2* m_iPhaseLength];
        CVectorFloat::setZero(m_pfSwapBuff, 2 * static_cast<long long>(m_iPhaseLength));
        m_apfPhase[0] = &m_pfSwapBuff[0];
        m_apfPhase[1] = &m_pfSwapBuff[m_iPhaseLength];
        //init omega
        for (auto k = 0; k < m_iPhaseLength; k++)
            m_pfOmega[k] = static_cast<float>(k*m_iHopLength * 2*M_PI/ iFftLength);
    }
References CFft::getLength(), CFft::init(), CFft::kLengthPhase, m_apfPhase, m_iHopLength, m_iPhaseLength, m_pCFft, m_pfOmega, m_pfSwapBuff, and CVectorFloat::setZero().
~CInstFreq()
virtual CInstFreq::~CInstFreq () inline virtual
Definition at line 42 of file ToolInstFreq.h.
    {
        delete[] m_pfOmega;
        delete[] m_pfSwapBuff;
        delete m_pCFft;
    }
References m_pCFft, m_pfOmega, and m_pfSwapBuff.
CInstFreq() [2/2]
CInstFreq::CInstFreq (const CInstFreq & that) private
Member Function Documentation
operator=()
CInstFreq & CInstFreq::operator= (const CInstFreq & c) private
princArg_()
void CInstFreq::princArg_ (float * pfSrcDestPhase) inline private
Definition at line 91 of file ToolInstFreq.h.
    {
        assert(pfSrcDestPhase);
        for (auto k = 0; k < m_iPhaseLength; k++)
            pfSrcDestPhase[k] = static_cast<float>(std::fmod(pfSrcDestPhase[k] + M_PI, -2 * M_PI) + M_PI);
        return;
    }
References m_iPhaseLength.
Referenced by process().
process()
Error_t CInstFreq::process (float * pfInstFreq, const CFft::complex_t * pfSpectrum) inline
performs the InstFreq computation
Parameters
pfInstFreq output vector containing the estimated frequencies (to be written), length iFftLength/2+1
pfSpectrum current (complex) spectrum return Error_t
Definition at line 56 of file ToolInstFreq.h.
    {
        if (!pfInstFreq || !pfSpectrum)
            return Error_t::kFunctionInvalidArgsError;
        // get current phase
        m_pCFft->getPhase(m_apfPhase[kPhaseCurr], pfSpectrum);
         //// calc instantaneous frequency
        CVectorFloat::sub_I(m_apfPhase[kPhasePrev], m_apfPhase[kPhaseCurr], m_iPhaseLength);
        CVectorFloat::add_I(m_apfPhase[kPhasePrev], m_pfOmega, m_iPhaseLength);
        CVectorFloat::mulC_I(m_apfPhase[kPhasePrev], -1.0F, m_iPhaseLength);
        princArg_(m_apfPhase[kPhasePrev]);
        CVectorFloat::add_I(m_apfPhase[kPhasePrev], m_pfOmega, m_iPhaseLength);
        CVectorFloat::copy(pfInstFreq, m_apfPhase[kPhasePrev], m_iPhaseLength);
        CVectorFloat::mulC_I(pfInstFreq, static_cast<float>(m_fSampleRate / (m_iHopLength * 2 * M_PI)), m_iPhaseLength);
        // remember phase for next call but avoid copying
        CUtil::swap(m_apfPhase[kPhasePrev], m_apfPhase[kPhaseCurr]);
        return Error_t::kNoError;
    }
References CVectorFloat::add_I(), CVectorFloat::copy(), CFft::getPhase(), kFunctionInvalidArgsError, kNoError, kPhaseCurr, kPhasePrev, m_apfPhase, m_fSampleRate, m_iHopLength, m_iPhaseLength, m_pCFft, m_pfOmega, CVectorFloat::mulC_I(), princArg_(), CVectorFloat::sub_I(), and CUtil::swap().
Member Data Documentation
m_apfPhase
float* CInstFreq::m_apfPhase[kNumPhases] = { 0 } private
Definition at line 105 of file ToolInstFreq.h.
Referenced by CInstFreq(), and process().
m_fSampleRate
float CInstFreq::m_fSampleRate = 0.F private
Definition at line 103 of file ToolInstFreq.h.
Referenced by process().
m_iHopLength
int CInstFreq::m_iHopLength = 0 private
Definition at line 102 of file ToolInstFreq.h.
Referenced by CInstFreq(), and process().
m_iPhaseLength
int CInstFreq::m_iPhaseLength = 0 private
Definition at line 101 of file ToolInstFreq.h.
Referenced by CInstFreq(), princArg_(), and process().
m_pCFft
CFft* CInstFreq::m_pCFft = 0 private
Definition at line 109 of file ToolInstFreq.h.
Referenced by CInstFreq(), process(), and ~CInstFreq().
m_pfOmega
float* CInstFreq::m_pfOmega = 0 private
Definition at line 107 of file ToolInstFreq.h.
Referenced by CInstFreq(), process(), and ~CInstFreq().
m_pfSwapBuff
float* CInstFreq::m_pfSwapBuff = 0 private
Definition at line 106 of file ToolInstFreq.h.
Referenced by CInstFreq(), and ~CInstFreq().
The documentation for this class was generated from the following file:
ToolInstFreq.h