ACA: CChordFromFile Class Reference
CChordFromFile Class Reference
Public Member Functions
CChordFromFile (std::string strAudioFilePath, int iBlockLength, int iHopLength)
virtual ~CChordFromFile ()
Public Member Functions inherited from CChordIf
Error_t getNumBlocks (int &iNumBlocks) const
int getNumBlocks () const
float getTimeStamp (int iBlockIdx) const
Error_t getTimeStamps (float *pfAxisTicks) const
Error_t compChords (Chords_t *peChord, bool bWithViterbi=true)
Private Attributes
CAudioFileIf * m_pCAudioFile
Additional Inherited Members
Public Types inherited from CChordIf
enum Chords_t {
kCMajor , kCsMajor , kDMajor , kDsMajor ,
kEMajor , kFMajor , kFsMajor , kGMajor ,
kGsMajor , kAMajor , kAsMajor , kBMajor ,
kCMinor , kCsMinor , kDMinor , kDsMinor ,
kEMinor , kFMinor , kFsMinor , kGMinor ,
kGsMinor , kAMinor , kAsMinor , kBMinor ,
kNoChord , kNumChords
}
Static Public Member Functions inherited from CChordIf
static Error_t create (CChordIf *&pCInstance, const std::string &strAudioFilePath, int iBlockLength=8192, int iHopLength=2048)
static Error_t create (CChordIf *&pCInstance, const float *pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength=8192, int iHopLength=2048)
static Error_t destroy (CChordIf *&pCInstance)
static std::string getChordString (Chords_t eChordIdx)
static Chords_t getChordIdxFromString (std::string sChordString)
Protected Member Functions inherited from CChordIf
CChordIf ()
virtual ~CChordIf ()
CChordIf (const CChordIf &that)
CChordIf & operator= (const CChordIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ ()
init configuration
void initViterbi_ ()
void computeMagSpectrum_ ()
Protected Attributes inherited from CChordIf
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CChordFromBlockIf * m_pCChord = 0
CFft * m_pCFft = 0
fft instance
CViterbi * m_pCViterbi = 0
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcessBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcessBuff1 = 0
temporary buffer
float ** m_ppfChordProbs = 0
chord probabilities (chrods X observations)
bool m_bIsInitialized = false
true if initialized
Detailed Description
Definition at line 22 of file Chord.cpp.
Constructor & Destructor Documentation
CChordFromFile()
CChordFromFile::CChordFromFile (std::string strAudioFilePath, int iBlockLength, int iHopLength)
Definition at line 42 of file Chord.cpp.
                                                                                           :
    m_pCAudioFile(0)
{
    this->reset_();
    CAudioFileIf::FileSpec_t stFileSpec;
    CAudioFileIf::create(m_pCAudioFile);
    m_pCAudioFile->openFile(strAudioFilePath, CAudioFileIf::kFileRead);
    m_pCAudioFile->getFileSpec(stFileSpec);
    m_fSampleRate = stFileSpec.fSampleRateInHz;
    CBlockAudioIf::create(m_pCBlockAudio, m_pCAudioFile, iBlockLength, iHopLength);
    m_pCNormalize = new CNormalizeAudio(m_pCAudioFile);
    // set length variables
    m_iBlockLength = iBlockLength;
    m_iHopLength = iHopLength;
    init_();
}
References CAudioFileIf::create(), CBlockAudioIf::create(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CAudioFileIf::getFileSpec(), CChordIf::init_(), CAudioFileIf::kFileRead, CChordIf::m_fSampleRate, CChordIf::m_iBlockLength, CChordIf::m_iHopLength, m_pCAudioFile, CChordIf::m_pCBlockAudio, CChordIf::m_pCNormalize, CAudioFileIf::openFile(), and CChordIf::reset_().
~CChordFromFile()
virtual CChordFromFile::~CChordFromFile () inline virtual
Definition at line 27 of file Chord.cpp.
    {
        delete m_pCNormalize;
        m_pCNormalize = 0;
        CVector::free(m_pfProcessBuff1);
        m_pCAudioFile->closeFile();
        CAudioFileIf::destroy(m_pCAudioFile);
    };
References CAudioFileIf::closeFile(), CAudioFileIf::destroy(), CVector::free(), m_pCAudioFile, CChordIf::m_pCNormalize, and CChordIf::m_pfProcessBuff1.
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CChordFromFile::m_pCAudioFile private
Definition at line 39 of file Chord.cpp.
Referenced by CChordFromFile(), and ~CChordFromFile().
The documentation for this class was generated from the following file:
Chord.cpp