ACA: CMovingAverage Class Reference
CMovingAverage Class Reference
class for single-pole low pass filtering
#include <ToolLowPass.h>
Public Member Functions
Error_t setFilterParam (int iFilterLength=64)
int getFilterParam () const
Error_t process (float *pfOutput, const float *pfInput, long long iLengthOfBuffer)
Error_t reset ()
void filtfilt (float *pfOutput, const float *pfInput, long long iLengthOfBuffer)
Static Public Member Functions
static Error_t create (CMovingAverage *&pCInstance)
static Error_t destroy (CMovingAverage *&pCInstance)
static int calcFilterLength (float fIntegrationTimeInS, float fSampleRate)
Private Member Functions
CMovingAverage ()
virtual ~CMovingAverage ()
CMovingAverage (const CMovingAverage &that)
CMovingAverage & operator= (const CMovingAverage &c)
Private Attributes
CRingBuffer< float > * m_pCRingBuff = new CRingBuffer<float>(65)
float m_fPrevOut = 0
Detailed Description
class for single-pole low pass filtering
Definition at line 122 of file ToolLowPass.h.
Constructor & Destructor Documentation
CMovingAverage() [1/2]
CMovingAverage::CMovingAverage () inline private
Definition at line 270 of file ToolLowPass.h.
    {
        reset();
    };
References reset().
Referenced by create().
~CMovingAverage()
virtual CMovingAverage::~CMovingAverage () inline private virtual
Definition at line 274 of file ToolLowPass.h.
    {
        delete m_pCRingBuff;
    };
References m_pCRingBuff.
CMovingAverage() [2/2]
CMovingAverage::CMovingAverage (const CMovingAverage & that) private
Member Function Documentation
calcFilterLength()
static int CMovingAverage::calcFilterLength (float fIntegrationTimeInS, float fSampleRate) inline static
compute the filter length from an "integration time"
Parameters
fIntegrationTimeInS integration time in seconds (the higher, the more low pass)
fSampleRate sample rate in Hz return int number of coeffs
Definition at line 182 of file ToolLowPass.h.
    {
        assert(fSampleRate > 0);
        assert(fIntegrationTimeInS >= 0);
        if (fIntegrationTimeInS <= 1.5F / fSampleRate)
            return 1;
        return static_cast<int>(std::ceil(fIntegrationTimeInS * fSampleRate));
    }
Referenced by CNoveltyIf::compNovelty().
create()
static Error_t CMovingAverage::create (CMovingAverage *& pCInstance) inline static
initializes a MovingAverage instance with file reading
Parameters
pCInstance pointer to instance to be written
Returns
Error_t
Definition at line 130 of file ToolLowPass.h.
    {
        pCInstance = new CMovingAverage();
        return Error_t::kNoError;
    }
References CMovingAverage(), and kNoError.
Referenced by CNoveltyIf::init_().
destroy()
static Error_t CMovingAverage::destroy (CMovingAverage *& pCInstance) inline static
destroys a MovingAverage instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 142 of file ToolLowPass.h.
    {
        delete pCInstance;
        pCInstance = 0;
        return Error_t::kNoError;
    }
References kNoError.
Referenced by CNoveltyIf::reset_().
filtfilt()
void CMovingAverage::filtfilt (float * pfOutput, const float * pfInput, long long iLengthOfBuffer) inline
performs zero-phase filtering with the MA
Parameters
pfOutput filter result (user-allocated, to be written, length iLengthOfBuffer)
pfInput input data of length iLengthOfBuffer
iLengthOfBuffer length of buffer in samples
Returns
Error_t
Definition at line 234 of file ToolLowPass.h.
    {
        int iFilterLength = this->getFilterParam();
        this->reset();
        this->setFilterParam(iFilterLength);
        float* pfTmpBuff = new float[iLengthOfBuffer + 2 * static_cast<long long>(iFilterLength)];
        this->process(&pfTmpBuff[iFilterLength], pfInput, iLengthOfBuffer);
        // tail
        for (auto i = 0; i < iFilterLength; i++)
        {
            float fZero = 0.F;
            this->process(&pfTmpBuff[iLengthOfBuffer + iFilterLength + i], &fZero, 1);
        }
        // reverse tail
        for (auto i = iLengthOfBuffer + 2*static_cast<long long>(iFilterLength) - 1; i >= iLengthOfBuffer + iFilterLength; i--)
        {
            float fZero = 0.F;
            this->process(&fZero, &pfTmpBuff[i], 1);
        }
        for (auto i = iLengthOfBuffer + iFilterLength - 1; i >= iFilterLength; i--)
            this->process(&pfOutput[i-iFilterLength], &pfTmpBuff[i], 1);
        this->reset();
        this->setFilterParam(iFilterLength);
        delete[] pfTmpBuff;
    }
References getFilterParam(), process(), reset(), and setFilterParam().
Referenced by CNoveltyIf::compNovelty().
getFilterParam()
int CMovingAverage::getFilterParam () const inline
returns the filter length
Returns
int
Definition at line 172 of file ToolLowPass.h.
    {
        return m_pCRingBuff->getNumValuesInBuffer();
    }
References CRingBuffer< T >::getNumValuesInBuffer(), and m_pCRingBuff.
Referenced by filtfilt().
operator=()
CMovingAverage & CMovingAverage::operator= (const CMovingAverage & c) private
process()
Error_t CMovingAverage::process (float * pfOutput, const float * pfInput, long long iLengthOfBuffer) inline
performs the MovingAverage computation
Parameters
pfOutput filter result (user-allocated, to be written, length iLengthOfBuffer)
pfInput input data of length iLengthOfBuffer
iLengthOfBuffer length of buffer in samples
Returns
Error_t
Definition at line 198 of file ToolLowPass.h.
    {
        if (!pfOutput || !pfInput || iLengthOfBuffer <= 0)
            return Error_t::kFunctionInvalidArgsError;
        int iFilterLength = m_pCRingBuff->getNumValuesInBuffer();
        // recursive implementation - beware of potential error propagation due to numerical precision
        for (auto i = 0; i < iLengthOfBuffer; i++)
        {
            m_fPrevOut += (pfInput[i] - m_pCRingBuff->getPostInc()) / iFilterLength;
            pfOutput[i] = m_fPrevOut;
            m_pCRingBuff->putPostInc(pfInput[i]);
        }
        return Error_t::kNoError;
    }
References CRingBuffer< T >::getNumValuesInBuffer(), CRingBuffer< T >::getPostInc(), kFunctionInvalidArgsError, kNoError, m_fPrevOut, m_pCRingBuff, and CRingBuffer< T >::putPostInc().
Referenced by filtfilt().
reset()
Error_t CMovingAverage::reset () inline
clears internal buffers and sets parameters to default
Returns
Error_t
Definition at line 219 of file ToolLowPass.h.
    {
        m_pCRingBuff->reset();
        m_pCRingBuff->setReadIdx(-64);
        m_fPrevOut = 0;
        return Error_t::kNoError;
    }
References kNoError, m_fPrevOut, m_pCRingBuff, CRingBuffer< T >::reset(), and CRingBuffer< T >::setReadIdx().
Referenced by CMovingAverage(), CNoveltyIf::compNovelty(), and filtfilt().
setFilterParam()
Error_t CMovingAverage::setFilterParam (int iFilterLength = 64) inline
sets the length of the filter
Parameters
iFilterLength length of the moving average filter (the longer the more lowpass)
Returns
int
Definition at line 154 of file ToolLowPass.h.
    {
        if (iFilterLength <= 0)
            return Error_t::kFunctionInvalidArgsError;
        if (m_pCRingBuff->getLength() < iFilterLength)
        {
            delete m_pCRingBuff;
            m_pCRingBuff = new CRingBuffer<float>(iFilterLength+1);
        }
        m_pCRingBuff->setReadIdx(-iFilterLength);
        return Error_t::kNoError;
    }
References CRingBuffer< T >::getLength(), kFunctionInvalidArgsError, kNoError, m_pCRingBuff, and CRingBuffer< T >::setReadIdx().
Referenced by CNoveltyIf::compNovelty(), and filtfilt().
Member Data Documentation
m_fPrevOut
float CMovingAverage::m_fPrevOut = 0 private
Definition at line 283 of file ToolLowPass.h.
Referenced by process(), and reset().
m_pCRingBuff
CRingBuffer<float>* CMovingAverage::m_pCRingBuff = new CRingBuffer<float>(65) private
Definition at line 281 of file ToolLowPass.h.
Referenced by getFilterParam(), process(), reset(), setFilterParam(), and ~CMovingAverage().
The documentation for this class was generated from the following file:
ToolLowPass.h