ACA: CNoveltyFromFile Class Reference
CNoveltyFromFile Class Reference
class for computation of the novelty function from a file
Public Member Functions
CNoveltyFromFile (Novelty_t eNoveltyIdx, std::string strAudioFilePath, int iBlockLength, int iHopLength)
virtual ~CNoveltyFromFile ()
Public Member Functions inherited from CNoveltyIf
Error_t getNumBlocks (int &iNumBlocks) const
int getNumBlocks () const
float getTimeStamp (int iBlockIdx) const
Error_t getTimeStamps (float *pfAxisTicks) const
Error_t compNovelty (float *pfNovelty, bool *pbisOnset=0)
Private Attributes
CAudioFileIf * m_pCAudioFile
Additional Inherited Members
Public Types inherited from CNoveltyIf
enum Novelty_t { kNoveltyFlux , kNoveltyHainsworth , kNoveltyLaroche , kNumNoveltyFunctions }
enum to index all Noveltys note: update CNoveltyIf::isNoveltySpectral_() when modifying
Static Public Member Functions inherited from CNoveltyIf
static Error_t create (CNoveltyIf *&pCInstance, Novelty_t eNoveltyIdx, const std::string &strAudioFilePath, int iBlockLength=4096, int iHopLength=512)
static Error_t create (CNoveltyIf *&pCInstance, Novelty_t eNoveltyIdx, const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=4096, int iHopLength=512)
static Error_t destroy (CNoveltyIf *&pCInstance)
static std::string getNoveltyString (Novelty_t eNoveltyIdx)
static Novelty_t getNoveltyIdxFromString (std::string sNoveltyString)
Protected Member Functions inherited from CNoveltyIf
CNoveltyIf ()
virtual ~CNoveltyIf ()
CNoveltyIf (const CNoveltyIf &that)
CNoveltyIf & operator= (const CNoveltyIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (Novelty_t eNoveltyIdx)
init configuration
void computeMagSpectrum_ ()
Protected Attributes inherited from CNoveltyIf
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CNoveltyFromBlockIf * m_pCNovelty = 0
instance for instantaneous novelty extraction
CFft * m_pCFft = 0
fft instance
CMovingAverage * m_pCLpFilter = 0
smoothing filter handle
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcBuff1 = 0
temporary buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of the novelty function from a file
Definition at line 17 of file Novelty.cpp.
Constructor & Destructor Documentation
CNoveltyFromFile()
CNoveltyFromFile::CNoveltyFromFile (Novelty_t eNoveltyIdx, std::string strAudioFilePath, int iBlockLength, int iHopLength)
Definition at line 37 of file Novelty.cpp.
                                                                                                                      :
    m_pCAudioFile(0)
{
    this->reset_();
    CAudioFileIf::FileSpec_t stFileSpec;
    CAudioFileIf::create(m_pCAudioFile);
    m_pCAudioFile->openFile(strAudioFilePath, CAudioFileIf::kFileRead);
    m_pCAudioFile->getFileSpec(stFileSpec);
    m_fSampleRate = stFileSpec.fSampleRateInHz;
    CBlockAudioIf::create(m_pCBlockAudio, m_pCAudioFile, iBlockLength, iHopLength);
    m_pCNormalize = new CNormalizeAudio(m_pCAudioFile);
    // set length variables
    m_iBlockLength = iBlockLength;
    m_iHopLength = iHopLength;
    init_(eNoveltyIdx);
}
References CAudioFileIf::create(), CBlockAudioIf::create(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CNoveltyIf::init_(), CAudioFileIf::kFileRead, CNoveltyIf::m_fSampleRate, CNoveltyIf::m_iBlockLength, CNoveltyIf::m_iHopLength, m_pCAudioFile, CNoveltyIf::m_pCBlockAudio, CNoveltyIf::m_pCNormalize, and CNoveltyIf::reset_().
~CNoveltyFromFile()
virtual CNoveltyFromFile::~CNoveltyFromFile () inline virtual
Definition at line 22 of file Novelty.cpp.
    {
        delete m_pCNormalize;
        m_pCNormalize = 0;
        CVector::free(m_pfProcBuff1);
        m_pCAudioFile->closeFile();
        CAudioFileIf::destroy(m_pCAudioFile);
    };
References CAudioFileIf::destroy(), CVector::free(), m_pCAudioFile, CNoveltyIf::m_pCNormalize, and CNoveltyIf::m_pfProcBuff1.
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CNoveltyFromFile::m_pCAudioFile private
Definition at line 34 of file Novelty.cpp.
Referenced by CNoveltyFromFile(), and ~CNoveltyFromFile().
The documentation for this class was generated from the following file:
Novelty.cpp