ACA: CPitchTimeAuditory Class Reference
CPitchTimeAuditory Class Reference
class for computation of the pitch via the auditory method from the time domain signal
Public Member Functions
CPitchTimeAuditory (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchTimeAuditory ()
float compF0 (const float *pfIn) override
Public Member Functions inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t getPitchExtractorIdx () const
Private Member Functions
CPitchTimeAuditory ()
CPitchTimeAuditory (const CPitchTimeAuditory &that)
disallow copy construction
CPitchTimeAuditory & operator= (const CPitchTimeAuditory &c)
int getAcfMax_ (const float *pfInput)
Private Attributes
CCcf * m_pCCcf = 0
instance for correlation function computation
float * m_pfAcf = 0
acf result
float * m_pfSumAcf = 0
aggregated acf result
float ** m_ppfProcBuff = 0
temporary processing buffer
CFilter< float > * m_apCFilter [m_iNumBands] = { 0 }
the actual filters
CGammaToneFbIf * m_pCFilterBank = 0
instance of gammatone filterbank
float m_fMax = 2000.F
maximum frequency to detect
const float m_fSmoothLpCutoff = 0.02F
cutoff frequency for smoothing lowpass
const float m_fMinThresh = 0.35F
minimum threshold for acf parsing
Static Private Attributes
static const int m_iNumBands = 20
number of filter bands
Additional Inherited Members
Static Public Member Functions inherited from CPitchFromBlockIf
static Error_t create (CPitchFromBlockIf *&pCInstance, CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CPitchFromBlockIf *&pCInstance)
Protected Member Functions inherited from CPitchFromBlockIf
CPitchFromBlockIf ()
CPitchFromBlockIf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchFromBlockIf ()
CPitchFromBlockIf (const CPitchFromBlockIf &that)
CPitchFromBlockIf & operator= (const CPitchFromBlockIf &c)
Protected Attributes inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t m_ePitchIdx = CPitchIf::kNumPitchExtractors
index of Pitch to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
Detailed Description
class for computation of the pitch via the auditory method from the time domain signal
Definition at line 222 of file PitchFromBlock.cpp.
Constructor & Destructor Documentation
CPitchTimeAuditory() [1/3]
CPitchTimeAuditory::CPitchTimeAuditory (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate) inline
Definition at line 225 of file PitchFromBlock.cpp.
                                                                                                : CPitchFromBlockIf(ePitchIdx, iDataLength, fSampleRate)
    {
        float afA[3] = { 0 };
        float afB[3] = { 0 };
        CButterLp::calcCoeffs(afB, afA, 2, m_fSmoothLpCutoff);
        m_pCCcf = new CCcf();
        m_pCCcf->init(iDataLength);
        CVector::alloc(m_pfAcf, m_pCCcf->getCcfLength(true));
        CVector::alloc(m_pfSumAcf, m_pCCcf->getCcfLength(true));
        CMatrix::alloc(m_ppfProcBuff, m_iNumBands, iDataLength);
        for (auto c = 0; c < m_iNumBands; c++)
        {
            m_apCFilter[c] = new CFilter<float>();
            m_apCFilter[c]->init(afB, afA, 3);
        }
        CGammaToneFbIf::create(m_pCFilterBank, fSampleRate, m_iNumBands);
    };
References CMatrix::alloc(), CVector::alloc(), CButterLp::calcCoeffs(), CPitchFromBlockIf::CPitchFromBlockIf(), CGammaToneFbIf::create(), m_apCFilter, m_fSmoothLpCutoff, m_iNumBands, m_pCCcf, m_pCFilterBank, m_pfAcf, m_pfSumAcf, and m_ppfProcBuff.
Referenced by CPitchTimeAuditory(), and operator=().
~CPitchTimeAuditory()
virtual CPitchTimeAuditory::~CPitchTimeAuditory () inline virtual
Definition at line 248 of file PitchFromBlock.cpp.
    {
        CVector::free(m_pfAcf);
        CVector::free(m_pfSumAcf);
        CMatrix::free(m_ppfProcBuff, m_iNumBands);
        for (auto c = 0; c < m_iNumBands; c++)
            delete m_apCFilter[c];
        delete m_pCCcf;
        m_pCCcf = 0;
        CGammaToneFbIf::destroy(m_pCFilterBank);
    };
References CGammaToneFbIf::destroy(), CMatrix::free(), CVector::free(), m_apCFilter, m_iNumBands, m_pCCcf, m_pCFilterBank, m_pfAcf, m_pfSumAcf, and m_ppfProcBuff.
CPitchTimeAuditory() [2/3]
CPitchTimeAuditory::CPitchTimeAuditory () inline private
Definition at line 290 of file PitchFromBlock.cpp.
{};
CPitchTimeAuditory() [3/3]
CPitchTimeAuditory::CPitchTimeAuditory (const CPitchTimeAuditory & that) private
disallow copy construction
References CPitchTimeAuditory().
Member Function Documentation
compF0()
float CPitchTimeAuditory::compF0 (const float * pfIn) inline override virtual
performs the PitchFromBlock computation
Parameters
pfIn input data of length iDataLength
Returns
float fF0InHz
Implements CPitchFromBlockIf.
Definition at line 263 of file PitchFromBlock.cpp.
    {
        assert(pfIn);
        CVector::setZero(m_pfSumAcf, m_iDataLength);
        m_pCFilterBank->process(m_ppfProcBuff, pfIn, m_iDataLength);
        for (auto c = 0; c < m_iNumBands; c++)
        {
            // smooth
            m_apCFilter[c]->process(m_ppfProcBuff[c], m_ppfProcBuff[c], m_iDataLength);
            // compute acf
            m_pCCcf->compCcf(m_ppfProcBuff[c], m_ppfProcBuff[c], true);
            m_pCCcf->getCcf(m_pfAcf, true);
            // compute sum of acfs
            CVector::add_I(m_pfSumAcf, m_pfAcf, m_iDataLength);
        }
        int iEta = getAcfMax_(m_pfSumAcf);
        return m_fSampleRate / iEta;
    }
References CVector::add_I(), getAcfMax_(), m_apCFilter, CPitchFromBlockIf::m_fSampleRate, CPitchFromBlockIf::m_iDataLength, m_iNumBands, m_pCCcf, m_pCFilterBank, m_pfAcf, m_pfSumAcf, m_ppfProcBuff, and CVector::setZero().
getAcfMax_()
int CPitchTimeAuditory::getAcfMax_ (const float * pfInput) inline private
Definition at line 294 of file PitchFromBlock.cpp.
    {
        int iEta = 0,
            iEtaMin = static_cast<int>(m_fSampleRate / m_fMax);
        // avoid main lobe
        while (pfInput[iEta] > m_fMinThresh)
            iEta++;
        if (iEtaMin < iEta)
            iEtaMin = iEta;
        // only look after first minimum
        iEta = 0;
        while (pfInput[iEta] > pfInput[iEta + 1])
        {
            iEta++;
            if (iEta >= m_iDataLength)
                break;
        }
        if (iEta >= m_iDataLength)
            iEtaMin = 0;
        else if (iEtaMin < iEta)
            iEtaMin = iEta;
        // get the maximum given the constraints above
        float fMax = 0;
        long long iMax = -1;
        CVector::findMax(&pfInput[iEtaMin], fMax, iMax, static_cast<long long>(m_iDataLength) - iEtaMin);
        if (fMax <= 0)
            return 0;
        return static_cast<int>(iMax + iEtaMin);
    };
References CVector::findMax(), m_fMax, m_fMinThresh, CPitchFromBlockIf::m_fSampleRate, and CPitchFromBlockIf::m_iDataLength.
Referenced by compF0().
operator=()
CPitchTimeAuditory & CPitchTimeAuditory::operator= (const CPitchTimeAuditory & c) private
References CPitchTimeAuditory().
Member Data Documentation
m_apCFilter
CFilter<float>* CPitchTimeAuditory::m_apCFilter[m_iNumBands] = { 0 } private
the actual filters
Definition at line 336 of file PitchFromBlock.cpp.
{ 0 }; //!< the actual filters
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_fMax
float CPitchTimeAuditory::m_fMax = 2000.F private
maximum frequency to detect
Definition at line 340 of file PitchFromBlock.cpp.
Referenced by getAcfMax_().
m_fMinThresh
const float CPitchTimeAuditory::m_fMinThresh = 0.35F private
minimum threshold for acf parsing
Definition at line 342 of file PitchFromBlock.cpp.
Referenced by getAcfMax_().
m_fSmoothLpCutoff
const float CPitchTimeAuditory::m_fSmoothLpCutoff = 0.02F private
cutoff frequency for smoothing lowpass
Definition at line 341 of file PitchFromBlock.cpp.
Referenced by CPitchTimeAuditory().
m_iNumBands
const int CPitchTimeAuditory::m_iNumBands = 20 static private
number of filter bands
Definition at line 335 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pCCcf
CCcf* CPitchTimeAuditory::m_pCCcf = 0 private
instance for correlation function computation
Definition at line 330 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pCFilterBank
CGammaToneFbIf* CPitchTimeAuditory::m_pCFilterBank = 0 private
instance of gammatone filterbank
Definition at line 337 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pfAcf
float* CPitchTimeAuditory::m_pfAcf = 0 private
acf result
Definition at line 331 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_pfSumAcf
float* CPitchTimeAuditory::m_pfSumAcf = 0 private
aggregated acf result
Definition at line 332 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
m_ppfProcBuff
float** CPitchTimeAuditory::m_ppfProcBuff = 0 private
temporary processing buffer
Definition at line 333 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAuditory(), and ~CPitchTimeAuditory().
The documentation for this class was generated from the following file:
PitchFromBlock.cpp