ACA: CNormalizeAudio Class Reference
CNormalizeAudio Class Reference
class for audio normalization offering three options
#include <ToolPreProc.h>
Public Member Functions
CNormalizeAudio (CAudioFileIf *pCAudioFile)
CNormalizeAudio (const float *pfAudioBuff, long long iAudioLength)
virtual ~CNormalizeAudio ()
void normalizeBlock (float *pfAudioBlock, long long iNumSamples)
Static Public Member Functions
static void normalizeSignal (float *pfAudio, long long iNumSamples)
Private Member Functions
CNormalizeAudio ()
CNormalizeAudio (const CNormalizeAudio &that)
CNormalizeAudio & operator= (const CNormalizeAudio &c)
Private Attributes
float m_fScaleFactor
factor to normalize
Detailed Description
class for audio normalization offering three options
normalize an audio file during blockwise reading with normalizeBlock (requires instance with audio file)
normalize an audio vector with blockwise reading with normalizeBlock (requires instance with buffer)
normalize an entire vector at once with normalizeSignal (static function does not require instance)
Definition at line 46 of file ToolPreProc.h.
Constructor & Destructor Documentation
CNormalizeAudio() [1/4]
CNormalizeAudio::CNormalizeAudio (CAudioFileIf * pCAudioFile) inline explicit
Definition at line 49 of file ToolPreProc.h.
                                                        :
        m_fScaleFactor(1.F)
    {
        assert(pCAudioFile);
        CAudioFileIf::FileSpec_t stFileSpec;
        pCAudioFile->getFileSpec(stFileSpec);
        const int iBlockLength = 4096;
        float fGlobalMax = 0.F;
        long long iCurrPos = 0;
        float** ppfAudioData = 0;
        // alloc read buffer
        ppfAudioData = new float *[stFileSpec.iNumChannels];
        for (auto c = 0; c < stFileSpec.iNumChannels; c++)
            ppfAudioData[c] = new float [iBlockLength];
        // store current file position for resetting later
        pCAudioFile->getPosition(iCurrPos);
        pCAudioFile->getFileSpec(stFileSpec);
        //
        pCAudioFile->setPosition(0.);
        while (!pCAudioFile->isEof())
        {
            // set block length variable
            long long iNumSamples = iBlockLength;
            float fMax = 0;
            // read data (iNumOfFrames might be updated!)
            pCAudioFile->readData(ppfAudioData, iNumSamples);
            //downmix if multichannel
            CPreProc::downmix(ppfAudioData[0], ppfAudioData, stFileSpec.iNumChannels, iNumSamples);
            // find max
            fMax = CVectorFloat::getMax(ppfAudioData[0], iNumSamples, true);
            if (fMax > fGlobalMax)
                fGlobalMax = fMax;
        }
        if (fGlobalMax > 0)
            m_fScaleFactor = 1.F / fGlobalMax;
        // reset file read position
        pCAudioFile->setPosition(iCurrPos);
        //free internal memory
        for (auto c = 0; c < stFileSpec.iNumChannels; c++)
            delete[] ppfAudioData[c];
        delete[] ppfAudioData;
        ppfAudioData = 0;
    };
References CPreProc::downmix(), CAudioFileIf::getFileSpec(), CVectorFloat::getMax(), CAudioFileIf::getPosition(), CAudioFileIf::FileSpec_t::iNumChannels, CAudioFileIf::isEof(), m_fScaleFactor, CAudioFileIf::readData(), and CAudioFileIf::setPosition().
CNormalizeAudio() [2/4]
CNormalizeAudio::CNormalizeAudio (const float * pfAudioBuff, long long iAudioLength) inline
Definition at line 103 of file ToolPreProc.h.
                                                                      :
        m_fScaleFactor(1.F)
    {
        assert(pfAudioBuff);
        assert(iAudioLength > 0);
        float fGlobalMax = CVectorFloat::getMax(pfAudioBuff, iAudioLength, true);
        if (fGlobalMax > 0)
            m_fScaleFactor = 1.F / fGlobalMax;
    };
References CVectorFloat::getMax(), and m_fScaleFactor.
~CNormalizeAudio()
virtual CNormalizeAudio::~CNormalizeAudio () inline virtual
Definition at line 113 of file ToolPreProc.h.
{};
CNormalizeAudio() [3/4]
CNormalizeAudio::CNormalizeAudio () private
CNormalizeAudio() [4/4]
CNormalizeAudio::CNormalizeAudio (const CNormalizeAudio & that) private
Member Function Documentation
normalizeBlock()
void CNormalizeAudio::normalizeBlock (float * pfAudioBlock, long long iNumSamples) inline
performs the normalization on a buffer after previous file parsing to get the maximum
Parameters
pfAudioBlock audio data, to be over-written
iNumSamples legnth of pfAudio
Returns
Error_t
Definition at line 120 of file ToolPreProc.h.
    {
        assert(pfAudioBlock);
        assert(iNumSamples > 0);
        CVectorFloat::mulC_I(pfAudioBlock, m_fScaleFactor, iNumSamples);
    };
References m_fScaleFactor, and CVectorFloat::mulC_I().
Referenced by CFeatureIf::compFeature1Dim(), CFeatureIf::compFeatureNDim(), CNoveltyIf::compNovelty(), CSpectrogramIf::computeMagSpectrum_(), and CGammaToneFbIf::process().
normalizeSignal()
static void CNormalizeAudio::normalizeSignal (float * pfAudio, long long iNumSamples) inline static
performs the normalization inplace on a buffer
Parameters
pfAudio audio data, to be over-written
iNumSamples legnth of pfAudio
Returns
Error_t
Definition at line 133 of file ToolPreProc.h.
    {
        assert(pfAudio);
        assert(iNumSamples > 0);
        float fMax = CVectorFloat::getMax(pfAudio, iNumSamples, true);
        if (fMax > 0)
            CVectorFloat::mulC_I(pfAudio, 1.F / fMax, iNumSamples);
        return;
    }
References CVectorFloat::getMax(), and CVectorFloat::mulC_I().
Referenced by CBeatHistoIf::compBeatHisto().
operator=()
CNormalizeAudio & CNormalizeAudio::operator= (const CNormalizeAudio & c) private
Member Data Documentation
m_fScaleFactor
float CNormalizeAudio::m_fScaleFactor private
factor to normalize
Definition at line 149 of file ToolPreProc.h.
Referenced by CNormalizeAudio(), and normalizeBlock().
The documentation for this class was generated from the following file:
ToolPreProc.h