ACA: CFeatureSpectralFlux Class Reference
CFeatureSpectralFlux Class Reference
class for computation of the spectral flux
Public Member Functions
CFeatureSpectralFlux (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureSpectralFlux ()
Error_t compFeature (float *pfFeature, const float *pfIn) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Member Functions
CFeatureSpectralFlux ()
CFeatureSpectralFlux (const CFeatureSpectralFlux &that)
disallow copy construction
CFeatureSpectralFlux & operator= (const CFeatureSpectralFlux &c)
Private Attributes
float * m_pfPrevSpec = 0
memory of previous spectrum
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume everything's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
class for computation of the spectral flux
Definition at line 343 of file FeatureFromBlock.cpp.
Constructor & Destructor Documentation
CFeatureSpectralFlux() [1/3]
CFeatureSpectralFlux::CFeatureSpectralFlux (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 346 of file FeatureFromBlock.cpp.
                                                                                              : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        CVector::alloc(m_pfPrevSpec, m_iDataLength);
        CVector::setZero(m_pfPrevSpec, m_iDataLength);
    };
References CVector::alloc(), CFeatureFromBlockIf::CFeatureFromBlockIf(), CFeatureFromBlockIf::m_iDataLength, m_pfPrevSpec, and CVector::setZero().
Referenced by CFeatureSpectralFlux(), and operator=().
~CFeatureSpectralFlux()
virtual CFeatureSpectralFlux::~CFeatureSpectralFlux () inline virtual
Definition at line 352 of file FeatureFromBlock.cpp.
    {
        CVector::free(m_pfPrevSpec);
    };
References CVector::free(), and m_pfPrevSpec.
CFeatureSpectralFlux() [2/3]
CFeatureSpectralFlux::CFeatureSpectralFlux () inline private
Definition at line 367 of file FeatureFromBlock.cpp.
{};
CFeatureSpectralFlux() [3/3]
CFeatureSpectralFlux::CFeatureSpectralFlux (const CFeatureSpectralFlux & that) private
disallow copy construction
References CFeatureSpectralFlux().
Member Function Documentation
compFeature()
Error_t CFeatureSpectralFlux::compFeature (float * pfFeature, const float * pfIn) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfIn input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 357 of file FeatureFromBlock.cpp.
    {
        *pfFeature = compFeatureSpectralFlux(pfIn, m_pfPrevSpec, m_iDataLength, m_fSampleRate);
        CVector::copy(m_pfPrevSpec, pfIn, m_iDataLength);
        return Error_t::kNoError;
    };
References CFeatureFromBlockIf::compFeatureSpectralFlux(), CVector::copy(), kNoError, CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, and m_pfPrevSpec.
operator=()
CFeatureSpectralFlux & CFeatureSpectralFlux::operator= (const CFeatureSpectralFlux & c) private
References CFeatureSpectralFlux().
Member Data Documentation
m_pfPrevSpec
float* CFeatureSpectralFlux::m_pfPrevSpec = 0 private
memory of previous spectrum
Definition at line 371 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralFlux(), compFeature(), and ~CFeatureSpectralFlux().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp