ACA: CFeatureTimePeakEnvelope Class Reference
CFeatureTimePeakEnvelope Class Reference
class for computation of the peak envelope
Public Member Functions
CFeatureTimePeakEnvelope (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureTimePeakEnvelope ()
Error_t compFeature (float *pfFeature, const float *pfIn) override
int getFeatureDimensions () const override
Public Member Functions inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t getFeatureIdx () const
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Types
enum PeakType_t { kBlockMax , kPpmMax , kNumPeakTypes }
enum PpmFilters_t { kAttack , kRelease , kNumPpmFilters }
Private Member Functions
CFeatureTimePeakEnvelope ()
float ppm_I (float fIn)
Private Attributes
const float m_afIntegrationTimeInS [kNumPpmFilters] = { .01F, 1.5F }
integration times for filter initialization
float m_afAlpha [kNumPpmFilters] = { 0,0 }
filter coefficients
float m_fFilterBuff = 0.F
internal filter memory
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume everything's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
class for computation of the peak envelope
Definition at line 837 of file FeatureFromBlock.cpp.
Member Enumeration Documentation
PeakType_t
enum CFeatureTimePeakEnvelope::PeakType_t private
Enumerator
kBlockMax
kPpmMax
kNumPeakTypes
Definition at line 873 of file FeatureFromBlock.cpp.
    {
        kBlockMax,
        kPpmMax,
        kNumPeakTypes
    };
PpmFilters_t
enum CFeatureTimePeakEnvelope::PpmFilters_t private
Enumerator
kAttack
kRelease
kNumPpmFilters
Definition at line 881 of file FeatureFromBlock.cpp.
    {
        kAttack,
        kRelease,
        kNumPpmFilters
    };
Constructor & Destructor Documentation
CFeatureTimePeakEnvelope() [1/2]
CFeatureTimePeakEnvelope::CFeatureTimePeakEnvelope (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 840 of file FeatureFromBlock.cpp.
                                                                                                  : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        for (auto i = 0; i < kNumPpmFilters; i++)
            m_afAlpha[i] = CSinglePoleLp::calcFilterParam(m_afIntegrationTimeInS[i], fSampleRate);
    };
References CSinglePoleLp::calcFilterParam(), CFeatureFromBlockIf::CFeatureFromBlockIf(), kNumPpmFilters, m_afAlpha, and m_afIntegrationTimeInS.
~CFeatureTimePeakEnvelope()
virtual CFeatureTimePeakEnvelope::~CFeatureTimePeakEnvelope () inline virtual
Definition at line 846 of file FeatureFromBlock.cpp.
{};
CFeatureTimePeakEnvelope() [2/2]
CFeatureTimePeakEnvelope::CFeatureTimePeakEnvelope () inline private
Definition at line 871 of file FeatureFromBlock.cpp.
{};
Member Function Documentation
compFeature()
Error_t CFeatureTimePeakEnvelope::compFeature (float * pfFeature, const float * pfIn) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfIn input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 848 of file FeatureFromBlock.cpp.
    {
        // extract 1st variant: maximum per block
        pfFeature[kBlockMax] = compFeatureTimePeakEnvelope(pfIn, m_iDataLength, m_fSampleRate);
        // extract 2nd variant: maximum of ppm
        pfFeature[kPpmMax] = 0;
        for (auto i = 0; i < m_iDataLength; i++)
        {
            float fOut = ppm_I(pfIn[i]);
            if (fOut > pfFeature[kPpmMax])
                pfFeature[kPpmMax] = fOut;
        }
        return Error_t::kNoError;
    };
References CFeatureFromBlockIf::compFeatureTimePeakEnvelope(), kBlockMax, kNoError, kPpmMax, CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, and ppm_I().
getFeatureDimensions()
int CFeatureTimePeakEnvelope::getFeatureDimensions () const inline override virtual
returns size of output feature (1 in most cases)
Returns
int
Reimplemented from CFeatureFromBlockIf.
Definition at line 865 of file FeatureFromBlock.cpp.
    {
        return kNumPeakTypes;
    }
References kNumPeakTypes.
ppm_I()
float CFeatureTimePeakEnvelope::ppm_I (float fIn) inline private
Definition at line 889 of file FeatureFromBlock.cpp.
    {
        float fOut = 0;
        fIn = std::abs(fIn);
        // check release vs. attack phase
        if (m_fFilterBuff > fIn)
            fOut = m_afAlpha[kRelease] * m_fFilterBuff;
        else
            fOut = (1.F - m_afAlpha[kAttack]) * fIn + m_afAlpha[kAttack] * m_fFilterBuff;
        m_fFilterBuff = fOut;
        return fOut;
    }
References kAttack, kRelease, m_afAlpha, and m_fFilterBuff.
Referenced by compFeature().
Member Data Documentation
m_afAlpha
float CFeatureTimePeakEnvelope::m_afAlpha[kNumPpmFilters] = { 0,0 } private
filter coefficients
Definition at line 907 of file FeatureFromBlock.cpp.
{ 0,0 }; //!< filter coefficients
Referenced by CFeatureTimePeakEnvelope(), and ppm_I().
m_afIntegrationTimeInS
const float CFeatureTimePeakEnvelope::m_afIntegrationTimeInS[kNumPpmFilters] = { .01F, 1.5F } private
integration times for filter initialization
Definition at line 906 of file FeatureFromBlock.cpp.
{ .01F, 1.5F }; //!< integration times for filter initialization
Referenced by CFeatureTimePeakEnvelope().
m_fFilterBuff
float CFeatureTimePeakEnvelope::m_fFilterBuff = 0.F private
internal filter memory
Definition at line 908 of file FeatureFromBlock.cpp.
Referenced by ppm_I().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp