ACA: CPitchSpectralHps Class Reference
CPitchSpectralHps Class Reference
class for computation of the pitch via the hps of the magnitude spectrum
Public Member Functions
CPitchSpectralHps (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchSpectralHps ()
float compF0 (const float *pfIn) override
Public Member Functions inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t getPitchExtractorIdx () const
virtual float compF0 (const float *pfIn)=0
Private Member Functions
CPitchSpectralHps ()
CPitchSpectralHps (const CPitchSpectralHps &that)
disallow copy construction
CPitchSpectralHps & operator= (const CPitchSpectralHps &c)
Private Attributes
float * m_pfProcBuff = 0
temporary buffer for processing
int m_iOrder = 4
HPS order.
float m_fMin = 300.F
minimum frequency
Additional Inherited Members
Static Public Member Functions inherited from CPitchFromBlockIf
static Error_t create (CPitchFromBlockIf *&pCInstance, CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CPitchFromBlockIf *&pCInstance)
Protected Member Functions inherited from CPitchFromBlockIf
CPitchFromBlockIf ()
CPitchFromBlockIf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchFromBlockIf ()
CPitchFromBlockIf (const CPitchFromBlockIf &that)
CPitchFromBlockIf & operator= (const CPitchFromBlockIf &c)
Protected Attributes inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t m_ePitchIdx = CPitchIf::kNumPitchExtractors
index of Pitch to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
Detailed Description
class for computation of the pitch via the hps of the magnitude spectrum
Definition at line 93 of file PitchFromBlock.cpp.
Constructor & Destructor Documentation
CPitchSpectralHps() [1/3]
CPitchSpectralHps::CPitchSpectralHps (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate) inline
Definition at line 96 of file PitchFromBlock.cpp.
                                                                                               : CPitchFromBlockIf(ePitchIdx, iDataLength, fSampleRate)
    {
        CVector::alloc(m_pfProcBuff, m_iDataLength);
    }
References CVector::alloc(), CPitchFromBlockIf::m_iDataLength, and m_pfProcBuff.
~CPitchSpectralHps()
virtual CPitchSpectralHps::~CPitchSpectralHps () inline virtual
Definition at line 101 of file PitchFromBlock.cpp.
    {
        CVector::free(m_pfProcBuff);
    }
References CVector::free(), and m_pfProcBuff.
CPitchSpectralHps() [2/3]
CPitchSpectralHps::CPitchSpectralHps () inline private
Definition at line 134 of file PitchFromBlock.cpp.
{};
CPitchSpectralHps() [3/3]
CPitchSpectralHps::CPitchSpectralHps (const CPitchSpectralHps & that) private
disallow copy construction
Member Function Documentation
compF0()
float CPitchSpectralHps::compF0 (const float * pfIn) inline override virtual
performs the PitchFromBlock computation
Parameters
pfIn input data of length iDataLength
Returns
float fF0InHz
Implements CPitchFromBlockIf.
Definition at line 106 of file PitchFromBlock.cpp.
    {
        assert(pfIn);
        float fTmp = 0.F;
        long long iMaxIdx = 0;
        int iMin = CUtil::float2int<int>(CConversion::convertFreq2Bin(m_fMin, (m_iDataLength - 1) * 2, m_fSampleRate));
        CVector::copy(m_pfProcBuff, pfIn, m_iDataLength);
        CVector::setZero(m_pfProcBuff, iMin);
        CVector::setZero(&m_pfProcBuff[m_iDataLength / m_iOrder], static_cast<long long>(m_iDataLength) - (m_iDataLength / m_iOrder));
        // do the actual product sum
        for (auto j = 2; j <= m_iOrder; j++)
        {
            for (auto k = 0; k < m_iDataLength / j; k++)
                m_pfProcBuff[k] *= pfIn[j * k];
        }
        // this could be restricted a bit, but is it worth it?
        CVector::findMax(m_pfProcBuff, fTmp, iMaxIdx, m_iDataLength);
        // sanity check
        if (fTmp <= 1e-30F)
            return 0.F;
        return CConversion::convertBin2Freq(iMaxIdx * 1.F, (m_iDataLength - 1) * 2, m_fSampleRate);
    };
References CConversion::convertBin2Freq(), CConversion::convertFreq2Bin(), CVector::copy(), CVector::findMax(), m_fMin, CPitchFromBlockIf::m_fSampleRate, CPitchFromBlockIf::m_iDataLength, m_iOrder, m_pfProcBuff, and CVector::setZero().
operator=()
CPitchSpectralHps & CPitchSpectralHps::operator= (const CPitchSpectralHps & c) private
Member Data Documentation
m_fMin
float CPitchSpectralHps::m_fMin = 300.F private
minimum frequency
Definition at line 140 of file PitchFromBlock.cpp.
Referenced by compF0().
m_iOrder
int CPitchSpectralHps::m_iOrder = 4 private
HPS order.
Definition at line 139 of file PitchFromBlock.cpp.
Referenced by compF0().
m_pfProcBuff
float* CPitchSpectralHps::m_pfProcBuff = 0 private
temporary buffer for processing
Definition at line 138 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchSpectralHps(), and ~CPitchSpectralHps().
The documentation for this class was generated from the following file:
PitchFromBlock.cpp