ACA: CFeatureSpectralMfccs Class Reference
CFeatureSpectralMfccs Class Reference
class for computation of the mfccs
Public Member Functions
CFeatureSpectralMfccs (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureSpectralMfccs ()
Error_t compFeature (float *pfFeature, const float *pfIn) override
int getFeatureDimensions () const override
bool hasAdditionalParam () const override
Error_t setAdditionalParam (float fParamValue) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfIn)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Member Functions
CFeatureSpectralMfccs ()
CFeatureSpectralMfccs (const CFeatureSpectralMfccs &that)
disallow copy construction
CFeatureSpectralMfccs & operator= (const CFeatureSpectralMfccs &c)
void genMfccFilters_ ()
void genDctMat_ (int iNumCoeffs)
void allocDctMat_ (int iNumCoeffs)
void deleteDctMat_ ()
Private Attributes
const int m_iNumBands = 40
number of mel bands
int m_iNumMfcCoeffs = 13
number of dct coefficients to extract
float ** m_ppfH = 0
filter bank matrix
float ** m_ppfDct = 0
dct matrix
float * m_pfMelSpec = 0
mel-transformed spectrum
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume everything's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
class for computation of the mfccs
Definition at line 376 of file FeatureFromBlock.cpp.
Constructor & Destructor Documentation
CFeatureSpectralMfccs() [1/3]
CFeatureSpectralMfccs::CFeatureSpectralMfccs (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 379 of file FeatureFromBlock.cpp.
                                                                                               : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        // alloc transfer function memory
        CMatrix::alloc(m_ppfH, m_iNumBands, iDataLength);
        // init MFCC filters
        genMfccFilters_();
        // init dct transform
        genDctMat_(m_iNumMfcCoeffs);
        CVector::alloc(m_pfMelSpec, m_iNumBands);
    }
References CVector::alloc(), CMatrix::alloc(), genDctMat_(), genMfccFilters_(), m_iNumBands, m_iNumMfcCoeffs, m_pfMelSpec, and m_ppfH.
~CFeatureSpectralMfccs()
virtual CFeatureSpectralMfccs::~CFeatureSpectralMfccs () inline virtual
Definition at line 393 of file FeatureFromBlock.cpp.
    {
        CMatrix::free(m_ppfH, m_iNumBands);
        deleteDctMat_();
        CVector::free(m_pfMelSpec);
    }
References deleteDctMat_(), CVector::free(), CMatrix::free(), m_iNumBands, m_pfMelSpec, and m_ppfH.
CFeatureSpectralMfccs() [2/3]
CFeatureSpectralMfccs::CFeatureSpectralMfccs () inline private
Definition at line 441 of file FeatureFromBlock.cpp.
{};
CFeatureSpectralMfccs() [3/3]
CFeatureSpectralMfccs::CFeatureSpectralMfccs (const CFeatureSpectralMfccs & that) private
disallow copy construction
Member Function Documentation
allocDctMat_()
void CFeatureSpectralMfccs::allocDctMat_ (int iNumCoeffs) inline private
Definition at line 507 of file FeatureFromBlock.cpp.
    {
        if (m_ppfDct)
            deleteDctMat_();
        CMatrix::alloc(m_ppfDct, iNumCoeffs, m_iNumBands);
    }
References CMatrix::alloc(), deleteDctMat_(), m_iNumBands, and m_ppfDct.
Referenced by genDctMat_().
compFeature()
Error_t CFeatureSpectralMfccs::compFeature (float * pfFeature, const float * pfIn) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfIn input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 402 of file FeatureFromBlock.cpp.
    {
        assert(pfFeature);
        assert(pfIn);
        CVector::setZero(pfFeature, m_iNumMfcCoeffs);
        // compute mel spectrum
        for (auto c = 0; c < m_iNumBands; c++)
            m_pfMelSpec[c] = std::log10(CVector::mulScalar(m_ppfH[c], pfIn, m_iDataLength) + 1e-20F);
        // compute dct
        for (auto j = 0; j < m_iNumMfcCoeffs; j++)
            pfFeature[j] = CVector::mulScalar(m_ppfDct[j], m_pfMelSpec, m_iNumBands);
        return Error_t::kNoError;
    };
References CFeatureFromBlockIf::m_iDataLength, m_iNumBands, m_iNumMfcCoeffs, m_pfMelSpec, m_ppfDct, m_ppfH, CVector::mulScalar(), and CVector::setZero().
deleteDctMat_()
void CFeatureSpectralMfccs::deleteDctMat_ () inline private
Definition at line 514 of file FeatureFromBlock.cpp.
    {
        CMatrix::free(m_ppfDct, m_iNumMfcCoeffs);
    }
References CMatrix::free(), m_iNumMfcCoeffs, and m_ppfDct.
Referenced by allocDctMat_(), and ~CFeatureSpectralMfccs().
genDctMat_()
void CFeatureSpectralMfccs::genDctMat_ (int iNumCoeffs) inline private
Definition at line 492 of file FeatureFromBlock.cpp.
    {
        allocDctMat_(iNumCoeffs);
        for (auto c = 0; c < iNumCoeffs; c++)
        {
            for (auto b = 0; b < m_iNumBands; b++)
                m_ppfDct[c][b] = static_cast<float>(std::cos(c * (2. * b + 1) * M_PI / 2. / m_iNumBands));
            CVector::mulC_I(m_ppfDct[c], 1 / std::sqrt(m_iNumBands / 2.F), m_iNumBands);
        }
        CVector::mulC_I(m_ppfDct[0], 1.F / std::sqrt(2.f), m_iNumBands);
        m_iNumMfcCoeffs = iNumCoeffs;
    }
References allocDctMat_(), m_iNumBands, m_iNumMfcCoeffs, M_PI, m_ppfDct, and CVector::mulC_I().
Referenced by CFeatureSpectralMfccs(), and setAdditionalParam().
genMfccFilters_()
void CFeatureSpectralMfccs::genMfccFilters_ () inline private
< Check me
Definition at line 445 of file FeatureFromBlock.cpp.
    {
        const double dFreq = 400. / 3.;
        const int iNumLinFilters = 13;
        const double dLinSpacing = 200. / 3.,
            dLogSpacing = 1.0711703; // note sure where this mel resolution comes from exactly
        assert(m_iNumBands > iNumLinFilters);
        double adBoundFreqs[3] = { dFreq,
            dFreq + dLinSpacing,
            dFreq + 2. * dLinSpacing };
        int aiBoundIdx[3] = { static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[0]), (m_iDataLength - 1) * 2, m_fSampleRate)),
            static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[1]), (m_iDataLength - 1) * 2, m_fSampleRate)),
            static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[2]), (m_iDataLength - 1) * 2, m_fSampleRate)) };
        for (auto c = 0; c < m_iNumBands; c++)
        {
            double dFilterAmp = 2. / (adBoundFreqs[2] - adBoundFreqs[0]);
            // upward slope
            for (auto k = aiBoundIdx[0]; k <= aiBoundIdx[1]; k++)
            {
                float fFreqk = CConversion::convertBin2Freq(1.F * k, (m_iDataLength - 1) * 2, m_fSampleRate);
                if ((fFreqk - adBoundFreqs[0]) <= 0.F)
                    continue;
                m_ppfH[c][k] = static_cast<float>(dFilterAmp * (fFreqk - adBoundFreqs[0]) / (adBoundFreqs[1] - adBoundFreqs[0]));
                assert(m_ppfH[c][k] >= 0);
            }
            // downward slope
            for (auto k = aiBoundIdx[1] + 1; k <= aiBoundIdx[2]; k++)
            {
                float fFreqk = CConversion::convertBin2Freq(1.F * k, (m_iDataLength - 1) * 2, m_fSampleRate);
                m_ppfH[c][k] = static_cast<float>(dFilterAmp * (adBoundFreqs[2] - fFreqk) / (adBoundFreqs[2] - adBoundFreqs[1]));
                assert(m_ppfH[c][k] >= 0);
            }
            // proceed to next band
            adBoundFreqs[0] = adBoundFreqs[1];
            adBoundFreqs[1] = adBoundFreqs[2];
            adBoundFreqs[2] = (c < iNumLinFilters - 3) ? adBoundFreqs[1] + dLinSpacing : adBoundFreqs[2] * dLogSpacing; //!< Check me
            aiBoundIdx[0] = aiBoundIdx[1];
            aiBoundIdx[1] = aiBoundIdx[2];
            aiBoundIdx[2] = static_cast<int>(CConversion::convertFreq2Bin(static_cast<float>(adBoundFreqs[2]), (m_iDataLength - 1) * 2, m_fSampleRate));
        }
    }
References CConversion::convertBin2Freq(), CConversion::convertFreq2Bin(), CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, m_iNumBands, and m_ppfH.
Referenced by CFeatureSpectralMfccs().
getFeatureDimensions()
int CFeatureSpectralMfccs::getFeatureDimensions () const inline override virtual
returns size of output feature (1 in most cases)
Returns
int
Reimplemented from CFeatureFromBlockIf.
Definition at line 421 of file FeatureFromBlock.cpp.
    {
        return m_iNumMfcCoeffs;
    }
References m_iNumMfcCoeffs.
hasAdditionalParam()
bool CFeatureSpectralMfccs::hasAdditionalParam () const inline override virtual
returns true if there is an additional parameter
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 426 of file FeatureFromBlock.cpp.
    {
        return true;
    }
operator=()
CFeatureSpectralMfccs & CFeatureSpectralMfccs::operator= (const CFeatureSpectralMfccs & c) private
setAdditionalParam()
Error_t CFeatureSpectralMfccs::setAdditionalParam (float fParamValue) inline override virtual
returns true if there is an additional parameter
Parameters
fParamValue new parameter value
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 431 of file FeatureFromBlock.cpp.
    {
        if (fParamValue <= 0)
            return Error_t::kFunctionInvalidArgsError;
        genDctMat_(CUtil::float2int<int>(fParamValue));
        return Error_t::kNoError;
    }
References genDctMat_().
Member Data Documentation
m_iNumBands
const int CFeatureSpectralMfccs::m_iNumBands = 40 private
number of mel bands
Definition at line 519 of file FeatureFromBlock.cpp.
Referenced by allocDctMat_(), CFeatureSpectralMfccs(), compFeature(), genDctMat_(), genMfccFilters_(), and ~CFeatureSpectralMfccs().
m_iNumMfcCoeffs
int CFeatureSpectralMfccs::m_iNumMfcCoeffs = 13 private
number of dct coefficients to extract
Definition at line 520 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralMfccs(), compFeature(), deleteDctMat_(), genDctMat_(), and getFeatureDimensions().
m_pfMelSpec
float* CFeatureSpectralMfccs::m_pfMelSpec = 0 private
mel-transformed spectrum
Definition at line 525 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralMfccs(), compFeature(), and ~CFeatureSpectralMfccs().
m_ppfDct
float ** CFeatureSpectralMfccs::m_ppfDct = 0 private
dct matrix
Definition at line 523 of file FeatureFromBlock.cpp.
Referenced by allocDctMat_(), compFeature(), deleteDctMat_(), and genDctMat_().
m_ppfH
float** CFeatureSpectralMfccs::m_ppfH = 0 private
filter bank matrix
Definition at line 522 of file FeatureFromBlock.cpp.
Referenced by CFeatureSpectralMfccs(), compFeature(), genMfccFilters_(), and ~CFeatureSpectralMfccs().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp