ACA: CFeatureTimeRms Class Reference
CFeatureTimeRms Class Reference
class for computation of the rms
Public Member Functions
CFeatureTimeRms (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureTimeRms ()
Error_t compFeature (float *pfFeature, const float *pfIn) override
int getFeatureDimensions () const override
bool hasAdditionalParam () const override
Error_t setAdditionalParam (float fParamValue) override
Public Member Functions inherited from CFeatureFromBlockIf
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfIn)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Private Types
enum RmsType_t { kBlockRms , kLowpass , kNumRmsTypes }
Private Member Functions
CFeatureTimeRms ()
CFeatureTimeRms (const CFeatureTimeRms &that)
disallow copy construction
Private Attributes
CSinglePoleLp * m_pCSinglePole = 0
instance of low pass filter
float m_fIntegrationTimeInS = .3F
integration time for filter coeff calculation
Additional Inherited Members
Static Public Member Functions inherited from CFeatureFromBlockIf
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes inherited from CFeatureFromBlockIf
static const float m_kfFloatThresh = 1e-30F
below this we just assume everything's zero
Protected Member Functions inherited from CFeatureFromBlockIf
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes inherited from CFeatureFromBlockIf
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
class for computation of the rms
Definition at line 913 of file FeatureFromBlock.cpp.
Member Enumeration Documentation
RmsType_t
enum CFeatureTimeRms::RmsType_t private
Enumerator
kBlockRms
kLowpass
kNumRmsTypes
Definition at line 969 of file FeatureFromBlock.cpp.
    {
        kBlockRms,
        kLowpass,
        kNumRmsTypes
    };
Constructor & Destructor Documentation
CFeatureTimeRms() [1/3]
CFeatureTimeRms::CFeatureTimeRms (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) inline
Definition at line 916 of file FeatureFromBlock.cpp.
                                                                                         : CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate)
    {
        CSinglePoleLp::create(m_pCSinglePole);
        m_pCSinglePole->setFilterParam(CSinglePoleLp::calcFilterParam(m_fIntegrationTimeInS, fSampleRate));
    };
References CSinglePoleLp::calcFilterParam(), CSinglePoleLp::create(), m_fIntegrationTimeInS, m_pCSinglePole, and CSinglePoleLp::setFilterParam().
~CFeatureTimeRms()
virtual CFeatureTimeRms::~CFeatureTimeRms () inline virtual
Definition at line 922 of file FeatureFromBlock.cpp.
    {
        CSinglePoleLp::destroy(m_pCSinglePole);
    };
References CSinglePoleLp::destroy(), and m_pCSinglePole.
CFeatureTimeRms() [2/3]
CFeatureTimeRms::CFeatureTimeRms () inline private
Definition at line 976 of file FeatureFromBlock.cpp.
{};
CFeatureTimeRms() [3/3]
CFeatureTimeRms::CFeatureTimeRms (const CFeatureTimeRms & that) private
disallow copy construction
Member Function Documentation
compFeature()
Error_t CFeatureTimeRms::compFeature (float * pfFeature, const float * pfIn) inline override virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfIn input data of length iDataLength
Returns
Error_t
Reimplemented from CFeatureFromBlockIf.
Definition at line 927 of file FeatureFromBlock.cpp.
    {
        // extract 1st variant: rms per block
        pfFeature[kBlockRms] = compFeatureTimeRms(pfIn, m_iDataLength, m_fSampleRate);
        // extract 2nd variant: rms from single pole
        // do inefficient sample based processing so we don't have to alloc extra memory
        pfFeature[kLowpass] = 0;
        for (auto i = 0; i < m_iDataLength; i++)
        {
            float fIn = pfIn[i] * pfIn[i];
            float fOut = 0;
            m_pCSinglePole->process(&fOut, &fIn, 1);
            if (fOut > pfFeature[kLowpass])
                pfFeature[kLowpass] = fOut;
        }
        pfFeature[kLowpass] = std::sqrt(pfFeature[kLowpass]);
        return Error_t::kNoError;
    };
References CFeatureFromBlockIf::compFeatureTimeRms(), kBlockRms, kLowpass, kNoError, CFeatureFromBlockIf::m_fSampleRate, CFeatureFromBlockIf::m_iDataLength, m_pCSinglePole, and CSinglePoleLp::process().
getFeatureDimensions()
int CFeatureTimeRms::getFeatureDimensions () const inline override virtual
returns size of output feature (1 in most cases)
Returns
int
Reimplemented from CFeatureFromBlockIf.
Definition at line 948 of file FeatureFromBlock.cpp.
    {
        return kNumRmsTypes;
    }
References kNumRmsTypes.
hasAdditionalParam()
bool CFeatureTimeRms::hasAdditionalParam () const inline override virtual
returns true if there is an additional parameter
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 953 of file FeatureFromBlock.cpp.
    {
        return true;
    }
setAdditionalParam()
Error_t CFeatureTimeRms::setAdditionalParam (float fParamValue) inline override virtual
returns true if there is an additional parameter
Parameters
fParamValue new parameter value
Returns
bool
Reimplemented from CFeatureFromBlockIf.
Definition at line 958 of file FeatureFromBlock.cpp.
    {
        if (fParamValue <= 0)
            return Error_t::kNoError;
        m_fIntegrationTimeInS = fParamValue;
        return Error_t::kNoError;
    }
References kNoError, and m_fIntegrationTimeInS.
Member Data Documentation
m_fIntegrationTimeInS
float CFeatureTimeRms::m_fIntegrationTimeInS = .3F private
integration time for filter coeff calculation
Definition at line 981 of file FeatureFromBlock.cpp.
Referenced by CFeatureTimeRms(), and setAdditionalParam().
m_pCSinglePole
CSinglePoleLp* CFeatureTimeRms::m_pCSinglePole = 0 private
instance of low pass filter
Definition at line 979 of file FeatureFromBlock.cpp.
Referenced by CFeatureTimeRms(), compFeature(), and ~CFeatureTimeRms().
The documentation for this class was generated from the following file:
FeatureFromBlock.cpp