ACA: CResample Class Reference
CResample Class Reference
class for simple interpolation/sample rate conversion
#include <ToolResample.h>
Public Member Functions
CResample (float fInSampleRate, float fOutSampleRate)
virtual ~CResample ()
long long getOutputLength (long long iNumInSamples) const
Error_t process (float *pfOut, const float *pfIn, long long iNumInSamples)
Static Public Member Functions
static Error_t interp1d (float *pfOut, const float *pfNewIdx, const float *pfIn, long long iNumOutSamples, long long iNumInSamples)
Private Member Functions
CResample (const CResample &that)
CResample & operator= (const CResample &c)
void compButterCoeffs_ (float *pfB, float *pfA, int iOrder, float fOmegaCutoff)
Private Attributes
float m_fInSampleRate = 0.F
sample rate of input
float m_fOutSampleRate = 0.F
sample rate of output
CFilter< float > * m_pCFilter = 0
low pass filter processing
Detailed Description
class for simple interpolation/sample rate conversion
Definition at line 11 of file ToolResample.h.
Constructor & Destructor Documentation
CResample() [1/2]
CResample::CResample (float fInSampleRate, float fOutSampleRate) inline explicit
Definition at line 72 of file ToolResample.h.
                                                                  :
        m_fInSampleRate(fInSampleRate),
        m_fOutSampleRate(fOutSampleRate)
    {
        assert(m_fInSampleRate > 0);
        assert(m_fOutSampleRate > 0);
        m_pCFilter = new CFilter<float>();
    }
References m_fInSampleRate, m_fOutSampleRate, and m_pCFilter.
~CResample()
virtual CResample::~CResample () inline virtual
Definition at line 82 of file ToolResample.h.
    {
        delete m_pCFilter;
    }
References m_pCFilter.
CResample() [2/2]
CResample::CResample (const CResample & that) private
Member Function Documentation
compButterCoeffs_()
void CResample::compButterCoeffs_ (float * pfB, float * pfA, int iOrder, float fOmegaCutoff) inline private
Definition at line 154 of file ToolResample.h.
    {
        assert(pfB);
        assert(pfA);
        assert(iOrder > 0);
        assert(fOmegaCutoff > 0 && fOmegaCutoff <= M_PI);
    }
getOutputLength()
long long CResample::getOutputLength (long long iNumInSamples) const inline
returns the length of the output in case of iNumInSamples as input
Returns
long long
Definition at line 91 of file ToolResample.h.
    {
        return CUtil::float2int<long long>(iNumInSamples/m_fInSampleRate*m_fOutSampleRate);
    }
References m_fInSampleRate, and m_fOutSampleRate.
Referenced by process().
interp1d()
static Error_t CResample::interp1d (float * pfOut, const float * pfNewIdx, const float * pfIn, long long iNumOutSamples, long long iNumInSamples) inline static
simple linear interpolation, static function can be used without instantiation
Parameters
pfOut buffer with interpolated output samples (user allocated of length iNumOutSamples)
pfNewIdx indication of location of outputs on the input index scale, e.g., if the output sample rate is 3x the input sample rate, this vector will start with 0, 0.33, 0.66, 1, 1.33, ...
pfIn original samples
iNumOutSamples length of pfOut and pfNewIdx
iNumInSamples length of pfIn
Returns
Error_t
Definition at line 24 of file ToolResample.h.
    {
        if (!pfNewIdx || !pfOut || !pfIn || iNumInSamples <= 0 || iNumOutSamples <= 0)
            return Error_t::kFunctionInvalidArgsError;
        long long iStart = 0,
            iEnd = iNumOutSamples - 1;
        // treat first samples
        while ((pfNewIdx[iStart] < 0) && (iStart < iNumOutSamples))
        {
            if (pfNewIdx[iStart] < -1)
                pfOut[iStart] = 0;
            else
            {
                int     iIdx = static_cast<int>(std::floor(pfNewIdx[iStart]));
                float   fFrac = pfNewIdx[iStart] - iIdx;
                pfOut[iStart] = fFrac * pfIn[0];
            }
            iStart++;
        }
        // treat last samples
        while ((pfNewIdx[iEnd] > iNumInSamples - 1) && (iEnd >= 0))
        {
            if (pfNewIdx[iEnd] > iNumInSamples)
                pfOut[iEnd] = 0;
            else
            {
                int     iIdx = static_cast<int>(std::floor(pfNewIdx[iEnd]));
                float   fFrac = pfNewIdx[iEnd] - iIdx;
                pfOut[iEnd] = (1 - fFrac) * pfIn[iNumInSamples - 1];
            }
            iEnd--;
        }
        // now go through the buffer
        for (auto i = iStart; i <= iEnd; i++)
        {
            int     iIdx = static_cast<int>(std::floor(pfNewIdx[i]));
            float   fFrac = pfNewIdx[i] - iIdx;
            pfOut[i] = (1 - fFrac) * pfIn[iIdx] + fFrac * pfIn[iIdx + 1];
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
Referenced by process().
operator=()
CResample & CResample::operator= (const CResample & c) private
process()
Error_t CResample::process (float * pfOut, const float * pfIn, long long iNumInSamples) inline
does the sample rate conversion (filtered linear interpolation)
Parameters
pfOut output buffer (to be written, user allocated, length see CResample::getOutputLength)
pfIn input buffer of length iNumInSamples
iNumInSamples length of input buffer
Returns
Error_t
Definition at line 102 of file ToolResample.h.
    {
        if (!pfOut || !pfIn || iNumInSamples <= 0)
            return Error_t::kFunctionInvalidArgsError;
        const int iOrder = 4;
        float fOmegaCutoff = (m_fOutSampleRate > m_fInSampleRate) ? m_fInSampleRate / m_fOutSampleRate : m_fOutSampleRate / m_fInSampleRate;
        // compute index axis
        long long iNumOutSamples = getOutputLength(iNumInSamples);
        float* pfOutIdx = 0;
        CVectorFloat::alloc(pfOutIdx, iNumOutSamples);
        for (auto i = 0; i < iNumOutSamples; i++)
            pfOutIdx[i] = i * m_fInSampleRate / m_fOutSampleRate;
        // compute butterworth low pass filter coefficients
        float aafCoeffs[2][iOrder+1] = { 0 };
        CButterLp::calcCoeffs(aafCoeffs[0], aafCoeffs[1], iOrder, .9F * fOmegaCutoff);
        m_pCFilter->init(aafCoeffs[0], aafCoeffs[1], iOrder+1);
        if (m_fOutSampleRate > m_fInSampleRate) // upsample
        {
            // interpolate
            interp1d(pfOut, pfOutIdx, pfIn, iNumOutSamples, iNumInSamples);
            // apply zero phase filter
            m_pCFilter->filtfilt(pfOut, pfOut, iNumOutSamples);
        }
        else // downsample
        {
            float* pfFiltered = 0;
            CVectorFloat::alloc(pfFiltered, iNumInSamples);
            // apply zero phase filter
            m_pCFilter->filtfilt(pfFiltered, pfIn, iNumInSamples);
            // interpolate
            interp1d(pfOut, pfOutIdx, pfFiltered, iNumOutSamples, iNumInSamples);
            CVectorFloat::free(pfFiltered);
        }
        // free internal memory
        CVectorFloat::free(pfOutIdx);
        return Error_t::kNoError;
    }
References CVectorFloat::alloc(), CButterLp::calcCoeffs(), CFilter< T >::filtfilt(), CVectorFloat::free(), getOutputLength(), CFilter< T >::init(), interp1d(), kFunctionInvalidArgsError, kNoError, m_fInSampleRate, m_fOutSampleRate, and m_pCFilter.
Member Data Documentation
m_fInSampleRate
float CResample::m_fInSampleRate = 0.F private
sample rate of input
Definition at line 162 of file ToolResample.h.
Referenced by CResample(), getOutputLength(), and process().
m_fOutSampleRate
float CResample::m_fOutSampleRate = 0.F private
sample rate of output
Definition at line 163 of file ToolResample.h.
Referenced by CResample(), getOutputLength(), and process().
m_pCFilter
CFilter<float>* CResample::m_pCFilter = 0 private
low pass filter processing
Definition at line 165 of file ToolResample.h.
Referenced by CResample(), process(), and ~CResample().
The documentation for this class was generated from the following file:
ToolResample.h