ACA: CPitchTimeAcf Class Reference
CPitchTimeAcf Class Reference
class for computation of the pitch via the acf of the time domain signal
Public Member Functions
CPitchTimeAcf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchTimeAcf ()
float compF0 (const float *pfIn) override
Public Member Functions inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t getPitchExtractorIdx () const
virtual float compF0 (const float *pfIn)=0
Private Member Functions
CPitchTimeAcf ()
CPitchTimeAcf (const CPitchTimeAcf &that)
disallow copy construction
CPitchTimeAcf & operator= (const CPitchTimeAcf &c)
Private Attributes
CCcf * m_pCCcf = 0
instance for correlation function computation
float * m_pfAcf = 0
acf result
float m_fMax = 2000.F
maximum frequency
const float m_fMinThresh = 0.35F
acf threshold for parsing
Additional Inherited Members
Static Public Member Functions inherited from CPitchFromBlockIf
static Error_t create (CPitchFromBlockIf *&pCInstance, CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CPitchFromBlockIf *&pCInstance)
Protected Member Functions inherited from CPitchFromBlockIf
CPitchFromBlockIf ()
CPitchFromBlockIf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate)
virtual ~CPitchFromBlockIf ()
CPitchFromBlockIf (const CPitchFromBlockIf &that)
CPitchFromBlockIf & operator= (const CPitchFromBlockIf &c)
Protected Attributes inherited from CPitchFromBlockIf
CPitchIf::PitchExtractors_t m_ePitchIdx = CPitchIf::kNumPitchExtractors
index of Pitch to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
Detailed Description
class for computation of the pitch via the acf of the time domain signal
Definition at line 145 of file PitchFromBlock.cpp.
Constructor & Destructor Documentation
CPitchTimeAcf() [1/3]
CPitchTimeAcf::CPitchTimeAcf (CPitchIf::PitchExtractors_t ePitchIdx, int iDataLength, float fSampleRate) inline
Definition at line 148 of file PitchFromBlock.cpp.
                                                                                           : CPitchFromBlockIf(ePitchIdx, iDataLength, fSampleRate)
    {
        m_pCCcf = new CCcf();
        m_pCCcf->init(iDataLength);
        CVector::alloc(m_pfAcf, m_pCCcf->getCcfLength(true));
    };
References CVector::alloc(), CCcf::getCcfLength(), CCcf::init(), m_pCCcf, and m_pfAcf.
~CPitchTimeAcf()
virtual CPitchTimeAcf::~CPitchTimeAcf () inline virtual
Definition at line 156 of file PitchFromBlock.cpp.
    {
        CVector::free(m_pfAcf);
        delete m_pCCcf;
        m_pCCcf = 0;
    };
References CVector::free(), m_pCCcf, and m_pfAcf.
CPitchTimeAcf() [2/3]
CPitchTimeAcf::CPitchTimeAcf () inline private
Definition at line 207 of file PitchFromBlock.cpp.
{};
CPitchTimeAcf() [3/3]
CPitchTimeAcf::CPitchTimeAcf (const CPitchTimeAcf & that) private
disallow copy construction
Member Function Documentation
compF0()
float CPitchTimeAcf::compF0 (const float * pfIn) inline override virtual
performs the PitchFromBlock computation
Parameters
pfIn input data of length iDataLength
Returns
float fF0InHz
Implements CPitchFromBlockIf.
Definition at line 164 of file PitchFromBlock.cpp.
    {
        assert(pfIn);
        int iEta = 0,
            iEtaMin = static_cast<int>(m_fSampleRate / m_fMax);
        m_pCCcf->compCcf(pfIn, pfIn, true);
        m_pCCcf->getCcf(m_pfAcf, true);
        // avoid main lobe
        while (m_pfAcf[iEta] > m_fMinThresh)
            iEta++;
        if (iEtaMin < iEta)
            iEtaMin = iEta;
        // only look after first minimum
        iEta = 0;
        while (m_pfAcf[iEta] > m_pfAcf[iEta + 1])
        {
            iEta++;
            if (iEta >= m_iDataLength)
                break;
        }
        if (iEta >= m_iDataLength)
            iEtaMin = 0;
        else if (iEtaMin < iEta)
            iEtaMin = iEta;
        // get the maximum given the constraints above
        float fMax = 0;
        long long iMax = -1;
        CVector::findMax(&m_pfAcf[iEtaMin], fMax, iMax, static_cast<long long>(m_iDataLength) - iEtaMin);
        if (fMax <= 0)
            return 0.F;
        return m_fSampleRate / (iMax + iEtaMin);
    };
References CCcf::compCcf(), CVector::findMax(), CCcf::getCcf(), m_fMax, m_fMinThresh, CPitchFromBlockIf::m_fSampleRate, CPitchFromBlockIf::m_iDataLength, m_pCCcf, and m_pfAcf.
operator=()
CPitchTimeAcf & CPitchTimeAcf::operator= (const CPitchTimeAcf & c) private
Member Data Documentation
m_fMax
float CPitchTimeAcf::m_fMax = 2000.F private
maximum frequency
Definition at line 214 of file PitchFromBlock.cpp.
Referenced by compF0().
m_fMinThresh
const float CPitchTimeAcf::m_fMinThresh = 0.35F private
acf threshold for parsing
Definition at line 215 of file PitchFromBlock.cpp.
Referenced by compF0().
m_pCCcf
CCcf* CPitchTimeAcf::m_pCCcf = 0 private
instance for correlation function computation
Definition at line 211 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAcf(), and ~CPitchTimeAcf().
m_pfAcf
float* CPitchTimeAcf::m_pfAcf = 0 private
acf result
Definition at line 212 of file PitchFromBlock.cpp.
Referenced by compF0(), CPitchTimeAcf(), and ~CPitchTimeAcf().
The documentation for this class was generated from the following file:
PitchFromBlock.cpp