ACA: CFft Class Reference
CFft Class Reference
class for FFT computation with windowing
#include <Fft.h>
Public Types
enum WindowFunction_t { kWindowSine , kWindowHann , kWindowHamming , kNumWindows }
enum Windowing_t { kNoWindow = 0x00L , kPreWindow = 0x01L , kPostWindow = 0x02L }
enum Length_t {
kLengthFft , kLengthData , kLengthMagnitude , kLengthPhase ,
kNumLengths
}
typedef float complex_t
Public Member Functions
CFft ()
virtual ~CFft ()
Error_t init (int iBlockLength, int iZeroPadFactor=1, WindowFunction_t eWindow=kWindowHann, Windowing_t eWindowing=kPreWindow)
Error_t reset ()
Error_t overrideWindow (const float *pfNewWindow)
Error_t getWindow (float *pfWindow) const
Error_t compFft (complex_t *pfSpectrum, const float *pfInput)
Error_t compInvFft (float *pfOutput, const complex_t *pfSpectrum)
Error_t getMagnitude (float *pfMag, const complex_t *pfSpectrum) const
Error_t getPhase (float *pfPhase, const complex_t *pfSpectrum) const
Error_t splitRealImag (float *pfReal, float *pfImag, const complex_t *pfSpectrum) const
Error_t mergeRealImag (complex_t *pfSpectrum, const float *pfReal, const float *pfImag) const
int getLength (Length_t eLengthIdx) const
float freq2bin (float fFreqInHz, float fSampleRateInHz) const
float bin2freq (int iBinIdx, float fSampleRateInHz) const
void conjugate_I (complex_t *pfFftResult) const
void multiply_I (complex_t *pfFftSrc1Dest, const complex_t *pfFftSrc2) const
Private Member Functions
CFft (const CFft &that)
CFft & operator= (const CFft &c)
Error_t allocMemory_ ()
Error_t freeMemory_ ()
Error_t computeWindow_ (WindowFunction_t eWindow)
Private Attributes
float * m_pfProcessBuff = 0
generic processing buffer
float * m_pfWindowBuff = 0
window function
int m_iDataLength = 0
length of data
int m_iFftLength = 0
length of FFT
Windowing_t m_ePrePostWindowOpt = kNoWindow
windowing option
bool m_bIsInitialized = false
flag indicating if the instance is initialized
Static Private Attributes
static const float m_Pi = static_cast<float>(M_PI)
just to have it as float
static const float m_Pi2 = static_cast<float>(M_PI_2)
just to have it as float
Detailed Description
class for FFT computation with windowing
Definition at line 8 of file Fft.h.
Member Typedef Documentation
complex_t
typedef float CFft::complex_t
Definition at line 11 of file Fft.h.
Member Enumeration Documentation
Length_t
enum CFft::Length_t
Enumerator
kLengthFft
length of the FFT
kLengthData
length of the input data
kLengthMagnitude
length of the magnitude spectrum
kLengthPhase
length of the phase spectrum
kNumLengths
Definition at line 103 of file Fft.h.
    {
        kLengthFft,             //!< length of the FFT
        kLengthData,            //!< length of the input data
        kLengthMagnitude,       //!< length of the magnitude spectrum
        kLengthPhase,           //!< length of the phase spectrum
        kNumLengths
    };
WindowFunction_t
enum CFft::WindowFunction_t
defines the window function to use – a custom window can also be used (
See also
overrideWindow)
Enumerator
kWindowSine
sinusoidal window
kWindowHann
von-Hann window
kWindowHamming
Hamming window.
kNumWindows
Definition at line 14 of file Fft.h.
    {
        //kWindowNone,            //!< rectangular window (see Windowing_t::kNoWindow)
        kWindowSine,            //!< sinusoidal window
        kWindowHann,            //!< von-Hann window
        kWindowHamming,         //!< Hamming window
        kNumWindows
    };
Windowing_t
enum CFft::Windowing_t
Enumerator
kNoWindow
do not apply any window
kPreWindow
apply window function before FFT
kPostWindow
apply window function after IFFT
Definition at line 23 of file Fft.h.
    {
        kNoWindow   = 0x00L,    //!< do not apply any window
        kPreWindow  = 0x01L,    //!< apply window function before FFT
        kPostWindow = 0x02L     //!< apply window function after IFFT
    };
Constructor & Destructor Documentation
CFft() [1/2]
CFft::CFft ()
Definition at line 14 of file Fft.cpp.
{
    reset ();
}
References reset().
~CFft()
CFft::~CFft () inline virtual
Definition at line 19 of file Fft.cpp.
{
    reset();
}
References reset().
CFft() [2/2]
CFft::CFft (const CFft & that) private
Member Function Documentation
allocMemory_()
Error_t CFft::allocMemory_ () private
Definition at line 257 of file Fft.cpp.
{
    CVector::alloc(m_pfProcessBuff, m_iFftLength);
    CVector::alloc(m_pfWindowBuff, m_iDataLength);
    if (!m_pfProcessBuff || !m_pfWindowBuff)
        return Error_t::kMemError;
    else
    {
        return Error_t::kNoError;
    }
}
References CVector::alloc(), kMemError, kNoError, m_iDataLength, m_iFftLength, m_pfProcessBuff, and m_pfWindowBuff.
Referenced by init().
bin2freq()
float CFft::bin2freq (int iBinIdx, float fSampleRateInHz) const
convert bin to frequency
Parameters
iBinIdx index of the FFT bin
fSampleRateInHz sample rate of the audio signal
Returns
frequency in Hz
Definition at line 221 of file Fft.cpp.
{
    return iBinIdx * fSampleRateInHz / m_iFftLength;
}
References m_iFftLength.
Referenced by CSpectrogramIf::getSpectrogramAxisVectors().
compFft()
Error_t CFft::compFft (complex_t * pfSpectrum, const float * pfInput)
perform the FFT
Parameters
pfSpectrum output result of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Parameters
pfInput input data of length iBlockLength (
See also
initInstance)
Returns
Error_t
Definition at line 91 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!pfInput || !pfSpectrum)
        return Error_t::kFunctionInvalidArgsError;
    // copy data to internal buffer
    CVector::copy(m_pfProcessBuff, pfInput, m_iDataLength);
    CVector::setZero(&m_pfProcessBuff[m_iDataLength], static_cast<long long>(m_iFftLength)-m_iDataLength);
    // apply window function
    if (m_ePrePostWindowOpt & kPreWindow)
        CVector::mul_I(m_pfProcessBuff, m_pfWindowBuff, m_iDataLength);
    // compute fft
    LaszloFft::realfft_split(m_pfProcessBuff, m_iFftLength);
    // copy data to output buffer
    CVector::copy(pfSpectrum, m_pfProcessBuff, m_iFftLength);
    return Error_t::kNoError;
}
References CVector::copy(), kFunctionInvalidArgsError, kNoError, kNotInitializedError, kPreWindow, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, m_iFftLength, m_pfProcessBuff, m_pfWindowBuff, CVector::mul_I(), LaszloFft::realfft_split(), and CVector::setZero().
Referenced by CBeatHistoIf::compBeatHisto(), CCcf::compCcf(), CChordIf::computeMagSpectrum_(), CFeatureIf::computeMagSpectrum_(), CNoveltyIf::computeMagSpectrum_(), CPitchIf::computeMagSpectrum_(), CFingerprint::computeMagSpectrum_(), and CSpectrogramIf::computeMagSpectrum_().
compInvFft()
Error_t CFft::compInvFft (float * pfOutput, const complex_t * pfSpectrum)
perform IFFT
Parameters
pfOutput time domain output signal of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Parameters
pfSpectrum input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 115 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // copy data to internal buffer
    CVector::copy(m_pfProcessBuff, pfSpectrum, m_iFftLength);
    // compute ifft
    LaszloFft::irealfft_split(m_pfProcessBuff, m_iFftLength);
    // apply window function
    if (m_ePrePostWindowOpt & kPostWindow)
        CVector::mul_I(m_pfProcessBuff, m_pfWindowBuff, m_iDataLength);
    // copy data to output buffer
    CVector::copy(pfOutput, m_pfProcessBuff, m_iFftLength);
    return Error_t::kNoError;
}
References CVector::copy(), LaszloFft::irealfft_split(), kNoError, kNotInitializedError, kPostWindow, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, m_iFftLength, m_pfProcessBuff, m_pfWindowBuff, and CVector::mul_I().
Referenced by CCcf::compCcf().
computeWindow_()
Error_t CFft::computeWindow_ (WindowFunction_t eWindow) private
Definition at line 281 of file Fft.cpp.
{
    int i;
    // note that these windows are periodic, not symmetric
    switch (eWindow)
    {
    case kWindowSine:
    {
        for (i = 0; i < m_iDataLength; i++)
        {
            m_pfWindowBuff[i] = sinf((i * m_Pi) / (m_iDataLength + 1));
        }
        break;
    }
    case kWindowHann:
    {
        for (i = 0; i < m_iDataLength; i++)
        {
            m_pfWindowBuff[i] = .5F * (1.F - cosf((i * 2.F * m_Pi) / (m_iDataLength + 1)));
        }
        break;
    }
    case kWindowHamming:
    {
        for (i = 0; i < m_iDataLength; i++)
        {
            m_pfWindowBuff[i] = .54F - .46F * cosf((i * 2.F * m_Pi) / (m_iDataLength + 1));
        }
        break;
    }
    default:
    case kNumWindows:
    {
        return Error_t::kFunctionInvalidArgsError;
    }
    }
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, kNoError, kNumWindows, kWindowHamming, kWindowHann, kWindowSine, m_iDataLength, m_pfWindowBuff, and m_Pi.
Referenced by init().
conjugate_I()
void CFft::conjugate_I (complex_t * pfFftResult) const
Definition at line 226 of file Fft.cpp.
{
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    CVector::mulC_I(&pfFftResult[(m_iFftLength>>1)+1], -1.F, static_cast<long long>(m_iFftLength>>1)-1);
}
References m_iFftLength, and CVector::mulC_I().
Referenced by CCcf::compCcf().
freeMemory_()
Error_t CFft::freeMemory_ () private
Definition at line 270 of file Fft.cpp.
{
    CVector::free(m_pfProcessBuff);
    CVector::free(m_pfWindowBuff);
    m_pfProcessBuff = 0;
    m_pfWindowBuff  = 0;
    return Error_t::kNoError;
}
References CVector::free(), kNoError, m_pfProcessBuff, and m_pfWindowBuff.
Referenced by reset().
freq2bin()
float CFft::freq2bin (float fFreqInHz, float fSampleRateInHz) const
convert frequency to bin value
Parameters
fFreqInHz frequency to convert
fSampleRateInHz sample rate of the audio signal
Returns
index (not quantized to integer)
Definition at line 216 of file Fft.cpp.
{
    return fFreqInHz / fSampleRateInHz * m_iFftLength;
}
References m_iFftLength.
Referenced by CSpectrogramIf::generateMelFb_().
getLength()
int CFft::getLength (Length_t eLengthIdx) const
return length of spectrum
Parameters
eLengthIdx spectrum type
Returns
int
Definition at line 322 of file Fft.cpp.
{
    switch (eLengthIdx)
    {
    case kLengthFft:
        return m_iFftLength;
    case kLengthData:
        return m_iDataLength;
    case kLengthMagnitude:
    case kLengthPhase:
        return m_iFftLength/2+1;
    default:
    case kNumLengths:
        return -1;
    }
}
References kLengthData, kLengthFft, kLengthMagnitude, kLengthPhase, kNumLengths, m_iDataLength, and m_iFftLength.
Referenced by CInstFreq::CInstFreq(), CSpectrogramIf::compMelSpectrogram(), CSpectrogramIf::compSpectrogram(), CChordIf::computeMagSpectrum_(), CFeatureIf::computeMagSpectrum_(), CNoveltyIf::computeMagSpectrum_(), CPitchIf::computeMagSpectrum_(), CFingerprint::computeMagSpectrum_(), CSpectrogramIf::generateMelFb_(), CChordIf::init_(), CFingerprint::init_(), CFeatureIf::init_(), CNoveltyIf::init_(), and CPitchIf::init_().
getMagnitude()
Error_t CFft::getMagnitude (float * pfMag, const complex_t * pfSpectrum) const
extract magnitude spectrum from complex values
Parameters
pfMag resulting magnitude spectrum of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
pfSpectrum input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 136 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    // no imaginary part at these bins
    pfMag[0]        = std::abs(pfSpectrum[0]);
    pfMag[iNyq]     = std::abs(pfSpectrum[iNyq]);
    for (int i = 1; i < iNyq; i++)
    {
        int iImagIdx    = m_iFftLength - i;
        pfMag[i]        = sqrtf(pfSpectrum[i]*pfSpectrum[i] + pfSpectrum[iImagIdx]*pfSpectrum[iImagIdx]);
    }
    return Error_t::kNoError;
}
References kNoError, kNotInitializedError, m_bIsInitialized, and m_iFftLength.
Referenced by CBeatHistoIf::compBeatHisto(), CChordIf::computeMagSpectrum_(), CFeatureIf::computeMagSpectrum_(), CNoveltyIf::computeMagSpectrum_(), CPitchIf::computeMagSpectrum_(), CFingerprint::computeMagSpectrum_(), and CSpectrogramIf::computeMagSpectrum_().
getPhase()
Error_t CFft::getPhase (float * pfPhase, const complex_t * pfSpectrum) const
extract phase spectrum from complex values
Parameters
pfPhase resulting phase spectrum of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
pfSpectrum input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 156 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    pfPhase[0]      = m_Pi;
    pfPhase[iNyq]   = m_Pi;
    for (int i = 1; i < iNyq; i++)
    {
        int iImagIdx    = m_iFftLength - i;
        if (pfSpectrum[i] == .0F && pfSpectrum[iImagIdx] != .0F)
            pfPhase[i]   = m_Pi2;
        else
            pfPhase[i]   = atan2f (pfSpectrum[iImagIdx], pfSpectrum[i]);
    }
    return Error_t::kNoError;
}
References kNoError, kNotInitializedError, m_bIsInitialized, m_iFftLength, m_Pi, and m_Pi2.
Referenced by CInstFreq::process().
getWindow()
Error_t CFft::getWindow (float * pfWindow) const
retrieve current window
Parameters
pfWindow window data of length iBlockLength (
See also
initInstance)
Returns
Error_t
Definition at line 79 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!pfWindow)
        return Error_t::kFunctionInvalidArgsError;
    CVector::copy(pfWindow, m_pfWindowBuff, m_iDataLength);
    return Error_t::kNoError;
}
References CVector::copy(), kFunctionInvalidArgsError, kNoError, kNotInitializedError, m_bIsInitialized, m_iDataLength, and m_pfWindowBuff.
init()
Error_t CFft::init (int iBlockLength, int iZeroPadFactor = 1, WindowFunction_t eWindow = kWindowHann, Windowing_t eWindowing = kPreWindow)
initializes an FFT instance
Parameters
iBlockLength input data block length in Frames
iZeroPadFactor fft length (zeropadded)
eWindow window type
eWindowing apply window before FFT, after IFFT, or both
Returns
Error_t
Definition at line 24 of file Fft.cpp.
{
    Error_t  rErr = Error_t::kNoError;
    // sanity check
    if (iZeroPadFactor <= 0)
        return Error_t::kFunctionInvalidArgsError;
    // clean up
    reset();
    // make sure the fft length is a power of two
    int iInternalBlockLength = CUtil::isPowOf2(iBlockLength) ? iBlockLength : CUtil::nextPowOf2(iBlockLength);
    m_iDataLength   = iBlockLength;
    m_iFftLength    = iInternalBlockLength * iZeroPadFactor;
    m_ePrePostWindowOpt = eWindowing;
    rErr = allocMemory_ ();
    if (rErr != Error_t::kNoError)
        return rErr;
    rErr = computeWindow_ (eWindow);
    m_bIsInitialized    = true;
    return rErr;
}
References allocMemory_(), computeWindow_(), CUtil::isPowOf2(), kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, m_iFftLength, CUtil::nextPowOf2(), and reset().
Referenced by CInstFreq::CInstFreq(), CBeatHistoIf::compBeatHisto(), CCcf::init(), CChordIf::init_(), CFingerprint::init_(), CFeatureIf::init_(), CSpectrogramIf::init_(), CNoveltyIf::init_(), and CPitchIf::init_().
mergeRealImag()
Error_t CFft::mergeRealImag (complex_t * pfSpectrum, const float * pfReal, const float * pfImag) const
merge real and imaginary parts into complex spectrum
Parameters
pfSpectrum resulting spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Parameters
pfReal input real part of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
pfImag input imaginary part of length (iBlockLength * iZeroPadFactor)/2 (
See also
initInstance)
Returns
Error_t
Definition at line 198 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    CVector::copy(pfSpectrum, pfReal, static_cast<long long>(iNyq)+1);
    for (int i = 1, iImag = m_iFftLength-1; i < iNyq; i++, iImag--)
    {
        pfSpectrum[iImag]   = pfImag[i];
    }
    return Error_t::kNoError;
}
References CVector::copy(), kNoError, kNotInitializedError, m_bIsInitialized, and m_iFftLength.
multiply_I()
void CFft::multiply_I (complex_t * pfFftSrc1Dest, const complex_t * pfFftSrc2) const
Definition at line 232 of file Fft.cpp.
{
    int i = 0,
        j = 0;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    pfFftSrc1Dest[0] *= pfFftSrc2[0];
    pfFftSrc1Dest[m_iFftLength >> 1] *= pfFftSrc2[m_iFftLength >> 1];
    for (i = 1, j = m_iFftLength-1; i < m_iFftLength>>1; i++, j--)
    {
        float fTemp = pfFftSrc1Dest[i];
        // real part of multiplication
        pfFftSrc1Dest[i] *= pfFftSrc2[i];
        pfFftSrc1Dest[i] -= pfFftSrc1Dest[j] * pfFftSrc2[j];
        // imaginary part of multiplication
        pfFftSrc1Dest[j] *= pfFftSrc2[i];
        pfFftSrc1Dest[j] += fTemp * pfFftSrc2[j];
    }
    return;
}
References m_iFftLength.
Referenced by CCcf::compCcf().
operator=()
CFft & CFft::operator= (const CFft & c) private
overrideWindow()
Error_t CFft::overrideWindow (const float * pfNewWindow)
use a customized window
Parameters
pfNewWindow window data of length iBlockLength (
See also
initInstance)
Returns
Error_t
Definition at line 67 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!pfNewWindow)
        return Error_t::kFunctionInvalidArgsError;
    CVector::copy(m_pfWindowBuff, pfNewWindow, m_iDataLength);
    return Error_t::kNoError;
}
References CVector::copy(), kFunctionInvalidArgsError, kNoError, kNotInitializedError, m_bIsInitialized, m_iDataLength, and m_pfWindowBuff.
Referenced by CSpectrogramIf::init_().
reset()
Error_t CFft::reset ()
resets an FFT instance
Returns
Error_t
Definition at line 53 of file Fft.cpp.
{
    freeMemory_();
    m_iDataLength       = 0;
    m_iFftLength        = 0;
    m_ePrePostWindowOpt = kNoWindow;
    m_bIsInitialized    = false;
    return Error_t::kNoError;
}
References freeMemory_(), kNoError, kNoWindow, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, and m_iFftLength.
Referenced by CFft(), init(), CCcf::reset(), and ~CFft().
splitRealImag()
Error_t CFft::splitRealImag (float * pfReal, float * pfImag, const complex_t * pfSpectrum) const
get real and imaginary part from complex spectrum
Parameters
pfReal resulting real part of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
pfImag resulting imaginary part of length (iBlockLength * iZeroPadFactor)/2 (
See also
initInstance)
Parameters
pfSpectrum input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 178 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    CVector::copy(pfReal, pfSpectrum, static_cast<long long>(iNyq)+1);
    pfImag[0] = 0;
    pfImag[iNyq] = 0;
    for (int i = 1, iImag = m_iFftLength-1; i < iNyq; i++, iImag--)
    {
        pfImag[i]   = pfSpectrum[iImag];
    }
    return Error_t::kNoError;
}
References CVector::copy(), kNoError, kNotInitializedError, m_bIsInitialized, and m_iFftLength.
Member Data Documentation
m_bIsInitialized
bool CFft::m_bIsInitialized = false private
flag indicating if the instance is initialized
Definition at line 150 of file Fft.h.
Referenced by compFft(), compInvFft(), getMagnitude(), getPhase(), getWindow(), init(), mergeRealImag(), overrideWindow(), reset(), and splitRealImag().
m_ePrePostWindowOpt
Windowing_t CFft::m_ePrePostWindowOpt = kNoWindow private
windowing option
Definition at line 148 of file Fft.h.
Referenced by compFft(), compInvFft(), init(), and reset().
m_iDataLength
int CFft::m_iDataLength = 0 private
length of data
Definition at line 145 of file Fft.h.
Referenced by allocMemory_(), compFft(), compInvFft(), computeWindow_(), getLength(), getWindow(), init(), overrideWindow(), and reset().
m_iFftLength
int CFft::m_iFftLength = 0 private
length of FFT
Definition at line 146 of file Fft.h.
Referenced by allocMemory_(), bin2freq(), compFft(), compInvFft(), conjugate_I(), freq2bin(), getLength(), getMagnitude(), getPhase(), init(), mergeRealImag(), multiply_I(), reset(), and splitRealImag().
m_pfProcessBuff
float* CFft::m_pfProcessBuff = 0 private
generic processing buffer
Definition at line 142 of file Fft.h.
Referenced by allocMemory_(), compFft(), compInvFft(), and freeMemory_().
m_pfWindowBuff
float* CFft::m_pfWindowBuff = 0 private
window function
Definition at line 143 of file Fft.h.
Referenced by allocMemory_(), compFft(), compInvFft(), computeWindow_(), freeMemory_(), getWindow(), and overrideWindow().
m_Pi
const float CFft::m_Pi = static_cast<float>(M_PI) static private
just to have it as float
Definition at line 152 of file Fft.h.
Referenced by computeWindow_(), and getPhase().
m_Pi2
const float CFft::m_Pi2 = static_cast<float>(M_PI_2) static private
just to have it as float
Definition at line 153 of file Fft.h.
Referenced by getPhase().
The documentation for this class was generated from the following files:
Fft.h
Fft.cpp