ACA: CAudioFileSndLib Class Reference
CAudioFileSndLib Class Reference
open, read, and write audio files with sndlib (CMake option WITH_SNDLIB has to be ON)
#include <AudioFile.h>
Public Member Functions
CAudioFileSndLib ()
virtual ~CAudioFileSndLib ()
Error_t openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const *psFileSpec=0) override
Error_t closeFile () override
bool isEof () override
bool isOpen () override
Error_t freeMemory_ () override
Error_t allocMemory_ () override
Public Member Functions inherited from CAudioFileIf
virtual Error_t reset (bool bFreeMemory=false)
virtual Error_t openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const *psFileSpec=0)=0
virtual Error_t closeFile ()=0
virtual Error_t readData (float **ppfAudioData, long long int &iNumFrames)
virtual Error_t writeData (const float *const *const ppfAudioData, long long int iNumFrames)
Error_t getFileSpec (FileSpec_t &sFileSpec)
virtual Error_t setPosition (long long iFrame=0)
Error_t setPosition (double dTimeInS=.0)
Error_t setClippingEnabled (bool bisEnabled=true)
bool isClippingEnabled ()
Error_t getPosition (long long &iFrame)
Error_t getPosition (double &dTimeInS)
Error_t getLength (long long &iLengthInFrames)
Error_t getLength (double &dLengthInSeconds)
virtual bool isEof ()=0
virtual bool isOpen ()=0
virtual bool isInitialized ()
Private Member Functions
CAudioFileSndLib (const CAudioFileSndLib &that)
long long int readDataIntern_ (float **ppfAudioData, long long int iLength) override
long long int writeDataIntern_ (const float *const *const ppfAudioData, long long int iLength) override
long long getLengthIntern_ () override
long long getPositionIntern_ () override
Error_t setPositionIntern_ (long long iFrame) override
Private Attributes
int m_FileHandle = 0
sndlib file handle
long long m_lFrameCnt = 0
current file position in frames
long long m_lFileLength = 0
file length in frames
double ** m_ppdTmpBuff = 0
temporary buffer for double values
Additional Inherited Members
Public Types inherited from CAudioFileIf
enum FileIoType_t { kFileRead = 0x1L , kFileWrite = 0x2L , kNumFileOpenTypes = 2 }
enum FileFormat_t {
kFileFormatRaw , kFileFormatWav , kFileFormatAiff , kFileFormatUnknown ,
kNumFileFormats
}
enum BitStream_t { kFileBitStreamInt16 , kFileBitStreamFloat32 , kFileBitStreamUnknown , kNumWordLengths }
Static Public Member Functions inherited from CAudioFileIf
static Error_t create (CAudioFileIf *&pCInstance)
static Error_t destroy (CAudioFileIf *&pCInstance)
Protected Member Functions inherited from CAudioFileIf
CAudioFileIf ()
virtual ~CAudioFileIf ()
virtual Error_t freeMemory_ ()
virtual Error_t allocMemory_ ()
Error_t setInitialized_ (bool bInitialized=true)
Error_t setIoType_ (FileIoType_t eIoType)
FileIoType_t getIoType_ () const
Error_t setFileSpec_ (const FileSpec_t *pFileSpec)
int getNumChannels_ () const
long long convFrames2Bytes_ (long long iNumFrames)
long long convBytes2Frames_ (long long iNumFrames)
Error_t setNumBytesPerSample_ (int iNumBytes)
int getNumBytesPerSample_ () const
int getNumBitsPerSample_ () const
float clip2Range_ (float fSample2Clip, float fMin, float fMax)
Static Protected Attributes inherited from CAudioFileIf
static const long long int m_kiDefBlockLength = 1024
buffer length for read and write operations
Detailed Description
open, read, and write audio files with sndlib (CMake option WITH_SNDLIB has to be ON)
Definition at line 41 of file AudioFile.h.
Constructor & Destructor Documentation
CAudioFileSndLib() [1/2]
CAudioFileSndLib::CAudioFileSndLib ()
Definition at line 243 of file AudioFile.cpp.
                                  : CAudioFileIf() ,
    m_FileHandle(-1),
    m_lFrameCnt(0),
    m_lFileLength(0),
    m_ppdTmpBuff(0)
{
    reset (true);
}
References CAudioFileIf::reset().
~CAudioFileSndLib()
CAudioFileSndLib::~CAudioFileSndLib () virtual
Definition at line 252 of file AudioFile.cpp.
{
    reset (true);
}
References CAudioFileIf::reset().
CAudioFileSndLib() [2/2]
CAudioFileSndLib::CAudioFileSndLib (const CAudioFileSndLib & that) private
Member Function Documentation
allocMemory_()
Error_t CAudioFileSndLib::allocMemory_ () override virtual
Reimplemented from CAudioFileIf.
Definition at line 524 of file AudioFile.cpp.
{
    int iNumChannels = getNumChannels_();
    freeMemory_();
    m_ppdTmpBuff    = new double* [iNumChannels];
    for (int i = 0; i < iNumChannels; i++)
        m_ppdTmpBuff[i] = new double [static_cast<unsigned int>(m_kiDefBlockLength)];
    if (!m_ppdTmpBuff)
        return Error_t::kMemError;
    else
        return Error_t::kNoError;
}
References freeMemory_(), CAudioFileIf::getNumChannels_(), kMemError, kNoError, CAudioFileIf::m_kiDefBlockLength, and m_ppdTmpBuff.
Referenced by openFile().
closeFile()
Error_t CAudioFileSndLib::closeFile () override virtual
close the current file
Returns
Error_t
Implements CAudioFileIf.
Definition at line 369 of file AudioFile.cpp.
{
    if (!isOpen())
    {
        return Error_t::kNoError;
    }
    if (getIoType_() == kFileRead)
    {
        mus_sound_close_input(m_FileHandle);
    }
    else
    {
        mus_sound_close_output(m_FileHandle, convFrames2Bytes_(m_lFrameCnt));
    }
    m_lFrameCnt     = 0;
    m_FileHandle    = -1;
    m_lFileLength   = 0;
    // free internal memory
    return freeMemory_();
}
References CAudioFileIf::convFrames2Bytes_(), freeMemory_(), CAudioFileIf::getIoType_(), isOpen(), CAudioFileIf::kFileRead, kNoError, m_FileHandle, m_lFileLength, m_lFrameCnt, mus_sound_close_input(), and mus_sound_close_output().
freeMemory_()
Error_t CAudioFileSndLib::freeMemory_ () override virtual
Reimplemented from CAudioFileIf.
Definition at line 509 of file AudioFile.cpp.
{
    CAudioFileIf::freeMemory_ ();
    if (!m_ppdTmpBuff)
        return Error_t::kNoError;
    for (int i = 0; i < getNumChannels_(); i++)
        delete m_ppdTmpBuff[i];
    delete [] m_ppdTmpBuff;
    m_ppdTmpBuff  = 0;
    return Error_t::kNoError;
}
References CAudioFileIf::freeMemory_(), CAudioFileIf::getNumChannels_(), kNoError, and m_ppdTmpBuff.
Referenced by allocMemory_(), and closeFile().
getLengthIntern_()
long long CAudioFileSndLib::getLengthIntern_ () override private virtual
Implements CAudioFileIf.
Definition at line 485 of file AudioFile.cpp.
{
    if (getIoType_() == kFileWrite)
    {
        return m_lFrameCnt;
    }
    else
    {
        return m_lFileLength;
    }
}
References CAudioFileIf::getIoType_(), CAudioFileIf::kFileWrite, m_lFileLength, and m_lFrameCnt.
getPositionIntern_()
long long CAudioFileSndLib::getPositionIntern_ () override private virtual
Implements CAudioFileIf.
Definition at line 497 of file AudioFile.cpp.
{
    return m_lFrameCnt;
}
References m_lFrameCnt.
isEof()
bool CAudioFileSndLib::isEof () override virtual
check if EOF is true
Returns
bool
Implements CAudioFileIf.
Definition at line 539 of file AudioFile.cpp.
{
    return (m_lFrameCnt >= m_lFileLength);
}
References m_lFileLength, and m_lFrameCnt.
isOpen()
bool CAudioFileSndLib::isOpen () override virtual
check if a file is opened
Returns
bool
Implements CAudioFileIf.
Definition at line 393 of file AudioFile.cpp.
{
    return (m_FileHandle >= 0);
}
References m_FileHandle.
Referenced by closeFile(), and openFile().
openFile()
Error_t CAudioFileSndLib::openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const * psFileSpec = 0) override virtual
open a file for reading or writing
Parameters
cAudioFileName
eIoType
psFileSpec
Returns
Error_t
Implements CAudioFileIf.
Definition at line 258 of file AudioFile.cpp.
{
    FileSpec_t  sSpec;
    int iSndLibFileFormat = MUS_RIFF;
    if (cAudioFileName.empty())
        return Error_t::kFileOpenError;
    reset (true);
    setIoType_(eIoType);
    if (!psFileSpec)
    {
        getFileSpec(sSpec);
    }
    else
    {
        CVector::copy(&sSpec, psFileSpec, 1);
    }
    switch (sSpec.eFormat)
    {
    case kFileFormatWav:
        iSndLibFileFormat = MUS_RIFF;
        break;
    case kFileFormatRaw:
        iSndLibFileFormat = MUS_RAW;
        break;
    case kFileFormatAiff:
        iSndLibFileFormat = MUS_AIFF;
        break;
    default:
        return Error_t::kFunctionInvalidArgsError;
    }
    // set file spec (required for raw streams)
    setFileSpec_(&sSpec);
    if (getIoType_() == kFileRead)
    {
        if (mus_sound_header_type(cAudioFileName.c_str()) == MUS_RAW)
        {
            mus_sound_set_chans(cAudioFileName.c_str(), sSpec.iNumChannels);
            mus_sound_set_srate(cAudioFileName.c_str(), CUtil::float2int<int>(sSpec.fSampleRateInHz));
            mus_sound_set_header_type(cAudioFileName.c_str(),  iSndLibFileFormat);
            mus_sound_set_data_format(cAudioFileName.c_str(), (sSpec.eBitStreamType == kFileBitStreamInt16)?MUS_LSHORT:MUS_LFLOAT);
        }
        else
        {
            FileSpec_t  sFileSpec;
            int iTmp = -1;
            sFileSpec.fSampleRateInHz   = static_cast<float>(mus_sound_srate(cAudioFileName.c_str()));
            sFileSpec.iNumChannels      = mus_sound_chans(cAudioFileName.c_str());
            iTmp                        = mus_sound_header_type(cAudioFileName.c_str());
            switch (iTmp)
            {
            case MUS_RIFF:
                sFileSpec.eFormat = kFileFormatWav;
                break;
            case MUS_AIFF:
                sFileSpec.eFormat = kFileFormatAiff;
                break;
            default:
                sFileSpec.eFormat = kFileFormatUnknown;
                break;
            }
            iTmp    = mus_sound_data_format(cAudioFileName.c_str());
            switch (iTmp)
            {
            case MUS_LSHORT:
            case MUS_BSHORT:
                sFileSpec.eBitStreamType = kFileBitStreamInt16;
                setNumBytesPerSample_(2);
                break;
            case MUS_BFLOAT:
            case MUS_LFLOAT:
                sFileSpec.eBitStreamType = kFileBitStreamFloat32;
                setNumBytesPerSample_(4);
                break;
            default:
                sFileSpec.eBitStreamType = kFileBitStreamUnknown;
                break;
            }
            setFileSpec_(&sFileSpec);
        }
        m_FileHandle = mus_sound_open_input(cAudioFileName.c_str());
    }
    else
    {
        m_FileHandle = mus_sound_open_output(cAudioFileName.c_str(),
            CUtil::float2int<int>(sSpec.fSampleRateInHz),
            sSpec.iNumChannels,
            (sSpec.eBitStreamType == kFileBitStreamInt16)?MUS_LSHORT:MUS_LFLOAT, // only write little endian files
            iSndLibFileFormat,
            0);
    }
    if (!isOpen())
    {
        reset (true);
        return Error_t::kFileOpenError;
    }
    m_lFileLength = mus_sound_frames(cAudioFileName.c_str());
    setInitialized_(true);
    // allocate internal memory
    return allocMemory_();
}
References allocMemory_(), CVector::copy(), CAudioFileIf::FileSpec_t::eBitStreamType, CAudioFileIf::FileSpec_t::eFormat, CAudioFileIf::FileSpec_t::fSampleRateInHz, CAudioFileIf::getFileSpec(), CAudioFileIf::getIoType_(), CAudioFileIf::FileSpec_t::iNumChannels, isOpen(), CAudioFileIf::kFileBitStreamFloat32, CAudioFileIf::kFileBitStreamInt16, CAudioFileIf::kFileBitStreamUnknown, CAudioFileIf::kFileFormatAiff, CAudioFileIf::kFileFormatRaw, CAudioFileIf::kFileFormatUnknown, CAudioFileIf::kFileFormatWav, kFileOpenError, CAudioFileIf::kFileRead, kFunctionInvalidArgsError, m_FileHandle, m_lFileLength, MUS_AIFF, MUS_BFLOAT, MUS_BSHORT, MUS_LFLOAT, MUS_LSHORT, MUS_RAW, MUS_RIFF, mus_sound_chans(), mus_sound_data_format(), mus_sound_frames(), mus_sound_header_type(), mus_sound_open_input(), mus_sound_open_output(), mus_sound_set_chans(), mus_sound_set_data_format(), mus_sound_set_header_type(), mus_sound_set_srate(), mus_sound_srate(), CAudioFileIf::reset(), CAudioFileIf::setFileSpec_(), CAudioFileIf::setInitialized_(), CAudioFileIf::setIoType_(), and CAudioFileIf::setNumBytesPerSample_().
readDataIntern_()
long long int CAudioFileSndLib::readDataIntern_ (float ** ppfAudioData, long long int iLength) override private virtual
Implements CAudioFileIf.
Definition at line 398 of file AudioFile.cpp.
{
    int iNumChannels                = getNumChannels_();
    long long int iNumFrames2Read   = min (iLength, m_kiDefBlockLength);
    long long int iNumFrames        = 0;
    // sanity check
    assert(ppfAudioData);
    assert(ppfAudioData[0]);
    // use internal buffer with fixed length
    while (iNumFrames2Read > 0)
    {
        long long int iCurrFrames = mus_sound_read(m_FileHandle, 0, iNumFrames2Read-1, getNumChannels_(), m_ppdTmpBuff);
        if (iCurrFrames <= m_lFileLength-m_lFrameCnt)
        {
            iNumFrames2Read = std::min (iLength-iCurrFrames, m_kiDefBlockLength);
        }
        else
        {
            iCurrFrames     = static_cast<int>(m_lFileLength-m_lFrameCnt);
            iNumFrames2Read = 0;
        }
        // copy the data
        for (int iCh = 0; iCh < iNumChannels; iCh++)
        {
            for (int i = 0; i < iCurrFrames; i++)
            {
                ppfAudioData[iCh][iNumFrames+i] = static_cast<float>(m_ppdTmpBuff[iCh][i]);
            }
        }
        // update frame counters
        iLength        -= iCurrFrames;
        iNumFrames     += iCurrFrames;
        m_lFrameCnt    += iCurrFrames;
        assert (iLength >= 0);
    }
    // update iLength to the number of frames actually read
    return iNumFrames;
}
References CAudioFileIf::getNumChannels_(), m_FileHandle, CAudioFileIf::m_kiDefBlockLength, m_lFileLength, m_lFrameCnt, m_ppdTmpBuff, and mus_sound_read.
setPositionIntern_()
Error_t CAudioFileSndLib::setPositionIntern_ (long long iFrame) override private virtual
Implements CAudioFileIf.
Definition at line 502 of file AudioFile.cpp.
{
    m_lFrameCnt = convBytes2Frames_(mus_sound_seek_frame(m_FileHandle, iFrame));
    return Error_t::kNoError;
}
References CAudioFileIf::convBytes2Frames_(), kNoError, m_FileHandle, m_lFrameCnt, and mus_sound_seek_frame.
writeDataIntern_()
long long int CAudioFileSndLib::writeDataIntern_ (const float *const *const ppfAudioData, long long int iLength) override private virtual
Implements CAudioFileIf.
Definition at line 444 of file AudioFile.cpp.
{
    long long int iIdx            = 0;
    long long int iNumChannels    = getNumChannels_();
    // sanity check
    assert(ppfAudioData);
    assert(ppfAudioData[0]);
    float afRange[2] = {std::numeric_limits<float>::min(), std::numeric_limits<float>::max()};
    if (isClippingEnabled())
    {
        afRange[0]  = -1.F;
        afRange[1]  = 1-1.F/static_cast<float>(1<<(getNumBitsPerSample_()));
    }
    // use internal buffer with fixed length
    while (iIdx < iLength)
    {
        long long int iNumFrames2Write = min (iLength-iIdx, m_kiDefBlockLength);
        // copy the data
        for (int iCh = 0; iCh < iNumChannels; iCh++)
        {
            for (int i = 0; i < iNumFrames2Write; i++)
            {
                m_ppdTmpBuff[iCh][i]    = clip2Range_(ppfAudioData[iCh][iIdx+i], afRange[0], afRange[1]);
            }
        }
        if (mus_sound_write(m_FileHandle, 0, iNumFrames2Write-1, getNumChannels_(), m_ppdTmpBuff) == 0)
        {
            // update frame counter
            iIdx        += iNumFrames2Write;
            m_lFrameCnt += iNumFrames2Write;
        }
    }
    return iIdx;
}
References CAudioFileIf::clip2Range_(), CAudioFileIf::getNumBitsPerSample_(), CAudioFileIf::getNumChannels_(), CAudioFileIf::isClippingEnabled(), m_FileHandle, CAudioFileIf::m_kiDefBlockLength, m_lFrameCnt, m_ppdTmpBuff, and mus_sound_write.
Member Data Documentation
m_FileHandle
int CAudioFileSndLib::m_FileHandle = 0 private
sndlib file handle
Definition at line 62 of file AudioFile.h.
Referenced by closeFile(), isOpen(), openFile(), readDataIntern_(), setPositionIntern_(), and writeDataIntern_().
m_lFileLength
long long CAudioFileSndLib::m_lFileLength = 0 private
file length in frames
Definition at line 65 of file AudioFile.h.
Referenced by closeFile(), getLengthIntern_(), isEof(), openFile(), and readDataIntern_().
m_lFrameCnt
long long CAudioFileSndLib::m_lFrameCnt = 0 private
current file position in frames
Definition at line 64 of file AudioFile.h.
Referenced by closeFile(), getLengthIntern_(), getPositionIntern_(), isEof(), readDataIntern_(), setPositionIntern_(), and writeDataIntern_().
m_ppdTmpBuff
double** CAudioFileSndLib::m_ppdTmpBuff = 0 private
temporary buffer for double values
Definition at line 66 of file AudioFile.h.
Referenced by allocMemory_(), freeMemory_(), readDataIntern_(), and writeDataIntern_().
The documentation for this class was generated from the following files:
AudioFile.h
AudioFile.cpp