ACA: CGammatone Class Reference
CGammatone Class Reference
class for a single gammtone filter
Public Member Functions
CGammatone ()
virtual ~CGammatone ()
Error_t init (float fFreqCenter, float fSampleRate)
Error_t process (float *pfOut, const float *pfIn, long long iNumSamples)
Error_t reset ()
Private Types
enum { kNumCoeffs = 3 , kNumFilters = 4 }
Private Member Functions
CGammatone (const CGammatone &that)
CGammatone & operator= (const CGammatone &c)
void calcFilterCoeffs_ (int iOrder=1)
Private Attributes
float m_fFreqCenter = 0
center frequency of this filter
float m_fSampleRate = 0
sample rate in Hz
float m_aafCoeffB [kNumFilters][kNumCoeffs] = { { 0 } }
FIR coefficients.
float m_aafCoeffA [kNumFilters][kNumCoeffs] = { { 0 } }
IIR coefficients.
CFilter< float > * m_apCFilter [kNumFilters] = { 0 }
number crunching (multiple instances b/c cascaded)
bool m_bIsInitialized = false
flag indicating that this is initialized
Detailed Description
class for a single gammtone filter
Definition at line 18 of file ToolGammatone.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kNumCoeffs
kNumFilters
Definition at line 53 of file ToolGammatone.cpp.
    {
        kNumCoeffs = 3,
        kNumFilters = 4
    };
Constructor & Destructor Documentation
CGammatone() [1/2]
CGammatone::CGammatone ()
Definition at line 82 of file ToolGammatone.cpp.
{
    for (auto c = 0; c < kNumFilters; c++)
        m_apCFilter[c] = new CFilter<float>();
}
References kNumFilters, and m_apCFilter.
Referenced by CGammatone(), and operator=().
~CGammatone()
CGammatone::~CGammatone () virtual
Definition at line 89 of file ToolGammatone.cpp.
{
    for (auto c = 0; c < kNumFilters; c++)
        delete m_apCFilter[c];
}
References kNumFilters, and m_apCFilter.
CGammatone() [2/2]
CGammatone::CGammatone (const CGammatone & that) private
References CGammatone().
Member Function Documentation
calcFilterCoeffs_()
void CGammatone::calcFilterCoeffs_ (int iOrder = 1) private
compute the filter coeffs
Parameters
iOrder filter order
Definition at line 205 of file ToolGammatone.cpp.
{
    assert(m_fSampleRate > 0);
    assert(m_fFreqCenter >= 0);
    const float f2Pi = static_cast<float>(2 * M_PI);
    const float fEarQ = 9.26449F;
    const float fBandwidth = 24.7F;
    const float B = static_cast<float>(1.019 * f2Pi * std::pow(std::pow(m_fFreqCenter / fEarQ, iOrder) + std::pow(fBandwidth, iOrder), 1. / iOrder));
    float fArg = f2Pi * m_fFreqCenter / m_fSampleRate;
    float fCos = std::cos(fArg);
    float fSin = std::sin(fArg);
    float fExp = std::exp(B / m_fSampleRate);
    float fSqrtA = 2 * std::sqrt(3.F + std::pow(2.F, 1.5F));
    float fSqrtS = 2 * std::sqrt(3.F - std::pow(2.F, 1.5F));
    float fGain = 0;
    for (auto c = 0; c < kNumFilters; c++)
    {
        m_aafCoeffB[c][0] = 1.F / m_fSampleRate;
        m_aafCoeffB[c][2] = 0.F;
        m_aafCoeffA[c][0] = 1.F;
        m_aafCoeffA[c][1] = -2.F * fCos / fExp;
        m_aafCoeffA[c][2] = std::exp(-2.F * B / m_fSampleRate);
    }
    m_aafCoeffB[0][1] = -(2.F / m_fSampleRate * fCos / fExp + fSqrtA / m_fSampleRate * fSin / fExp) / 2.F;
    m_aafCoeffB[1][1] = -(2.F / m_fSampleRate * fCos / fExp - fSqrtA / m_fSampleRate * fSin / fExp) / 2.F;
    m_aafCoeffB[2][1] = -(2.F / m_fSampleRate * fCos / fExp + fSqrtS / m_fSampleRate * fSin / fExp) / 2.F;
    m_aafCoeffB[3][1] = -(2.F / m_fSampleRate * fCos / fExp - fSqrtS / m_fSampleRate * fSin / fExp) / 2.F;
    // apply gain to first cascade
    {
        fSqrtA *= .5F;
        fSqrtS *= .5F;
        float fScale = 2 * 2 * 2 * 2 / (m_fSampleRate * m_fSampleRate * m_fSampleRate * m_fSampleRate);
        std::complex<float> num1(-std::cos(2.F * fArg), -std::sin(2 * fArg));
        std::complex<float> num2(std::cos(fArg) * std::exp(-B / m_fSampleRate), std::sin(fArg) * std::exp(-B / m_fSampleRate));
        std::complex<float> denom(-2.F / std::exp(2.F * B / m_fSampleRate) + 2.F / fExp + std::cos(2 * fArg) * (2.F / fExp - 2.F), std::sin(2 * fArg) * (2.F / fExp - 2.F));
        auto numerator = fScale *
            (num1 + num2 * (fCos - fSqrtS * fSin)) *
            (num1 + num2 * (fCos + fSqrtS * fSin)) *
            (num1 + num2 * (fCos - fSqrtA * fSin)) *
            (num1 + num2 * (fCos + fSqrtA * fSin));
        auto denominator = denom * denom * denom * denom;
        fGain = std::abs(numerator / denominator);
    }
    CVector::mulC_I(m_aafCoeffB[0], 1.F / fGain, kNumCoeffs);
    for (auto c = 0; c < kNumFilters; c++)
        m_apCFilter[c]->init(m_aafCoeffB[c], m_aafCoeffA[c], 3);
}
References init(), kNumCoeffs, kNumFilters, m_aafCoeffA, m_aafCoeffB, m_apCFilter, m_fFreqCenter, m_fSampleRate, M_PI, and CVector::mulC_I().
Referenced by init().
init()
Error_t CGammatone::init (float fFreqCenter, float fSampleRate)
initializes a Gammatone instance (one band)
Parameters
fFreqCenter center frequency
fSampleRate sample rate
Returns
Error_t
Definition at line 95 of file ToolGammatone.cpp.
{
    m_fFreqCenter = fFreqCenter;
    m_fSampleRate = fSampleRate;
    calcFilterCoeffs_();
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References calcFilterCoeffs_(), kNoError, m_bIsInitialized, m_fFreqCenter, and m_fSampleRate.
Referenced by calcFilterCoeffs_().
operator=()
CGammatone & CGammatone::operator= (const CGammatone & c) private
References CGammatone().
process()
Error_t CGammatone::process (float * pfOut, const float * pfIn, long long iNumSamples)
performs the Gammatone filter computation
Parameters
pfOut filter result (user-allocated, to be written, length iNumSamples)
pfIn input data of length iNumSamples
iNumSamples length of buffers return Error_t
Definition at line 107 of file ToolGammatone.cpp.
{
    if (!pfOut || !pfIn || iNumSamples <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
#ifdef ACA_USE_DOUBLE
    for (auto i = 0; i < iNumSamples; i++)
    {
        double fTmp = pfIn[i];
        for (auto c = 0; c < kNumFilters; c++)
            m_apCFilter[c]->process(&fTmp, &fTmp, 1);
        pfOut[i] = static_cast<float>(fTmp);
    }
#else
    CVector::copy(pfOut, pfIn, iNumSamples);
    for (auto c = 0; c < kNumFilters; c++)
        m_apCFilter[c]->process(pfOut, pfOut, iNumSamples);
#endif // ACA_USE_DOUBLE
    return Error_t::kNoError;
}
References CVector::copy(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, kNumFilters, m_apCFilter, m_bIsInitialized, and process().
Referenced by process().
reset()
Error_t CGammatone::reset ()
clears internal buffers and sets parameters to default
Returns
Error_t
Definition at line 132 of file ToolGammatone.cpp.
{
    m_fFreqCenter = 0.F;
    for (auto c = 0; c < kNumFilters; c++)
    {
        m_apCFilter[c]->reset();
        delete m_apCFilter[c];
        m_apCFilter[c] = 0;
    }
    return Error_t::kNoError;
}
References kNoError, kNumFilters, m_apCFilter, and m_fFreqCenter.
Member Data Documentation
m_aafCoeffA
float CGammatone::m_aafCoeffA[kNumFilters][kNumCoeffs] = { { 0 } } private
IIR coefficients.
Definition at line 68 of file ToolGammatone.cpp.
{ { 0 } }; //!< IIR coefficients
Referenced by calcFilterCoeffs_().
m_aafCoeffB
float CGammatone::m_aafCoeffB[kNumFilters][kNumCoeffs] = { { 0 } } private
FIR coefficients.
Definition at line 67 of file ToolGammatone.cpp.
{ { 0 } }; //!< FIR coefficients
Referenced by calcFilterCoeffs_().
m_apCFilter
CFilter<float>* CGammatone::m_apCFilter[kNumFilters] = { 0 } private
number crunching (multiple instances b/c cascaded)
Definition at line 69 of file ToolGammatone.cpp.
{ 0 }; //!< number crunching (multiple instances b/c cascaded)
Referenced by calcFilterCoeffs_(), CGammatone(), process(), reset(), and ~CGammatone().
m_bIsInitialized
bool CGammatone::m_bIsInitialized = false private
flag indicating that this is initialized
Definition at line 71 of file ToolGammatone.cpp.
Referenced by init(), and process().
m_fFreqCenter
float CGammatone::m_fFreqCenter = 0 private
center frequency of this filter
Definition at line 59 of file ToolGammatone.cpp.
Referenced by calcFilterCoeffs_(), init(), and reset().
m_fSampleRate
float CGammatone::m_fSampleRate = 0 private
sample rate in Hz
Definition at line 60 of file ToolGammatone.cpp.
Referenced by calcFilterCoeffs_(), and init().
The documentation for this class was generated from the following file:
ToolGammatone.cpp