ACA: CSynthesis Class Reference
CSynthesis Class Reference
class with static functions for signal generation
#include <Synthesis.h>
Static Public Member Functions
template<class T >
static Error_t genSine (T *pfOutBuf, T fFreqInHz, T fSampleRateInHz, long long iLength, T fAmplitude=1.F, T fStartPhaseInRad=0.)
template<class T >
static Error_t genRect (T *pfOutBuf, T fFreqInHz, T fSampleRateInHz, long long iLength, T fAmplitude=1.)
template<class T >
static Error_t genSaw (T *pfOutBuf, T fFreqInHz, T fSampleRateInHz, long long iLength, T fAmplitude=1.)
template<class T >
static Error_t genDc (T *pfOutBuf, long long iLength, T fAmplitude=1.)
template<class T >
static Error_t genNoise (T *pfOutBuf, long long iLength, T fAmplitude=1.)
Detailed Description
class with static functions for signal generation
Definition at line 13 of file Synthesis.h.
Member Function Documentation
genDc()
template<class T > static Error_t CSynthesis::genDc (T * pfOutBuf, long long iLength, T fAmplitude = 1.) inline static
generates a dc signal
Parameters
pfOutBuf output memory buffer (to be written)
iLength number of frames to be generated
fAmplitude amplitude of signal
Returns
Error_t
Definition at line 101 of file Synthesis.h.
    {
        if (!pfOutBuf)
            return Error_t::kFunctionInvalidArgsError;
        for (int i = 0; i < iLength; i++)
        {
            pfOutBuf[i] = fAmplitude;
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
genNoise()
template<class T > static Error_t CSynthesis::genNoise (T * pfOutBuf, long long iLength, T fAmplitude = 1.) inline static
generates a uniform noise
Parameters
pfOutBuf output memory buffer (to be written)
iLength number of frames to be generated
fAmplitude max amplitude of noise
Returns
Error_t
Definition at line 121 of file Synthesis.h.
    {
        if (!pfOutBuf)
            return Error_t::kFunctionInvalidArgsError;
        for (int i = 0; i < iLength; i++)
        {
            pfOutBuf[i] = rand()*fAmplitude/RAND_MAX;
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
Referenced by CKmeans::initClusterMeans_(), CKmeans::reinitClusterMeans_(), and CVector::setRand().
genRect()
template<class T > static Error_t CSynthesis::genRect (T * pfOutBuf, T fFreqInHz, T fSampleRateInHz, long long iLength, T fAmplitude = 1.) inline static
generates a square wave
Parameters
pfOutBuf output memory buffer (to be written)
fFreqInHz frequency of sinusoidal
fSampleRateInHz sample rate
iLength number of frames to be generated
fAmplitude amplitude of signal
Returns
Error_t
Definition at line 48 of file Synthesis.h.
    {
        if (!pfOutBuf)
            return Error_t::kFunctionInvalidArgsError;
        T fPeriodLength = fSampleRateInHz / fFreqInHz;
        for (int i = 0; i < iLength; i++)
        {
            // this seems super inefficient
            if (i % static_cast<int>(fPeriodLength) < .5*fPeriodLength)
            {
                pfOutBuf[i] = fAmplitude;
            }
            else
            {
                pfOutBuf[i] = -fAmplitude;
            }
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
genSaw()
template<class T > static Error_t CSynthesis::genSaw (T * pfOutBuf, T fFreqInHz, T fSampleRateInHz, long long iLength, T fAmplitude = 1.) inline static
generates a sawtooth
Parameters
pfOutBuf output memory buffer (to be written)
fFreqInHz frequency of sinusoidal
fSampleRateInHz sample rate
iLength number of frames to be generated
fAmplitude amplitude of signal
Returns
Error_t
Definition at line 79 of file Synthesis.h.
    {
        if (!pfOutBuf)
            return Error_t::kFunctionInvalidArgsError;
        float fIncr = 2*fAmplitude / fSampleRateInHz * fFreqInHz;
        pfOutBuf[0] = 0;
        for (int i = 1; i < iLength; i++)
        {
            pfOutBuf[i] = fmodf(pfOutBuf[i-1] + fIncr + fAmplitude, 2*fAmplitude) - fAmplitude;
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
genSine()
template<class T > static Error_t CSynthesis::genSine (T * pfOutBuf, T fFreqInHz, T fSampleRateInHz, long long iLength, T fAmplitude = 1.F, T fStartPhaseInRad = 0.) inline static
generates a sinusoidal
Parameters
pfOutBuf output memory buffer (to be written)
fFreqInHz frequency of sinusoidal
fSampleRateInHz sample rate
iLength number of frames to be generated
fAmplitude amplitude of signal
fStartPhaseInRad starting phase in radiants
Returns
Error_t
Definition at line 26 of file Synthesis.h.
    {
        if (!pfOutBuf)
            return Error_t::kFunctionInvalidArgsError;
        for (int i = 0; i < iLength; i++)
        {
            pfOutBuf[i] = fAmplitude * static_cast<T>(sin (2*M_PI*fFreqInHz * i/fSampleRateInHz + fStartPhaseInRad));
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, kNoError, and M_PI.
The documentation for this class was generated from the following file:
Synthesis.h