ACA: CRingBuffer< T > Class Template Reference
CRingBuffer< T > Class Template Reference
implement a circular buffer of type T
#include <RingBuffer.h>
Public Member Functions
CRingBuffer (int iBufferLengthInSamples)
virtual ~CRingBuffer ()
void putPostInc (T tNewValue)
void putPostInc (const T *ptNewBuff, int iLength)
void put (T tNewValue)
void put (const T *ptNewBuff, int iLength)
T getPostInc ()
void getPostInc (T *ptBuff, int iLength)
T get (float fOffset=0) const
void get (T *ptBuff, int iLength) const
void reset ()
int getWriteIdx () const
void setWriteIdx (int iNewWriteIdx)
int getReadIdx () const
void setReadIdx (int iNewReadIdx)
int getNumValuesInBuffer () const
int getLength () const
Private Member Functions
CRingBuffer ()
CRingBuffer (const CRingBuffer &that)
CRingBuffer & operator= (const CRingBuffer &c)
void incIdx (int &iIdx, int iOffset=1)
Private Attributes
int m_iBuffLength = 0
length of the internal buffer
int m_iReadIdx = 0
current read index
int m_iWriteIdx = 0
current write index
T * m_ptBuff = 0
data buffer
Detailed Description
template<class T>
class CRingBuffer< T >
implement a circular buffer of type T
Definition at line 13 of file RingBuffer.h.
Constructor & Destructor Documentation
CRingBuffer() [1/3]
template<class T > CRingBuffer< T >::CRingBuffer (int iBufferLengthInSamples) inline explicit
Definition at line 16 of file RingBuffer.h.
                                                     :
        m_iBuffLength(iBufferLengthInSamples)
    {
        assert(iBufferLengthInSamples > 0);
        m_ptBuff = new T[m_iBuffLength];
        reset();
    }
References CRingBuffer< T >::m_iBuffLength, CRingBuffer< T >::m_ptBuff, and CRingBuffer< T >::reset().
~CRingBuffer()
template<class T > virtual CRingBuffer< T >::~CRingBuffer () inline virtual
Definition at line 25 of file RingBuffer.h.
    {
        delete[] m_ptBuff;
        m_ptBuff = 0;
    }
References CRingBuffer< T >::m_ptBuff.
CRingBuffer() [2/3]
template<class T > CRingBuffer< T >::CRingBuffer () private
CRingBuffer() [3/3]
template<class T > CRingBuffer< T >::CRingBuffer (const CRingBuffer< T > & that) private
Member Function Documentation
get() [1/2]
template<class T > T CRingBuffer< T >::get (float fOffset = 0) const inline
return the value at the current read index
Parameters
fOffset read at offset from read index
Returns
float the value from the read index
Definition at line 98 of file RingBuffer.h.
    {
        if (fOffset == 0)
            return m_ptBuff[m_iReadIdx];
        else
        {
            // compute fraction for linear interpolation
            int     iOffset = static_cast<int>(std::floor(fOffset));
            float   fFrac = fOffset - iOffset;
            int     iRead = m_iReadIdx + iOffset;
            while (iRead > m_iBuffLength - 1)
                iRead -= m_iBuffLength;
            while (iRead < 0)
                iRead += m_iBuffLength;
            return (1 - fFrac) * m_ptBuff[iRead] +
                fFrac * m_ptBuff[(iRead + 1) % m_iBuffLength];
        }
    }
References CRingBuffer< T >::m_iBuffLength, CRingBuffer< T >::m_iReadIdx, and CRingBuffer< T >::m_ptBuff.
Referenced by CKeyFromChroma::getKey(), CBlockAudioFile::getNextBlock(), and CRingBuffer< T >::getPostInc().
get() [2/2]
template<class T > void CRingBuffer< T >::get (T * ptBuff, int iLength) const inline
return the values starting at the current read index
Parameters
ptBuff to where the values will be written
iLength number of values
Definition at line 123 of file RingBuffer.h.
    {
        assert(iLength <= m_iBuffLength && iLength >= 0);
        // copy two parts: to the end of buffer and after wrap around
        int iNumValues2End = std::min(iLength, m_iBuffLength - m_iReadIdx);
        std::memcpy(ptBuff, &m_ptBuff[m_iReadIdx], sizeof(T) * iNumValues2End);
        if ((iLength - iNumValues2End) > 0)
            std::memcpy(&ptBuff[iNumValues2End], m_ptBuff, sizeof(T) * (static_cast<long long>(iLength) - iNumValues2End));
    }
References CRingBuffer< T >::m_iBuffLength, CRingBuffer< T >::m_iReadIdx, and CRingBuffer< T >::m_ptBuff.
getLength()
template<class T > int CRingBuffer< T >::getLength () const inline
returns the length of the internal buffer
Returns
int
Definition at line 187 of file RingBuffer.h.
    {
        return m_iBuffLength;
    }
References CRingBuffer< T >::m_iBuffLength.
Referenced by CBlockAudioFile::CBlockAudioFile(), and CMovingAverage::setFilterParam().
getNumValuesInBuffer()
template<class T > int CRingBuffer< T >::getNumValuesInBuffer () const inline
returns the number of values currently buffered (note: 0 could also mean the buffer is full!)
Returns
int
Definition at line 179 of file RingBuffer.h.
    {
        return (m_iWriteIdx - m_iReadIdx + m_iBuffLength) % m_iBuffLength;
    }
References CRingBuffer< T >::m_iBuffLength, CRingBuffer< T >::m_iReadIdx, and CRingBuffer< T >::m_iWriteIdx.
Referenced by CBlockAudioFile::CBlockAudioFile(), CMovingAverage::getFilterParam(), CBlockAudioFile::getNextBlock(), and CMovingAverage::process().
getPostInc() [1/2]
template<class T > T CRingBuffer< T >::getPostInc () inline
return the value at the current read index and increment the read pointer
Returns
float the value from the read index
Definition at line 77 of file RingBuffer.h.
    {
        T tValue = get();
        incIdx(m_iReadIdx);
        return tValue;
    }
References CRingBuffer< T >::get(), CRingBuffer< T >::incIdx(), and CRingBuffer< T >::m_iReadIdx.
Referenced by CMovingAverage::process().
getPostInc() [2/2]
template<class T > void CRingBuffer< T >::getPostInc (T * ptBuff, int iLength) inline
return the values starting at the current read index and increment the read pointer
Parameters
ptBuff pointer to where the values will be written
iLength number of values
Definition at line 88 of file RingBuffer.h.
    {
        get(ptBuff, iLength);
        incIdx(m_iReadIdx, iLength);
    }
References CRingBuffer< T >::get(), CRingBuffer< T >::incIdx(), and CRingBuffer< T >::m_iReadIdx.
getReadIdx()
template<class T > int CRingBuffer< T >::getReadIdx () const inline
return the current index for reading/get
Returns
int
Definition at line 163 of file RingBuffer.h.
    {
        return m_iReadIdx;
    }
References CRingBuffer< T >::m_iReadIdx.
Referenced by CBlockAudioFile::getNextBlock().
getWriteIdx()
template<class T > int CRingBuffer< T >::getWriteIdx () const inline
return the current index for writing/put
Returns
int
Definition at line 147 of file RingBuffer.h.
    {
        return m_iWriteIdx;
    }
References CRingBuffer< T >::m_iWriteIdx.
incIdx()
template<class T > void CRingBuffer< T >::incIdx (int & iIdx, int iOffset = 1) inline private
Definition at line 196 of file RingBuffer.h.
    {
        while ((iIdx + iOffset) < 0)
        {
            // avoid negative buffer indices
            iOffset += m_iBuffLength;
        }
        iIdx = (iIdx + iOffset) % m_iBuffLength;
    };
References CRingBuffer< T >::m_iBuffLength.
Referenced by CRingBuffer< T >::getPostInc(), CRingBuffer< T >::putPostInc(), CRingBuffer< T >::setReadIdx(), and CRingBuffer< T >::setWriteIdx().
operator=()
template<class T > CRingBuffer & CRingBuffer< T >::operator= (const CRingBuffer< T > & c) private
put() [1/2]
template<class T > void CRingBuffer< T >::put (const T * ptNewBuff, int iLength) inline
add new values of type T to write index
Parameters
ptNewBuff new values
iLength number of values
Definition at line 62 of file RingBuffer.h.
    {
        assert(iLength <= m_iBuffLength && iLength >= 0);
        // copy two parts: to the end of buffer and after wrap around
        int iNumValues2End = std::min(iLength, m_iBuffLength - m_iWriteIdx);
        std::memcpy(&m_ptBuff[m_iWriteIdx], ptNewBuff, sizeof(T) * iNumValues2End);
        if ((iLength - iNumValues2End) > 0)
            std::memcpy(m_ptBuff, &ptNewBuff[iNumValues2End], sizeof(T) * (static_cast<long long>(iLength) - iNumValues2End));
    }
References CRingBuffer< T >::m_iBuffLength, CRingBuffer< T >::m_iWriteIdx, and CRingBuffer< T >::m_ptBuff.
put() [2/2]
template<class T > void CRingBuffer< T >::put (T tNewValue) inline
add a new value of type T to write index
Parameters
tNewValue the new value
Definition at line 53 of file RingBuffer.h.
    {
        m_ptBuff[m_iWriteIdx] = tNewValue;
    }
References CRingBuffer< T >::m_iWriteIdx, and CRingBuffer< T >::m_ptBuff.
Referenced by CRingBuffer< T >::putPostInc().
putPostInc() [1/2]
template<class T > void CRingBuffer< T >::putPostInc (const T * ptNewBuff, int iLength) inline
add new values of type T to write index and increment write index
Parameters
ptNewBuff new values
iLength number of values
Definition at line 44 of file RingBuffer.h.
    {
        put(ptNewBuff, iLength);
        incIdx(m_iWriteIdx, iLength);
    }
References CRingBuffer< T >::incIdx(), CRingBuffer< T >::m_iWriteIdx, and CRingBuffer< T >::put().
putPostInc() [2/2]
template<class T > void CRingBuffer< T >::putPostInc (T tNewValue) inline
add a new value of type T to write index and increment write index
Parameters
tNewValue the new value
Definition at line 34 of file RingBuffer.h.
    {
        put(tNewValue);
        incIdx(m_iWriteIdx);
    }
References CRingBuffer< T >::incIdx(), CRingBuffer< T >::m_iWriteIdx, and CRingBuffer< T >::put().
Referenced by CMovingAverage::process(), and CBlockAudioFile::readFile2RingBuff().
reset()
template<class T > void CRingBuffer< T >::reset () inline
set buffer content and indices to 0
Definition at line 137 of file RingBuffer.h.
    {
        std::memset(m_ptBuff, 0, sizeof(T) * m_iBuffLength);
        m_iReadIdx = 0;
        m_iWriteIdx = 0;
    }
References CRingBuffer< T >::m_iBuffLength, CRingBuffer< T >::m_iReadIdx, CRingBuffer< T >::m_iWriteIdx, and CRingBuffer< T >::m_ptBuff.
Referenced by CRingBuffer< T >::CRingBuffer(), and CMovingAverage::reset().
setReadIdx()
template<class T > void CRingBuffer< T >::setReadIdx (int iNewReadIdx) inline
move the read index to a new position
Parameters
iNewReadIdx new position
Definition at line 171 of file RingBuffer.h.
    {
        incIdx(m_iReadIdx, iNewReadIdx - m_iReadIdx);
    }
References CRingBuffer< T >::incIdx(), and CRingBuffer< T >::m_iReadIdx.
Referenced by CKeyFromChroma::getKey(), CBlockAudioFile::getNextBlock(), CMovingAverage::reset(), and CMovingAverage::setFilterParam().
setWriteIdx()
template<class T > void CRingBuffer< T >::setWriteIdx (int iNewWriteIdx) inline
move the write index to a new position
Parameters
iNewWriteIdx new position
Definition at line 155 of file RingBuffer.h.
    {
        incIdx(m_iWriteIdx, iNewWriteIdx - m_iWriteIdx);
    }
References CRingBuffer< T >::incIdx(), and CRingBuffer< T >::m_iWriteIdx.
Member Data Documentation
m_iBuffLength
template<class T > int CRingBuffer< T >::m_iBuffLength = 0 private
length of the internal buffer
Definition at line 206 of file RingBuffer.h.
Referenced by CRingBuffer< T >::CRingBuffer(), CRingBuffer< T >::get(), CRingBuffer< T >::getLength(), CRingBuffer< T >::getNumValuesInBuffer(), CRingBuffer< T >::incIdx(), CRingBuffer< T >::put(), and CRingBuffer< T >::reset().
m_iReadIdx
template<class T > int CRingBuffer< T >::m_iReadIdx = 0 private
current read index
Definition at line 207 of file RingBuffer.h.
Referenced by CRingBuffer< T >::get(), CRingBuffer< T >::getNumValuesInBuffer(), CRingBuffer< T >::getPostInc(), CRingBuffer< T >::getReadIdx(), CRingBuffer< T >::reset(), and CRingBuffer< T >::setReadIdx().
m_iWriteIdx
template<class T > int CRingBuffer< T >::m_iWriteIdx = 0 private
current write index
Definition at line 208 of file RingBuffer.h.
Referenced by CRingBuffer< T >::getNumValuesInBuffer(), CRingBuffer< T >::getWriteIdx(), CRingBuffer< T >::put(), CRingBuffer< T >::putPostInc(), CRingBuffer< T >::reset(), and CRingBuffer< T >::setWriteIdx().
m_ptBuff
template<class T > T* CRingBuffer< T >::m_ptBuff = 0 private
data buffer
Definition at line 210 of file RingBuffer.h.
Referenced by CRingBuffer< T >::CRingBuffer(), CRingBuffer< T >::get(), CRingBuffer< T >::put(), CRingBuffer< T >::reset(), and CRingBuffer< T >::~CRingBuffer().
The documentation for this class was generated from the following file:
RingBuffer.h