ACA: CBeatHistoIf Class Reference
CBeatHistoIf Class Reference
class for computation of a BeatHistogram from either a file or a vector
#include <BeatHisto.h>
Public Types
enum BeatHisto_t { kBeatHistoCorr , kBeatHistoFft , kNumBeatHistoComputations }
enum to index all BeatHistogram computations
Public Member Functions
Error_t getNumBins (int &iNumBeatHistoBins, BeatHisto_t eBeatHistoComp) const
int getNumBins (BeatHisto_t eBeatHistoComp) const
Error_t getBeatHistoAxisTicks (float *pfAxisTicks, BeatHisto_t eBeatHistoComp) const
Error_t compBeatHisto (float *pfBeatHisto, BeatHisto_t eBeatHistoComp=kBeatHistoFft)
Static Public Member Functions
static Error_t create (CBeatHistoIf *&pCInstance, const std::string &strAudioFilePath, int iBlockLength=1024, int iHopLength=8)
static Error_t create (CBeatHistoIf *&pCInstance, const float *pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength=1024, int iHopLength=8)
static Error_t destroy (CBeatHistoIf *&pCInstance)
Protected Member Functions
CBeatHistoIf (int iBlockLength, int iHopLength, float fSampleRate)
virtual ~CBeatHistoIf ()
CBeatHistoIf (const CBeatHistoIf &that)
CBeatHistoIf & operator= (const CBeatHistoIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (const std::string &strAudioFilePath)
init configuration
Error_t init_ (const float *pfAudio, long long iNumFrames, float fSampleRate)
init configuration
void compHistoRange_ (int &istartIdx, int &istopIdx, BeatHisto_t eBeatHistoComp) const
Protected Attributes
CFft * m_pCFft = 0
fft instance
CCcf * m_pCCcf = 0
correlation instance
CNoveltyIf * m_pCNovelty = 0
novelty function extraction instance
float * m_pfNovelty = 0
buffer to hold extracted nvelty function
float * m_pfProcessBuff = 0
temporary processing buffer
float * m_pfBeatHisto = 0
result buffer
int m_iBlockLength = 0
processing block length for novelty
int m_iHopLength = 0
hop length for novelty
const int m_iBeatHistoLength = 65536
default length of FFT
float m_fSampleRate = 0
sample rate
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a BeatHistogram from either a file or a vector
Definition at line 15 of file BeatHisto.h.
Member Enumeration Documentation
BeatHisto_t
enum CBeatHistoIf::BeatHisto_t
enum to index all BeatHistogram computations
Enumerator
kBeatHistoCorr
use correlation based method
kBeatHistoFft
use FFT based method
kNumBeatHistoComputations
Definition at line 20 of file BeatHisto.h.
    {
        kBeatHistoCorr, //!< use correlation based method
        kBeatHistoFft, //!< use FFT based method
        kNumBeatHistoComputations
    };
Constructor & Destructor Documentation
CBeatHistoIf() [1/2]
CBeatHistoIf::CBeatHistoIf (int iBlockLength, int iHopLength, float fSampleRate) inline explicit protected
Definition at line 82 of file BeatHisto.h.
                                                                               :
        m_iBlockLength(iBlockLength),
        m_iHopLength(iHopLength),
        m_fSampleRate(fSampleRate)
    {};
Referenced by create().
~CBeatHistoIf()
CBeatHistoIf::~CBeatHistoIf () inline protected virtual
Definition at line 14 of file BeatHisto.cpp.
{
    reset_();
}
References reset_().
CBeatHistoIf() [2/2]
CBeatHistoIf::CBeatHistoIf (const CBeatHistoIf & that) protected
Member Function Documentation
compBeatHisto()
Error_t CBeatHistoIf::compBeatHisto (float * pfBeatHisto, BeatHisto_t eBeatHistoComp = kBeatHistoFft)
performs the BeatHisto computation for 1 dimensional BeatHistos and writes the result
Parameters
pfBeatHisto (user-allocated, to be written, dimensions from CBeatHistoIf::getNumBins)
eBeatHistoComp computation method
Returns
Error_t
Definition at line 113 of file BeatHisto.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!pfBeatHisto)
        return Error_t::kFunctionInvalidArgsError;
    CBlockAudioIf* pCBlock = 0;
    int aiBeatHistoRange[2] = { 0,0 };
    int iBeatHistoLength = getNumBins(eBeatHistoComp);
    int iHopSize = m_iBeatHistoLength >> 2;
    assert(iHopSize > 0);
    m_pCNovelty->compNovelty(m_pfNovelty);
    // create a blocking instance to use it on the Novelty function
    CBlockAudioIf::create(pCBlock, m_pfNovelty, m_pCNovelty->getNumBlocks(), m_iBeatHistoLength, iHopSize, m_fSampleRate / m_iHopLength);
    long long iNumBlocks = pCBlock->getNumBlocks();
    if (eBeatHistoComp == kBeatHistoCorr)
    {
        CCcf* pCAcf = new CCcf();
        // create correlation instance with zeropadding
        pCAcf->init(m_iBeatHistoLength);
        // loop over novelty functions with hopsize
        CVector::setZero(m_pfBeatHisto, m_iBeatHistoLength);
        for (auto n = 0; n < iNumBlocks; n++)
        {
            // get next novelty block
            pCBlock->getNextBlock(m_pfProcessBuff);
            // compute magnitude spectrum
            pCAcf->compCcf(m_pfProcessBuff, m_pfProcessBuff);
            pCAcf->getCcf(m_pfProcessBuff, true);
            // accumulate average spectrum
            CVector::add_I(m_pfBeatHisto, m_pfProcessBuff, m_iBeatHistoLength);
        }
        CVector::flip_I(m_pfBeatHisto, m_iBeatHistoLength);
        // destroy correlation instance
        delete pCAcf;
    }
    else if (eBeatHistoComp == kBeatHistoFft)
    {
        CFft *pCFft = new CFft();
        // create FFT instance with zeropadding
        pCFft->init(m_iBeatHistoLength, 2);
        // loop over novelty functions with hopsize
        CVector::setZero(m_pfBeatHisto, m_iBeatHistoLength);
        for (auto n = 0; n < iNumBlocks; n++)
        {
            // get next novelty block
            pCBlock->getNextBlock(m_pfProcessBuff);
            // compute magnitude spectrum
            pCFft->compFft(m_pfProcessBuff, m_pfProcessBuff);
            pCFft->getMagnitude(m_pfProcessBuff, m_pfProcessBuff);
            // accumulate average spectrum
            CVector::add_I(m_pfBeatHisto, m_pfProcessBuff, m_iBeatHistoLength);
        }
        // destroy FFT instance
        delete pCFft;
    }
    else
        return Error_t::kFunctionInvalidArgsError;
    // restrict output BPM to 30-200
    compHistoRange_(aiBeatHistoRange[0], aiBeatHistoRange[1], eBeatHistoComp);
    // copy to output
    //CVector::moveInMem(m_pfBeatHisto, 0, aiBeatHistoRange[0], aiBeatHistoRange[1] - aiBeatHistoRange[0] + 1);
    //CVector::setZero(&m_pfBeatHisto[aiBeatHistoRange[1] - aiBeatHistoRange[0] + 1], iBeatHistoLength - (aiBeatHistoRange[1] - aiBeatHistoRange[0] + 1));
    CVector::copy(pfBeatHisto, &m_pfBeatHisto[aiBeatHistoRange[0]], iBeatHistoLength);
    // create BPM axis labels
    // normalize result
    CNormalizeAudio::normalizeSignal(pfBeatHisto, iBeatHistoLength);
    // cleanup
    CBlockAudioIf::destroy(pCBlock);
    return Error_t::kNoError;
}
References CVector::add_I(), CCcf::compCcf(), CFft::compFft(), compHistoRange_(), CNoveltyIf::compNovelty(), CVector::copy(), CBlockAudioIf::create(), CBlockAudioIf::destroy(), CVector::flip_I(), CCcf::getCcf(), CFft::getMagnitude(), CBlockAudioIf::getNextBlock(), getNumBins(), CBlockAudioIf::getNumBlocks(), CNoveltyIf::getNumBlocks(), CCcf::init(), CFft::init(), kBeatHistoCorr, kBeatHistoFft, kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSampleRate, m_iBeatHistoLength, m_iHopLength, m_pCNovelty, m_pfBeatHisto, m_pfNovelty, m_pfProcessBuff, CNormalizeAudio::normalizeSignal(), and CVector::setZero().
Referenced by main().
compHistoRange_()
void CBeatHistoIf::compHistoRange_ (int & istartIdx, int & istopIdx, BeatHisto_t eBeatHistoComp) const inline protected
Definition at line 270 of file BeatHisto.cpp.
{
    const float afBpmRange[2] = { 30.F, 200.F };
    if (eBeatHistoComp == kBeatHistoFft)
    {
        iStartIdx = static_cast<int>(CConversion::convertFreq2Bin(afBpmRange[0] / 60.F, m_iBeatHistoLength << 1, m_fSampleRate / m_iHopLength));
        iStopIdx = static_cast<int>(CConversion::convertFreq2Bin(afBpmRange[1] / 60.F, m_iBeatHistoLength << 1, m_fSampleRate / m_iHopLength)) + 1;
    }
    else
    {
        iStartIdx = m_iBeatHistoLength - static_cast<int>(60.F * m_fSampleRate / m_iHopLength / afBpmRange[0]);
        iStopIdx = m_iBeatHistoLength - static_cast<int>(60.F * m_fSampleRate / m_iHopLength / afBpmRange[1]);
    }
}
References CConversion::convertFreq2Bin(), kBeatHistoFft, m_fSampleRate, m_iBeatHistoLength, and m_iHopLength.
Referenced by compBeatHisto(), getBeatHistoAxisTicks(), and getNumBins().
create() [1/2]
Error_t CBeatHistoIf::create (CBeatHistoIf *& pCInstance, const float * pfAudio, long long iNumFrames, float fSampleRate, int iBlockLength = 1024, int iHopLength = 8) static
initializes a BeatHisto instance from audio data
Parameters
pCInstance pointer to instance to be written
pfAudio complete audio data
iNumFrames length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in Frames
iHopLength hop length in Frames
Returns
Error_t
Definition at line 35 of file BeatHisto.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumFrames <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CBeatHistoIf(iBlockLength, iHopLength, fSampleRate);
    assert(pCInstance);
    return pCInstance->init_(pfAudio, iNumFrames, fSampleRate);
}
References CBeatHistoIf(), init_(), and kFunctionInvalidArgsError.
create() [2/2]
Error_t CBeatHistoIf::create (CBeatHistoIf *& pCInstance, const std::string & strAudioFilePath, int iBlockLength = 1024, int iHopLength = 8) static
initializes a BeatHisto instance with file reading
Parameters
pCInstance pointer to instance to be written
strAudioFilePath complete path to audio file
iBlockLength FFT block length in Frames
iHopLength hop length in Frames
Returns
Error_t
Definition at line 19 of file BeatHisto.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CBeatHistoIf(iBlockLength, iHopLength, 0.F);
    assert(pCInstance);
    return pCInstance->init_(strAudioFilePath);
}
References CBeatHistoIf(), init_(), CUtil::isPowOf2(), and kFunctionInvalidArgsError.
Referenced by main().
destroy()
Error_t CBeatHistoIf::destroy (CBeatHistoIf *& pCInstance) static
destroys a BeatHisto instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 55 of file BeatHisto.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by main().
getBeatHistoAxisTicks()
Error_t CBeatHistoIf::getBeatHistoAxisTicks (float * pfAxisTicks, BeatHisto_t eBeatHistoComp) const
returns axis ticks
Parameters
pfAxisTicks (to be written) in BPM, length equals iNumBins
eBeatHistoComp (computation method used in CBeatHistoIf::compBeatHisto)
Returns
Error_t
Definition at line 82 of file BeatHisto.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    int aiRangeIndices[2] = { 0,0 };
    compHistoRange_(aiRangeIndices[0], aiRangeIndices[1], eBeatHistoComp);
    if (eBeatHistoComp == kBeatHistoFft)
    {
        for (auto k = aiRangeIndices[0], j = 0; k <= aiRangeIndices[1]; k++, j++)
            pfAxisTicks[j] = 60.F * CConversion::convertBin2Freq(1.F * k, m_iBeatHistoLength << 1, m_fSampleRate / m_iHopLength);
    }
    else
    {
        for (auto k = aiRangeIndices[0], j = 0; k <= aiRangeIndices[1]; k++, j++)
            pfAxisTicks[j] = 60.F / m_iHopLength *  m_fSampleRate / (m_iBeatHistoLength - k);
    }
    return Error_t::kNoError;
}
References compHistoRange_(), CConversion::convertBin2Freq(), kBeatHistoFft, kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSampleRate, m_iBeatHistoLength, m_iBlockLength, and m_iHopLength.
getNumBins() [1/2]
int CBeatHistoIf::getNumBins (BeatHisto_t eBeatHistoComp) const
returns length of the frequency axis of the beat histogram
Parameters
eBeatHistoComp (computation method used in CBeatHistoIf::compBeatHisto)
Returns
ing number bins
Definition at line 75 of file BeatHisto.cpp.
{
    int aiRangeIndices[2] = { 0,0 };
    compHistoRange_(aiRangeIndices[0], aiRangeIndices[1], eBeatHistoComp);
    return aiRangeIndices[1] - aiRangeIndices[0] + 1;
}
References compHistoRange_().
getNumBins() [2/2]
Error_t CBeatHistoIf::getNumBins (int & iNumBeatHistoBins, BeatHisto_t eBeatHistoComp) const
returns length of the frequency axis of the beat histogram
Parameters
iNumBeatHistoBins (number of bins, to be written)
eBeatHistoComp (computation method used in CBeatHistoIf::compBeatHisto)
Returns
Error_t
Definition at line 63 of file BeatHisto.cpp.
{
    if (!m_bIsInitialized)
    {
        iLengthOfBeatHisto = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iLengthOfBeatHisto = this->getNumBins(eBeatHistoComp);
    return Error_t::kNoError;
}
References getNumBins(), kFunctionIllegalCallError, kNoError, and m_bIsInitialized.
Referenced by compBeatHisto(), getNumBins(), and main().
init_() [1/2]
Error_t CBeatHistoIf::init_ (const float * pfAudio, long long iNumFrames, float fSampleRate) protected
init configuration
Definition at line 250 of file BeatHisto.cpp.
{
    if (Error_t::kNoError == CNoveltyIf::create(m_pCNovelty, CNoveltyIf::kNoveltyFlux, pfAudio, iNumFrames, fSampleRate, m_iBlockLength, m_iHopLength))
    {
        int iNumBlocks = 0;
        m_pCNovelty->getNumBlocks(iNumBlocks);
        assert(iNumBlocks > 2);
        CVector::alloc(m_pfNovelty, iNumBlocks);
        CVector::alloc(m_pfProcessBuff, static_cast<long long>(m_iBeatHistoLength) * 2);
        CVector::alloc(m_pfBeatHisto, static_cast<long long>(m_iBeatHistoLength) + 1);
        m_bIsInitialized = true;
        return Error_t::kNoError;
    }
    else
        return Error_t::kMemError;
}
References CVector::alloc(), CNoveltyIf::create(), CNoveltyIf::getNumBlocks(), kMemError, kNoError, CNoveltyIf::kNoveltyFlux, m_bIsInitialized, m_iBeatHistoLength, m_iBlockLength, m_iHopLength, m_pCNovelty, m_pfBeatHisto, m_pfNovelty, and m_pfProcessBuff.
init_() [2/2]
Error_t CBeatHistoIf::init_ (const std::string & strAudioFilePath) protected
init configuration
Definition at line 227 of file BeatHisto.cpp.
{
    if (Error_t::kNoError == CNoveltyIf::create(m_pCNovelty, CNoveltyIf::kNoveltyFlux, strAudioFilePath, m_iBlockLength, m_iHopLength))
    {
        int iNumBlocks = 0;
        m_pCNovelty->getNumBlocks(iNumBlocks);
        assert(iNumBlocks > 2);
        CVector::alloc(m_pfNovelty, iNumBlocks);
        m_pCNovelty->getTimeStamps(m_pfNovelty);
        m_fSampleRate = m_iHopLength / (m_pfNovelty[1] - m_pfNovelty[0]);
        CVector::alloc(m_pfProcessBuff, static_cast<long long>(m_iBeatHistoLength) * 2);
        CVector::alloc(m_pfBeatHisto, static_cast<long long>(m_iBeatHistoLength) + 1);
        m_bIsInitialized = true;
        return Error_t::kNoError;
    }
    else
        return Error_t::kMemError;
}
References CVector::alloc(), CNoveltyIf::create(), CNoveltyIf::getNumBlocks(), CNoveltyIf::getTimeStamps(), kMemError, kNoError, CNoveltyIf::kNoveltyFlux, m_bIsInitialized, m_fSampleRate, m_iBeatHistoLength, m_iBlockLength, m_iHopLength, m_pCNovelty, m_pfBeatHisto, m_pfNovelty, and m_pfProcessBuff.
Referenced by create().
operator=()
CBeatHistoIf & CBeatHistoIf::operator= (const CBeatHistoIf & c) protected
reset_()
Error_t CBeatHistoIf::reset_ () protected
reset configuration
Definition at line 210 of file BeatHisto.cpp.
{
    CVector::free(m_pfNovelty);
    CVector::free(m_pfProcessBuff);
    CVector::free(m_pfBeatHisto);
    m_iBlockLength = 0;
    m_iHopLength = 0;
    m_fSampleRate = 0;
    CNoveltyIf::destroy(m_pCNovelty);
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CNoveltyIf::destroy(), CVector::free(), kNoError, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, m_pCNovelty, m_pfBeatHisto, m_pfNovelty, and m_pfProcessBuff.
Referenced by ~CBeatHistoIf().
Member Data Documentation
m_bIsInitialized
bool CBeatHistoIf::m_bIsInitialized = false protected
true if initialized
Definition at line 114 of file BeatHisto.h.
Referenced by compBeatHisto(), getBeatHistoAxisTicks(), getNumBins(), init_(), and reset_().
m_fSampleRate
float CBeatHistoIf::m_fSampleRate = 0 protected
sample rate
Definition at line 112 of file BeatHisto.h.
Referenced by compBeatHisto(), compHistoRange_(), getBeatHistoAxisTicks(), init_(), and reset_().
m_iBeatHistoLength
const int CBeatHistoIf::m_iBeatHistoLength = 65536 protected
default length of FFT
Definition at line 110 of file BeatHisto.h.
Referenced by compBeatHisto(), compHistoRange_(), getBeatHistoAxisTicks(), and init_().
m_iBlockLength
int CBeatHistoIf::m_iBlockLength = 0 protected
processing block length for novelty
Definition at line 107 of file BeatHisto.h.
Referenced by getBeatHistoAxisTicks(), init_(), and reset_().
m_iHopLength
int CBeatHistoIf::m_iHopLength = 0 protected
hop length for novelty
Definition at line 108 of file BeatHisto.h.
Referenced by compBeatHisto(), compHistoRange_(), getBeatHistoAxisTicks(), init_(), and reset_().
m_pCCcf
CCcf* CBeatHistoIf::m_pCCcf = 0 protected
correlation instance
Definition at line 99 of file BeatHisto.h.
m_pCFft
CFft* CBeatHistoIf::m_pCFft = 0 protected
fft instance
Definition at line 98 of file BeatHisto.h.
m_pCNovelty
CNoveltyIf* CBeatHistoIf::m_pCNovelty = 0 protected
novelty function extraction instance
Definition at line 101 of file BeatHisto.h.
Referenced by compBeatHisto(), init_(), and reset_().
m_pfBeatHisto
float* CBeatHistoIf::m_pfBeatHisto = 0 protected
result buffer
Definition at line 105 of file BeatHisto.h.
Referenced by compBeatHisto(), init_(), and reset_().
m_pfNovelty
float* CBeatHistoIf::m_pfNovelty = 0 protected
buffer to hold extracted nvelty function
Definition at line 103 of file BeatHisto.h.
Referenced by compBeatHisto(), init_(), and reset_().
m_pfProcessBuff
float* CBeatHistoIf::m_pfProcessBuff = 0 protected
temporary processing buffer
Definition at line 104 of file BeatHisto.h.
Referenced by compBeatHisto(), init_(), and reset_().
The documentation for this class was generated from the following files:
BeatHisto.h
BeatHisto.cpp