ACA: CFeatureFromBlockIf Class Reference
CFeatureFromBlockIf Class Reference
class for computation of a feature from a block of data (e.g., time or magnitude spectrum)
#include <FeatureFromBlock.h>
Public Member Functions
virtual int getFeatureDimensions () const
CFeatureIf::Feature_t getFeatureIdx () const
virtual Error_t compFeature (float *pfFeature, const float *pfInput)
virtual bool hasAdditionalParam () const
virtual Error_t setAdditionalParam (float fParamValue)
Static Public Member Functions
static Error_t create (CFeatureFromBlockIf *&pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate=1.F)
static Error_t destroy (CFeatureFromBlockIf *&pCInstance)
static float compFeatureSpectralCentroid (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralCrestFactor (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralDecrease (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlatness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralFlux (const float *pfMagSpec, const float *pfPrevSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralKurtosis (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralRolloff (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fKappa=.85F)
static float compFeatureSpectralSkewness (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSlope (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralSpread (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F)
static float compFeatureSpectralTonalPowerRatio (const float *pfMagSpec, int iDataLength, float fSampleRate=1.F, float fThresh=5e-4)
static float compFeatureTimeAcfCoeff (const float *pfSamples, int iDataLength, float fSampleRate=1.F, int iEta=19)
static float compFeatureTimePeakEnvelope (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeRms (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeStd (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
static float compFeatureTimeZeroCrossingRate (const float *pfSamples, int iDataLength, float fSampleRate=1.F)
Static Public Attributes
static const float m_kfFloatThresh = 1e-30F
below this we just assume it's zero
Protected Member Functions
CFeatureFromBlockIf ()
CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate)
virtual ~CFeatureFromBlockIf ()
CFeatureFromBlockIf (const CFeatureFromBlockIf &that)
CFeatureFromBlockIf & operator= (const CFeatureFromBlockIf &c)
Protected Attributes
CFeatureIf::Feature_t m_eFeatureIdx = CFeatureIf::kNumFeatures
index of feature to extract
int m_iDataLength = 0
block length
float m_fSampleRate = 0
sample rate
const std::map< CFeatureIf::Feature_t, std::function< float(const float *, int, float)> > m_DispatchMap
Detailed Description
class for computation of a feature from a block of data (e.g., time or magnitude spectrum)
Definition at line 14 of file FeatureFromBlock.h.
Constructor & Destructor Documentation
CFeatureFromBlockIf() [1/3]
CFeatureFromBlockIf::CFeatureFromBlockIf () inline protected
Definition at line 88 of file FeatureFromBlock.h.
{};
Referenced by create().
CFeatureFromBlockIf() [2/3]
CFeatureFromBlockIf::CFeatureFromBlockIf (CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate) protected
Definition at line 323 of file FeatureFromBlock.cpp.
: m_eFeatureIdx(eFeatureIdx), m_iDataLength(iDataLength), m_fSampleRate(fSampleRate) { assert(iDataLength > 0); }
~CFeatureFromBlockIf()
virtual CFeatureFromBlockIf::~CFeatureFromBlockIf () inline protected virtual
Definition at line 90 of file FeatureFromBlock.h.
{};
CFeatureFromBlockIf() [3/3]
CFeatureFromBlockIf::CFeatureFromBlockIf (const CFeatureFromBlockIf & that) protected
Member Function Documentation
compFeature()
Error_t CFeatureFromBlockIf::compFeature (float * pfFeature, const float * pfInput) virtual
performs the FeatureFromBlock computation
Parameters
pfFeature feature result (user-allocated, to be written, length from CFeatureFromBlockIf::getFeatureDimensions)
pfInput input data of length iDataLength
Returns
Error_t
Reimplemented in CFeatureSpectralFlux, CFeatureSpectralMfccs, CFeatureSpectralPitchChroma, CFeatureSpectralRolloff, CFeatureSpectralTonalPowerRatio, CFeatureTimeAcfCoeff, CFeatureTimeMaxAcf, CFeatureTimePeakEnvelope, and CFeatureTimeRms.
Definition at line 1027 of file FeatureFromBlock.cpp.
{
    // default: use one of the static functions
    *pfFeature = m_DispatchMap.at(m_eFeatureIdx)(pfInput, m_iDataLength, m_fSampleRate);
    return Error_t::kNoError;
}
References kNoError, m_DispatchMap, m_eFeatureIdx, m_fSampleRate, and m_iDataLength.
Referenced by CChordFromBlockIf::compChordProb(), CFeatureIf::compFeature1Dim(), and CFeatureIf::compFeatureNDim().
compFeatureSpectralCentroid()
float CFeatureFromBlockIf::compFeatureSpectralCentroid (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 16 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    float fNorm = 0;
    float fvsc = 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        fNorm += pfMagSpec[k];
        fvsc += k * pfMagSpec[k];
    }
    if (fNorm < m_kfFloatThresh)
        return 0;
    // convert from index to Hz
    return fvsc * fSampleRate / (2.F * fNorm * (iDataLength - 1));
}
References m_kfFloatThresh.
Referenced by compFeatureSpectralKurtosis(), compFeatureSpectralSkewness(), compFeatureSpectralSlope(), and compFeatureSpectralSpread().
compFeatureSpectralCrestFactor()
float CFeatureFromBlockIf::compFeatureSpectralCrestFactor (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 38 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    float fNorm = CVector::getSum(pfMagSpec, iDataLength);
    if (fNorm < m_kfFloatThresh)
        return 0;
    return CVector::getMax(pfMagSpec, iDataLength) / fNorm;
}
References CVector::getMax(), CVector::getSum(), and m_kfFloatThresh.
compFeatureSpectralDecrease()
float CFeatureFromBlockIf::compFeatureSpectralDecrease (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 51 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    float fNorm = 0;
    float fvsd = 0;
    for (auto k = 1; k < iDataLength; k++)
    {
        fNorm += pfMagSpec[k];
        fvsd += (pfMagSpec[k] - pfMagSpec[0]) / k;
    }
    if (fNorm < m_kfFloatThresh)
        return 0;
    return fvsd / fNorm;
}
References m_kfFloatThresh.
compFeatureSpectralFlatness()
float CFeatureFromBlockIf::compFeatureSpectralFlatness (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 71 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    float fNorm = CVector::getMean(pfMagSpec, iDataLength);
    float fGeoMean = 0;
    // avoid unnecessary complications
    if (fNorm < m_kfFloatThresh || CVector::getMin(pfMagSpec, iDataLength) < m_kfFloatThresh)
        return 0;
    // compute geometric mean through log
    for (auto k = 0; k < iDataLength; k++)
        fGeoMean += std::log(pfMagSpec[k]);
    return std::exp(fGeoMean / iDataLength) / fNorm;
}
References CVector::getMean(), CVector::getMin(), and m_kfFloatThresh.
compFeatureSpectralFlux()
float CFeatureFromBlockIf::compFeatureSpectralFlux (const float * pfMagSpec, const float * pfPrevSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 90 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(pfPrevSpec);
    assert(iDataLength > 0);
    float fSum = 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fDiff = pfMagSpec[k] - pfPrevSpec[k];
        fSum += fDiff * fDiff;
    }
    return std::sqrt(fSum) / iDataLength;
}
Referenced by CFeatureSpectralFlux::compFeature().
compFeatureSpectralKurtosis()
float CFeatureFromBlockIf::compFeatureSpectralKurtosis (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 130 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    float fNorm = 0;
    float fvsk = 0;
    float fvsc = compFeatureSpectralCentroid(pfMagSpec, iDataLength, fSampleRate) * 2 / fSampleRate * (iDataLength - 1);
    float fvss = compFeatureSpectralSpread(pfMagSpec, iDataLength, fSampleRate) * 2 / fSampleRate * (iDataLength - 1);
    if (fvsc < m_kfFloatThresh || fvss < m_kfFloatThresh)
        return 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fAgg = (k - fvsc) * (k - fvsc);
        fAgg *= fAgg;
        fNorm += pfMagSpec[k];
        fvsk += fAgg * pfMagSpec[k];
    }
    if (fNorm < m_kfFloatThresh)
        return 0;
    return fvsk / (fvss * fvss * fvss * fvss * fNorm) - 3;
}
References compFeatureSpectralCentroid(), compFeatureSpectralSpread(), and m_kfFloatThresh.
compFeatureSpectralRolloff()
float CFeatureFromBlockIf::compFeatureSpectralRolloff (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F, float fKappa = .85F) static
Definition at line 158 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    assert(fKappa > 0 && fKappa <= 1);
    float fNorm = CVector::getSum(pfMagSpec, iDataLength);
    float fSum = 0;
    int k = 0;
    if (fNorm < m_kfFloatThresh)
        return 0;
    fNorm *= fKappa;
    while (fSum <= fNorm)
    {
        fSum += pfMagSpec[k];
        k++;
        assert(k < iDataLength);
    }
    // convert from index to Hz
    return (k - 1) * fSampleRate / (2.F * (iDataLength - 1));
}
References CVector::getSum(), and m_kfFloatThresh.
Referenced by CFeatureSpectralRolloff::compFeature().
compFeatureSpectralSkewness()
float CFeatureFromBlockIf::compFeatureSpectralSkewness (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 185 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    float fNorm = 0;
    float fvssk = 0;
    float fvsc = compFeatureSpectralCentroid(pfMagSpec, iDataLength, fSampleRate) * 2 / fSampleRate * (iDataLength - 1);
    float fvss = compFeatureSpectralSpread(pfMagSpec, iDataLength, fSampleRate) * 2 / fSampleRate * (iDataLength - 1);
    if (fvsc < m_kfFloatThresh || fvss < m_kfFloatThresh)
        return 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fAgg = (k - fvsc) * (k - fvsc) * (k - fvsc);
        fNorm += pfMagSpec[k];
        fvssk += fAgg * pfMagSpec[k];
    }
    if (fNorm < m_kfFloatThresh)
        return 0;
    return fvssk / (fvss * fvss * fvss * fNorm);
}
References compFeatureSpectralCentroid(), compFeatureSpectralSpread(), and m_kfFloatThresh.
compFeatureSpectralSlope()
float CFeatureFromBlockIf::compFeatureSpectralSlope (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 212 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    // compute mean
    float fvsc = compFeatureSpectralCentroid(pfMagSpec, iDataLength, fSampleRate) * 2 / fSampleRate * (iDataLength - 1);
    float fvssl = 0;
    float fNorm = 0;
    if (fvsc < m_kfFloatThresh)
        return 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fk = k - (iDataLength + 1) / 2.F;
        fvssl += fk * (pfMagSpec[k] - fvsc);
        fNorm += fk * fk;
    }
    if (fNorm < m_kfFloatThresh)
        return 0;
    return fvssl / fNorm;
}
References compFeatureSpectralCentroid(), and m_kfFloatThresh.
compFeatureSpectralSpread()
float CFeatureFromBlockIf::compFeatureSpectralSpread (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F) static
Definition at line 106 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    assert(fSampleRate > 0);
    float fNorm = 0;
    float fvss = 0;
    float fvsc = compFeatureSpectralCentroid(pfMagSpec, iDataLength, fSampleRate) * 2 / fSampleRate * (iDataLength - 1);
    if (fvsc < m_kfFloatThresh)
        return 0;
    for (auto k = 0; k < iDataLength; k++)
    {
        float fAgg = (k - fvsc) * (k - fvsc);
        fNorm += pfMagSpec[k];
        fvss += fAgg * pfMagSpec[k];
    }
    // convert from index to Hz
    return std::sqrt(fvss / fNorm) * fSampleRate / (2.F * (iDataLength - 1));
}
References compFeatureSpectralCentroid(), and m_kfFloatThresh.
Referenced by compFeatureSpectralKurtosis(), and compFeatureSpectralSkewness().
compFeatureSpectralTonalPowerRatio()
float CFeatureFromBlockIf::compFeatureSpectralTonalPowerRatio (const float * pfMagSpec, int iDataLength, float fSampleRate = 1.F, float fThresh = 5e-4) static
Definition at line 238 of file FeatureFromBlock.cpp.
{
    assert(pfMagSpec);
    assert(iDataLength > 0);
    // initialize
    float fvtpr = 0;
    float fNorm = pfMagSpec[0] * pfMagSpec[0] + pfMagSpec[iDataLength - 1] * pfMagSpec[iDataLength - 1];
    for (auto k = 1; k < iDataLength - 1; k++)
    {
        float fSquare = pfMagSpec[k] * pfMagSpec[k];
        fNorm += fSquare;
        // search for local maxima
        if (pfMagSpec[k] <= pfMagSpec[k - 1] || pfMagSpec[k] <= pfMagSpec[k + 1] || pfMagSpec[k] <= fThresh)
            continue;
        else
        {
            fvtpr += fSquare;
            // increment because the next bin cannot be a local max but don't forget fNorm
            fNorm += pfMagSpec[k + 1] * pfMagSpec[k + 1];
            k++;
        }
    }
    if (fNorm < m_kfFloatThresh)
        return 0;
    return fvtpr / fNorm;
}
References m_kfFloatThresh.
Referenced by CFeatureSpectralTonalPowerRatio::compFeature().
compFeatureTimeAcfCoeff()
float CFeatureFromBlockIf::compFeatureTimeAcfCoeff (const float * pfSamples, int iDataLength, float fSampleRate = 1.F, int iEta = 19) static
Definition at line 271 of file FeatureFromBlock.cpp.
{
    assert(pfSamples);
    assert(iDataLength > iEta);
    assert(iEta >= 0);
    return CVector::mulScalar(pfSamples, &pfSamples[iEta], static_cast<long long>(iDataLength) - iEta);
}
References CVector::mulScalar().
Referenced by CFeatureTimeAcfCoeff::compFeature().
compFeatureTimePeakEnvelope()
float CFeatureFromBlockIf::compFeatureTimePeakEnvelope (const float * pfSamples, int iDataLength, float fSampleRate = 1.F) static
Definition at line 280 of file FeatureFromBlock.cpp.
{
    assert(pfSamples);
    assert(iDataLength > 0);
    return CVector::getMax(pfSamples, iDataLength);
}
References CVector::getMax().
Referenced by CFeatureTimePeakEnvelope::compFeature().
compFeatureTimeRms()
float CFeatureFromBlockIf::compFeatureTimeRms (const float * pfSamples, int iDataLength, float fSampleRate = 1.F) static
Definition at line 296 of file FeatureFromBlock.cpp.
{
    assert(pfSamples);
    assert(iDataLength > 0);
    return CVector::getStd(pfSamples, iDataLength, 0.F);
}
References CVector::getStd().
Referenced by CFeatureTimeRms::compFeature().
compFeatureTimeStd()
float CFeatureFromBlockIf::compFeatureTimeStd (const float * pfSamples, int iDataLength, float fSampleRate = 1.F) static
Definition at line 288 of file FeatureFromBlock.cpp.
{
    assert(pfSamples);
    assert(iDataLength > 0);
    return CVector::getStd(pfSamples, iDataLength);
}
References CVector::getStd().
compFeatureTimeZeroCrossingRate()
float CFeatureFromBlockIf::compFeatureTimeZeroCrossingRate (const float * pfSamples, int iDataLength, float fSampleRate = 1.F) static
Definition at line 304 of file FeatureFromBlock.cpp.
{
    assert(pfSamples);
    assert(iDataLength > 0);
    float fvzc = 0;
    float fPrevSign = 0;
    for (auto i = 0; i < iDataLength; i++)
    {
        float fCurrSign = CUtil::sign(pfSamples[i]);
        fvzc += std::abs(fCurrSign - fPrevSign);
        fPrevSign = fCurrSign;
    }
    // standardize feature
    return fvzc / (2 * iDataLength);
}
References CUtil::sign().
create()
Error_t CFeatureFromBlockIf::create (CFeatureFromBlockIf *& pCInstance, CFeatureIf::Feature_t eFeatureIdx, int iDataLength, float fSampleRate = 1.F) static
initializes a FeatureFromBlock instance
Parameters
pCInstance pointer to instance to be written
eFeatureIdx index of Feature to extract
iDataLength block length
fSampleRate sample rate (only used when needed)
Returns
Error_t
Definition at line 950 of file FeatureFromBlock.cpp.
{
    if (iDataLength <= 0 || fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    switch (eFeatureIdx)
    {
    default:
    case CFeatureIf::kFeatureSpectralCentroid:
    case CFeatureIf::kFeatureSpectralCrestFactor:
    case CFeatureIf::kFeatureSpectralDecrease:
    case CFeatureIf::kFeatureSpectralFlatness:
    case CFeatureIf::kFeatureSpectralKurtosis:
    case CFeatureIf::kFeatureSpectralSkewness:
    case CFeatureIf::kFeatureSpectralSlope:
    case CFeatureIf::kFeatureSpectralSpread:
    case CFeatureIf::kFeatureTimeStd:
    case CFeatureIf::kFeatureTimeZeroCrossingRate:
        pCInstance = new CFeatureFromBlockIf(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureSpectralFlux:
        pCInstance = new CFeatureSpectralFlux(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureSpectralMfccs:
        pCInstance = new CFeatureSpectralMfccs(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureSpectralPitchChroma:
        pCInstance = new CFeatureSpectralPitchChroma(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureSpectralRolloff:
        pCInstance = new CFeatureSpectralRolloff(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureSpectralTonalPowerRatio:
        pCInstance = new CFeatureSpectralTonalPowerRatio(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureTimeAcfCoeff:
        pCInstance = new CFeatureTimeAcfCoeff(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureTimeMaxAcf:
        pCInstance = new CFeatureTimeMaxAcf(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureTimePeakEnvelope:
        pCInstance = new CFeatureTimePeakEnvelope(eFeatureIdx, iDataLength, fSampleRate);
        break;
    case CFeatureIf::kFeatureTimeRms:
        pCInstance = new CFeatureTimeRms(eFeatureIdx, iDataLength, fSampleRate);
        break;
    }
    return Error_t::kNoError;
}
References CFeatureFromBlockIf(), CFeatureIf::kFeatureSpectralCentroid, CFeatureIf::kFeatureSpectralCrestFactor, CFeatureIf::kFeatureSpectralDecrease, CFeatureIf::kFeatureSpectralFlatness, CFeatureIf::kFeatureSpectralFlux, CFeatureIf::kFeatureSpectralKurtosis, CFeatureIf::kFeatureSpectralMfccs, CFeatureIf::kFeatureSpectralPitchChroma, CFeatureIf::kFeatureSpectralRolloff, CFeatureIf::kFeatureSpectralSkewness, CFeatureIf::kFeatureSpectralSlope, CFeatureIf::kFeatureSpectralSpread, CFeatureIf::kFeatureSpectralTonalPowerRatio, CFeatureIf::kFeatureTimeAcfCoeff, CFeatureIf::kFeatureTimeMaxAcf, CFeatureIf::kFeatureTimePeakEnvelope, CFeatureIf::kFeatureTimeRms, CFeatureIf::kFeatureTimeStd, CFeatureIf::kFeatureTimeZeroCrossingRate, kFunctionInvalidArgsError, and kNoError.
Referenced by CChordFromBlockIf::CChordFromBlockIf(), and CFeatureIf::init_().
destroy()
Error_t CFeatureFromBlockIf::destroy (CFeatureFromBlockIf *& pCInstance) static
destroys a FeatureFromBlock instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 1012 of file FeatureFromBlock.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by CFeatureIf::reset_(), and CChordFromBlockIf::~CChordFromBlockIf().
getFeatureDimensions()
int CFeatureFromBlockIf::getFeatureDimensions () const virtual
returns size of output feature (1 in most cases)
Returns
int
Reimplemented in CFeatureSpectralMfccs, CFeatureSpectralPitchChroma, CFeatureTimePeakEnvelope, and CFeatureTimeRms.
Definition at line 1021 of file FeatureFromBlock.cpp.
{
    // default: 1 value per block
    return 1;
}
Referenced by CFeatureIf::compFeatureNDim(), and CFeatureIf::getFeatureDimensions().
getFeatureIdx()
CFeatureIf::Feature_t CFeatureFromBlockIf::getFeatureIdx () const inline
returns index of the feature to extract
Returns
CFeatureIf::Feature_t
Definition at line 41 of file FeatureFromBlock.h.
    {
        return m_eFeatureIdx;
    }
References m_eFeatureIdx.
Referenced by CFeatureIf::compFeature1Dim(), and CFeatureIf::compFeatureNDim().
hasAdditionalParam()
bool CFeatureFromBlockIf::hasAdditionalParam () const virtual
returns true if there is an additional parameter
Returns
bool
Reimplemented in CFeatureSpectralMfccs, CFeatureSpectralPitchChroma, CFeatureSpectralRolloff, CFeatureSpectralTonalPowerRatio, CFeatureTimeAcfCoeff, CFeatureTimeMaxAcf, and CFeatureTimeRms.
Definition at line 1035 of file FeatureFromBlock.cpp.
{
    // default: feature doesn't need any additional parameters
    return false;
}
operator=()
CFeatureFromBlockIf & CFeatureFromBlockIf::operator= (const CFeatureFromBlockIf & c) protected
setAdditionalParam()
Error_t CFeatureFromBlockIf::setAdditionalParam (float fParamValue) virtual
returns true if there is an additional parameter
Parameters
fParamValue new parameter value
Returns
bool
Reimplemented in CFeatureSpectralMfccs, CFeatureSpectralPitchChroma, CFeatureSpectralRolloff, CFeatureSpectralTonalPowerRatio, CFeatureTimeAcfCoeff, CFeatureTimeMaxAcf, and CFeatureTimeRms.
Definition at line 1041 of file FeatureFromBlock.cpp.
{
    // default: setting a parameter that doesn't exist
    return Error_t::kFunctionIllegalCallError;
}
References kFunctionIllegalCallError.
Member Data Documentation
m_DispatchMap
const std::map<CFeatureIf::Feature_t, std::function<float(const float*, int, float)> > CFeatureFromBlockIf::m_DispatchMap protected
Initial value:
{
            {CFeatureIf::kFeatureSpectralCentroid, &compFeatureSpectralCentroid},
            {CFeatureIf::kFeatureSpectralCrestFactor, &compFeatureSpectralCrestFactor},
            {CFeatureIf::kFeatureSpectralDecrease, &compFeatureSpectralDecrease},
            {CFeatureIf::kFeatureSpectralFlatness, &compFeatureSpectralFlatness},
            {CFeatureIf::kFeatureSpectralKurtosis, &compFeatureSpectralKurtosis},
            {CFeatureIf::kFeatureSpectralSkewness, &compFeatureSpectralSkewness},
            {CFeatureIf::kFeatureSpectralSlope, &compFeatureSpectralSlope},
            {CFeatureIf::kFeatureSpectralSpread, &compFeatureSpectralSpread},
            {CFeatureIf::kFeatureTimeStd, &compFeatureTimeStd},
            {CFeatureIf::kFeatureTimeZeroCrossingRate, &compFeatureTimeZeroCrossingRate}
    }
Definition at line 101 of file FeatureFromBlock.h.
Referenced by compFeature().
m_eFeatureIdx
CFeatureIf::Feature_t CFeatureFromBlockIf::m_eFeatureIdx = CFeatureIf::kNumFeatures protected
index of feature to extract
Definition at line 94 of file FeatureFromBlock.h.
Referenced by compFeature(), and getFeatureIdx().
m_fSampleRate
float CFeatureFromBlockIf::m_fSampleRate = 0 protected
sample rate
dispatcher map for static functions without additional arguments
Definition at line 98 of file FeatureFromBlock.h.
Referenced by compFeature(), CFeatureSpectralFlux::compFeature(), CFeatureSpectralRolloff::compFeature(), CFeatureSpectralTonalPowerRatio::compFeature(), CFeatureTimeAcfCoeff::compFeature(), CFeatureTimeMaxAcf::compFeature(), CFeatureTimePeakEnvelope::compFeature(), CFeatureTimeRms::compFeature(), CFeatureSpectralMfccs::genMfccFilters_(), CFeatureSpectralPitchChroma::genPcFilters_(), and CFeatureTimeMaxAcf::setAdditionalParam().
m_iDataLength
int CFeatureFromBlockIf::m_iDataLength = 0 protected
block length
Definition at line 96 of file FeatureFromBlock.h.
Referenced by CFeatureSpectralFlux::CFeatureSpectralFlux(), compFeature(), CFeatureSpectralFlux::compFeature(), CFeatureSpectralMfccs::compFeature(), CFeatureSpectralPitchChroma::compFeature(), CFeatureSpectralRolloff::compFeature(), CFeatureSpectralTonalPowerRatio::compFeature(), CFeatureTimeAcfCoeff::compFeature(), CFeatureTimeMaxAcf::compFeature(), CFeatureTimePeakEnvelope::compFeature(), CFeatureTimeRms::compFeature(), CFeatureSpectralMfccs::genMfccFilters_(), and CFeatureSpectralPitchChroma::genPcFilters_().
m_kfFloatThresh
const float CFeatureFromBlockIf::m_kfFloatThresh = 1e-30F static
below this we just assume it's zero
Definition at line 84 of file FeatureFromBlock.h.
Referenced by compFeatureSpectralCentroid(), compFeatureSpectralCrestFactor(), compFeatureSpectralDecrease(), compFeatureSpectralFlatness(), compFeatureSpectralKurtosis(), compFeatureSpectralRolloff(), compFeatureSpectralSkewness(), compFeatureSpectralSlope(), compFeatureSpectralSpread(), and compFeatureSpectralTonalPowerRatio().
The documentation for this class was generated from the following files:
FeatureFromBlock.h
FeatureFromBlock.cpp