ACA: CChordFromBlockIf Class Reference
CChordFromBlockIf Class Reference
class for computation of a chord from a magnitude spectrum
#include <ChordFromBlock.h>
Public Member Functions
virtual Error_t compChordProb (float *pfChordProb, const float *pfIn)
Static Public Member Functions
static Error_t create (CChordFromBlockIf *&pCInstance, int iMagSpecLength, float fSampleRate=1.F)
static Error_t destroy (CChordFromBlockIf *&pCInstance)
Protected Types
enum PitchClasses_t {
kC , kCs , kD , kDs ,
kE , kF , kFs , kG ,
kGs , kA , kAs , kB ,
kNumPitchClasses
}
Protected Member Functions
CChordFromBlockIf (int iMagSpecLength, float fSampleRate)
virtual ~CChordFromBlockIf ()
CChordFromBlockIf (const CChordFromBlockIf &that)
CChordFromBlockIf & operator= (const CChordFromBlockIf &c)
void genTemplateMatrix_ ()
chord templates for this similarity based chord detection
Protected Attributes
int m_iMagSpecLength = 0
block length
float m_fSampleRate = 0
sample rate
float * m_pfPitchChroma = 0
current pitch chroma
float ** m_ppfTemplateMatrix = 0
matrix holding all chord templates
CFeatureFromBlockIf * m_pCFeatureExtractor = 0
instance for pitch chroma extraction
Detailed Description
class for computation of a chord from a magnitude spectrum
Definition at line 12 of file ChordFromBlock.h.
Member Enumeration Documentation
PitchClasses_t
enum CChordFromBlockIf::PitchClasses_t protected
Enumerator
kC
kCs
kD
kDs
kE
kF
kFs
kG
kGs
kA
kAs
kB
kNumPitchClasses
Definition at line 38 of file ChordFromBlock.h.
    {
        kC,
        kCs,
        kD,
        kDs,
        kE,
        kF,
        kFs,
        kG,
        kGs,
        kA,
        kAs,
        kB,
        kNumPitchClasses
    };
Constructor & Destructor Documentation
CChordFromBlockIf() [1/2]
CChordFromBlockIf::CChordFromBlockIf (int iMagSpecLength, float fSampleRate) inline explicit protected
Definition at line 54 of file ChordFromBlock.cpp.
                                                                                 : m_iMagSpecLength(iMagSpecLength), m_fSampleRate(fSampleRate)
{
    CVector::alloc(m_pfPitchChroma, kNumPitchClasses);
    CMatrix::alloc(m_ppfTemplateMatrix, CChordIf::kNumChords, kNumPitchClasses);
    CFeatureFromBlockIf::create(m_pCFeatureExtractor, CFeatureIf::kFeatureSpectralPitchChroma, m_iMagSpecLength, m_fSampleRate);
    genTemplateMatrix_();
}
References CVector::alloc(), CMatrix::alloc(), CFeatureFromBlockIf::create(), genTemplateMatrix_(), CFeatureIf::kFeatureSpectralPitchChroma, CChordIf::kNumChords, kNumPitchClasses, m_fSampleRate, m_iMagSpecLength, m_pCFeatureExtractor, m_pfPitchChroma, and m_ppfTemplateMatrix.
Referenced by create().
~CChordFromBlockIf()
CChordFromBlockIf::~CChordFromBlockIf () inline protected virtual
Definition at line 64 of file ChordFromBlock.cpp.
{
    CVector::free(m_pfPitchChroma);
    CMatrix::free(m_ppfTemplateMatrix, CChordIf::kNumChords);
    CFeatureFromBlockIf::destroy(m_pCFeatureExtractor);
}
References CFeatureFromBlockIf::destroy(), CVector::free(), CMatrix::free(), CChordIf::kNumChords, m_pCFeatureExtractor, m_pfPitchChroma, and m_ppfTemplateMatrix.
CChordFromBlockIf() [2/2]
CChordFromBlockIf::CChordFromBlockIf (const CChordFromBlockIf & that) protected
Member Function Documentation
compChordProb()
Error_t CChordFromBlockIf::compChordProb (float * pfChordProb, const float * pfIn) virtual
calculates the chord probabilities
Parameters
pfChordProb resulting chord probabilities (user allocated, length kNumChords)
pfIn input data of length iMagSpecLength
Returns
Error_t
Definition at line 30 of file ChordFromBlock.cpp.
{
    // compute pitch chroma
    m_pCFeatureExtractor->compFeature(m_pfPitchChroma, pfIn);
    // check if zero
    if (CVector::getSum(m_pfPitchChroma, kNumPitchClasses) <= 1e-20F)
    {
        CVector::setZero(pfChordProb, CChordIf::kNumChords);
        pfChordProb[CChordIf::kNoChord] = 1.F;
        return Error_t::kNoError;
    }
    // get chord probs with template
    CMatrix::mulMatColvec(pfChordProb, m_ppfTemplateMatrix, m_pfPitchChroma, CChordIf::kNumChords, kNumPitchClasses);
    assert(CVector::getSum(pfChordProb, CChordIf::kNumChords) > 0);
    // normalize to probability of 1
    CVector::mulC_I(pfChordProb, 1.F / CVector::getSum(pfChordProb, CChordIf::kNumChords), CChordIf::kNumChords);
    return Error_t::kNoError;
}
References CFeatureFromBlockIf::compFeature(), CVector::getSum(), CChordIf::kNoChord, kNoError, CChordIf::kNumChords, kNumPitchClasses, m_pCFeatureExtractor, m_pfPitchChroma, m_ppfTemplateMatrix, CVector::mulC_I(), CMatrix::mulMatColvec(), and CVector::setZero().
Referenced by CChordIf::compChords().
create()
Error_t CChordFromBlockIf::create (CChordFromBlockIf *& pCInstance, int iMagSpecLength, float fSampleRate = 1.F) static
initializes a ChordFromBlock instance
Parameters
pCInstance pointer to instance to be written
iMagSpecLength block length
fSampleRate sample rate
Returns
Error_t
Definition at line 10 of file ChordFromBlock.cpp.
{
    if (iMagSpecLength <= 0 || fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CChordFromBlockIf(iMagSpecLength, fSampleRate);
    return Error_t::kNoError;
}
References CChordFromBlockIf(), kFunctionInvalidArgsError, and kNoError.
Referenced by CChordIf::init_().
destroy()
Error_t CChordFromBlockIf::destroy (CChordFromBlockIf *& pCInstance) static
destroys a ChordFromBlock instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 21 of file ChordFromBlock.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by CChordIf::reset_().
genTemplateMatrix_()
void CChordFromBlockIf::genTemplateMatrix_ () protected
chord templates for this similarity based chord detection
Definition at line 72 of file ChordFromBlock.cpp.
{
    assert(m_ppfTemplateMatrix);
    assert(m_ppfTemplateMatrix[0]);
    const int iNumChordPitches = 3;
    const int aiMajorIndices[3] = { 0,4,7 };
    const int aiMinorIndices[3] = { 0,3,7 };
    // simple template with equally weighted chord pitches, zero otherwise
    for (auto c = 0; c < kNumPitchClasses; c++)
    {
        for (auto p = 0; p < iNumChordPitches; p++)
        {
            m_ppfTemplateMatrix[c][(c + aiMajorIndices[p]) % 12] = 1.F / iNumChordPitches;
            m_ppfTemplateMatrix[c + kNumPitchClasses][(c + aiMinorIndices[p]) % 12] = 1.F / iNumChordPitches;
        }
    }
    CVector::addC_I(m_ppfTemplateMatrix[CChordIf::kNoChord], 1.F / kNumPitchClasses, kNumPitchClasses);
}
References CVector::addC_I(), CChordIf::kNoChord, kNumPitchClasses, and m_ppfTemplateMatrix.
Referenced by CChordFromBlockIf().
operator=()
CChordFromBlockIf & CChordFromBlockIf::operator= (const CChordFromBlockIf & c) protected
Member Data Documentation
m_fSampleRate
float CChordFromBlockIf::m_fSampleRate = 0 protected
sample rate
Definition at line 64 of file ChordFromBlock.h.
Referenced by CChordFromBlockIf().
m_iMagSpecLength
int CChordFromBlockIf::m_iMagSpecLength = 0 protected
block length
Definition at line 63 of file ChordFromBlock.h.
Referenced by CChordFromBlockIf().
m_pCFeatureExtractor
CFeatureFromBlockIf* CChordFromBlockIf::m_pCFeatureExtractor = 0 protected
instance for pitch chroma extraction
Definition at line 70 of file ChordFromBlock.h.
Referenced by CChordFromBlockIf(), compChordProb(), and ~CChordFromBlockIf().
m_pfPitchChroma
float* CChordFromBlockIf::m_pfPitchChroma = 0 protected
current pitch chroma
Definition at line 66 of file ChordFromBlock.h.
Referenced by CChordFromBlockIf(), compChordProb(), and ~CChordFromBlockIf().
m_ppfTemplateMatrix
float** CChordFromBlockIf::m_ppfTemplateMatrix = 0 protected
matrix holding all chord templates
Definition at line 68 of file ChordFromBlock.h.
Referenced by CChordFromBlockIf(), compChordProb(), genTemplateMatrix_(), and ~CChordFromBlockIf().
The documentation for this class was generated from the following files:
ChordFromBlock.h
ChordFromBlock.cpp