ACA: CButterLp Class Reference
CButterLp Class Reference
class providing a generic filter implementation implementation inspired by src from https://exstrom.com/journal/sigproc/dsigproc.html
#include <Filter.h>
Static Public Member Functions
template<typename T >
static Error_t calcCoeffs (T *pfB, T *pfA, int iOrder, T fCutOff)
Static Private Member Functions
template<typename T >
static Error_t calcB (T *pfB, int iOrder, T fCutOff)
template<typename T >
static Error_t calcA (T *pfA, int iOrder, T fCutOff)
template<typename T >
static T calcScale (int iOrder, T fCutOff)
template<typename T >
static Error_t multBinomial (T *pfOut, const T *pfIn, int iOrder)
Detailed Description
class providing a generic filter implementation implementation inspired by src from https://exstrom.com/journal/sigproc/dsigproc.html
Definition at line 288 of file Filter.h.
Member Function Documentation
calcA()
template<typename T > static Error_t CButterLp::calcA (T * pfA, int iOrder, T fCutOff) inline static private
Definition at line 340 of file Filter.h.
    {
        T* pfCoeff = 0;     // binomial coefficients
        CVector::alloc<T>(pfCoeff, static_cast<long long>(2) * iOrder);
        for (auto j = 0; j < iOrder; j++)
        {
            T fArg = static_cast<T>(M_PI * (2. * j + 1) / (2. * iOrder));
            T fNorm = static_cast<T>(1 + std::sin(M_PI * fCutOff) * std::sin(fArg));
            pfCoeff[2 * j] = static_cast<T>(-std::cos(M_PI * fCutOff) / fNorm);
            pfCoeff[2 * j + 1] = static_cast<T>(-std::sin(M_PI * fCutOff) * std::cos(fArg) / fNorm);
        }
        multBinomial(pfA, pfCoeff, iOrder);
        pfA[1] = pfA[0];
        pfA[0] = 1;
            for (auto j = 3; j <= iOrder; j++)
            pfA[j] = pfA[2 * j - 2];
        CVector::free<T>(pfCoeff);
        return Error_t::kNoError;
    }
References kNoError, M_PI, and multBinomial().
Referenced by calcCoeffs().
calcB()
template<typename T > static Error_t CButterLp::calcB (T * pfB, int iOrder, T fCutOff) inline static private
Definition at line 319 of file Filter.h.
    {
        pfB[0] = 1;
        pfB[1] = static_cast<T>(iOrder);
        for (auto j = 2; j <= iOrder / 2; ++j)
        {
            pfB[j] = (iOrder - j + 1) * pfB[j - 1] / j;
            pfB[iOrder - j] = pfB[j];
        }
        pfB[iOrder - 1] = static_cast<T>(iOrder);
        pfB[iOrder] = 1;
        T fScale = calcScale(iOrder, fCutOff);
        for (auto j = 0; j < iOrder + 1; j++)
            pfB[j] *= fScale;
        return Error_t::kNoError;
    }
References calcScale(), and kNoError.
Referenced by calcCoeffs().
calcCoeffs()
template<typename T > static Error_t CButterLp::calcCoeffs (T * pfB, T * pfA, int iOrder, T fCutOff) inline static
computes buttworth lowpass coefficients
Parameters
pfB output signal (to be written, length iOrder+1, allocated by user)
pfA input signal (to be written, length iOrder+1, allocated by user)
iOrder number of poles
fCutOff normed cutoff between 0 and 1 (fs/2)
Returns
Error_t
Definition at line 300 of file Filter.h.
    {
        const long long iTmpOrder = static_cast<long long>(iOrder); // silly compiler warnings get annoying
        float* pfTmpA = 0;
        CVector::alloc(pfTmpA, 2 * iTmpOrder);
        CVector::setZero(pfB, iTmpOrder + 1);
        CVector::setZero(pfTmpA, 2 * iTmpOrder);
        calcB(pfB, iOrder, fCutOff);
        calcA(pfTmpA, iOrder, fCutOff);
        CVector::copy(pfA, pfTmpA, iTmpOrder + 1);
        CVector::free(pfTmpA);
        return Error_t::kNoError;
    }
References CVector::alloc(), calcA(), calcB(), CVector::copy(), CVector::free(), kNoError, and CVector::setZero().
Referenced by CPitchTimeAuditory::CPitchTimeAuditory(), and CResample::process().
calcScale()
template<typename T > static T CButterLp::calcScale (int iOrder, T fCutOff) inline static private
Definition at line 367 of file Filter.h.
    {
        T fPhase = static_cast<T>(M_PI / (2. * iOrder));
        T fScale = 1;
        for (auto j = 0; j < iOrder / 2; ++j)
            fScale *= static_cast<T>(1 + std::sin(M_PI * fCutOff) * std::sin((2 * j + 1) * fPhase));
        if (iOrder % 2)
            fScale *= static_cast<T>(std::sin(M_PI * fCutOff / 2) + std::cos(M_PI * fCutOff / 2));
        fScale = static_cast<T>(std::pow(std::sin(M_PI * fCutOff / 2), iOrder) / fScale);
        return fScale;
    }
References M_PI.
Referenced by calcB().
multBinomial()
template<typename T > static Error_t CButterLp::multBinomial (T * pfOut, const T * pfIn, int iOrder) inline static private
Definition at line 383 of file Filter.h.
    {
        for (auto i = 0; i < iOrder; i++)
        {
            for (auto j = i; j > 0; j--)
            {
                pfOut[2 * j] += pfIn[2 * i] * pfOut[2 * (j - 1)] - pfIn[2 * i + 1] * pfOut[2 * (j - 1) + 1];
                pfOut[2 * j + 1] += pfIn[2 * i] * pfOut[2 * (j - 1) + 1] + pfIn[2 * i + 1] * pfOut[2 * (j - 1)];
            }
            pfOut[0] += pfIn[2 * i];
            pfOut[1] += pfIn[2 * i + 1];
        }
        return Error_t::kNoError;
    }
References kNoError.
Referenced by calcA().
The documentation for this class was generated from the following file:
Filter.h