ACA: CClassifierBase Class Reference
CClassifierBase Class Reference abstract
abstract base class for traditional classifiers
#include <ClassifierBase.h>
Public Types
enum Normalization_t { kNoNormalization , kZscoreNormalization , kMinmaxNormalization , kNumNormModes }
Public Member Functions
virtual Error_t init (int iNumFeatures, int iNumObs)=0
virtual Error_t train (const float *const *const ppfTrainFeatures, const int *piTrainClassIndices, Normalization_t eNorm=kNoNormalization)=0
virtual Error_t reset ()=0
virtual int classify (const float *pfQuery)=0
Static Public Attributes
static const int kIllegalClassLabel = -1111111111
indicates something went wrong (this number should not be used as a class label)
Protected Member Functions
virtual ~CClassifierBase ()
virtual void compNormConstants (const float *const *const ppfTrainFeatures, int iNumFeatures, int iNumObs, Normalization_t eNorm)
virtual void normalizeVector (float *pfQuery, int iNumFeatures)
Protected Attributes
float * m_pfNormScale = 0
scaling constant for normalization (length m_iNumFeatures)
float * m_pfNormSub = 0
offset for normalization (length m_iNumFeatures)
Detailed Description
abstract base class for traditional classifiers
Definition at line 10 of file ClassifierBase.h.
Member Enumeration Documentation
Normalization_t
enum CClassifierBase::Normalization_t
Enumerator
kNoNormalization
kZscoreNormalization
kMinmaxNormalization
kNumNormModes
Definition at line 13 of file ClassifierBase.h.
    {
        kNoNormalization,
        kZscoreNormalization,
        kMinmaxNormalization,
        kNumNormModes
    };
Constructor & Destructor Documentation
~CClassifierBase()
virtual CClassifierBase::~CClassifierBase () inline protected virtual
Definition at line 50 of file ClassifierBase.h.
    {
        CVector::free(m_pfNormScale);
        CVector::free(m_pfNormSub);
    }
References CVector::free(), m_pfNormScale, and m_pfNormSub.
Member Function Documentation
classify()
virtual int CClassifierBase::classify (const float * pfQuery) pure virtual
classifies a new query vector
Parameters
pfQuery vector of length iNumFeatures to classify
Returns
int class label of most likely class (returns CClassifierBase::kIllegalClassLabel in case of error)
Implemented in CGmmClassifier, and CKnn.
Referenced by CLeaveOneOutCrossVal::process().
compNormConstants()
virtual void CClassifierBase::compNormConstants (const float *const *const ppfTrainFeatures, int iNumFeatures, int iNumObs, Normalization_t eNorm) inline protected virtual
estimates the constants for data normalization
Parameters
ppfTrainFeatures training feature matrix (iNumFeatures X iNumObs)
iNumFeatures number of features (rows in the input matrix)
iNumObs number of observations (columns in the feature matrix)
eNorm method for normalization
Definition at line 62 of file ClassifierBase.h.
    {
        assert(m_pfNormScale);
        assert(m_pfNormSub);
        // normalization constants
        if (eNorm == kZscoreNormalization)
        {
            for (auto f = 0; f < iNumFeatures; f++)
            {
                m_pfNormSub[f] = CVector::getMean(ppfTrainFeatures[f], iNumObs);
                m_pfNormScale[f] = CVector::getStd(ppfTrainFeatures[f], iNumObs, m_pfNormSub[f]);
                if (m_pfNormScale[f] > 0)
                    m_pfNormScale[f] = 1.F / m_pfNormScale[f];
            }
        }
        else if (eNorm == kMinmaxNormalization)
        {
            for (auto f = 0; f < iNumFeatures; f++)
            {
                m_pfNormSub[f] = CVector::getMin(ppfTrainFeatures[f], iNumObs);
                m_pfNormScale[f] = CVector::getMax(ppfTrainFeatures[f], iNumObs) - m_pfNormSub[f];
                if (m_pfNormScale[f] != 0)
                    m_pfNormScale[f] = 1.F / m_pfNormScale[f];
            }
        }
        else
        {
            CVector::setValue(m_pfNormScale, 1.F, iNumFeatures);
            CVector::setZero(m_pfNormSub, iNumFeatures);
        }
    }
References CVector::getMax(), CVector::getMean(), CVector::getMin(), CVector::getStd(), kMinmaxNormalization, kZscoreNormalization, m_pfNormScale, m_pfNormSub, CVector::setValue(), and CVector::setZero().
Referenced by CGmmClassifier::train(), and CKnn::train().
init()
virtual Error_t CClassifierBase::init (int iNumFeatures, int iNumObs) pure virtual
initializes instance
Parameters
iNumFeatures number of features (rows in the input matrix)
iNumObs number of observations (columns in the feature matrix)
Returns
Error_t
Implemented in CKnn, and CGmmClassifier.
Referenced by CLeaveOneOutCrossVal::process().
normalizeVector()
virtual void CClassifierBase::normalizeVector (float * pfQuery, int iNumFeatures) inline protected virtual
normalizes a new query vector according to previously extracted constants
Parameters
pfQuery vector of length iNumFeatures to classify
iNumFeatures number of features (rows in the input matrix)
Definition at line 99 of file ClassifierBase.h.
    {
        CVector::sub_I(pfQuery, m_pfNormSub, iNumFeatures);
        CVector::mul_I(pfQuery, m_pfNormScale, iNumFeatures);
    }
References m_pfNormScale, m_pfNormSub, CVector::mul_I(), and CVector::sub_I().
Referenced by CGmmClassifier::classify(), CKnn::classify(), CGmmClassifier::train(), and CKnn::train().
reset()
virtual Error_t CClassifierBase::reset () pure virtual
resets classifier instance
Returns
Error_t
Implemented in CGmmClassifier, and CKnn.
Referenced by CLeaveOneOutCrossVal::init().
train()
virtual Error_t CClassifierBase::train (const float *const *const ppfTrainFeatures, const int * piTrainClassIndices, Normalization_t eNorm = kNoNormalization) pure virtual
trains a classifier instance
Parameters
ppfTrainFeatures feature data for 'training' (dimensions iNumFeatures X iNumObs)
piTrainClassIndices ground truth class index for each observation
eNorm specification of what normalization should be applied to the feature data
Returns
Error_t
Implemented in CGmmClassifier, and CKnn.
Referenced by CLeaveOneOutCrossVal::process().
Member Data Documentation
kIllegalClassLabel
const int CClassifierBase::kIllegalClassLabel = -1111111111 static
indicates something went wrong (this number should not be used as a class label)
Definition at line 21 of file ClassifierBase.h.
Referenced by CKnn::buildHistogram_(), CGmmClassifier::classify(), and CKnn::classify().
m_pfNormScale
float* CClassifierBase::m_pfNormScale = 0 protected
scaling constant for normalization (length m_iNumFeatures)
Definition at line 105 of file ClassifierBase.h.
Referenced by compNormConstants(), CKnn::init(), CGmmClassifier::init(), normalizeVector(), CGmmClassifier::reset(), CKnn::reset(), and ~CClassifierBase().
m_pfNormSub
float* CClassifierBase::m_pfNormSub = 0 protected
offset for normalization (length m_iNumFeatures)
Definition at line 106 of file ClassifierBase.h.
Referenced by compNormConstants(), CKnn::init(), CGmmClassifier::init(), normalizeVector(), CGmmClassifier::reset(), CKnn::reset(), and ~CClassifierBase().
The documentation for this class was generated from the following files:
ClassifierBase.h
ToolSimpleKnn.cpp