ACA: CSpectrogramFromFile Class Reference
CSpectrogramFromFile Class Reference
class for computation of the spectrogram from a file
Public Member Functions
CSpectrogramFromFile (std::string strAudioFilePath, int iBlockLength, int iHopLength, bool bNormalize, float *pfWindow)
virtual ~CSpectrogramFromFile ()
Public Member Functions inherited from CSpectrogramIf
Error_t getSpectrogramDimensions (int &iNumRows, int &iNumCols) const
Error_t getSpectrogramAxisVectors (float *pfAxisTicks, enum AxisLabel_t eAxisLabel) const
Error_t compSpectrogram (float **ppfSpectrogram)
Error_t getMelSpectrogramDimensions (int &iNumRows, int &iNumCols, const MelSpectrogramConfig_t *pMelSpecConfig) const
Error_t getMelSpectrogramAxisVectors (float *pfAxisTicks, enum AxisLabel_t eAxisLabel, const MelSpectrogramConfig_t *pMelSpecConfig)
Error_t compMelSpectrogram (float **ppfMelSpectrogram, const MelSpectrogramConfig_t *pMelSpecConfig)
Private Attributes
CAudioFileIf * m_pCAudioFile
Additional Inherited Members
Public Types inherited from CSpectrogramIf
enum AxisLabel_t { kFrequencyInHz , kTimeInS , kNumAxisLabels }
Static Public Member Functions inherited from CSpectrogramIf
static Error_t create (CSpectrogramIf *&pCInstance, const std::string &strAudioFilePath, int iBlockLength=2048, int iHopLength=1024, bool bNormalize=true, float *pfWindow=0)
static Error_t create (CSpectrogramIf *&pCInstance, const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=2048, int iHopLength=1024, bool bNormalize=true, float *pfWindow=0)
static Error_t destroy (CSpectrogramIf *&pCInstance)
Protected Member Functions inherited from CSpectrogramIf
CSpectrogramIf ()
virtual ~CSpectrogramIf ()
CSpectrogramIf (const CSpectrogramIf &that)
CSpectrogramIf & operator= (const CSpectrogramIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (float *pfWindow)
init configuration
void computeMagSpectrum_ (int iLength)
Error_t generateMelFb_ (const MelSpectrogramConfig_t *pMelSpecConfig)
void destroyMelFb_ (const MelSpectrogramConfig_t *pMelSpecConfig)
Protected Attributes inherited from CSpectrogramIf
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CFft * m_pCFft = 0
fft instance
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfSpectrum = 0
temporary buffer for current spectrum
float * m_pfProcBuff = 0
temporary buffer
float ** m_ppfHMel = 0
Mel filterbank.
float * m_pffcMel = 0
Mel center frequencies.
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of the spectrogram from a file
Definition at line 17 of file Spectrogram.cpp.
Constructor & Destructor Documentation
CSpectrogramFromFile()
CSpectrogramFromFile::CSpectrogramFromFile (std::string strAudioFilePath, int iBlockLength, int iHopLength, bool bNormalize, float * pfWindow)
Definition at line 37 of file Spectrogram.cpp.
                                                                                                                                         :
    m_pCAudioFile(0)
{
    this->reset_();
    CAudioFileIf::FileSpec_t stFileSpec;
    CAudioFileIf::create(m_pCAudioFile);
    m_pCAudioFile->openFile(strAudioFilePath, CAudioFileIf::kFileRead);
    m_pCAudioFile->getFileSpec(stFileSpec);
    m_fSampleRate = stFileSpec.fSampleRateInHz;
    CBlockAudioIf::create(m_pCBlockAudio, m_pCAudioFile, iBlockLength, iHopLength);
    if (bNormalize)
        m_pCNormalize = new CNormalizeAudio(m_pCAudioFile);
    // set length variables
    m_iBlockLength = iBlockLength;
    m_iHopLength = iHopLength;
    init_(pfWindow);
}
References CAudioFileIf::create(), CBlockAudioIf::create(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CSpectrogramIf::init_(), CAudioFileIf::kFileRead, CSpectrogramIf::m_fSampleRate, CSpectrogramIf::m_iBlockLength, CSpectrogramIf::m_iHopLength, m_pCAudioFile, CSpectrogramIf::m_pCBlockAudio, CSpectrogramIf::m_pCNormalize, and CSpectrogramIf::reset_().
~CSpectrogramFromFile()
virtual CSpectrogramFromFile::~CSpectrogramFromFile () inline virtual
Definition at line 22 of file Spectrogram.cpp.
    {
        delete m_pCNormalize;
        m_pCNormalize = 0;
        CVector::free(m_pfProcBuff);
        m_pCAudioFile->closeFile();
        CAudioFileIf::destroy(m_pCAudioFile);
    };
References CAudioFileIf::destroy(), CVector::free(), m_pCAudioFile, CSpectrogramIf::m_pCNormalize, and CSpectrogramIf::m_pfProcBuff.
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CSpectrogramFromFile::m_pCAudioFile private
Definition at line 34 of file Spectrogram.cpp.
Referenced by CSpectrogramFromFile(), and ~CSpectrogramFromFile().
The documentation for this class was generated from the following file:
Spectrogram.cpp