ACA: CMatrix Class Reference
CMatrix Class Reference
class with static functions for matrix operations with type float (functionality only added when needed)
#include <Matrix.h>
Static Public Member Functions
template<typename T >
static void alloc (T **&pptMat, int iNumRows, int iNumCols)
template<typename T >
static void free (T **&pptMat, int iNumRows)
template<typename T >
static void setZero (T **pptMat, int iNumRows, int iNumCols)
template<typename T >
static void setValue (T **pptMat, T tValue, int iNumRows, int iNumCols)
template<typename T >
static void setRand (T **pptMat, int iNumRows, int iNumCols)
template<typename T >
static void setCol (T **pptDestMat, T *ptSrcVec, int iColIdx, int iNumRows)
template<typename T >
static void setZeroBelowThresh (T **pptMat, int iNumRows, int iNumCols, T tThresh)
static void setEye (float **pptDest, int iNumRows, int iNumCols)
static void getCol (float *ptDest, float **pptMat, int iColIdx, int iNumRows)
static float getSumCol (float **pptMat, int iColIdx, int iNumRows, bool bAbs=false)
static float getSum (float **pptMat, int iNumRows, int iNumCols, bool bAbs=false)
static float getNorm (float **pptMat, int iNumRows, int iNumCols)
static void vecnorm_I (float **pptSrcDest, int iNumRows, int iNumCols)
static float calcKlDivergence (float **pptSrc1, float **pptSrc2, int iNumRows, int iNumCols)
static void transpose (float **pptDest, float **pptSrc, int iNumSrcRows, int iNumSrcCols)
static void rearrangeRows (float **pptSrcDest, int *piRowIndices, int iNumRows)
static void diag (float *ptDest, float **pptSrc, int iNumSrcRows, int iNumSrcCols)
static void mulMatColVec (float *ptDestColVec, float **pptMat, const float *ptSrcColVec, int iNumMatRows, int iNumMatCols)
static void mulColVecRowVec (float **pptDestMat, const float *ptSrcColVec, const float *ptSrcRowVec, int iNumMatRows, int iNumMatCols)
static void mulRowVecMat (float *ptDestRowVec, const float *ptSrcRowVec, float **pptMat, int iNumMatRows, int iNumMatCols)
static void mulColC_I (float **pptMat, float fValue, int iCol, int iNumRows)
static void mulMatMat (float **pptDest, float **pptSrc1, float **pptSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols)
static void mul_I (float **pptSrcDest, float **pptSrc, int iNumRows, int iNumCols)
static void add_I (float **pptSrcDest, float **pptSrc, int iNumRows, int iNumCols)
static void sub_I (float **pptSrcDest, float **pptSrc, int iNumRows, int iNumCols)
static void div_I (float **pptSrcDest, float **pptSrc, int iNumRows, int iNumCols, bool bAddSmallConst=false)
static float getMax (float **pptMat, int iNumRows, int iNumCols)
static void addC_I (float **pptMat, float fAdd, int iNumRows, int iNumCols)
static void mulC_I (float **pptMat, float fScale, int iNumRows, int iNumCols)
static void swapRowCol (float **pptSrcDest, int iRowIdx, int iColIdx, int iNumCols)
template<typename T >
static void copy (T **pptDestMat, T **pptSrcMat, int iNumRows, int iNumCols)
template<typename T >
static void setRow (T **pptDestMat, T *ptSrcVec, int iRowIdx, int iNumCols)
template<typename T >
static T det (T **pptMat, int iNumRows, int iNumCols)
template<typename T >
static void inv_I (T **pptSrcDest, int iNumRows, int iNumCols)
Detailed Description
class with static functions for matrix operations with type float (functionality only added when needed)
Definition at line 11 of file Matrix.h.
Member Function Documentation
add_I()
static void CMatrix::add_I (float ** pptSrcDest, float ** pptSrc, int iNumRows, int iNumCols) inline static
elementwise addition of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 538 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] += pptSrc[m][n];
        }
    }
Referenced by CGmm::updateState_().
addC_I()
static void CMatrix::addC_I (float ** pptMat, float fAdd, int iNumRows, int iNumCols) inline static
adds a single value to all matrix elements
Parameters
pptMat matrix to analyze
fAdd scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 633 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::addC_I(pptMat[m], fAdd, iNumCols);
    }
References CVector::addC_I().
Referenced by CChordIf::initViterbi_(), and CNmf::runNmfIter().
alloc()
template<typename T > static void CMatrix::alloc (T **& pptMat, int iNumRows, int iNumCols) inline static
allocates a float matrix and inits it with zeros
Parameters
pptMat (empty double pointer, to be allocated)
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 22 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        CVector::alloc(pptMat, iNumRows);
        assert(pptMat);
        for (auto m = 0; m < iNumRows; m++)
            CVector::alloc(pptMat[m], iNumCols);
    }
References CVector::alloc().
Referenced by CFeatureSpectralMfccs::allocDctMat_(), CBlockAudioFile::CBlockAudioFile(), CChordFromBlockIf::CChordFromBlockIf(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma(), CGmmResult::CGmmResult(), CNormalizeAudio::CNormalizeAudio(), CKey::compKey(), CPitchTimeAuditory::CPitchTimeAuditory(), CSubFingerprint::CSubFingerprint(), det(), CSpectrogramIf::generateMelFb_(), CGmm::init(), CNmf::init(), CFingerprint::init(), CViterbi::init(), CKnn::init(), CGmmResult::init(), CKmeans::init(), CPca::init(), CDtw::init(), CNmfResult::init(), CChordIf::init_(), CChordIf::initViterbi_(), inv_I(), and CFilter< T >::setInitState_().
calcKlDivergence()
static float CMatrix::calcKlDivergence (float ** pptSrc1, float ** pptSrc2, int iNumRows, int iNumCols) inline static
comnputes kl divergence between two matrices
Parameters
pptSrc1 matrix of dimension iNumRows x iNumCols
pptSrc2 matrix of dimension iNumRows x iNumCols
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 293 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptSrc1);
        assert(pptSrc1[0]);
        assert(pptSrc2);
        assert(pptSrc2[0]);
        float fResult = 0;
        for (int i = 0; i < iNumRows; i++)
        {
            for (int j = 0; j < iNumCols; j++)
                fResult += pptSrc1[i][j] * (std::log((pptSrc1[i][j] + 1e-24F) / (pptSrc2[i][j] + 1e-24F)) - 1.F) + pptSrc2[i][j];
        }
        return fResult;
    }
Referenced by CNmf::runNmfIter().
copy()
template<typename T > static void CMatrix::copy (T ** pptDestMat, T ** pptSrcMat, int iNumRows, int iNumCols) inline static
copies matrix content to another matrix
Parameters
pptDestMat (destination matrix, user allocated)
pptSrcMat (source matrix)
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 694 of file Matrix.h.
    {
        assert(pptDestMat);
        assert(pptSrcMat);
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::copy(pptDestMat[m], pptSrcMat[m], iNumCols);
    }
References CVector::copy().
Referenced by CPca::calcSVD(), CGmmResult::CGmmResult(), CKmeans::compKmeans(), det(), CNmfResult::getMat(), CGmmResult::getSigma(), CViterbi::init(), inv_I(), CGmmResult::operator=(), CNmf::runNmfIter(), and CGmmResult::setSigma().
det()
template<typename T > static T CMatrix::det (T ** pptMat, int iNumRows, int iNumCols) inline static
Definition at line 724 of file Matrix.h.
    {
        assert(pptMat);
        assert(iNumRows == iNumCols);
        const float kSingularityThresh = 1e-15F;
        T **pptTmp = 0;
        double dDet = 1;
        if (iNumRows == 2)
            return ((pptMat[0][0] * pptMat[1][1]) - (pptMat[0][1] * pptMat[1][0]));
        CMatrix::alloc(pptTmp, iNumRows, iNumCols);
        CMatrix::copy(pptTmp, pptMat, iNumRows, iNumCols);
        if (pptTmp[0][0] == 0)
        {
            auto i = 1;
            while (i < iNumRows)
            {
                if (pptTmp[i][0] != 0)
                {
                    swapRowCol(pptTmp, 0, i, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        if (pptTmp[0][0] == 0)
        {
            CMatrix::free(pptTmp, iNumRows);
            return 0;
        }
        dDet *= pptTmp[0][0];
        CVector::mulC_I(pptTmp[0], 1.F / pptTmp[0][0], iNumCols);
        for (auto i = 1; i < iNumRows; i++)
        {
            auto j = 0;
            if (std::abs(dDet) < kSingularityThresh * 1. * kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVector::addW_I(pptTmp[i], pptTmp[j], -pptTmp[i][j], iNumCols);
                j++;
            }
            if (pptTmp[i][i] != 0)
            {
                dDet *= pptTmp[i][i];
                CVector::mulC_I(pptTmp[i], 1.F / pptTmp[i][i], iNumCols);
            }
            if (pptTmp[i][i] == 0)
            {
                for (j = i + 1; j < iNumCols; j++)
                {
                    if (pptTmp[i][j] != 0)
                    {
                        CVector::add_I(pptTmp[i], pptTmp[j], iNumCols);
                        dDet *= pptTmp[i][i];
                        CVector::mulC_I(pptTmp[i], 1.F / pptTmp[i][i], iNumCols);
                        break;
                    }
                }
            }
            if (pptTmp[i][i] == 0)
            {
                CMatrix::free(pptTmp, iNumRows);
                return 0;
            }
        }
        CMatrix::free(pptTmp, iNumRows);
        return static_cast<T>(dDet);
    }
References CVector::add_I(), CVector::addW_I(), alloc(), copy(), free(), CVector::mulC_I(), and swapRowCol().
Referenced by CGmm::compProbabilities_().
diag()
static void CMatrix::diag (float * ptDest, float ** pptSrc, int iNumSrcRows, int iNumSrcCols) inline static
returns matrix diagonal as vector
Parameters
ptDest resulting vector of dimension min(iNumSrcRows, iNumCols) (to be written, user allocated)
pptSrc input matrix of dimension iNumSrcRows x iNumCols
iNumSrcRows number of rows in the matrix
iNumSrcCols number of columns in the matrix
Returns
Definition at line 371 of file Matrix.h.
    {
        assert(iNumSrcRows > 0);
        assert(iNumSrcCols > 0);
        assert(pptSrc);
        assert(pptSrc[0]);
        assert(ptDest);
        int iLen = std::min(iNumSrcRows, iNumSrcCols);
        for (auto m = 0; m < iLen; m++)
            ptDest[m] = pptSrc[m][m];
    }
Referenced by CPca::compPca().
div_I()
static void CMatrix::div_I (float ** pptSrcDest, float ** pptSrc, int iNumRows, int iNumCols, bool bAddSmallConst = false) inline static
elementwise division of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
bAddSmallConst a small floating point number is added before division if true
Returns
Definition at line 585 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        float fEpsilon = bAddSmallConst? 1e-30F : .0F;
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] /= (pptSrc[m][n] + fEpsilon);
        }
    }
Referenced by CNmf::runNmfIter().
free()
template<typename T > static void CMatrix::free (T **& pptMat, int iNumRows) inline static
frees a float matrix
Parameters
pptMat (empty double pointer, to be set to zero)
iNumRows number of rows
Returns
Definition at line 40 of file Matrix.h.
    {
        if (!pptMat) return;
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::free(pptMat[m]);
        CVector::free(pptMat);
        pptMat = 0;
    }
References CVector::free().
Referenced by CNormalizeAudio::CNormalizeAudio(), CKey::compKey(), CFeatureSpectralMfccs::deleteDctMat_(), CSpectrogramIf::destroyMelFb_(), det(), CFingerprint::init(), CChordIf::initViterbi_(), inv_I(), CGmmResult::reset(), CGmm::reset(), CNmfResult::reset(), CNmf::reset(), CPca::reset(), CDtw::reset(), CKmeans::reset(), CViterbi::reset(), CKnn::reset(), CChordIf::reset_(), CFilter< T >::setInitState_(), CBlockAudioFile::~CBlockAudioFile(), CChordFromBlockIf::~CChordFromBlockIf(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::~CFeatureSpectralPitchChroma(), CPitchTimeAuditory::~CPitchTimeAuditory(), and CSubFingerprint::~CSubFingerprint().
getCol()
static void CMatrix::getCol (float * ptDest, float ** pptMat, int iColIdx, int iNumRows) inline static
returns a column as vector
Parameters
ptDest resulting vector of dimension iNumRows (to be written, user allocated)
pptMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iColIdx index of column to retrieve
iNumRows number of rows in the matrix
Definition at line 171 of file Matrix.h.
    {
        assert(iColIdx >= 0);
        assert(iNumRows > 0);
        assert(pptMat);
        assert(ptDest);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            ptDest[m] = pptMat[m][iColIdx];
    }
Referenced by CKmeans::assignClusterLabels_().
getMax()
static float CMatrix::getMax (float ** pptMat, int iNumRows, int iNumCols) inline static
return maximum value in a matrix
Parameters
pptMat matrix to analyze
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 609 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        float fGlobalMax = CVector::getMax(pptMat[0], iNumCols);
        for (auto m = 1; m < iNumRows; m++)
        {
            float fMax = CVector::getMax(pptMat[m], iNumCols);
            if (fMax > fGlobalMax)
                fGlobalMax = fMax;
        }
        return fGlobalMax;
    }
References CVector::getMax().
Referenced by CChordIf::initViterbi_().
getNorm()
static float CMatrix::getNorm (float ** pptMat, int iNumRows, int iNumCols) inline static
return the matrix norm (p=1)
Parameters
pptMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 240 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        float fResult = 0;
        for (auto n = 0; n < iNumCols; n++)
        {
            float fTmp = 0;
            for (auto m = 0; m < iNumRows; m++)
                fTmp += std::abs(pptMat[m][n]);
            if (fTmp > fResult)
                fResult = fTmp;
        }
        return fResult;
    }
Referenced by CNmf::runNmfIter().
getSum()
static float CMatrix::getSum (float ** pptMat, int iNumRows, int iNumCols, bool bAbs = false) inline static
adds all matrix elements
Parameters
pptMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
bAbs flag to indicate whether to sum the absolute values
Returns
Definition at line 219 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        float fResult = 0;
        for (auto m = 0; m < iNumRows; m++)
            fResult += CVector::getSum(pptMat[m], iNumCols, bAbs);
        return fResult;
    }
References CVector::getSum().
getSumCol()
static float CMatrix::getSumCol (float ** pptMat, int iColIdx, int iNumRows, bool bAbs = false) inline static
adds all elements in one columns
Parameters
pptMat input matrix of dimension iNumRows x iNumCols
iColIdx column of interest
iNumRows number of rows in the matrix
bAbs flag to indicate whether to sum the absolute values
Returns
Definition at line 190 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(pptMat);
        assert(pptMat[0]);
        float fResult = 0;
        if (bAbs)
        {
            for (auto m = 0; m < iNumRows; m++)
                fResult += std::abs(pptMat[m][iColIdx]);
        }
        else
        {
            for (auto m = 0; m < iNumRows; m++)
                fResult += pptMat[m][iColIdx];
        }
        return fResult;
    }
Referenced by CGmm::compProbabilities_().
inv_I()
template<typename T > static void CMatrix::inv_I (T ** pptSrcDest, int iNumRows, int iNumCols) inline static
computes inverse of square matrix
Parameters
pptSrcDest input and output matrix (to be modified, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 817 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        const float kSingularityThresh = 1e-15F;
        T** ppfTmp = 0;
        T** ppfEye = 0;
        int    i, j;
        double dDet = 1;
        alloc(ppfTmp, iNumRows, iNumCols);
        copy(ppfTmp, pptSrcDest, iNumRows, iNumCols);
        alloc(ppfEye, iNumRows, iNumCols);
        setEye(ppfEye, iNumRows, iNumCols);
        if (pptSrcDest[0][0] == 0)
        {
            i = 1;
            while (i < iNumRows)
            {
                if (pptSrcDest[i][0] != 0)
                {
                    swapRowCol(pptSrcDest, 0, i, iNumCols);
                    swapRowCol(ppfEye, 0, i, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        dDet *= pptSrcDest[0][0];
        CVector::mulC_I(ppfEye[0], 1.F / pptSrcDest[0][0], iNumCols);
        CVector::mulC_I(pptSrcDest[0], 1.F / pptSrcDest[0][0], iNumCols);
        for (i = 1; i < iNumRows; i++)
        {
            j = 0;
            if (std::abs(dDet) < kSingularityThresh * 1.* kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVector::subW_I(ppfEye[i], ppfEye[j], pptSrcDest[i][j], iNumCols);
                CVector::subW_I(pptSrcDest[i], pptSrcDest[j], pptSrcDest[i][j], iNumCols);
                j++;
            }
            if (pptSrcDest[i][i] != 0)
            {
                dDet *= pptSrcDest[i][i];
                CVector::mulC_I(ppfEye[i], 1.F / pptSrcDest[i][i], iNumCols);
                CVector::mulC_I(pptSrcDest[i], 1.F / pptSrcDest[i][i], iNumCols);
            }
            if (pptSrcDest[i][i] == 0)
            {
                for (int j1 = i + 1; j1 < iNumCols; j1++)
                {
                    if (pptSrcDest[i][j1] != 0)         // Column pivotting not supported
                    {
                        for (int i1 = 0; i1 < iNumRows; i1++)
{
                            for (j = 0; j < iNumCols; j++)
                                pptSrcDest[i1][j] = ppfTmp[i1][j];
                        }
                        inv_I(ppfTmp, iNumRows, iNumCols);
                        copy(pptSrcDest, ppfTmp, iNumRows, iNumCols);
                        CMatrix::free(ppfTmp, iNumRows);
                        CMatrix::free(ppfEye, iNumRows);
                        return;
                    }
                }
            }
        }
        for (i = iNumRows - 1; i > 0; i--)
        {
            for (j = i - 1; j >= 0; j--)
            {
                CVector::subW_I(ppfEye[j], ppfEye[i], pptSrcDest[j][i], iNumCols);
                CVector::subW_I(pptSrcDest[j], pptSrcDest[i], pptSrcDest[j][i], iNumCols);
            }
        }
        copy(pptSrcDest, ppfEye, iNumRows, iNumCols);
        CMatrix::free(ppfTmp, iNumRows);
        CMatrix::free(ppfEye, iNumRows);
    }
References alloc(), copy(), free(), inv_I(), CVector::mulC_I(), setEye(), CVector::subW_I(), and swapRowCol().
Referenced by CGmm::compProbabilities_(), inv_I(), and CFilter< T >::setInitState_().
mul_I()
static void CMatrix::mul_I (float ** pptSrcDest, float ** pptSrc, int iNumRows, int iNumCols) inline static
elementwise multiplication of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 515 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] *= pptSrc[m][n];
        }
    }
Referenced by CNmf::runNmfIter().
mulC_I()
static void CMatrix::mulC_I (float ** pptMat, float fScale, int iNumRows, int iNumCols) inline static
multiplies the whole matrix with a single factor
Parameters
pptMat matrix to analyze
fScale scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 651 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::mulC_I(pptMat[m], fScale, iNumCols);
    }
References CVector::mulC_I().
Referenced by CPca::compCov(), CChordIf::initViterbi_(), and CGmm::updateState_().
mulColC_I()
static void CMatrix::mulColC_I (float ** pptMat, float fValue, int iCol, int iNumRows) inline static
multiplies a column of a matrix with a constant
Parameters
pptMat matrix with column to be multiplied
fValue value to multiply the column with
iCol index of column to be multiplied
iNumRows number of rows in the matrix
Returns
Definition at line 460 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iCol >= 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            pptMat[m][iCol] *= fValue;
    }
Referenced by CGmm::compProbabilities_().
mulColVecRowVec()
static void CMatrix::mulColVecRowVec (float ** pptDestMat, const float * ptSrcColVec, const float * ptSrcRowVec, int iNumMatRows, int iNumMatCols) inline static
multiplies a column vec with a row vec (VEC * VEC)
Parameters
pptDestMat resulting matrix of dimension iNumMatRows X iNumMatCols (to be written, user allocated)
ptSrcColVec (column) vector to be multiplied
ptSrcRowVec (row) vector to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 414 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(ptSrcRowVec);
        assert(ptSrcColVec);
        assert(pptDestMat);
        assert(pptDestMat[0]);
        for (auto m = 0; m < iNumMatRows; m++)
        {
            for (auto n = 0; n < iNumMatCols; n++)
                pptDestMat[m][n] = ptSrcColVec[m] * ptSrcRowVec[n];
        }
    }
Referenced by CGmm::updateState_().
mulMatColVec()
static void CMatrix::mulMatColVec (float * ptDestColVec, float ** pptMat, const float * ptSrcColVec, int iNumMatRows, int iNumMatCols) inline static
multiplies a matrix with a column vector (MAT * VEC)
Parameters
ptDestColVec resulting (column) vector of length iNumMatRows (to be written, user allocated)
pptMat matrix to be multiplied
ptSrcColVec (column) vector to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 393 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(ptDestColVec);
        assert(ptSrcColVec);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumMatRows; m++)
            ptDestColVec[m] = CVector::mulScalar(pptMat[m], ptSrcColVec, iNumMatCols);
    }
References CVector::mulScalar().
Referenced by CChordFromBlockIf::compChordProb(), CGmm::compProbabilities_(), and CFilter< T >::setInitState_().
mulMatMat()
static void CMatrix::mulMatMat (float ** pptDest, float ** pptSrc1, float ** pptSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols) inline static
multiplies a matrix with a matrix (MAT1 * MAT2)
Parameters
pptDest resulting matrix of dimension iNum1Rows x iNum2Cols (to be written, user allocated)
pptSrc1 first matrix to be multiplied
pptSrc2 second matrix to be multiplied
iNum1Rows number of rows in matrix 1
iNum1Cols number of columns in matrix 1 (has to equal iNum2Rows)
iNum2Rows number of rows in matrix 2 (has to equal iNum1Col)
iNum2Cols number of columns in matrix 2
Returns
Definition at line 481 of file Matrix.h.
    {
        assert(iNum1Rows > 0);
        assert(iNum1Cols > 0);
        assert(iNum2Rows > 0);
        assert(iNum2Cols > 0);
        assert(iNum1Cols == iNum2Rows);
        assert(pptDest);
        assert(pptDest[0]);
        assert(pptSrc1);
        assert(pptSrc1[0]);
        assert(pptSrc2);
        assert(pptSrc2[0]);
        iNum2Rows = iNum1Cols; // avoid compiler warning
        for (auto m = 0; m < iNum1Rows; m++)
        {
            for (auto n = 0; n < iNum2Cols; n++)
            {
                pptDest[m][n] = 0.F;
                for (auto k = 0; k < iNum1Cols; k++)
                    pptDest[m][n] += pptSrc1[m][k] * pptSrc2[k][n];
            }
        }
    }
Referenced by CPca::compPca(), and CNmf::runNmfIter().
mulRowVecMat()
static void CMatrix::mulRowVecMat (float * ptDestRowVec, const float * ptSrcRowVec, float ** pptMat, int iNumMatRows, int iNumMatCols) inline static
multiplies a row vector with a matrix (VEC * MAT)
Parameters
ptDestRowVec resulting (row) vector of length iNumMatCols (to be written, user allocated)
ptSrcRowVec (column) vector to be multiplied
pptMat matrix to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Returns
Definition at line 438 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(ptDestRowVec);
        assert(ptSrcRowVec);
        assert(pptMat);
        assert(pptMat[0]);
        CVector::setZero(ptDestRowVec, iNumMatCols);
        for (auto n = 0; n < iNumMatCols; n++)
            for (auto m = 0; m < iNumMatRows; m++)
                ptDestRowVec[n] += ptSrcRowVec[m] * pptMat[m][n];
    }
References CVector::setZero().
rearrangeRows()
static void CMatrix::rearrangeRows (float ** pptSrcDest, int * piRowIndices, int iNumRows) inline static
rearrange the rows of a matrix according to a row index vector
Parameters
pptSrcDest resorted matrix of dimension iNumRows x ?
piRowIndices new indices iNumRows
iNumRows number of rows in the matrix
Returns
Definition at line 342 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(piRowIndices);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        float** ppfTmp = 0;
        CVector::alloc(ppfTmp, iNumRows);
        for (auto m = 0; m < iNumRows; m++)
        {
            assert(piRowIndices[m] < iNumRows);
            assert(piRowIndices[m] >= 0);
            ppfTmp[m] = pptSrcDest[piRowIndices[m]];
        }
        CVector::copy(pptSrcDest, ppfTmp, iNumRows);
        CVector::free(ppfTmp);
    }
References CVector::alloc(), CVector::copy(), and CVector::free().
Referenced by CPca::compPca().
setCol()
template<typename T > static void CMatrix::setCol (T ** pptDestMat, T * ptSrcVec, int iColIdx, int iNumRows) inline static
copies vector content to a column
Parameters
pptDestMat (destination matrix, user allocated)
ptSrcVec (source vector)
iColIdx index of row to copy to
iNumRows number of columns
Returns
Definition at line 115 of file Matrix.h.
    {
        assert(pptDestMat);
        assert(ptSrcVec);
        assert(iColIdx >= 0);
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            pptDestMat[m][iColIdx] = ptSrcVec[m];
    }
Referenced by CChordIf::compChords(), and CChordIf::initViterbi_().
setEye()
static void CMatrix::setEye (float ** pptDest, int iNumRows, int iNumCols) inline static
fills matrix with ones on the diagonal, zeros elsewhere
Parameters
pptDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 151 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(pptDest);
        assert(pptDest[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            CVector::setZero(pptDest[m], iNumCols);
            pptDest[m][m] = 1.F;
        }
    }
References CVector::setZero().
Referenced by inv_I().
setRand()
template<typename T > static void CMatrix::setRand (T ** pptMat, int iNumRows, int iNumCols) inline static
sets a float matrix to random
Parameters
pptMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 96 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setRand(pptMat[m], iNumCols);
    }
References CVector::setRand().
Referenced by CNmfResult::init().
setRow()
template<typename T > static void CMatrix::setRow (T ** pptDestMat, T * ptSrcVec, int iRowIdx, int iNumCols) inline static
copies vector content to a row
Parameters
pptDestMat (destination matrix, user allocated)
ptSrcVec (source vector)
iRowIdx index of row to copy to
iNumCols number of columns
Returns
Definition at line 713 of file Matrix.h.
    {
        assert(pptDestMat);
        assert(ptSrcVec);
        assert(iRowIdx >= 0);
        assert(iNumCols > 0);
        CVector::copy(pptDestMat[iRowIdx], ptSrcVec, iNumCols);
    }
References CVector::copy().
setValue()
template<typename T > static void CMatrix::setValue (T ** pptMat, T tValue, int iNumRows, int iNumCols) inline static
sets a float matrix to zero
Parameters
pptMat pointer to memory to be set
tValue value to use
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 78 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setValue(pptMat[m], tValue, iNumCols);
    }
References CVector::setValue().
Referenced by CNmf::init().
setZero()
template<typename T > static void CMatrix::setZero (T ** pptMat, int iNumRows, int iNumCols) inline static
sets a float matrix to zero
Parameters
pptMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 59 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setZero(pptMat[m], iNumCols);
    }
References CVector::setZero().
Referenced by CPca::calcSVD(), CKmeans::compClusterMeans_(), CPca::compCov(), CSubFingerprint::genBands_(), and CGmm::updateState_().
setZeroBelowThresh()
template<typename T > static void CMatrix::setZeroBelowThresh (T ** pptMat, int iNumRows, int iNumCols, T tThresh) inline static
sets all elements in a matrix below a threshold to zero
Parameters
pptMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
tThresh threshold
Returns
Definition at line 134 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setZeroBelowThresh(pptMat[m], iNumCols, tThresh);
    }
References CVector::setZeroBelowThresh().
Referenced by CNmf::runNmfIter().
sub_I()
static void CMatrix::sub_I (float ** pptSrcDest, float ** pptSrc, int iNumRows, int iNumCols) inline static
elementwise subtraction of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Returns
Definition at line 561 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] -= pptSrc[m][n];
        }
    }
swapRowCol()
static void CMatrix::swapRowCol (float ** pptSrcDest, int iRowIdx, int iColIdx, int iNumCols) inline static
swaps a matrix row with a column in a square matrix
Parameters
pptSrcDest resulting matrix (to be modified)
iRowIdx index of row
iColIdx index of columns
iNumCols number of columns in the matrix
Returns
Definition at line 670 of file Matrix.h.
    {
        assert(iRowIdx > 0);
        assert(iColIdx > 0);
        assert(iNumCols > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            float fTmp = pptSrcDest[iRowIdx][n];
            pptSrcDest[iRowIdx][n] = pptSrcDest[iColIdx][n];
            pptSrcDest[iColIdx][n] = fTmp;
        }
    }
Referenced by det(), and inv_I().
transpose()
static void CMatrix::transpose (float ** pptDest, float ** pptSrc, int iNumSrcRows, int iNumSrcCols) inline static
transposes matrix pptSrc and write the result to pptDest
Parameters
pptDest resulting matrix of dimension iNumSrcCols x iNumSrcRows (to be written, user allocated)
pptSrc input matrix of dimension iNumSrcRows x iNumCols
iNumSrcRows number of rows in the matrix
iNumSrcCols number of columns in the matrix
Returns
Definition at line 320 of file Matrix.h.
    {
        assert(iNumSrcRows > 0);
        assert(iNumSrcCols > 0);
        assert(pptSrc);
        assert(pptSrc[0]);
        assert(pptDest);
        assert(pptDest[0]);
        for (auto m = 0; m < iNumSrcRows; m++)
        {
            for (auto n = 0; n < iNumSrcCols; n++)
                pptDest[n][m] = pptSrc[m][n];
        }
    }
Referenced by CPca::compPca(), CKnn::init(), and CNmf::runNmfIter().
vecnorm_I()
static void CMatrix::vecnorm_I (float ** pptSrcDest, int iNumRows, int iNumCols) inline static
normalizes each column of the matrix (p=1)
Parameters
pptSrcDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
Definition at line 268 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            float fNorm = 0;
            for (auto m = 0; m < iNumRows; m++)
                fNorm += std::abs(pptSrcDest[m][n]);
            if (fNorm > 0)
                for (auto m = 0; m < iNumRows; m++)
                    pptSrcDest[m][n] /= fNorm;
        }
    }
Referenced by CNmfResult::init(), and CNmf::runNmfIter().
The documentation for this class was generated from the following file:
Matrix.h