ACA: CMatrix Class Reference
CMatrix Class Reference
class with static functions for matrix operations, works with both float and double (functionality only added when needed)
#include <Matrix.h>
Static Public Member Functions
template<typename T >
static void alloc (T **&pptMat, int iNumRows, int iNumCols)
template<typename T >
static void copy (T **pptDestMat, const T *const *const pptSrcMat, int iNumRows, int iNumCols)
template<typename T >
static void free (T **&pptMat, int iNumRows)
template<typename T >
static void setCol (T **pptDestMat, const T *ptSrcVec, int iColIdx, int iNumRows)
template<typename T >
static void setEye (T **pptDest, int iNumRows, int iNumCols)
template<typename T >
static void setRand (T **pptMat, int iNumRows, int iNumCols)
template<typename T >
static void setRow (T **pptDestMat, const T *ptSrcVec, int iRowIdx, int iNumCols)
template<typename T >
static void setValue (T **pptMat, T tValue, int iNumRows, int iNumCols)
template<typename T >
static void setZero (T **pptMat, int iNumRows, int iNumCols)
template<typename T >
static void setZeroBelowThresh (T **pptMat, int iNumRows, int iNumCols, T tThresh)
template<typename T >
static void vecnorm_I (T **pptSrcDest, int iNumRows, int iNumCols)
template<typename T >
static void getCol (T *ptDest, const T *const *const pptMat, int iColIdx, int iNumRows)
template<typename T >
static void getDiag (T *ptDest, const T *const *const pptSrc, int iNumSrcRows, int iNumSrcCols)
template<typename T >
static T getMax (const T *const *const pptMat, int iNumRows, int iNumCols)
template<typename T >
static T getNorm (const T *const *const pptMat, int iNumRows, int iNumCols)
template<typename T >
static T getSum (T **pptMat, int iNumRows, int iNumCols, bool bAbs=false)
template<typename T >
static T getSumCol (T **pptMat, int iColIdx, int iNumRows, bool bAbs=false)
template<typename T >
static T calcKlDivergence (const T *const *const pptSrc1, const T *const *const pptSrc2, int iNumRows, int iNumCols)
template<typename T >
static void add_I (T **pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols)
template<typename T >
static void addC_I (T **pptMat, T tAdd, int iNumRows, int iNumCols)
template<typename T >
static void div_I (T **pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols, bool bAddSmallConst=false)
template<typename T >
static void mul_I (T **pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols)
template<typename T >
static void mulC_I (T **pptMat, T tScale, int iNumRows, int iNumCols)
template<typename T >
static void mulColC_I (T **pptMat, T fValue, int iCol, int iNumRows)
template<typename T >
static void mulColvecRowvec (T **pptDestMat, const T *ptSrcColVec, const T *ptSrcRowVec, int iNumMatRows, int iNumMatCols)
template<typename T >
static void mulMatColvec (T *ptDestColVec, const T *const *const pptMat, const T *ptSrcColVec, int iNumMatRows, int iNumMatCols)
template<typename T >
static void mulMatMat (T **pptDest, const T *const *const pptSrc1, const T *const *const pptSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols)
template<typename T >
static void mulRowvecMat (T *ptDestRowVec, const T *ptSrcRowVec, const T *const *const pptMat, int iNumMatRows, int iNumMatCols)
template<typename T >
static void sub_I (T **pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols)
template<typename T >
static T det (const T *const *const pptMat, int iNumRows, int iNumCols)
template<typename T >
static void inv_I (T **pptSrcDest, int iNumRows, int iNumCols)
template<typename T >
static void rearrangeRows (T **pptSrcDest, int *piRowIndices, int iNumRows)
template<typename T >
static void swapRowCol (T **pptSrcDest, int iRowIdx, int iColIdx, int iNumCols)
template<typename T >
static void transpose (T **pptDest, const T *const *const pptSrc, int iNumSrcRows, int iNumSrcCols)
Detailed Description
class with static functions for matrix operations, works with both float and double (functionality only added when needed)
Definition at line 11 of file Matrix.h.
Member Function Documentation
add_I()
template<typename T > static void CMatrix::add_I (T ** pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols) inline static
elementwise addition of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Definition at line 408 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] += pptSrc[m][n];
        }
    }
Referenced by CGmm::updateState_().
addC_I()
template<typename T > static void CMatrix::addC_I (T ** pptMat, T tAdd, int iNumRows, int iNumCols) inline static
adds a single value to all matrix elements
Parameters
pptMat matrix to analyze
tAdd scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Definition at line 431 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::addC_I(pptMat[m], tAdd, iNumCols);
    }
References CVector::addC_I().
Referenced by CChordIf::initViterbi_(), and CNmf::runNmfIter().
alloc()
template<typename T > static void CMatrix::alloc (T **& pptMat, int iNumRows, int iNumCols) inline static
allocates a matrix and inits it with zeros
Parameters
pptMat (empty double pointer, to be allocated)
iNumRows number of rows
iNumCols number of columns
Definition at line 23 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        CVector::alloc(pptMat, iNumRows);
        assert(pptMat);
        for (auto m = 0; m < iNumRows; m++)
            CVector::alloc(pptMat[m], iNumCols);
    }
References CVector::alloc().
Referenced by CFeatureSpectralMfccs::allocDctMat_(), CBlockAudioFile::CBlockAudioFile(), CChordFromBlockIf::CChordFromBlockIf(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::CFeatureSpectralPitchChroma(), CGmmResult::CGmmResult(), CNormalizeAudio::CNormalizeAudio(), CKey::compKey(), CPitchTimeAuditory::CPitchTimeAuditory(), CSubFingerprint::CSubFingerprint(), det(), CSpectrogramIf::generateMelFb_(), CGmm::init(), CNmf::init(), CViterbi::init(), CFingerprint::init(), CGmmResult::init(), CKmeans::init(), CPca::init(), CSeqFeatureSel::init(), CKnn::init(), CLeaveOneOutCrossVal::init(), CDtw::init(), CNmfResult::init(), CChordIf::init_(), CChordIf::initViterbi_(), inv_I(), CFilter< T >::setInitState_(), and CGmmClassifier::train().
calcKlDivergence()
template<typename T > static T CMatrix::calcKlDivergence (const T *const *const pptSrc1, const T *const *const pptSrc2, int iNumRows, int iNumCols) inline static
comnputes kl divergence between two matrices
Parameters
pptSrc1 matrix of dimension iNumRows x iNumCols
pptSrc2 matrix of dimension iNumRows x iNumCols
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
kld
Definition at line 379 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptSrc1);
        assert(pptSrc1[0]);
        assert(pptSrc2);
        assert(pptSrc2[0]);
        T tResult = 0;
        for (int i = 0; i < iNumRows; i++)
        {
            for (int j = 0; j < iNumCols; j++)
                tResult += pptSrc1[i][j] * (std::log((pptSrc1[i][j] + 1e-24F) / (pptSrc2[i][j] + 1e-24F)) - 1.F) + pptSrc2[i][j];
        }
        return tResult;
    }
Referenced by CNmf::runNmfIter().
copy()
template<typename T > static void CMatrix::copy (T ** pptDestMat, const T *const *const pptSrcMat, int iNumRows, int iNumCols) inline static
copies matrix content to another matrix
Parameters
pptDestMat (destination matrix, user allocated)
pptSrcMat (source matrix)
iNumRows number of rows
iNumCols number of columns
Definition at line 42 of file Matrix.h.
    {
        assert(pptDestMat);
        assert(pptSrcMat);
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::copy(pptDestMat[m], pptSrcMat[m], iNumCols);
    }
References CVector::copy().
Referenced by CPca::calcSVD(), CGmmResult::CGmmResult(), CKmeans::compKmeans(), det(), CNmfResult::getMat(), CGmmResult::getSigma(), CViterbi::init(), inv_I(), CGmmResult::operator=(), CLeaveOneOutCrossVal::process(), CNmf::runNmfIter(), and CGmmResult::setSigma().
det()
template<typename T > static T CMatrix::det (const T *const *const pptMat, int iNumRows, int iNumCols) inline static
Definition at line 659 of file Matrix.h.
    {
        assert(pptMat);
        assert(iNumRows == iNumCols);
        const T kSingularityThresh = 1e-15F;
        T **pptTmp = 0;
        double dDet = 1;
        if (iNumRows == 2)
            return ((pptMat[0][0] * pptMat[1][1]) - (pptMat[0][1] * pptMat[1][0]));
        CMatrix::alloc(pptTmp, iNumRows, iNumCols);
        CMatrix::copy(pptTmp, pptMat, iNumRows, iNumCols);
        if (pptTmp[0][0] == 0)
        {
            auto i = 1;
            while (i < iNumRows)
            {
                if (pptTmp[i][0] != 0)
                {
                    swapRowCol(pptTmp, 0, i, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        if (pptTmp[0][0] == 0)
        {
            CMatrix::free(pptTmp, iNumRows);
            return 0;
        }
        dDet *= pptTmp[0][0];
        CVector::mulC_I(pptTmp[0], 1.F / pptTmp[0][0], iNumCols);
        for (auto i = 1; i < iNumRows; i++)
        {
            auto j = 0;
            if (std::abs(dDet) < kSingularityThresh * 1. * kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVector::addW_I(pptTmp[i], pptTmp[j], -pptTmp[i][j], iNumCols);
                j++;
            }
            if (pptTmp[i][i] != 0)
            {
                dDet *= pptTmp[i][i];
                CVector::mulC_I(pptTmp[i], 1.F / pptTmp[i][i], iNumCols);
            }
            if (pptTmp[i][i] == 0)
            {
                for (j = i + 1; j < iNumCols; j++)
                {
                    if (pptTmp[i][j] != 0)
                    {
                        CVector::add_I(pptTmp[i], pptTmp[j], iNumCols);
                        dDet *= pptTmp[i][i];
                        CVector::mulC_I(pptTmp[i], 1.F / pptTmp[i][i], iNumCols);
                        break;
                    }
                }
            }
            if (pptTmp[i][i] == 0)
            {
                CMatrix::free(pptTmp, iNumRows);
                return 0;
            }
        }
        CMatrix::free(pptTmp, iNumRows);
        return static_cast<T>(dDet);
    }
References CVector::add_I(), CVector::addW_I(), alloc(), copy(), free(), CVector::mulC_I(), and swapRowCol().
Referenced by CGmm::compProbabilities_(), and CGmmResult::getProb().
div_I()
template<typename T > static void CMatrix::div_I (T ** pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols, bool bAddSmallConst = false) inline static
elementwise division of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
bAddSmallConst a small floating point number is added before division if true
Definition at line 450 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        T fEpsilon = bAddSmallConst ? 1e-30F : .0F;
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] /= (pptSrc[m][n] + fEpsilon);
        }
    }
Referenced by CNmf::runNmfIter().
free()
template<typename T > static void CMatrix::free (T **& pptMat, int iNumRows) inline static
frees a matrix
Parameters
pptMat (empty double pointer, to be set to zero)
iNumRows number of rows
Definition at line 58 of file Matrix.h.
    {
        if (!pptMat) return;
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            CVector::free(pptMat[m]);
        CVector::free(pptMat);
        pptMat = 0;
    }
References CVector::free().
Referenced by CNormalizeAudio::CNormalizeAudio(), CKey::compKey(), CFeatureSpectralMfccs::deleteDctMat_(), CSpectrogramIf::destroyMelFb_(), det(), CFingerprint::init(), CChordIf::initViterbi_(), inv_I(), CGmmResult::reset(), CGmm::reset(), CLeaveOneOutCrossVal::reset(), CNmfResult::reset(), CNmf::reset(), CPca::reset(), CSeqFeatureSel::reset(), CDtw::reset(), CKmeans::reset(), CViterbi::reset(), CKnn::reset(), CChordIf::reset_(), CFilter< T >::setInitState_(), CGmmClassifier::train(), CBlockAudioFile::~CBlockAudioFile(), CChordFromBlockIf::~CChordFromBlockIf(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureSpectralPitchChroma::~CFeatureSpectralPitchChroma(), CPitchTimeAuditory::~CPitchTimeAuditory(), and CSubFingerprint::~CSubFingerprint().
getCol()
template<typename T > static void CMatrix::getCol (T * ptDest, const T *const *const pptMat, int iColIdx, int iNumRows) inline static
returns a column as vector
Parameters
ptDest resulting vector of dimension iNumRows (to be written, user allocated)
pptMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iColIdx index of column to retrieve
iNumRows number of rows in the matrix
Definition at line 230 of file Matrix.h.
    {
        assert(iColIdx >= 0);
        assert(iNumRows > 0);
        assert(pptMat);
        assert(ptDest);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            ptDest[m] = pptMat[m][iColIdx];
    }
Referenced by CKmeans::assignClusterLabels_(), CLeaveOneOutCrossVal::process(), and CGmmClassifier::train().
getDiag()
template<typename T > static void CMatrix::getDiag (T * ptDest, const T *const *const pptSrc, int iNumSrcRows, int iNumSrcCols) inline static
returns matrix diagonal as vector
Parameters
ptDest resulting vector of dimension min(iNumSrcRows, iNumCols) (to be written, user allocated)
pptSrc input matrix of dimension iNumSrcRows x iNumCols
iNumSrcRows number of rows in the matrix
iNumSrcCols number of columns in the matrix
Definition at line 249 of file Matrix.h.
    {
        assert(iNumSrcRows > 0);
        assert(iNumSrcCols > 0);
        assert(pptSrc);
        assert(pptSrc[0]);
        assert(ptDest);
        int iLen = std::min(iNumSrcRows, iNumSrcCols);
        for (auto m = 0; m < iLen; m++)
            ptDest[m] = pptSrc[m][m];
    }
Referenced by CPca::compPca().
getMax()
template<typename T > static T CMatrix::getMax (const T *const *const pptMat, int iNumRows, int iNumCols) inline static
return maximum value in a matrix
Parameters
pptMat matrix to analyze
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
max
Definition at line 270 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        T fGlobalMax = CVector::getMax(pptMat[0], iNumCols);
        for (auto m = 1; m < iNumRows; m++)
        {
            T fMax = CVector::getMax(pptMat[m], iNumCols);
            if (fMax > fGlobalMax)
                fGlobalMax = fMax;
        }
        return fGlobalMax;
    }
References CVector::getMax().
Referenced by CChordIf::initViterbi_().
getNorm()
template<typename T > static T CMatrix::getNorm (const T *const *const pptMat, int iNumRows, int iNumCols) inline static
return the matrix norm (p=1)
Parameters
pptMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Returns
norm
Definition at line 294 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        T tResult = 0;
        for (auto n = 0; n < iNumCols; n++)
        {
            T tTmp = 0;
            for (auto m = 0; m < iNumRows; m++)
                tTmp += std::abs(pptMat[m][n]);
            if (tTmp > tResult)
                tResult = tTmp;
        }
        return tResult;
    }
Referenced by CNmf::runNmfIter().
getSum()
template<typename T > static T CMatrix::getSum (T ** pptMat, int iNumRows, int iNumCols, bool bAbs = false) inline static
adds all matrix elements
Parameters
pptMat input matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
bAbs flag to indicate whether to sum the absolute values
Returns
sum
Definition at line 324 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        T tResult = 0;
        for (auto m = 0; m < iNumRows; m++)
            tResult += CVector::getSum(pptMat[m], iNumCols, bAbs);
        return tResult;
    }
References CVector::getSum().
getSumCol()
template<typename T > static T CMatrix::getSumCol (T ** pptMat, int iColIdx, int iNumRows, bool bAbs = false) inline static
adds all elements in one columns
Parameters
pptMat input matrix of dimension iNumRows x iNumCols
iColIdx column of interest
iNumRows number of rows in the matrix
bAbs flag to indicate whether to sum the absolute values
Returns
sum
Definition at line 347 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(pptMat);
        assert(pptMat[0]);
        T tResult = 0;
        if (bAbs)
        {
            for (auto m = 0; m < iNumRows; m++)
                tResult += std::abs(pptMat[m][iColIdx]);
        }
        else
        {
            for (auto m = 0; m < iNumRows; m++)
                tResult += pptMat[m][iColIdx];
        }
        return tResult;
    }
Referenced by CGmm::compProbabilities_().
inv_I()
template<typename T > static void CMatrix::inv_I (T ** pptSrcDest, int iNumRows, int iNumCols) inline static
computes inverse of square matrix
Parameters
pptSrcDest input and output matrix (to be modified, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Definition at line 751 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        const T kSingularityThresh = 1e-15F;
        T **ppfTmp = 0;
        T **ppfEye = 0;
        int    i, j;
        double dDet = 1;
        alloc(ppfTmp, iNumRows, iNumCols);
        copy(ppfTmp, pptSrcDest, iNumRows, iNumCols);
        alloc(ppfEye, iNumRows, iNumCols);
        setEye(ppfEye, iNumRows, iNumCols);
        if (pptSrcDest[0][0] == 0)
        {
            i = 1;
            while (i < iNumRows)
            {
                if (pptSrcDest[i][0] != 0)
                {
                    swapRowCol(pptSrcDest, 0, i, iNumCols);
                    swapRowCol(ppfEye, 0, i, iNumCols);
                    dDet *= -1;
                    break;
                }
                i++;
            }
        }
        dDet *= pptSrcDest[0][0];
        CVector::mulC_I(ppfEye[0], 1.F / pptSrcDest[0][0], iNumCols);
        CVector::mulC_I(pptSrcDest[0], 1.F / pptSrcDest[0][0], iNumCols);
        for (i = 1; i < iNumRows; i++)
        {
            j = 0;
            if (std::abs(dDet) < kSingularityThresh * 1. * kSingularityThresh)
                dDet = 0;
            while (j < i)
            {
                CVector::subW_I(ppfEye[i], ppfEye[j], pptSrcDest[i][j], iNumCols);
                CVector::subW_I(pptSrcDest[i], pptSrcDest[j], pptSrcDest[i][j], iNumCols);
                j++;
            }
            if (pptSrcDest[i][i] != 0)
            {
                dDet *= pptSrcDest[i][i];
                CVector::mulC_I(ppfEye[i], 1.F / pptSrcDest[i][i], iNumCols);
                CVector::mulC_I(pptSrcDest[i], 1.F / pptSrcDest[i][i], iNumCols);
            }
            if (pptSrcDest[i][i] == 0)
            {
                for (int j1 = i + 1; j1 < iNumCols; j1++)
                {
                    if (pptSrcDest[i][j1] != 0)
                    {
                        for (int i1 = 0; i1 < iNumRows; i1++)
{
                            for (j = 0; j < iNumCols; j++)
                                pptSrcDest[i1][j] = ppfTmp[i1][j];
                        }
                        inv_I(ppfTmp, iNumRows, iNumCols);
                        copy(pptSrcDest, ppfTmp, iNumRows, iNumCols);
                        CMatrix::free(ppfTmp, iNumRows);
                        CMatrix::free(ppfEye, iNumRows);
                        return;
                    }
                }
            }
        }
        for (i = iNumRows - 1; i > 0; i--)
        {
            for (j = i - 1; j >= 0; j--)
            {
                CVector::subW_I(ppfEye[j], ppfEye[i], pptSrcDest[j][i], iNumCols);
                CVector::subW_I(pptSrcDest[j], pptSrcDest[i], pptSrcDest[j][i], iNumCols);
            }
        }
        copy(pptSrcDest, ppfEye, iNumRows, iNumCols);
        CMatrix::free(ppfTmp, iNumRows);
        CMatrix::free(ppfEye, iNumRows);
    }
References alloc(), copy(), free(), inv_I(), CVector::mulC_I(), setEye(), CVector::subW_I(), and swapRowCol().
Referenced by CGmm::compProbabilities_(), inv_I(), CFilter< T >::setInitState_(), and CGmmResult::setSigma().
mul_I()
template<typename T > static void CMatrix::mul_I (T ** pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols) inline static
elementwise multiplication of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Definition at line 475 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] *= pptSrc[m][n];
        }
    }
Referenced by CNmf::runNmfIter().
mulC_I()
template<typename T > static void CMatrix::mulC_I (T ** pptMat, T tScale, int iNumRows, int iNumCols) inline static
multiplies the whole matrix with a single factor
Parameters
pptMat matrix to analyze
tScale scaling factor to apply
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Definition at line 498 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::mulC_I(pptMat[m], tScale, iNumCols);
    }
References CVector::mulC_I().
Referenced by CPca::compCov(), CChordIf::initViterbi_(), and CGmm::updateState_().
mulColC_I()
template<typename T > static void CMatrix::mulColC_I (T ** pptMat, T fValue, int iCol, int iNumRows) inline static
multiplies a column of a matrix with a constant
Parameters
pptMat matrix with column to be multiplied
fValue value to multiply the column with
iCol index of column to be multiplied
iNumRows number of rows in the matrix
Definition at line 517 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iCol >= 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            pptMat[m][iCol] *= fValue;
    }
Referenced by CGmm::compProbabilities_().
mulColvecRowvec()
template<typename T > static void CMatrix::mulColvecRowvec (T ** pptDestMat, const T * ptSrcColVec, const T * ptSrcRowVec, int iNumMatRows, int iNumMatCols) inline static
multiplies a column vec with a row vec (VEC * VEC)
Parameters
pptDestMat resulting matrix of dimension iNumMatRows X iNumMatCols (to be written, user allocated)
ptSrcColVec (column) vector to be multiplied
ptSrcRowVec (row) vector to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Definition at line 536 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(ptSrcRowVec);
        assert(ptSrcColVec);
        assert(pptDestMat);
        assert(pptDestMat[0]);
        for (auto m = 0; m < iNumMatRows; m++)
        {
            for (auto n = 0; n < iNumMatCols; n++)
                pptDestMat[m][n] = ptSrcColVec[m] * ptSrcRowVec[n];
        }
    }
Referenced by CGmm::updateState_().
mulMatColvec()
template<typename T > static void CMatrix::mulMatColvec (T * ptDestColVec, const T *const *const pptMat, const T * ptSrcColVec, int iNumMatRows, int iNumMatCols) inline static
multiplies a matrix with a column vector (MAT * VEC)
Parameters
ptDestColVec resulting (column) vector of length iNumMatRows (to be written, user allocated)
pptMat matrix to be multiplied
ptSrcColVec (column) vector to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Definition at line 560 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(ptDestColVec);
        assert(ptSrcColVec);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumMatRows; m++)
            ptDestColVec[m] = CVector::mulScalar(pptMat[m], ptSrcColVec, iNumMatCols);
    }
References CVector::mulScalar().
Referenced by CChordFromBlockIf::compChordProb(), CGmm::compProbabilities_(), CGmmResult::getProb(), and CFilter< T >::setInitState_().
mulMatMat()
template<typename T > static void CMatrix::mulMatMat (T ** pptDest, const T *const *const pptSrc1, const T *const *const pptSrc2, int iNum1Rows, int iNum1Cols, int iNum2Rows, int iNum2Cols) inline static
multiplies a matrix with a matrix (MAT1 * MAT2)
Parameters
pptDest resulting matrix of dimension iNum1Rows x iNum2Cols (to be written, user allocated)
pptSrc1 first matrix to be multiplied
pptSrc2 second matrix to be multiplied
iNum1Rows number of rows in matrix 1
iNum1Cols number of columns in matrix 1 (has to equal iNum2Rows)
iNum2Rows number of rows in matrix 2 (has to equal iNum1Col)
iNum2Cols number of columns in matrix 2
Definition at line 583 of file Matrix.h.
    {
        assert(iNum1Rows > 0);
        assert(iNum1Cols > 0);
        assert(iNum2Rows > 0);
        assert(iNum2Cols > 0);
        assert(iNum1Cols == iNum2Rows);
        assert(pptDest);
        assert(pptDest[0]);
        assert(pptSrc1);
        assert(pptSrc1[0]);
        assert(pptSrc2);
        assert(pptSrc2[0]);
        iNum2Rows = iNum1Cols; // avoid compiler warning
        for (auto m = 0; m < iNum1Rows; m++)
        {
            for (auto n = 0; n < iNum2Cols; n++)
            {
                pptDest[m][n] = 0.F;
                for (auto k = 0; k < iNum1Cols; k++)
                    pptDest[m][n] += pptSrc1[m][k] * pptSrc2[k][n];
            }
        }
    }
Referenced by CPca::compPca(), and CNmf::runNmfIter().
mulRowvecMat()
template<typename T > static void CMatrix::mulRowvecMat (T * ptDestRowVec, const T * ptSrcRowVec, const T *const *const pptMat, int iNumMatRows, int iNumMatCols) inline static
multiplies a row vector with a matrix (VEC * MAT)
Parameters
ptDestRowVec resulting (row) vector of length iNumMatCols (to be written, user allocated)
ptSrcRowVec (column) vector to be multiplied
pptMat matrix to be multiplied
iNumMatRows number of rows in the matrix
iNumMatCols number of columns in the matrix
Definition at line 618 of file Matrix.h.
    {
        assert(iNumMatRows > 0);
        assert(iNumMatCols > 0);
        assert(ptDestRowVec);
        assert(ptSrcRowVec);
        assert(pptMat);
        assert(pptMat[0]);
        CVector::setZero(ptDestRowVec, iNumMatCols);
        for (auto n = 0; n < iNumMatCols; n++)
            for (auto m = 0; m < iNumMatRows; m++)
                ptDestRowVec[n] += ptSrcRowVec[m] * pptMat[m][n];
    }
References CVector::setZero().
rearrangeRows()
template<typename T > static void CMatrix::rearrangeRows (T ** pptSrcDest, int * piRowIndices, int iNumRows) inline static
rearrange the rows of a matrix according to a row index vector
Parameters
pptSrcDest resorted matrix of dimension iNumRows x ?
piRowIndices new indices iNumRows
iNumRows number of rows in the matrix
Definition at line 854 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(piRowIndices);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        T **pptTmp = 0;
        CVector::alloc(pptTmp, iNumRows);
        for (auto m = 0; m < iNumRows; m++)
        {
            assert(piRowIndices[m] < iNumRows);
            assert(piRowIndices[m] >= 0);
            pptTmp[m] = pptSrcDest[piRowIndices[m]];
        }
        CVector::copy(pptSrcDest, pptTmp, iNumRows);
        CVector::free(pptTmp);
    }
References CVector::alloc(), CVector::copy(), and CVector::free().
Referenced by CPca::compPca().
setCol()
template<typename T > static void CMatrix::setCol (T ** pptDestMat, const T * ptSrcVec, int iColIdx, int iNumRows) inline static
copies vector content to a column
Parameters
pptDestMat (destination matrix, user allocated)
ptSrcVec (source vector)
iColIdx index of row to copy to
iNumRows number of columns
Definition at line 79 of file Matrix.h.
    {
        assert(pptDestMat);
        assert(ptSrcVec);
        assert(iColIdx >= 0);
        assert(iNumRows > 0);
        for (auto m = 0; m < iNumRows; m++)
            pptDestMat[m][iColIdx] = ptSrcVec[m];
    }
Referenced by CChordIf::compChords(), CChordIf::initViterbi_(), CLeaveOneOutCrossVal::process(), and CGmmClassifier::train().
setEye()
template<typename T > static void CMatrix::setEye (T ** pptDest, int iNumRows, int iNumCols) inline static
fills matrix with ones on the diagonal, zeros elsewhere
Parameters
pptDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Definition at line 96 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows == iNumCols);
        assert(pptDest);
        assert(pptDest[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            CVector::setZero(pptDest[m], iNumCols);
            pptDest[m][m] = 1.F;
        }
    }
References CVector::setZero().
Referenced by inv_I().
setRand()
template<typename T > static void CMatrix::setRand (T ** pptMat, int iNumRows, int iNumCols) inline static
sets all matrix elements to a random value
Parameters
pptMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
Definition at line 116 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setRand(pptMat[m], iNumCols);
    }
References CVector::setRand().
Referenced by CNmfResult::init().
setRow()
template<typename T > static void CMatrix::setRow (T ** pptDestMat, const T * ptSrcVec, int iRowIdx, int iNumCols) inline static
copies vector content to a row
Parameters
pptDestMat (destination matrix, user allocated)
ptSrcVec (source vector)
iRowIdx index of row to copy to
iNumCols number of columns
Definition at line 134 of file Matrix.h.
    {
        assert(pptDestMat);
        assert(ptSrcVec);
        assert(iRowIdx >= 0);
        assert(iNumCols > 0);
        CVector::copy(pptDestMat[iRowIdx], ptSrcVec, iNumCols);
    }
References CVector::copy().
setValue()
template<typename T > static void CMatrix::setValue (T ** pptMat, T tValue, int iNumRows, int iNumCols) inline static
sets all matrix elements to a value
Parameters
pptMat pointer to memory to be set
tValue value to use
iNumRows number of rows
iNumCols number of columns
Definition at line 151 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setValue(pptMat[m], tValue, iNumCols);
    }
References CVector::setValue().
Referenced by CNmf::init().
setZero()
template<typename T > static void CMatrix::setZero (T ** pptMat, int iNumRows, int iNumCols) inline static
sets all matrix elements to zero
Parameters
pptMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
Definition at line 168 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setZero(pptMat[m], iNumCols);
    }
References CVector::setZero().
Referenced by CPca::calcSVD(), CKmeans::compClusterMeans_(), CPca::compCov(), CSubFingerprint::genBands_(), CLeaveOneOutCrossVal::init(), and CGmm::updateState_().
setZeroBelowThresh()
template<typename T > static void CMatrix::setZeroBelowThresh (T ** pptMat, int iNumRows, int iNumCols, T tThresh) inline static
sets all elements in a matrix below a threshold to zero
Parameters
pptMat pointer to memory to be set
iNumRows number of rows
iNumCols number of columns
tThresh threshold
Definition at line 186 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptMat);
        assert(pptMat[0]);
        for (auto m = 0; m < iNumRows; m++)
            CVector::setZeroBelowThresh(pptMat[m], iNumCols, tThresh);
    }
References CVector::setZeroBelowThresh().
Referenced by CNmf::runNmfIter().
sub_I()
template<typename T > static void CMatrix::sub_I (T ** pptSrcDest, const T *const *const pptSrc, int iNumRows, int iNumCols) inline static
elementwise subtraction of two matrices inplace
Parameters
pptSrcDest resulting matrix
pptSrc matrix to be multiplied
iNumRows number of rows
iNumCols number of columns
Definition at line 640 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumRows > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        assert(pptSrc);
        assert(pptSrc[0]);
        for (auto m = 0; m < iNumRows; m++)
        {
            for (auto n = 0; n < iNumCols; n++)
                pptSrcDest[m][n] -= pptSrc[m][n];
        }
    }
swapRowCol()
template<typename T > static void CMatrix::swapRowCol (T ** pptSrcDest, int iRowIdx, int iColIdx, int iNumCols) inline static
swaps a matrix row with a column in a square matrix
Parameters
pptSrcDest resulting matrix (to be modified)
iRowIdx index of row
iColIdx index of columns
iNumCols number of columns in the matrix
Definition at line 883 of file Matrix.h.
    {
        assert(iRowIdx > 0);
        assert(iColIdx > 0);
        assert(iNumCols > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            T fTmp = pptSrcDest[iRowIdx][n];
            pptSrcDest[iRowIdx][n] = pptSrcDest[iColIdx][n];
            pptSrcDest[iColIdx][n] = fTmp;
        }
    }
Referenced by det(), and inv_I().
transpose()
template<typename T > static void CMatrix::transpose (T ** pptDest, const T *const *const pptSrc, int iNumSrcRows, int iNumSrcCols) inline static
transposes matrix pptSrc and write the result to pptDest
Parameters
pptDest resulting matrix of dimension iNumSrcCols x iNumSrcRows (to be written, user allocated)
pptSrc input matrix of dimension iNumSrcRows x iNumCols
iNumSrcRows number of rows in the matrix
iNumSrcCols number of columns in the matrix
Definition at line 906 of file Matrix.h.
    {
        assert(iNumSrcRows > 0);
        assert(iNumSrcCols > 0);
        assert(pptSrc);
        assert(pptSrc[0]);
        assert(pptDest);
        assert(pptDest[0]);
        for (auto m = 0; m < iNumSrcRows; m++)
        {
            for (auto n = 0; n < iNumSrcCols; n++)
                pptDest[n][m] = pptSrc[m][n];
        }
    }
Referenced by CPca::compPca(), CNmf::runNmfIter(), and CKnn::train().
vecnorm_I()
template<typename T > static void CMatrix::vecnorm_I (T ** pptSrcDest, int iNumRows, int iNumCols) inline static
normalizes each column of the matrix (p=1)
Parameters
pptSrcDest resulting matrix of dimension iNumRows x iNumCols (to be written, user allocated)
iNumRows number of rows in the matrix
iNumCols number of columns in the matrix
Definition at line 203 of file Matrix.h.
    {
        assert(iNumRows > 0);
        assert(iNumCols > 0);
        assert(pptSrcDest);
        assert(pptSrcDest[0]);
        for (auto n = 0; n < iNumCols; n++)
        {
            T tNorm = 0;
            for (auto m = 0; m < iNumRows; m++)
                tNorm += std::abs(pptSrcDest[m][n]);
            if (tNorm > 0)
                for (auto m = 0; m < iNumRows; m++)
                    pptSrcDest[m][n] /= tNorm;
        }
    }
Referenced by CNmfResult::init(), and CNmf::runNmfIter().
The documentation for this class was generated from the following file:
Matrix.h