ACA: CUtil Class Reference
CUtil Class Reference
class with static utility functions
#include <Util.h>
Static Public Member Functions
template<typename T >
static T float2int (float fIn)
template<typename T >
static T double2int (double fIn)
static bool isPowOf2 (int n)
static int nextPowOf2 (int n)
template<typename T >
static void swap (T &tValue1, T &tValue2)
static float sign (float fValue)
static int sign (int iValue)
Detailed Description
class with static utility functions
Definition at line 10 of file Util.h.
Member Function Documentation
double2int()
template<typename T > static T CUtil::double2int (double fIn) inline static
converts a double to an int
Parameters
fIn double value
Returns
T
Definition at line 30 of file Util.h.
    {
        if (fIn >= 0)
            return static_cast<T>(fIn + .5);
        else
            return static_cast<T>(fIn - .5);
    }
float2int()
template<typename T > static T CUtil::float2int (float fIn) inline static
converts a float to an int
Parameters
fIn float value
Returns
T
Definition at line 18 of file Util.h.
    {
        if (fIn >= 0.F)
            return static_cast<T>(fIn + .5);
        else
            return static_cast<T>(fIn - .5);
    }
isPowOf2()
static bool CUtil::isPowOf2 (int n) inline static
checks if the input is a power of 2
Parameters
n integer value
Returns
bool
Definition at line 42 of file Util.h.
    {
        return !(n & (n - 1));
    }
Referenced by CBeatHistoIf::create(), CChordIf::create(), CFeatureIf::create(), CNoveltyIf::create(), CPitchIf::create(), CSpectrogramIf::create(), CCcf::init(), and CFft::init().
nextPowOf2()
static int CUtil::nextPowOf2 (int n) inline static
converts an arbitrary integer (positive) to the next larger power of two
Parameters
n integer value
Returns
int
Definition at line 51 of file Util.h.
    {
        int iOrder = 0;
        if (n <= 0)
            return 0;
        while (n >> iOrder)
            iOrder++;
        if (!(n % (1 << (iOrder - 1))))
            iOrder--;
        return (1 << (iOrder));
    }
Referenced by CCcf::init(), and CFft::init().
sign() [1/2]
static float CUtil::sign (float fValue) inline static
returns the sign of a value
Parameters
fValue value
Returns
float -1, 0, or 1
Definition at line 84 of file Util.h.
    {
        if (fValue > 0) return 1.F;
        if (fValue < 0) return -1.F;
        return 0.F;
    }
Referenced by CFeatureFromBlockIf::compFeatureTimeZeroCrossingRate().
sign() [2/2]
static int CUtil::sign (int iValue) inline static
returns the sign of a value
Parameters
iValue value
Returns
int -1, 0, or 1
Definition at line 96 of file Util.h.
    {
        if (iValue > 0) return 1;
        if (iValue < 0) return -1;
        return 0;
    }
swap()
template<typename T > static void CUtil::swap (T & tValue1, T & tValue2) inline static
swaps two values
Parameters
tValue1 first value
tValue2 second value
Definition at line 72 of file Util.h.
    {
        T tTmp = tValue1;
        tValue1 = tValue2;
        tValue2 = tTmp;
    }
Referenced by CDtw::compDtw(), CSubFingerprint::compSubFingerprint(), CKnn::countMaxima_(), CInstFreq::process(), and CVector::sort_I().
The documentation for this class was generated from the following file:
Util.h