ACA: CBlockAudioFile Class Reference
CBlockAudioFile Class Reference
class for audio blocking from a file
Public Member Functions
CBlockAudioFile (CAudioFileIf *pCAudioFile, int iBlockLength, int iHopLength)
virtual ~CBlockAudioFile ()
bool isEndOfData () const override
int getNextBlock (float *pfBlock, float *pfTimeStamp) override
Public Member Functions inherited from CBlockAudioIf
long long getNumBlocks () const
long long getLengthInSamples () const
float getTimeStamp (long long iBlockIdx)
virtual bool isEndOfData () const =0
virtual int getNextBlock (float *pfBlock, float *pfTimeStampInS=0)=0
Private Member Functions
CBlockAudioFile (const CBlockAudioFile &that)
disallow copy construction
CBlockAudioFile & operator= (const CBlockAudioFile &c)
void readFile2RingBuff ()
Private Attributes
CAudioFileIf * m_pCAudioFile
CRingBuffer< float > * m_pCRingBuff
float ** m_ppfAudioData
Additional Inherited Members
Static Public Member Functions inherited from CBlockAudioIf
static Error_t create (CBlockAudioIf *&pCInstance, CAudioFileIf *pCAudioFile, int iBlockLength, int iHopLength)
static Error_t create (CBlockAudioIf *&pCInstance, const float *pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate)
static Error_t destroy (CBlockAudioIf *&pCInstance)
Protected Member Functions inherited from CBlockAudioIf
CBlockAudioIf ()
virtual ~CBlockAudioIf ()
CBlockAudioIf (const CBlockAudioIf &that)
CBlockAudioIf & operator= (const CBlockAudioIf &c)
Protected Attributes inherited from CBlockAudioIf
long long m_iNumBlocks = 0
number of blocks
long long m_iCurrBlock = 0
current block index
long long m_iAudioLength = 0
length of audio buffer
int m_iBlockLength = 0
block length
int m_iNumChannels = 0
number of channels
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
Detailed Description
class for audio blocking from a file
Definition at line 13 of file ToolBlockAudio.cpp.
Constructor & Destructor Documentation
CBlockAudioFile() [1/2]
CBlockAudioFile::CBlockAudioFile (CAudioFileIf * pCAudioFile, int iBlockLength, int iHopLength) inline
Definition at line 16 of file ToolBlockAudio.cpp.
                                                                                 :
        m_pCAudioFile(pCAudioFile),
        m_pCRingBuff(0),
        m_ppfAudioData(0)
    {
        m_iBlockLength = iBlockLength;
        m_iHopLength = iHopLength;
        CAudioFileIf::FileSpec_t stFileSpec;
        // get length of audio file
        m_pCAudioFile->getLength(m_iAudioLength);
        m_pCAudioFile->getFileSpec(stFileSpec);
        m_iNumChannels = stFileSpec.iNumChannels;
        m_fSampleRate = stFileSpec.fSampleRateInHz;
        // compute number of blocks
        m_iNumBlocks = m_iAudioLength / m_iHopLength + 1;
        // initialize read buffers
        m_pCRingBuff = new CRingBuffer<float>(iBlockLength + 1);
        CMatrix::alloc(m_ppfAudioData, m_iNumChannels, iHopLength);
        // prefill from file to read buffer
        while (m_pCRingBuff->getNumValuesInBuffer() < m_pCRingBuff->getLength() - m_iHopLength - 1)
            readFile2RingBuff();
    }
References CMatrix::alloc(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CAudioFileIf::getFileSpec(), CRingBuffer< T >::getLength(), CAudioFileIf::getLength(), CRingBuffer< T >::getNumValuesInBuffer(), CAudioFileIf::FileSpec_t::iNumChannels, CBlockAudioIf::m_fSampleRate, CBlockAudioIf::m_iAudioLength, CBlockAudioIf::m_iBlockLength, CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumBlocks, CBlockAudioIf::m_iNumChannels, m_pCAudioFile, m_pCRingBuff, m_ppfAudioData, and readFile2RingBuff().
~CBlockAudioFile()
virtual CBlockAudioFile::~CBlockAudioFile () inline virtual
Definition at line 44 of file ToolBlockAudio.cpp.
    {
        CVector::free(m_pCRingBuff);
        CMatrix::free(m_ppfAudioData, m_iNumChannels);
    }
References CVector::free(), CMatrix::free(), CBlockAudioIf::m_iNumChannels, m_pCRingBuff, and m_ppfAudioData.
CBlockAudioFile() [2/2]
CBlockAudioFile::CBlockAudioFile (const CBlockAudioFile & that) private
disallow copy construction
Member Function Documentation
getNextBlock()
int CBlockAudioFile::getNextBlock (float * pfBlock, float * pfTimeStampInS) inline override virtual
retrieves audio data for next block
Parameters
pfBlock (to be written) of length blocklength
pfTimeStampInS (to be written, optional) for current time stamp
Returns
int iNumsamplesRead
Implements CBlockAudioIf.
Definition at line 56 of file ToolBlockAudio.cpp.
    {
        if (!m_pCAudioFile || !pfBlock)
            return -1;
        // read from file to read buffer
        readFile2RingBuff();
        int iNumSamples = m_iBlockLength;
        if (m_pCAudioFile->isEof())
            iNumSamples = m_pCRingBuff->getNumValuesInBuffer();
        // get data from ringbuffer and increment read index
        m_pCRingBuff->get(pfBlock, iNumSamples);
        if (iNumSamples < m_iBlockLength)
        {
            for (int c = 0; c < m_iNumChannels; c++)
                CVector::setZero(&pfBlock[iNumSamples], static_cast<long long>(m_iBlockLength) - iNumSamples);
            iNumSamples = m_iHopLength;
        }
        m_pCRingBuff->setReadIdx(m_pCRingBuff->getReadIdx() + m_iHopLength);
        if (pfTimeStamp)
            *pfTimeStamp = getTimeStamp(m_iCurrBlock);
        m_iCurrBlock++;
        return iNumSamples;
    }
References CRingBuffer< T >::get(), CRingBuffer< T >::getNumValuesInBuffer(), CRingBuffer< T >::getReadIdx(), CBlockAudioIf::getTimeStamp(), CAudioFileIf::isEof(), CBlockAudioIf::m_iBlockLength, CBlockAudioIf::m_iCurrBlock, CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumChannels, m_pCAudioFile, m_pCRingBuff, readFile2RingBuff(), CRingBuffer< T >::setReadIdx(), and CVector::setZero().
isEndOfData()
bool CBlockAudioFile::isEndOfData () const inline override virtual
checks for end of data
Returns
bool true if end of audio data is reached
Implements CBlockAudioIf.
Definition at line 50 of file ToolBlockAudio.cpp.
    {
        assert(m_pCAudioFile);
        return m_pCAudioFile->isEof();
    }
References CAudioFileIf::isEof(), and m_pCAudioFile.
operator=()
CBlockAudioFile & CBlockAudioFile::operator= (const CBlockAudioFile & c) private
readFile2RingBuff()
void CBlockAudioFile::readFile2RingBuff () inline private
Definition at line 91 of file ToolBlockAudio.cpp.
    {
        // set file read length variable
        //long long iNumSamples = std::min(m_iHopLength, m_pCRingBuff->getLength() - m_pCRingBuff->getNumValuesInBuffer() + 1);
        long long iNumSamples = m_iHopLength;
        // read data (iNumOfSamples might be updated!)
        m_pCAudioFile->readData(m_ppfAudioData, iNumSamples);
        // set buffer to zero if not written (EOF)
        if (iNumSamples < m_iHopLength)
        {
            for (int c = 0; c < m_iNumChannels; c++)
                CVector::setZero(&m_ppfAudioData[c][iNumSamples], m_iHopLength - iNumSamples);
            iNumSamples = m_iHopLength;
        }
        // downmix in case of multichannel
        CPreProc::downmix(m_ppfAudioData[0], m_ppfAudioData, m_iNumChannels, iNumSamples);
        // write data into inputbuffer
        m_pCRingBuff->putPostInc(m_ppfAudioData[0], m_iHopLength);
    }
References CPreProc::downmix(), CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumChannels, m_pCAudioFile, m_pCRingBuff, m_ppfAudioData, CRingBuffer< T >::putPostInc(), CAudioFileIf::readData(), and CVector::setZero().
Referenced by CBlockAudioFile(), and getNextBlock().
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CBlockAudioFile::m_pCAudioFile private
Definition at line 115 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioFile(), getNextBlock(), isEndOfData(), and readFile2RingBuff().
m_pCRingBuff
CRingBuffer<float>* CBlockAudioFile::m_pCRingBuff private
Definition at line 116 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioFile(), getNextBlock(), readFile2RingBuff(), and ~CBlockAudioFile().
m_ppfAudioData
float** CBlockAudioFile::m_ppfAudioData private
Definition at line 117 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioFile(), readFile2RingBuff(), and ~CBlockAudioFile().
The documentation for this class was generated from the following file:
ToolBlockAudio.cpp