ACA: CAudioFileIf Class Reference
CAudioFileIf Class Reference abstract
open, read, and write audio files
#include <AudioFileIf.h>
Classes
struct FileSpec_t
Public Types
enum FileIoType_t { kFileRead = 0x1L , kFileWrite = 0x2L , kNumFileOpenTypes = 2 }
enum FileFormat_t {
kFileFormatRaw , kFileFormatWav , kFileFormatAiff , kFileFormatUnknown ,
kNumFileFormats
}
enum BitStream_t { kFileBitStreamInt16 , kFileBitStreamFloat32 , kFileBitStreamUnknown , kNumWordLengths }
Public Member Functions
virtual Error_t reset (bool bFreeMemory=false)
virtual Error_t openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const *psFileSpec=0)=0
virtual Error_t closeFile ()=0
virtual Error_t readData (float **ppfAudioData, long long int &iNumFrames)
virtual Error_t writeData (float **ppfAudioData, long long int iNumFrames)
Error_t getFileSpec (FileSpec_t &sFileSpec)
virtual Error_t setPosition (long long iFrame=0)
Error_t setPosition (double dTimeInS=.0)
Error_t setClippingEnabled (bool bisEnabled=true)
bool isClippingEnabled ()
Error_t getPosition (long long &iFrame)
Error_t getPosition (double &dTimeInS)
Error_t getLength (long long &iLengthInFrames)
Error_t getLength (double &dLengthInSeconds)
virtual bool isEof ()=0
virtual bool isOpen ()=0
virtual bool isInitialized ()
Static Public Member Functions
static Error_t create (CAudioFileIf *&pCInstance)
static Error_t destroy (CAudioFileIf *&pCInstance)
Protected Member Functions
CAudioFileIf ()
virtual ~CAudioFileIf ()
virtual Error_t freeMemory_ ()
virtual Error_t allocMemory_ ()
Error_t setInitialized_ (bool bInitialized=true)
Error_t setIoType_ (FileIoType_t eIoType)
FileIoType_t getIoType_ () const
Error_t setFileSpec_ (const FileSpec_t *pFileSpec)
int getNumChannels_ () const
long long convFrames2Bytes_ (long long iNumFrames)
long long convBytes2Frames_ (long long iNumFrames)
Error_t setNumBytesPerSample_ (int iNumBytes)
int getNumBytesPerSample_ () const
int getNumBitsPerSample_ () const
float clip2Range_ (float fSample2Clip, float fMin, float fMax)
Static Protected Attributes
static const long long int m_kiDefBlockLength = 1024
buffer length for read and write operations
Private Member Functions
CAudioFileIf (const CAudioFileIf &that)
CAudioFileIf & operator= (const CAudioFileIf &c)
virtual Error_t initDefaults_ ()
virtual long long int readDataIntern_ (float **ppfAudioData, long long int iLength)=0
virtual long long int writeDataIntern_ (float **ppfAudioData, long long int iLength)=0
virtual long long getLengthIntern_ ()=0
virtual long long getPositionIntern_ ()=0
virtual Error_t setPositionIntern_ (long long iFrame)=0
Private Attributes
FileSpec_t m_CurrFileSpec
current file specifications
FileIoType_t m_eIoType
read or write
bool m_bWithClipping = false
true if abs(values) > 1 should be clipped
bool m_bIsInitialized = false
true if initialized
int m_iNumBytesPerSample = 0
number of bytes per sample for the raw pcm IO option without sndlib
Detailed Description
open, read, and write audio files
Definition at line 11 of file AudioFileIf.h.
Member Enumeration Documentation
BitStream_t
enum CAudioFileIf::BitStream_t
Enumerator
kFileBitStreamInt16
a sample is two byte (int16)
kFileBitStreamFloat32
a sample is four byte (float32) (not available without sndlib)
kFileBitStreamUnknown
word length is unknown
kNumWordLengths
Definition at line 30 of file AudioFileIf.h.
    {
        kFileBitStreamInt16,    //!< a sample is two byte (int16)
        kFileBitStreamFloat32,  //!< a sample is four byte (float32)  (not available without sndlib)
        kFileBitStreamUnknown,  //!< word length is unknown
        kNumWordLengths
    };
FileFormat_t
enum CAudioFileIf::FileFormat_t
Enumerator
kFileFormatRaw
file is raw pcm format
kFileFormatWav
file is wav riff format (not available without sndlib)
kFileFormatAiff
file is aiff format (not available without sndlib)
kFileFormatUnknown
file format is unknown
kNumFileFormats
Definition at line 21 of file AudioFileIf.h.
    {
        kFileFormatRaw,         //!< file is raw pcm format
        kFileFormatWav,         //!< file is wav riff format (not available without sndlib)
        kFileFormatAiff,        //!< file is aiff format (not available without sndlib)
        kFileFormatUnknown,     //!< file format is unknown
        kNumFileFormats
    };
FileIoType_t
enum CAudioFileIf::FileIoType_t
Enumerator
kFileRead
open file for reading
kFileWrite
open file for writing
kNumFileOpenTypes
Definition at line 14 of file AudioFileIf.h.
    {
        kFileRead   = 0x1L,     //!< open file for reading
        kFileWrite  = 0x2L,     //!< open file for writing
        kNumFileOpenTypes = 2
    };
Constructor & Destructor Documentation
CAudioFileIf() [1/2]
CAudioFileIf::CAudioFileIf () protected
Definition at line 37 of file AudioFileIf.cpp.
                           :
    m_eIoType(kFileRead),
    m_bWithClipping(true),
    m_bIsInitialized(false),
    m_iNumBytesPerSample(2)
{
        this->initDefaults_();
}
References initDefaults_().
~CAudioFileIf()
CAudioFileIf::~CAudioFileIf () protected virtual
Definition at line 46 of file AudioFileIf.cpp.
{
}
CAudioFileIf() [2/2]
CAudioFileIf::CAudioFileIf (const CAudioFileIf & that) private
Member Function Documentation
allocMemory_()
Error_t CAudioFileIf::allocMemory_ () protected virtual
Reimplemented in CAudioFileRaw, and CAudioFileSndLib.
Definition at line 75 of file AudioFileIf.cpp.
{
    freeMemory_ ();
    return Error_t::kNoError;
}
References freeMemory_(), and kNoError.
clip2Range_()
float CAudioFileIf::clip2Range_ (float fSample2Clip, float fMin, float fMax) inline protected
Definition at line 172 of file AudioFileIf.h.
    {
        fSample2Clip = std::min (fSample2Clip, fMax);
        fSample2Clip = std::max (fSample2Clip, fMin);
        return fSample2Clip;
    }
Referenced by CAudioFileRaw::scaleUp(), and CAudioFileSndLib::writeDataIntern_().
closeFile()
virtual Error_t CAudioFileIf::closeFile () pure virtual
close the current file
Returns
Error_t
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by reset(), CChordFromFile::~CChordFromFile(), CFeatureFromFile::~CFeatureFromFile(), CGammaToneFbFromFile::~CGammaToneFbFromFile(), CNoveltyFromFile::~CNoveltyFromFile(), CPitchFromFile::~CPitchFromFile(), and CSpectrogramFromFile::~CSpectrogramFromFile().
convBytes2Frames_()
long long CAudioFileIf::convBytes2Frames_ (long long iNumFrames) protected
Definition at line 147 of file AudioFileIf.cpp.
{
    return iNumBytes/(m_iNumBytesPerSample * getNumChannels_());
}
References getNumChannels_(), and m_iNumBytesPerSample.
Referenced by CAudioFileRaw::getLengthIntern_(), CAudioFileRaw::getPositionIntern_(), CAudioFileRaw::readDataIntern_(), and CAudioFileSndLib::setPositionIntern_().
convFrames2Bytes_()
long long CAudioFileIf::convFrames2Bytes_ (long long iNumFrames) protected
Definition at line 142 of file AudioFileIf.cpp.
{
    return m_iNumBytesPerSample*iNumFrames*getNumChannels_();
}
References getNumChannels_(), and m_iNumBytesPerSample.
Referenced by CAudioFileSndLib::closeFile(), CAudioFileRaw::readDataIntern_(), CAudioFileRaw::setPositionIntern_(), and CAudioFileRaw::writeDataIntern_().
create()
Error_t CAudioFileIf::create (CAudioFileIf *& pCInstance) static
opens a new instance for audio file IO
Parameters
pCInstance
Returns
Error_t
Definition at line 15 of file AudioFileIf.cpp.
{
#ifdef WITH_SNDLIB
    pCInstance   = new CAudioFileSndLib ();
#else
    pCInstance   = new CAudioFileRaw ();
#endif
    if (!pCInstance)
        return Error_t::kMemError;
    return Error_t::kNoError;
}
References kMemError, and kNoError.
Referenced by CChordFromFile::CChordFromFile(), CFeatureFromFile::CFeatureFromFile(), CGammaToneFbFromFile::CGammaToneFbFromFile(), CNoveltyFromFile::CNoveltyFromFile(), CPitchFromFile::CPitchFromFile(), CSpectrogramFromFile::CSpectrogramFromFile(), and CFingerprint::init().
destroy()
Error_t CAudioFileIf::destroy (CAudioFileIf *& pCInstance) static
destroys and audio file IO instance
Parameters
pCInstance
Returns
Error_t
Definition at line 29 of file AudioFileIf.cpp.
{
    delete pCInstance;
    pCInstance  = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by CFingerprint::init(), CChordFromFile::~CChordFromFile(), CFeatureFromFile::~CFeatureFromFile(), CGammaToneFbFromFile::~CGammaToneFbFromFile(), CNoveltyFromFile::~CNoveltyFromFile(), CPitchFromFile::~CPitchFromFile(), and CSpectrogramFromFile::~CSpectrogramFromFile().
freeMemory_()
Error_t CAudioFileIf::freeMemory_ () protected virtual
Reimplemented in CAudioFileRaw, and CAudioFileSndLib.
Definition at line 70 of file AudioFileIf.cpp.
{
    return Error_t::kNoError;
}
References kNoError.
Referenced by allocMemory_(), CAudioFileRaw::freeMemory_(), CAudioFileSndLib::freeMemory_(), and reset().
getFileSpec()
Error_t CAudioFileIf::getFileSpec (FileSpec_t & sFileSpec)
retrieve file specifications
Parameters
sFileSpec
Returns
Error_t
Definition at line 152 of file AudioFileIf.cpp.
{
    memcpy (&sFileSpec, &m_CurrFileSpec, sizeof(FileSpec_t));
    return Error_t::kNoError;
}
References kNoError, and m_CurrFileSpec.
Referenced by CBlockAudioFile::CBlockAudioFile(), CChordFromFile::CChordFromFile(), CFeatureFromFile::CFeatureFromFile(), CGammaToneFbFromFile::CGammaToneFbFromFile(), CNormalizeAudio::CNormalizeAudio(), CNoveltyFromFile::CNoveltyFromFile(), CPitchFromFile::CPitchFromFile(), CSpectrogramFromFile::CSpectrogramFromFile(), CFingerprint::init(), and CAudioFileSndLib::openFile().
getIoType_()
CAudioFileIf::FileIoType_t CAudioFileIf::getIoType_ () const protected
Definition at line 274 of file AudioFileIf.cpp.
{
    return m_eIoType;
}
References m_eIoType.
Referenced by CAudioFileSndLib::closeFile(), CAudioFileSndLib::getLengthIntern_(), and CAudioFileSndLib::openFile().
getLength() [1/2]
Error_t CAudioFileIf::getLength (double & dLengthInSeconds)
get length of file
Parameters
dLengthInSeconds file length in seconds
Returns
Error_t
Definition at line 243 of file AudioFileIf.cpp.
{
    long long iLengthInFrames;
    dLengthInSeconds = -1.;
    Error_t iErr = getLength (iLengthInFrames);
    if (iErr != Error_t::kNoError)
        return iErr;
    dLengthInSeconds = iLengthInFrames * (1./m_CurrFileSpec.fSampleRateInHz);
    return Error_t::kNoError;
}
References CAudioFileIf::FileSpec_t::fSampleRateInHz, getLength(), kNoError, and m_CurrFileSpec.
getLength() [2/2]
Error_t CAudioFileIf::getLength (long long & iLengthInFrames)
get length of file
Parameters
iLengthInFrames file length in frames
Returns
Error_t
Definition at line 189 of file AudioFileIf.cpp.
{
    iLengthInFrames = -1;
    // check file status
    if (!isOpen())
        return Error_t::kUnknownError;
    // check file properties
    if (!isInitialized())
        return Error_t::kNotInitializedError;
    iLengthInFrames = getLengthIntern_();
    return Error_t::kNoError;
}
References getLengthIntern_(), isInitialized(), isOpen(), kNoError, kNotInitializedError, and kUnknownError.
Referenced by CBlockAudioFile::CBlockAudioFile(), getLength(), and CFingerprint::init().
getLengthIntern_()
virtual long long CAudioFileIf::getLengthIntern_ () private pure virtual
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by getLength(), and setPosition().
getNumBitsPerSample_()
int CAudioFileIf::getNumBitsPerSample_ () const inline protected
Definition at line 170 of file AudioFileIf.h.
{return (m_iNumBytesPerSample<<3);}
References m_iNumBytesPerSample.
Referenced by CAudioFileRaw::scaleDown(), CAudioFileRaw::scaleUp(), and CAudioFileSndLib::writeDataIntern_().
getNumBytesPerSample_()
int CAudioFileIf::getNumBytesPerSample_ () const protected
Definition at line 297 of file AudioFileIf.cpp.
{
    return m_iNumBytesPerSample;
}
References m_iNumBytesPerSample.
getNumChannels_()
int CAudioFileIf::getNumChannels_ () const protected
Definition at line 285 of file AudioFileIf.cpp.
{
    return m_CurrFileSpec.iNumChannels;
}
References CAudioFileIf::FileSpec_t::iNumChannels, and m_CurrFileSpec.
Referenced by CAudioFileSndLib::allocMemory_(), convBytes2Frames_(), convFrames2Bytes_(), CAudioFileSndLib::freeMemory_(), CAudioFileSndLib::readDataIntern_(), CAudioFileRaw::readDataIntern_(), CAudioFileRaw::writeDataIntern_(), and CAudioFileSndLib::writeDataIntern_().
getPosition() [1/2]
Error_t CAudioFileIf::getPosition (double & dTimeInS)
get current position in file
Parameters
dTimeInS current time in seconds
Returns
Error_t
Definition at line 221 of file AudioFileIf.cpp.
{
    long long iFrame;
    // check file status
    if (!isOpen())
        return Error_t::kUnknownError;
    // check file properties
    if (!isInitialized())
        return Error_t::kNotInitializedError;
    dTimeInS = -1.;
    Error_t iErr = getPosition(iFrame);
    if (iErr != Error_t::kNoError)
        return iErr;
    dTimeInS = iFrame * (1./m_CurrFileSpec.fSampleRateInHz);
    return Error_t::kNoError;
}
References CAudioFileIf::FileSpec_t::fSampleRateInHz, getPosition(), isInitialized(), isOpen(), kNoError, kNotInitializedError, kUnknownError, and m_CurrFileSpec.
getPosition() [2/2]
Error_t CAudioFileIf::getPosition (long long & iFrame)
get current position in file
Parameters
iFrame current frame
Returns
Error_t
Definition at line 206 of file AudioFileIf.cpp.
{
    // check file status
    if (!isOpen())
        return Error_t::kUnknownError;
    // check file properties
    if (!isInitialized())
        return Error_t::kNotInitializedError;
    iFrame = getPositionIntern_();
    return Error_t::kNoError;
}
References getPositionIntern_(), isInitialized(), isOpen(), kNoError, kNotInitializedError, and kUnknownError.
Referenced by CNormalizeAudio::CNormalizeAudio(), and getPosition().
getPositionIntern_()
virtual long long CAudioFileIf::getPositionIntern_ () private pure virtual
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by getPosition().
initDefaults_()
Error_t CAudioFileIf::initDefaults_ () private virtual
Definition at line 82 of file AudioFileIf.cpp.
{
    m_CurrFileSpec.eBitStreamType  = kFileBitStreamInt16;
    m_CurrFileSpec.eFormat         = kFileFormatRaw;
    m_CurrFileSpec.fSampleRateInHz = 48000;
    m_CurrFileSpec.iNumChannels    = 2;
    setIoType_(kFileRead);
    setInitialized_(false);
    setClippingEnabled ();
    return Error_t::kNoError;
}
References CAudioFileIf::FileSpec_t::eBitStreamType, CAudioFileIf::FileSpec_t::eFormat, CAudioFileIf::FileSpec_t::fSampleRateInHz, CAudioFileIf::FileSpec_t::iNumChannels, kFileBitStreamInt16, kFileFormatRaw, kFileRead, kNoError, m_CurrFileSpec, setClippingEnabled(), setInitialized_(), and setIoType_().
Referenced by CAudioFileIf(), and reset().
isClippingEnabled()
bool CAudioFileIf::isClippingEnabled () inline
check if clipping is enabled
Returns
bool
Definition at line 116 of file AudioFileIf.h.
{return m_bWithClipping;};
References m_bWithClipping.
Referenced by CAudioFileRaw::scaleUp(), and CAudioFileSndLib::writeDataIntern_().
isEof()
virtual bool CAudioFileIf::isEof () pure virtual
check if EOF is true
Returns
bool
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by CNormalizeAudio::CNormalizeAudio(), CBlockAudioFile::getNextBlock(), CFingerprint::init(), and CBlockAudioFile::isEndOfData().
isInitialized()
bool CAudioFileIf::isInitialized () virtual
check is the instance is initialized
Returns
bool
Definition at line 256 of file AudioFileIf.cpp.
{
    return m_bIsInitialized;
}
References m_bIsInitialized.
Referenced by getLength(), getPosition(), readData(), setPosition(), and writeData().
isOpen()
virtual bool CAudioFileIf::isOpen () pure virtual
check if a file is opened
Returns
bool
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by getLength(), getPosition(), readData(), setPosition(), and writeData().
openFile()
virtual Error_t CAudioFileIf::openFile (std::string cAudioFileName, FileIoType_t eIoType, FileSpec_t const * psFileSpec = 0) pure virtual
open a file for reading or writing
Parameters
cAudioFileName
eIoType
psFileSpec
Returns
Error_t
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by CChordFromFile::CChordFromFile(), CFeatureFromFile::CFeatureFromFile(), CGammaToneFbFromFile::CGammaToneFbFromFile(), CNoveltyFromFile::CNoveltyFromFile(), CPitchFromFile::CPitchFromFile(), CSpectrogramFromFile::CSpectrogramFromFile(), and CFingerprint::init().
operator=()
CAudioFileIf & CAudioFileIf::operator= (const CAudioFileIf & c) private
readData()
Error_t CAudioFileIf::readData (float ** ppfAudioData, long long int & iNumFrames) virtual
read data from file and increments read position
Parameters
ppfAudioData [channels][iNumFrames]
iNumFrames number of frames to read (per channel), is updated to the number of frames actually read
Returns
Error_t
Definition at line 97 of file AudioFileIf.cpp.
{
    // check parameters
    if (!ppfAudioData || !ppfAudioData[0] || iLength < 0)
        return Error_t::kFunctionInvalidArgsError;
    // check file status
    if (!isOpen())
        return Error_t::kUnknownError;
    // check file properties
    if (!isInitialized())
        return Error_t::kNotInitializedError;
    // update iLength to the number of frames actually read
    iLength = readDataIntern_ (ppfAudioData, iLength);
    if (iLength < 0)
        return Error_t::kFileAccessError;
    return Error_t::kNoError;
}
References isInitialized(), isOpen(), kFileAccessError, kFunctionInvalidArgsError, kNoError, kNotInitializedError, kUnknownError, and readDataIntern_().
Referenced by CNormalizeAudio::CNormalizeAudio(), CFingerprint::init(), and CBlockAudioFile::readFile2RingBuff().
readDataIntern_()
virtual long long int CAudioFileIf::readDataIntern_ (float ** ppfAudioData, long long int iLength) private pure virtual
Implemented in CAudioFileSndLib, and CAudioFileRaw.
Referenced by readData().
reset()
Error_t CAudioFileIf::reset (bool bFreeMemory = false) virtual
reset instance to initial state
Parameters
bFreeMemory also free the internal memory if true
Returns
Error_t
Definition at line 50 of file AudioFileIf.cpp.
{
    Error_t eErr = closeFile ();
    if (eErr != Error_t::kNoError)
        return eErr;
    if (bFreeMemory)
    {
        eErr = freeMemory_ ();
        if (eErr != Error_t::kNoError)
            return eErr;
    }
    eErr = initDefaults_ ();
    if (eErr != Error_t::kNoError)
        return eErr;
    return eErr;
}
References closeFile(), freeMemory_(), initDefaults_(), and kNoError.
Referenced by CAudioFileRaw::CAudioFileRaw(), CAudioFileSndLib::CAudioFileSndLib(), CAudioFileRaw::openFile(), CAudioFileSndLib::openFile(), CAudioFileRaw::~CAudioFileRaw(), and CAudioFileSndLib::~CAudioFileSndLib().
setClippingEnabled()
Error_t CAudioFileIf::setClippingEnabled (bool bisEnabled = true)
enable clipping to avoid wrap-arounds
Parameters
bisEnabled
Returns
Error_t
Definition at line 159 of file AudioFileIf.cpp.
{
    m_bWithClipping = bIsEnabled;
    return Error_t::kNoError;
}
References kNoError, and m_bWithClipping.
Referenced by initDefaults_().
setFileSpec_()
Error_t CAudioFileIf::setFileSpec_ (const FileSpec_t * pFileSpec) protected
Definition at line 279 of file AudioFileIf.cpp.
{
    memcpy (&m_CurrFileSpec, pFileSpec, sizeof (FileSpec_t));
    return Error_t::kNoError;
}
References kNoError, and m_CurrFileSpec.
Referenced by CAudioFileRaw::openFile(), and CAudioFileSndLib::openFile().
setInitialized_()
Error_t CAudioFileIf::setInitialized_ (bool bInitialized = true) protected
Definition at line 261 of file AudioFileIf.cpp.
{
    m_bIsInitialized    = bInitialized;
    return Error_t::kNoError;
}
References kNoError, and m_bIsInitialized.
Referenced by initDefaults_(), CAudioFileRaw::openFile(), and CAudioFileSndLib::openFile().
setIoType_()
Error_t CAudioFileIf::setIoType_ (FileIoType_t eIoType) protected
Definition at line 268 of file AudioFileIf.cpp.
{
    m_eIoType   = eIoType;
    return Error_t::kNoError;
}
References kNoError, and m_eIoType.
Referenced by initDefaults_(), CAudioFileRaw::openFile(), and CAudioFileSndLib::openFile().
setNumBytesPerSample_()
Error_t CAudioFileIf::setNumBytesPerSample_ (int iNumBytes) protected
Definition at line 290 of file AudioFileIf.cpp.
{
    assert (iNumBytes > 0);
    m_iNumBytesPerSample    = iNumBytes;
    return Error_t::kNoError;
}
References kNoError, and m_iNumBytesPerSample.
Referenced by CAudioFileSndLib::openFile().
setPosition() [1/2]
Error_t CAudioFileIf::setPosition (double dTimeInS = .0)
jump to new position in file
Parameters
dTimeInS time to jump to
Returns
Error_t
Definition at line 182 of file AudioFileIf.cpp.
{
    long long iPosInFrames = CUtil::double2int<long long>(dTimeInS * m_CurrFileSpec.fSampleRateInHz);
    return setPosition (iPosInFrames);
}
References CAudioFileIf::FileSpec_t::fSampleRateInHz, m_CurrFileSpec, and setPosition().
setPosition() [2/2]
Error_t CAudioFileIf::setPosition (long long iFrame = 0) virtual
jump to new position in file
Parameters
iFrame frame to jump to
Returns
Error_t
Definition at line 165 of file AudioFileIf.cpp.
{
    // check file status
    if (!isOpen())
        return Error_t::kUnknownError;
    // check file properties
    if (!isInitialized())
        return Error_t::kNotInitializedError;
    if (iFrame < 0 || iFrame >= getLengthIntern_())
        return Error_t::kFunctionInvalidArgsError;
    return setPositionIntern_(iFrame);
}
References getLengthIntern_(), isInitialized(), isOpen(), kFunctionInvalidArgsError, kNotInitializedError, kUnknownError, and setPositionIntern_().
Referenced by CNormalizeAudio::CNormalizeAudio(), and setPosition().
setPositionIntern_()
virtual Error_t CAudioFileIf::setPositionIntern_ (long long iFrame) private pure virtual
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by setPosition().
writeData()
Error_t CAudioFileIf::writeData (float ** ppfAudioData, long long int iNumFrames) virtual
write data to file and increments write position
Parameters
ppfAudioData [channels][iNumFrames]
iNumFrames number of frames to write (per channel)
Returns
Error_t
Definition at line 119 of file AudioFileIf.cpp.
{
    // check parameters
    if (!ppfAudioData || !ppfAudioData[0] || iLength < 0)
        return Error_t::kFunctionInvalidArgsError;
    // check file status
    if (!isOpen())
        return Error_t::kUnknownError;
    // check file properties
    if (!isInitialized())
        return Error_t::kNotInitializedError;
    // update iLength
    iLength = writeDataIntern_ (ppfAudioData, iLength);
    if (iLength < 0)
        return Error_t::kFileAccessError;
    return Error_t::kNoError;
}
References isInitialized(), isOpen(), kFileAccessError, kFunctionInvalidArgsError, kNoError, kNotInitializedError, kUnknownError, and writeDataIntern_().
writeDataIntern_()
virtual long long int CAudioFileIf::writeDataIntern_ (float ** ppfAudioData, long long int iLength) private pure virtual
Implemented in CAudioFileRaw, and CAudioFileSndLib.
Referenced by writeData().
Member Data Documentation
m_bIsInitialized
bool CAudioFileIf::m_bIsInitialized = false private
true if initialized
Definition at line 196 of file AudioFileIf.h.
Referenced by isInitialized(), and setInitialized_().
m_bWithClipping
bool CAudioFileIf::m_bWithClipping = false private
true if abs(values) > 1 should be clipped
Definition at line 195 of file AudioFileIf.h.
Referenced by isClippingEnabled(), and setClippingEnabled().
m_CurrFileSpec
FileSpec_t CAudioFileIf::m_CurrFileSpec private
current file specifications
Definition at line 192 of file AudioFileIf.h.
Referenced by getFileSpec(), getLength(), getNumChannels_(), getPosition(), initDefaults_(), setFileSpec_(), and setPosition().
m_eIoType
FileIoType_t CAudioFileIf::m_eIoType private
read or write
Definition at line 193 of file AudioFileIf.h.
Referenced by getIoType_(), and setIoType_().
m_iNumBytesPerSample
int CAudioFileIf::m_iNumBytesPerSample = 0 private
number of bytes per sample for the raw pcm IO option without sndlib
Definition at line 197 of file AudioFileIf.h.
Referenced by convBytes2Frames_(), convFrames2Bytes_(), getNumBitsPerSample_(), getNumBytesPerSample_(), and setNumBytesPerSample_().
m_kiDefBlockLength
const long long int CAudioFileIf::m_kiDefBlockLength = 1024 static protected
buffer length for read and write operations
Definition at line 179 of file AudioFileIf.h.
Referenced by CAudioFileRaw::allocMemory_(), CAudioFileSndLib::allocMemory_(), CAudioFileSndLib::readDataIntern_(), CAudioFileRaw::readDataIntern_(), CAudioFileRaw::writeDataIntern_(), and CAudioFileSndLib::writeDataIntern_().
The documentation for this class was generated from the following files:
AudioFileIf.h
AudioFileIf.cpp