ACA: CBlockAudioBuffer Class Reference
CBlockAudioBuffer Class Reference
class for audio blocking from a buffer
Public Member Functions
CBlockAudioBuffer (const float *pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate)
virtual ~CBlockAudioBuffer ()
bool isEndOfData () const override
int getNextBlock (float *pfBlock, float *pfTimeStamp) override
Public Member Functions inherited from CBlockAudioIf
long long getNumBlocks () const
long long getLengthInSamples () const
float getTimeStamp (long long iBlockIdx)
virtual bool isEndOfData () const =0
virtual int getNextBlock (float *pfBlock, float *pfTimeStampInS=0)=0
Private Member Functions
CBlockAudioBuffer (const CBlockAudioBuffer &that)
disallow copy construction
CBlockAudioBuffer & operator= (const CBlockAudioBuffer &c)
Private Attributes
long long m_iCurrIdx = 0
float * m_pfAudioData = 0
Additional Inherited Members
Static Public Member Functions inherited from CBlockAudioIf
static Error_t create (CBlockAudioIf *&pCInstance, CAudioFileIf *pCAudioFile, int iBlockLength, int iHopLength)
static Error_t create (CBlockAudioIf *&pCInstance, const float *pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate)
static Error_t destroy (CBlockAudioIf *&pCInstance)
Protected Member Functions inherited from CBlockAudioIf
CBlockAudioIf ()
virtual ~CBlockAudioIf ()
CBlockAudioIf (const CBlockAudioIf &that)
CBlockAudioIf & operator= (const CBlockAudioIf &c)
Protected Attributes inherited from CBlockAudioIf
long long m_iNumBlocks = 0
number of blocks
long long m_iCurrBlock = 0
current block index
long long m_iAudioLength = 0
length of audio buffer
int m_iBlockLength = 0
block length
int m_iNumChannels = 0
number of channels
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
Detailed Description
class for audio blocking from a buffer
Definition at line 123 of file ToolBlockAudio.cpp.
Constructor & Destructor Documentation
CBlockAudioBuffer() [1/2]
CBlockAudioBuffer::CBlockAudioBuffer (const float * pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate) inline
Definition at line 126 of file ToolBlockAudio.cpp.
                                                                                                                             :
        m_iCurrIdx(0),
        m_pfAudioData(0)
    {
        m_fSampleRate = fSampleRate;
        m_iBlockLength = iBlockLength;
        m_iHopLength = iHopLength;
        m_iAudioLength = iAudioLength;
        // compute number of blocks
        m_iNumBlocks = m_iAudioLength / m_iHopLength + 1;
        // initialize read buffers
        CVector::alloc(m_pfAudioData, m_iAudioLength);
        CVector::copy(m_pfAudioData, pfAudioBuff, m_iAudioLength);
    }
References CVector::alloc(), CVector::copy(), CBlockAudioIf::m_fSampleRate, CBlockAudioIf::m_iAudioLength, CBlockAudioIf::m_iBlockLength, CBlockAudioIf::m_iHopLength, CBlockAudioIf::m_iNumBlocks, and m_pfAudioData.
~CBlockAudioBuffer()
virtual CBlockAudioBuffer::~CBlockAudioBuffer () inline virtual
Definition at line 144 of file ToolBlockAudio.cpp.
    {
        CVector::free(m_pfAudioData);
        m_iAudioLength = 0;
        m_iCurrIdx = 0;
    }
References CVector::free(), CBlockAudioIf::m_iAudioLength, m_iCurrIdx, and m_pfAudioData.
CBlockAudioBuffer() [2/2]
CBlockAudioBuffer::CBlockAudioBuffer (const CBlockAudioBuffer & that) private
disallow copy construction
Member Function Documentation
getNextBlock()
int CBlockAudioBuffer::getNextBlock (float * pfBlock, float * pfTimeStampInS) inline override virtual
retrieves audio data for next block
Parameters
pfBlock (to be written) of length blocklength
pfTimeStampInS (to be written, optional) for current time stamp
Returns
int iNumsamplesRead
Implements CBlockAudioIf.
Definition at line 157 of file ToolBlockAudio.cpp.
    {
        if (!m_pfAudioData)
            return -1;
        int iNumSamplesInBlock = m_iAudioLength - m_iCurrIdx < m_iBlockLength ? static_cast<int>(m_iAudioLength - m_iCurrIdx) : m_iBlockLength;
        CVector::copy(pfBlock, &m_pfAudioData[m_iCurrIdx], iNumSamplesInBlock);
        CVector::setZero(&pfBlock[iNumSamplesInBlock], static_cast<long long>(m_iBlockLength) - iNumSamplesInBlock);
        if (pfTimeStamp)
            *pfTimeStamp = getTimeStamp(m_iCurrBlock);
        m_iCurrIdx += std::min(iNumSamplesInBlock, m_iHopLength);
        m_iCurrBlock++;
        return iNumSamplesInBlock;
    }
References CVector::copy(), CBlockAudioIf::getTimeStamp(), CBlockAudioIf::m_iAudioLength, CBlockAudioIf::m_iBlockLength, CBlockAudioIf::m_iCurrBlock, m_iCurrIdx, CBlockAudioIf::m_iHopLength, m_pfAudioData, and CVector::setZero().
isEndOfData()
bool CBlockAudioBuffer::isEndOfData () const inline override virtual
checks for end of data
Returns
bool true if end of audio data is reached
Implements CBlockAudioIf.
Definition at line 152 of file ToolBlockAudio.cpp.
    {
        return m_iAudioLength == m_iCurrIdx;
    }
References CBlockAudioIf::m_iAudioLength, and m_iCurrIdx.
operator=()
CBlockAudioBuffer & CBlockAudioBuffer::operator= (const CBlockAudioBuffer & c) private
Member Data Documentation
m_iCurrIdx
long long CBlockAudioBuffer::m_iCurrIdx = 0 private
Definition at line 180 of file ToolBlockAudio.cpp.
Referenced by getNextBlock(), isEndOfData(), and ~CBlockAudioBuffer().
m_pfAudioData
float* CBlockAudioBuffer::m_pfAudioData = 0 private
Definition at line 181 of file ToolBlockAudio.cpp.
Referenced by CBlockAudioBuffer(), getNextBlock(), and ~CBlockAudioBuffer().
The documentation for this class was generated from the following file:
ToolBlockAudio.cpp