ACA: CSynthesis Class Reference
CSynthesis Class Reference
class with static functions for signal generation
#include <Synthesis.h>
Static Public Member Functions
template<class T >
static Error_t genSine (T *pfOutBuff, T fFreqInHz, T fSampleRateInHz, long long iLen, T fAmplitude=1.F, T fStartPhaseInRad=0.)
template<class T >
static Error_t genRect (T *pfOutBuff, T fFreqInHz, T fSampleRateInHz, long long iLen, T fAmplitude=1.)
template<class T >
static Error_t genSaw (T *pfOutBuff, T fFreqInHz, T fSampleRateInHz, long long iLen, T fAmplitude=1.)
template<class T >
static Error_t genDc (T *pfOutBuff, long long iLen, T fAmplitude=1.)
template<class T >
static Error_t genNoise (T *pfOutBuff, long long iLen, T fAmplitude=1., bool bOnlyPositive=true)
Detailed Description
class with static functions for signal generation
Definition at line 13 of file Synthesis.h.
Member Function Documentation
genDc()
template<class T > static Error_t CSynthesis::genDc (T * pfOutBuff, long long iLen, T fAmplitude = 1.) inline static
generates a dc signal
Parameters
pfOutBuff output memory buffer (to be written)
iLen number of samples to be generated
fAmplitude amplitude of signal
Returns
Error_t
Definition at line 101 of file Synthesis.h.
    {
        if (!pfOutBuff)
            return Error_t::kFunctionInvalidArgsError;
        for (int i = 0; i < iLen; i++)
        {
            pfOutBuff[i] = fAmplitude;
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
genNoise()
template<class T > static Error_t CSynthesis::genNoise (T * pfOutBuff, long long iLen, T fAmplitude = 1., bool bOnlyPositive = true) inline static
generates a uniform noise
Parameters
pfOutBuff output memory buffer (to be written)
iLen number of samples to be generated
fAmplitude max amplitude of noise
bOnlyPositive create only positive values
Returns
Error_t
Definition at line 122 of file Synthesis.h.
    {
        if (!pfOutBuff)
            return Error_t::kFunctionInvalidArgsError;
        if (bOnlyPositive)
        {
            for (int i = 0; i < iLen; i++)
                pfOutBuff[i] = rand() * fAmplitude / static_cast<float>(RAND_MAX);
        }
        else
        {
            for (int i = 0; i < iLen; i++)
                pfOutBuff[i] = rand() * 2 * fAmplitude / static_cast<float>(RAND_MAX) - 1;
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
Referenced by CKmeans::initClusterMeans_(), CGmm::initState_(), CKmeans::reinitClusterMeans_(), and CVector::setRand().
genRect()
template<class T > static Error_t CSynthesis::genRect (T * pfOutBuff, T fFreqInHz, T fSampleRateInHz, long long iLen, T fAmplitude = 1.) inline static
generates a square wave
Parameters
pfOutBuff output memory buffer (to be written)
fFreqInHz frequency of sinusoidal
fSampleRateInHz sample rate
iLen number of samples to be generated
fAmplitude amplitude of signal
Returns
Error_t
Definition at line 48 of file Synthesis.h.
    {
        if (!pfOutBuff)
            return Error_t::kFunctionInvalidArgsError;
        T fPeriodLength = fSampleRateInHz / fFreqInHz;
        for (int i = 0; i < iLen; i++)
        {
            // this seems super inefficient
            if (i % static_cast<int>(fPeriodLength) < .5 * fPeriodLength)
            {
                pfOutBuff[i] = fAmplitude;
            }
            else
            {
                pfOutBuff[i] = -fAmplitude;
            }
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
genSaw()
template<class T > static Error_t CSynthesis::genSaw (T * pfOutBuff, T fFreqInHz, T fSampleRateInHz, long long iLen, T fAmplitude = 1.) inline static
generates a sawtooth
Parameters
pfOutBuff output memory buffer (to be written)
fFreqInHz frequency of sinusoidal
fSampleRateInHz sample rate
iLen number of samples to be generated
fAmplitude amplitude of signal
Returns
Error_t
Definition at line 79 of file Synthesis.h.
    {
        if (!pfOutBuff)
            return Error_t::kFunctionInvalidArgsError;
        float fIncr = 2 * fAmplitude / fSampleRateInHz * fFreqInHz;
        pfOutBuff[0] = 0;
        for (int i = 1; i < iLen; i++)
        {
            pfOutBuff[i] = fmodf(pfOutBuff[i - 1] + fIncr + fAmplitude, 2 * fAmplitude) - fAmplitude;
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, and kNoError.
genSine()
template<class T > static Error_t CSynthesis::genSine (T * pfOutBuff, T fFreqInHz, T fSampleRateInHz, long long iLen, T fAmplitude = 1.F, T fStartPhaseInRad = 0.) inline static
generates a sinusoidal
Parameters
pfOutBuff output memory buffer (to be written)
fFreqInHz frequency of sinusoidal
fSampleRateInHz sample rate
iLen number of samples to be generated
fAmplitude amplitude of signal
fStartPhaseInRad starting phase in radiants
Returns
Error_t
Definition at line 26 of file Synthesis.h.
    {
        if (!pfOutBuff)
            return Error_t::kFunctionInvalidArgsError;
        for (int i = 0; i < iLen; i++)
        {
            pfOutBuff[i] = fAmplitude * static_cast<T>(sin(2 * M_PI * fFreqInHz * i / fSampleRateInHz + fStartPhaseInRad));
        }
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, kNoError, and M_PI.
The documentation for this class was generated from the following file:
Synthesis.h