ACA: CGammaToneFbFromFile Class Reference
CGammaToneFbFromFile Class Reference
class for computation of the filterbank outputs from a file
Public Member Functions
CGammaToneFbFromFile (const std::string &strAudioFilePath, int iNumBands, float fStartInHz)
virtual ~CGammaToneFbFromFile ()
Public Member Functions inherited from CGammaToneFbIf
Error_t getOutputDimensions (long long &iNumRows, long long &iNumCols) const
float getCenterFreq (int iBandIdx) const
Error_t process (float **ppfOut, const float *pfIn=0, long long iNumSamples=0)
Private Attributes
CAudioFileIf * m_pCAudioFile
Additional Inherited Members
Static Public Member Functions inherited from CGammaToneFbIf
static Error_t create (CGammaToneFbIf *&pCInstance, const std::string &strAudioFilePath, int iNumBands=20, float fStartInHz=100)
static Error_t create (CGammaToneFbIf *&pCInstance, const float *pfAudio, long long iNumSamples, float fSampleRate, int iNumBands=20, float fStartInHz=100)
static Error_t create (CGammaToneFbIf *&pCInstance, float fSampleRate, int iNumBands=20, float fStartInHz=100)
static Error_t destroy (CGammaToneFbIf *&pCInstance)
Protected Member Functions inherited from CGammaToneFbIf
CGammaToneFbIf ()
virtual ~CGammaToneFbIf ()
CGammaToneFbIf (const CGammaToneFbIf &that)
CGammaToneFbIf & operator= (const CGammaToneFbIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ ()
init configuration
float compMidFreqs_ (float fFreqLow, float fFreqHigh, int k) const
compute center frequencies for all bands
Protected Attributes inherited from CGammaToneFbIf
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CGammatone ** m_ppCGammatone = 0
array of filters
const int m_iBlockLength = 4096
internal processing block length
int m_iNumBands = 0
number of gammatone bands
float m_fSampleRate = 0
sample rate
float m_fStartInHz = 0
lowest band center frequency
float * m_pfProcBuff = 0
temporary processing buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of the filterbank outputs from a file
Definition at line 266 of file ToolGammatone.cpp.
Constructor & Destructor Documentation
CGammaToneFbFromFile()
CGammaToneFbFromFile::CGammaToneFbFromFile (const std::string & strAudioFilePath, int iNumBands, float fStartInHz)
Definition at line 284 of file ToolGammatone.cpp.
                                                                                                             :
    m_pCAudioFile(0)
{
    this->reset_();
    m_iNumBands = iNumBands;
    m_fStartInHz = fStartInHz;
    CAudioFileIf::FileSpec_t stFileSpec;
    CAudioFileIf::create(m_pCAudioFile);
    m_pCAudioFile->openFile(strAudioFilePath, CAudioFileIf::kFileRead);
    m_pCAudioFile->getFileSpec(stFileSpec);
    m_fSampleRate = stFileSpec.fSampleRateInHz;
    CBlockAudioIf::create(m_pCBlockAudio, m_pCAudioFile, m_iBlockLength, m_iBlockLength);
    m_pCNormalize = new CNormalizeAudio(m_pCAudioFile);
    init_();
}
References CAudioFileIf::create(), CBlockAudioIf::create(), CAudioFileIf::FileSpec_t::fSampleRateInHz, CGammaToneFbIf::init_(), CAudioFileIf::kFileRead, CGammaToneFbIf::m_fSampleRate, CGammaToneFbIf::m_fStartInHz, CGammaToneFbIf::m_iBlockLength, CGammaToneFbIf::m_iNumBands, m_pCAudioFile, CGammaToneFbIf::m_pCBlockAudio, CGammaToneFbIf::m_pCNormalize, and CGammaToneFbIf::reset_().
~CGammaToneFbFromFile()
virtual CGammaToneFbFromFile::~CGammaToneFbFromFile () inline virtual
Definition at line 271 of file ToolGammatone.cpp.
    {
        delete m_pCNormalize;
        m_pCNormalize = 0;
        m_pCAudioFile->closeFile();
        CAudioFileIf::destroy(m_pCAudioFile);
    };
References CAudioFileIf::destroy(), m_pCAudioFile, and CGammaToneFbIf::m_pCNormalize.
Member Data Documentation
m_pCAudioFile
CAudioFileIf* CGammaToneFbFromFile::m_pCAudioFile private
Definition at line 281 of file ToolGammatone.cpp.
Referenced by CGammaToneFbFromFile(), and ~CGammaToneFbFromFile().
The documentation for this class was generated from the following file:
ToolGammatone.cpp