ACA: CGmmResult Class Reference
CGmmResult Class Reference
class holding the result/details of a Gaussian Mixture Model created with CGmm
#include <ToolGmm.h>
Public Member Functions
CGmmResult ()
virtual ~CGmmResult (void)
CGmmResult (const CGmmResult &that)
int getNumGaussians () const
int getNumDimensions () const
float getMu (int iGaussianIdx, int iFeatureIdx) const
float getPrior (int iGaussianIdx) const
float getSigma (int iGaussianIdx, int iRowIdx, int iColIdx) const
void getSigma (float **ppfSigma, int iGaussianIdx) const
float getProb (const float *pfQuery)
bool isInitialized () const
CGmmResult & operator= (const CGmmResult &that)
Protected Member Functions
Error_t init (int iK, int iNumFeatures)
Error_t reset ()
Error_t setMu (int iGaussianIdx, int iFeatureIdx, float fParamValue)
Error_t setPrior (int iGaussianIdx, float fParamValue)
Error_t setSigma (int iGaussianIdx, float **ppfSigma)
Private Types
enum Sigma_t { kNormal , kInv , kSigma }
Private Attributes
float ** m_ppfMu = 0
means, dim: cluster x feature
float * m_pfPrior = 0
priors, dim: cluster
float *** m_apppfSigma [kSigma] = { 0 }
sigma, cluster x feature x feature
float * m_apfProc [2] = { 0 }
pre-allocated temporary memory buffer
int m_iK = 0
number of Gaussians
int m_iNumFeatures = 0
number of features
bool m_bIsInitialized = false
indicates whether instance is initialized
Friends
class CGmm
Detailed Description
class holding the result/details of a Gaussian Mixture Model created with CGmm
Definition at line 11 of file ToolGmm.h.
Member Enumeration Documentation
Sigma_t
enum CGmmResult::Sigma_t private
Enumerator
kNormal
kInv
kSigma
Definition at line 76 of file ToolGmm.h.
    {
        kNormal,
        kInv,
        kSigma
    };
Constructor & Destructor Documentation
CGmmResult() [1/2]
CGmmResult::CGmmResult () inline
Definition at line 16 of file ToolGmm.h.
{};
Referenced by CGmmResult(), and operator=().
~CGmmResult()
CGmmResult::~CGmmResult (void) virtual
Definition at line 203 of file ToolGmm.cpp.
{ reset(); }
References reset().
CGmmResult() [2/2]
CGmmResult::CGmmResult (const CGmmResult & that)
Definition at line 243 of file ToolGmm.cpp.
                                             :
    m_iK(that.m_iK),
    m_iNumFeatures(that.m_iNumFeatures),
    m_bIsInitialized(that.m_bIsInitialized)
{
    CMatrix::alloc(m_ppfMu, m_iK, m_iNumFeatures);
    CMatrix::copy(m_ppfMu, that.m_ppfMu, m_iK, m_iNumFeatures);
    CVector::alloc(m_pfPrior, m_iK);
    CVector::copy(m_pfPrior, that.m_pfPrior, m_iK);
    for (auto i = 0; i < kSigma; i++)
    {
        CVector::alloc(m_apppfSigma[i], m_iK);
        for (auto k = 0; k < m_iK; k++)
        {
            CMatrix::alloc(m_apppfSigma[i][k], m_iNumFeatures, m_iNumFeatures);
            CMatrix::copy(m_apppfSigma[i][k], that.m_apppfSigma[i][k], m_iNumFeatures, m_iNumFeatures);
        }
    }
}
References CMatrix::alloc(), CVector::alloc(), CGmmResult(), CMatrix::copy(), CVector::copy(), kSigma, m_apppfSigma, m_bIsInitialized, m_iK, m_iNumFeatures, m_pfPrior, and m_ppfMu.
Member Function Documentation
getMu()
float CGmmResult::getMu (int iGaussianIdx, int iFeatureIdx) const
returns mean for one Gaussian and one feature
Parameters
iGaussianIdx index of Gaussian
iFeatureIdx index of feature
Returns
float
Definition at line 275 of file ToolGmm.cpp.
{
    return m_ppfMu[iGaussianIdx][iFeatureIdx];
}
References m_ppfMu.
Referenced by CGmm::checkConverged_(), CGmm::compProbabilities_(), and CGmm::updateState_().
getNumDimensions()
int CGmmResult::getNumDimensions () const
returns the dimensionality of each Gaussian, i.e., the number of features
Returns
int
Definition at line 270 of file ToolGmm.cpp.
{
    return m_iNumFeatures;
}
References m_iNumFeatures.
getNumGaussians()
int CGmmResult::getNumGaussians () const
returns the number of Gaussians in the mixture
Returns
int
Definition at line 265 of file ToolGmm.cpp.
{
    return m_iK;
}
References m_iK.
getPrior()
float CGmmResult::getPrior (int iGaussianIdx) const
returns the prior for one Gaussian
Parameters
iGaussianIdx index of Gaussian
Returns
float
Definition at line 280 of file ToolGmm.cpp.
{
    return m_pfPrior[iGaussianIdx];
}
References m_pfPrior.
Referenced by CGmm::compProbabilities_(), and getProb().
getProb()
float CGmmResult::getProb (const float * pfQuery)
Definition at line 222 of file ToolGmm.cpp.
{
    float fProb = 0;
    for (auto k = 0; k < m_iK; k++)
    {
        float fDet = CMatrix::det(m_apppfSigma[kNormal][k], m_iNumFeatures, m_iNumFeatures);
        if (fDet < 1e-30F)
            continue;
        float fNorm = static_cast<float>(1. / std::sqrt(std::pow(2. * M_PI, m_iNumFeatures) * fDet));
        CVector::copy(m_apfProc[0], pfQuery, m_iNumFeatures);
        CVector::sub_I(m_apfProc[0], m_ppfMu[k], m_iNumFeatures);
        CMatrix::mulMatColvec(m_apfProc[1], m_apppfSigma[kInv][k], m_apfProc[0], m_iNumFeatures, m_iNumFeatures);
        fProb += this->getPrior(k) * fNorm * std::exp(-.5F * CVector::mulScalar(m_apfProc[0], m_apfProc[1], m_iNumFeatures));
    }
    return fProb;
}
References CVector::copy(), CMatrix::det(), getPrior(), kInv, kNormal, m_apfProc, m_apppfSigma, m_iK, m_iNumFeatures, M_PI, m_ppfMu, CMatrix::mulMatColvec(), CVector::mulScalar(), and CVector::sub_I().
getSigma() [1/2]
void CGmmResult::getSigma (float ** ppfSigma, int iGaussianIdx) const
writes sigma matrix for one Gaussian
Parameters
ppfSigma to be written (user allocated, dimensions iNumFeatures X iNumFeatures)
iGaussianIdx index of Gaussian
Definition at line 290 of file ToolGmm.cpp.
{
    CMatrix::copy(ppfSigma, m_apppfSigma[kNormal][iGaussianIdx], m_iNumFeatures, m_iNumFeatures);
    return;
}
References CMatrix::copy(), kNormal, m_apppfSigma, and m_iNumFeatures.
getSigma() [2/2]
float CGmmResult::getSigma (int iGaussianIdx, int iRowIdx, int iColIdx) const
returns entry of sigma matrix for one Gaussian,
Parameters
iGaussianIdx index of Gaussian
iRowIdx row index (< iNumFeatures)
iColIdx col index (< iNumFeatures)
Returns
float
Definition at line 285 of file ToolGmm.cpp.
{
    return m_apppfSigma[kNormal][iGaussianIdx][iRowIdx][iColIdx];
}
References kNormal, and m_apppfSigma.
Referenced by CGmm::compProbabilities_().
init()
Error_t CGmmResult::init (int iK, int iNumFeatures) protected
Definition at line 301 of file ToolGmm.cpp.
{
    reset();
    m_iK = iK;
    m_iNumFeatures = iNumFeatures;
    CMatrix::alloc(m_ppfMu, m_iK, m_iNumFeatures);
    CVector::alloc(m_pfPrior, m_iK);
    for (auto i = 0; i < kSigma; i++)
    {
        CVector::alloc(m_apppfSigma[i], m_iK);
        for (auto k = 0; k < m_iK; k++)
            CMatrix::alloc(m_apppfSigma[i][k], m_iNumFeatures, m_iNumFeatures);
    }
    for (auto i = 0; i < 2; i++)
        CVector::alloc(m_apfProc[i], m_iNumFeatures);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CMatrix::alloc(), CVector::alloc(), kNoError, kSigma, m_apfProc, m_apppfSigma, m_bIsInitialized, m_iK, m_iNumFeatures, m_pfPrior, m_ppfMu, and reset().
Referenced by CGmm::init(), and operator=().
isInitialized()
bool CGmmResult::isInitialized () const
returns initialization state
Returns
bool true if initialized
Definition at line 296 of file ToolGmm.cpp.
{
    return m_bIsInitialized;
}
References m_bIsInitialized.
operator=()
CGmmResult & CGmmResult::operator= (const CGmmResult & that)
assignment operator
Definition at line 205 of file ToolGmm.cpp.
{
    // should be all the same
    if (this->m_iK != that.m_iK || this->m_iNumFeatures != that.m_iNumFeatures || this->m_bIsInitialized != that.m_bIsInitialized)
        this->init(that.m_iK, that.m_iNumFeatures);
    CMatrix::copy(this->m_ppfMu, that.m_ppfMu, this->m_iK, this->m_iNumFeatures);
    CVector::copy(this->m_pfPrior, that.m_pfPrior, this->m_iK);
    for (auto i = 0; i < kSigma; i++)
    {
        for (auto k = 0; k < this->m_iK; k++)
            CMatrix::copy(this->m_apppfSigma[i][k], that.m_apppfSigma[i][k], this->m_iNumFeatures, this->m_iNumFeatures);
    }
    return *this;
}
References CGmmResult(), CMatrix::copy(), CVector::copy(), init(), kSigma, m_apppfSigma, m_bIsInitialized, m_iK, m_iNumFeatures, m_pfPrior, and m_ppfMu.
reset()
Error_t CGmmResult::reset () protected
Definition at line 325 of file ToolGmm.cpp.
{
    m_bIsInitialized = false;
    CMatrix::free(m_ppfMu, m_iK);
    CVector::free(m_pfPrior);
    for (auto i = 0; i < kSigma; i++)
    {
        for (auto k = 0; k < m_iK; k++)
            CMatrix::free(m_apppfSigma[i][k], m_iNumFeatures);
        CVector::free(m_apppfSigma[i]);
    }
    for (auto i = 0; i < 2; i++)
        CVector::free(m_apfProc[i]);
    m_iK = 0;
    m_iNumFeatures = 0;
    return Error_t::kNoError;
}
References CMatrix::free(), CVector::free(), kNoError, kSigma, m_apfProc, m_apppfSigma, m_bIsInitialized, m_iK, m_iNumFeatures, m_pfPrior, and m_ppfMu.
Referenced by init(), and ~CGmmResult().
setMu()
Error_t CGmmResult::setMu (int iGaussianIdx, int iFeatureIdx, float fParamValue) protected
Definition at line 347 of file ToolGmm.cpp.
{
    m_ppfMu[iGaussianIdx][iFeatureIdx] = fParamValue;
    return Error_t::kNoError;
}
References kNoError, and m_ppfMu.
Referenced by CGmm::initState_(), and CGmm::updateState_().
setPrior()
Error_t CGmmResult::setPrior (int iGaussianIdx, float fParamValue) protected
Definition at line 354 of file ToolGmm.cpp.
{
    m_pfPrior[iGaussianIdx] = fParamValue;
    return Error_t::kNoError;
}
References kNoError, and m_pfPrior.
Referenced by CGmm::initState_(), and CGmm::updateState_().
setSigma()
Error_t CGmmResult::setSigma (int iGaussianIdx, float ** ppfSigma) protected
Definition at line 361 of file ToolGmm.cpp.
{
    CMatrix::copy(m_apppfSigma[kNormal][iGaussianIdx], ppfSigma, m_iNumFeatures, m_iNumFeatures);
    CMatrix::copy(m_apppfSigma[kInv][iGaussianIdx], ppfSigma, m_iNumFeatures, m_iNumFeatures);
    CMatrix::inv_I(m_apppfSigma[kInv][iGaussianIdx], m_iNumFeatures, m_iNumFeatures);
    return Error_t::kNoError;
}
References CMatrix::copy(), CMatrix::inv_I(), kInv, kNoError, kNormal, m_apppfSigma, and m_iNumFeatures.
Referenced by CGmm::initState_(), and CGmm::updateState_().
Friends And Related Symbol Documentation
CGmm
friend class CGmm friend
Definition at line 13 of file ToolGmm.h.
References CGmm.
Referenced by CGmm.
Member Data Documentation
m_apfProc
float* CGmmResult::m_apfProc[2] = { 0 } private
pre-allocated temporary memory buffer
Definition at line 86 of file ToolGmm.h.
{ 0 }; //!< pre-allocated temporary memory buffer
Referenced by getProb(), init(), and reset().
m_apppfSigma
float*** CGmmResult::m_apppfSigma[kSigma] = { 0 } private
sigma, cluster x feature x feature
Definition at line 85 of file ToolGmm.h.
{ 0 }; //!< sigma, cluster x feature x feature
Referenced by CGmmResult(), getProb(), getSigma(), getSigma(), init(), operator=(), reset(), and setSigma().
m_bIsInitialized
bool CGmmResult::m_bIsInitialized = false private
indicates whether instance is initialized
Definition at line 91 of file ToolGmm.h.
Referenced by CGmmResult(), init(), isInitialized(), operator=(), and reset().
m_iK
int CGmmResult::m_iK = 0 private
number of Gaussians
Definition at line 88 of file ToolGmm.h.
Referenced by CGmmResult(), getNumGaussians(), getProb(), init(), operator=(), and reset().
m_iNumFeatures
int CGmmResult::m_iNumFeatures = 0 private
number of features
Definition at line 89 of file ToolGmm.h.
Referenced by CGmmResult(), getNumDimensions(), getProb(), getSigma(), init(), operator=(), reset(), and setSigma().
m_pfPrior
float* CGmmResult::m_pfPrior = 0 private
priors, dim: cluster
Definition at line 84 of file ToolGmm.h.
Referenced by CGmmResult(), getPrior(), init(), operator=(), reset(), and setPrior().
m_ppfMu
float** CGmmResult::m_ppfMu = 0 private
means, dim: cluster x feature
Definition at line 83 of file ToolGmm.h.
Referenced by CGmmResult(), getMu(), getProb(), init(), operator=(), reset(), and setMu().
The documentation for this class was generated from the following files:
ToolGmm.h
ToolGmm.cpp