ACA: CPitchIf Class Reference
CPitchIf Class Reference
class for computation of a magnitude Pitch from either a file or a vector
#include <Pitch.h>
Public Types
enum PitchExtractors_t {
kPitchSpectralAcf , kPitchSpectralHps , kPitchTimeAcf , kPitchTimeAmdf ,
kPitchTimeAuditory , kPitchTimeZeroCrossings , kNumPitchExtractors
}
enum to index all Pitch extractorss
Public Member Functions
Error_t getNumBlocks (int &iNumBlocks) const
int getNumBlocks () const
float getTimeStamp (int iBlockIdx) const
Error_t getTimeStamps (float *pfAxisTicks) const
Error_t compF0 (float *pfPitch)
Static Public Member Functions
static Error_t create (CPitchIf *&pCInstance, PitchExtractors_t ePitchIdx, const std::string &strAudioFilePath, int iBlockLength=2048, int iHopLength=1024)
static Error_t create (CPitchIf *&pCInstance, PitchExtractors_t ePitchIdx, const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=2048, int iHopLength=1024)
static Error_t destroy (CPitchIf *&pCInstance)
static std::string getPitchString (PitchExtractors_t ePitchIdx)
static PitchExtractors_t getPitchIdxFromString (std::string sPitchString)
Protected Member Functions
CPitchIf ()
virtual ~CPitchIf ()
CPitchIf (const CPitchIf &that)
CPitchIf & operator= (const CPitchIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (PitchExtractors_t ePitchIdx)
init configuration
bool isPitchExtractorSpectral_ (PitchExtractors_t ePitchIdx)
void computeMagSpectrum_ ()
Protected Attributes
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CPitchFromBlockIf * m_pCPitch = 0
class for extracting f0 from block of data
CPitchAuditory * m_pCAuditory = 0
instace for auditory pitch tracking (the other pitch trackers don't need a time dependent implementation)
CFft * m_pCFft = 0
fft instance
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcBuff1 = 0
temporary buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a magnitude Pitch from either a file or a vector
Definition at line 18 of file Pitch.h.
Member Enumeration Documentation
PitchExtractors_t
enum CPitchIf::PitchExtractors_t
enum to index all Pitch extractorss
Enumerator
kPitchSpectralAcf
kPitchSpectralHps
kPitchTimeAcf
kPitchTimeAmdf
kPitchTimeAuditory
kPitchTimeZeroCrossings
kNumPitchExtractors
Definition at line 23 of file Pitch.h.
    {
        kPitchSpectralAcf,
        kPitchSpectralHps,
        kPitchTimeAcf,
        kPitchTimeAmdf,
        kPitchTimeAuditory,
        kPitchTimeZeroCrossings,
        kNumPitchExtractors
    };
Constructor & Destructor Documentation
CPitchIf() [1/2]
CPitchIf::CPitchIf () protected
Definition at line 89 of file Pitch.cpp.
{
    reset_();
}
References reset_().
~CPitchIf()
CPitchIf::~CPitchIf () inline protected virtual
Definition at line 94 of file Pitch.cpp.
{
    reset_();
}
References reset_().
CPitchIf() [2/2]
CPitchIf::CPitchIf (const CPitchIf & that) protected
Member Function Documentation
compF0()
Error_t CPitchIf::compF0 (float * pfPitch)
performs the Pitch computation for 1 dimensional Pitchs and writes the result
Parameters
pfPitch (user-allocated, to be written, dimensions from CPitchIf::getPitchDimensions)
Returns
Error_t
Definition at line 187 of file Pitch.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!pfPitch)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcBuff1);
    assert(m_pCBlockAudio);
    assert(m_pCNormalize);
    assert(m_pCPitch);
    auto iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        // retrieve the next audio block
        m_pCBlockAudio->getNextBlock(m_pfProcBuff1);
        // normalize if specified
        if (m_pCNormalize)
            m_pCNormalize->normalizeBlock(m_pfProcBuff1, m_iBlockLength);
        if (isPitchExtractorSpectral_(m_pCPitch->getPitchExtractorIdx()))
        {
            // compute magnitude specturm
            assert(m_pfProcBuff2);
            assert(m_pCFft);
            computeMagSpectrum_();
        }
        // extract f0
        pfPitch[n] = m_pCPitch->compF0(m_pfProcBuff1);
    }
    return Error_t::kNoError;
}
References CPitchFromBlockIf::compF0(), computeMagSpectrum_(), CBlockAudioIf::getNextBlock(), CBlockAudioIf::getNumBlocks(), CPitchFromBlockIf::getPitchExtractorIdx(), isPitchExtractorSpectral_(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iBlockLength, m_pCBlockAudio, m_pCFft, m_pCNormalize, m_pCPitch, m_pfProcBuff1, m_pfProcBuff2, and CNormalizeAudio::normalizeBlock().
Referenced by main().
computeMagSpectrum_()
void CPitchIf::computeMagSpectrum_ () protected
Definition at line 261 of file Pitch.cpp.
{
    assert(m_pCFft);
    // compute magnitude spectrum
    m_pCFft->compFft(m_pfProcBuff2, m_pfProcBuff1);
    m_pCFft->getMagnitude(m_pfProcBuff1, m_pfProcBuff2);
    CVector::mulC_I(m_pfProcBuff2, 2.F, m_pCFft->getLength(CFft::kLengthMagnitude));
}
References CFft::compFft(), CFft::getLength(), CFft::getMagnitude(), CFft::kLengthMagnitude, m_pCFft, m_pfProcBuff1, m_pfProcBuff2, and CVector::mulC_I().
Referenced by compF0().
create() [1/2]
Error_t CPitchIf::create (CPitchIf *& pCInstance, PitchExtractors_t ePitchIdx, const float * pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength = 2048, int iHopLength = 1024) static
initializes a Pitch instance from audio data
Parameters
pCInstance pointer to instance to be written
ePitchIdx as defined in PitchExtractors_t
pfAudio complete audio data
iNumSamples length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in samples
iHopLength hop length in samples
Returns
Error_t
Definition at line 114 of file Pitch.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumSamples <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CPitchFromVector(ePitchIdx, pfAudio, iNumSamples, fSampleRate, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, and kNoError.
create() [2/2]
Error_t CPitchIf::create (CPitchIf *& pCInstance, PitchExtractors_t ePitchIdx, const std::string & strAudioFilePath, int iBlockLength = 2048, int iHopLength = 1024) static
initializes a Pitch instance with file reading
Parameters
pCInstance pointer to instance to be written
ePitchIdx as defined in PitchExtractors_t
strAudioFilePath complete path to audio file
iBlockLength FFT block length in samples
iHopLength hop length in samples
Returns
Error_t
Definition at line 99 of file Pitch.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CPitchFromFile(ePitchIdx, strAudioFilePath, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References CUtil::isPowOf2(), kFunctionInvalidArgsError, and kNoError.
Referenced by main().
destroy()
Error_t CPitchIf::destroy (CPitchIf *& pCInstance) static
destroys a Pitch instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 132 of file Pitch.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by main().
getNumBlocks() [1/2]
int CPitchIf::getNumBlocks () const
returns length of vector to be allocated by user
Returns
int
Definition at line 153 of file Pitch.cpp.
{
    assert(m_bIsInitialized);
    assert(m_pCBlockAudio);
    return static_cast<int>(m_pCBlockAudio->getNumBlocks());
}
References CBlockAudioIf::getNumBlocks(), m_bIsInitialized, and m_pCBlockAudio.
Referenced by getNumBlocks().
getNumBlocks() [2/2]
Error_t CPitchIf::getNumBlocks (int & iNumBlocks) const
returns length of vector to be allocated by user
Parameters
iNumBlocks (number of blocks, to be written)
Returns
Error_t
Definition at line 140 of file Pitch.cpp.
{
    if (!m_bIsInitialized)
    {
        iNumBlocks = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumBlocks = this->getNumBlocks();
    return Error_t::kNoError;
}
References getNumBlocks(), kFunctionIllegalCallError, kNoError, and m_bIsInitialized.
Referenced by main().
getPitchIdxFromString()
CPitchIf::PitchExtractors_t CPitchIf::getPitchIdxFromString (std::string sPitchString) static
returns Pitch index from string
Parameters
sPitchString string describing the Pitch
Returns
PitchExtractors_t
Definition at line 242 of file Pitch.cpp.
{
    const std::map<std::string, CPitchIf::PitchExtractors_t> PitchMap
    {
            {"SpectralAcf", kPitchSpectralAcf},
            {"SpectralHps", kPitchSpectralHps},
            {"TimeAcf", kPitchTimeAcf},
            {"TimeAmdf", kPitchTimeAmdf},
            {"TimeAuditory", kPitchTimeAuditory},
            {"TimeZeroCrossings", kPitchTimeZeroCrossings}
    };
    auto search = PitchMap.find(sPitchString);
    if (search != PitchMap.end())
        return PitchMap.at(sPitchString);
    else
        return kNumPitchExtractors;
}
References kNumPitchExtractors, kPitchSpectralAcf, kPitchSpectralHps, kPitchTimeAcf, kPitchTimeAmdf, kPitchTimeAuditory, and kPitchTimeZeroCrossings.
Referenced by main().
getPitchString()
std::string CPitchIf::getPitchString (PitchExtractors_t ePitchIdx) static
returns Pitch name as string
Parameters
ePitchIdx Pitch index
Returns
std::string
Definition at line 226 of file Pitch.cpp.
{
    const std::map<CPitchIf::PitchExtractors_t, std::string> PitchMap
    {
            {kPitchSpectralAcf, "SpectralAcf"},
            {kPitchSpectralHps, "SpectralHps"},
            {kPitchTimeAcf, "TimeAcf"},
            {kPitchTimeAmdf, "TimeAmdf"},
            {kPitchTimeAuditory, "TimeAuditory,"},
            {kPitchTimeZeroCrossings, "TimeZeroCrossings"}
    };
    return PitchMap.at(ePitchIdx);
}
References kPitchSpectralAcf, kPitchSpectralHps, kPitchTimeAcf, kPitchTimeAmdf, kPitchTimeAuditory, and kPitchTimeZeroCrossings.
getTimeStamp()
float CPitchIf::getTimeStamp (int iBlockIdx) const
returns time stamps
Parameters
iBlockIdx index of block
Returns
float time stamp
Definition at line 161 of file Pitch.cpp.
{
    return m_pCBlockAudio->getTimeStamp(iBlockIdx);
}
References CBlockAudioIf::getTimeStamp(), and m_pCBlockAudio.
Referenced by main().
getTimeStamps()
Error_t CPitchIf::getTimeStamps (float * pfAxisTicks) const
returns time stamps
Parameters
pfAxisTicks (user- allocated, to be written) length iNumBlocks
Returns
Error_t
Definition at line 166 of file Pitch.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
        pfAxisTicks[n] = m_pCBlockAudio->getTimeStamp(n);
    return Error_t::kNoError;
}
References CBlockAudioIf::getNumBlocks(), CBlockAudioIf::getTimeStamp(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, and m_pCBlockAudio.
init_()
Error_t CPitchIf::init_ (PitchExtractors_t ePitchIdx) protected
init configuration
Definition at line 296 of file Pitch.cpp.
{
    if (isPitchExtractorSpectral_(ePitchIdx))
    {
        // initialize FFT and fft  buffer
        m_pCFft = new CFft();
        m_pCFft->init(m_iBlockLength);
        // allocate processing memory
        CVector::alloc(m_pfProcBuff1, m_pCFft->getLength(CFft::kLengthFft));
        CVector::alloc(m_pfProcBuff2, m_pCFft->getLength(CFft::kLengthFft));
        CPitchFromBlockIf::create(m_pCPitch, ePitchIdx, m_pCFft->getLength(CFft::kLengthMagnitude), m_fSampleRate);
    }
    else
    {
        // allocate processing memory
        CVector::alloc(m_pfProcBuff1, m_iBlockLength);
        CPitchFromBlockIf::create(m_pCPitch, ePitchIdx, m_iBlockLength, m_fSampleRate);
    }
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CPitchFromBlockIf::create(), CFft::getLength(), CFft::init(), isPitchExtractorSpectral_(), CFft::kLengthFft, CFft::kLengthMagnitude, kNoError, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_pCFft, m_pCPitch, m_pfProcBuff1, and m_pfProcBuff2.
Referenced by CPitchFromFile::CPitchFromFile(), and CPitchFromVector::CPitchFromVector().
isPitchExtractorSpectral_()
bool CPitchIf::isPitchExtractorSpectral_ (PitchExtractors_t ePitchIdx) protected
Definition at line 319 of file Pitch.cpp.
{
    return (ePitchIdx <= kPitchSpectralHps) ? true : false;
}
References kPitchSpectralHps, and true.
Referenced by compF0(), and init_().
operator=()
CPitchIf & CPitchIf::operator= (const CPitchIf & c) protected
reset_()
Error_t CPitchIf::reset_ () protected
reset configuration
Definition at line 273 of file Pitch.cpp.
{
    CVector::free(m_pfProcBuff1);
    CVector::free(m_pfProcBuff2);
    delete m_pCFft;
    m_pCFft = 0;
    delete m_pCNormalize;
    m_pCNormalize = 0;
    CBlockAudioIf::destroy(m_pCBlockAudio);
    CPitchFromBlockIf::destroy(m_pCPitch);
    m_iBlockLength = 0;
    m_iHopLength = 0;
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CBlockAudioIf::destroy(), CPitchFromBlockIf::destroy(), CVector::free(), kNoError, m_bIsInitialized, m_iBlockLength, m_iHopLength, m_pCBlockAudio, m_pCFft, m_pCNormalize, m_pCPitch, m_pfProcBuff1, and m_pfProcBuff2.
Referenced by CPitchFromFile::CPitchFromFile(), CPitchIf(), and ~CPitchIf().
Member Data Documentation
m_bIsInitialized
bool CPitchIf::m_bIsInitialized = false protected
true if initialized
Definition at line 134 of file Pitch.h.
Referenced by compF0(), getNumBlocks(), getTimeStamps(), init_(), and reset_().
m_fSampleRate
float CPitchIf::m_fSampleRate = 0 protected
sample rate
Definition at line 129 of file Pitch.h.
Referenced by CPitchFromFile::CPitchFromFile(), CPitchFromVector::CPitchFromVector(), getTimeStamps(), and init_().
m_iBlockLength
int CPitchIf::m_iBlockLength = 0 protected
fft length
Definition at line 126 of file Pitch.h.
Referenced by compF0(), CPitchFromFile::CPitchFromFile(), CPitchFromVector::CPitchFromVector(), getTimeStamps(), init_(), and reset_().
m_iHopLength
int CPitchIf::m_iHopLength = 0 protected
hop length
Definition at line 127 of file Pitch.h.
Referenced by CPitchFromFile::CPitchFromFile(), CPitchFromVector::CPitchFromVector(), getTimeStamps(), and reset_().
m_pCAuditory
CPitchAuditory* CPitchIf::m_pCAuditory = 0 protected
instace for auditory pitch tracking (the other pitch trackers don't need a time dependent implementation)
Definition at line 122 of file Pitch.h.
m_pCBlockAudio
CBlockAudioIf* CPitchIf::m_pCBlockAudio = 0 protected
instantiate for blocking time domain signal
Definition at line 118 of file Pitch.h.
Referenced by compF0(), CPitchFromFile::CPitchFromFile(), CPitchFromVector::CPitchFromVector(), getNumBlocks(), getTimeStamp(), getTimeStamps(), and reset_().
m_pCFft
CFft* CPitchIf::m_pCFft = 0 protected
fft instance
Definition at line 124 of file Pitch.h.
Referenced by compF0(), computeMagSpectrum_(), init_(), and reset_().
m_pCNormalize
CNormalizeAudio* CPitchIf::m_pCNormalize = 0 protected
instantiate if audio file normalization is wanted
Definition at line 116 of file Pitch.h.
Referenced by compF0(), CPitchFromFile::CPitchFromFile(), CPitchFromVector::CPitchFromVector(), reset_(), and CPitchFromFile::~CPitchFromFile().
m_pCPitch
CPitchFromBlockIf* CPitchIf::m_pCPitch = 0 protected
class for extracting f0 from block of data
Definition at line 120 of file Pitch.h.
Referenced by compF0(), init_(), and reset_().
m_pfProcBuff1
float* CPitchIf::m_pfProcBuff1 = 0 protected
temporary buffer
Definition at line 132 of file Pitch.h.
Referenced by compF0(), computeMagSpectrum_(), init_(), reset_(), and CPitchFromFile::~CPitchFromFile().
m_pfProcBuff2
float* CPitchIf::m_pfProcBuff2 = 0 protected
temporary buffer for current spectrum
Definition at line 131 of file Pitch.h.
Referenced by compF0(), computeMagSpectrum_(), init_(), and reset_().
The documentation for this class was generated from the following files:
Pitch.h
Pitch.cpp