ACA: CSubFingerprint Class Reference
CSubFingerprint Class Reference
class for computation of a subfingerprint from a magnitude spectrum, 256 subfingerprints comprise one fingerprint
#include <SubFingerprint.h>
Public Member Functions
CSubFingerprint (int iMagSpecLength=1025, float fSampleRate=5000.F)
virtual ~CSubFingerprint ()
uint32_t compSubFingerprint (const float *pfMagSpec)
Error_t reset ()
Protected Types
enum Block_t { kPrev , kCurr , kTmp , kNumProcBuffs }
Protected Member Functions
CSubFingerprint (const CSubFingerprint &that)
CSubFingerprint & operator= (const CSubFingerprint &c)
void genBands_ ()
Protected Attributes
int m_iMagSpecLength = 1025
block length
const int m_iNumBands = 32
number of bands
float m_fSampleRate = 5000
sample rate
float ** m_ppfH = 0
transformation matrix bin to band
float * m_apfProcBuff [kNumProcBuffs] = { 0 }
temporary processing buffers
Detailed Description
class for computation of a subfingerprint from a magnitude spectrum, 256 subfingerprints comprise one fingerprint
Definition at line 8 of file SubFingerprint.h.
Member Enumeration Documentation
Block_t
enum CSubFingerprint::Block_t protected
Enumerator
kPrev
kCurr
kTmp
kNumProcBuffs
Definition at line 32 of file SubFingerprint.h.
    {
        kPrev,
        kCurr,
        kTmp,
        kNumProcBuffs
    };
Constructor & Destructor Documentation
CSubFingerprint() [1/2]
CSubFingerprint::CSubFingerprint (int iMagSpecLength = 1025, float fSampleRate = 5000.F) explicit
Definition at line 11 of file SubFingerprint.cpp.
                                                                      :
    m_iMagSpecLength(iMagSpecLength),
    m_fSampleRate(fSampleRate)
{
    assert(iMagSpecLength > 0);
    assert(fSampleRate > 4000);
    // alloc transfer function memory
    CMatrix::alloc(m_ppfH, m_iNumBands + 1, m_iMagSpecLength);
    for (auto k = 0; k < kNumProcBuffs; k++)
        CVector::alloc(m_apfProcBuff[k], m_iNumBands + static_cast<long long>(1));
    genBands_();
}
References CMatrix::alloc(), CVector::alloc(), genBands_(), kNumProcBuffs, m_apfProcBuff, m_fSampleRate, m_iMagSpecLength, m_iNumBands, and m_ppfH.
Referenced by CSubFingerprint(), and operator=().
~CSubFingerprint()
CSubFingerprint::~CSubFingerprint () virtual
Definition at line 27 of file SubFingerprint.cpp.
{
    for (auto k = 0; k < kNumProcBuffs; k++)
        CVector::free(m_apfProcBuff[k]);
    CMatrix::free(m_ppfH, m_iNumBands + 1);
}
References CMatrix::free(), CVector::free(), kNumProcBuffs, m_apfProcBuff, m_iNumBands, and m_ppfH.
CSubFingerprint() [2/2]
CSubFingerprint::CSubFingerprint (const CSubFingerprint & that) protected
References CSubFingerprint().
Member Function Documentation
compSubFingerprint()
uint32_t CSubFingerprint::compSubFingerprint (const float * pfMagSpec)
performs the SubFingerprint computation
Parameters
pfMagSpec input data of length iDataLength
Returns
Error_t
Definition at line 35 of file SubFingerprint.cpp.
{
    assert(pfMagSpec);
    CVector::setZero(m_apfProcBuff[kCurr], m_iNumBands + static_cast<long long>(1));
    for (auto p = 0; p < m_iNumBands + 1; p++)
    {
        // we could do this nicer with CVector::mulScalar if we allocated memory; or, we could use the bin boundaries for start and end of loop. or both.
        for (auto k = 0; k < m_iMagSpecLength; k++)
            m_apfProcBuff[kCurr][p] += m_ppfH[p][k] * (pfMagSpec[k] * pfMagSpec[k]);
    }
    // compute diff in freq domain
    for (auto p = 0; p < m_iNumBands; p++)
    {
        m_apfProcBuff[kCurr][p] = m_apfProcBuff[kCurr][p + 1] - m_apfProcBuff[kCurr][p];
        m_apfProcBuff[kTmp][p] = m_apfProcBuff[kCurr][p] - m_apfProcBuff[kPrev][p];
    }
    // update for next block
    CUtil::swap(m_apfProcBuff[kCurr], m_apfProcBuff[kPrev]);
    return CConversion::convertFloat2Word(m_apfProcBuff[kTmp]);
}
References CConversion::convertFloat2Word(), kCurr, kPrev, kTmp, m_apfProcBuff, m_iMagSpecLength, m_iNumBands, m_ppfH, CVector::setZero(), and CUtil::swap().
genBands_()
void CSubFingerprint::genBands_ () protected
< extract 33 bands
Definition at line 72 of file SubFingerprint.cpp.
{
    enum FreqBounds_t
    {
        kLow,
        kHigh,
        kNumBounds
    };
    const float afFreqBounds[kNumBounds] = { 300.F, 2000.F };
    int iNumBands = m_iNumBands + 1;  //!< extract 33 bands
    int iFftLength = 2 * (m_iMagSpecLength - 1);
    float fFreqScale = std::log(afFreqBounds[kHigh] / afFreqBounds[kLow]);
    float fLowBound = afFreqBounds[kLow];
    CMatrix::setZero(m_ppfH, m_iNumBands + 1, m_iMagSpecLength);
    for (auto p = 0; p < m_iNumBands; p++)
    {
        float fHighBound = afFreqBounds[kLow] * std::exp((p + 1) * fFreqScale / iNumBands);
        // get indices from freqs
        const int aiBoundIdx[kNumBounds] = { static_cast<int>(CConversion::convertFreq2Bin(fLowBound, iFftLength, m_fSampleRate)) + 1,
            static_cast<int>(CConversion::convertFreq2Bin(fHighBound, iFftLength, m_fSampleRate)) };
        CVector::setValue(&m_ppfH[p][aiBoundIdx[kLow]], 1.F, aiBoundIdx[kHigh] + static_cast<long long>(1) - aiBoundIdx[kLow]);
        // proceed to next band
        fLowBound = fHighBound;
    }
}
References CConversion::convertFreq2Bin(), m_fSampleRate, m_iMagSpecLength, m_iNumBands, m_ppfH, CVector::setValue(), and CMatrix::setZero().
Referenced by CSubFingerprint().
operator=()
CSubFingerprint & CSubFingerprint::operator= (const CSubFingerprint & c) protected
References CSubFingerprint().
reset()
Error_t CSubFingerprint::reset ()
performs the SubFingerprint computation
Parameters
pfSubFingerprint feature result (user-allocated, to be written, length from CSubFingerprint::getFeatureDimensions)
pfMagSpec input data of length iDataLength
Returns
Error_t
Definition at line 61 of file SubFingerprint.cpp.
{
    if (!m_apfProcBuff[kCurr] || !m_apfProcBuff[kTmp] || !m_apfProcBuff[kPrev])
        return Error_t::kMemError;
    for (auto k = 0; k < kNumProcBuffs; k++)
        CVector::setZero(m_apfProcBuff[k], m_iNumBands + static_cast<long long>(1));
    return Error_t::kNoError;
}
References kCurr, kMemError, kNoError, kNumProcBuffs, kPrev, kTmp, m_apfProcBuff, m_iNumBands, and CVector::setZero().
Member Data Documentation
m_apfProcBuff
float* CSubFingerprint::m_apfProcBuff[kNumProcBuffs] = { 0 } protected
temporary processing buffers
Definition at line 51 of file SubFingerprint.h.
{ 0 }; //!< temporary processing buffers
Referenced by compSubFingerprint(), CSubFingerprint(), reset(), and ~CSubFingerprint().
m_fSampleRate
float CSubFingerprint::m_fSampleRate = 5000 protected
sample rate
Definition at line 47 of file SubFingerprint.h.
Referenced by CSubFingerprint(), and genBands_().
m_iMagSpecLength
int CSubFingerprint::m_iMagSpecLength = 1025 protected
block length
Definition at line 43 of file SubFingerprint.h.
Referenced by compSubFingerprint(), CSubFingerprint(), and genBands_().
m_iNumBands
const int CSubFingerprint::m_iNumBands = 32 protected
number of bands
Definition at line 45 of file SubFingerprint.h.
Referenced by compSubFingerprint(), CSubFingerprint(), genBands_(), reset(), and ~CSubFingerprint().
m_ppfH
float** CSubFingerprint::m_ppfH = 0 protected
transformation matrix bin to band
Definition at line 49 of file SubFingerprint.h.
Referenced by compSubFingerprint(), CSubFingerprint(), genBands_(), and ~CSubFingerprint().
The documentation for this class was generated from the following files:
SubFingerprint.h
SubFingerprint.cpp