ACA: CSpectrogramIf Class Reference
CSpectrogramIf Class Reference
class for computation of a magnitude spectrogram from either a file or a vector
#include <Spectrogram.h>
Classes
struct MelSpectrogramConfig_t
structure holding configuration specifics for the mel spectrogram computation
Public Types
enum AxisLabel_t { kFrequencyInHz , kTimeInS , kNumAxisLabels }
Public Member Functions
Error_t getSpectrogramDimensions (int &iNumRows, int &iNumCols) const
Error_t getSpectrogramAxisVectors (float *pfAxisTicks, enum AxisLabel_t eAxisLabel) const
Error_t compSpectrogram (float **ppfSpectrogram)
Error_t getMelSpectrogramDimensions (int &iNumRows, int &iNumCols, const MelSpectrogramConfig_t *pMelSpecConfig) const
Error_t getMelSpectrogramAxisVectors (float *pfAxisTicks, enum AxisLabel_t eAxisLabel, const MelSpectrogramConfig_t *pMelSpecConfig)
Error_t compMelSpectrogram (float **ppfMelSpectrogram, const MelSpectrogramConfig_t *pMelSpecConfig)
Static Public Member Functions
static Error_t create (CSpectrogramIf *&pCInstance, const std::string &strAudioFilePath, int iBlockLength=2048, int iHopLength=1024, bool bNormalize=true, float *pfWindow=0)
static Error_t create (CSpectrogramIf *&pCInstance, const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=2048, int iHopLength=1024, bool bNormalize=true, float *pfWindow=0)
static Error_t destroy (CSpectrogramIf *&pCInstance)
Protected Member Functions
CSpectrogramIf ()
virtual ~CSpectrogramIf ()
CSpectrogramIf (const CSpectrogramIf &that)
CSpectrogramIf & operator= (const CSpectrogramIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (float *pfWindow)
init configuration
void computeMagSpectrum_ (int iLength)
Error_t generateMelFb_ (const MelSpectrogramConfig_t *pMelSpecConfig)
void destroyMelFb_ (const MelSpectrogramConfig_t *pMelSpecConfig)
Protected Attributes
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CFft * m_pCFft = 0
fft instance
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfSpectrum = 0
temporary buffer for current spectrum
float * m_pfProcBuff = 0
temporary buffer
float ** m_ppfHMel = 0
Mel filterbank.
float * m_pffcMel = 0
Mel center frequencies.
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a magnitude spectrogram from either a file or a vector
Definition at line 16 of file Spectrogram.h.
Member Enumeration Documentation
AxisLabel_t
enum CSpectrogramIf::AxisLabel_t
Enumerator
kFrequencyInHz
kTimeInS
kNumAxisLabels
Definition at line 19 of file Spectrogram.h.
    {
        kFrequencyInHz,
        kTimeInS,
        kNumAxisLabels
    };
Constructor & Destructor Documentation
CSpectrogramIf() [1/2]
CSpectrogramIf::CSpectrogramIf () protected
Definition at line 90 of file Spectrogram.cpp.
{
    reset_();
}
References reset_().
~CSpectrogramIf()
CSpectrogramIf::~CSpectrogramIf () inline protected virtual
Definition at line 95 of file Spectrogram.cpp.
{
    reset_();
}
References reset_().
CSpectrogramIf() [2/2]
CSpectrogramIf::CSpectrogramIf (const CSpectrogramIf & that) protected
Member Function Documentation
compMelSpectrogram()
Error_t CSpectrogramIf::compMelSpectrogram (float ** ppfMelSpectrogram, const MelSpectrogramConfig_t * pMelSpecConfig)
performs the Spectrogram computation
Parameters
ppfMelSpectrogram (user-allocated, to be written, dimensions from CSpectrogramIf::getSpectrogramDimensions)
pMelSpecConfig parametrization of the mel spectrogram
Returns
Error_t
Definition at line 333 of file Spectrogram.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!pMelSpecConfig)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfMelSpectrogram)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfMelSpectrogram[0])
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcBuff);
    assert(m_pfSpectrum);
    assert(m_pCFft);
    // initialize mel filterbank
    generateMelFb_(pMelSpecConfig);
    assert(m_ppfHMel);
    long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        auto iLength = m_pCFft->getLength(CFft::kLengthMagnitude);
        computeMagSpectrum_(iLength);
        // copy to output buffer
        for (auto k = 0; k < pMelSpecConfig->iNumMelBins; k++)
        {
            assert(m_ppfHMel[k]);
            ppfMelSpectrogram[k][n] = CVector::mulScalar(m_ppfHMel[k], m_pfSpectrum, iLength);
        }
        if (pMelSpecConfig->bIsLogarithmic)
        {
            // convert amplitude to level(dB)
            for (auto k = 0; k < pMelSpecConfig->iNumMelBins; k++)
                ppfMelSpectrogram[k][n] = 20.F * std::log10(ppfMelSpectrogram[k][n] + 1e-12F);
        }
    }
    destroyMelFb_(pMelSpecConfig);
    return Error_t::kNoError;
}
References CSpectrogramIf::MelSpectrogramConfig_t::bIsLogarithmic, computeMagSpectrum_(), destroyMelFb_(), generateMelFb_(), CFft::getLength(), CBlockAudioIf::getNumBlocks(), CSpectrogramIf::MelSpectrogramConfig_t::iNumMelBins, CFft::kLengthMagnitude, m_bIsInitialized, m_pCBlockAudio, m_pCFft, m_pfProcBuff, m_pfSpectrum, m_ppfHMel, and CVector::mulScalar().
Referenced by main().
compSpectrogram()
Error_t CSpectrogramIf::compSpectrogram (float ** ppfSpectrogram)
performs the Spectrogram computation
Parameters
ppfSpectrogram (user-allocated, to be written, dimensions from CSpectrogramIf::getSpectrogramDimensions)
Returns
Error_t
Definition at line 188 of file Spectrogram.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!ppfSpectrogram)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfSpectrogram[0])
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcBuff);
    assert(m_pfSpectrum);
    assert(m_pCFft);
    long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        auto iLength = m_pCFft->getLength(CFft::kLengthMagnitude);
        computeMagSpectrum_(iLength);
        // copy to output buffer
        for (auto k = 0; k < iLength; k++)
            ppfSpectrogram[k][n] = m_pfSpectrum[k];
    }
    return Error_t::kNoError;
}
References computeMagSpectrum_(), CFft::getLength(), CBlockAudioIf::getNumBlocks(), CFft::kLengthMagnitude, m_bIsInitialized, m_pCBlockAudio, m_pCFft, m_pfProcBuff, and m_pfSpectrum.
Referenced by main().
computeMagSpectrum_()
void CSpectrogramIf::computeMagSpectrum_ (int iLength) protected
Definition at line 217 of file Spectrogram.cpp.
{
    // retrieve the next audio block
    m_pCBlockAudio->getNextBlock(m_pfProcBuff);
    // normalize if specified
    if (m_pCNormalize)
        m_pCNormalize->normalizeBlock(m_pfProcBuff, m_iBlockLength);
    // compute magnitude spectrum
    m_pCFft->compFft(m_pfSpectrum, m_pfProcBuff);
    m_pCFft->getMagnitude(m_pfSpectrum, m_pfSpectrum);
    CVector::mulC_I(m_pfSpectrum, 2.F, iLength);
}
References CFft::compFft(), CFft::getMagnitude(), CBlockAudioIf::getNextBlock(), m_iBlockLength, m_pCBlockAudio, m_pCFft, m_pCNormalize, m_pfProcBuff, m_pfSpectrum, CVector::mulC_I(), and CNormalizeAudio::normalizeBlock().
Referenced by compMelSpectrogram(), and compSpectrogram().
create() [1/2]
Error_t CSpectrogramIf::create (CSpectrogramIf *& pCInstance, const float * pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength = 2048, int iHopLength = 1024, bool bNormalize = true, float * pfWindow = 0) static
initializes a Spectrogram instance from audio data
Parameters
pCInstance pointer to instance to be written
pfAudio complete audio data
iNumSamples length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in samples
iHopLength hop length in samples
bNormalize flag if input audio should be normalized
pfWindow window function of length iBlockLength (optional, default will be von-Hann if 0)
Returns
Error_t
Definition at line 115 of file Spectrogram.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumSamples <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CSpectrogramFromVector(pfAudio, iNumSamples, fSampleRate, iBlockLength, iHopLength, bNormalize, pfWindow);
    return Error_t::kNoError;
}
References CUtil::isPowOf2().
create() [2/2]
Error_t CSpectrogramIf::create (CSpectrogramIf *& pCInstance, const std::string & strAudioFilePath, int iBlockLength = 2048, int iHopLength = 1024, bool bNormalize = true, float * pfWindow = 0) static
initializes a Spectrogram instance with file reading
Parameters
pCInstance pointer to instance to be written
strAudioFilePath complete path to audio file
iBlockLength FFT block length in samples
iHopLength hop length in samples
bNormalize flag if input audio should be normalized
pfWindow window function of length iBlockLength (optional, default will be von-Hann if 0)
Returns
Error_t
Definition at line 100 of file Spectrogram.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CSpectrogramFromFile(strAudioFilePath, iBlockLength, iHopLength, bNormalize, pfWindow);
    return Error_t::kNoError;
}
References CUtil::isPowOf2().
Referenced by main().
destroy()
Error_t CSpectrogramIf::destroy (CSpectrogramIf *& pCInstance) static
destroys a Spectrogram instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 133 of file Spectrogram.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
Referenced by main().
destroyMelFb_()
void CSpectrogramIf::destroyMelFb_ (const MelSpectrogramConfig_t * pMelSpecConfig) protected
Definition at line 233 of file Spectrogram.cpp.
{
    CMatrix::free(m_ppfHMel, pMelSpecConfig->iNumMelBins);
}
References CMatrix::free(), CSpectrogramIf::MelSpectrogramConfig_t::iNumMelBins, and m_ppfHMel.
Referenced by compMelSpectrogram(), and getMelSpectrogramAxisVectors().
generateMelFb_()
Error_t CSpectrogramIf::generateMelFb_ (const MelSpectrogramConfig_t * pMelSpecConfig) protected
< normalization
Definition at line 380 of file Spectrogram.cpp.
{
    assert(pMelSpecConfig);
    int iMagLength = m_pCFft->getLength(CFft::kLengthMagnitude);
    // configuration check
    if (pMelSpecConfig->fMinFreqInHz < 0)
        return Error_t::kFunctionInvalidArgsError;
    if (pMelSpecConfig->fMaxFreqInHz > m_fSampleRate / 2)
        return Error_t::kFunctionInvalidArgsError;
    if (pMelSpecConfig->iNumMelBins <= 0 || pMelSpecConfig->iNumMelBins > iMagLength)
        return Error_t::kFunctionInvalidArgsError;
    // allocate filter matrix and frequency matrix
    CVector::alloc(m_pffcMel, static_cast<long long>(pMelSpecConfig->iNumMelBins) + 2); // +2 for lower and upper bound
    CMatrix::alloc(m_ppfHMel, pMelSpecConfig->iNumMelBins, iMagLength);
    // compute center band frequencies
    m_pffcMel[0] = CConversion::convertFreq2Mel(pMelSpecConfig->fMinFreqInHz);
    m_pffcMel[pMelSpecConfig->iNumMelBins + 1] = CConversion::convertFreq2Mel(pMelSpecConfig->fMaxFreqInHz);
    float fMelInc = (m_pffcMel[pMelSpecConfig->iNumMelBins + 1] - m_pffcMel[0]) / (pMelSpecConfig->iNumMelBins + 1);
    for (auto k = 1; k < pMelSpecConfig->iNumMelBins + 1; k++)
        m_pffcMel[k] = m_pffcMel[k - 1] + fMelInc;
    for (auto k = 0; k < pMelSpecConfig->iNumMelBins + 2; k++)
        m_pffcMel[k] = CConversion::convertMel2Freq(m_pffcMel[k]);
    float *pf_l = &m_pffcMel[0],
        *pf_c = &m_pffcMel[1],
        *pf_u = &m_pffcMel[2];
    for (auto m = 0; m < pMelSpecConfig->iNumMelBins; m++)
    {
        float fFilterMax = 2.F / (pf_u[m] - pf_l[m]); //!< normalization
        int iLowBin = 1 + static_cast<int>(m_pCFft->freq2bin(pf_l[m], m_fSampleRate));
        int iCenterBin = 1 + static_cast<int>(m_pCFft->freq2bin(pf_c[m], m_fSampleRate));
        int iUpBin = 1 + static_cast<int>(m_pCFft->freq2bin(pf_u[m], m_fSampleRate));
        for (auto k = iLowBin; k < iCenterBin; k++)
            m_ppfHMel[m][k] = fFilterMax * (CConversion::convertBin2Freq(static_cast<float>(k), (iMagLength - 1) * 2, m_fSampleRate) - pf_l[m]) / (pf_c[m] - pf_l[m]);
        for (auto k = iCenterBin; k < iUpBin; k++)
            m_ppfHMel[m][k] = fFilterMax * (pf_u[m] - CConversion::convertBin2Freq(static_cast<float>(k), (iMagLength - 1) * 2, m_fSampleRate)) / (pf_u[m] - pf_c[m]);
    }
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), CConversion::convertBin2Freq(), CConversion::convertFreq2Mel(), CConversion::convertMel2Freq(), CSpectrogramIf::MelSpectrogramConfig_t::fMaxFreqInHz, CSpectrogramIf::MelSpectrogramConfig_t::fMinFreqInHz, CFft::freq2bin(), CFft::getLength(), CSpectrogramIf::MelSpectrogramConfig_t::iNumMelBins, CFft::kLengthMagnitude, m_fSampleRate, m_pCFft, m_pffcMel, and m_ppfHMel.
Referenced by compMelSpectrogram(), and getMelSpectrogramAxisVectors().
getMelSpectrogramAxisVectors()
Error_t CSpectrogramIf::getMelSpectrogramAxisVectors (float * pfAxisTicks, enum AxisLabel_t eAxisLabel, const MelSpectrogramConfig_t * pMelSpecConfig)
returns axis ticks
Parameters
pfAxisTicks (to be written) equals iNumRows if eAxisLabel == kFrequencyInHz, otherwise iNumCols
eAxisLabel indicator which axis
pMelSpecConfig parametrization of the mel spectrogram
Returns
Error_t
Definition at line 296 of file Spectrogram.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks || !pMelSpecConfig)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    if (eAxisLabel == kTimeInS)
    {
        long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
        for (auto n = 0; n < iNumBlocks; n++)
            pfAxisTicks[n] = m_pCBlockAudio->getTimeStamp(n);
    }
    if (eAxisLabel == kFrequencyInHz)
    {
        generateMelFb_(pMelSpecConfig);
        assert(m_pffcMel);
        // note that we start with 1 to look at the center freqs only
        CVector::copy(pfAxisTicks, &m_pffcMel[1], pMelSpecConfig->iNumMelBins);
        destroyMelFb_(pMelSpecConfig);
    }
    return Error_t::kNoError;
}
References CVector::copy(), destroyMelFb_(), generateMelFb_(), CBlockAudioIf::getNumBlocks(), CBlockAudioIf::getTimeStamp(), CSpectrogramIf::MelSpectrogramConfig_t::iNumMelBins, kFrequencyInHz, kTimeInS, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, m_pCBlockAudio, and m_pffcMel.
getMelSpectrogramDimensions()
Error_t CSpectrogramIf::getMelSpectrogramDimensions (int & iNumRows, int & iNumCols, const MelSpectrogramConfig_t * pMelSpecConfig) const
returns size of matrix to be allocated by user
Parameters
iNumRows (number of rows, to be written) equals number of frequency bins
iNumCols (number of columns, to be written) equals number of blocks
pMelSpecConfig parametrization of the mel spectrogram
Returns
Error_t
Definition at line 278 of file Spectrogram.cpp.
{
    if (!pMelSpecConfig)
        return Error_t::kFunctionInvalidArgsError;
    if (!m_bIsInitialized)
    {
        iNumRows = 0;
        iNumCols = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumRows = pMelSpecConfig->iNumMelBins;
    iNumCols = static_cast<int>(m_pCBlockAudio->getNumBlocks());
    return Error_t::kNoError;
}
References CBlockAudioIf::getNumBlocks(), CSpectrogramIf::MelSpectrogramConfig_t::iNumMelBins, m_bIsInitialized, and m_pCBlockAudio.
Referenced by main().
getSpectrogramAxisVectors()
Error_t CSpectrogramIf::getSpectrogramAxisVectors (float * pfAxisTicks, enum AxisLabel_t eAxisLabel) const
returns axis ticks
Parameters
pfAxisTicks (to be written) equals iNumRows if eAxisLabel == kFrequencyInHz, otherwise iNumCols
eAxisLabel indicator which axis
Returns
Error_t
Definition at line 156 of file Spectrogram.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    if (eAxisLabel == kTimeInS)
    {
        long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
        for (auto n = 0; n < iNumBlocks; n++)
            pfAxisTicks[n] = m_pCBlockAudio->getTimeStamp(n);
    }
    if (eAxisLabel == kFrequencyInHz)
    {
        int iNumFreqBins = (m_iBlockLength >> 1) + 1;
        for (auto k = 0; k < iNumFreqBins; k++)
            pfAxisTicks[k] = m_pCFft->bin2freq(k, m_fSampleRate);
    }
    return Error_t::kNoError;
}
References CFft::bin2freq(), CBlockAudioIf::getNumBlocks(), CBlockAudioIf::getTimeStamp(), kFrequencyInHz, kTimeInS, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, m_pCBlockAudio, and m_pCFft.
getSpectrogramDimensions()
Error_t CSpectrogramIf::getSpectrogramDimensions (int & iNumRows, int & iNumCols) const
returns size of matrix to be allocated by user
Parameters
iNumRows (number of rows, to be written) equals number of frequency bins
iNumCols (number of columns, to be written) equals number of blocks
Returns
Error_t
Definition at line 141 of file Spectrogram.cpp.
{
    if (!m_bIsInitialized)
    {
        iNumRows = 0;
        iNumCols = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumRows = (m_iBlockLength >> 1) + 1;
    iNumCols = static_cast<int>(m_pCBlockAudio->getNumBlocks());
    return Error_t::kNoError;
}
References CBlockAudioIf::getNumBlocks(), m_bIsInitialized, m_iBlockLength, and m_pCBlockAudio.
Referenced by main().
init_()
Error_t CSpectrogramIf::init_ (float * pfWindow) protected
init configuration
Definition at line 260 of file Spectrogram.cpp.
{
    // initialize FFT and fft  buffer
    m_pCFft = new CFft();
    m_pCFft->init(m_iBlockLength);
    if (pfWindow)
        m_pCFft->overrideWindow(pfWindow);
    // allocate processing memory
    CVector::alloc(m_pfSpectrum, m_iBlockLength);
    CVector::alloc(m_pfProcBuff, m_iBlockLength);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CFft::init(), m_bIsInitialized, m_iBlockLength, m_pCFft, m_pfProcBuff, m_pfSpectrum, and CFft::overrideWindow().
Referenced by CSpectrogramFromFile::CSpectrogramFromFile(), and CSpectrogramFromVector::CSpectrogramFromVector().
operator=()
CSpectrogramIf & CSpectrogramIf::operator= (const CSpectrogramIf & c) protected
reset_()
Error_t CSpectrogramIf::reset_ () protected
reset configuration
Definition at line 238 of file Spectrogram.cpp.
{
    CVector::free(m_pfProcBuff);
    CVector::free(m_pfSpectrum);
    delete m_pCFft;
    m_pCFft = 0;
    delete m_pCNormalize;
    m_pCNormalize = 0;
    CBlockAudioIf::destroy(m_pCBlockAudio);
    m_iBlockLength = 0;
    m_iHopLength = 0;
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CBlockAudioIf::destroy(), CVector::free(), m_bIsInitialized, m_iBlockLength, m_iHopLength, m_pCBlockAudio, m_pCFft, m_pCNormalize, m_pfProcBuff, and m_pfSpectrum.
Referenced by CSpectrogramFromFile::CSpectrogramFromFile(), CSpectrogramIf(), and ~CSpectrogramIf().
Member Data Documentation
m_bIsInitialized
bool CSpectrogramIf::m_bIsInitialized = false protected
true if initialized
Definition at line 140 of file Spectrogram.h.
Referenced by compMelSpectrogram(), compSpectrogram(), getMelSpectrogramAxisVectors(), getMelSpectrogramDimensions(), getSpectrogramAxisVectors(), getSpectrogramDimensions(), init_(), and reset_().
m_fSampleRate
float CSpectrogramIf::m_fSampleRate = 0 protected
sample rate
Definition at line 132 of file Spectrogram.h.
Referenced by CSpectrogramFromFile::CSpectrogramFromFile(), CSpectrogramFromVector::CSpectrogramFromVector(), generateMelFb_(), getMelSpectrogramAxisVectors(), and getSpectrogramAxisVectors().
m_iBlockLength
int CSpectrogramIf::m_iBlockLength = 0 protected
fft length
Definition at line 129 of file Spectrogram.h.
Referenced by computeMagSpectrum_(), CSpectrogramFromFile::CSpectrogramFromFile(), CSpectrogramFromVector::CSpectrogramFromVector(), getMelSpectrogramAxisVectors(), getSpectrogramAxisVectors(), getSpectrogramDimensions(), init_(), and reset_().
m_iHopLength
int CSpectrogramIf::m_iHopLength = 0 protected
hop length
Definition at line 130 of file Spectrogram.h.
Referenced by CSpectrogramFromFile::CSpectrogramFromFile(), CSpectrogramFromVector::CSpectrogramFromVector(), getMelSpectrogramAxisVectors(), getSpectrogramAxisVectors(), and reset_().
m_pCBlockAudio
CBlockAudioIf* CSpectrogramIf::m_pCBlockAudio = 0 protected
instantiate for blocking time domain signal
Definition at line 125 of file Spectrogram.h.
Referenced by compMelSpectrogram(), compSpectrogram(), computeMagSpectrum_(), CSpectrogramFromFile::CSpectrogramFromFile(), CSpectrogramFromVector::CSpectrogramFromVector(), getMelSpectrogramAxisVectors(), getMelSpectrogramDimensions(), getSpectrogramAxisVectors(), getSpectrogramDimensions(), and reset_().
m_pCFft
CFft* CSpectrogramIf::m_pCFft = 0 protected
fft instance
Definition at line 127 of file Spectrogram.h.
Referenced by compMelSpectrogram(), compSpectrogram(), computeMagSpectrum_(), generateMelFb_(), getSpectrogramAxisVectors(), init_(), and reset_().
m_pCNormalize
CNormalizeAudio* CSpectrogramIf::m_pCNormalize = 0 protected
instantiate if audio file normalization is wanted
Definition at line 123 of file Spectrogram.h.
Referenced by computeMagSpectrum_(), CSpectrogramFromFile::CSpectrogramFromFile(), CSpectrogramFromVector::CSpectrogramFromVector(), reset_(), and CSpectrogramFromFile::~CSpectrogramFromFile().
m_pffcMel
float* CSpectrogramIf::m_pffcMel = 0 protected
Mel center frequencies.
Definition at line 138 of file Spectrogram.h.
Referenced by generateMelFb_(), and getMelSpectrogramAxisVectors().
m_pfProcBuff
float* CSpectrogramIf::m_pfProcBuff = 0 protected
temporary buffer
Definition at line 135 of file Spectrogram.h.
Referenced by compMelSpectrogram(), compSpectrogram(), computeMagSpectrum_(), init_(), reset_(), and CSpectrogramFromFile::~CSpectrogramFromFile().
m_pfSpectrum
float* CSpectrogramIf::m_pfSpectrum = 0 protected
temporary buffer for current spectrum
Definition at line 134 of file Spectrogram.h.
Referenced by compMelSpectrogram(), compSpectrogram(), computeMagSpectrum_(), init_(), and reset_().
m_ppfHMel
float** CSpectrogramIf::m_ppfHMel = 0 protected
Mel filterbank.
Definition at line 137 of file Spectrogram.h.
Referenced by compMelSpectrogram(), destroyMelFb_(), and generateMelFb_().
The documentation for this class was generated from the following files:
Spectrogram.h
Spectrogram.cpp