ACA: CKey Class Reference
CKey Class Reference
class for computation of the key from either a file or a vector
#include <Key.h>
Public Types
enum Keys_t {
kCMajor , kCsMajor , kDMajor , kDsMajor ,
kEMajor , kFMajor , kFsMajor , kGMajor ,
kGsMajor , kAMajor , kAsMajor , kBMajor ,
kCMinor , kCsMinor , kDMinor , kDsMinor ,
kEMinor , kFMinor , kFsMinor , kGMinor ,
kGsMinor , kAMinor , kAsMinor , kBMinor ,
kNoKey , kNumKeys
}
Public Member Functions
CKey ()
virtual ~CKey ()
Error_t init (const std::string &strAudioFilePath, int iBlockLength=4096, int iHopLength=2048)
Error_t init (const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=4096, int iHopLength=2048)
Error_t reset ()
int compKey ()
Static Public Member Functions
static std::string getKeyString (Keys_t eKeyIdx)
static Keys_t getKeyIdxFromString (std::string sKeyString)
Protected Member Functions
CKey (const CKey &that)
CKey & operator= (const CKey &c)
Protected Attributes
CFeatureIf * m_pCPitchChromaExtractor = 0
instance for extracting the pitch chroma
CKeyFromChroma * m_pCKeyFromChroma = 0
estimate key from one chroma
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of the key from either a file or a vector
Definition at line 14 of file Key.h.
Member Enumeration Documentation
Keys_t
enum CKey::Keys_t
detectable keys
Enumerator
kCMajor
kCsMajor
kDMajor
kDsMajor
kEMajor
kFMajor
kFsMajor
kGMajor
kGsMajor
kAMajor
kAsMajor
kBMajor
kCMinor
kCsMinor
kDMinor
kDsMinor
kEMinor
kFMinor
kFsMinor
kGMinor
kGsMinor
kAMinor
kAsMinor
kBMinor
kNoKey
kNumKeys
Definition at line 20 of file Key.h.
    {
        kCMajor,
        kCsMajor,
        kDMajor,
        kDsMajor,
        kEMajor,
        kFMajor,
        kFsMajor,
        kGMajor,
        kGsMajor,
        kAMajor,
        kAsMajor,
        kBMajor,
        kCMinor,
        kCsMinor,
        kDMinor,
        kDsMinor,
        kEMinor,
        kFMinor,
        kFsMinor,
        kGMinor,
        kGsMinor,
        kAMinor,
        kAsMinor,
        kBMinor,
        kNoKey,
        kNumKeys
    };
Constructor & Destructor Documentation
CKey() [1/2]
CKey::CKey ()
Definition at line 11 of file Key.cpp.
{
    m_pCKeyFromChroma = new CKeyFromChroma();
}
References m_pCKeyFromChroma.
~CKey()
CKey::~CKey () virtual
Definition at line 16 of file Key.cpp.
{
    reset();
    delete m_pCKeyFromChroma;
}
References m_pCKeyFromChroma, and reset().
CKey() [2/2]
CKey::CKey (const CKey & that) protected
Member Function Documentation
compKey()
int CKey::compKey ()
performs the key computation and returns the key index
Returns
Keys_t
Definition at line 82 of file Key.cpp.
{
    if (!m_bIsInitialized)
        return -1;
    int aiDim[2] = { 0 };
    float **m_ppfPitchChromagram = 0;
    float afAvgPitchChroma[12] = { 0 };
    // alloc memory
    m_pCPitchChromaExtractor->getFeatureDimensions(aiDim[0], aiDim[1]);
    CMatrix::alloc(m_ppfPitchChromagram, aiDim[0], aiDim[1]);
    // compute pitch chromagram
    m_pCPitchChromaExtractor->compFeatureNDim(m_ppfPitchChromagram);
    // average pitch chroma
    for (auto n = 0; n < aiDim[0]; n++)
        afAvgPitchChroma[n] = CVector::getMean(m_ppfPitchChromagram[n], aiDim[1]);
    CMatrix::free(m_ppfPitchChromagram, aiDim[0]);
    // compute key
    return m_pCKeyFromChroma->getKey(afAvgPitchChroma);
}
References CMatrix::alloc(), CFeatureIf::compFeatureNDim(), CMatrix::free(), CFeatureIf::getFeatureDimensions(), CKeyFromChroma::getKey(), CVector::getMean(), m_bIsInitialized, m_pCKeyFromChroma, and m_pCPitchChromaExtractor.
Referenced by main().
getKeyIdxFromString()
CKey::Keys_t CKey::getKeyIdxFromString (std::string sKeyString) static
returns Key index from string
Parameters
sKeyString string describing the Key
Returns
Keys_t
Definition at line 144 of file Key.cpp.
{
    const std::map<std::string, CKey::Keys_t> KeyMap
    {
        { "C Major", kCMajor },
        { "C# Major", kCsMajor },
        { "Db Major", kCsMajor },
        { "C# Major/Db Major", kCsMajor },
        { "D Major", kDMajor },
        { "D# Major", kDsMajor },
        { "Eb Major", kDsMajor },
        { "D# Major/Eb Major", kDsMajor },
        { "E Major", kEMajor },
        { "F Major", kFMajor },
        { "F# Majo", kFsMajor },
        { "Gb Major", kFsMajor },
        { "F# Major/Gb Major", kFsMajor },
        { "G Major", kGMajor },
        { "G# Major", kGsMajor },
        { "Ab Major", kGsMajor },
        { "G# Major/Ab Major", kGsMajor },
        { "A Major", kAMajor },
        { "A# Major", kAsMajor },
        { "Bb Major", kAsMajor },
        { "A# Major/Bb Major", kAsMajor },
        { "B Major", kBMajor },
        { "C Minor", kCMinor },
        { "C# Minor", kCsMinor },
        { "Db Minor", kCsMinor },
        { "C# Minor/Db Minor", kCsMinor },
        { "D Minor", kDMinor },
        { "D# Minor", kDsMinor },
        { "Eb Minor", kDsMinor },
        { "D# Minor/Eb Minor", kDsMinor },
        { "E Minor", kEMinor },
        { "F Minor", kFMinor },
        { "F# Minor", kFsMinor },
        { "Gb Minor", kFsMinor },
        { "F# Minor/Gb Minor", kFsMinor },
        { "G Minor", kGMinor },
        { "G# Minor", kGsMinor },
        { "Ab Minor", kGsMinor },
        { "G# Minor/Ab Minor", kGsMinor },
        { "A Minor", kAMinor },
        { "A# Minor", kAsMinor },
        { "Bb Minor", kAsMinor },
        { "A# Minor/Bb Minor", kAsMinor },
        { "B Minor", kBMinor },
        { "No Chord", kNoKey }
    };
    auto search = KeyMap.find(sKeyString);
    if (search != KeyMap.end())
        return KeyMap.at(sKeyString);
    else
        return kNumKeys;
}
References kAMajor, kAMinor, kAsMajor, kAsMinor, kBMajor, kBMinor, kCMajor, kCMinor, kCsMajor, kCsMinor, kDMajor, kDMinor, kDsMajor, kDsMinor, kEMajor, kEMinor, kFMajor, kFMinor, kFsMajor, kFsMinor, kGMajor, kGMinor, kGsMajor, kGsMinor, kNoKey, and kNumKeys.
getKeyString()
std::string CKey::getKeyString (Keys_t eKeyIdx) static
returns Key name as string
Parameters
eKeyIdx Key index
Returns
std::string
Definition at line 108 of file Key.cpp.
{
    const std::map<CKey::Keys_t, std::string> KeyMap
    {
        { kCMajor, "C Major" },
        { kCsMajor, "C# Major/Db Major" },
        { kDMajor, "D Major" },
        { kDsMajor, "D# Major/Eb Major" },
        { kEMajor, "E Major" },
        { kFMajor, "F Major" },
        { kFsMajor, "F# Major/Gb Major" },
        { kGMajor, "G Major" },
        { kGsMajor, "G# Major/Ab Major" },
        { kAMajor, "A Major" },
        { kAsMajor, "A# Major/Bb Major" },
        { kBMajor, "B Major" },
        { kCMinor, "C Minor" },
        { kCsMinor, "C# Minor/Db Minor" },
        { kDMinor, "D Minor" },
        { kDsMinor, "D# Minor/Eb Minor" },
        { kEMinor, "E Minor" },
        { kFMinor, "F Minor" },
        { kFsMinor, "F# Minor/Gb Minor" },
        { kGMinor, "G Minor" },
        { kGsMinor, "G# Minor/Ab Minor" },
        { kAMinor, "A Minor" },
        { kAsMinor, "A# Minor/Bb Minor" },
        { kBMinor, "B Minor" },
        { kNoKey, "No Chord" }
    };
    return KeyMap.at(eKeyIdx);
}
References kAMajor, kAMinor, kAsMajor, kAsMinor, kBMajor, kBMinor, kCMajor, kCMinor, kCsMajor, kCsMinor, kDMajor, kDMinor, kDsMajor, kDsMinor, kEMajor, kEMinor, kFMajor, kFMinor, kFsMajor, kFsMinor, kGMajor, kGMinor, kGsMajor, kGsMinor, and kNoKey.
Referenced by main().
init() [1/2]
Error_t CKey::init (const float * pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength = 4096, int iHopLength = 2048)
initializes a Key instance from audio data
Parameters
pfAudio complete audio data
iNumSamples length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in samples
iHopLength hop length in samples
Returns
Error_t
Definition at line 46 of file Key.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumSamples <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    Error_t rErr = CFeatureIf::create(m_pCPitchChromaExtractor, CFeatureIf::kFeatureSpectralPitchChroma, pfAudio, iNumSamples, fSampleRate, iBlockLength, iHopLength);
    if (rErr == Error_t::kNoError)
    {
        m_bIsInitialized = true;
        return Error_t::kNoError;
    }
    else
        return rErr;
}
References CFeatureIf::create(), CFeatureIf::kFeatureSpectralPitchChroma, m_bIsInitialized, m_pCPitchChromaExtractor, and reset().
init() [2/2]
Error_t CKey::init (const std::string & strAudioFilePath, int iBlockLength = 4096, int iHopLength = 2048)
initializes a Key instance with file reading
Parameters
strAudioFilePath complete path to audio file
iBlockLength FFT block length in samples
iHopLength hop length in samples
Returns
Error_t
Definition at line 23 of file Key.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    Error_t rErr = CFeatureIf::create(m_pCPitchChromaExtractor, CFeatureIf::kFeatureSpectralPitchChroma, strAudioFilePath, iBlockLength, iHopLength);
    if (rErr == Error_t::kNoError)
    {
        m_bIsInitialized = true;
        return Error_t::kNoError;
    }
    else
        return rErr;
}
References CFeatureIf::create(), CFeatureIf::kFeatureSpectralPitchChroma, m_bIsInitialized, m_pCPitchChromaExtractor, and reset().
Referenced by main().
operator=()
CKey & CKey::operator= (const CKey & c) protected
reset()
Error_t CKey::reset ()
resets instance
Returns
Error_t
Definition at line 73 of file Key.cpp.
{
    m_bIsInitialized = false;
    CFeatureIf::destroy(m_pCPitchChromaExtractor);
    return Error_t::kNoError;
}
References CFeatureIf::destroy(), m_bIsInitialized, and m_pCPitchChromaExtractor.
Referenced by init(), and ~CKey().
Member Data Documentation
m_bIsInitialized
bool CKey::m_bIsInitialized = false protected
true if initialized
Definition at line 103 of file Key.h.
Referenced by compKey(), init(), and reset().
m_pCKeyFromChroma
CKeyFromChroma* CKey::m_pCKeyFromChroma = 0 protected
estimate key from one chroma
Definition at line 101 of file Key.h.
Referenced by CKey(), compKey(), and ~CKey().
m_pCPitchChromaExtractor
CFeatureIf* CKey::m_pCPitchChromaExtractor = 0 protected
instance for extracting the pitch chroma
Definition at line 100 of file Key.h.
Referenced by compKey(), init(), and reset().
The documentation for this class was generated from the following files:
Key.h
Key.cpp