ACA: CVector Class Reference
CVector Class Reference
class with static functions for buffer operations with type T
#include <Vector.h>
Static Public Member Functions
template<typename T>
static void alloc (T *&ptVec, long long iLength)
template<typename T>
static void copy (T *ptDest, const T *ptSrc, long long int iLength)
template<typename T>
static void free (T *&ptVec)
template<typename T>
static void moveInMem (T *ptSrcDest, int iDestIdx, int isrcIdx, long long int iLength)
template<typename T>
static void setRand (T *ptDest, long long iLength)
template<typename T>
static void setValue (T *ptDest, T tValue, long long iLength)
template<typename T>
static void setZero (T *ptSrcDest, long long iLength)
template<typename T>
static void setZeroBelowThresh (T *ptSrcDest, long long int iLength, T tThresh)
template<typename T>
static void add_I (T *ptSrcDest, const T *ptSrc, long long int iLength)
template<typename T>
static void addC_I (T *ptSrcDest, T fConst, long long int iLength)
template<typename T>
static void addW_I (T *ptSrcDest, const T *ptSrc, T fWeight, long long int iLength)
template<typename T>
static void div_I (T *ptSrcDest, const T *ptSrc, long long int iLength)
template<typename T>
static void mulC_I (T *ptSrcDest, T fScale, long long int iLength)
template<typename T>
static void mul_I (T *ptSrcDest, const T *ptSrc, long long int iLength)
template<typename T>
static T mulScalar (const T *ptSrc1, const T *ptSrc2, long long int iLength)
template<typename T>
static void sub_I (T *ptSrcDest, const T *ptSrc, long long int iLength)
template<typename T>
static void subW_I (T *ptSrcDest, const T *ptSrc, T fWeight, long long int iLength)
template<typename T>
static void flip_I (T *ptSrcDest, long long int iLength)
template<typename T>
static void sort_I (T *ptSrcDest, int *piIndices, int iLength, bool bAscending=true)
template<typename T>
static T distCosine (const T *ptSrc1, const T *ptSrc2, long long iLength)
template<typename T>
static T distEuclidean (const T *ptSrc1, const T *ptSrc2, long long iLength)
template<typename T>
static T distManhattan (const T *ptSrc1, const T *ptSrc2, long long iLength)
template<typename T>
static T getMax (const T *ptSrc, long long int iLength, bool bAbs=false)
template<typename T>
static T getMean (const T *ptSrc, long long int iLength)
template<typename T>
static T getMin (const T *ptSrc, long long int iLength, bool bAbs=false)
template<typename T>
static T getRms (const T *ptSrc, long long int iLength)
template<typename T>
static T getStd (const T *ptSrc, long long int iLength, T fMean=std::numeric_limits< T >::max())
template<typename T>
static T getSum (const T *ptSrc, long long int iLength, bool bAbs=false)
template<typename T>
static void findMax (const T *ptSrc, T &fMax, long long &iMax, long long int iLength, bool bAbs=false)
template<typename T>
static void findMin (const T *ptSrc, T &fMin, long long &iMin, long long int iLength, bool bAbs=false)
template<typename T>
static int findPeaks (bool *pbisLocalMax, const T *ptSrc, long long int iLength, T fThresh=-std::numeric_limits< T >::max())
template<typename T>
static bool isEqual (const T *ptSrc1, const T *ptSrc2, long long int iLength)
Detailed Description
class with static functions for buffer operations with type T
Definition at line 14 of file Vector.h.
Member Function Documentation
add_I()
template<typename T> static void CVector::add_I (T * ptSrcDest, const T * ptSrc, long long int iLength) inline static
element-wise vector addition
Parameters
ptSrcDest one input and output buffer
ptSrc second input buffer
iLength number of element to be added
Definition at line 147 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        assert(ptSrc);
        for (auto i = 0; i < iLength; i++)
            ptSrcDest[i] += ptSrc[i];
    }
Referenced by CBeatHistoIf::compBeatHisto(), CPitchTimeAuditory::compF0(), CMatrix::det(), CPreProc::downmix(), and CInstFreq::process().
addC_I()
template<typename T> static void CVector::addC_I (T * ptSrcDest, T fConst, long long int iLength) inline static
adds a buffer to a scalar
Parameters
ptSrcDest buffer to be added
fConst scalar
iLength number of element to be added
Definition at line 163 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        for (auto i = 0; i < iLength; i++)
            ptSrcDest[i] += fConst;
    }
Referenced by CMatrix::addC_I(), CKnn::buildHistogram_(), CNoveltyIf::compNovelty(), CChordFromBlockIf::genTemplateMatrix_(), and CKeyFromChroma::getKey().
addW_I()
template<typename T> static void CVector::addW_I (T * ptSrcDest, const T * ptSrc, T fWeight, long long int iLength) inline static
weighted element-wise vector addition
Parameters
ptSrcDest one input and output buffer
ptSrc second input buffer
fWeight weight to be applied to ptSrc entries
iLength number of elements to be added
Definition at line 179 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        assert(ptSrc);
        for (auto i = 0; i < iLength; i++)
            ptSrcDest[i] += fWeight * ptSrc[i];
    }
Referenced by CMatrix::det(), and subW_I().
alloc()
template<typename T> static void CVector::alloc (T *& ptVec, long long iLength) inline static
allocates a T buffer and inits it with zeros
Parameters
ptVec (empty pointer, to be allocated)
iLength number of Ts
Definition at line 25 of file Vector.h.
    {
        assert(iLength > 0);
        ptVec = new T[iLength];
        assert(ptVec);
        setZero(ptVec, iLength);
    }
References setZero().
Referenced by CMatrix::alloc(), CFft::allocMemory_(), CButterLp::calcA(), CButterLp::calcCoeffs(), CPca::calcSVD(), CBlockAudioBuffer::CBlockAudioBuffer(), CChordFromBlockIf::CChordFromBlockIf(), CFeatureSpectralFlux::CFeatureSpectralFlux(), CFeatureSpectralMfccs::CFeatureSpectralMfccs(), CFeatureTimeMaxAcf::CFeatureTimeMaxAcf(), CGmmResult::CGmmResult(), CInstFreq::CInstFreq(), CNoveltyFromBlockIf::CNoveltyFromBlockIf(), CChordIf::compChords(), CNoveltyIf::compNovelty(), CPitchSpectralAcf::CPitchSpectralAcf(), CPitchSpectralHps::CPitchSpectralHps(), CPitchTimeAcf::CPitchTimeAcf(), CPitchTimeAuditory::CPitchTimeAuditory(), CSubFingerprint::CSubFingerprint(), CFilter< T >::filtfilt(), CMovingAverage::filtfilt(), CSpectrogramIf::generateMelFb_(), CCcf::init(), CDtw::init(), CFilter< T >::init(), CFingerprint::init(), CFingerprint::init(), CGmm::init(), CGmmClassifier::init(), CGmmResult::init(), CKmeans::init(), CKnn::init(), CLeaveOneOutCrossVal::init(), CPca::init(), CSeqFeatureSel::init(), CViterbi::init(), CBeatHistoIf::init_(), CBeatHistoIf::init_(), CChordIf::init_(), CFeatureIf::init_(), CFingerprint::init_(), CGammaToneFbIf::init_(), CNoveltyIf::init_(), CPitchIf::init_(), CSpectrogramIf::init_(), CResample::process(), CMatrix::rearrangeRows(), CFilter< T >::setInitState_(), CKnn::setParamK(), and CGmmClassifier::train().
copy()
template<typename T> static void CVector::copy (T * ptDest, const T * ptSrc, long long int iLength) inline static
copies buffer of type T
Parameters
ptDest pointer to destination memory
ptSrc pointer to source memory
iLength length of buffer
Definition at line 41 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptDest);
            assert(ptSrc);
            memcpy(ptDest, ptSrc, sizeof(T) * iLength);
        }
    }
Referenced by CButterLp::calcCoeffs(), CBlockAudioBuffer::CBlockAudioBuffer(), CGmmResult::CGmmResult(), CKmeans::checkConverged_(), CGmmClassifier::classify(), CKnn::classify(), CBeatHistoIf::compBeatHisto(), CCcf::compCcf(), CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), CFeatureSpectralFlux::compFeature(), CFft::compFft(), CFft::compInvFft(), CNoveltyFromBlockIf::compNovelty(), CMatrix::copy(), CPreProc::downmix(), CCcf::getCcf(), CKeyFromChroma::getKey(), CSpectrogramIf::getMelSpectrogramAxisVectors(), CBlockAudioBuffer::getNextBlock(), CGmmResult::getProb(), CSeqFeatureSel::getResult(), CFft::getWindow(), CFilter< T >::init(), CViterbi::init(), CFft::mergeRealImag(), CAudioFileSndLib::openFile(), CGmmResult::operator=(), CFft::overrideWindow(), CGammatone::process(), CInstFreq::process(), CLeaveOneOutCrossVal::process(), CSeqFeatureSel::process(), CMatrix::rearrangeRows(), CMatrix::setRow(), CFft::splitRealImag(), and CKnn::train().
distCosine()
template<typename T> static T CVector::distCosine (const T * ptSrc1, const T * ptSrc2, long long iLength) inline static
Cosine distance
Parameters
ptSrc1 first input vector
ptSrc2 second input vector
iLength length of vectors
Returns
T
Definition at line 381 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc1);
        assert(ptSrc2);
        T fDist = 0;
        for (auto i = 0; i < iLength; i++)
            fDist += ptSrc1[i] * ptSrc2[i];
        return 1.F - fDist / std::sqrt(mulScalar(ptSrc1, ptSrc1, iLength) * mulScalar(ptSrc2, ptSrc2, iLength));
    }
References mulScalar().
distEuclidean()
template<typename T> static T CVector::distEuclidean (const T * ptSrc1, const T * ptSrc2, long long iLength) inline static
Euclidean distance
Parameters
ptSrc1 first input vector
ptSrc2 second input vector
iLength length of vectors
Returns
T
Definition at line 402 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc1);
        assert(ptSrc2);
        T fDist = -2.F * mulScalar(ptSrc1, ptSrc2, iLength);
        fDist += mulScalar(ptSrc1, ptSrc1, iLength);
        fDist += mulScalar(ptSrc2, ptSrc2, iLength);
        return std::sqrt(fDist);
    }
References mulScalar().
Referenced by CKmeans::assignClusterLabels_(), and CKnn::classify().
distManhattan()
template<typename T> static T CVector::distManhattan (const T * ptSrc1, const T * ptSrc2, long long iLength) inline static
manhattan distance
Parameters
ptSrc1 first input vector
ptSrc2 second input vector
iLength length of vectors
Returns
T
Definition at line 422 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc1);
        assert(ptSrc2);
        T fDist = std::abs(ptSrc1[0] - ptSrc2[0]);
        for (auto i = 1; i < iLength; i++)
            fDist += std::abs(ptSrc1[i] - ptSrc2[i]);
        return fDist;
    }
Referenced by CKeyFromChroma::getKey().
div_I()
template<typename T> static void CVector::div_I (T * ptSrcDest, const T * ptSrc, long long int iLength) inline static
element-wise vector division
Parameters
ptSrcDest one input and output buffer
ptSrc second input buffer
iLength number of element to be divided
Definition at line 195 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        assert(ptSrc);
        for (auto i = 0; i < iLength; i++)
        {
            assert(ptSrc[i] != 0);
            ptSrcDest[i] /= ptSrc[i];
        }
    }
findMax()
template<typename T> static void CVector::findMax (const T * ptSrc, T & fMax, long long & iMax, long long int iLength, bool bAbs = false) inline static
finds the maximum (absolute) value in the buffer
Parameters
ptSrc input buffer
fMax resulting output value
iMax index of the resulting output value
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Definition at line 585 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc);
        fMax = -std::numeric_limits<T>::max();
        iMax = -1;
        for (auto i = 0; i < iLength; i++)
        {
            T fCurr = (bAbs) ? std::abs(ptSrc[i]) : ptSrc[i];
            if (fCurr > fMax)
            {
                fMax = fCurr;
                iMax = i;
            }
        }
    }
Referenced by CChordIf::compChords(), CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), CPitchTimeAcf::compF0(), CKnn::countMaxima_(), CPitchTimeAuditory::getAcfMax_(), CCcf::getCcfMaxIdx(), and getMax().
findMin()
template<typename T> static void CVector::findMin (const T * ptSrc, T & fMin, long long & iMin, long long int iLength, bool bAbs = false) inline static
finds the minimum (absolute) value in the buffer
Parameters
ptSrc input buffer
fMin resulting output value
iMin index of the resulting output value
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Definition at line 613 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc);
        fMin = std::numeric_limits<T>::max();
        iMin = -1;
        for (auto i = 0; i < iLength; i++)
        {
            T fCurr = (bAbs) ? std::abs(ptSrc[i]) : ptSrc[i];
            if (fCurr < fMin)
            {
                fMin = fCurr;
                iMin = i;
            }
        }
    }
Referenced by CKmeans::assignClusterLabels_(), CKeyFromChroma::getKey(), and getMin().
findPeaks()
template<typename T> static int CVector::findPeaks (bool * pbisLocalMax, const T * ptSrc, long long int iLength, T fThresh = -std::numeric_limits<T>::max()) inline static
finds the local maxima in the buffer
Parameters
pbisLocalMax result buffer
ptSrc input buffer
iLength number of elements in buffer
fThresh only detect maxima above this threshold
Returns
int number of local maxima
Definition at line 640 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc);
        assert(pbisLocalMax);
        int iNumPeaks = 0;
        CVector::setValue(pbisLocalMax, false, iLength);
        for (auto k = 1; k < iLength - 1; k++)
        {
            // search for local maxima
            if (ptSrc[k] <= ptSrc[k - 1] || ptSrc[k] <= ptSrc[k + 1] || ptSrc[k] <= fThresh)
                continue;
            else
            {
                pbisLocalMax[k] = true;
                iNumPeaks++;
                // increment because the next bin cannot be a local max
                k++;
            }
        }
        return iNumPeaks;
    }
References setValue().
Referenced by CNoveltyIf::compNovelty().
flip_I()
template<typename T> static void CVector::flip_I (T * ptSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
ptSrcDest pointer to memory to be flipped
iLength number of elements
Definition at line 294 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(ptSrcDest);
            auto iLoopLength = iLength / 2; // integer division!
            for (auto i = 0; i < iLoopLength; i++)
            {
                T Tmp = ptSrcDest[i];
                ptSrcDest[i] = ptSrcDest[iLength - 1 - i];
                ptSrcDest[iLength - 1 - i] = Tmp;
            }
        }
    }
Referenced by CBeatHistoIf::compBeatHisto(), and CPitchSpectralAcf::compF0().
free()
template<typename T> static void CVector::free (T *& ptVec) inline static
frees a T buffer and sets it to zero
Parameters
ptVec (empty pointer, to be allocated)
Definition at line 57 of file Vector.h.
    {
        delete[] ptVec;
        ptVec = 0;
    }
Referenced by CButterLp::calcA(), CButterLp::calcCoeffs(), CPca::calcSVD(), CChordIf::compChords(), CNoveltyIf::compNovelty(), CFilter< T >::filtfilt(), CMovingAverage::filtfilt(), CMatrix::free(), CFft::freeMemory_(), CFingerprint::init(), CResample::process(), CMatrix::rearrangeRows(), CCcf::reset(), CDtw::reset(), CFilter< T >::reset(), CFingerprint::reset(), CGmm::reset(), CGmmClassifier::reset(), CGmmResult::reset(), CKmeans::reset(), CKnn::reset(), CLeaveOneOutCrossVal::reset(), CPca::reset(), CSeqFeatureSel::reset(), CViterbi::reset(), CBeatHistoIf::reset_(), CChordIf::reset_(), CFeatureIf::reset_(), CGammaToneFbIf::reset_(), CNoveltyIf::reset_(), CPitchIf::reset_(), CSpectrogramIf::reset_(), CFilter< T >::setInitState_(), CKnn::setParamK(), CGmmClassifier::train(), CBlockAudioBuffer::~CBlockAudioBuffer(), CBlockAudioFile::~CBlockAudioFile(), CChordFromBlockIf::~CChordFromBlockIf(), CChordFromFile::~CChordFromFile(), CClassifierBase::~CClassifierBase(), CFeatureFromFile::~CFeatureFromFile(), CFeatureSpectralFlux::~CFeatureSpectralFlux(), CFeatureSpectralMfccs::~CFeatureSpectralMfccs(), CFeatureTimeMaxAcf::~CFeatureTimeMaxAcf(), CFingerprint::~CFingerprint(), CInstFreq::~CInstFreq(), CNoveltyFromBlockIf::~CNoveltyFromBlockIf(), CNoveltyFromFile::~CNoveltyFromFile(), CPitchFromFile::~CPitchFromFile(), CPitchSpectralAcf::~CPitchSpectralAcf(), CPitchSpectralHps::~CPitchSpectralHps(), CPitchTimeAcf::~CPitchTimeAcf(), CPitchTimeAuditory::~CPitchTimeAuditory(), CSpectrogramFromFile::~CSpectrogramFromFile(), and CSubFingerprint::~CSubFingerprint().
getMax()
template<typename T> static T CVector::getMax (const T * ptSrc, long long int iLength, bool bAbs = false) inline static
finds the maximum (absolute) value in the buffer
Parameters
ptSrc input buffer
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
T
Definition at line 444 of file Vector.h.
    {
        T fMax = 0;
        long long iMax = -1;
        findMax(ptSrc, fMax, iMax, iLength, bAbs);
        return fMax;
    }
References findMax().
Referenced by CKnn::buildHistogram_(), CNormalizeAudio::CNormalizeAudio(), CNormalizeAudio::CNormalizeAudio(), CPitchSpectralAcf::compF0(), CFeatureTimeMaxAcf::compFeature(), CFeatureFromBlockIf::compFeatureSpectralCrestFactor(), CFeatureFromBlockIf::compFeatureTimePeakEnvelope(), CClassifierBase::compNormConstants(), CNoveltyIf::compNovelty(), CCcf::getCcfMax(), CMatrix::getMax(), and CNormalizeAudio::normalizeSignal().
getMean()
template<typename T> static T CVector::getMean (const T * ptSrc, long long int iLength) inline static
extracts the mean value
Parameters
ptSrc input buffer
iLength number of elements in buffer
Returns
T
Definition at line 460 of file Vector.h.
    {
        assert(iLength >= 0);
        T fMean = getSum(ptSrc, iLength);
        if (iLength > 0)
        {
            fMean /= iLength;
        }
        return fMean;
    }
References getSum().
Referenced by CPca::compCov(), CFeatureFromBlockIf::compFeatureSpectralFlatness(), CKey::compKey(), CClassifierBase::compNormConstants(), CNoveltyIf::compNovelty(), getStd(), and CGmm::updateState_().
getMin()
template<typename T> static T CVector::getMin (const T * ptSrc, long long int iLength, bool bAbs = false) inline static
finds the minimum (absolute) value in the buffer
Parameters
ptSrc input buffer
iLength number of elements in buffer
bAbs bool to specify whether we search absolute values
Returns
T
Definition at line 481 of file Vector.h.
    {
        T fMin = 0;
        long long iMin = -1;
        findMin(ptSrc, fMin, iMin, iLength, bAbs);
        return fMin;
    }
References findMin().
Referenced by CFeatureFromBlockIf::compFeatureSpectralFlatness(), CClassifierBase::compNormConstants(), and CKmeans::reinitClusterMeans_().
getRms()
template<typename T> static T CVector::getRms (const T * ptSrc, long long int iLength) inline static
extracts the root mean square from a buffer
Parameters
ptSrc input buffer
iLength number of elements in buffer
Returns
T
Definition at line 497 of file Vector.h.
    {
        assert(iLength >= 0);
        T fRms = 0;
        for (auto i = 0; i < iLength; i++)
        {
            fRms += ptSrc[i] * ptSrc[i];
        }
        if (iLength > 0)
        {
            fRms /= iLength;
        }
        return std::sqrt(fRms);
    }
getStd()
template<typename T> static T CVector::getStd (const T * ptSrc, long long int iLength, T fMean = std::numeric_limits<T>::max()) inline static
extracts the standard deviation (biased) from a buffer
Parameters
ptSrc input buffer
iLength number of elements in buffer
fMean mean value if it has already been computed, otherwise it will be extracted in function
Returns
T
Definition at line 524 of file Vector.h.
    {
        assert(iLength >= 0);
        T  fStd = 0;
        if (fMean == std::numeric_limits<T>::max())
        {
            fMean = getMean(ptSrc, iLength);
        }
        for (auto i = 0; i < iLength; i++)
        {
            fStd += (ptSrc[i] - fMean) * (ptSrc[i] - fMean);
        }
        if (iLength > 1)
        {
            //dStd   /= (iLength - 1);
            fStd /= iLength;
        }
        return std::sqrt(fStd);
    }
References getMean().
Referenced by CFeatureFromBlockIf::compFeatureTimeRms(), CFeatureFromBlockIf::compFeatureTimeStd(), and CClassifierBase::compNormConstants().
getSum()
template<typename T> static T CVector::getSum (const T * ptSrc, long long int iLength, bool bAbs = false) inline static
computes the sum of a vector
Parameters
ptSrc vector
iLength length of vector
bAbs specifies whether it is the sum of absolute values or not
Returns
T
Definition at line 556 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc);
        T fResult = 0;
        if (bAbs)
        {
            for (auto i = 0; i < iLength; i++)
                fResult += std::abs(ptSrc[i]);
        }
        else
        {
            for (auto i = 0; i < iLength; i++)
                fResult += ptSrc[i];
        }
        return fResult;
    }
Referenced by CKmeans::checkConverged_(), CKeyFromChroma::CKeyFromChroma(), CChordFromBlockIf::compChordProb(), CPitchTimeAmdf::compF0(), CFeatureSpectralPitchChroma::compFeature(), CFeatureFromBlockIf::compFeatureSpectralCrestFactor(), CFeatureFromBlockIf::compFeatureSpectralRolloff(), CKeyFromChroma::getKey(), getMean(), CMatrix::getSum(), CChordIf::initViterbi_(), and CGmm::updateState_().
isEqual()
template<typename T> static bool CVector::isEqual (const T * ptSrc1, const T * ptSrc2, long long int iLength) inline static
checks to buffer for equality (no floating point tolerance)
Parameters
ptSrc1 buffer 1
ptSrc2 buffer 2
iLength number of dimensions
Returns
bool
Definition at line 676 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc1);
        assert(ptSrc2);
        return (memcmp(ptSrc1, ptSrc2, iLength * sizeof(T)) == 0);
    }
moveInMem()
template<typename T> static void CVector::moveInMem (T * ptSrcDest, int iDestIdx, int isrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
ptSrcDest source and destination
iDestIdx destination index
isrcIdx source index
iLength number of elements to be moved
Definition at line 70 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        if (iLength > 0)
            memmove(&ptSrcDest[iDestIdx], &ptSrcDest[isrcIdx], sizeof(T) * iLength);
    }
mul_I()
template<typename T> static void CVector::mul_I (T * ptSrcDest, const T * ptSrc, long long int iLength) inline static
element-wise vector multiplication
Parameters
ptSrcDest one input and output buffer
ptSrc second input buffer
iLength number of element to be multiplied
Definition at line 229 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        assert(ptSrc);
        for (auto i = 0; i < iLength; i++)
            ptSrcDest[i] *= ptSrc[i];
    }
Referenced by CFft::compFft(), CFft::compInvFft(), and CClassifierBase::normalizeVector().
mulC_I()
template<typename T> static void CVector::mulC_I (T * ptSrcDest, T fScale, long long int iLength) inline static
multiplies a buffer with a scalar
Parameters
ptSrcDest buffer to be multiplied
fScale scalar
iLength number of element to be multiplied
Definition at line 214 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        for (auto i = 0; i < iLength; i++)
            ptSrcDest[i] *= fScale;
    }
Referenced by CKnn::buildHistogram_(), CGammatone::calcFilterCoeffs_(), CCcf::compCcf(), CChordFromBlockIf::compChordProb(), CKmeans::compClusterMeans_(), CFeatureSpectralPitchChroma::compFeature(), CNoveltyIf::compNovelty(), CGmm::compProbabilities_(), CChordIf::computeMagSpectrum_(), CFeatureIf::computeMagSpectrum_(), CFingerprint::computeMagSpectrum_(), CNoveltyIf::computeMagSpectrum_(), CPitchIf::computeMagSpectrum_(), CSpectrogramIf::computeMagSpectrum_(), CFft::conjugate_I(), CMatrix::det(), CPreProc::downmix(), CFeatureSpectralMfccs::genDctMat_(), CKeyFromChroma::getKey(), CKmeans::initClusterMeans_(), CGmm::initState_(), CChordIf::initViterbi_(), CMatrix::inv_I(), CMatrix::mulC_I(), CNormalizeAudio::normalizeBlock(), CNormalizeAudio::normalizeSignal(), CInstFreq::process(), and CKmeans::reinitClusterMeans_().
mulScalar()
template<typename T> static T CVector::mulScalar (const T * ptSrc1, const T * ptSrc2, long long int iLength) inline static
computes the scalar product between two vectors
Parameters
ptSrc1 vector one
ptSrc2 vector two
iLength number of dimenions
Returns
T
Definition at line 246 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrc1);
        assert(ptSrc2);
        T  fResult = 0;
        for (auto i = 0; i < iLength; i++)
            fResult += ptSrc1[i] * ptSrc2[i];
        return fResult;
    }
Referenced by CCcf::compCcf(), CFeatureSpectralMfccs::compFeature(), CFeatureFromBlockIf::compFeatureTimeAcfCoeff(), CSpectrogramIf::compMelSpectrogram(), CGmm::compProbabilities_(), distCosine(), distEuclidean(), CGmmResult::getProb(), CMatrix::mulMatColvec(), and CGmm::updateState_().
setRand()
template<typename T> static void CVector::setRand (T * ptDest, long long iLength) inline static
initializes the buffer with random noise
Parameters
ptDest pointer to memory to be initialized
iLength number of elements to be set
Definition at line 86 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptDest);
        CSynthesis::genNoise(ptDest, iLength);
    }
References CSynthesis::genNoise().
Referenced by CMatrix::setRand().
setValue()
template<typename T> static void CVector::setValue (T * ptDest, T tValue, long long iLength) inline static
initializes the buffer to a specific value
Parameters
ptDest pointer to memory to be set
tValue value to use
iLength number of elements to be set
Definition at line 100 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptDest);
        for (auto i = 0; i < iLength; i++)
            ptDest[i] = tValue;
    }
Referenced by CKnn::buildHistogram_(), CClassifierBase::compNormConstants(), CNoveltyIf::compNovelty(), CViterbi::compProbability_(), findPeaks(), CSubFingerprint::genBands_(), CFeatureSpectralPitchChroma::genPcFilters_(), CChordIf::initViterbi_(), CSeqFeatureSel::process(), and CMatrix::setValue().
setZero()
template<typename T> static void CVector::setZero (T * ptSrcDest, long long iLength) inline static
sets a buffer to zero
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
Definition at line 114 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        if (iLength > 0)
            memset(ptSrcDest, 0, sizeof(T) * iLength);
    }
Referenced by alloc(), CKmeans::assignClusterLabels_(), CKnn::buildHistogram_(), CButterLp::calcCoeffs(), CDtw::CDtw(), CFeatureSpectralFlux::CFeatureSpectralFlux(), CBeatHistoIf::compBeatHisto(), CChordFromBlockIf::compChordProb(), CDtw::compDtw(), CPitchSpectralHps::compF0(), CPitchTimeAuditory::compF0(), CFeatureSpectralMfccs::compFeature(), CFeatureSpectralPitchChroma::compFeature(), CFft::compFft(), CClassifierBase::compNormConstants(), CGmm::compProbabilities_(), CSubFingerprint::compSubFingerprint(), CBlockAudioBuffer::getNextBlock(), CBlockAudioFile::getNextBlock(), CFilter< T >::init(), CLeaveOneOutCrossVal::init(), CMatrix::mulRowvecMat(), CBlockAudioFile::readFile2RingBuff(), CFilter< T >::reset(), CNmfResult::reset(), CSubFingerprint::reset(), CMatrix::setEye(), and CMatrix::setZero().
setZeroBelowThresh()
template<typename T> static void CVector::setZeroBelowThresh (T * ptSrcDest, long long int iLength, T tThresh) inline static
sets all values smaller than a threshold to 0
Parameters
ptSrcDest pointer to memory to be modified
iLength buffer length
tThresh threshold value
Definition at line 129 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        for (auto i = 0; i < iLength; i++)
            if (ptSrcDest[i] < tThresh)
                ptSrcDest[i] = 0;
    }
Referenced by CNoveltyIf::compNovelty(), and CMatrix::setZeroBelowThresh().
sort_I()
template<typename T> static void CVector::sort_I (T * ptSrcDest, int * piIndices, int iLength, bool bAscending = true) inline static
sorts values in a buffer
Parameters
ptSrcDest buffer to be sorted
piIndices new indices (optional, can be left 0)
iLength number of elements to be sorted
bAscending sort order (descending -> false)
Definition at line 319 of file Vector.h.
    {
        // go bubble sort! ( should be replaced some time with something faster)
        bool bDone = false; // this flag will be used to check whether we have to continue the algorithm
        // initialize
        if (piIndices)
            for (auto i = 0; i < iLength; i++)
                piIndices[i] = i;
        if (bAscending)
        {
            while (!bDone)
            {
                bDone = true;
                for (auto i = 0; i < iLength - 1; i++)
                {
                    if (ptSrcDest[i] > ptSrcDest[i + 1]) // compare the current element with the following one
                    {
                        //swap them
                        CUtil::swap(ptSrcDest[i], ptSrcDest[i + 1]);
                        if (piIndices)
                            CUtil::swap(piIndices[i], piIndices[i + 1]);
                        bDone = false; // let's recheck the array
                    }
                }
            }
        }
        else // descending
        {
            while (!bDone)
            {
                bDone = true;
                for (auto i = 0; i < iLength - 1; i++)
                {
                    if (ptSrcDest[i] < ptSrcDest[i + 1]) // compare the current element with the following one
                    {
                        //swap them
                        CUtil::swap(ptSrcDest[i], ptSrcDest[i + 1]);
                        if (piIndices)
                            CUtil::swap(piIndices[i], piIndices[i + 1]);
                        bDone = false; // let's recheck the array
                    }
                }
            }
        }
    }
References CUtil::swap().
Referenced by CKnn::classify(), and CPca::compPca().
sub_I()
template<typename T> static void CVector::sub_I (T * ptSrcDest, const T * ptSrc, long long int iLength) inline static
element-wise vector subtraction
Parameters
ptSrcDest one input and output buffer
ptSrc second input buffer
iLength number of element to be subtracted
Definition at line 265 of file Vector.h.
    {
        assert(iLength >= 0);
        assert(ptSrcDest);
        assert(ptSrc);
        for (auto i = 0; i < iLength; i++)
            ptSrcDest[i] -= ptSrc[i];
    }
Referenced by CKmeans::checkConverged_(), CNoveltyIf::compNovelty(), CGmmResult::getProb(), CClassifierBase::normalizeVector(), and CInstFreq::process().
subW_I()
template<typename T> static void CVector::subW_I (T * ptSrcDest, const T * ptSrc, T fWeight, long long int iLength) inline static
weighted element-wise vector subtraction
Parameters
ptSrcDest one input and output buffer
ptSrc second input buffer
fWeight weight to be applied to ptSrc entries
iLength number of element to be subtracted
Definition at line 282 of file Vector.h.
    {
        addW_I(ptSrcDest, ptSrc, -fWeight, iLength);
    }
References addW_I().
Referenced by CMatrix::inv_I().
The documentation for this class was generated from the following file:
Vector.h