ACA: CBlockAudioIf Class Reference
CBlockAudioIf Class Reference abstract
forward declaration
#include <ToolBlockAudio.h>
Public Member Functions
long long getNumBlocks () const
long long getLengthInSamples () const
float getTimeStamp (long long iBlockIdx)
virtual bool isEndOfData () const =0
virtual int getNextBlock (float *pfBlock, float *pfTimeStampInS=0)=0
Static Public Member Functions
static Error_t create (CBlockAudioIf *&pCInstance, CAudioFileIf *pCAudioFile, int iBlockLength, int iHopLength)
static Error_t create (CBlockAudioIf *&pCInstance, const float *pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate)
static Error_t destroy (CBlockAudioIf *&pCInstance)
Protected Member Functions
CBlockAudioIf ()
virtual ~CBlockAudioIf ()
CBlockAudioIf (const CBlockAudioIf &that)
CBlockAudioIf & operator= (const CBlockAudioIf &c)
Protected Attributes
long long m_iNumBlocks = 0
number of blocks
long long m_iCurrBlock = 0
current block index
long long m_iAudioLength = 0
length of audio buffer
int m_iBlockLength = 0
block length
int m_iNumChannels = 0
number of channels
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
Detailed Description
forward declaration
class for audio blocking, supports both an audio file or an audio buffer as source to block
Definition at line 10 of file ToolBlockAudio.h.
Constructor & Destructor Documentation
CBlockAudioIf() [1/2]
CBlockAudioIf::CBlockAudioIf () inline protected
Definition at line 84 of file ToolBlockAudio.h.
{};
~CBlockAudioIf()
virtual CBlockAudioIf::~CBlockAudioIf () inline protected virtual
Definition at line 85 of file ToolBlockAudio.h.
{};
CBlockAudioIf() [2/2]
CBlockAudioIf::CBlockAudioIf (const CBlockAudioIf & that) protected
Member Function Documentation
create() [1/2]
Error_t CBlockAudioIf::create (CBlockAudioIf *& pCInstance, CAudioFileIf * pCAudioFile, int iBlockLength, int iHopLength) static
creates an instance for blocking from file
Parameters
pCInstance pointer to instance to be written
pCAudioFile pointer to audio file
iBlockLength block length in frames
iHopLength hop length in frames
Returns
float
Definition at line 183 of file ToolBlockAudio.cpp.
{
    if (!pCAudioFile)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 0 || iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CBlockAudioFile(pCAudioFile, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, and kNoError.
Referenced by CChordFromFile::CChordFromFile(), CChordFromVector::CChordFromVector(), CFeatureFromFile::CFeatureFromFile(), CFeatureFromVector::CFeatureFromVector(), CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), CNoveltyFromFile::CNoveltyFromFile(), CNoveltyFromVector::CNoveltyFromVector(), CBeatHistoIf::compBeatHisto(), CPitchFromFile::CPitchFromFile(), CPitchFromVector::CPitchFromVector(), CSpectrogramFromFile::CSpectrogramFromFile(), and CSpectrogramFromVector::CSpectrogramFromVector().
create() [2/2]
Error_t CBlockAudioIf::create (CBlockAudioIf *& pCInstance, const float * pfAudioBuff, long long iAudioLength, int iBlockLength, int iHopLength, float fSampleRate) static
creates an instance for blocking from vector
Parameters
pCInstance pointer to instance to be written
pfAudioBuff buffer with audio data
iAudioLength length of pfAudioBuff in frames
iBlockLength block length in frames
iHopLength hop length in frames
fSampleRate sample rate in Hz
Returns
float
Definition at line 195 of file ToolBlockAudio.cpp.
{
    if (!pfAudioBuff)
        return Error_t::kFunctionInvalidArgsError;
    if (iAudioLength <= 0 || iBlockLength <= 0 || iHopLength <= 0 || iHopLength > iBlockLength || fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CBlockAudioBuffer(pfAudioBuff, iAudioLength, iBlockLength, iHopLength, fSampleRate);
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, and kNoError.
destroy()
static Error_t CBlockAudioIf::destroy (CBlockAudioIf *& pCInstance) inline static
destroys a block audio instance
Parameters
pCInstance pointer to instance to be written
Returns
Error_t
Definition at line 38 of file ToolBlockAudio.h.
    {
        delete pCInstance;
        pCInstance = 0;
        return Error_t::kNoError;
    };
References kNoError.
Referenced by CBeatHistoIf::compBeatHisto(), CChordIf::reset_(), CFeatureIf::reset_(), CNoveltyIf::reset_(), CPitchIf::reset_(), CSpectrogramIf::reset_(), and CGammaToneFbIf::reset_().
getLengthInSamples()
long long CBlockAudioIf::getLengthInSamples () const inline
returns number of samples
Returns
number of samples for current audio
Definition at line 57 of file ToolBlockAudio.h.
    {
        return m_iAudioLength;
    };
References m_iAudioLength.
Referenced by CGammaToneFbIf::getOutputDimensions().
getNextBlock()
virtual int CBlockAudioIf::getNextBlock (float * pfBlock, float * pfTimeStampInS = 0) pure virtual
retrieves audio data for next block
Parameters
pfBlock (to be written) of length blocklength
pfTimeStampInS (to be written, optional) for current time stamp
Returns
int iNumFramesRead
Implemented in CBlockAudioFile, and CBlockAudioBuffer.
Referenced by CBeatHistoIf::compBeatHisto(), CChordIf::compChords(), CPitchIf::compF0(), CFeatureIf::compFeature1Dim(), CFeatureIf::compFeatureNDim(), CNoveltyIf::compNovelty(), CSpectrogramIf::computeMagSpectrum_(), and CGammaToneFbIf::process().
getNumBlocks()
long long CBlockAudioIf::getNumBlocks () const inline
returns number of blocks
Returns
number of blocks for current audio
Definition at line 49 of file ToolBlockAudio.h.
    {
        return m_iNumBlocks;
    };
References m_iNumBlocks.
Referenced by CBeatHistoIf::compBeatHisto(), CChordIf::compChords(), CPitchIf::compF0(), CFeatureIf::compFeature1Dim(), CFeatureIf::compFeatureNDim(), CSpectrogramIf::compMelSpectrogram(), CNoveltyIf::compNovelty(), CSpectrogramIf::compSpectrogram(), CFeatureIf::getFeatureDimensions(), CSpectrogramIf::getMelSpectrogramAxisVectors(), CSpectrogramIf::getMelSpectrogramDimensions(), CChordIf::getNumBlocks(), CNoveltyIf::getNumBlocks(), CPitchIf::getNumBlocks(), CSpectrogramIf::getSpectrogramAxisVectors(), CSpectrogramIf::getSpectrogramDimensions(), CChordIf::getTimeStamps(), CFeatureIf::getTimeStamps(), CNoveltyIf::getTimeStamps(), CPitchIf::getTimeStamps(), CChordIf::init_(), CChordIf::initViterbi_(), and CGammaToneFbIf::process().
getTimeStamp()
float CBlockAudioIf::getTimeStamp (long long iBlockIdx) inline
returns time stamp in s for a given block index
Parameters
iBlockIdx index for requested time stamp
Returns
float
Definition at line 66 of file ToolBlockAudio.h.
    {
        return (m_iBlockLength / 2.F + iBlockIdx * m_iHopLength) / m_fSampleRate;
    }
References m_fSampleRate, m_iBlockLength, and m_iHopLength.
Referenced by CSpectrogramIf::getMelSpectrogramAxisVectors(), CBlockAudioFile::getNextBlock(), CBlockAudioBuffer::getNextBlock(), CSpectrogramIf::getSpectrogramAxisVectors(), CChordIf::getTimeStamp(), CFeatureIf::getTimeStamp(), CNoveltyIf::getTimeStamp(), CPitchIf::getTimeStamp(), CChordIf::getTimeStamps(), CFeatureIf::getTimeStamps(), CNoveltyIf::getTimeStamps(), and CPitchIf::getTimeStamps().
isEndOfData()
virtual bool CBlockAudioIf::isEndOfData () const pure virtual
checks for end of data
Returns
bool true if end of audio data is reached
Implemented in CBlockAudioFile, and CBlockAudioBuffer.
operator=()
CBlockAudioIf & CBlockAudioIf::operator= (const CBlockAudioIf & c) protected
Member Data Documentation
m_fSampleRate
float CBlockAudioIf::m_fSampleRate = 0 protected
sample rate
Definition at line 97 of file ToolBlockAudio.h.
Referenced by CBlockAudioBuffer::CBlockAudioBuffer(), CBlockAudioFile::CBlockAudioFile(), and getTimeStamp().
m_iAudioLength
long long CBlockAudioIf::m_iAudioLength = 0 protected
length of audio buffer
Definition at line 91 of file ToolBlockAudio.h.
Referenced by CBlockAudioBuffer::CBlockAudioBuffer(), CBlockAudioFile::CBlockAudioFile(), getLengthInSamples(), CBlockAudioBuffer::getNextBlock(), CBlockAudioBuffer::isEndOfData(), and CBlockAudioBuffer::~CBlockAudioBuffer().
m_iBlockLength
int CBlockAudioIf::m_iBlockLength = 0 protected
block length
Definition at line 93 of file ToolBlockAudio.h.
Referenced by CBlockAudioBuffer::CBlockAudioBuffer(), CBlockAudioFile::CBlockAudioFile(), CBlockAudioFile::getNextBlock(), CBlockAudioBuffer::getNextBlock(), and getTimeStamp().
m_iCurrBlock
long long CBlockAudioIf::m_iCurrBlock = 0 protected
current block index
Definition at line 90 of file ToolBlockAudio.h.
Referenced by CBlockAudioFile::getNextBlock(), and CBlockAudioBuffer::getNextBlock().
m_iHopLength
int CBlockAudioIf::m_iHopLength = 0 protected
hop length
Definition at line 95 of file ToolBlockAudio.h.
Referenced by CBlockAudioBuffer::CBlockAudioBuffer(), CBlockAudioFile::CBlockAudioFile(), CBlockAudioFile::getNextBlock(), CBlockAudioBuffer::getNextBlock(), getTimeStamp(), and CBlockAudioFile::readFile2RingBuff().
m_iNumBlocks
long long CBlockAudioIf::m_iNumBlocks = 0 protected
number of blocks
Definition at line 89 of file ToolBlockAudio.h.
Referenced by CBlockAudioBuffer::CBlockAudioBuffer(), CBlockAudioFile::CBlockAudioFile(), and getNumBlocks().
m_iNumChannels
int CBlockAudioIf::m_iNumChannels = 0 protected
number of channels
Definition at line 94 of file ToolBlockAudio.h.
Referenced by CBlockAudioFile::CBlockAudioFile(), CBlockAudioFile::getNextBlock(), CBlockAudioFile::readFile2RingBuff(), and CBlockAudioFile::~CBlockAudioFile().
The documentation for this class was generated from the following files:
ToolBlockAudio.h
ToolBlockAudio.cpp