ACA: CLeaveOneOutCrossVal Class Reference
CLeaveOneOutCrossVal Class Reference
computation of leav one out cross validation
#include <ToolLeaveOneOutCrossVal.h>
Public Member Functions
CLeaveOneOutCrossVal (void)
virtual ~CLeaveOneOutCrossVal (void)
Error_t init (int iNumFeatures, int iNumObservations, CClassifierBase *pCClassifier)
float process (float **ppfTrainFeatures, const int *piTrainClassIndices)
Error_t reset ()
Private Member Functions
CLeaveOneOutCrossVal (const CLeaveOneOutCrossVal &that)
disallow copy construction
CLeaveOneOutCrossVal & operator= (const CLeaveOneOutCrossVal &c)
Private Attributes
int m_iNumFeatures = 0
number of features
int m_iNumObs = 0
number of neighbors for classification
float ** m_ppfTrain = 0
train data (m_iNumObs X m_iNumFeatures)
float * m_pfQuery = 0
preallocated vector for the normalized query
int * m_piClassLabels = 0
CClassifierBase * m_pCClassifier = 0
bool m_bIsInitialized = false
indicates if instance has been properly initialized
Detailed Description
computation of leav one out cross validation
Definition at line 12 of file ToolLeaveOneOutCrossVal.h.
Constructor & Destructor Documentation
CLeaveOneOutCrossVal() [1/2]
CLeaveOneOutCrossVal::CLeaveOneOutCrossVal (void) inline
Definition at line 15 of file ToolLeaveOneOutCrossVal.h.
{};
~CLeaveOneOutCrossVal()
CLeaveOneOutCrossVal::~CLeaveOneOutCrossVal (void) virtual
Definition at line 8 of file ToolLeaveOneOutCrossVal.cpp.
{ reset(); }
References reset().
CLeaveOneOutCrossVal() [2/2]
CLeaveOneOutCrossVal::CLeaveOneOutCrossVal (const CLeaveOneOutCrossVal & that) private
disallow copy construction
Member Function Documentation
init()
Error_t CLeaveOneOutCrossVal::init (int iNumFeatures, int iNumObservations, CClassifierBase * pCClassifier)
initializes LeaveOneOutCrossVal instance
Parameters
iNumFeatures number of features (rows in the input matrix)
iNumObservations number of observations (columns in the feature matrix)
pCClassifier classifier to be used internally
Returns
Error_t
Definition at line 10 of file ToolLeaveOneOutCrossVal.cpp.
{
    if (iNumFeatures <= 0 || iNumObservations <= 1)
        return Error_t::kFunctionInvalidArgsError;
    if (!pCClassifier)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    // set internal member variables
    m_iNumFeatures = iNumFeatures;
    m_iNumObs = iNumObservations;
    m_pCClassifier = pCClassifier;
    // allocate memory for feature and ground truth data, and query
    CMatrix::alloc(m_ppfTrain, m_iNumFeatures, m_iNumObs - static_cast<long long>(1));
    CVector::alloc(m_piClassLabels, m_iNumObs - static_cast<long long>(1));
    CVector::alloc(m_pfQuery, m_iNumFeatures);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iNumFeatures, m_iNumObs, m_pCClassifier, m_pfQuery, m_piClassLabels, m_ppfTrain, and reset().
operator=()
CLeaveOneOutCrossVal & CLeaveOneOutCrossVal::operator= (const CLeaveOneOutCrossVal & c) private
process()
float CLeaveOneOutCrossVal::process (float ** ppfTrainFeatures, const int * piTrainClassIndices)
initializes LeaveOneOutCrossVal instance
Parameters
ppfTrainFeatures feature data for 'training' (dimensions iNumFeatures X iNumObservations)
piTrainClassIndices ground truth class index for each observation
Returns
Error_t
Definition at line 34 of file ToolLeaveOneOutCrossVal.cpp.
{
    if (!m_bIsInitialized)
        return -1.F;
    if (!ppfTrainFeatures || !piTrainClassIndices)
        return -1.F;
    if (!ppfTrainFeatures[0])
        return -1.F;
    assert(m_iNumObs > 1);
    assert(m_iNumFeatures > 0);
    int iGtLabel = piTrainClassIndices[m_iNumObs - 1];
    int iTruePositives = 0;
    // initialize classifier
    m_pCClassifier->init(m_iNumFeatures, m_iNumObs - 1);
    // copy feature data and ground truth data
    CMatrix::copy(m_ppfTrain, ppfTrainFeatures, m_iNumFeatures, m_iNumObs - static_cast<long long>(1));
    CVector::copy(m_piClassLabels, piTrainClassIndices, m_iNumObs - static_cast<long long>(1));
    for (int n = 0; n < m_iNumObs-1; n++)
    {
        CMatrix::getCol(m_pfQuery, ppfTrainFeatures, m_iNumObs - 1 - n, m_iNumFeatures);
        iGtLabel = piTrainClassIndices[m_iNumObs - 1 - n];
        // train (check reset and memory alloc)
        m_pCClassifier->train(m_ppfTrain, m_piClassLabels);
        // classify
        if (iGtLabel == m_pCClassifier->classify(m_pfQuery))
            iTruePositives++;
        // prep for next round
        CMatrix::setCol(m_ppfTrain, m_pfQuery, m_iNumObs - 2 - n, m_iNumFeatures);
        m_piClassLabels[m_iNumObs - 2 - n] = iGtLabel;
    }
    // last observation (avoid if in loop)
    CMatrix::getCol(m_pfQuery, ppfTrainFeatures, 0, m_iNumFeatures);
    iGtLabel = piTrainClassIndices[0];
    // train (check reset and memory alloc)
    m_pCClassifier->train(m_ppfTrain, m_piClassLabels);
    // classify
    if (iGtLabel == m_pCClassifier->classify(m_pfQuery))
        iTruePositives++;
    return iTruePositives * 1.F / m_iNumObs;
}
References CClassifierBase::classify(), CMatrix::copy(), CVector::copy(), CMatrix::getCol(), CClassifierBase::init(), m_bIsInitialized, m_iNumFeatures, m_iNumObs, m_pCClassifier, m_pfQuery, m_piClassLabels, m_ppfTrain, CMatrix::setCol(), and CClassifierBase::train().
reset()
Error_t CLeaveOneOutCrossVal::reset ()
resets LeaveOneOutCrossVal instance
Returns
Error_t
Definition at line 91 of file ToolLeaveOneOutCrossVal.cpp.
{
    m_bIsInitialized = false;
    // allocate memory for feature and ground truth data, and query
    CMatrix::free(m_ppfTrain, m_iNumFeatures);
    CVector::free(m_piClassLabels);
    CVector::free(m_pfQuery);
    m_iNumFeatures = 0;
    m_iNumObs = 0;
    m_pCClassifier = 0;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kNoError, m_bIsInitialized, m_iNumFeatures, m_iNumObs, m_pCClassifier, m_pfQuery, m_piClassLabels, and m_ppfTrain.
Referenced by init(), and ~CLeaveOneOutCrossVal().
Member Data Documentation
m_bIsInitialized
bool CLeaveOneOutCrossVal::m_bIsInitialized = false private
indicates if instance has been properly initialized
Definition at line 55 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
m_iNumFeatures
int CLeaveOneOutCrossVal::m_iNumFeatures = 0 private
number of features
Definition at line 44 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
m_iNumObs
int CLeaveOneOutCrossVal::m_iNumObs = 0 private
number of neighbors for classification
Definition at line 45 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
m_pCClassifier
CClassifierBase* CLeaveOneOutCrossVal::m_pCClassifier = 0 private
Definition at line 53 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
m_pfQuery
float* CLeaveOneOutCrossVal::m_pfQuery = 0 private
preallocated vector for the normalized query
Definition at line 49 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
m_piClassLabels
int* CLeaveOneOutCrossVal::m_piClassLabels = 0 private
Definition at line 51 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
m_ppfTrain
float** CLeaveOneOutCrossVal::m_ppfTrain = 0 private
train data (m_iNumObs X m_iNumFeatures)
Definition at line 47 of file ToolLeaveOneOutCrossVal.h.
Referenced by init(), process(), and reset().
The documentation for this class was generated from the following files:
ToolLeaveOneOutCrossVal.h
ToolLeaveOneOutCrossVal.cpp