ACA: CKeyFromChroma Class Reference
CKeyFromChroma Class Reference
computation of key profile distance
#include <KeyFromChroma.h>
Public Member Functions
CKeyFromChroma (void)
virtual ~CKeyFromChroma (void)
int getKey (const float *pfQuery)
Private Types
enum Modes_t { kMajor , kMinor , kNumModes }
enum Pitches_t {
kC , kCs , kD , kDs ,
kE , kF , kFs , kG ,
kGs , kA , kAs , kB ,
kNumPitchClasses
}
Private Member Functions
CKeyFromChroma (const CKeyFromChroma &that)
disallow copy construction
CKeyFromChroma & operator= (const CKeyFromChroma &c)
Private Attributes
const float m_aafKeyProfiles [kNumModes][kNumPitchClasses]
CRingBuffer< float > * m_apCRingBuff [kNumModes] = { 0 }
ringbuffer for cyclic shifting of the templates
Detailed Description
computation of key profile distance
Definition at line 13 of file KeyFromChroma.h.
Member Enumeration Documentation
Modes_t
enum CKeyFromChroma::Modes_t private
Enumerator
kMajor
kMinor
kNumModes
Definition at line 26 of file KeyFromChroma.h.
    {
        kMajor,
        kMinor,
        kNumModes
    };
Pitches_t
enum CKeyFromChroma::Pitches_t private
Enumerator
kC
kCs
kD
kDs
kE
kF
kFs
kG
kGs
kA
kAs
kB
kNumPitchClasses
Definition at line 33 of file KeyFromChroma.h.
    {
        kC,
        kCs,
        kD,
        kDs,
        kE,
        kF,
        kFs,
        kG,
        kGs,
        kA,
        kAs,
        kB,
        kNumPitchClasses
    };
Constructor & Destructor Documentation
CKeyFromChroma() [1/2]
CKeyFromChroma::CKeyFromChroma (void)
Definition at line 11 of file KeyFromChroma.cpp.
{
    // norm template key profiles
    for (auto m = 0; m < kNumModes; m++)
    {
        float fSum = CVector::getSum(m_aafKeyProfiles[m], kNumPitchClasses);
        m_apCRingBuff[m] = new CRingBuffer<float>(kNumPitchClasses);
        for (auto p = 0; p < kNumPitchClasses; p++)
            m_apCRingBuff[m]->putPostInc(m_aafKeyProfiles[m][p] / fSum);
    }
}
References CVector::getSum(), kNumModes, kNumPitchClasses, m_aafKeyProfiles, and m_apCRingBuff.
~CKeyFromChroma()
CKeyFromChroma::~CKeyFromChroma (void) virtual
Definition at line 25 of file KeyFromChroma.cpp.
{
    for (auto m = 0; m < kNumModes; m++)
        delete m_apCRingBuff[m];
}
References kNumModes, and m_apCRingBuff.
CKeyFromChroma() [2/2]
CKeyFromChroma::CKeyFromChroma (const CKeyFromChroma & that) private
disallow copy construction
Member Function Documentation
getKey()
int CKeyFromChroma::getKey (const float * pfQuery)
classifies a new query chroma vector
Returns
int index of most likely key
Definition at line 31 of file KeyFromChroma.cpp.
{
    long long iRes = -1;
    float afQueryN[kNumPitchClasses] = { 0 };
    float afDist[CKey::kNumKeys] = { 0 };
    float fNorm = CVector::getSum(pfQuery, kNumPitchClasses);
    if (fNorm <= 0)
        return CKey::kNoKey;
    // normalize input
    CVector::copy(afQueryN, pfQuery, kNumPitchClasses);
    CVector::mulC_I(afQueryN, 1.F / fNorm, kNumPitchClasses);
    // compute manhattan distances for modes (major and minor)
    for (auto m = 0; m < kNumModes; m++)
    {
        for (auto p = 0; p < kNumPitchClasses; p++)
        {
            float afShiftedChroma[kNumPitchClasses] = { 0 };
            m_apCRingBuff[m]->get(afShiftedChroma, kNumPitchClasses);
            afDist[m * kNumPitchClasses + p] = CVector::distManhattan(afQueryN, afShiftedChroma, kNumPitchClasses);
            m_apCRingBuff[m]->setReadIdx(m_apCRingBuff[m]->getReadIdx() - 1);
        }
    }
    // last distance
    CVector::addC_I(afQueryN, -1.F / kNumPitchClasses, kNumPitchClasses);
    afDist[CKey::kNoKey] = CVector::getSum(afQueryN, kNumPitchClasses, true);
    // get key index (reuse afQuery as dummy arg)
    CVector::findMin(afDist, afQueryN[0], iRes, CKey::kNumKeys);
    return static_cast<int>(iRes);
}
References CVector::addC_I(), CVector::copy(), CVector::distManhattan(), CVector::findMin(), CRingBuffer< T >::get(), CVector::getSum(), CKey::kNoKey, CKey::kNumKeys, kNumModes, kNumPitchClasses, m_apCRingBuff, CVector::mulC_I(), and CRingBuffer< T >::setReadIdx().
Referenced by CKey::compKey().
operator=()
CKeyFromChroma & CKeyFromChroma::operator= (const CKeyFromChroma & c) private
Member Data Documentation
m_aafKeyProfiles
const float CKeyFromChroma::m_aafKeyProfiles[kNumModes][kNumPitchClasses] private
Initial value:
= { {6.35F, 2.23F, 3.48F, 2.33F, 4.38F, 4.09F, 2.52F, 5.19F, 2.39F, 3.66F, 2.29F, 2.88F},
                                                                  {6.33F, 2.68F, 3.52F, 5.38F, 2.60F, 3.53F, 2.54F, 4.75F, 3.98F, 2.69F, 3.34F, 3.17F} }
Definition at line 53 of file KeyFromChroma.h.
Referenced by CKeyFromChroma().
m_apCRingBuff
CRingBuffer<float>* CKeyFromChroma::m_apCRingBuff[kNumModes] = { 0 } private
ringbuffer for cyclic shifting of the templates
Definition at line 56 of file KeyFromChroma.h.
Referenced by CKeyFromChroma(), getKey(), and ~CKeyFromChroma().
The documentation for this class was generated from the following files:
KeyFromChroma.h
KeyFromChroma.cpp