ACA: CGmmClassifier Class Reference
CGmmClassifier Class Reference
computation of k nearest neighbor
#include <ToolGmmClassifier.h>
Public Member Functions
CGmmClassifier (void)
virtual ~CGmmClassifier (void)
Error_t init (int iNumFeatures, int iNumObservations) override
Error_t train (const float *const *const ppfTrainFeatures, const int *piTrainClassIndices, CClassifierBase::Normalization_t eNorm=CClassifierBase::kNoNormalization) override
Error_t reset () override
Error_t setNumMixtures (int iK=3)
int getNumMixtures () const
int classify (const float *pfQuery) override
virtual Error_t init (int iNumFeatures, int iNumObs)=0
virtual Error_t train (const float *const *const ppfTrainFeatures, const int *piTrainClassIndices, Normalization_t eNorm=kNoNormalization)=0
virtual Error_t reset ()=0
virtual int classify (const float *pfQuery)=0
Private Member Functions
CGmmClassifier (const CGmmClassifier &that)
disallow copy construction
CGmmClassifier & operator= (const CGmmClassifier &c)
int countClasses (const int *piClassLabels)
Private Attributes
int m_iNumFeatures = 0
number of features
int m_iNumObs = 0
number of training observations
int m_iNumClasses = 0
number of classes in the data
int m_iK = 3
number of neighbors for classification
int * m_piClassLabels = 0
preallocated vector containing the unique set of classes
float * m_pfQuery = 0
preallocated vector for the normalized query
bool m_bIsInitialized = false
indicates if instance has been properly initialized
CGmmResult ** m_ppCGmmResult = 0
array holding the individual Gmm models (length m_iNumClasses)
Additional Inherited Members
Public Types inherited from CClassifierBase
enum Normalization_t { kNoNormalization , kZscoreNormalization , kMinmaxNormalization , kNumNormModes }
Static Public Attributes inherited from CClassifierBase
static const int kIllegalClassLabel = -1111111111
indicates something went wrong (this number should not be used as a class label)
Protected Member Functions inherited from CClassifierBase
virtual ~CClassifierBase ()
virtual void compNormConstants (const float *const *const ppfTrainFeatures, int iNumFeatures, int iNumObs, Normalization_t eNorm)
virtual void normalizeVector (float *pfQuery, int iNumFeatures)
Protected Attributes inherited from CClassifierBase
float * m_pfNormScale = 0
scaling constant for normalization (length m_iNumFeatures)
float * m_pfNormSub = 0
offset for normalization (length m_iNumFeatures)
Detailed Description
computation of k nearest neighbor
Definition at line 13 of file ToolGmmClassifier.h.
Constructor & Destructor Documentation
CGmmClassifier() [1/2]
CGmmClassifier::CGmmClassifier (void) inline
Definition at line 16 of file ToolGmmClassifier.h.
{};
~CGmmClassifier()
CGmmClassifier::~CGmmClassifier (void) virtual
Definition at line 7 of file ToolGmmClassifier.cpp.
{ reset(); }
References reset().
CGmmClassifier() [2/2]
CGmmClassifier::CGmmClassifier (const CGmmClassifier & that) private
disallow copy construction
Member Function Documentation
classify()
int CGmmClassifier::classify (const float * pfQuery) override virtual
classifies a new query vector
Parameters
pfQuery vector of length iNumFeatures to classify
Returns
int class label of most likely class (returns CClassifierBase::kIllegalClassLabel in case of error)
Implements CClassifierBase.
Definition at line 135 of file ToolGmmClassifier.cpp.
{
    if (!pfQuery || !m_bIsInitialized)
        return kIllegalClassLabel;
    // normalize
    CVector::copy(m_pfQuery, pfQuery, m_iNumFeatures);
    normalizeVector(m_pfQuery, m_iNumFeatures);
    // check which Gmm gives us the highest value
    float fMax = -1;
    int iIdx = kIllegalClassLabel;
    for (auto c = 0; c < m_iNumClasses; c++)
    {
        float fProb = m_ppCGmmResult[c]->getProb(pfQuery);
        if (fProb > fMax)
        {
            fMax = fProb;
            iIdx = c;
        }
    }
    if (iIdx == kIllegalClassLabel)
        return kIllegalClassLabel;
    else
        return iIdx;
}
References CVector::copy(), CGmmResult::getProb(), CClassifierBase::kIllegalClassLabel, m_bIsInitialized, m_iNumClasses, m_iNumFeatures, m_pfQuery, m_ppCGmmResult, and CClassifierBase::normalizeVector().
countClasses()
int CGmmClassifier::countClasses (const int * piClassLabels) private
counts the number of unique classes in piClassLabels
Parameters
piClassLabels vector containing int class labels
Returns
int number of classes
Definition at line 164 of file ToolGmmClassifier.cpp.
{
    m_iNumClasses = 1;
    m_piClassLabels[0] = piClassLabels[0];
    for (auto n = 1; n < m_iNumObs; n++)
    {
        int i = 0;
        while (i < m_iNumClasses)
        {
            // if it's in list go to next labels
            if (piClassLabels[n] == m_piClassLabels[i])
                break;
            i++;
        }
        // if we haven't found it, add it to the class list
        if (i == m_iNumClasses)
        {
            m_piClassLabels[m_iNumClasses] = piClassLabels[n];
            m_iNumClasses++;
        }
    }
    return m_iNumClasses;
}
References m_iNumClasses, m_iNumObs, and m_piClassLabels.
Referenced by train().
getNumMixtures()
int CGmmClassifier::getNumMixtures () const
returns the number of Gaussians per class
Returns
int
Definition at line 129 of file ToolGmmClassifier.cpp.
{
    return m_iK;
}
References m_iK.
init()
Error_t CGmmClassifier::init (int iNumFeatures, int iNumObservations) override virtual
initializes GmmClassifier instance
Parameters
iNumFeatures number of features (rows in the input matrix)
iNumObservations number of observations (columns in the feature matrix)
Returns
Error_t
Implements CClassifierBase.
Definition at line 9 of file ToolGmmClassifier.cpp.
{
    if (iNumFeatures <= 0 || iNumObs < 1)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    m_iNumFeatures = iNumFeatures;
    m_iNumObs = iNumObs;
    // worst case: number of classes equals number of observations
    CVector::alloc(m_piClassLabels, m_iNumObs);
    CVector::alloc(m_pfNormScale, m_iNumFeatures);
    CVector::alloc(m_pfNormSub, m_iNumFeatures);
    CVector::alloc(m_pfQuery, m_iNumFeatures);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iNumFeatures, m_iNumObs, CClassifierBase::m_pfNormScale, CClassifierBase::m_pfNormSub, m_pfQuery, m_piClassLabels, and reset().
operator=()
CGmmClassifier & CGmmClassifier::operator= (const CGmmClassifier & c) private
reset()
Error_t CGmmClassifier::reset () override virtual
resets GmmClassifier instance
Returns
Error_t
Implements CClassifierBase.
Definition at line 92 of file ToolGmmClassifier.cpp.
{
    m_bIsInitialized = false;
    CVector::free(m_piClassLabels);
    CVector::free(m_pfQuery);
    for (auto c = 0; c < m_iNumClasses; c++)
        delete m_ppCGmmResult[c];
    CVector::free(m_ppCGmmResult);
    CVector::free(m_pfNormScale);
    CVector::free(m_pfNormSub);
    m_iNumClasses = 0;
    m_iNumFeatures = 0;
    m_iNumObs = 0;
    return Error_t::kNoError;
}
References CVector::free(), kNoError, m_bIsInitialized, m_iNumClasses, m_iNumFeatures, m_iNumObs, CClassifierBase::m_pfNormScale, CClassifierBase::m_pfNormSub, m_pfQuery, m_piClassLabels, and m_ppCGmmResult.
Referenced by init(), setNumMixtures(), and ~CGmmClassifier().
setNumMixtures()
Error_t CGmmClassifier::setNumMixtures (int iK = 3)
sets the number of Gaussians per class
Parameters
iK number of Gaussians
Returns
Error_t
Definition at line 114 of file ToolGmmClassifier.cpp.
{
    if (iK < 1)
        return Error_t::kFunctionInvalidArgsError;
    if (m_iK != iK)
    {
        reset();
        m_iK = iK;
    }
    return Error_t::kNoError;
}
References kFunctionInvalidArgsError, kNoError, m_iK, and reset().
train()
Error_t CGmmClassifier::train (const float *const *const ppfTrainFeatures, const int * piTrainClassIndices, CClassifierBase::Normalization_t eNorm = CClassifierBase::kNoNormalization) override virtual
trains a GmmClassifier instance
Parameters
ppfTrainFeatures feature data for 'training' (dimensions iNumFeatures X iNumObservations)
piTrainClassIndices ground truth class index for each observation
eNorm specification of what normalization should be applied to the feature data
Returns
Error_t
Implements CClassifierBase.
Definition at line 32 of file ToolGmmClassifier.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!ppfTrainFeatures || !piTrainClassIndices)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfTrainFeatures[0])
        return Error_t::kFunctionInvalidArgsError;
    float **ppfTrain = 0;
    CGmm Gmm;
    // alloc temp train data matrix
    CMatrix::alloc(ppfTrain, m_iNumFeatures, m_iNumObs);
    // get number of classes
    m_iNumClasses = countClasses(piTrainClassIndices);
    // allocate GMM stuff but keep result for later (avoid mem leaks when repeatedly calling train)
    if (m_ppCGmmResult)
    {
        for (auto c = 0; c < m_iNumClasses; c++)
            delete m_ppCGmmResult[c];
        CVector::free(m_ppCGmmResult);
    }
    CVector::alloc(m_ppCGmmResult, m_iNumClasses);
    // normalize features and train GMM per class
    compNormConstants(ppfTrainFeatures, m_iNumFeatures, m_iNumObs, eNorm);
    for (auto c = 0; c < m_iNumClasses; c++)
    {
        Gmm.reset();
        int iNumClassObs = 0;
        for (auto n = 0; n < m_iNumObs; n++)
        {
            // add class-specific observations to the train matrix
            if (piTrainClassIndices[n] == m_piClassLabels[c])
            {
                CMatrix::getCol(m_pfQuery, ppfTrainFeatures, n, m_iNumFeatures);
                normalizeVector(m_pfQuery, m_iNumFeatures);
                CMatrix::setCol(ppfTrain, m_pfQuery, iNumClassObs, m_iNumFeatures);
                iNumClassObs++;
            }
        }
        // train
        m_ppCGmmResult[c] = new CGmmResult();
        Gmm.init(m_ppCGmmResult[c], m_iK, m_iNumFeatures, iNumClassObs);
        Gmm.compGmm(m_ppCGmmResult[c], ppfTrain);
    }
    // clean up
    CMatrix::free(ppfTrain, m_iNumFeatures);
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), CGmm::compGmm(), CClassifierBase::compNormConstants(), countClasses(), CVector::free(), CMatrix::free(), CMatrix::getCol(), CGmm::init(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iK, m_iNumClasses, m_iNumFeatures, m_iNumObs, m_pfQuery, m_piClassLabels, m_ppCGmmResult, CClassifierBase::normalizeVector(), CGmm::reset(), and CMatrix::setCol().
Member Data Documentation
m_bIsInitialized
bool CGmmClassifier::m_bIsInitialized = false private
indicates if instance has been properly initialized
Definition at line 77 of file ToolGmmClassifier.h.
Referenced by classify(), init(), reset(), and train().
m_iK
int CGmmClassifier::m_iK = 3 private
number of neighbors for classification
Definition at line 72 of file ToolGmmClassifier.h.
Referenced by getNumMixtures(), setNumMixtures(), and train().
m_iNumClasses
int CGmmClassifier::m_iNumClasses = 0 private
number of classes in the data
Definition at line 71 of file ToolGmmClassifier.h.
Referenced by classify(), countClasses(), reset(), and train().
m_iNumFeatures
int CGmmClassifier::m_iNumFeatures = 0 private
number of features
Definition at line 69 of file ToolGmmClassifier.h.
Referenced by classify(), init(), reset(), and train().
m_iNumObs
int CGmmClassifier::m_iNumObs = 0 private
number of training observations
Definition at line 70 of file ToolGmmClassifier.h.
Referenced by countClasses(), init(), reset(), and train().
m_pfQuery
float* CGmmClassifier::m_pfQuery = 0 private
preallocated vector for the normalized query
Definition at line 75 of file ToolGmmClassifier.h.
Referenced by classify(), init(), reset(), and train().
m_piClassLabels
int* CGmmClassifier::m_piClassLabels = 0 private
preallocated vector containing the unique set of classes
Definition at line 74 of file ToolGmmClassifier.h.
Referenced by countClasses(), init(), reset(), and train().
m_ppCGmmResult
CGmmResult** CGmmClassifier::m_ppCGmmResult = 0 private
array holding the individual Gmm models (length m_iNumClasses)
Definition at line 79 of file ToolGmmClassifier.h.
Referenced by classify(), reset(), and train().
The documentation for this class was generated from the following files:
ToolGmmClassifier.h
ToolGmmClassifier.cpp