ACA: CCcf Class Reference
CCcf Class Reference
computation of correlation (freq domain)
#include <ToolCcf.h>
Public Member Functions
CCcf (void)
virtual ~CCcf (void)
Error_t init (int iBlockLength)
Error_t reset ()
Error_t compCcf (const float *pfInput1, const float *pfInput2, bool bNormalize=true)
int getCcfLength (bool bisAcf=false)
Error_t getCcf (float *pfCcfResult, bool bisAcf=false) const
float getCcfMax (bool bisAcf=false) const
int getCcfMaxIdx (bool bisAcf=false) const
Private Member Functions
CCcf (const CCcf &that)
disallow copy construction
CCcf & operator= (const CCcf &c)
Private Attributes
bool m_bIsInitialized = false
true if init has been called
bool m_bWasProcessed = false
true if process has been called
float * m_apfData [2] = { 0,0 }
CCF result.
CFft * m_pCFft = 0
FFT instance.
int m_iBlockLength = 0
length of input
int m_iFftLength = 0
length of FFT
Detailed Description
computation of correlation (freq domain)
Definition at line 13 of file ToolCcf.h.
Constructor & Destructor Documentation
CCcf() [1/2]
CCcf::CCcf (void)
Definition at line 8 of file ToolCcf.cpp.
{
    m_pCFft = new CFft();
}
References m_pCFft.
~CCcf()
CCcf::~CCcf (void) virtual
Definition at line 13 of file ToolCcf.cpp.
{
    reset();
    delete m_pCFft;
}
References m_pCFft, and reset().
CCcf() [2/2]
CCcf::CCcf (const CCcf & that) private
disallow copy construction
Member Function Documentation
compCcf()
Error_t CCcf::compCcf (const float * pfInput1, const float * pfInput2, bool bNormalize = true)
computes cross correlation function
Parameters
pfInput1 (block of data to be correlated)
pfInput2 (block of data to be correlated, equals pfInput1 when ACF)
bNormalize flag whether the output is normalized
Returns
Error_t
Definition at line 62 of file ToolCcf.cpp.
{
    if (!pfInput1 || !pfInput2)
        return Error_t::kFunctionInvalidArgsError;
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    // extract standard deviation for normalization
    float afStd[2] = { 1.F, 1.F };
    if (bNormalize)
    {
        float fPower = std::sqrt(CVector::mulScalar(pfInput1, pfInput1, m_iBlockLength));
        afStd[0] = fPower > 0 ? fPower : 1.F;
        fPower = std::sqrt(CVector::mulScalar(pfInput2, pfInput2, m_iBlockLength));
        afStd[1] = fPower > 0 ? fPower : 1.F;
    }
    // compute the FFTs
    m_pCFft->compFft(m_apfData[0], pfInput1);
    m_pCFft->compFft(m_apfData[1], pfInput2);
    // conjugate complex multiply
    CVector::mulC_I(m_apfData[1], static_cast<float>(m_iFftLength), m_iFftLength);
    m_pCFft->conjugate_I(m_apfData[1]);
    m_pCFft->multiply_I(m_apfData[0], m_apfData[1]);
    // normalization
    CVector::mulC_I(m_apfData[0], 1.F / (afStd[0] * afStd[1]), m_iFftLength);
    // inverse Fft
    m_pCFft->compInvFft(m_apfData[0], m_apfData[0]);
    // copy results
    CVector::copy(m_apfData[1], &m_apfData[0][static_cast<long long>(m_iFftLength) - m_iBlockLength + 1], static_cast<long long>(m_iBlockLength) - 1);
    CVector::copy(&m_apfData[1][m_iBlockLength - 1], m_apfData[0], m_iBlockLength);
    m_bWasProcessed = true;
    return Error_t::kNoError;
}
References CFft::compFft(), CFft::compInvFft(), CFft::conjugate_I(), CVector::copy(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_apfData, m_bIsInitialized, m_bWasProcessed, m_iBlockLength, m_iFftLength, m_pCFft, CVector::mulC_I(), CVector::mulScalar(), and CFft::multiply_I().
Referenced by CBeatHistoIf::compBeatHisto(), CPitchSpectralAcf::compF0(), CPitchTimeAcf::compF0(), CPitchTimeAuditory::compF0(), and CFeatureTimeMaxAcf::compFeature().
getCcf()
Error_t CCcf::getCcf (float * pfCcfResult, bool bisAcf = false) const
returns the correlation result
Parameters
pfCcfResult result buffer
bisAcf returns only non-redundant ACF result if true
Returns
Error_t
Definition at line 111 of file ToolCcf.cpp.
{
    if (!(m_bIsInitialized && m_bWasProcessed))
        return Error_t::kFunctionIllegalCallError;
    if (!pfCcfResult)
        return Error_t::kFunctionInvalidArgsError;
    int iStartIdx = bIsAcf ? m_iBlockLength - 1 : 0;
    CVector::copy(pfCcfResult, &m_apfData[1][iStartIdx], static_cast<long long>(2) * m_iBlockLength - 1 - iStartIdx);
    return Error_t::kNoError;
}
References CVector::copy(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_apfData, m_bIsInitialized, m_bWasProcessed, and m_iBlockLength.
Referenced by CBeatHistoIf::compBeatHisto(), CPitchSpectralAcf::compF0(), CPitchTimeAcf::compF0(), CPitchTimeAuditory::compF0(), and CFeatureTimeMaxAcf::compFeature().
getCcfLength()
int CCcf::getCcfLength (bool bisAcf = false)
returns the length of the CCF result
Returns
int
Definition at line 103 of file ToolCcf.cpp.
{
    if (!m_bIsInitialized)
        return -1;
    return bIsAcf ? m_iBlockLength : 2 * m_iBlockLength - 1;
}
References m_bIsInitialized, and m_iBlockLength.
Referenced by CFeatureTimeMaxAcf::CFeatureTimeMaxAcf(), CPitchSpectralAcf::CPitchSpectralAcf(), CPitchTimeAcf::CPitchTimeAcf(), and CPitchTimeAuditory::CPitchTimeAuditory().
getCcfMax()
float CCcf::getCcfMax (bool bisAcf = false) const
returns the overall max
Parameters
bisAcf search only non-redundant ACF result if true
Returns
float
Definition at line 124 of file ToolCcf.cpp.
{
    if (!(m_bIsInitialized && m_bWasProcessed))
        return -1.F;
    int iStartIdx = bIsAcf ? m_iBlockLength - 1 : 0;
    return CVector::getMax(&m_apfData[1][iStartIdx], static_cast<long long>(2) * m_iBlockLength - 1 - iStartIdx);
}
References CVector::getMax(), m_apfData, m_bIsInitialized, m_bWasProcessed, and m_iBlockLength.
getCcfMaxIdx()
int CCcf::getCcfMaxIdx (bool bisAcf = false) const
returns the index of the overall max
Parameters
bisAcf search only non-redundant ACF result if true
Returns
float
Definition at line 133 of file ToolCcf.cpp.
{
    if (!(m_bIsInitialized && m_bWasProcessed))
        return -1;
    float fMax = -1.F;
    long long iMax = -1;
    int iStartIdx = bIsAcf ? m_iBlockLength - 1 : 0;
    CVector::findMax(&m_apfData[1][iStartIdx], fMax, iMax, static_cast<long long>(2) * m_iBlockLength - 1 - iStartIdx);
    return static_cast<int>(iMax);
}
References CVector::findMax(), m_apfData, m_bIsInitialized, m_bWasProcessed, and m_iBlockLength.
init()
Error_t CCcf::init (int iBlockLength)
initializes the class with the size of the distance matrix
Parameters
iBlockLength
Returns
Error_t
Definition at line 20 of file ToolCcf.cpp.
{
    if (iBlockLength <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (m_bIsInitialized)
        reset();
    m_iBlockLength = iBlockLength;
    if (CUtil::isPowOf2(m_iBlockLength))
        m_iFftLength = 2 * m_iBlockLength;
    else
        m_iFftLength = CUtil::nextPowOf2(2*iBlockLength);
    m_pCFft->init(m_iBlockLength, 2, CFft::kWindowHann, CFft::kNoWindow);
    for (auto j = 0; j < 2; j++)
        CVector::alloc(m_apfData[j], m_iFftLength);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CFft::init(), CUtil::isPowOf2(), kFunctionInvalidArgsError, kNoError, CFft::kNoWindow, CFft::kWindowHann, m_apfData, m_bIsInitialized, m_iBlockLength, m_iFftLength, m_pCFft, CUtil::nextPowOf2(), and reset().
Referenced by CFeatureTimeMaxAcf::CFeatureTimeMaxAcf(), CBeatHistoIf::compBeatHisto(), CPitchSpectralAcf::CPitchSpectralAcf(), CPitchTimeAcf::CPitchTimeAcf(), and CPitchTimeAuditory::CPitchTimeAuditory().
operator=()
CCcf & CCcf::operator= (const CCcf & c) private
reset()
Error_t CCcf::reset ()
resets all internal class members
Returns
Error_t
Definition at line 44 of file ToolCcf.cpp.
{
    m_bWasProcessed = false;
    m_bIsInitialized = false;
    m_pCFft->reset();
    for (auto j = 0; j < 2; j++)
    {
        CVector::free(m_apfData[j]);
    }
    m_iFftLength = 0;
    m_iBlockLength = 0;
    return Error_t::kNoError;
}
References CVector::free(), kNoError, m_apfData, m_bIsInitialized, m_bWasProcessed, m_iBlockLength, m_iFftLength, m_pCFft, and CFft::reset().
Referenced by init(), and ~CCcf().
Member Data Documentation
m_apfData
float* CCcf::m_apfData[2] = { 0,0 } private
CCF result.
Definition at line 70 of file ToolCcf.h.
Referenced by compCcf(), getCcf(), getCcfMax(), getCcfMaxIdx(), init(), and reset().
m_bIsInitialized
bool CCcf::m_bIsInitialized = false private
true if init has been called
Definition at line 67 of file ToolCcf.h.
Referenced by compCcf(), getCcf(), getCcfLength(), getCcfMax(), getCcfMaxIdx(), init(), and reset().
m_bWasProcessed
bool CCcf::m_bWasProcessed = false private
true if process has been called
Definition at line 68 of file ToolCcf.h.
Referenced by compCcf(), getCcf(), getCcfMax(), getCcfMaxIdx(), and reset().
m_iBlockLength
int CCcf::m_iBlockLength = 0 private
length of input
Definition at line 73 of file ToolCcf.h.
Referenced by compCcf(), getCcf(), getCcfLength(), getCcfMax(), getCcfMaxIdx(), init(), and reset().
m_iFftLength
int CCcf::m_iFftLength = 0 private
length of FFT
Definition at line 74 of file ToolCcf.h.
Referenced by compCcf(), init(), and reset().
m_pCFft
CFft* CCcf::m_pCFft = 0 private
FFT instance.
Definition at line 71 of file ToolCcf.h.
Referenced by CCcf(), compCcf(), init(), reset(), and ~CCcf().
The documentation for this class was generated from the following files:
ToolCcf.h
ToolCcf.cpp