ACA: CNoveltyIf Class Reference
CNoveltyIf Class Reference
class for computation of a magnitude Novelty from either a file or a vector
#include <Novelty.h>
Public Types
enum Novelty_t { kNoveltyFlux , kNoveltyHainsworth , kNoveltyLaroche , kNumNoveltyFunctions }
enum to index all Noveltys note: update CNoveltyIf::isNoveltySpectral_() when modifying
Public Member Functions
Error_t getNumBlocks (int &iNumBlocks) const
int getNumBlocks () const
float getTimeStamp (int iBlockIdx) const
Error_t getTimeStamps (float *pfAxisTicks) const
Error_t compNovelty (float *pfNovelty, bool *pbisOnset=0)
Static Public Member Functions
static Error_t create (CNoveltyIf *&pCInstance, Novelty_t eNoveltyIdx, const std::string &strAudioFilePath, int iBlockLength=4096, int iHopLength=512)
static Error_t create (CNoveltyIf *&pCInstance, Novelty_t eNoveltyIdx, const float *pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength=4096, int iHopLength=512)
static Error_t destroy (CNoveltyIf *&pCInstance)
static std::string getNoveltyString (Novelty_t eNoveltyIdx)
static Novelty_t getNoveltyIdxFromString (std::string sNoveltyString)
Protected Member Functions
CNoveltyIf ()
virtual ~CNoveltyIf ()
CNoveltyIf (const CNoveltyIf &that)
CNoveltyIf & operator= (const CNoveltyIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ (Novelty_t eNoveltyIdx)
init configuration
void computeMagSpectrum_ ()
Protected Attributes
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CNoveltyFromBlockIf * m_pCNovelty = 0
instance for instantaneous novelty extraction
CFft * m_pCFft = 0
fft instance
CMovingAverage * m_pCLpFilter = 0
smoothing filter handle
int m_iBlockLength = 0
fft length
int m_iHopLength = 0
hop length
float m_fSampleRate = 0
sample rate
float * m_pfProcBuff2 = 0
temporary buffer for current spectrum
float * m_pfProcBuff1 = 0
temporary buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a magnitude Novelty from either a file or a vector
Definition at line 18 of file Novelty.h.
Member Enumeration Documentation
Novelty_t
enum CNoveltyIf::Novelty_t
enum to index all Noveltys note: update CNoveltyIf::isNoveltySpectral_() when modifying
Enumerator
kNoveltyFlux
kNoveltyHainsworth
kNoveltyLaroche
kNumNoveltyFunctions
Definition at line 24 of file Novelty.h.
    {
        kNoveltyFlux,
        kNoveltyHainsworth,
        kNoveltyLaroche,
        kNumNoveltyFunctions
    };
Constructor & Destructor Documentation
CNoveltyIf() [1/2]
CNoveltyIf::CNoveltyIf () protected
Definition at line 88 of file Novelty.cpp.
{
    reset_();
}
References reset_().
~CNoveltyIf()
CNoveltyIf::~CNoveltyIf () inline protected virtual
Definition at line 93 of file Novelty.cpp.
{
    reset_();
}
References reset_().
CNoveltyIf() [2/2]
CNoveltyIf::CNoveltyIf (const CNoveltyIf & that) protected
Member Function Documentation
compNovelty()
Error_t CNoveltyIf::compNovelty (float * pfNovelty, bool * pbisOnset = 0)
performs the Novelty computation for 1 dimensional Noveltys and writes the result
Parameters
pfNovelty (user-allocated, to be written, dimensions from CNoveltyIf::getNumBlocks)
pbisOnset (user-allocated, to be written, true if onset)
Returns
Error_t
< adaptive threshold - memory allocation is ok since we compDtw the whole signal at once anyway
Definition at line 186 of file Novelty.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!pfNovelty)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_pfProcBuff1);
    assert(m_pfProcBuff2);
    assert(m_pCFft);
    assert(m_pCBlockAudio);
    assert(m_pCNormalize);
    assert(m_pCNovelty);
    const float fSmoothLpLenInS = 0.07F;
    const float fThreshLpLenInS = 0.14F;
    auto iNumBlocks = m_pCBlockAudio->getNumBlocks();
    float *pfThreshold = 0; //!< adaptive threshold - memory allocation is ok since we compDtw the whole signal at once anyway
    CVector::alloc(pfThreshold, iNumBlocks);
    for (auto n = 0; n < iNumBlocks; n++)
    {
        // retrieve the next audio block
        m_pCBlockAudio->getNextBlock(m_pfProcBuff1);
        // normalize if specified
        if (m_pCNormalize)
            m_pCNormalize->normalizeBlock(m_pfProcBuff1, m_iBlockLength);
        // compute spectrum
        computeMagSpectrum_();
        // extract novelty for this block
        m_pCNovelty->compNovelty(&pfNovelty[n], m_pfProcBuff1);
    }
    // normalize
    float fMax = CVector::getMax(pfNovelty, iNumBlocks, true);
    if (fMax > 0)
        CVector::mulC_I(pfNovelty, 1 / fMax, iNumBlocks);
    // smoothing with moving average
    m_pCLpFilter->reset();
    m_pCLpFilter->setFilterParam(m_pCLpFilter->calcFilterLength(fSmoothLpLenInS, m_fSampleRate / m_iHopLength));
    m_pCLpFilter->filtfilt(pfNovelty, pfNovelty, iNumBlocks);
    // HWR
    CVector::setZeroBelowThresh(pfNovelty, iNumBlocks, 0.F);
    // threshold computation
    m_pCLpFilter->reset();
    m_pCLpFilter->setFilterParam(m_pCLpFilter->calcFilterLength(fThreshLpLenInS, m_fSampleRate / m_iHopLength));
    m_pCLpFilter->filtfilt(pfThreshold, pfNovelty, iNumBlocks);
    CVector::addC_I(pfThreshold, .4F * CVector::getMean(&pfNovelty[1], iNumBlocks - 1), iNumBlocks);
    CVector::sub_I(pfThreshold, pfNovelty, iNumBlocks);
    CVector::mulC_I(pfThreshold, -1.F, iNumBlocks);
    CVector::setZeroBelowThresh(pfThreshold, iNumBlocks, 0.F);
    // peak picking
    if (pbIsOnset)
    {
        CVector::setValue(pbIsOnset, false, iNumBlocks);
        CVector::findPeaks(pbIsOnset, pfThreshold, iNumBlocks, 0.F);
    }
    // clean up memory
    CVector::free(pfThreshold);
    return Error_t::kNoError;
}
References CVector::addC_I(), CVector::alloc(), CMovingAverage::calcFilterLength(), CNoveltyFromBlockIf::compNovelty(), computeMagSpectrum_(), CMovingAverage::filtfilt(), CVector::findPeaks(), CVector::free(), CVector::getMax(), CVector::getMean(), CBlockAudioIf::getNextBlock(), CBlockAudioIf::getNumBlocks(), m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, m_pCBlockAudio, m_pCFft, m_pCLpFilter, m_pCNormalize, m_pCNovelty, m_pfProcBuff1, m_pfProcBuff2, CVector::mulC_I(), CNormalizeAudio::normalizeBlock(), CMovingAverage::reset(), CMovingAverage::setFilterParam(), CVector::setValue(), CVector::setZeroBelowThresh(), and CVector::sub_I().
Referenced by CBeatHistoIf::compBeatHisto(), and main().
computeMagSpectrum_()
void CNoveltyIf::computeMagSpectrum_ () protected
Definition at line 286 of file Novelty.cpp.
{
    assert(m_pCFft);
    // compute magnitude spectrum
    m_pCFft->compFft(m_pfProcBuff2, m_pfProcBuff1);
    m_pCFft->getMagnitude(m_pfProcBuff1, m_pfProcBuff2);
    CVector::mulC_I(m_pfProcBuff1, 2.F, m_pCFft->getLength(CFft::kLengthMagnitude));
}
References CFft::compFft(), CFft::getLength(), CFft::getMagnitude(), CFft::kLengthMagnitude, m_pCFft, m_pfProcBuff1, m_pfProcBuff2, and CVector::mulC_I().
Referenced by compNovelty().
create() [1/2]
Error_t CNoveltyIf::create (CNoveltyIf *& pCInstance, Novelty_t eNoveltyIdx, const float * pfAudio, long long iNumSamples, float fSampleRate, int iBlockLength = 4096, int iHopLength = 512) static
initializes a Novelty instance from audio data
Parameters
pCInstance pointer to instance to be written
eNoveltyIdx as defined in Novelty_t
pfAudio complete audio data
iNumSamples length of pfAudio
fSampleRate sample rate in Hz
iBlockLength FFT block length in samples
iHopLength hop length in samples
Returns
Error_t
Definition at line 113 of file Novelty.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumSamples <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2)
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CNoveltyFromVector(eNoveltyIdx, pfAudio, iNumSamples, fSampleRate, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
create() [2/2]
Error_t CNoveltyIf::create (CNoveltyIf *& pCInstance, Novelty_t eNoveltyIdx, const std::string & strAudioFilePath, int iBlockLength = 4096, int iHopLength = 512) static
initializes a Novelty instance with file reading
Parameters
pCInstance pointer to instance to be written
eNoveltyIdx as defined in Novelty_t
strAudioFilePath complete path to audio file
iBlockLength FFT block length in samples
iHopLength hop length in samples
Returns
Error_t
Definition at line 98 of file Novelty.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iBlockLength <= 2 || !CUtil::isPowOf2(iBlockLength))
        return Error_t::kFunctionInvalidArgsError;
    if (iHopLength <= 0 || iHopLength > iBlockLength)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CNoveltyFromFile(eNoveltyIdx, strAudioFilePath, iBlockLength, iHopLength);
    return Error_t::kNoError;
}
References CUtil::isPowOf2().
Referenced by CBeatHistoIf::init_(), and main().
destroy()
Error_t CNoveltyIf::destroy (CNoveltyIf *& pCInstance) static
destroys a Novelty instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 131 of file Novelty.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
Referenced by main(), and CBeatHistoIf::reset_().
getNoveltyIdxFromString()
CNoveltyIf::Novelty_t CNoveltyIf::getNoveltyIdxFromString (std::string sNoveltyString) static
returns Novelty index from string
Parameters
sNoveltyString string describing the Novelty
Returns
Novelty_t
Definition at line 271 of file Novelty.cpp.
{
    const std::map<std::string, CNoveltyIf::Novelty_t> NoveltyMap
    {
            {"Flux", kNoveltyFlux},
            {"Hainsworth", kNoveltyHainsworth},
            {"Laroche", kNoveltyLaroche}
    };
    auto search = NoveltyMap.find(sNoveltyString);
    if (search != NoveltyMap.end())
        return NoveltyMap.at(sNoveltyString);
    else
        return kNumNoveltyFunctions;
}
References kNoveltyFlux, kNoveltyHainsworth, kNoveltyLaroche, and kNumNoveltyFunctions.
Referenced by main().
getNoveltyString()
std::string CNoveltyIf::getNoveltyString (Novelty_t eNoveltyIdx) static
returns Novelty name as string
Parameters
eNoveltyIdx Novelty index
Returns
std::string
Definition at line 259 of file Novelty.cpp.
{
    const std::map<CNoveltyIf::Novelty_t, std::string> NoveltyMap
    {
            {kNoveltyFlux, "Flux"},
            {kNoveltyHainsworth, "Hainsworth"},
            {kNoveltyLaroche, "Laroche"}
    };
    return NoveltyMap.at(eNoveltyIdx);
}
References kNoveltyFlux, kNoveltyHainsworth, and kNoveltyLaroche.
getNumBlocks() [1/2]
int CNoveltyIf::getNumBlocks () const
returns size of matrix to be allocated by user
Returns
int
Definition at line 152 of file Novelty.cpp.
{
    assert(m_bIsInitialized);
    assert(m_pCBlockAudio);
    return static_cast<int>(m_pCBlockAudio->getNumBlocks());
}
References CBlockAudioIf::getNumBlocks(), m_bIsInitialized, and m_pCBlockAudio.
Referenced by getNumBlocks().
getNumBlocks() [2/2]
Error_t CNoveltyIf::getNumBlocks (int & iNumBlocks) const
returns size of matrix to be allocated by user
Parameters
iNumBlocks (number of blocks, to be written) equals number of hops
Returns
Error_t
Definition at line 139 of file Novelty.cpp.
{
    if (!m_bIsInitialized)
    {
        iNumBlocks = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumBlocks = this->getNumBlocks();
    return Error_t::kNoError;
}
References getNumBlocks(), and m_bIsInitialized.
Referenced by CBeatHistoIf::compBeatHisto(), CBeatHistoIf::init_(), and main().
getTimeStamp()
float CNoveltyIf::getTimeStamp (int iBlockIdx) const
returns time stamps
Parameters
iBlockIdx index of block
Returns
float time stamp
Definition at line 160 of file Novelty.cpp.
{
    return m_pCBlockAudio->getTimeStamp(iBlockIdx);
}
References CBlockAudioIf::getTimeStamp(), and m_pCBlockAudio.
Referenced by main().
getTimeStamps()
Error_t CNoveltyIf::getTimeStamps (float * pfAxisTicks) const
returns time stamps
Parameters
pfAxisTicks (user- allocated, to be written) length iNumBlocks
Returns
Error_t
Definition at line 165 of file Novelty.cpp.
{
    if (!m_bIsInitialized)
    {
        return Error_t::kFunctionIllegalCallError;
    }
    if (!pfAxisTicks)
        return Error_t::kFunctionInvalidArgsError;
    assert(m_iBlockLength > 0);
    assert(m_iHopLength > 0);
    assert(m_fSampleRate > 0);
    long long iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
        pfAxisTicks[n] = m_pCBlockAudio->getTimeStamp(n);
    return Error_t::kNoError;
}
References CBlockAudioIf::getNumBlocks(), CBlockAudioIf::getTimeStamp(), m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_iHopLength, and m_pCBlockAudio.
Referenced by CBeatHistoIf::init_().
init_()
Error_t CNoveltyIf::init_ (Novelty_t eNoveltyIdx) protected
init configuration
Definition at line 323 of file Novelty.cpp.
{
    // initialize FFT and fft  buffer
    m_pCFft = new CFft();
    m_pCFft->init(m_iBlockLength);
    // allocate processing memory
    CVector::alloc(m_pfProcBuff1, m_pCFft->getLength(CFft::kLengthFft));
    CVector::alloc(m_pfProcBuff2, m_pCFft->getLength(CFft::kLengthFft));
    CNoveltyFromBlockIf::create(m_pCNovelty, eNoveltyIdx, m_pCFft->getLength(CFft::kLengthMagnitude), m_fSampleRate);
    CMovingAverage::create(m_pCLpFilter);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMovingAverage::create(), CNoveltyFromBlockIf::create(), CFft::getLength(), CFft::init(), CFft::kLengthFft, CFft::kLengthMagnitude, m_bIsInitialized, m_fSampleRate, m_iBlockLength, m_pCFft, m_pCLpFilter, m_pCNovelty, m_pfProcBuff1, and m_pfProcBuff2.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), and CNoveltyFromVector::CNoveltyFromVector().
operator=()
CNoveltyIf & CNoveltyIf::operator= (const CNoveltyIf & c) protected
reset_()
Error_t CNoveltyIf::reset_ () protected
reset configuration
Definition at line 298 of file Novelty.cpp.
{
    CVector::free(m_pfProcBuff1);
    CVector::free(m_pfProcBuff2);
    delete m_pCFft;
    m_pCFft = 0;
    delete m_pCNormalize;
    m_pCNormalize = 0;
    CBlockAudioIf::destroy(m_pCBlockAudio);
    CNoveltyFromBlockIf::destroy(m_pCNovelty);
    m_iBlockLength = 0;
    m_iHopLength = 0;
    CMovingAverage::destroy(m_pCLpFilter);
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CBlockAudioIf::destroy(), CMovingAverage::destroy(), CNoveltyFromBlockIf::destroy(), CVector::free(), m_bIsInitialized, m_iBlockLength, m_iHopLength, m_pCBlockAudio, m_pCFft, m_pCLpFilter, m_pCNormalize, m_pCNovelty, m_pfProcBuff1, and m_pfProcBuff2.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), CNoveltyIf(), and ~CNoveltyIf().
Member Data Documentation
m_bIsInitialized
bool CNoveltyIf::m_bIsInitialized = false protected
true if initialized
Definition at line 131 of file Novelty.h.
Referenced by compNovelty(), getNumBlocks(), getTimeStamps(), init_(), and reset_().
m_fSampleRate
float CNoveltyIf::m_fSampleRate = 0 protected
sample rate
Definition at line 126 of file Novelty.h.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), CNoveltyFromVector::CNoveltyFromVector(), compNovelty(), getTimeStamps(), and init_().
m_iBlockLength
int CNoveltyIf::m_iBlockLength = 0 protected
fft length
Definition at line 123 of file Novelty.h.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), CNoveltyFromVector::CNoveltyFromVector(), compNovelty(), getTimeStamps(), init_(), and reset_().
m_iHopLength
int CNoveltyIf::m_iHopLength = 0 protected
hop length
Definition at line 124 of file Novelty.h.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), CNoveltyFromVector::CNoveltyFromVector(), compNovelty(), getTimeStamps(), and reset_().
m_pCBlockAudio
CBlockAudioIf* CNoveltyIf::m_pCBlockAudio = 0 protected
instantiate for blocking time domain signal
Definition at line 115 of file Novelty.h.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), CNoveltyFromVector::CNoveltyFromVector(), compNovelty(), getNumBlocks(), getTimeStamp(), getTimeStamps(), and reset_().
m_pCFft
CFft* CNoveltyIf::m_pCFft = 0 protected
fft instance
Definition at line 119 of file Novelty.h.
Referenced by compNovelty(), computeMagSpectrum_(), init_(), and reset_().
m_pCLpFilter
CMovingAverage* CNoveltyIf::m_pCLpFilter = 0 protected
smoothing filter handle
Definition at line 121 of file Novelty.h.
Referenced by compNovelty(), init_(), and reset_().
m_pCNormalize
CNormalizeAudio* CNoveltyIf::m_pCNormalize = 0 protected
instantiate if audio file normalization is wanted
Definition at line 113 of file Novelty.h.
Referenced by CNoveltyFromFile::CNoveltyFromFile(), CNoveltyFromVector::CNoveltyFromVector(), compNovelty(), reset_(), and CNoveltyFromFile::~CNoveltyFromFile().
m_pCNovelty
CNoveltyFromBlockIf* CNoveltyIf::m_pCNovelty = 0 protected
instance for instantaneous novelty extraction
Definition at line 117 of file Novelty.h.
Referenced by compNovelty(), init_(), and reset_().
m_pfProcBuff1
float* CNoveltyIf::m_pfProcBuff1 = 0 protected
temporary buffer
Definition at line 129 of file Novelty.h.
Referenced by compNovelty(), computeMagSpectrum_(), init_(), reset_(), and CNoveltyFromFile::~CNoveltyFromFile().
m_pfProcBuff2
float* CNoveltyIf::m_pfProcBuff2 = 0 protected
temporary buffer for current spectrum
Definition at line 128 of file Novelty.h.
Referenced by compNovelty(), computeMagSpectrum_(), init_(), and reset_().
The documentation for this class was generated from the following files:
Novelty.h
Novelty.cpp