ACA: CNmfResult Class Reference
CNmfResult Class Reference
class holding the result of Non-Negative Matrix Factorization executed with CNmf
#include <ToolNmf.h>
Public Types
enum NmfMatrices_t { kW , kH , kXHat , kNumMatrices }
Public Member Functions
CNmfResult ()
virtual ~CNmfResult (void)
int getMatCols (NmfMatrices_t eMatIdx) const
int getMatRows (NmfMatrices_t eMatIdx) const
void getMatDims (NmfMatrices_t eMatIdx, int &iNumRows, int &iNumCols) const
Error_t getMat (float **ppfDest, NmfMatrices_t eMatIdx)
bool isInitialized () const
Protected Member Functions
Error_t init (int iRank, int iNumRows, int iNumCols)
Error_t reset ()
float ** getMatPointer (NmfMatrices_t eMatIdx) const
Private Member Functions
CNmfResult (const CNmfResult &that)
disallow copy construction
Private Attributes
float ** m_appfMatrices [kNumMatrices] = { 0 }
arry holding all matrix pointers
int m_aaiMatrixDims [kNumMatrices][2] = { { 0 } }
array holding the various matrix dimensions
bool m_bIsInitialized = false
flag to indicate whether instance is initialized
Friends
class CNmf
Detailed Description
class holding the result of Non-Negative Matrix Factorization executed with CNmf
Definition at line 11 of file ToolNmf.h.
Member Enumeration Documentation
NmfMatrices_t
enum CNmfResult::NmfMatrices_t
Enumerator
kW
template matrix
kH
activation matrix
kXHat
reconstructed input matrix
kNumMatrices
Definition at line 16 of file ToolNmf.h.
    {
        kW, //!< template matrix
        kH, //!< activation matrix
        kXHat, //!< reconstructed input matrix
        kNumMatrices
    };
Constructor & Destructor Documentation
CNmfResult() [1/2]
CNmfResult::CNmfResult ()
Definition at line 173 of file ToolNmf.cpp.
{}
Referenced by CNmfResult().
~CNmfResult()
CNmfResult::~CNmfResult (void) virtual
Definition at line 176 of file ToolNmf.cpp.
{
    reset();
}
References reset().
CNmfResult() [2/2]
CNmfResult::CNmfResult (const CNmfResult & that) private
disallow copy construction
References CNmfResult().
Member Function Documentation
getMat()
Error_t CNmfResult::getMat (float ** ppfDest, NmfMatrices_t eMatIdx)
returns the number of rows in the matrix specified in eMatIdx
Parameters
ppfDest matrix to copy to (user allocated, dimensions see CNmfResult::getMatDims
eMatIdx matrix to copy
Returns
Error_t
Definition at line 240 of file ToolNmf.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!ppfDest)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfDest[0])
        return Error_t::kFunctionInvalidArgsError;
    CMatrix::copy(ppfDest, m_appfMatrices[eMatIdx], m_aaiMatrixDims[eMatIdx][0], m_aaiMatrixDims[eMatIdx][1]);
    return Error_t::kNoError;
}
References CMatrix::copy(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_aaiMatrixDims, m_appfMatrices, and m_bIsInitialized.
getMatCols()
int CNmfResult::getMatCols (NmfMatrices_t eMatIdx) const
returns the number of columns in the matrix specified in eMatIdx
Parameters
eMatIdx
Returns
int
Definition at line 223 of file ToolNmf.cpp.
{
    return  m_aaiMatrixDims[eMatIdx][1];
}
References m_aaiMatrixDims.
Referenced by getMatDims(), and CNmf::runNmfIter().
getMatDims()
void CNmfResult::getMatDims (NmfMatrices_t eMatIdx, int & iNumRows, int & iNumCols) const
writes the number of rows and columns in the matrix specified in eMatIdx
Parameters
eMatIdx
iNumRows number of rows
iNumCols number of columns
Definition at line 233 of file ToolNmf.cpp.
{
    iNumRows = getMatRows(eMatIdx);
    iNumCols = getMatCols(eMatIdx);
    return;
}
References getMatCols(), and getMatRows().
getMatPointer()
float ** CNmfResult::getMatPointer (NmfMatrices_t eMatIdx) const protected
Definition at line 259 of file ToolNmf.cpp.
{
    return m_appfMatrices[eMatIdx];
}
References m_appfMatrices.
Referenced by CNmf::runNmfIter().
getMatRows()
int CNmfResult::getMatRows (NmfMatrices_t eMatIdx) const
returns the number of rows in the matrix specified in eMatIdx
Parameters
eMatIdx
Returns
int
Definition at line 228 of file ToolNmf.cpp.
{
    return  m_aaiMatrixDims[eMatIdx][0];
}
References m_aaiMatrixDims.
Referenced by getMatDims(), and CNmf::runNmfIter().
init()
Error_t CNmfResult::init (int iRank, int iNumRows, int iNumCols) protected
Definition at line 181 of file ToolNmf.cpp.
{
    if (iRank <= 0 || iNumRows <= 0 || iNumCols <= 0)
        return Error_t::kFunctionInvalidArgsError;
    m_aaiMatrixDims[kW][0] = iNumRows;
    m_aaiMatrixDims[kW][1] = iRank;
    m_aaiMatrixDims[kH][0] = iRank;
    m_aaiMatrixDims[kH][1] = iNumCols;
    m_aaiMatrixDims[kXHat][0] = iNumRows;
    m_aaiMatrixDims[kXHat][1] = iNumCols;
    // alloc memory
    for (auto m = 0; m < kNumMatrices; m++)
        CMatrix::alloc(m_appfMatrices[m], m_aaiMatrixDims[m][0], m_aaiMatrixDims[m][1]);
    // init with random values
    CMatrix::setRand(m_appfMatrices[kW], m_aaiMatrixDims[kW][0], m_aaiMatrixDims[kW][1]);
    CMatrix::setRand(m_appfMatrices[kH], m_aaiMatrixDims[kH][0], m_aaiMatrixDims[kH][1]);
    // normalize
    CMatrix::vecnorm_I(m_appfMatrices[kW], m_aaiMatrixDims[kW][0], m_aaiMatrixDims[kW][1]);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CMatrix::alloc(), kFunctionInvalidArgsError, kH, kNoError, kNumMatrices, kW, kXHat, m_aaiMatrixDims, m_appfMatrices, m_bIsInitialized, CMatrix::setRand(), and CMatrix::vecnorm_I().
Referenced by CNmf::init().
isInitialized()
bool CNmfResult::isInitialized () const
returns true if the instance is initialized
Returns
bool
Definition at line 254 of file ToolNmf.cpp.
{
    return m_bIsInitialized;
}
References m_bIsInitialized.
Referenced by CNmf::compNmf().
reset()
Error_t CNmfResult::reset (void) protected
Definition at line 210 of file ToolNmf.cpp.
{
    m_bIsInitialized = false;
    for (auto m = 0; m < kNumMatrices; m++)
    {
        CMatrix::free(m_appfMatrices[m], m_aaiMatrixDims[m][0]);
        CVector::setZero(m_aaiMatrixDims[m], 2);
    }
    return Error_t::kNoError;
}
References CMatrix::free(), kNoError, kNumMatrices, m_aaiMatrixDims, m_appfMatrices, m_bIsInitialized, and CVector::setZero().
Referenced by ~CNmfResult().
Friends And Related Symbol Documentation
CNmf
friend class CNmf friend
Definition at line 13 of file ToolNmf.h.
References CNmf.
Referenced by CNmf.
Member Data Documentation
m_aaiMatrixDims
int CNmfResult::m_aaiMatrixDims[kNumMatrices][2] = { { 0 } } private
array holding the various matrix dimensions
Definition at line 69 of file ToolNmf.h.
{ { 0 } }; //!< array holding the various matrix dimensions
Referenced by getMat(), getMatCols(), getMatRows(), init(), and reset().
m_appfMatrices
float** CNmfResult::m_appfMatrices[kNumMatrices] = { 0 } private
arry holding all matrix pointers
Definition at line 67 of file ToolNmf.h.
{ 0 }; //!< arry holding all matrix pointers
Referenced by getMat(), getMatPointer(), init(), and reset().
m_bIsInitialized
bool CNmfResult::m_bIsInitialized = false private
flag to indicate whether instance is initialized
Definition at line 71 of file ToolNmf.h.
Referenced by getMat(), init(), isInitialized(), and reset().
The documentation for this class was generated from the following files:
ToolNmf.h
ToolNmf.cpp