ACA: CGmm Class Reference
CGmm Class Reference
implements Gaussian mixture model
#include <ToolGmm.h>
Public Member Functions
CGmm (void)
virtual ~CGmm (void)
Error_t init (CGmmResult *pCResult, int iK, int iNumFeatures, int iNumObs, int iMaxIter=300)
Error_t reset ()
Error_t compGmm (CGmmResult *pCResult, const float *const *const ppfFeatures)
Private Types
enum States_t { kPrev , kCurr , kNumStates }
Private Member Functions
CGmm (const CGmm &that)
disallow copy construction
CGmm & operator= (const CGmm &c)
void initState_ (const float *const *const ppfFeatures, CGmmResult *pCCurrState)
void compProbabilities_ (const float *const *const ppfFeatures, CGmmResult *pCCurrState)
void updateState_ (const float *const *const ppfFeatures, CGmmResult *pCCurrState)
bool checkConverged_ (CGmmResult *pCCurrState)
Private Attributes
CGmmResult PrevState
previous state for convergence
float ** m_appfClusterMeans [kNumStates] = { 0 }
contains the current and previous cluster means
float * m_apfProc [2] = { 0 }
temporary pre-allocated memory buffer
float ** m_appfSigma [2] = { 0 }
temporary sigma matrices (m_iNumFeatures x m_iNumFeatures)
float ** m_ppfProb = 0
probabilities (temp, dims m_iK x m_iNumObs)
int * m_piClusterSize = 0
number of observations per cluster
int m_iNumFeatures = 0
number of feature dimension (matrix rows)
int m_iNumObs = 0
number of observations (matrix cols)
int m_iK = 0
number of clusters
int m_iMaxIter = 300
maximum number of iterations
bool m_bisInitialized = false
indicates whether instance is initialized
Detailed Description
implements Gaussian mixture model
Definition at line 97 of file ToolGmm.h.
Member Enumeration Documentation
States_t
enum CGmm::States_t private
Enumerator
kPrev
kCurr
kNumStates
Definition at line 129 of file ToolGmm.h.
    {
        kPrev,
        kCurr,
        kNumStates
    };
Constructor & Destructor Documentation
CGmm() [1/2]
CGmm::CGmm (void) inline
Definition at line 101 of file ToolGmm.h.
{};
~CGmm()
CGmm::~CGmm (void) virtual
Definition at line 9 of file ToolGmm.cpp.
{ reset(); }
References reset().
CGmm() [2/2]
CGmm::CGmm (const CGmm & that) private
disallow copy construction
Member Function Documentation
checkConverged_()
bool CGmm::checkConverged_ (CGmmResult * pCCurrState) private
returns true if the means are identical compared to previous iteration
Returns
bool true if identical
Definition at line 188 of file ToolGmm.cpp.
{
    float fSum = 0;
    for (auto k = 0; k < m_iK; k++)
    {
        for (auto v = 0; v < m_iNumFeatures; v++)
            fSum += std::abs(pCCurrState->getMu(k, v) - PrevState.getMu(k, v));
    }
    if (fSum / m_iK <= 1e-20F)
        return true;
    return false;
}
References CGmmResult::getMu(), m_iK, m_iNumFeatures, and PrevState.
Referenced by compGmm().
compGmm()
Error_t CGmm::compGmm (CGmmResult * pCResult, const float *const *const ppfFeatures)
computes the mixture model
Parameters
pCResult class holding resulting mean, sigma, and priors, see class CGmmResult
ppfFeatures input matrix of dimensions iNumFeatures X iNumObs
Returns
Error_t
Definition at line 62 of file ToolGmm.cpp.
{
    if (!pCResult || !ppfFeatures)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfFeatures[0])
        return Error_t::kFunctionInvalidArgsError;
    if (!m_bisInitialized)
        return Error_t::kFunctionIllegalCallError;
    // init: randomly selected data points as cluster means
    initState_(ppfFeatures, pCResult);
    // iterate
    for (auto i = 0; i < m_iMaxIter; i++)
    {
        // copy state to prev state
        PrevState = *pCResult;
        // update cluster means
        compProbabilities_(ppfFeatures, pCResult);
        // assign observations to clusters
        updateState_(ppfFeatures, pCResult);
        // check for change
        if (checkConverged_(pCResult))
            break;
    }
    return Error_t::kNoError;
}
References checkConverged_(), compProbabilities_(), initState_(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bisInitialized, m_iMaxIter, PrevState, and updateState_().
Referenced by CGmmClassifier::train().
compProbabilities_()
void CGmm::compProbabilities_ (const float *const *const ppfFeatures, CGmmResult * pCCurrState) private
computes probabilities given the current state
Parameters
ppfFeatures input matrix of dimensions iNumFeatures X iNumObs
pCCurrState class holding the current state variables
Definition at line 117 of file ToolGmm.cpp.
{
    // compute gaussian per cluster per observation
    for (auto k = 0; k < m_iK; k++)
    {
        pCCurrState->getSigma(m_appfSigma[0], k);
        float fDet = CMatrix::det(m_appfSigma[0], m_iNumFeatures, m_iNumFeatures);
        if (fDet < 1e-30F)
        {
            CVector::setZero(m_ppfProb[k], m_iNumObs);
            continue;
        }
        float fNorm = static_cast<float>(1. / std::sqrt(std::pow(2. * M_PI, m_iNumFeatures) * fDet));
        CMatrix::inv_I(m_appfSigma[0], m_iNumFeatures, m_iNumFeatures);
        for (auto n = 0; n < m_iNumObs; n++)
        {
            for (auto v = 0; v < m_iNumFeatures; v++)
                m_apfProc[0][v] = ppfFeatures[v][n] - pCCurrState->getMu(k, v);
            CMatrix::mulMatColvec(m_apfProc[1], m_appfSigma[0], m_apfProc[0], m_iNumFeatures, m_iNumFeatures);
            m_ppfProb[k][n] = fNorm * std::exp(-.5F * CVector::mulScalar(m_apfProc[0], m_apfProc[1], m_iNumFeatures));
        }
        CVector::mulC_I(m_ppfProb[k], pCCurrState->getPrior(k), m_iNumObs);
    }
    // norm over clusters
    for (auto n = 0; n < m_iNumObs; n++)
    {
        float fSum = CMatrix::getSumCol(m_ppfProb, n, m_iK);
        if (fSum > 0)
            CMatrix::mulColC_I(m_ppfProb, 1.F / fSum, n, m_iK);
    }
}
References CMatrix::det(), CGmmResult::getMu(), CGmmResult::getPrior(), CGmmResult::getSigma(), CMatrix::getSumCol(), CMatrix::inv_I(), m_apfProc, m_appfSigma, m_iK, m_iNumFeatures, m_iNumObs, M_PI, m_ppfProb, CVector::mulC_I(), CMatrix::mulColC_I(), CMatrix::mulMatColvec(), CVector::mulScalar(), and CVector::setZero().
Referenced by compGmm().
init()
Error_t CGmm::init (CGmmResult * pCResult, int iK, int iNumFeatures, int iNumObs, int iMaxIter = 300)
initializes the class
Parameters
pCResult class holding resulting mean, sigma, and priors, see class CGmmResult (user-allocated)
iK target number of Gaussians
iNumFeatures number of rows (features) of input matrix
iNumObs number of columns (observations) of input matrix
iMaxIter maximum number of iterations
Returns
Error_t
Definition at line 11 of file ToolGmm.cpp.
{
    if (!pCResult || iK < 1 || iNumFeatures < 1 || iNumObs < 1 || iMaxIter < 1)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    // set variables
    m_iMaxIter = iMaxIter;
    m_iNumFeatures = iNumFeatures;
    m_iNumObs = iNumObs;
    m_iK = iK;
    // init result class
    pCResult->init(iK, iNumFeatures);
    PrevState = CGmmResult(*pCResult);
    // alloc memory
    for (auto i = 0; i < 2; i++)
    {
        CVector::alloc(m_apfProc[i], std::max(iK, iNumFeatures));
        CMatrix::alloc(m_appfSigma[i], m_iNumFeatures, m_iNumFeatures);
    }
    CMatrix::alloc(m_ppfProb, m_iK, m_iNumObs);
    // all done
    m_bisInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), CGmmResult::init(), kFunctionInvalidArgsError, kNoError, m_apfProc, m_appfSigma, m_bisInitialized, m_iK, m_iMaxIter, m_iNumFeatures, m_iNumObs, m_ppfProb, PrevState, and reset().
Referenced by CGmmClassifier::train().
initState_()
void CGmm::initState_ (const float *const *const ppfFeatures, CGmmResult * pCCurrState) private
randomly initializes the state variables
Parameters
ppfFeatures input matrix of dimensions iNumFeatures X iNumObs
pCCurrState class holding the current state variables
Definition at line 93 of file ToolGmm.cpp.
{
    // generate some noise
    CSynthesis::genNoise(m_apfProc[0], m_iK);
    CVector::mulC_I(m_apfProc[0], m_iNumObs - 1.F, m_iK);
    CPca::compCov(m_appfSigma[0], ppfFeatures, m_iNumFeatures, m_iNumObs);
    for (auto k = 0; k < m_iK; k++)
    {
        int iIdx = CUtil::float2int<int>(m_apfProc[0][k]);
        assert(iIdx >= 0 && iIdx < m_iNumObs);
        // set sigma
        pCCurrState->setSigma(k, m_appfSigma[0]);
        // set mean
        for (auto v = 0; v < m_iNumFeatures; v++)
            pCCurrState->setMu(k, v, ppfFeatures[v][iIdx]);
        // set prior
        pCCurrState->setPrior(k, 1.F / m_iK);
    }
}
References CPca::compCov(), CSynthesis::genNoise(), m_apfProc, m_appfSigma, m_iK, m_iNumFeatures, m_iNumObs, CVector::mulC_I(), CGmmResult::setMu(), CGmmResult::setPrior(), and CGmmResult::setSigma().
Referenced by compGmm().
operator=()
CGmm & CGmm::operator= (const CGmm & c) private
reset()
Error_t CGmm::reset ()
resets all internal class members
Returns
Error_t
Definition at line 42 of file ToolGmm.cpp.
{
    m_bisInitialized = false;
    for (auto i = 0; i < 2; i++)
    {
        CVector::free(m_apfProc[i]);
        CMatrix::free(m_appfSigma[i], m_iNumFeatures);
    }
    CMatrix::free(m_ppfProb, m_iK);
    m_iMaxIter = 300;
    m_iNumFeatures = 0;
    m_iNumObs = 0;
    m_iK = 0;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kNoError, m_apfProc, m_appfSigma, m_bisInitialized, m_iK, m_iMaxIter, m_iNumFeatures, m_iNumObs, and m_ppfProb.
Referenced by init(), CGmmClassifier::train(), and ~CGmm().
updateState_()
void CGmm::updateState_ (const float *const *const ppfFeatures, CGmmResult * pCCurrState) private
update mean, sigma, and prior
Parameters
ppfFeatures input matrix of dimensions iNumFeatures X iNumObs
pCCurrState class holding the current state variables
Definition at line 155 of file ToolGmm.cpp.
{
    for (auto k = 0; k < m_iK; k++)
    {
        // update priors
        pCCurrState->setPrior(k, CVector::getMean(m_ppfProb[k], m_iNumObs));
        // update means
        float fNorm = CVector::getSum(m_ppfProb[k], m_iNumObs);
        if (fNorm < 1e-30F)
            fNorm = 1.F;
        for (auto v = 0; v < m_iNumFeatures; v++)
            pCCurrState->setMu(k, v, CVector::mulScalar(ppfFeatures[v], m_ppfProb[k], m_iNumObs) / fNorm);
        // update sigma
        CMatrix::setZero(m_appfSigma[0], m_iNumFeatures, m_iNumFeatures);
        for (auto n = 0; n < m_iNumObs; n++)
        {
            for (auto v = 0; v < m_iNumFeatures; v++)
                m_apfProc[0][v] = ppfFeatures[v][n] - pCCurrState->getMu(k, v);
            CMatrix::mulColvecRowvec(m_appfSigma[1], m_apfProc[0], m_apfProc[0], m_iNumFeatures, m_iNumFeatures);
            CMatrix::mulC_I(m_appfSigma[1], m_ppfProb[k][n], m_iNumFeatures, m_iNumFeatures);
            CMatrix::add_I(m_appfSigma[0], m_appfSigma[1], m_iNumFeatures, m_iNumFeatures);
        }
        fNorm = CVector::getSum(m_ppfProb[k], m_iNumObs);
        if (fNorm < 1e-30F)
            fNorm = 1.F;
        CMatrix::mulC_I(m_appfSigma[0], 1.F / fNorm, m_iNumFeatures, m_iNumFeatures);
        pCCurrState->setSigma(k, m_appfSigma[0]);
    }
}
References CMatrix::add_I(), CVector::getMean(), CGmmResult::getMu(), CVector::getSum(), m_apfProc, m_appfSigma, m_iK, m_iNumFeatures, m_iNumObs, m_ppfProb, CMatrix::mulC_I(), CMatrix::mulColvecRowvec(), CVector::mulScalar(), CGmmResult::setMu(), CGmmResult::setPrior(), CGmmResult::setSigma(), and CMatrix::setZero().
Referenced by compGmm().
Member Data Documentation
m_apfProc
float* CGmm::m_apfProc[2] = { 0 } private
temporary pre-allocated memory buffer
Definition at line 170 of file ToolGmm.h.
Referenced by compProbabilities_(), init(), initState_(), reset(), and updateState_().
m_appfClusterMeans
float** CGmm::m_appfClusterMeans[kNumStates] = { 0 } private
contains the current and previous cluster means
Definition at line 168 of file ToolGmm.h.
m_appfSigma
float ** CGmm::m_appfSigma[2] = { 0 } private
temporary sigma matrices (m_iNumFeatures x m_iNumFeatures)
Definition at line 171 of file ToolGmm.h.
Referenced by compProbabilities_(), init(), initState_(), reset(), and updateState_().
m_bisInitialized
bool CGmm::m_bisInitialized = false private
indicates whether instance is initialized
Definition at line 181 of file ToolGmm.h.
Referenced by compGmm(), init(), and reset().
m_iK
int CGmm::m_iK = 0 private
number of clusters
Definition at line 178 of file ToolGmm.h.
Referenced by checkConverged_(), compProbabilities_(), init(), initState_(), reset(), and updateState_().
m_iMaxIter
int CGmm::m_iMaxIter = 300 private
maximum number of iterations
Definition at line 179 of file ToolGmm.h.
Referenced by compGmm(), init(), and reset().
m_iNumFeatures
int CGmm::m_iNumFeatures = 0 private
number of feature dimension (matrix rows)
Definition at line 176 of file ToolGmm.h.
Referenced by checkConverged_(), compProbabilities_(), init(), initState_(), reset(), and updateState_().
m_iNumObs
int CGmm::m_iNumObs = 0 private
number of observations (matrix cols)
Definition at line 177 of file ToolGmm.h.
Referenced by compProbabilities_(), init(), initState_(), reset(), and updateState_().
m_piClusterSize
int* CGmm::m_piClusterSize = 0 private
number of observations per cluster
Definition at line 174 of file ToolGmm.h.
m_ppfProb
float ** CGmm::m_ppfProb = 0 private
probabilities (temp, dims m_iK x m_iNumObs)
Definition at line 172 of file ToolGmm.h.
Referenced by compProbabilities_(), init(), reset(), and updateState_().
PrevState
CGmmResult CGmm::PrevState private
previous state for convergence
Definition at line 166 of file ToolGmm.h.
Referenced by checkConverged_(), compGmm(), and init().
The documentation for this class was generated from the following files:
ToolGmm.h
ToolGmm.cpp