ACA: CGammaToneFbIf Class Reference
CGammaToneFbIf Class Reference
class for computation of a Gammatone filterbank output from either a file or a vector
#include <ToolGammatone.h>
Public Member Functions
Error_t getOutputDimensions (long long &iNumRows, long long &iNumCols) const
float getCenterFreq (int iBandIdx) const
Error_t process (float **ppfOut, const float *pfIn=0, long long iNumSamples=0)
Static Public Member Functions
static Error_t create (CGammaToneFbIf *&pCInstance, const std::string &strAudioFilePath, int iNumBands=20, float fStartInHz=100)
static Error_t create (CGammaToneFbIf *&pCInstance, const float *pfAudio, long long iNumSamples, float fSampleRate, int iNumBands=20, float fStartInHz=100)
static Error_t create (CGammaToneFbIf *&pCInstance, float fSampleRate, int iNumBands=20, float fStartInHz=100)
static Error_t destroy (CGammaToneFbIf *&pCInstance)
Protected Member Functions
CGammaToneFbIf ()
virtual ~CGammaToneFbIf ()
CGammaToneFbIf (const CGammaToneFbIf &that)
CGammaToneFbIf & operator= (const CGammaToneFbIf &c)
Error_t reset_ ()
reset configuration
Error_t init_ ()
init configuration
float compMidFreqs_ (float fFreqLow, float fFreqHigh, int k) const
compute center frequencies for all bands
Protected Attributes
CNormalizeAudio * m_pCNormalize = 0
instantiate if audio file normalization is wanted
CBlockAudioIf * m_pCBlockAudio = 0
instantiate for blocking time domain signal
CGammatone ** m_ppCGammatone = 0
array of filters
const int m_iBlockLength = 4096
internal processing block length
int m_iNumBands = 0
number of gammatone bands
float m_fSampleRate = 0
sample rate
float m_fStartInHz = 0
lowest band center frequency
float * m_pfProcBuff = 0
temporary processing buffer
bool m_bIsInitialized = false
true if initialized
Detailed Description
class for computation of a Gammatone filterbank output from either a file or a vector
Definition at line 18 of file ToolGammatone.h.
Constructor & Destructor Documentation
CGammaToneFbIf() [1/2]
CGammaToneFbIf::CGammaToneFbIf () protected
Definition at line 350 of file ToolGammatone.cpp.
{
    reset_();
}
References reset_().
Referenced by CGammaToneFbIf(), create(), create(), create(), destroy(), and operator=().
~CGammaToneFbIf()
CGammaToneFbIf::~CGammaToneFbIf () inline protected virtual
Definition at line 355 of file ToolGammatone.cpp.
{
    reset_();
}
References reset_().
CGammaToneFbIf() [2/2]
CGammaToneFbIf::CGammaToneFbIf (const CGammaToneFbIf & that) protected
References CGammaToneFbIf().
Member Function Documentation
compMidFreqs_()
float CGammaToneFbIf::compMidFreqs_ (float fFreqLow, float fFreqHigh, int k) const inline protected
compute center frequencies for all bands
Definition at line 514 of file ToolGammatone.cpp.
{
    const float fEarQ = 9.26449F;
    const float fBandwidth = 24.7F;
    return -(fEarQ * fBandwidth) + std::exp((m_iNumBands - k) * (-std::log(fFreqHigh + fEarQ * fBandwidth) + std::log(fFreqLow + fEarQ * fBandwidth)) / m_iNumBands) * (fFreqHigh + fEarQ * fBandwidth);
}
References m_iNumBands.
Referenced by getCenterFreq(), and init_().
create() [1/3]
Error_t CGammaToneFbIf::create (CGammaToneFbIf *& pCInstance, const float * pfAudio, long long iNumSamples, float fSampleRate, int iNumBands = 20, float fStartInHz = 100) static
initializes a GammaToneFb instance from audio data
Parameters
pCInstance pointer to instance to be written
pfAudio complete audio data
iNumSamples length of pfAudio
fSampleRate sample rate in Hz
iNumBands number of gammatone bands
fStartInHz center frequency of the lowest band
Returns
Error_t
Definition at line 375 of file ToolGammatone.cpp.
{
    if (!pfAudio)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumSamples <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumBands <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fStartInHz <= 0 || fStartInHz >= fSampleRate / 2)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CGammaToneFbFromVector(pfAudio, iNumSamples, fSampleRate, iNumBands, fStartInHz);
    return Error_t::kNoError;
}
References CGammaToneFbIf(), kFunctionInvalidArgsError, and kNoError.
create() [2/3]
Error_t CGammaToneFbIf::create (CGammaToneFbIf *& pCInstance, const std::string & strAudioFilePath, int iNumBands = 20, float fStartInHz = 100) static
initializes a GammaToneFb instance with file reading
Parameters
pCInstance pointer to instance to be written
strAudioFilePath complete path to audio file
iNumBands number of gammatone bands
fStartInHz center frequency of the lowest band
Returns
Error_t
Definition at line 360 of file ToolGammatone.cpp.
{
    if (strAudioFilePath.empty())
        return Error_t::kFunctionInvalidArgsError;
    if (iNumBands <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fStartInHz <= 0)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CGammaToneFbFromFile(strAudioFilePath, iNumBands, fStartInHz);
    return Error_t::kNoError;
}
References CGammaToneFbIf(), kFunctionInvalidArgsError, and kNoError.
Referenced by CPitchTimeAuditory::CPitchTimeAuditory().
create() [3/3]
Error_t CGammaToneFbIf::create (CGammaToneFbIf *& pCInstance, float fSampleRate, int iNumBands = 20, float fStartInHz = 100) static
initializes a GammaToneFb instance for block based processing
Parameters
pCInstance pointer to instance to be written
fSampleRate sample rate in Hz
iNumBands number of gammatone bands
fStartInHz center frequency of the lowest band
Returns
Error_t
Definition at line 393 of file ToolGammatone.cpp.
{
    if (fSampleRate <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (iNumBands <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (fStartInHz <= 0 || fStartInHz >= fSampleRate / 2)
        return Error_t::kFunctionInvalidArgsError;
    pCInstance = new CGammaToneFbRealTime(fSampleRate, iNumBands, fStartInHz);
    return Error_t::kNoError;
}
References CGammaToneFbIf(), kFunctionInvalidArgsError, and kNoError.
destroy()
Error_t CGammaToneFbIf::destroy (CGammaToneFbIf *& pCInstance) static
destroys a GammaToneFb instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 407 of file ToolGammatone.cpp.
{
    delete pCInstance;
    pCInstance = 0;
    return Error_t::kNoError;
}
References CGammaToneFbIf(), and kNoError.
Referenced by CPitchTimeAuditory::~CPitchTimeAuditory().
getCenterFreq()
float CGammaToneFbIf::getCenterFreq (int iBandIdx) const
returns center frequency
Parameters
iBandIdx index of band the frequency is request for
Returns
float
Definition at line 430 of file ToolGammatone.cpp.
{
    return compMidFreqs_(m_fStartInHz, m_fSampleRate / 2, iBandIdx);
}
References compMidFreqs_(), m_fSampleRate, and m_fStartInHz.
getOutputDimensions()
Error_t CGammaToneFbIf::getOutputDimensions (long long & iNumRows, long long & iNumCols) const
returns size of matrix to be allocated by user for the output
Parameters
iNumRows (number of bands, to be written)
iNumCols (number of samples, to be written)
Returns
Error_t
Definition at line 415 of file ToolGammatone.cpp.
{
    if (!m_bIsInitialized)
    {
        iNumRows = 0;
        iNumCols = 0;
        return Error_t::kFunctionIllegalCallError;
    }
    iNumRows = m_iNumBands;
    iNumCols = m_pCBlockAudio->getLengthInSamples();
    return Error_t::kNoError;
}
References kFunctionIllegalCallError, kNoError, m_bIsInitialized, m_iNumBands, and m_pCBlockAudio.
init_()
Error_t CGammaToneFbIf::init_ () protected
init configuration
Definition at line 496 of file ToolGammatone.cpp.
{
    // allocate processing memory
    CVector::alloc(m_pfProcBuff, m_iBlockLength);
    CVector::alloc(m_ppCGammatone, m_iNumBands);
    for (auto i = 0; i < m_iNumBands; i++)
    {
        m_ppCGammatone[i] = new CGammatone();
        m_ppCGammatone[i]->init(compMidFreqs_(m_fStartInHz, m_fSampleRate / 2, i), m_fSampleRate);
    }
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), compMidFreqs_(), kNoError, m_bIsInitialized, m_fSampleRate, m_fStartInHz, m_iBlockLength, m_iNumBands, m_pfProcBuff, and m_ppCGammatone.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), and CGammaToneFbRealTime::CGammaToneFbRealTime().
operator=()
CGammaToneFbIf & CGammaToneFbIf::operator= (const CGammaToneFbIf & c) protected
References CGammaToneFbIf().
process()
Error_t CGammaToneFbIf::process (float ** ppfOut, const float * pfIn = 0, long long iNumSamples = 0)
performs the GammaToneFb computation for 1 dimensional GammaToneFbs and writes the result
Parameters
ppfOut (user-allocated, to be written, dimensions iNumBands x iNumSamples, see CGammaToneFbIf::getOutputDimensions)
pfIn input data (for real-time block processing only)
iNumSamples length of input data (for real-time block processing only)
Returns
Error_t
Definition at line 435 of file ToolGammatone.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!ppfOut)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfOut[0])
        return Error_t::kFunctionInvalidArgsError;
    // special case of block by block processing - no normalization, no blocking
    if (pfIn)
    {
        assert(iNumSamples > 0);
        for (auto i = 0; i < m_iNumBands; i++)
        {
            assert(ppfOut[i]);
            m_ppCGammatone[i]->process(ppfOut[i], pfIn, iNumSamples);
        }
        return Error_t::kNoError;
    }
    assert(m_pCBlockAudio);
    auto iNumBlocks = m_pCBlockAudio->getNumBlocks();
    for (auto n = 0; n < iNumBlocks; n++)
    {
        // retrieve the next audio block
        int iNumFrames = m_pCBlockAudio->getNextBlock(m_pfProcBuff);
        // normalize if specified
        if (m_pCNormalize)
            m_pCNormalize->normalizeBlock(m_pfProcBuff, m_iBlockLength);
        for (auto i = 0; i < m_iNumBands; i++)
        {
            assert(ppfOut[i]);
            m_ppCGammatone[i]->process(&ppfOut[i][n * m_iBlockLength], m_pfProcBuff, iNumFrames);
        }
    }
    return Error_t::kNoError;
}
References kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iBlockLength, m_iNumBands, m_pCBlockAudio, m_pCNormalize, m_pfProcBuff, and m_ppCGammatone.
reset_()
Error_t CGammaToneFbIf::reset_ () protected
reset configuration
Definition at line 479 of file ToolGammatone.cpp.
{
    CVector::free(m_pfProcBuff);
    delete m_pCNormalize;
    m_pCNormalize = 0;
    CBlockAudioIf::destroy(m_pCBlockAudio);
    for (auto i = 0; i < m_iNumBands; i++)
        delete m_ppCGammatone[i];
    CVector::free(m_ppCGammatone);
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CBlockAudioIf::destroy(), CVector::free(), kNoError, m_bIsInitialized, m_iNumBands, m_pCBlockAudio, m_pCNormalize, m_pfProcBuff, and m_ppCGammatone.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbIf(), and ~CGammaToneFbIf().
Member Data Documentation
m_bIsInitialized
bool CGammaToneFbIf::m_bIsInitialized = false protected
true if initialized
Definition at line 103 of file ToolGammatone.h.
Referenced by getOutputDimensions(), init_(), process(), and reset_().
m_fSampleRate
float CGammaToneFbIf::m_fSampleRate = 0 protected
sample rate
Definition at line 98 of file ToolGammatone.h.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), CGammaToneFbRealTime::CGammaToneFbRealTime(), getCenterFreq(), and init_().
m_fStartInHz
float CGammaToneFbIf::m_fStartInHz = 0 protected
lowest band center frequency
Definition at line 99 of file ToolGammatone.h.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), CGammaToneFbRealTime::CGammaToneFbRealTime(), getCenterFreq(), and init_().
m_iBlockLength
const int CGammaToneFbIf::m_iBlockLength = 4096 protected
internal processing block length
Definition at line 94 of file ToolGammatone.h.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), init_(), and process().
m_iNumBands
int CGammaToneFbIf::m_iNumBands = 0 protected
number of gammatone bands
Definition at line 96 of file ToolGammatone.h.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), CGammaToneFbRealTime::CGammaToneFbRealTime(), compMidFreqs_(), getOutputDimensions(), init_(), process(), and reset_().
m_pCBlockAudio
CBlockAudioIf* CGammaToneFbIf::m_pCBlockAudio = 0 protected
instantiate for blocking time domain signal
Definition at line 91 of file ToolGammatone.h.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), getOutputDimensions(), process(), and reset_().
m_pCNormalize
CNormalizeAudio* CGammaToneFbIf::m_pCNormalize = 0 protected
instantiate if audio file normalization is wanted
Definition at line 89 of file ToolGammatone.h.
Referenced by CGammaToneFbFromFile::CGammaToneFbFromFile(), CGammaToneFbFromVector::CGammaToneFbFromVector(), process(), reset_(), and CGammaToneFbFromFile::~CGammaToneFbFromFile().
m_pfProcBuff
float* CGammaToneFbIf::m_pfProcBuff = 0 protected
temporary processing buffer
Definition at line 101 of file ToolGammatone.h.
Referenced by init_(), process(), and reset_().
m_ppCGammatone
CGammatone** CGammaToneFbIf::m_ppCGammatone = 0 protected
array of filters
Definition at line 92 of file ToolGammatone.h.
Referenced by init_(), process(), and reset_().
The documentation for this class was generated from the following files:
ToolGammatone.h
ToolGammatone.cpp