ACA: CConversion Class Reference
CConversion Class Reference
class for various frequency conversion functions
#include <ToolConversion.h>
Public Types
enum MelConversionFunctions_t { kFant , kShaughnessy , kUmesh , kNumMelConversionFunctions }
different methods for frequency to mel conversion
enum BarkConversionFunctions_t {
kSchroeder , kTerhardt , kZwicker , kTraunmuller ,
kNumBarkConversionFunctions
}
different methods for frequency to bark conversion
Static Public Member Functions
static float convertFreq2Mel (float fInHz, MelConversionFunctions_t eFunc=kFant)
static float convertMel2Freq (float fMel, MelConversionFunctions_t eFunc=kFant)
static void convertFreq2Mel (float *pfMel, const float *pffInHz, int iLengthBuff, MelConversionFunctions_t eFunc=kFant)
static void convertMel2Freq (float *pffInHz, const float *pfMel, int iLengthBuff, MelConversionFunctions_t eFunc=kFant)
static float convertFreq2Bark (float fInHz, BarkConversionFunctions_t eFunc=kSchroeder)
static float convertBark2Freq (float fBark, BarkConversionFunctions_t eFunc=kSchroeder)
static void convertFreq2Bark (float *pfBark, const float *pffInHz, int iLengthBuff, BarkConversionFunctions_t eFunc=kSchroeder)
static void convertBark2Freq (float *pffInHz, const float *pfBark, int iLengthBuff, BarkConversionFunctions_t eFunc=kSchroeder)
static float convertFreq2Midi (float fInHz, float fA4InHz=440.F)
static void convertFreq2Midi (float *pfMidi, const float *pffInHz, int iLengthBuff, float fA4InHz=440.F)
static float convertMidi2Freq (float fMidi, float fA4InHz=440.F)
static void convertMidi2Freq (float *pffInHz, const float *pfMidi, int iLengthBuff, float fA4InHz=440.F)
static float convertFreq2Bin (float fInHz, int iFftLength, float fSampleRate=44100.F)
static void convertFreq2Bin (float *pfBin, const float *pffInHz, int iLengthBuff, int iFftLength, float fSampleRate=44100.F)
static float convertBin2Freq (float fBin, int iFftLength, float fSampleRate=44100.F)
static void convertBin2Freq (float *pffInHz, const float *pfBin, int iLengthBuff, int iFftLength, float fSampleRate=44100.F)
static uint32_t convertFloat2Word (const float *pfVec)
static void convertWord2Float (float *pfDest, uint32_t iWord)
Static Protected Member Functions
static float convertFreq2MelFant (float fFrequency)
static float convertMel2FreqFant (float fMel)
static float convertFreq2MelShaughnessy (float fFrequency)
static float convertMel2FreqShaughnessy (float fMel)
static float convertFreq2MelUmesh (float fFrequency)
static float convertMel2FreqUmesh (float fMel)
static float convertFreq2BarkSchroeder (float fFrequency)
static float convertBark2FreqSchroeder (float fBark)
static float convertFreq2BarkTerhardt (float fFrequency)
static float convertBark2FreqTerhardt (float fBark)
static float convertFreq2BarkZwicker (float fFrequency)
static float convertBark2FreqZwicker (float fBark)
static float convertFreq2BarkTraunmuller (float fFrequency)
static float convertBark2FreqTraunmuller (float fBark)
Private Member Functions
CConversion ()
virtual ~CConversion ()
Static Private Attributes
static const std::map< int, std::function< float(float)> > m_MelDispatchMap
static const std::map< int, std::function< float(float)> > m_BarkDispatchMap
Detailed Description
class for various frequency conversion functions
Definition at line 15 of file ToolConversion.h.
Member Enumeration Documentation
BarkConversionFunctions_t
enum CConversion::BarkConversionFunctions_t
different methods for frequency to bark conversion
Enumerator
kSchroeder
conversion acc. to Schroeder
kTerhardt
conversion acc. to Terhardt
kZwicker
conversion acc. to Zwicker
kTraunmuller
conversion acc. to Traunmuller
kNumBarkConversionFunctions
Definition at line 29 of file ToolConversion.h.
    {
        kSchroeder,     //!< conversion acc. to Schroeder
        kTerhardt,      //!< conversion acc. to Terhardt
        kZwicker,       //!< conversion acc. to Zwicker
        kTraunmuller,   //!< conversion acc. to Traunmuller
        kNumBarkConversionFunctions
    };
MelConversionFunctions_t
enum CConversion::MelConversionFunctions_t
different methods for frequency to mel conversion
Enumerator
kFant
conversion acc. to Fant
kShaughnessy
conversion acc. to Shaughnessy
kUmesh
conversion acc. to Umesh
kNumMelConversionFunctions
Definition at line 19 of file ToolConversion.h.
    {
        kFant,          //!< conversion acc. to Fant
        kShaughnessy,   //!< conversion acc. to Shaughnessy
        kUmesh,         //!< conversion acc. to Umesh
        kNumMelConversionFunctions
    };
Constructor & Destructor Documentation
CConversion()
CConversion::CConversion () inline private
Definition at line 285 of file ToolConversion.h.
{};
Member Function Documentation
convertBark2Freq() [1/2]
void CConversion::convertBark2Freq (float * pffInHz, const float * pfBark, int iLengthBuff, BarkConversionFunctions_t eFunc = kSchroeder) static
converts a Bark array to a frequency array
Parameters
pffInHz output frequency values in Hz (length iLenghBuff, to be written)
pfBark input Bark values (length iLenghBuff)
iLengthBuff length of buffers
eFunc index for conversion function selection
Definition at line 115 of file ToolConversion.cpp.
{
    assert(pfBark);
    assert(pffInHz);
    assert(iLengthBuff > 0);
    for (auto k = 0; k < iLengthBuff; k++)
        pffInHz[k] = m_BarkDispatchMap.at(eFunc + kNumBarkConversionFunctions)(pfBark[k]);
}
References kNumBarkConversionFunctions, and m_BarkDispatchMap.
convertBark2Freq() [2/2]
float CConversion::convertBark2Freq (float fBark, BarkConversionFunctions_t eFunc = kSchroeder) static
converts a Bark scalar to a frequency
Parameters
fBark Bark value
eFunc index for conversion function selection
Returns
frequency value in Hz
Definition at line 99 of file ToolConversion.cpp.
{
    assert(fBark >= 0);
    return m_BarkDispatchMap.at(eFunc + kNumBarkConversionFunctions)(fBark);
}
References kNumBarkConversionFunctions, and m_BarkDispatchMap.
convertBark2FreqSchroeder()
float CConversion::convertBark2FreqSchroeder (float fBark) static protected
Definition at line 131 of file ToolConversion.cpp.
{
    assert(fBark > 0);
    return 650.F * std::sinh(fBark / 7.F);
}
convertBark2FreqTerhardt()
float CConversion::convertBark2FreqTerhardt (float fBark) static protected
Definition at line 142 of file ToolConversion.cpp.
{
    assert(fBark > 0);
    return 4.F / 3.F * 1000.F * std::tan(fBark / 13.3F);
}
convertBark2FreqTraunmuller()
float CConversion::convertBark2FreqTraunmuller (float fBark) static protected
Definition at line 163 of file ToolConversion.cpp.
{
    assert(fBark > 0);
    //return 1960.F * (fBark + 0.53F) / (26.81F - fBark);
    return 1960.F / (26.81F / (fBark + 0.53F) - 1.F);
}
convertBark2FreqZwicker()
float CConversion::convertBark2FreqZwicker (float fBark) static protected
Definition at line 153 of file ToolConversion.cpp.
{
    return -1.F;
}
convertBin2Freq() [1/2]
void CConversion::convertBin2Freq (float * pffInHz, const float * pfBin, int iLengthBuff, int iFftLength, float fSampleRate = 44100.F) static
converts an FFT bin vector to a frequency vector
Parameters
pffInHz frequency in Hz output buffer (length iLengthBuff, to be written)
pfBin input buffer with FFT bin indices (length iLengthBuff)
iLengthBuff length of buffers
iFftLength length of FFT
fSampleRate sample rate frequency in Hz
Definition at line 171 of file ToolConversion.cpp.
{
    assert(pfBin);
    assert(pffInHz);
    assert(iLengthBuff > 0);
    assert(iFftLength >= 0);
    assert(fSampleRate > 0);
    for (auto n = 0; n < iLengthBuff; n++)
        pffInHz[n] = convertBin2Freq(pfBin[n], iFftLength, fSampleRate);
}
References convertBin2Freq().
convertBin2Freq() [2/2]
static float CConversion::convertBin2Freq (float fBin, int iFftLength, float fSampleRate = 44100.F) inline static
converts a FFT bin index to a frequency scalar
Parameters
fBin FFT bin index
iFftLength length of FFT
fSampleRate sample rate frequency in Hz
Returns
frequency in Hz
Definition at line 204 of file ToolConversion.h.
    {
        assert(fBin >= 0);
        assert(iFftLength >= 0);
        assert(fBin < iFftLength);
        assert(fSampleRate > 0);
        return fBin * fSampleRate / static_cast<float>(iFftLength);
    };
Referenced by CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), convertBin2Freq(), CSpectrogramIf::generateMelFb_(), CFeatureSpectralMfccs::genMfccFilters_(), and CBeatHistoIf::getBeatHistoAxisTicks().
convertFloat2Word()
static uint32_t CConversion::convertFloat2Word (const float * pfVec) inline static
converts a float vector in a 32 bit word based on the sign
Parameters
pfVec vector of signed float values (length 32)
Returns
uint32_t 32 bit word
Definition at line 227 of file ToolConversion.h.
    {
        assert(pfVec);
        int iLength = 32;
        uint32_t iRes = 0;
        for (auto b = 0; b < iLength; b++)
        {
            if (pfVec[b] > 0)
                iRes += (1 << (b + 1));
        }
        return iRes;
    }
Referenced by CSubFingerprint::compSubFingerprint().
convertFreq2Bark() [1/2]
void CConversion::convertFreq2Bark (float * pfBark, const float * pffInHz, int iLengthBuff, BarkConversionFunctions_t eFunc = kSchroeder) static
converts a frequency array to a Bark array
Parameters
pfBark output Bark values (length iLenghBuff, to be written)
pffInHz input frequency values in Hz (length iLenghBuff)
iLengthBuff length of buffers
eFunc index for conversion function selection
Definition at line 105 of file ToolConversion.cpp.
{
    assert(pfBark);
    assert(pffInHz);
    assert(iLengthBuff > 0);
    for (auto k = 0; k < iLengthBuff; k++)
        pfBark[k] = m_BarkDispatchMap.at(eFunc)(pffInHz[k]);
}
References m_BarkDispatchMap.
convertFreq2Bark() [2/2]
float CConversion::convertFreq2Bark (float fInHz, BarkConversionFunctions_t eFunc = kSchroeder) static
converts a frequency scalar to a Bark value
Parameters
fInHz frequency in Hz
eFunc index for conversion function selection
Returns
Bark value
Definition at line 93 of file ToolConversion.cpp.
{
    assert(fInHz >= 0);
    return m_BarkDispatchMap.at(eFunc)(fInHz);
}
References m_BarkDispatchMap.
convertFreq2BarkSchroeder()
float CConversion::convertFreq2BarkSchroeder (float fFrequency) static protected
Definition at line 126 of file ToolConversion.cpp.
{
    assert(fFrequency > 0);
    return 7.F * std::asinh(fFrequency / 650.F);
}
convertFreq2BarkTerhardt()
float CConversion::convertFreq2BarkTerhardt (float fFrequency) static protected
Definition at line 137 of file ToolConversion.cpp.
{
    assert(fFrequency > 0);
    return 13.3F * std::atan(0.75F * fFrequency / 1000.F);
}
convertFreq2BarkTraunmuller()
float CConversion::convertFreq2BarkTraunmuller (float fFrequency) static protected
Definition at line 158 of file ToolConversion.cpp.
{
    assert(fFrequency > 0);
    return 26.81F / (1.F + 1960.F / fFrequency) - 0.53F;
}
convertFreq2BarkZwicker()
float CConversion::convertFreq2BarkZwicker (float fFrequency) static protected
Definition at line 148 of file ToolConversion.cpp.
{
    assert(fFrequency > 0);
    return 13.F * std::atan(0.76F  * fFrequency / 1000.F) + 3.5F * std::atan(fFrequency / 7500.F);
}
convertFreq2Bin() [1/2]
static void CConversion::convertFreq2Bin (float * pfBin, const float * pffInHz, int iLengthBuff, int iFftLength, float fSampleRate = 44100.F) inline static
converts a frequency vector into a FFT bin vector
Parameters
pfBin output buffer with FFT bin indices (length iLengthBuff, to be written)
pffInHz frequency in Hz input buffer (length iLengthBuff)
iLengthBuff length of buffers
iFftLength length of FFT
fSampleRate sample rate frequency in Hz
Definition at line 186 of file ToolConversion.h.
    {
        assert(pfBin);
        assert(pffInHz);
        assert(iLengthBuff > 0);
        assert(iFftLength >= 0);
        assert(fSampleRate > 0);
        for (auto n = 0; n < iLengthBuff; n++)
            pfBin[n] = convertFreq2Bin(pffInHz[n], iFftLength, fSampleRate);
    };
References convertFreq2Bin().
convertFreq2Bin() [2/2]
static float CConversion::convertFreq2Bin (float fInHz, int iFftLength, float fSampleRate = 44100.F) inline static
converts a frequency scalar to an FFT bin index
Parameters
fInHz frequency value in Hz
iFftLength length of FFT
fSampleRate sample rate frequency in Hz
Returns
bin index (float)
Definition at line 169 of file ToolConversion.h.
    {
        assert(fInHz >= 0);
        assert(iFftLength >= 0);
        assert(fInHz < fSampleRate);
        assert(fSampleRate > 0);
        return fInHz / fSampleRate * static_cast<float>(iFftLength);
    };
Referenced by CPitchSpectralAcf::compF0(), CPitchSpectralHps::compF0(), CBeatHistoIf::compHistoRange_(), convertFreq2Bin(), CSubFingerprint::genBands_(), CFeatureSpectralMfccs::genMfccFilters_(), and CFeatureSpectralPitchChroma::genPcFilters_().
convertFreq2Mel() [1/2]
void CConversion::convertFreq2Mel (float * pfMel, const float * pffInHz, int iLengthBuff, MelConversionFunctions_t eFunc = kFant) static
converts a frequency array to a mel array
Parameters
pfMel output mel values (length iLenghBuff, to be written)
pffInHz input frequency values in Hz (length iLenghBuff)
iLengthBuff length of buffers
eFunc index for conversion function selection
Returns
void
Definition at line 30 of file ToolConversion.cpp.
{
    assert(pfMel);
    assert(pffInHz);
    assert(iLengthBuff > 0);
    for (auto k = 0; k < iLengthBuff; k++)
        pfMel[k] = m_MelDispatchMap.at(eFunc)(pffInHz[k]);
}
References m_MelDispatchMap.
convertFreq2Mel() [2/2]
float CConversion::convertFreq2Mel (float fInHz, MelConversionFunctions_t eFunc = kFant) static
converts a frequency scalar to a mel value
Parameters
fInHz frequency in Hz
eFunc index for conversion function selection
Returns
mel value
Definition at line 18 of file ToolConversion.cpp.
{
    assert(fInHz >= 0);
    return m_MelDispatchMap.at(eFunc)(fInHz);
}
References m_MelDispatchMap.
Referenced by CSpectrogramIf::generateMelFb_().
convertFreq2MelFant()
float CConversion::convertFreq2MelFant (float fFrequency) static protected
Definition at line 50 of file ToolConversion.cpp.
{
    return 1000.F * std::log2(1.F + fFrequency / 1000.F);
}
convertFreq2MelShaughnessy()
float CConversion::convertFreq2MelShaughnessy (float fFrequency) static protected
Definition at line 60 of file ToolConversion.cpp.
{
    return 2595.F * std::log10(1.F + fFrequency / 700.F);
}
convertFreq2MelUmesh()
float CConversion::convertFreq2MelUmesh (float fFrequency) static protected
Definition at line 70 of file ToolConversion.cpp.
{
    return fFrequency / (2.4e-4F * fFrequency + 0.741F);
}
convertFreq2Midi() [1/2]
static void CConversion::convertFreq2Midi (float * pfMidi, const float * pffInHz, int iLengthBuff, float fA4InHz = 440.F) inline static
converts a frequency vector to midi (float)
Parameters
pfMidi output buffer (length iLengthBuff, to be written)
pffInHz input buffer with frequency values in Hz (length iLengthBuff)
iLengthBuff length of buffers
fA4InHz tuning (reference) frequency in Hz
Definition at line 122 of file ToolConversion.h.
    {
        assert(pfMidi);
        assert(pffInHz);
        assert(iLengthBuff > 0);
        assert(fA4InHz > 0);
        for (auto n = 0; n < iLengthBuff; n++)
            pfMidi[n] = convertFreq2Midi(pffInHz[n], fA4InHz);
    };
References convertFreq2Midi().
convertFreq2Midi() [2/2]
static float CConversion::convertFreq2Midi (float fInHz, float fA4InHz = 440.F) inline static
converts a frequency scalar to midi (float)
Parameters
fInHz frequency value in Hz
fA4InHz tuning (reference) frequency in Hz
Returns
Midi value
Definition at line 109 of file ToolConversion.h.
    {
        assert(fInHz > 0);
        assert(fA4InHz > 0);
        return 69.F + 12.F * std::log2(fInHz / fA4InHz);
    };
Referenced by convertFreq2Midi().
convertMel2Freq() [1/2]
void CConversion::convertMel2Freq (float * pffInHz, const float * pfMel, int iLengthBuff, MelConversionFunctions_t eFunc = kFant) static
converts a mel array to a frequency array
Parameters
pffInHz output frequency values in Hz (length iLenghBuff, to be written)
pfMel input mel values (length iLenghBuff)
iLengthBuff length of buffers
eFunc index for conversion function selection
Returns
void
Definition at line 40 of file ToolConversion.cpp.
{
    assert(pfMel);
    assert(pffInHz);
    assert(iLengthBuff > 0);
    for (auto k = 0; k < iLengthBuff; k++)
        pffInHz[k] = m_MelDispatchMap.at(eFunc + kNumMelConversionFunctions)(pfMel[k]);
}
References kNumMelConversionFunctions, and m_MelDispatchMap.
convertMel2Freq() [2/2]
float CConversion::convertMel2Freq (float fMel, MelConversionFunctions_t eFunc = kFant) static
converts a mel scalar to a frequency
Parameters
fMel mel value
eFunc index for conversion function selection
Returns
frequency value in Hz
Definition at line 24 of file ToolConversion.cpp.
{
    assert(fMel >= 0);
    return m_MelDispatchMap.at(eFunc + kNumMelConversionFunctions)(fMel);
}
References kNumMelConversionFunctions, and m_MelDispatchMap.
Referenced by CSpectrogramIf::generateMelFb_().
convertMel2FreqFant()
float CConversion::convertMel2FreqFant (float fMel) static protected
Definition at line 55 of file ToolConversion.cpp.
{
    return 1000.F * (std::exp2(fMel / 1000.F) - 1.F);
}
convertMel2FreqShaughnessy()
float CConversion::convertMel2FreqShaughnessy (float fMel) static protected
Definition at line 65 of file ToolConversion.cpp.
{
    return 700.F * (std::pow(10.F, fMel / 2595.F) - 1.F);
}
convertMel2FreqUmesh()
float CConversion::convertMel2FreqUmesh (float fMel) static protected
Definition at line 75 of file ToolConversion.cpp.
{
    return  fMel * 0.741F / (1.F - fMel * 2.4e-4F);
}
convertMidi2Freq() [1/2]
static void CConversion::convertMidi2Freq (float * pffInHz, const float * pfMidi, int iLengthBuff, float fA4InHz = 440.F) inline static
converts a midi vector to frequency
Parameters
pffInHz output buffer with frequency values in Hz (length iLengthBuff)
pfMidi input buffer (length iLengthBuff, to be written)
iLengthBuff length of buffers
fA4InHz tuning (reference) frequency in Hz
Definition at line 151 of file ToolConversion.h.
    {
        assert(pfMidi);
        assert(pffInHz);
        assert(iLengthBuff > 0);
        assert(fA4InHz > 0);
        for (auto n = 0; n < iLengthBuff; n++)
            pffInHz[n] = convertMidi2Freq(pfMidi[n], fA4InHz);
    };
References convertMidi2Freq().
convertMidi2Freq() [2/2]
static float CConversion::convertMidi2Freq (float fMidi, float fA4InHz = 440.F) inline static
converts a midi scalar to frequency
Parameters
fMidi value
fA4InHz tuning (reference) frequency in Hz
Returns
frequency value in Hz
Definition at line 138 of file ToolConversion.h.
    {
        assert(fMidi >= 0);
        assert(fA4InHz > 0);
        return fA4InHz * std::exp2((fMidi - 69.F) / 12.F);
    };
Referenced by convertMidi2Freq(), and CFeatureSpectralPitchChroma::genPcFilters_().
convertWord2Float()
static void CConversion::convertWord2Float (float * pfDest, uint32_t iWord) inline static
converts a 32 bit word into a float vector of -1.F and 1.F
Parameters
pfDest destination buffer (length 32, to be written)
iWord 32 bit word to be decoded
Definition at line 247 of file ToolConversion.h.
    {
        assert(pfDest);
        int iLength = 32;
        for (auto b = 0; b < iLength; b++)
        {
            if (iWord & (1 << (b + 1)))
                pfDest[b] = 1.F;
            else
                pfDest[b] = -1.F;
        }
    }
~CConversion()
virtual CConversion::~CConversion () inline private virtual
Definition at line 286 of file ToolConversion.h.
{};
Member Data Documentation
m_BarkDispatchMap
const std::map< int, std::function< float(float)> > CConversion::m_BarkDispatchMap static private
Initial value:
{
        {kSchroeder, &convertFreq2BarkSchroeder},
        {kTerhardt, &convertFreq2BarkTerhardt},
        {kZwicker, &convertFreq2BarkZwicker},
        {kTraunmuller, &convertFreq2BarkTraunmuller},
        {kSchroeder + kNumBarkConversionFunctions, &convertBark2FreqSchroeder},
        {kTerhardt + kNumBarkConversionFunctions, &convertBark2FreqTerhardt},
        {kZwicker + kNumBarkConversionFunctions, &convertBark2FreqZwicker},
        {kTraunmuller + kNumBarkConversionFunctions,&convertBark2FreqTraunmuller}
}
Definition at line 290 of file ToolConversion.h.
Referenced by convertBark2Freq(), and convertFreq2Bark().
m_MelDispatchMap
const std::map< int, std::function< float(float)> > CConversion::m_MelDispatchMap static private
Initial value:
{
        {kFant, &convertFreq2MelFant},
        {kShaughnessy, &convertFreq2MelShaughnessy},
        {kUmesh, &convertFreq2MelUmesh},
        {kFant + kNumMelConversionFunctions, &convertMel2FreqFant},
        {kShaughnessy + kNumMelConversionFunctions, &convertMel2FreqShaughnessy},
        {kUmesh + kNumMelConversionFunctions, &convertMel2FreqUmesh}
}
Definition at line 288 of file ToolConversion.h.
Referenced by convertFreq2Mel(), and convertMel2Freq().
The documentation for this class was generated from the following files:
ToolConversion.h
ToolConversion.cpp