ACA: CSinglePoleLp Class Reference
CSinglePoleLp Class Reference
class for single-pole low pass filtering
#include <ToolLowPass.h>
Public Member Functions
Error_t setFilterParam (float fAlpha=.9F)
float getFilterParam () const
Error_t process (float *pfOutput, const float *pfInput, long long iNumSamples)
Error_t reset ()
Static Public Member Functions
static Error_t create (CSinglePoleLp *&pCInstance)
static Error_t destroy (CSinglePoleLp *&pCInstance)
static float calcFilterParam (float fIntegrationTimeInS, float fSampleRate)
Private Member Functions
CSinglePoleLp ()
virtual ~CSinglePoleLp ()
CSinglePoleLp (const CSinglePoleLp &that)
CSinglePoleLp & operator= (const CSinglePoleLp &c)
Private Attributes
float m_fAlpha = 0.9F
filter coeff
float m_fPrevOut = 0.F
filter buffer
Detailed Description
class for single-pole low pass filtering
Definition at line 13 of file ToolLowPass.h.
Constructor & Destructor Documentation
CSinglePoleLp() [1/2]
CSinglePoleLp::CSinglePoleLp () inline private
Definition at line 109 of file ToolLowPass.h.
{};
Referenced by create().
CSinglePoleLp() [2/2]
CSinglePoleLp::CSinglePoleLp (const CSinglePoleLp & that) private
Member Function Documentation
calcFilterParam()
static float CSinglePoleLp::calcFilterParam (float fIntegrationTimeInS, float fSampleRate) inline static
compute the filter coeff from an "integration time"
Parameters
fIntegrationTimeInS integration time in seconds (the higher, the more low pass)
fSampleRate sample rate in Hz return float alpha
Definition at line 99 of file ToolLowPass.h.
    {
        assert(fSampleRate > 0);
        assert(fIntegrationTimeInS >= 0);
        if (fIntegrationTimeInS == 0)
            return 0.F;
        return std::exp(-2.2F / fSampleRate / fIntegrationTimeInS);
    }
Referenced by CFeatureTimePeakEnvelope::CFeatureTimePeakEnvelope(), and CFeatureTimeRms::CFeatureTimeRms().
create()
static Error_t CSinglePoleLp::create (CSinglePoleLp *& pCInstance) inline static
initializes a SinglePoleLp instance with file reading
Parameters
pCInstance pointer to instance to be written
Returns
Error_t
Definition at line 21 of file ToolLowPass.h.
    {
        pCInstance = new CSinglePoleLp();
        return Error_t::kNoError;
    }
References CSinglePoleLp(), and kNoError.
Referenced by CFeatureTimeRms::CFeatureTimeRms().
destroy()
static Error_t CSinglePoleLp::destroy (CSinglePoleLp *& pCInstance) inline static
destroys a SinglePoleLp instance
Parameters
pCInstance pointer to instance to be destroyed
Returns
Error_t
Definition at line 32 of file ToolLowPass.h.
    {
        delete pCInstance;
        pCInstance = 0;
        return Error_t::kNoError;
    }
References kNoError.
Referenced by CFeatureTimeRms::~CFeatureTimeRms().
getFilterParam()
float CSinglePoleLp::getFilterParam () const inline
returns the filter parameter alpha
Returns
float
Definition at line 57 of file ToolLowPass.h.
    {
        return m_fAlpha;
    }
References m_fAlpha.
operator=()
CSinglePoleLp & CSinglePoleLp::operator= (const CSinglePoleLp & c) private
process()
Error_t CSinglePoleLp::process (float * pfOutput, const float * pfInput, long long iNumSamples) inline
performs the SinglePoleLp computation
Parameters
pfOutput filter result (user-allocated, to be written, length iNumSamples)
pfInput input data of length iNumSamples
iNumSamples length of buffers return Error_t
Definition at line 68 of file ToolLowPass.h.
    {
        if (!pfOutput || !pfInput || iNumSamples <= 0)
            return Error_t::kFunctionInvalidArgsError;
        pfOutput[0] = (1.F - m_fAlpha) * pfInput[0] + m_fAlpha * m_fPrevOut;
        for (auto i = 1; i < iNumSamples; i++)
            pfOutput[i] = (1 - m_fAlpha) * pfInput[0] + m_fAlpha * pfOutput[i-1];
        m_fPrevOut = pfOutput[iNumSamples - 1];
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, kNoError, m_fAlpha, and m_fPrevOut.
Referenced by CFeatureTimeRms::compFeature().
reset()
Error_t CSinglePoleLp::reset () inline
clears internal buffers and sets parameters to default
Returns
Error_t
Definition at line 86 of file ToolLowPass.h.
    {
        m_fAlpha = .9F;
        m_fPrevOut = 0.F;
        return Error_t::kNoError;
    }
References kNoError, m_fAlpha, and m_fPrevOut.
setFilterParam()
Error_t CSinglePoleLp::setFilterParam (float fAlpha = .9F) inline
set the filter parameter
Parameters
fAlpha filter coeff (0 <= fAlpha < 1, the higher the more lowpass)
Returns
Error_t
Definition at line 44 of file ToolLowPass.h.
    {
        if (fAlpha < 0 || fAlpha >= 1)
            return Error_t::kFunctionInvalidArgsError;
        m_fAlpha = fAlpha;
        return Error_t::kNoError;
    }
References kFunctionInvalidArgsError, kNoError, and m_fAlpha.
Referenced by CFeatureTimeRms::CFeatureTimeRms().
~CSinglePoleLp()
virtual CSinglePoleLp::~CSinglePoleLp () inline private virtual
Definition at line 110 of file ToolLowPass.h.
{};
Member Data Documentation
m_fAlpha
float CSinglePoleLp::m_fAlpha = 0.9F private
filter coeff
Definition at line 114 of file ToolLowPass.h.
Referenced by getFilterParam(), process(), reset(), and setFilterParam().
m_fPrevOut
float CSinglePoleLp::m_fPrevOut = 0.F private
filter buffer
Definition at line 116 of file ToolLowPass.h.
Referenced by process(), and reset().
The documentation for this class was generated from the following file:
ToolLowPass.h