ACA: CPca Class Reference
CPca Class Reference
computation of principal component analysis
#include <ToolPca.h>
Public Member Functions
CPca (void)
virtual ~CPca (void)
Error_t init (int iNumFeatures, int iNumObservations)
Error_t reset ()
Error_t compPca (float **ppfRes, float *pfEigenValues, float **ppfIn)
Static Public Member Functions
static Error_t compCov (float **ppfCovOut, float **ppfIn, int iNumRows, int iNumCols)
static Error_t calcSVD (float **ppfU, float **ppfW, float **ppfV, float **ppfMat, int iNumRows, int iNumCols, int iMaxIterations=100)
Private Member Functions
CPca (const CPca &that)
disallow copy construction
CPca & operator= (const CPca &c)
Static Private Member Functions
static float matPythag (float dA, float dB)
Private Attributes
int m_iNumFeatures = 0
number of features
int m_iNumObs = 0
number of observations
float ** m_ppfProcTmp = 0
temporary processing memoru
float ** m_ppfU = 0
SVD result: U.
float ** m_ppfW = 0
SVD result: W.
float ** m_ppfV = 0
SVD result: V.
int * piSortIndices = 0
array for sorted indices
Detailed Description
computation of principal component analysis
Definition at line 10 of file ToolPca.h.
Constructor & Destructor Documentation
CPca() [1/2]
CPca::CPca (void) inline
Definition at line 13 of file ToolPca.h.
{};
~CPca()
CPca::~CPca (void) virtual
Definition at line 7 of file ToolPca.cpp.
{ reset(); }
References reset().
CPca() [2/2]
CPca::CPca (const CPca & that) private
disallow copy construction
Member Function Documentation
calcSVD()
Error_t CPca::calcSVD (float ** ppfU, float ** ppfW, float ** ppfV, float ** ppfMat, int iNumRows, int iNumCols, int iMaxIterations = 100) static
computes singular value decomposition (ppfMat = ppfU * ppfW * ppfV)
Parameters
ppfU (user-allocated, to be written, dimension iNumRows X iNumCols)
ppfW (user-allocated, to be written, dimension iNumCols X iNumCols)
ppfV (user-allocated, to be written, dimension iNumCols X iNumCols)
ppfMat input matrix (dimension iNumRows X iNumCols)
iNumRows number of rows in the input matrix
iNumCols number of columns/in the input matrix
iMaxIterations maximum number of iterations
Returns
Error_t
Definition at line 100 of file ToolPca.cpp.
{
    int        i, k, l = 0;
    float* pdRV1;
    float    dTmp,
        dF,
        dH,
        dS,
        dNorm = 0,
        dG = 0,
        dScale = 0;
    if (iNumRows < iNumCols)
        return Error_t::kFunctionIllegalCallError;
    CVector::alloc(pdRV1, iNumCols);
    if (!pdRV1)
        return Error_t::kMemError;
    //rErr = ppfW->SetDimensions(1, iNumCols);
    //rErr = ppfV->SetDimensions(iNumCols, iNumCols);
    CMatrix::setZero(ppfU, iNumRows, iNumCols);
    CMatrix::setZero(ppfW, iNumCols, iNumCols);
    CMatrix::setZero(ppfV, iNumCols, iNumCols);
    CMatrix::copy(ppfU, ppfMat, iNumRows, iNumCols);
    for (i = 0; i < iNumCols; i++)
    {
        l = i + 1;
        pdRV1[i] = dScale * dG;
        dG = 0;
        dS = 0;
        dScale = 0;
        if (i < iNumRows)
        {
            for (k = i; k < iNumRows; k++)
                dScale += fabs(ppfU[k][i]);
            if (dScale)
            {
                for (auto j = i; j < iNumRows; j++)
                    ppfU[j][i] *= 1 / dScale;
                for (k = i; k < iNumRows; k++)
                {
                    dTmp = ppfU[k][i];
                    dS += dTmp * dTmp;
                }
                dF = ppfU[i][i];
                dG = std::sqrt(dS);
                if (dF >= 0)
                    dG *= -1;
                dH = dF * dG - dS;
                ppfU[i][i] = dF - dG;
                if (i != iNumCols)
                {
                    for (auto j = l; j < iNumCols; j++)
                    {
                        dS = 0;
                        for (k = i; k < iNumRows; k++)
                            dS += ppfU[k][i] * ppfU[k][j];
                        dF = dS / dH;
                        for (k = i; k < iNumRows; k++)
                            ppfU[k][j] += dF * ppfU[k][i];
                    }
                }
                for (auto j = i; j < iNumRows; j++)
                    ppfU[j][i] *= dScale;
            }
        }
        ppfW[i][i] = dScale * dG;
        dG = 0;
        dS = 0;
        dScale = 0;
        if ((i <= iNumRows) && (i != iNumCols))
        {
            for (k = l; k < iNumCols; k++)
                dScale += fabs(ppfU[i][k]);
            if (dScale)
            {
                //RowMultC(i, l, 1 / dScale);
                for (auto j = l; j < iNumCols; j++)
                    ppfU[i][j] *= 1 / dScale;
                for (k = l; k < iNumCols; k++)
                {
                    dTmp = ppfU[i][k];
                    dS += dTmp * dTmp;
                }
                dF = ppfU[i][l];
                //dG = -MHLP_SIGN(sqrt(dS), dF);
                dG = std::sqrt(dS);
                if (dF >= 0)
                    dG *= -1;
                dH = dF * dG - dS;
                ppfU[i][l] = dF - dG;
                for (k = l; k < iNumCols; k++)
                    pdRV1[k] = ppfU[i][k] / dH;
                if (i != iNumRows)
                {
                    for (auto j = l; j < iNumRows; j++)
                    {
                        dS = 0;
                        for (k = l; k < iNumCols; k++)
                            dS += ppfU[j][k] * ppfU[i][k];
                        for (k = l; k < iNumCols; k++)
                            ppfU[j][k] += dS * pdRV1[k];
                    }
                }
                //RowMultC(i, l, dScale);
                for (auto j = l; j < iNumCols; j++)
                    ppfU[i][j] *= dScale;
            }
        }
        dTmp = fabs(ppfW[i][i]) + fabs(pdRV1[i]);
        dNorm = std::max(dNorm, dTmp);
    }
    for (i = iNumCols - 1; i >= 0; i--)
    {
        if (i < iNumCols)
        {
            if (dG)
            {
                for (auto j = l; j < iNumCols; j++)
                {
                    dTmp = ppfU[i][j] / ppfU[i][l];
                    ppfV[j][i] = dTmp / dG;
                }
                for (auto j = l; j < iNumCols; j++)
                {
                    dS = 0;
                    for (k = l; k < iNumCols; k++)
                        dS += ppfU[i][k] * ppfV[k][j];
                    for (k = l; k < iNumCols; k++)
                        ppfV[k][j] += dS * ppfV[k][i];
                }
            }
            for (auto j = l; j < iNumCols; j++)
            {
                ppfV[i][j] = 0;
                ppfV[j][i] = 0;
            }
        }
        ppfV[i][i] = 1;
        dG = pdRV1[i];
        l = i;
    }
    for (i = iNumCols - 1; i >= 0; i--)
    {
        l = i + 1;
        dG = ppfW[i][i];
        if (i < iNumCols)
        {    //RowMultC(i, l, 0);
            for (auto j = l; j < iNumCols; j++)
                ppfU[i][j] = 0;
        }
        if (dG)
        {
            dG = 1.F / dG;
            if (i != iNumCols)
            {
                for (auto j = l; j < iNumCols; j++)
                {
                    dS = 0;
                    for (k = l; k < iNumRows; k++)
                        dS += ppfU[k][i] * ppfU[k][j];
                    dF = (dS / ppfU[i][i]) * dG;
                    for (k = i; k < iNumRows; k++)
                        ppfU[k][j] += dF * ppfU[k][i];
                }
            }
        }
        //ColMultC(i, i, dG);
        for (auto j = i; j < iNumRows; j++)
            ppfU[j][i] *= dG;
        ppfU[i][i] += 1;
    }
    for (k = iNumCols - 1; k >= 0; k--)
    {
        for (int iIter = 0; iIter < iMaxIterations; iIter++)
        {
            float    dC, dX, dY, dZ;
            int        iNM = 0,
                iFlag = 1;
            for (l = k; l >= 0; l--)
            {
                iNM = l - 1;
                if (fabs(pdRV1[l]) + dNorm == dNorm)
                {
                    iFlag = 0;
                    break;
                }
                if (fabs(ppfW[iNM][iNM]) + dNorm == dNorm)
                    break;
            }
            if (iFlag)
            {
                dC = 0.0;
                dS = 1.0;
                for (i = l; i <= k; i++)
                {
                    dF = dS * pdRV1[i];
                    if (fabs(dF) + dNorm != dNorm)
                    {
                        dG = ppfW[i][i];
                        dH = matPythag(dF, dG);
                        ppfW[i][i] = dH;
                        dH = 1.F / dH;
                        dC = dG * dH;
                        dS = (-dF * dH);
                        for (auto j = 0; j < iNumRows; j++)
{
                            dY = ppfU[j][iNM];
                            dZ = ppfU[j][i];
                            ppfU[j][iNM] = dY * dC + dZ * dS;
                            ppfU[j][i] = dZ * dC - dY * dS;
                        }
                    }
                }
            }
            dZ = ppfW[k][k];
            if (l == k)
            {
                if (dZ < 0)
                {
                    ppfW[k][k] = -dZ;
                    for (auto j = 0; j < iNumCols; j++)
                        ppfV[j][k] *= -1;
                }
                break;
            }
            if (iIter >= iMaxIterations)
                return Error_t::kUnknownError;
            dX = ppfW[l][l];
            iNM = k - 1;
            dY = ppfW[iNM][iNM];
            dG = pdRV1[iNM];
            dH = pdRV1[k];
            dF = ((dY - dZ) * (dY + dZ) + (dG - dH) * (dG + dH)) / (2.F * dH * dY);
            dG = matPythag(dF, 1.);
            //dF = ((dX - dZ) * (dX + dZ) + dH * ((dY / (dF + MHLP_SIGN(dG, dF))) - dH)) / dX;
            dF = ((dX - dZ) * (dX + dZ) + dH * ((dY / (dF + (dF >= 0 ? fabs(dG) : -fabs(dG)))) - dH)) / dX;
            dC = 1;
            dS = 1;
            for (auto j = l; j <= iNM; j++)
            {
                int jj;
                i = j + 1;
                dG = pdRV1[i];
                dY = ppfW[i][i];
                dH = dS * dG;
                dG = dC * dG;
                dZ = matPythag(dF, dH);
                pdRV1[j] = dZ;
                dC = dF / dZ;
                dS = dH / dZ;
                dF = (dX * dC) + (dG * dS);
                dG = (dG * dC) - (dX * dS);
                dH = dY * dS;
                dY = dY * dC;
                for (jj = 0; jj < iNumCols; jj++)
                {
                    dX = ppfV[jj][j];
                    dZ = ppfV[jj][i];
                    ppfV[jj][j] = dX * dC + dZ * dS;
                    ppfV[jj][i] = dZ * dC - dX * dS;
                }
                dZ = matPythag(dF, dH);
                ppfW[j][j] = dZ;
                if (dZ)
                {
                    dZ = 1.F / dZ;
                    dC = dF * dZ;
                    dS = dH * dZ;
                }
                dF = (dC * dG) + (dS * dY);
                dX = (dC * dY) - (dS * dG);
                for (jj = 0; jj < iNumRows; jj++)
                {
                    dY = ppfU[jj][j];
                    dZ = ppfU[jj][i];
                    ppfU[jj][j] = dY * dC + dZ * dS;
                    ppfU[jj][i] = dZ * dC - dY * dS;
                }
            }
            pdRV1[l] = 0;
            pdRV1[k] = dF;
            ppfW[k][k] = dX;
        }
    }
    CVector::free(pdRV1);
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::copy(), CVector::free(), kFunctionIllegalCallError, kMemError, kNoError, kUnknownError, matPythag(), and CMatrix::setZero().
Referenced by compPca().
compCov()
Error_t CPca::compCov (float ** ppfCovOut, float ** ppfIn, int iNumRows, int iNumCols) static
computes covariance matrix
Parameters
ppfCovOut resulting covariance matrix (user-allocated, to be written, dimension iNumRows X iNumRows)
ppfIn input matrix (dimensions iNumRows X iNumCols), each row is a variable
iNumRows number of rows/features in the input matrix
iNumCols number of columns/observations in the input matrix
Returns
Error_t
Definition at line 72 of file ToolPca.cpp.
{
    if (iNumRows <= 1 || iNumCols <= 1)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfIn || !ppfCovOut)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfIn[0] || !ppfCovOut[0])
        return Error_t::kFunctionInvalidArgsError;
    CMatrix::setZero(ppfCovOut, iNumRows, iNumRows);
    for (auto m = 0; m < iNumRows; m++)
    {
        float fMean1 = CVector::getMean(ppfIn[m], iNumCols);
        for (auto n = 0; n <= m; n++)
        {
            float fMean2 = CVector::getMean(ppfIn[n], iNumCols);
            ppfCovOut[m][n] = 0;
            for (auto j = 0; j < iNumCols; j++)
                ppfCovOut[m][n] += (ppfIn[m][j] - fMean1) * (ppfIn[n][j] - fMean2);
            ppfCovOut[n][m] = ppfCovOut[m][n];
        }
    }
    CMatrix::mulC_I(ppfCovOut, 1.F / (iNumCols - 1), iNumRows, iNumRows);
    return Error_t::kNoError;
}
References CVector::getMean(), kFunctionInvalidArgsError, kNoError, CMatrix::mulC_I(), and CMatrix::setZero().
Referenced by compPca(), and CGmm::initState_().
compPca()
Error_t CPca::compPca (float ** ppfRes, float * pfEigenValues, float ** ppfIn)
computes the principal components
Parameters
ppfRes matrix with principal components (user-allocated, to be written, dimensions equal input matrix)
pfEigenValues eigenvalues of principle components (user-allocated, to be written, length equals number of features)
ppfIn input matrix (dimensions iNumFeatures X iNumObservations)
Returns
Error_t
Definition at line 39 of file ToolPca.cpp.
{
    if (m_iNumFeatures <= 1 || m_iNumObs <= 1)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfIn || !ppfRes || !pfEigenValues)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfIn[0] || !ppfRes[0])
        return Error_t::kFunctionInvalidArgsError;
    compCov(m_ppfProcTmp, ppfIn, m_iNumFeatures, m_iNumObs);
    calcSVD(m_ppfU, m_ppfW, m_ppfV, m_ppfProcTmp, m_iNumFeatures, m_iNumFeatures);
    // extract eigenvalues
    CMatrix::diag(pfEigenValues, m_ppfW, m_iNumFeatures, m_iNumFeatures);
    // sort eigenvalues
    CVector::sort_I(pfEigenValues, piSortIndices, m_iNumFeatures, false);
    // transpose T
    CMatrix::transpose(m_ppfProcTmp, m_ppfV, m_iNumFeatures, m_iNumFeatures);
    // rearrange transformation matrix
    CMatrix::rearrangeRows(m_ppfProcTmp, piSortIndices, m_iNumFeatures);
    //compute components
    CMatrix::mulMatMat(ppfRes, m_ppfProcTmp, ppfIn, m_iNumFeatures, m_iNumFeatures, m_iNumFeatures, m_iNumObs);
    return Error_t::kNoError;
}
References calcSVD(), compCov(), CMatrix::diag(), kFunctionInvalidArgsError, kNoError, m_iNumFeatures, m_iNumObs, m_ppfProcTmp, m_ppfU, m_ppfV, m_ppfW, CMatrix::mulMatMat(), piSortIndices, CMatrix::rearrangeRows(), CVector::sort_I(), and CMatrix::transpose().
init()
Error_t CPca::init (int iNumFeatures, int iNumObservations)
initializes PCA instance
Parameters
iNumFeatures number of rows in the input and output matrices
iNumObservations number of columns in the input and output matrices
Returns
Error_t
Definition at line 9 of file ToolPca.cpp.
{
    if (iNumFeatures <= 0 || iNumObservations <= 0)
        return Error_t::kFunctionInvalidArgsError;
    m_iNumFeatures = iNumFeatures;
    m_iNumObs = iNumObservations;
    CMatrix::alloc(m_ppfProcTmp, m_iNumFeatures, m_iNumFeatures);
    CMatrix::alloc(m_ppfU, m_iNumFeatures, m_iNumFeatures);
    CMatrix::alloc(m_ppfW, m_iNumFeatures, m_iNumFeatures);
    CMatrix::alloc(m_ppfV, m_iNumFeatures, m_iNumFeatures);
    CVector::alloc(piSortIndices, m_iNumFeatures);
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), kFunctionInvalidArgsError, kNoError, m_iNumFeatures, m_iNumObs, m_ppfProcTmp, m_ppfU, m_ppfV, m_ppfW, and piSortIndices.
matPythag()
float CPca::matPythag (float dA, float dB) static private
Definition at line 427 of file ToolPca.cpp.
{
    float    dC,
        dMult;
    if (fabs(dA) > fabs(dB))
    {
        dC = dB / dA;
        dMult = dA;
    }
    else
    {
        if (!dB)
            return 0;
        dC = dA / dB;
        dMult = dB;
    }
    return (dMult * std::sqrt(1 + (dC * dC)));
}
Referenced by calcSVD().
operator=()
CPca & CPca::operator= (const CPca & c) private
reset()
Error_t CPca::reset (void)
resets PCA instance
Returns
Error_t
Definition at line 27 of file ToolPca.cpp.
{
    CMatrix::free(m_ppfProcTmp, m_iNumFeatures);
    CMatrix::free(m_ppfU, m_iNumFeatures);
    CMatrix::free(m_ppfW, m_iNumFeatures);
    CMatrix::free(m_ppfV, m_iNumFeatures);
    CVector::free(piSortIndices);
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kNoError, m_iNumFeatures, m_ppfProcTmp, m_ppfU, m_ppfV, m_ppfW, and piSortIndices.
Referenced by ~CPca().
Member Data Documentation
m_iNumFeatures
int CPca::m_iNumFeatures = 0 private
number of features
Definition at line 66 of file ToolPca.h.
Referenced by compPca(), init(), and reset().
m_iNumObs
int CPca::m_iNumObs = 0 private
number of observations
Definition at line 67 of file ToolPca.h.
Referenced by compPca(), and init().
m_ppfProcTmp
float** CPca::m_ppfProcTmp = 0 private
temporary processing memoru
Definition at line 69 of file ToolPca.h.
Referenced by compPca(), init(), and reset().
m_ppfU
float** CPca::m_ppfU = 0 private
SVD result: U.
Definition at line 70 of file ToolPca.h.
Referenced by compPca(), init(), and reset().
m_ppfV
float** CPca::m_ppfV = 0 private
SVD result: V.
Definition at line 72 of file ToolPca.h.
Referenced by compPca(), init(), and reset().
m_ppfW
float** CPca::m_ppfW = 0 private
SVD result: W.
Definition at line 71 of file ToolPca.h.
Referenced by compPca(), init(), and reset().
piSortIndices
int* CPca::piSortIndices = 0 private
array for sorted indices
Definition at line 73 of file ToolPca.h.
Referenced by compPca(), init(), and reset().
The documentation for this class was generated from the following files:
ToolPca.h
ToolPca.cpp