ACA: CPreProc Class Reference
CPreProc Class Reference
class with static utility functions for pre-processing
#include <ToolPreProc.h>
Static Public Member Functions
static void downmix (float *pfOut, const float *const *const ppfIn, int iNumChannels, long long iNumSamples)
Detailed Description
class with static utility functions for pre-processing
Definition at line 13 of file ToolPreProc.h.
Member Function Documentation
downmix()
static void CPreProc::downmix (float * pfOut, const float *const *const ppfIn, int iNumChannels, long long iNumSamples) inline static
downmixes multichannel audio (can be inplace
Definition at line 18 of file ToolPreProc.h.
    {
        // sanity checks
        assert(pfOut);
        assert(ppfIn);
        assert(ppfIn[0]);
        assert(iNumChannels > 0);
        assert(iNumSamples > 0);
        // copy in case of not inplace processing
        if (pfOut != ppfIn[0])
            CVector::copy(pfOut, ppfIn[0], iNumSamples);
        // downmix
        for (auto c = 1; c < iNumChannels; c++)
            CVector::add_I(pfOut, ppfIn[c], iNumSamples);
        CVector::mulC_I(pfOut, 1.F / iNumChannels, iNumSamples);
        return;
    }
References CVector::add_I(), CVector::copy(), and CVector::mulC_I().
Referenced by CNormalizeAudio::CNormalizeAudio(), CFingerprint::init(), and CBlockAudioFile::readFile2RingBuff().
The documentation for this class was generated from the following file:
ToolPreProc.h