ACA: CKnn Class Reference
CKnn Class Reference
computation of k nearest neighbor
#include <ToolSimpleKnn.h>
Public Member Functions
CKnn (void)
virtual ~CKnn (void)
Error_t init (float **ppfTrainFeatures, const int *piTrainClassIndices, int iNumFeatures, int iNumObservations, CClassifierBase::Normalization_t eNorm=CClassifierBase::kNoNormalization) override
Error_t reset () override
Error_t setParamK (int iK=3)
int getParamK () const
int classify (const float *pfQuery) override
virtual Error_t init (float **ppfTrainFeatures, const int *piTrainClassIndices, int iNumFeatures, int iNumObservations, Normalization_t eNorm)=0
virtual Error_t reset ()=0
virtual int classify (const float *pfQuery)=0
Private Member Functions
CKnn (const CKnn &that)
disallow copy construction
CKnn & operator= (const CKnn &c)
void buildHistogram_ (bool bUseDistance)
int countMaxima_ ()
Private Attributes
int m_iNumFeatures = 0
number of features
int m_iNumObs = 0
number of training observations
int m_iK = 3
number of neighbors for classification
float ** m_ppfTrain = 0
train data (m_iNumObs X m_iNumFeatures)
int * m_piClassLabels = 0
ground truth train labels
float * m_pfDist = 0
preallocated vector for distance of query to all data points
float * m_pfQuery = 0
preallocated vector for the normalized query
int * m_piSortIdx = 0
preallocated vector for the resorted class indices
float * m_pfHist = 0
preallocated vector for the histogram of nearest neighbors
int * m_piHistLabel = 0
preallocated vector holding the histogram class labels
float * m_pfNormScale = 0
scaling constant for normalization (length m_iNumFeatures)
float * m_pfNormSub = 0
offset for normalization (length m_iNumFeatures)
bool m_bIsInitialized = false
indicates if instance has been properly initialized
Additional Inherited Members
Public Types inherited from CClassifierBase
enum Normalization_t { kNoNormalization , kZscoreNormalization , kMinmaxNormalization , kNumNormModes }
Static Public Attributes inherited from CClassifierBase
static const int kIllegalClassLabel = -1111111111
Detailed Description
computation of k nearest neighbor
Definition at line 34 of file ToolSimpleKnn.h.
Constructor & Destructor Documentation
CKnn() [1/2]
CKnn::CKnn (void) inline
Definition at line 37 of file ToolSimpleKnn.h.
{};
~CKnn()
CKnn::~CKnn (void) virtual
Definition at line 10 of file ToolSimpleKnn.cpp.
{
    this->reset();
}
References reset().
CKnn() [2/2]
CKnn::CKnn (const CKnn & that) private
disallow copy construction
Member Function Documentation
buildHistogram_()
void CKnn::buildHistogram_ (bool bUseDistance) private
Definition at line 162 of file ToolSimpleKnn.cpp.
{
    int iNumLabelsInK = 0;
    CVector::setValue(m_piHistLabel, kIllegalClassLabel, m_iK);
    m_piHistLabel[0] = m_piClassLabels[m_piSortIdx[0]];
    m_pfHist[0] += 1;
    iNumLabelsInK++;
    for (auto k = 1; k < m_iK; k++)
    {
        bool bContinue = false;
        for (auto l = 0; l < iNumLabelsInK; l++)
        {
            if (m_piHistLabel[l] == m_piClassLabels[m_piSortIdx[k]])
            {
                m_pfHist[l] += bUseDistance ? m_pfDist[m_piSortIdx[k]] : 1.F;
                bContinue = true;
                break;
            }
        }
        if (bContinue)
            continue;
        m_piHistLabel[iNumLabelsInK] = m_piClassLabels[m_piSortIdx[k]];
        m_pfHist[iNumLabelsInK] += 1;
        iNumLabelsInK++;
    }
}
References CClassifierBase::kIllegalClassLabel, m_iK, m_pfDist, m_pfHist, m_piClassLabels, m_piHistLabel, m_piSortIdx, and CVector::setValue().
Referenced by classify().
classify()
int CKnn::classify (const float * pfQuery) override virtual
classifies a new query vector
Parameters
pfQuery vector of length iNumFeatures to classify
Returns
int class label of most likely class (returns CClassifierBase::kIllegalClassLabel in case of error)
< remember m_iK
Implements CClassifierBase.
Definition at line 126 of file ToolSimpleKnn.cpp.
{
    if (!pfQuery || !m_bIsInitialized)
        return kIllegalClassLabel;
    // normalize
    CVector::copy(m_pfQuery, pfQuery, m_iNumFeatures);
    CVector::sub_I(m_pfQuery, m_pfNormSub, m_iNumFeatures);
    CVector::mul_I(m_pfQuery, m_pfNormScale, m_iNumFeatures);
    // compute distance to all training observations
    for (auto n = 0; n < m_iNumObs; n++)
        m_pfDist[n] = CVector::distEuclidean(pfQuery, m_ppfTrain[n], m_iNumFeatures);
    // sort distances
    CVector::sort_I(m_pfDist, m_piSortIdx, m_iNumObs);
    // take care of weird scenarios
    if (m_iK > m_iNumObs)
        m_iK = m_iNumObs;
    // create histogram
    buildHistogram_(false);
    // handle multiple maxima (first, use distances, then, reduce K)
    int iK = m_iK;  //!< remember m_iK
    while (countMaxima_() > 1)
    {
        buildHistogram_(true);
        m_iK--;
    }
    m_iK = iK;
    return m_piHistLabel[0];
}
References buildHistogram_(), CVector::copy(), countMaxima_(), CVector::distEuclidean(), CClassifierBase::kIllegalClassLabel, m_bIsInitialized, m_iK, m_iNumFeatures, m_iNumObs, m_pfDist, m_pfNormScale, m_pfNormSub, m_pfQuery, m_piHistLabel, m_piSortIdx, m_ppfTrain, CVector::mul_I(), CVector::sort_I(), and CVector::sub_I().
countMaxima_()
int CKnn::countMaxima_ () private
Definition at line 189 of file ToolSimpleKnn.cpp.
{
    int iNumMax = 0;
    float fMax = 0;
    long long iMax = 0;
    CVector::findMax(m_pfHist, fMax, iMax, m_iK);
    CUtil::swap(m_pfHist[iNumMax], m_pfHist[iMax]);
    CUtil::swap(m_piHistLabel[iNumMax], m_piHistLabel[iMax]);
    iNumMax++;
    for (auto k = 1; k < m_iK; k++)
    {
        if (m_pfHist[k] >= fMax)
        {
            CUtil::swap(m_pfHist[iNumMax], m_pfHist[k]);
            CUtil::swap(m_piHistLabel[iNumMax], m_piHistLabel[k]);
            iNumMax++;
        }
    }
    return iNumMax;
}
References CVector::findMax(), m_iK, m_pfHist, m_piHistLabel, and CUtil::swap().
Referenced by classify().
getParamK()
int CKnn::getParamK () const
returns the parameter K
Returns
int iK
Definition at line 121 of file ToolSimpleKnn.cpp.
{
    return m_iK;
}
References m_iK.
init()
Error_t CKnn::init (float ** ppfTrainFeatures, const int * piTrainClassIndices, int iNumFeatures, int iNumObservations, CClassifierBase::Normalization_t eNorm = CClassifierBase::kNoNormalization) override virtual
initializes Knn instance
Parameters
ppfTrainFeatures feature data for 'training' (dimensions iNumFeatures X iNumObservations)
piTrainClassIndices ground truth class index for each observation
iNumFeatures number of features (rows in the input matrix)
iNumObservations number of observations (columns in the feature matrix)
eNorm specification of what normalization should be applied to the feature data
Returns
Error_t
Implements CClassifierBase.
Definition at line 15 of file ToolSimpleKnn.cpp.
{
    if (!ppfTrainFeatures || !piTrainClassIndices)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfTrainFeatures[0])
        return Error_t::kFunctionInvalidArgsError;
    if (iNumFeatures <= 0 || iNumObservations <= 1)
        return Error_t::kFunctionInvalidArgsError;
    m_iNumObs = iNumObservations;
    m_iNumFeatures = iNumFeatures;
    CVector::alloc(m_piClassLabels, m_iNumObs);
    CVector::alloc(m_piSortIdx, m_iNumObs);
    CVector::alloc(m_pfDist, m_iNumObs);
    CMatrix::alloc(m_ppfTrain, m_iNumObs, m_iNumFeatures);
    CVector::alloc(m_pfQuery, m_iNumFeatures);
    CVector::alloc(m_pfHist, m_iK);
    CVector::alloc(m_piHistLabel, m_iK);
    CVector::alloc(m_pfNormScale, m_iNumFeatures);
    CVector::alloc(m_pfNormSub, m_iNumFeatures);
    CVector::copy(m_piClassLabels, piTrainClassIndices, m_iNumObs);
    // note we store this transposed - that's easier for the distance computation
    CMatrix::transpose(m_ppfTrain, ppfTrainFeatures, m_iNumFeatures, m_iNumObs);
    // normaization constants
    if (eNorm == kZscoreNormalization)
    {
        for (auto f = 0; f < m_iNumFeatures; f++)
        {
            m_pfNormSub[f] = CVector::getMean(ppfTrainFeatures[f], m_iNumObs);
            m_pfNormScale[f] = CVector::getStd(ppfTrainFeatures[f], m_iNumObs, m_pfNormSub[f]);
            if (m_pfNormScale[f] > 0)
                m_pfNormScale[f] = 1.F / m_pfNormScale[f];
        }
    }
    else if (eNorm == kMinmaxNormalization)
    {
        for (auto f = 0; f < m_iNumFeatures; f++)
        {
            m_pfNormSub[f] = CVector::getMin(ppfTrainFeatures[f], m_iNumObs);
            m_pfNormScale[f] = CVector::getMax(ppfTrainFeatures[f], m_iNumObs) - m_pfNormSub[f];
            if (m_pfNormScale[f] != 0)
                m_pfNormScale[f] = 1.F / m_pfNormScale[f];
        }
    }
    else
    {
        CVector::setValue(m_pfNormScale, 1.F, m_iNumFeatures);
        CVector::setZero(m_pfNormSub, m_iNumFeatures);
    }
    // normalize features
    for (auto n = 0; n < m_iNumObs; n++)
    {
        CVector::sub_I(m_ppfTrain[n], m_pfNormSub, m_iNumFeatures);
        CVector::mul_I(m_ppfTrain[n], m_pfNormScale, m_iNumFeatures);
    }
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), CVector::copy(), CVector::getMax(), CVector::getMean(), CVector::getMin(), CVector::getStd(), kFunctionInvalidArgsError, CClassifierBase::kMinmaxNormalization, kNoError, CClassifierBase::kZscoreNormalization, m_bIsInitialized, m_iK, m_iNumFeatures, m_iNumObs, m_pfDist, m_pfHist, m_pfNormScale, m_pfNormSub, m_pfQuery, m_piClassLabels, m_piHistLabel, m_piSortIdx, m_ppfTrain, CVector::mul_I(), CVector::setValue(), CVector::setZero(), CVector::sub_I(), and CMatrix::transpose().
operator=()
CKnn & CKnn::operator= (const CKnn & c) private
reset()
Error_t CKnn::reset (void) override virtual
resets Knn instance
Returns
Error_t
Implements CClassifierBase.
Definition at line 87 of file ToolSimpleKnn.cpp.
{
    CVector::free(m_piClassLabels);
    CVector::free(m_piSortIdx);
    CVector::free(m_pfDist);
    CMatrix::free(m_ppfTrain, m_iNumObs);
    CVector::free(m_pfQuery);
    CVector::free(m_pfHist);
    CVector::free(m_piHistLabel);
    CVector::free(m_pfNormScale);
    CVector::free(m_pfNormSub);
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kNoError, m_bIsInitialized, m_iNumObs, m_pfDist, m_pfHist, m_pfNormScale, m_pfNormSub, m_pfQuery, m_piClassLabels, m_piHistLabel, m_piSortIdx, and m_ppfTrain.
Referenced by ~CKnn().
setParamK()
Error_t CKnn::setParamK (int iK = 3)
sets the number of neighbors K
Parameters
iK number of nearest neighbors taken into consideration
Returns
Error_t
Definition at line 107 of file ToolSimpleKnn.cpp.
{
    if (iK <= 0)
        return Error_t::kFunctionInvalidArgsError;
    m_iK = iK;
    CVector::free(m_pfHist);
    CVector::free(m_piHistLabel);
    CVector::alloc(m_pfHist, m_iK);
    CVector::alloc(m_piHistLabel, m_iK);
    return Error_t::kNoError;
}
References CVector::alloc(), CVector::free(), kFunctionInvalidArgsError, kNoError, m_iK, m_pfHist, and m_piHistLabel.
Member Data Documentation
m_bIsInitialized
bool CKnn::m_bIsInitialized = false private
indicates if instance has been properly initialized
Definition at line 101 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
m_iK
int CKnn::m_iK = 3 private
number of neighbors for classification
Definition at line 86 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), countMaxima_(), getParamK(), init(), and setParamK().
m_iNumFeatures
int CKnn::m_iNumFeatures = 0 private
number of features
Definition at line 83 of file ToolSimpleKnn.h.
Referenced by classify(), and init().
m_iNumObs
int CKnn::m_iNumObs = 0 private
number of training observations
Definition at line 84 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
m_pfDist
float* CKnn::m_pfDist = 0 private
preallocated vector for distance of query to all data points
Definition at line 91 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), init(), and reset().
m_pfHist
float* CKnn::m_pfHist = 0 private
preallocated vector for the histogram of nearest neighbors
Definition at line 95 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), countMaxima_(), init(), reset(), and setParamK().
m_pfNormScale
float* CKnn::m_pfNormScale = 0 private
scaling constant for normalization (length m_iNumFeatures)
Definition at line 98 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
m_pfNormSub
float* CKnn::m_pfNormSub = 0 private
offset for normalization (length m_iNumFeatures)
Definition at line 99 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
m_pfQuery
float* CKnn::m_pfQuery = 0 private
preallocated vector for the normalized query
Definition at line 92 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
m_piClassLabels
int* CKnn::m_piClassLabels = 0 private
ground truth train labels
Definition at line 89 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), init(), and reset().
m_piHistLabel
int* CKnn::m_piHistLabel = 0 private
preallocated vector holding the histogram class labels
Definition at line 96 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), countMaxima_(), init(), reset(), and setParamK().
m_piSortIdx
int* CKnn::m_piSortIdx = 0 private
preallocated vector for the resorted class indices
Definition at line 93 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), init(), and reset().
m_ppfTrain
float** CKnn::m_ppfTrain = 0 private
train data (m_iNumObs X m_iNumFeatures)
Definition at line 88 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
The documentation for this class was generated from the following files:
ToolSimpleKnn.h
ToolSimpleKnn.cpp