ACA: CSeqFeatureSel Class Reference
CSeqFeatureSel Class Reference
computation of sequential feature forward selection
#include <ToolSeqFeatureSel.h>
Public Member Functions
CSeqFeatureSel (void)
virtual ~CSeqFeatureSel (void)
Error_t init (int iNumFeatures, int iNumObs)
Error_t process (const float *const *const ppfFeatures, const int *piClassIndices)
Error_t getResult (int *piFeatureIndices, float *pfAccuracyPerStep=0)
Error_t reset ()
Private Member Functions
CSeqFeatureSel (const CSeqFeatureSel &that)
disallow copy construction
CSeqFeatureSel & operator= (const CSeqFeatureSel &c)
bool isFeatureAlreadySelected_ (int iFeatureIdx) const
Private Attributes
int m_iNumFeatures = 0
number of features
int m_iNumObs = 0
number of neighbors for classification
float ** m_ppfTrain = 0
train data (m_iNumObs X m_iNumFeatures)
float * m_pfAccuracy = 0
resulting best accuracy over number of features
int * m_piSelFeatures = 0
resulting selected feature indices
CKnn * m_pCClassifier = 0
handle to wrapped classifier
CLeaveOneOutCrossVal * m_pCCv = 0
cross validation instance
bool m_bIsInitialized = false
indicates if instance has been properly initialized
bool m_bWasProcessed = false
indicates if process function had been successfully executed
Detailed Description
computation of sequential feature forward selection
Definition at line 14 of file ToolSeqFeatureSel.h.
Constructor & Destructor Documentation
CSeqFeatureSel() [1/2]
CSeqFeatureSel::CSeqFeatureSel (void) inline
Definition at line 17 of file ToolSeqFeatureSel.h.
{};
~CSeqFeatureSel()
CSeqFeatureSel::~CSeqFeatureSel (void) virtual
Definition at line 9 of file ToolSeqFeatureSel.cpp.
{ reset(); }
References reset().
CSeqFeatureSel() [2/2]
CSeqFeatureSel::CSeqFeatureSel (const CSeqFeatureSel & that) private
disallow copy construction
Member Function Documentation
getResult()
Error_t CSeqFeatureSel::getResult (int * piFeatureIndices, float * pfAccuracyPerStep = 0)
writes results after processing
Parameters
piFeatureIndices sorted feature indices, best first (dimensions iNumFeatures)
pfAccuracyPerStep best accuracy for each combination (1 feature, 2 features, 3 features...)
Returns
Error_t
Definition at line 105 of file ToolSeqFeatureSel.cpp.
{
    if (!m_bWasProcessed)
        return Error_t::kFunctionIllegalCallError;
    if (!piFeatureIndices)
        return Error_t::kFunctionInvalidArgsError;
    CVector::copy(piFeatureIndices, m_piSelFeatures, m_iNumFeatures);
    if (pfAccuracyPerStep)
        CVector::copy(pfAccuracyPerStep, m_pfAccuracy, m_iNumFeatures);
    return Error_t::kNoError;
}
References CVector::copy(), m_bWasProcessed, m_iNumFeatures, m_pfAccuracy, and m_piSelFeatures.
init()
Error_t CSeqFeatureSel::init (int iNumFeatures, int iNumObs)
initializes SeqFeatureSel instance
Parameters
iNumFeatures number of features (rows in the input matrix)
iNumObs number of observations (columns in the feature matrix)
Returns
Error_t
Definition at line 11 of file ToolSeqFeatureSel.cpp.
{
    if (iNumFeatures <= 0 || iNumObs <= 1)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    m_iNumFeatures = iNumFeatures;
    m_iNumObs = iNumObs;
    m_pCClassifier = new CKnn();
    m_pCClassifier->setParamK(1);
    m_pCCv = new CLeaveOneOutCrossVal();
    CVector::alloc(m_piSelFeatures, m_iNumFeatures);
    CVector::alloc(m_pfAccuracy, m_iNumFeatures);
    CMatrix::alloc(m_ppfTrain, m_iNumFeatures, m_iNumObs);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), m_bIsInitialized, m_iNumFeatures, m_iNumObs, m_pCClassifier, m_pCCv, m_pfAccuracy, m_piSelFeatures, m_ppfTrain, reset(), and CKnn::setParamK().
isFeatureAlreadySelected_()
bool CSeqFeatureSel::isFeatureAlreadySelected_ (int iFeatureIdx) const inline private
return true if feature index is already in the list of selected features
Parameters
iFeatureIdx index of the feature
Returns
bool
Definition at line 56 of file ToolSeqFeatureSel.h.
    {
        for (auto v = 0; v < m_iNumFeatures; v++)
        {
            if (iFeatureIdx == m_piSelFeatures[v])
                return true;
            if (m_piSelFeatures[v] < 0)
                return false;
        }
        return false;
    }
References m_iNumFeatures, and m_piSelFeatures.
Referenced by process().
operator=()
CSeqFeatureSel & CSeqFeatureSel::operator= (const CSeqFeatureSel & c) private
process()
Error_t CSeqFeatureSel::process (const float *const *const ppfFeatures, const int * piClassIndices)
selects the featyres
Parameters
ppfFeatures feature data for 'training' (dimensions iNumFeatures X iNumObs)
piClassIndices ground truth class index for each observation
Returns
Error_t
Definition at line 35 of file ToolSeqFeatureSel.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    if (!ppfFeatures || !piClassIndices)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfFeatures[0])
        return Error_t::kFunctionInvalidArgsError;
    int iNumFeatures2Select = m_iNumFeatures;
    int iNumSelFeatures = 0;
    CVector::setValue(m_piSelFeatures, -1, m_iNumFeatures);
    // find single best feature
    for (auto v = 0; v < m_iNumFeatures; v++)
    {
        float fAcc = 0;
        m_pCCv->init(1, m_iNumObs, m_pCClassifier);
        fAcc = m_pCCv->process(&ppfFeatures[v], piClassIndices);
        if (fAcc >= m_pfAccuracy[0])
        {
            m_pfAccuracy[0] = fAcc;
            m_piSelFeatures[0] = v;
        }
    }
    // copy best feature value to the first row of our feature matrix
    CVector::copy(m_ppfTrain[0], ppfFeatures[m_piSelFeatures[0]], m_iNumObs);
    iNumSelFeatures++;
    // iterate until target number of features is reached
    for (auto f = iNumSelFeatures; f < iNumFeatures2Select; f++)
    {
        // iterate over all features not yet selected
        for (auto v = 0; v < m_iNumFeatures; v++)
        {
            float fAcc = 0;
            if (isFeatureAlreadySelected_(v))
                continue;
            // add current feature v to internal feature matrix
            CVector::copy(m_ppfTrain[iNumSelFeatures], ppfFeatures[v], m_iNumObs);
            m_pCCv->init(iNumSelFeatures + 1, m_iNumObs, m_pCClassifier);
            //accuracy of selected features plus current feature f
            fAcc = m_pCCv->process(m_ppfTrain, piClassIndices);
            if (fAcc >= m_pfAccuracy[iNumSelFeatures])
            {
                m_pfAccuracy[iNumSelFeatures] = fAcc;
                m_piSelFeatures[iNumSelFeatures] = v;
            }
        }
        assert(m_piSelFeatures[iNumSelFeatures] >= 0 && m_piSelFeatures[iNumSelFeatures] < m_iNumFeatures);
        CVector::copy(m_ppfTrain[iNumSelFeatures], ppfFeatures[m_piSelFeatures[iNumSelFeatures]], m_iNumObs);
        iNumSelFeatures++;
    }
    m_bWasProcessed = true;
    return Error_t::kNoError;
}
References CVector::copy(), CLeaveOneOutCrossVal::init(), isFeatureAlreadySelected_(), m_bIsInitialized, m_bWasProcessed, m_iNumFeatures, m_iNumObs, m_pCClassifier, m_pCCv, m_pfAccuracy, m_piSelFeatures, m_ppfTrain, CLeaveOneOutCrossVal::process(), and CVector::setValue().
reset()
Error_t CSeqFeatureSel::reset ()
resets SeqFeatureSel instance
Returns
Error_t
Definition at line 119 of file ToolSeqFeatureSel.cpp.
{
    m_bIsInitialized = false;
    m_bWasProcessed = false;
    CVector::free(m_piSelFeatures);
    CVector::free(m_pfAccuracy);
    CMatrix::free(m_ppfTrain, m_iNumFeatures);
    delete m_pCClassifier;
    m_pCClassifier = 0;
    delete m_pCCv;
    m_pCCv = 0;
    m_iNumFeatures = 0;
    m_iNumObs = 0;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), m_bIsInitialized, m_bWasProcessed, m_iNumFeatures, m_iNumObs, m_pCClassifier, m_pCCv, m_pfAccuracy, m_piSelFeatures, and m_ppfTrain.
Referenced by init(), and ~CSeqFeatureSel().
Member Data Documentation
m_bIsInitialized
bool CSeqFeatureSel::m_bIsInitialized = false private
indicates if instance has been properly initialized
Definition at line 82 of file ToolSeqFeatureSel.h.
Referenced by init(), process(), and reset().
m_bWasProcessed
bool CSeqFeatureSel::m_bWasProcessed = false private
indicates if process function had been successfully executed
Definition at line 83 of file ToolSeqFeatureSel.h.
Referenced by getResult(), process(), and reset().
m_iNumFeatures
int CSeqFeatureSel::m_iNumFeatures = 0 private
number of features
Definition at line 69 of file ToolSeqFeatureSel.h.
Referenced by getResult(), init(), isFeatureAlreadySelected_(), process(), and reset().
m_iNumObs
int CSeqFeatureSel::m_iNumObs = 0 private
number of neighbors for classification
Definition at line 70 of file ToolSeqFeatureSel.h.
Referenced by init(), process(), and reset().
m_pCClassifier
CKnn* CSeqFeatureSel::m_pCClassifier = 0 private
handle to wrapped classifier
Definition at line 78 of file ToolSeqFeatureSel.h.
Referenced by init(), process(), and reset().
m_pCCv
CLeaveOneOutCrossVal* CSeqFeatureSel::m_pCCv = 0 private
cross validation instance
Definition at line 79 of file ToolSeqFeatureSel.h.
Referenced by init(), process(), and reset().
m_pfAccuracy
float* CSeqFeatureSel::m_pfAccuracy = 0 private
resulting best accuracy over number of features
Definition at line 74 of file ToolSeqFeatureSel.h.
Referenced by getResult(), init(), process(), and reset().
m_piSelFeatures
int* CSeqFeatureSel::m_piSelFeatures = 0 private
resulting selected feature indices
Definition at line 76 of file ToolSeqFeatureSel.h.
Referenced by getResult(), init(), isFeatureAlreadySelected_(), process(), and reset().
m_ppfTrain
float** CSeqFeatureSel::m_ppfTrain = 0 private
train data (m_iNumObs X m_iNumFeatures)
Definition at line 72 of file ToolSeqFeatureSel.h.
Referenced by init(), process(), and reset().
The documentation for this class was generated from the following files:
ToolSeqFeatureSel.h
ToolSeqFeatureSel.cpp