ACA: CKnn Class Reference
CKnn Class Reference
computation of k nearest neighbor
#include <ToolSimpleKnn.h>
Public Member Functions
CKnn (void)
virtual ~CKnn (void)
Error_t init (int iNumFeatures, int iNumObs) override
Error_t train (const float *const *const ppfTrainFeatures, const int *piTrainClassIndices, CClassifierBase::Normalization_t eNorm=CClassifierBase::kNoNormalization) override
Error_t reset () override
Error_t setParamK (int iK=3)
int getParamK () const
int classify (const float *pfQuery) override
virtual Error_t init (int iNumFeatures, int iNumObs)=0
virtual Error_t train (const float *const *const ppfTrainFeatures, const int *piTrainClassIndices, Normalization_t eNorm=kNoNormalization)=0
virtual Error_t reset ()=0
virtual int classify (const float *pfQuery)=0
Private Member Functions
CKnn (const CKnn &that)
disallow copy construction
CKnn & operator= (const CKnn &c)
void buildHistogram_ (bool bUseDistance)
int countMaxima_ ()
Private Attributes
int m_iNumFeatures = 0
number of features
int m_iNumObs = 0
number of training observations
int m_iK = 3
number of neighbors for classification
float ** m_ppfTrain = 0
train data (m_iNumObs X m_iNumFeatures)
int * m_piClassLabels = 0
ground truth train labels
float * m_pfSortDist = 0
preallocated vector for distance of query to all data points
float * m_pfQuery = 0
preallocated vector for the normalized query
int * m_piSortIdx = 0
preallocated vector for the resorted class indices
float * m_pfHist = 0
preallocated vector for the histogram of nearest neighbors
int * m_piHistLabel = 0
preallocated vector holding the histogram class labels
int * m_piHistCount = 0
number of entries per class (for weighted hist)
bool m_bIsInitialized = false
indicates if instance has been properly initialized
Additional Inherited Members
Public Types inherited from CClassifierBase
enum Normalization_t { kNoNormalization , kZscoreNormalization , kMinmaxNormalization , kNumNormModes }
Static Public Attributes inherited from CClassifierBase
static const int kIllegalClassLabel = -1111111111
indicates something went wrong (this number should not be used as a class label)
Protected Member Functions inherited from CClassifierBase
virtual ~CClassifierBase ()
virtual void compNormConstants (const float *const *const ppfTrainFeatures, int iNumFeatures, int iNumObs, Normalization_t eNorm)
virtual void normalizeVector (float *pfQuery, int iNumFeatures)
Protected Attributes inherited from CClassifierBase
float * m_pfNormScale = 0
scaling constant for normalization (length m_iNumFeatures)
float * m_pfNormSub = 0
offset for normalization (length m_iNumFeatures)
Detailed Description
computation of k nearest neighbor
Definition at line 12 of file ToolSimpleKnn.h.
Constructor & Destructor Documentation
CKnn() [1/2]
CKnn::CKnn (void) inline
Definition at line 15 of file ToolSimpleKnn.h.
{};
~CKnn()
CKnn::~CKnn (void) virtual
Definition at line 10 of file ToolSimpleKnn.cpp.
{
    reset();
}
References reset().
CKnn() [2/2]
CKnn::CKnn (const CKnn & that) private
disallow copy construction
Member Function Documentation
buildHistogram_()
void CKnn::buildHistogram_ (bool bUseDistance) private
Definition at line 148 of file ToolSimpleKnn.cpp.
{
    int iNumLabelsInK = 0;
    // init
    CVector::setZero(m_pfHist, m_iK);
    CVector::setZero(m_piHistCount, m_iK);
    CVector::setValue(m_piHistLabel, kIllegalClassLabel, m_iK);
    // set first candidate (lowest distance)
    m_piHistLabel[0] = m_piClassLabels[m_piSortIdx[0]];
    m_pfHist[0] += bUseDistance ? m_pfSortDist[0] : 1.F;
    m_piHistCount[0]++;
    iNumLabelsInK++;
    for (auto k = 1; k < m_iK; k++)
    {
        bool bContinue = false;
        for (auto l = 0; l < iNumLabelsInK; l++)
        {
            // check if current label k belongs to existing class
            if (m_piHistLabel[l] == m_piClassLabels[m_piSortIdx[k]])
            {
                m_pfHist[l] += bUseDistance ? m_pfSortDist[k] : 1.F;
                m_piHistCount[l]++;
                bContinue = true;
                break;
            }
        }
        if (bContinue)
            continue;
        // create new hist class
        m_piHistLabel[iNumLabelsInK] = m_piClassLabels[m_piSortIdx[k]];
        m_pfHist[iNumLabelsInK] += bUseDistance ? m_pfSortDist[k] : 1.F;
        m_piHistCount[iNumLabelsInK]++;
        iNumLabelsInK++;
    }
    // distance-based metrics
    if (bUseDistance)
    {
        // scale by number of entries in histogram
        for (auto k = 0; k < iNumLabelsInK; k++)
            if (m_piHistCount[k] > 0) m_pfHist[k] /= m_piHistCount[k];
        // invert so that distance becomes similarity
        float fMax = CVector::getMax(m_pfHist, iNumLabelsInK);
        if (fMax > 0)
            CVector::mulC_I(m_pfHist, -1.F / fMax, iNumLabelsInK);
        CVector::addC_I(m_pfHist, 1.F, iNumLabelsInK);
    }
}
References CVector::addC_I(), CVector::getMax(), CClassifierBase::kIllegalClassLabel, m_iK, m_pfHist, m_pfSortDist, m_piClassLabels, m_piHistCount, m_piHistLabel, m_piSortIdx, CVector::mulC_I(), CVector::setValue(), and CVector::setZero().
Referenced by classify().
classify()
int CKnn::classify (const float * pfQuery) override virtual
classifies a new query vector
Parameters
pfQuery vector of length iNumFeatures to classify
Returns
int class label of most likely class (returns CClassifierBase::kIllegalClassLabel in case of error)
< remember m_iK
Implements CClassifierBase.
Definition at line 113 of file ToolSimpleKnn.cpp.
{
    if (!pfQuery || !m_bIsInitialized)
        return kIllegalClassLabel;
    // normalize
    CVector::copy(m_pfQuery, pfQuery, m_iNumFeatures);
    normalizeVector(m_pfQuery, m_iNumFeatures);
    // compute distance to all training observations
    for (auto n = 0; n < m_iNumObs; n++)
        m_pfSortDist[n] = CVector::distEuclidean(pfQuery, m_ppfTrain[n], m_iNumFeatures);
    // sort distances
    CVector::sort_I(m_pfSortDist, m_piSortIdx, m_iNumObs);
    // take care of weird scenarios
    if (m_iK > m_iNumObs)
        m_iK = m_iNumObs;
    // create histogram
    buildHistogram_(false);
    // handle multiple maxima (first, use distances, then, reduce K)
    int iK = m_iK;  //!< remember m_iK
    while (countMaxima_() > 1)
    {
        buildHistogram_(true);
        m_iK--;
    }
    m_iK = iK;
    return m_piHistLabel[0];
}
References buildHistogram_(), CVector::copy(), countMaxima_(), CVector::distEuclidean(), CClassifierBase::kIllegalClassLabel, m_bIsInitialized, m_iK, m_iNumFeatures, m_iNumObs, m_pfQuery, m_pfSortDist, m_piHistLabel, m_piSortIdx, m_ppfTrain, CClassifierBase::normalizeVector(), and CVector::sort_I().
countMaxima_()
int CKnn::countMaxima_ () private
Definition at line 201 of file ToolSimpleKnn.cpp.
{
    int iNumMax = 0;
    float fMax = 0;
    long long iMax = 0;
    // find first max
    CVector::findMax(m_pfHist, fMax, iMax, m_iK);
    CUtil::swap(m_pfHist[iNumMax], m_pfHist[iMax]);
    CUtil::swap(m_piHistLabel[iNumMax], m_piHistLabel[iMax]);
    iNumMax++;
    for (auto k = 1; k < m_iK; k++)
    {
        // check for others
        if (m_pfHist[k] >= fMax)
        {
            CUtil::swap(m_pfHist[iNumMax], m_pfHist[k]);
            CUtil::swap(m_piHistLabel[iNumMax], m_piHistLabel[k]);
            iNumMax++;
        }
    }
    return iNumMax;
}
References CVector::findMax(), m_iK, m_pfHist, m_piHistLabel, and CUtil::swap().
Referenced by classify().
getParamK()
int CKnn::getParamK () const
returns the parameter K
Returns
int iK
Definition at line 108 of file ToolSimpleKnn.cpp.
{
    return m_iK;
}
References m_iK.
init()
Error_t CKnn::init (int iNumFeatures, int iNumObs) override virtual
initializes Knn instance
Parameters
iNumFeatures number of features (rows in the input matrix)
iNumObs number of observations (columns in the feature matrix)
Returns
Error_t
Implements CClassifierBase.
Definition at line 15 of file ToolSimpleKnn.cpp.
{
    if (iNumFeatures <= 0 || iNumObs <= 1)
        return Error_t::kFunctionInvalidArgsError;
    reset();
    m_iNumObs = iNumObs;
    m_iNumFeatures = iNumFeatures;
    CVector::alloc(m_piClassLabels, m_iNumObs);
    CVector::alloc(m_piSortIdx, m_iNumObs);
    CVector::alloc(m_pfSortDist, m_iNumObs);
    CVector::alloc(m_pfQuery, m_iNumFeatures);
    CVector::alloc(m_pfNormScale, m_iNumFeatures);
    CVector::alloc(m_pfNormSub, m_iNumFeatures);
    CMatrix::alloc(m_ppfTrain, m_iNumObs, m_iNumFeatures);
    CVector::alloc(m_pfHist, m_iK);
    CVector::alloc(m_piHistLabel, m_iK);
    CVector::alloc(m_piHistCount, m_iK);
    m_bIsInitialized = true;
    return Error_t::kNoError;
}
References CVector::alloc(), CMatrix::alloc(), kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iK, m_iNumFeatures, m_iNumObs, m_pfHist, CClassifierBase::m_pfNormScale, CClassifierBase::m_pfNormSub, m_pfQuery, m_pfSortDist, m_piClassLabels, m_piHistCount, m_piHistLabel, m_piSortIdx, m_ppfTrain, and reset().
operator=()
CKnn & CKnn::operator= (const CKnn & c) private
reset()
Error_t CKnn::reset (void) override virtual
resets Knn instance
Returns
Error_t
Implements CClassifierBase.
Definition at line 44 of file ToolSimpleKnn.cpp.
{
    CVector::free(m_piClassLabels);
    CVector::free(m_piSortIdx);
    CVector::free(m_pfSortDist);
    CVector::free(m_pfQuery);
    CMatrix::free(m_ppfTrain, m_iNumObs);
    CVector::free(m_pfHist);
    CVector::free(m_piHistLabel);
    CVector::free(m_piHistCount);
    CVector::free(m_pfNormScale);
    CVector::free(m_pfNormSub);
    m_iNumObs = 0;
    m_iNumFeatures = 0;
    m_bIsInitialized = false;
    return Error_t::kNoError;
}
References CVector::free(), CMatrix::free(), kNoError, m_bIsInitialized, m_iNumFeatures, m_iNumObs, m_pfHist, CClassifierBase::m_pfNormScale, CClassifierBase::m_pfNormSub, m_pfQuery, m_pfSortDist, m_piClassLabels, m_piHistCount, m_piHistLabel, m_piSortIdx, and m_ppfTrain.
Referenced by init(), and ~CKnn().
setParamK()
Error_t CKnn::setParamK (int iK = 3)
sets the number of neighbors K
Parameters
iK number of nearest neighbors taken into consideration
Returns
Error_t
Definition at line 89 of file ToolSimpleKnn.cpp.
{
    if (iK <= 0)
        return Error_t::kFunctionInvalidArgsError;
    if (m_iK == iK)
        return Error_t::kNoError;
    CVector::free(m_pfHist);
    CVector::free(m_piHistLabel);
    CVector::free(m_piHistCount);
    m_iK = iK;
    CVector::alloc(m_pfHist, m_iK);
    CVector::alloc(m_piHistLabel, m_iK);
    CVector::alloc(m_piHistCount, m_iK);
    return Error_t::kNoError;
}
References CVector::alloc(), CVector::free(), kFunctionInvalidArgsError, kNoError, m_iK, m_pfHist, m_piHistCount, and m_piHistLabel.
Referenced by CSeqFeatureSel::init().
train()
Error_t CKnn::train (const float *const *const ppfTrainFeatures, const int * piTrainClassIndices, CClassifierBase::Normalization_t eNorm = CClassifierBase::kNoNormalization) override virtual
initializes Knn instance
Parameters
ppfTrainFeatures feature data for 'training' (dimensions iNumFeatures X iNumObs)
piTrainClassIndices ground truth class index for each observation
eNorm specification of what normalization should be applied to the feature data
Returns
Error_t
Implements CClassifierBase.
Definition at line 66 of file ToolSimpleKnn.cpp.
{
    if (!ppfTrainFeatures || !piTrainClassIndices)
        return Error_t::kFunctionInvalidArgsError;
    if (!ppfTrainFeatures[0])
        return Error_t::kFunctionInvalidArgsError;
    if (!m_bIsInitialized)
        return Error_t::kFunctionIllegalCallError;
    CVector::copy(m_piClassLabels, piTrainClassIndices, m_iNumObs);
    // note we store this transposed - that's easier for the distance computation
    CMatrix::transpose(m_ppfTrain, ppfTrainFeatures, m_iNumFeatures, m_iNumObs);
    // normalize features
    compNormConstants(ppfTrainFeatures, m_iNumFeatures, m_iNumObs, eNorm);
    for (auto n = 0; n < m_iNumObs; n++)
        normalizeVector(m_ppfTrain[n], m_iNumFeatures);
    return Error_t::kNoError;
}
References CClassifierBase::compNormConstants(), CVector::copy(), kFunctionIllegalCallError, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_iNumFeatures, m_iNumObs, m_piClassLabels, m_ppfTrain, CClassifierBase::normalizeVector(), and CMatrix::transpose().
Member Data Documentation
m_bIsInitialized
bool CKnn::m_bIsInitialized = false private
indicates if instance has been properly initialized
Definition at line 81 of file ToolSimpleKnn.h.
Referenced by classify(), init(), reset(), and train().
m_iK
int CKnn::m_iK = 3 private
number of neighbors for classification
Definition at line 68 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), countMaxima_(), getParamK(), init(), and setParamK().
m_iNumFeatures
int CKnn::m_iNumFeatures = 0 private
number of features
Definition at line 65 of file ToolSimpleKnn.h.
Referenced by classify(), init(), reset(), and train().
m_iNumObs
int CKnn::m_iNumObs = 0 private
number of training observations
Definition at line 66 of file ToolSimpleKnn.h.
Referenced by classify(), init(), reset(), and train().
m_pfHist
float* CKnn::m_pfHist = 0 private
preallocated vector for the histogram of nearest neighbors
Definition at line 77 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), countMaxima_(), init(), reset(), and setParamK().
m_pfQuery
float* CKnn::m_pfQuery = 0 private
preallocated vector for the normalized query
Definition at line 74 of file ToolSimpleKnn.h.
Referenced by classify(), init(), and reset().
m_pfSortDist
float* CKnn::m_pfSortDist = 0 private
preallocated vector for distance of query to all data points
Definition at line 73 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), init(), and reset().
m_piClassLabels
int* CKnn::m_piClassLabels = 0 private
ground truth train labels
Definition at line 71 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), init(), reset(), and train().
m_piHistCount
int* CKnn::m_piHistCount = 0 private
number of entries per class (for weighted hist)
Definition at line 79 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), init(), reset(), and setParamK().
m_piHistLabel
int* CKnn::m_piHistLabel = 0 private
preallocated vector holding the histogram class labels
Definition at line 78 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), countMaxima_(), init(), reset(), and setParamK().
m_piSortIdx
int* CKnn::m_piSortIdx = 0 private
preallocated vector for the resorted class indices
Definition at line 75 of file ToolSimpleKnn.h.
Referenced by buildHistogram_(), classify(), init(), and reset().
m_ppfTrain
float** CKnn::m_ppfTrain = 0 private
train data (m_iNumObs X m_iNumFeatures)
Definition at line 70 of file ToolSimpleKnn.h.
Referenced by classify(), init(), reset(), and train().
The documentation for this class was generated from the following files:
ToolSimpleKnn.h
ToolSimpleKnn.cpp