ACA: Catch::IGeneratorTracker Struct Reference
Catch::IGeneratorTracker Struct Reference abstract
#include <catch.hpp>
Public Member Functions
virtual ~IGeneratorTracker ()
virtual auto hasGenerator () const -> bool=0
virtual auto getGenerator () const -> Generators::GeneratorBasePtr const &=0
virtual void setGenerator (Generators::GeneratorBasePtr &&generator)=0
Detailed Description
Definition at line 3859 of file catch.hpp.
Constructor & Destructor Documentation
~IGeneratorTracker()
virtual Catch::IGeneratorTracker::~IGeneratorTracker () virtual
Member Function Documentation
getGenerator()
virtual auto Catch::IGeneratorTracker::getGenerator () const -> Generators::GeneratorBasePtr const & pure virtual
Referenced by Catch::Generators::generate().
hasGenerator()
virtual auto Catch::IGeneratorTracker::hasGenerator () const -> bool pure virtual
Referenced by Catch::Generators::generate().
setGenerator()
virtual void Catch::IGeneratorTracker::setGenerator (Generators::GeneratorBasePtr && generator) pure virtual
References Catch::throw_exception().
Referenced by Catch::Generators::generate().
The documentation for this struct was generated from the following file:
catch.hpp