name: all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${ { matrix.config.name } }
    runs-on: ${ { matrix.config.os } }
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "ubuntu latest gcc", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: ${{env.BUILD_TYPE}}, cc: "gcc", cxx: "g++"
          }
        - {
            name: "macos latest clang", artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: ${{env.BUILD_TYPE}}, cc: "clang", cxx: "clang++"
          }
    steps:
    - uses: actions/checkout@v2

    - name: configure 
      run: cmake -B ${{github.workspace}}/bld -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_TESTS=1

    - name: build
      run: cmake --build ${{github.workspace}}/bld --config ${{env.BUILD_TYPE}}

    - name: test
      working-directory: ${{github.workspace}}/bld
      run: ctest -C ${{env.BUILD_TYPE}}
