name: Docu Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-docs:
    name: builds docs and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake to generate doxygen config file
      run: cmake -B ${{github.workspace}}/build

    - name: Doxygen
      uses: mattnotmitt/doxygen-action@edge
      with:
        working-directory: ./build
        doxyfile-path: docs/doxy.config
 
    # store the doc files
    - name: Upload Output Directory
      uses: actions/upload-artifact@v3
      with:
        name: doc-files
        path: doc
        retention-days: 1 
        
  copy:
    name: copies docs to gh-pages
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    # prepare the doc files
    - name: Download Output Directory
      uses: actions/download-artifact@v3
      with:
        name: doc-files
        path: docs

    # commit the doc files
    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: Alexander Lerch
        author_email: alexander.lerch@gatech.edu
        message: 'auto-update docs'
        add: '["docs/*"]'